{
  "hash": "24b43116ef99a939c4a22cea1622277a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"1. Inleiding: Waarom Statistiek?\"\nauthor: \"Lieven Clement\"\ndate: \"statOmics, Ghent University (https://statomics.github.io)\"\nformat:\n  html:\n    toc: true\n    number-sections: true\n    theme: cosmo\n    highlight-style: tango\n    code-tools: true\n    embed-resources: true\n---\n\n# Introductie\n\n\n\n![](../figures/ways_to_capture_b2b_customer_data_5bacd2dbe1a09.png)\n![](../figures/wpGraph.jpeg)\n![](../figures/mvpc.jpeg)\n\n- We leven in het big data era\n- Gegevens over locatie, surfgedrag, aankoopgedrag, sociale media\n- Wetenschap: expressie meten van duizenden genen, eiwitten,... voor elk subject\n- Chemische proces controle: groot aantal sensoren die continu een proces meten zodat het proces kan worden bijgestuurd\n- Data driven journalism\n- ...\n\nStatistiek is de wetenschap om te leren uit empirische gegevens\n\nStatistische geletterdheid is cruciaal om resultaten en publicaties kritisch te kunnen interpreteren.\n\n***\n\n# Case study: oksel microbiome\n\n\n![](https://images.vrt.be/width1280/2018/06/27/4e72098d-7a0d-11e8-abcc-02b7b76bf47f.jpg){width=70%}\n\n- <https://www.vrt.be/vrtnws/nl/2018/10/22/gezocht-mensen-met-penetrante-lijfgeur-om-probiotische-deodor/>\n- <https://youtu.be/9RIFyqLXdVw>\n\n***\n\n- Okselgeur wordt niet veroorzaakt door het zweet zelf. De geur is afkomstig van specificiek micro-organismen van de groep *Corynebacterium spp.* die het zweet metaboliseren. *Staphylococcus spp.* zijn een andere groep bacteriën die ook abundant zijn in het microbiome van de oksel die zweet metaboliseren naar metabolieten die niet stinken.\n\n- De CMET-groep aan UGENT doet onderzoek naar het transplanteren van de microbiële gemeenschap, het microbiome, om mensen van geurende oksels af te helpen.  \n\n- Voorgestelde therapie\n  \t1. Verwijder het oksel microbiome met antibiotica\n    2. Beïnvloed het oksel microbiome door microbiome te transplanteren van een individue die geen geurende oksels heeft (https://youtu.be/9RIFyqLXdVw)\n\n\n***\n\n## Proefopzet (experimental design)\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](01-intro_files/figure-html/unnamed-chunk-2-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n***\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](01-intro_files/figure-html/unnamed-chunk-3-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n***\n\n- Experiment:\n\n    - 20 personen worden at random uit de populatie getrokken van personen met een okselgeur: steekproef representatief voor populatie!\n\n    - de personen worden at random verdeeld over twee behandelingsgroepen:\n\n        - placebo (enkel antibiotica)\n        - transplantie (antibiotica en microbiële transplantatie).\n        - Randomisatie (at random toewijzen van proefpersonen aan de behandeling) is belangrijk om ervoor te zorgen dat de groepen vergelijkbaar zijn.\n\n    - Het microbiome wordt bemonsterd 6 weken na de behandeling.\n    - The relative abundantie van *Staphylococcus spp.* op *Corynebacterium spp.* + *Staphylococcus spp.* in het microbiome wordt gemeten via DGGE (*Denaturing Gradient Gel Electrophoresis*).\n\n***\n\nDGGE\n\n![](https://journals.plos.org/plosone/article/figure/image?size=large&download=&id=10.1371/journal.pone.0070538.g001){width=70%}\n\n<https://doi.org/10.1371/journal.pone.0070538>\n\n***\n\nVertaal onderzoeksvraag naar iets wat we kunnen quantificeren: Is er een verschil in relatieve abundantie van *Staphylococcus spp.* in het microbiome van de placebo groep en de transplantatie\n\n***\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](01-intro_files/figure-html/unnamed-chunk-4-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n***\n\n## Data Exploratie en beschrijvende statistiek\n\n\n- Data exploratie is heel belangrijk om inzicht te krijgen in de data en is een essentiële eerste stap om te leren uit data.\n- Het wordt vaak ondergewaardeerd of over het hoofd gezien.\n\n***\n\n### Importeer de data\n\n- Data in deze cursus wordt verwerkt via het statistisch software pakket R.\n- Dit pakket laat toe om te leren uit data.\n- In deze cursus gaan we data eerst exploreren om inzicht te verwerven in de gegevens om die vervolgens statistisch te verwerken.\n- Vooraleer we hiermee van start kunnen gaan moeten we de data eerst importeren in R.\n\n- Via het volgende commando kunnen we enkele regels van een data bestand inlezen om de structuur van het data bestand te weten te komen.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nread_lines(\"https://raw.githubusercontent.com/statOmics/sbc/master/data/armpit.csv\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"trt,rel\"                       \"placebo,54.99207606973059\"    \n [3] \"placebo,31.84466019417476\"     \"placebo,41.09947643979057\"    \n [5] \"placebo,59.52063914780293\"     \"placebo,63.573407202216075\"   \n [7] \"placebo,41.48648648648649\"     \"placebo,30.44041450777202\"    \n [9] \"placebo,42.95676429567643\"     \"placebo,41.7391304347826\"     \n[11] \"placebo,33.896515311510036\"    \"transplant,57.218124341412015\"\n[13] \"transplant,72.50900360144058\"  \"transplant,61.89258312020461\" \n[15] \"transplant,56.690140845070424\" \"transplant,76\"                \n[17] \"transplant,71.7357910906298\"   \"transplant,57.757296466973884\"\n[19] \"transplant,65.1219512195122\"   \"transplant,67.53424657534246\" \n[21] \"transplant,77.55359394703657\" \n```\n\n\n:::\n:::\n\n\n- Gegevens in het bestand zijn door comma's gescheiden.\n- Elke rij bevat de gegevens voor 1 proefpersoon\n- Verschillende variabelen worden gemeten per persoon en zijn van elkaar gescheiden door een comma. Het bestand is csv formaat: \"comma separated values\".\n- We kunnen bestanden met dit formaat inlezen R via het commando read_csv.\n- We slaan de data op in R in het object met naam ap. Hiervoor gebruiken we de `<-` operator.\n- We geven de data tabel terug door het object aan te roepen door zijn naam te typen.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nap <- read_csv(\"https://raw.githubusercontent.com/statOmics/sbc/master/data/armpit.csv\")\nap\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 20 × 2\n   trt          rel\n   <chr>      <dbl>\n 1 placebo     55.0\n 2 placebo     31.8\n 3 placebo     41.1\n 4 placebo     59.5\n 5 placebo     63.6\n 6 placebo     41.5\n 7 placebo     30.4\n 8 placebo     43.0\n 9 placebo     41.7\n10 placebo     33.9\n11 transplant  57.2\n12 transplant  72.5\n13 transplant  61.9\n14 transplant  56.7\n15 transplant  76  \n16 transplant  71.7\n17 transplant  57.8\n18 transplant  65.1\n19 transplant  67.5\n20 transplant  77.6\n```\n\n\n:::\n:::\n\n\n***\n\n### Beschrijvende statistiek\n\n- In artikels en de media worden resultaten uit een steekproef vaak gerapporteerd a.d.h.v. gemiddelde en de standaardafwijking\n\n- We vatten de data eerst samen. We berekenen het gemiddelde en de standaard deviatie (een maat voor de spreiding, zie volgende hoofdstukken).\nWe slaan het resultaat hiervan op in het object apRelSum via `apRelSum <-`.\n\n1. We pipen (via `|>`) het `ap` dataframe naar de `group_by` functie om de data te groeperen per treatment trt: `group_by(trt)`.\n\n2. We pipen het resultaat naar de `summarize_at` function om de \"rel\" variable samen te vatten en berekenen hierbij het gemiddelde en standaardafwijking. Omdat we de data eerst hebben gegroepeerd zullen we het gemiddelde en de standaard deviatie berekenen per groep.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\napRelSum <- ap |>\n  group_by(trt) |>\n  summarize_at(\"rel\",\n               list(mean=mean,\n                    sd=sd\n                    )\n                )\n```\n:::\n\n\nWe tonen vervolgens het resultaat door het object apRelSum aan te roepen\n\n\n::: {.cell}\n\n```{.r .cell-code}\napRelSum\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  trt         mean    sd\n  <chr>      <dbl> <dbl>\n1 placebo     44.2 11.5 \n2 transplant  66.4  7.88\n```\n\n\n:::\n:::\n\n\nWe kunnen ook een tabel in de webpagina of het pdf bestand integreren via het commando kable van het knitr pakket:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::kable(apRelSum)\n```\n\n::: {.cell-output-display}\n\n\n|trt        |     mean|        sd|\n|:----------|--------:|---------:|\n|placebo    | 44.15496| 11.543251|\n|transplant | 66.40127|  7.880175|\n\n\n:::\n:::\n\n\n***\n\n### Grafieken\n\nWe maken in deze cursus gebruik van het pakket `ggplot2` om grafieken te maken.  \nMet de ggplot2 bibliotheek kunnen we gemakkelijk grafieken opbouwen in lagen (layers).\nHierdoor leest de code veel makkelijker.\n\n#### barplot\n\nBar plots worden heel veel gebruikt in artikels om resultaten weer te geven.\n\n1. We pipen de samengevatte data naar de functie `ggplot`. Dat is de basis van elke ggplot.  We selecteren de variabele met de behandeling trt als x variabele en de variabele met naam mean als y-variabele voor de plot.\nWe doen dit steeds via de aesthetics `aes` functie.   `aes(x=trt,y=mean)`\n\n2. We maken een barplot door een laag toe te voegen via de  `geom_bar` function. De statistiek is `stat=\"identity\"` omdat de hoogte van de bar gelijk is aan de waarde voor y (hier het gemiddelde voor de relatieve abundantie).\n\n3. We voegen foutenvlaggen toe om de onzekerheid op het gemiddelde weer te geven.  We doen dit via de `geom_errorbar` functie en specifiëren het minimum en maximum van de error bar. Het `width` argument wordt gebruikt om de breedte van de error bar smaller te maken dan deze van de bar.\n\n\n::: {.cell}\n\n```{.r .cell-code}\napRelSum |>\n  ggplot(aes(x=trt,y=mean)) +\n  geom_bar(stat=\"identity\") +\n  geom_errorbar(aes(ymin=mean-sd,ymax=mean+sd),width=.2) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](01-intro_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n- Is deze plot informatief??\n\n***\n\n#### boxplots\n\nBarplots zijn geen goede grafieken:\n\n- Ze zijn niet informatief\n\n- Ze visulariseren een samenvatting van de data door twee punten: `two point summary`: gemiddelde en de standaard deviatie hierop en kunnen beter in een tabel worden opgenomen.\n\n- Ze laten niet toe om anomalieën in de data zoals meetfouten op te sporen.\n\n- Ze verbruiken veel ruimte, b.v. van nul tot de kleinste waarde voor de relatieve abundantie) waar geen data in ligt.\n\nHet is beter om de data zo ruw mogelijk voor te stellen zodat we inzicht krijgen in de verdeling van de gegevens.\nHiervoor zullen we ondermeer boxplots gebruiken.\n\n***\n\nWe maken nu een boxplot voor de ap data\n\n1. We pipen het `ap` dataframe naar `ggplot`\n2. We selecteren de data voor de plot via `ggplot(aes(x=trt,y=rel))`\n3. We voegen laag toe voor de boxplot dmv de functie `geom_boxplot()`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nap |>  \n  ggplot(aes(x=trt,y=rel)) +\n  geom_boxplot() + \n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](01-intro_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n***\n\nMerk op dat we de plot ook op kunnen slaan als een object.\n\n\n::: {.cell}\n\n```{.r .cell-code}\napBoxplot <- ap |>  \n  ggplot(aes(x=trt,y=rel)) +\n  geom_boxplot() +\n  theme_minimal()\n```\n:::\n\n\nDe plot wordt dan niet gemaakt.\n\nOm de plot weer te geven kunnen we het object aanroepen\n\n\n::: {.cell}\n\n```{.r .cell-code}\napBoxplot\n```\n\n::: {.cell-output-display}\n![](01-intro_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n***\n\n- Merk op dat we niet zoveel gegevens hebben. Enkel 10 per groep.\n\n- Het is altijd beter om de data zo ruw mogelijk te tonen!\n\nOmdat er niet zoveel gegevens zijn kunnen we de data toevoegen aan de plot zonder dat die te druk wordt.\n\n- Merk op dat we het argument `outlier.shape` op NA (not available) zetten `outlier.shape=NA` in the `geom_boxplot` functie omdat we anders outliers twee keer weer zullen geven. Eerst via de boxplot laag en daarna omdat we een laag met alle ruwe data toevoegen aan de plot.\n- We geven de ruwe data weer via de  `geom_point(position=\"jitter\")` functie. We gebruiken hierbij het argument position='jitter' zodat we wat random ruis toevoegen aan de x-cordinaat zodat de gegevens elkaar niet overlappen.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nap |>  \n  ggplot(aes(x=trt,y=rel)) +\n  geom_boxplot(outlier.shape=NA) +\n  geom_point(position=\"jitter\") +\n  theme_minimal() \n```\n\n::: {.cell-output-display}\n![](01-intro_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\nDit is een informatieve plot!\n\n***\n\nAangezien we de plot ook hebben opgeslagen konden we dit ook doen door de plot op te roepen en nog een laag toe te voegen.\n\n\n::: {.cell}\n\n```{.r .cell-code}\napBoxplot +\n  geom_point(position=\"jitter\")\n```\n\n::: {.cell-output-display}\n![](01-intro_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\nWe hadden het resultaat ook opnieuw op kunnen slaan voor later hergebruik.\n\n\n::: {.cell}\n\n```{.r .cell-code}\napBoxplot <- apBoxplot +\n  geom_point(position=\"jitter\")\n```\n:::\n\n\n***\n\n- We zagen duidelijk een effect van de transplantatie op de relatieve abundantie van Staphylococcus.\n\n- Is dat effect nu groot genoeg om te kunnen concluderen dat de behandeling werkt?\n\n***\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](01-intro_files/figure-html/unnamed-chunk-17-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n***\n\n- Inductie: Door middel van statistische besluitvorming (inference) kunnen we uitspraken doen over de populatie op basis van een steekproef.\n\n- De prijs die we hiervoor betalen is onzekerheid!\n\n- We kunnen op basis van een steekproef nooit absoluut zeker zijn van onze conclusies.\n\n***\n\n- Met data kunnen we niet bewijzen dat een behandeling werkt.\n\n- Falsificatie principe van Popper: Data kunnen enkel een hypothese of een theorie ontkrachten.\n\n- Met statistiek kunnen we dus niet aantonen dat de behandeling werkt.\n\n- Statistiek zal ons wel toelaten om het omgekeerde te falsifiëren: als we veronderstellen dat er geen effect van de behandeling, spreekt de data in de steekproef dit tegen?\n\n- Met statistiek kunnen we berekenen hoe waarschijnlijk het is om in een random steekproef (wanneer we het experiment dus opnieuw uit zouden voeren) een gemiddeld verschil in relatieve abundantie te zien tussen placebo en transplantatiegroep dat minstens zo groot is als in onze steekproef als de behandeling geen effect zou hebben.\n\n- Die kans wordt een p-waarde genoemd.\n\n- Als p heel klein is, dan is het heel onwaarschijnlijk om een dergelijk effect te observeren in een steekproef door toeval.\n\n- p wordt meestal vergeleken met 5%. Als er geen effect is van de behandeling dan tolereren 5% vals positieve conclusies.\n\n- Om de kans p te berekenen is het nodig om de data te modelleren met statistische modellen.\n\n***\n\nIn latere hoofdstukken zullen we zien dat we t-test kunnen gebruiken om hetgeen we observeren in de microbiome dataset te veralgemenen naar de populatie.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(rel~trt,data=ap)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  rel by trt\nt = -5.0334, df = 15.892, p-value = 0.0001249\nalternative hypothesis: true difference in means between group placebo and group transplant is not equal to 0\n95 percent confidence interval:\n -31.62100 -12.87163\nsample estimates:\n   mean in group placebo mean in group transplant \n                44.15496                 66.40127 \n```\n\n\n:::\n:::\n\n\nConclusie:\nGemiddeld is de relatieve abundantie van Staphylococcus in het microbiome van personen met een zweetgeur 22.2% hoger na de transplantie dan na de placebo behandeling.\n\n***\n\n## Random steekproeftrekking (Random sampling)\n\n- Wat zijn de consequenties van het gebruik van een random steekproeftrekking?\n\n- Random steekproeftrekking is sterk gerelateerd met het concept van de populatie en scope van de studie.  \n\n- De scope van de studie moet goed worden omschreven voor de start van het experiment.\n\n- Omdat de statistische analyse valide zou zijn is het noodzakelijk dat de subjecten volledig random worden getrokken uit de populatie naar waar we onze conclusies wensen te veralgemenen.\n\n- Volledig random trekken van de populatie impliceert dat:\n\n    - alle subjecten van de populatie evenveel kans hebben om in de steekproef te worden opgenomen\n    - de selectie van een subject onafhankelijk is van de andere subjecten in de steekproef.\n\n\n- De steekproef is dan representatief voor de populatie, maar is nog steeds random.\n\n- Wat betekent dit?\n\n***\n\n# Case study: Lengte van mannen en vrouwen \\- Variabiliteit van steekproef tot steekproef\n\n- Om te begrijpen dat een steekproef random is zouden we hetzelfde experiment veel keer moeten kunnen herhalen (`herhaalde steekproeftrekking`/`repeated sampling`).\n\n- Dan zouden we inzicht kunnen krijgen hoe de gegevens veranderen van steekproef tot steekproef.\n\n- Om dit te illustreren zullen we gebruik maken van een hele grote studie.\n\n- Uit die studie zullen we dan herhaaldelijk kleine steekproeven trekken om te begrijpen hoe de gegevens en statistieken veranderen van steekproef tot steekproef. Of om met andere woorden na te gaan wat de variabiliteit is tussen steekproeven.\n\n***\n\nNational Health And Nutrition Examination Study (NHANES)\n\n  - Sinds 1960 worden elk jaar mensen van alle leeftijden geïnterviewd bij hen thuis.\n  - Er maakt ook een gezondheidsonderzoek deel uit van de study die in een mobiel onderzoekscentrum wordt afgenomen.\n  - We zullen deze grote studie gebruiken om at random personen te selecteren van de Amerikaanse populatie.\n  - Dat zal inzicht geven in hoe de gegevens en resultaten van een analyse zullen variëren van steekproef tot steekproef.\n  - De data van deze studie is terug te vinden in het R pakket `NHANES`\n\n***\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(NHANES)\nhead(NHANES)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 76\n     ID SurveyYr Gender   Age AgeDecade AgeMonths Race1 Race3 Education   \n  <int> <fct>    <fct>  <int> <fct>         <int> <fct> <fct> <fct>       \n1 51624 2009_10  male      34 \" 30-39\"        409 White <NA>  High School \n2 51624 2009_10  male      34 \" 30-39\"        409 White <NA>  High School \n3 51624 2009_10  male      34 \" 30-39\"        409 White <NA>  High School \n4 51625 2009_10  male       4 \" 0-9\"           49 Other <NA>  <NA>        \n5 51630 2009_10  female    49 \" 40-49\"        596 White <NA>  Some College\n6 51638 2009_10  male       9 \" 0-9\"          115 White <NA>  <NA>        \n# ℹ 67 more variables: MaritalStatus <fct>, HHIncome <fct>, HHIncomeMid <int>,\n#   Poverty <dbl>, HomeRooms <int>, HomeOwn <fct>, Work <fct>, Weight <dbl>,\n#   Length <dbl>, HeadCirc <dbl>, Height <dbl>, BMI <dbl>,\n#   BMICatUnder20yrs <fct>, BMI_WHO <fct>, Pulse <int>, BPSysAve <int>,\n#   BPDiaAve <int>, BPSys1 <int>, BPDia1 <int>, BPSys2 <int>, BPDia2 <int>,\n#   BPSys3 <int>, BPDia3 <int>, Testosterone <dbl>, DirectChol <dbl>,\n#   TotChol <dbl>, UrineVol1 <int>, UrineFlow1 <dbl>, UrineVol2 <int>, …\n```\n\n\n:::\n\n```{.r .cell-code}\nglimpse(NHANES)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 10,000\nColumns: 76\n$ ID               <int> 51624, 51624, 51624, 51625, 51630, 51638, 51646, 5164…\n$ SurveyYr         <fct> 2009_10, 2009_10, 2009_10, 2009_10, 2009_10, 2009_10,…\n$ Gender           <fct> male, male, male, male, female, male, male, female, f…\n$ Age              <int> 34, 34, 34, 4, 49, 9, 8, 45, 45, 45, 66, 58, 54, 10, …\n$ AgeDecade        <fct>  30-39,  30-39,  30-39,  0-9,  40-49,  0-9,  0-9,  40…\n$ AgeMonths        <int> 409, 409, 409, 49, 596, 115, 101, 541, 541, 541, 795,…\n$ Race1            <fct> White, White, White, Other, White, White, White, Whit…\n$ Race3            <fct> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ Education        <fct> High School, High School, High School, NA, Some Colle…\n$ MaritalStatus    <fct> Married, Married, Married, NA, LivePartner, NA, NA, M…\n$ HHIncome         <fct> 25000-34999, 25000-34999, 25000-34999, 20000-24999, 3…\n$ HHIncomeMid      <int> 30000, 30000, 30000, 22500, 40000, 87500, 60000, 8750…\n$ Poverty          <dbl> 1.36, 1.36, 1.36, 1.07, 1.91, 1.84, 2.33, 5.00, 5.00,…\n$ HomeRooms        <int> 6, 6, 6, 9, 5, 6, 7, 6, 6, 6, 5, 10, 6, 10, 10, 4, 3,…\n$ HomeOwn          <fct> Own, Own, Own, Own, Rent, Rent, Own, Own, Own, Own, O…\n$ Work             <fct> NotWorking, NotWorking, NotWorking, NA, NotWorking, N…\n$ Weight           <dbl> 87.4, 87.4, 87.4, 17.0, 86.7, 29.8, 35.2, 75.7, 75.7,…\n$ Length           <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ HeadCirc         <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ Height           <dbl> 164.7, 164.7, 164.7, 105.4, 168.4, 133.1, 130.6, 166.…\n$ BMI              <dbl> 32.22, 32.22, 32.22, 15.30, 30.57, 16.82, 20.64, 27.2…\n$ BMICatUnder20yrs <fct> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ BMI_WHO          <fct> 30.0_plus, 30.0_plus, 30.0_plus, 12.0_18.5, 30.0_plus…\n$ Pulse            <int> 70, 70, 70, NA, 86, 82, 72, 62, 62, 62, 60, 62, 76, 8…\n$ BPSysAve         <int> 113, 113, 113, NA, 112, 86, 107, 118, 118, 118, 111, …\n$ BPDiaAve         <int> 85, 85, 85, NA, 75, 47, 37, 64, 64, 64, 63, 74, 85, 6…\n$ BPSys1           <int> 114, 114, 114, NA, 118, 84, 114, 106, 106, 106, 124, …\n$ BPDia1           <int> 88, 88, 88, NA, 82, 50, 46, 62, 62, 62, 64, 76, 86, 6…\n$ BPSys2           <int> 114, 114, 114, NA, 108, 84, 108, 118, 118, 118, 108, …\n$ BPDia2           <int> 88, 88, 88, NA, 74, 50, 36, 68, 68, 68, 62, 72, 88, 6…\n$ BPSys3           <int> 112, 112, 112, NA, 116, 88, 106, 118, 118, 118, 114, …\n$ BPDia3           <int> 82, 82, 82, NA, 76, 44, 38, 60, 60, 60, 64, 76, 82, 7…\n$ Testosterone     <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ DirectChol       <dbl> 1.29, 1.29, 1.29, NA, 1.16, 1.34, 1.55, 2.12, 2.12, 2…\n$ TotChol          <dbl> 3.49, 3.49, 3.49, NA, 6.70, 4.86, 4.09, 5.82, 5.82, 5…\n$ UrineVol1        <int> 352, 352, 352, NA, 77, 123, 238, 106, 106, 106, 113, …\n$ UrineFlow1       <dbl> NA, NA, NA, NA, 0.094, 1.538, 1.322, 1.116, 1.116, 1.…\n$ UrineVol2        <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ UrineFlow2       <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ Diabetes         <fct> No, No, No, No, No, No, No, No, No, No, No, No, No, N…\n$ DiabetesAge      <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ HealthGen        <fct> Good, Good, Good, NA, Good, NA, NA, Vgood, Vgood, Vgo…\n$ DaysPhysHlthBad  <int> 0, 0, 0, NA, 0, NA, NA, 0, 0, 0, 10, 0, 4, NA, NA, 0,…\n$ DaysMentHlthBad  <int> 15, 15, 15, NA, 10, NA, NA, 3, 3, 3, 0, 0, 0, NA, NA,…\n$ LittleInterest   <fct> Most, Most, Most, NA, Several, NA, NA, None, None, No…\n$ Depressed        <fct> Several, Several, Several, NA, Several, NA, NA, None,…\n$ nPregnancies     <int> NA, NA, NA, NA, 2, NA, NA, 1, 1, 1, NA, NA, NA, NA, N…\n$ nBabies          <int> NA, NA, NA, NA, 2, NA, NA, NA, NA, NA, NA, NA, NA, NA…\n$ Age1stBaby       <int> NA, NA, NA, NA, 27, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ SleepHrsNight    <int> 4, 4, 4, NA, 8, NA, NA, 8, 8, 8, 7, 5, 4, NA, 5, 7, N…\n$ SleepTrouble     <fct> Yes, Yes, Yes, NA, Yes, NA, NA, No, No, No, No, No, Y…\n$ PhysActive       <fct> No, No, No, NA, No, NA, NA, Yes, Yes, Yes, Yes, Yes, …\n$ PhysActiveDays   <int> NA, NA, NA, NA, NA, NA, NA, 5, 5, 5, 7, 5, 1, NA, 2, …\n$ TVHrsDay         <fct> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ CompHrsDay       <fct> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ TVHrsDayChild    <int> NA, NA, NA, 4, NA, 5, 1, NA, NA, NA, NA, NA, NA, 4, N…\n$ CompHrsDayChild  <int> NA, NA, NA, 1, NA, 0, 6, NA, NA, NA, NA, NA, NA, 3, N…\n$ Alcohol12PlusYr  <fct> Yes, Yes, Yes, NA, Yes, NA, NA, Yes, Yes, Yes, Yes, Y…\n$ AlcoholDay       <int> NA, NA, NA, NA, 2, NA, NA, 3, 3, 3, 1, 2, 6, NA, NA, …\n$ AlcoholYear      <int> 0, 0, 0, NA, 20, NA, NA, 52, 52, 52, 100, 104, 364, N…\n$ SmokeNow         <fct> No, No, No, NA, Yes, NA, NA, NA, NA, NA, No, NA, NA, …\n$ Smoke100         <fct> Yes, Yes, Yes, NA, Yes, NA, NA, No, No, No, Yes, No, …\n$ Smoke100n        <fct> Smoker, Smoker, Smoker, NA, Smoker, NA, NA, Non-Smoke…\n$ SmokeAge         <int> 18, 18, 18, NA, 38, NA, NA, NA, NA, NA, 13, NA, NA, N…\n$ Marijuana        <fct> Yes, Yes, Yes, NA, Yes, NA, NA, Yes, Yes, Yes, NA, Ye…\n$ AgeFirstMarij    <int> 17, 17, 17, NA, 18, NA, NA, 13, 13, 13, NA, 19, 15, N…\n$ RegularMarij     <fct> No, No, No, NA, No, NA, NA, No, No, No, NA, Yes, Yes,…\n$ AgeRegMarij      <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 20, 15, N…\n$ HardDrugs        <fct> Yes, Yes, Yes, NA, Yes, NA, NA, No, No, No, No, Yes, …\n$ SexEver          <fct> Yes, Yes, Yes, NA, Yes, NA, NA, Yes, Yes, Yes, Yes, Y…\n$ SexAge           <int> 16, 16, 16, NA, 12, NA, NA, 13, 13, 13, 17, 22, 12, N…\n$ SexNumPartnLife  <int> 8, 8, 8, NA, 10, NA, NA, 20, 20, 20, 15, 7, 100, NA, …\n$ SexNumPartYear   <int> 1, 1, 1, NA, 1, NA, NA, 0, 0, 0, NA, 1, 1, NA, NA, 1,…\n$ SameSex          <fct> No, No, No, NA, Yes, NA, NA, Yes, Yes, Yes, No, No, N…\n$ SexOrientation   <fct> Heterosexual, Heterosexual, Heterosexual, NA, Heteros…\n$ PregnantNow      <fct> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n```\n\n\n:::\n:::\n\n\n***\n\n## Data exploratie\n\n\n\nOnderzoeksvraag: hoe verschilt de lengte van volwassen mannen en vrouwen.\n\n1. We pipen de dataset naar de function `filter` om de data te filteren volgens leeftijd.  \n2. We plotten de lengte metingen.\n    - We selecteren de data data met het commando `ggplot(aes(x=lengte))`\n    - We voegen een histogram toe met het commando `geom_histogram()`\n    - We maken twee vertikale panels met het commando `facet_grid(Gender~.)`\n    - We veranderen het label van de x-as met de `xlab` functie.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNHANES|>  \n  filter(Age >= 18 & !is.na(Height)) |>\n  ggplot(aes(x = Height))+\n  geom_histogram() +\n  facet_grid(Gender ~ .) +\n  xlab(\"Lengte (cm)\") + \n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](01-intro_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\n***\n\nWe zien dat de data nu min of meer symmetrisch verdeeld zijn en een klokvorm hebben.  \nDat zal ons toe laten om de data verder samen te vatten door gebruik te maken van twee statistieken: het gemiddelde en de standaard deviatie wat een maat is voor de spreiding van de gegevens rond het gemiddelde.\n\n***\n\nWe maken nu een subset van de data die we zullen gebruiken om aan te tonen hoe de data in kleine steekproeven kan variëren van steekproef tot steekproef.\n\n  1. We filteren op leeftijd en verwijderen ontbrekenden gegevens (NA, Not Available).\n  2. We selecteren enkel het geslacht en Lengte zodat de dataset geen onnodige variabelen bevat.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnhanesSub <- NHANES |>\n  filter(Age >= 18 & !is.na(Height)) |>\n  select(c(\"Gender\",\"Height\"))\n```\n:::\n\n\n***\n\nWe berekenen het gemiddelde en de standaard deviatie voor de lengte voor mannen en vrouwen in de grote dataset.\nWe groeperen de data hiervoor op basis van het geslacht (variable Gender).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHeightSum <- nhanesSub |>\n  group_by(Gender) |>\n  summarize_at(\"Height\",\n               list(mean = mean,\n               sd = sd)\n              )\n\nknitr::kable(\n  HeightSum |>\n  mutate_if(is.numeric, round, digits=1)\n  )\n```\n\n::: {.cell-output-display}\n\n\n|Gender |  mean|  sd|\n|:------|-----:|---:|\n|female | 162.1| 7.3|\n|male   | 175.9| 7.5|\n\n\n:::\n:::\n\n\nBeide verdelingen: \n\n- lijken een normale verdeling te volgen\n- met dezelfde variantie\n\n\n$\\rightarrow$ ze verschillen dus enkel in gemiddelde. \n\n- Onderzoeksvraag: \"Is er een verschil in lengte tussen mannen en vrouwen?\" \n- kunnen vertalen naar 1 karakteristiek: het gemiddeld verschil in lengte\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHeightSum$mean[1]-HeightSum$mean[2]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -13.81445\n```\n\n\n:::\n:::\n\n\nGemiddeld zijn volwassen Amerikaanse vrouwen 13.8 cm kleiner dan mannen. \n\n***\n\n## Experiment\n\n- Stel dat we geen toegang hebben tot de metingen van de NHANES studie.\n\n- We zouden dan een experiment op moeten zetten om metingen bij mannen en vrouwen te doen.\n\n- Veronderstel dat we budget hebben om metingen bij 5 mannen en 5 vrouwen te doen.\n\n- We zouden dan 5 mannen en 5 vrouwen boven de 18 jaar at random selecteren uit de Amerikaanse populatie.\n\n- We kunnen dit experiment simuleren door 5 vrouwen en 5 mannen at random te selecteren uit de NHANES studie.\n\n***\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1023)\nnSamp <- 5\nfem <- nhanesSub |>\n  filter(Gender==\"female\") |>\n  sample_n(size=5)\n\nmal <- nhanesSub |>\n  filter(Gender==\"male\") |>\n  sample_n(size=5)\n\nsamp1 <- rbind(fem,mal)\n\nsamp1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 2\n   Gender Height\n   <fct>   <dbl>\n 1 female   164 \n 2 female   160.\n 3 female   159 \n 4 female   154.\n 5 female   156.\n 6 male     170.\n 7 male     183.\n 8 male     183.\n 9 male     185.\n10 male     170.\n```\n\n\n:::\n:::\n\n\n***\n\nData Exploratie\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsamp1 |>\n  ggplot(aes(x=Height)) +\n  geom_histogram() +\n  facet_grid(Gender~.) +\n  xlab(\"Lengte (cm)\") + \n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](01-intro_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n\n```{.r .cell-code}\nHeightSumExp1 <- samp1 |>\n  group_by(Gender) |>\n  summarize_at(\"Height\",\n               list(mean = mean,\n                      sd = sd)\n                  )\nHeightSumExp1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  Gender  mean    sd\n  <fct>  <dbl> <dbl>\n1 female  159.  3.76\n2 male    178.  7.55\n```\n\n\n:::\n:::\n\n\nHistogram is niet zinvol als we maar zo weinig datapunten hebben.\n\n***\n\n\nBoxplot is beter:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](01-intro_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\n\n## Herhaal het experiment\n\nAls we het experiment herhalen selecteren we andere mensen en verkrijgen we andere resultaten.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1024)\nfem <- nhanesSub |>\n  filter(Gender==\"female\") |>\n  sample_n(size=5)\n\nmal <- nhanesSub |>\n  filter(Gender==\"male\") |>\n  sample_n(size=5)\n\nsamp2 <- rbind(fem,mal)\n\nHeightSumExp2 <- samp2 |>\n  group_by(Gender) |>\n  summarize_at(\"Height\",\n               list(mean=mean,\n                    sd=sd)\n              )\nHeightSumExp2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  Gender  mean    sd\n  <fct>  <dbl> <dbl>\n1 female  166.  9.89\n2 male    170.  8.24\n```\n\n\n:::\n\n```{.r .cell-code}\nsamp2 |>\n  ggplot(aes(x = Gender,y = Height)) +\n  geom_boxplot(outlier.shape = NA) +\n  geom_point(position = \"jitter\") +\n  geom_point(\n    aes(x = 1, y = HeightSumExp2$mean[1]),\n    size = 3,\n    pch = 17,\n    color=\"darkred\") +\n  geom_point(\n    aes(x = 2, y = HeightSumExp2$mean[2]),\n    size = 3,\n    pch = 17,\n    color = \"darkred\") +\n  ylab(\"Height (cm)\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](01-intro_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\n\n## Herhaal het experiment opnieuw\n\n\n::: {.cell}\n\n```{.r .cell-code}\nseed <- 88605\nset.seed(seed)\nfem <- nhanesSub |>\n  filter(Gender==\"female\") |>\n  sample_n(size=5)\n\nmal <- nhanesSub |>\n  filter(Gender==\"male\") |>\n  sample_n(size=5)\n\nsamp3 <- rbind(fem,mal)\n\nHeightSumExp3 <- samp3 |>\n  group_by(Gender) |>\n  summarize_at(\"Height\",\n               list(mean=mean,\n                    sd=sd)\n              )\nHeightSumExp3\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  Gender  mean    sd\n  <fct>  <dbl> <dbl>\n1 female  173.  1.97\n2 male    168.  2.84\n```\n\n\n:::\n\n```{.r .cell-code}\nsamp3 |>\n  ggplot(aes(x = Gender,y = Height)) +\n  geom_boxplot(outlier.shape = NA) +\n  geom_point(position = \"jitter\") +\n  geom_point(\n    aes(x = 1, y = HeightSumExp3$mean[1]),\n    size = 3,\n    pch = 17,\n    color=\"darkred\") +\n  geom_point(\n    aes(x = 2, y = HeightSumExp3$mean[2]),\n    size = 3,\n    pch = 17,\n    color = \"darkred\") +\n  ylab(\"Height (cm)\") + \n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](01-intro_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n\n### Herhaal het experiment heel veel keer \n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(15152)\n# Aantal simulaties en steekproefgrootte per groep\nnSim <- 10000\nnSamp <- 5\n\n# We filteren de data vooraf zodat we dit niet telkens opnieuw hoeven te doen\nfem <- nhanesSub |>\n  filter(Gender == \"female\")\n\nmal <- nhanesSub |>\n  filter(Gender == \"male\")\n\n# Simulatie studie\n# Om snelle functies te kunnen gebruiken nemen we eerst nSim steekproeven en berekenen we daarna alles.\n\nfemSamps <- malSamps <-matrix(NA, nrow=nSamp, ncol=nSim)\nfor (i in 1:nSim)\n{\n  femSamps[,i] <- sample(fem$Height, nSamp)\n  malSamps[,i] <- sample(mal$Height, nSamp)\n}\n\nres <- data.frame(\n  verschil=colMeans(femSamps) - colMeans(malSamps))\n\nres |>\n  ggplot(aes(y=verschil)) +\n  geom_boxplot() +\n  ylab(\"Gemiddeld Verschil (cm)\") +\n  xlab(\"\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](01-intro_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\n### Effect van vergroten van steekproef \n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(15142)\n# Aantal simulaties en steekproefgrootte per groep\nnSim <- 10000\nnSamp <- 25\n\n# We filteren de data vooraf zodat we dit niet telkens opnieuw hoeven te doen\nfem <- nhanesSub |>\n  filter(Gender == \"female\")\n\nmal <- nhanesSub |>\n  filter(Gender == \"male\")\n\n# Simulatie studie\n# Om snelle functies te kunnen gebruiken nemen we eerst nSim steekproeven en berekenen we daarna alles.\n\nfemSamps <- malSamps <-matrix(NA, nrow=nSamp, ncol=nSim)\nfor (i in 1:nSim)\n{\n  femSamps[,i] <- sample(fem$Height, nSamp)\n  malSamps[,i] <- sample(mal$Height, nSamp)\n}\n\nres2 <- data.frame(\n  verschil=colMeans(femSamps) - colMeans(malSamps))\n\nres2$ng <- 25\nres$ng <- 5\n\nrbind(res,res2) |>\n  ggplot(aes(y=verschil)) +\n  geom_boxplot() +\n  ylab(\"Gemiddeld Verschil (cm)\") +\n  xlab(\"\") +\n  theme_minimal() +\n  facet_wrap(~ng)\n```\n\n::: {.cell-output-display}\n![](01-intro_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\n\n## Samenvatting\n\n- We trokken at random andere proefpersonen in elke steekproef\n\n- Hierdoor verschillen lengtemetingen van steekproef tot steekproef.\n\n- Dus ook de geschatte gemiddeldes en standaard deviaties.\n\n$\\rightarrow$ Bijgevolg zijn onze conclusies ook onzeker en kunnen deze wijzigen van steekproef tot steekproef.\n\n$\\rightarrow$ Met statistiek controleren we de kans op het trekken van foute conclusies.\n\n- We zagen ook dat we het werkelijke verschil meer precies kunnen schatten als we de steekproefgrootte vergroten. \n\n$\\rightarrow$ Design van experiment zal dus bepalen hoe makkelijk we het werkelijk verschil op kunnen pikken met de steekproef.\n\n***\n\n# Case study: Salk vaccin\n\n- In 1916 brak de eerste grote polio epidemie uit in de USA.\n- Begin de jaren 50 ontwikkelde John Salk een vaccin met belovende resultaten in het lab.\n- In 1954 heeft de National Foundation\nfor Infantile Paralysis (NFIP) een grote studie opgezet om de effectiviteit van het Salk vaccin na te gaan.\n- Veronderstel dat de NFIP in 1954 een groot aantal kinderen zou hebben gevaccineerd, wat zouden ze dan kunnen besluiten als de polio incidentie in 1954 lager was dan in 1953?\n\n***\n\n## NFIP Study\n### Design\n\n- Grote simultane studie met gevaccineerde kinderen (cases) en ongevaccineerde kinderen (controles).\n- In scholen van districten met hoge polio incidentie.\n- Cases: kinderen van de tweede graad van het lager onderwijs waarvan de ouders toestemden met vaccinatie.\n- Controles: kinderen van de eerste en derde graad.\n\n### Data\n\n::: {.cell}\n\n```{.r .cell-code}\nnfip <- tibble(\n  group=c(\"cases\",\"controls\",\"noConcent\"),\n  grade=c(\"g2\",\"g1g3\",\"g2\"),\n  vaccin=c(\"yes\",\"no\",\"no\"),\n  total=c(221998,725173,123605),\n  polio=c(54,391,56)\n  ) |>\n  mutate(noPolio = total - polio)\nknitr::kable(nfip)\n```\n\n::: {.cell-output-display}\n\n\n|group     |grade |vaccin |  total| polio| noPolio|\n|:---------|:-----|:------|------:|-----:|-------:|\n|cases     |g2    |yes    | 221998|    54|  221944|\n|controls  |g1g3  |no     | 725173|   391|  724782|\n|noConcent |g2    |no     | 123605|    56|  123549|\n\n\n:::\n:::\n\n\nVergelijk de polio incidentie?\n\n***\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnfip <- nfip |>\n  mutate(incidencePM = round(nfip$polio/nfip$total*1e6,0))\nknitr::kable(nfip)\n```\n\n::: {.cell-output-display}\n\n\n|group     |grade |vaccin |  total| polio| noPolio| incidencePM|\n|:---------|:-----|:------|------:|-----:|-------:|-----------:|\n|cases     |g2    |yes    | 221998|    54|  221944|         243|\n|controls  |g1g3  |no     | 725173|   391|  724782|         539|\n|noConcent |g2    |no     | 123605|    56|  123549|         453|\n\n\n:::\n:::\n\n\nWat kunnen we concluderen?\n\n***\n\n## Confounding\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](01-intro_files/figure-html/unnamed-chunk-33-1.png){fig-align='center' width=50%}\n:::\n:::\n\n\n\n- We observeren een lagere polio (P) incidentie voor kinderen bij wie de ouders geen toestemming gaven dan in de controle groep.  \n\n- Toestemming voor vaccinatie (V) is geassocieerd met de socio-economische status (S).\n\n- Kinderen van lagere socio-economische status zijn meer resistent tegen de ziekte.\n\n- De groepen van cases en controles zijn niet vergelijkbaar\n    - verschil in leeftijd\n    - verschil in socio-economische status en\n    - verschil in vatbaarheid voor de ziekte.\n\n***\n\n## Salk Study\n\n### Design\nEen nieuwe studie werd uitgevoerd: dubbel blinde gerandomiseerde studie.\n\n  - Kinderen worden at random toegewezen aan controle of case arm van het experiment nadat de ouders toestemden met vaccinatie.\n  - Controle: vaccinatie met placebo\n  - Treatment: vaccinatie met vaccin\n  - Double blinding:\n    - ouders en kinderen weten niet of ze werden gevaccineerd of niet\n    - medische staf en onderzoekers weten niet of het kind het vaccin of de placebo kreeg\n\n***\n\n### Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsalk <- data.frame(\n  group=c(\"cases\",\"control\",\"noConcent\"),\n  treatment=c(\"vaccine\",\"placebo\",\"none\"),\n  total=c(200745,201229, 338778),polio=c(57,142,157)\n  ) |>\n  mutate(\n    noPolio = total-polio,\n    incidencePM = round(polio/total*1e6,0)\n    )\nknitr::kable(salk)\n```\n\n::: {.cell-output-display}\n\n\n|group     |treatment |  total| polio| noPolio| incidencePM|\n|:---------|:---------|------:|-----:|-------:|-----------:|\n|cases     |vaccine   | 200745|    57|  200688|         284|\n|control   |placebo   | 201229|   142|  201087|         706|\n|noConcent |none      | 338778|   157|  338621|         463|\n\n\n:::\n:::\n\n\n- We observeren een veel groter effect nu cases en controles vergelijkbaar zijn, incidentie van respectievelijk 284  en 706 per miljoen.\n\n- De polio incidentie voor kinderen die geen toestemming geven blijft vergelijkbaar  453 en 463 per miljoen respectievelijk in de NFIP- en Salk-studie.\n\n***\n\n# Rol van Statistiek\n\n- We hebben gezien dat\n    - het belangrijk is om de scope van de studie goed te specifiëren voor de start van het experiment\n    - random steekproeftrekking nodig is om een representatieve steekproef te nemen\n    - steekproef grootte is heel belangrijk\n    - we moeten ons bewust zijn van Confounding\n    - een goede controle is belangrijk\n\n\n$\\rightarrow$ Goede proefopzet is cruciaal!\n\n***\n\n- We hebben ook geobserveerd dat er variabiliteit is in de populatie\n- We kunnen maar een beperkte steekproef nemen uit de populatie\n\n$\\rightarrow$ onzekerheid in de resultaten\n$\\rightarrow$ onzekerheid in de conclusies\n\n\n***\n\n- Statistiek is de wetenschap voor het\n    1. verzamelen (experimenteel design),\n    2. exploren (data exploration) en\n    3. leren van data zodat we hetgeen we observeren in de steekproef zouden kunnen veralgemenen naar de populatie terwijl we de onzekerheid quantificeren, controleren en rapporteren (statistisch modelleren en statistische besluitvorming).\n\n- Statistiek speelt daarom een heel belangrijke rol in zowat alle wetenschappen\n",
    "supporting": [
      "01-intro_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}