{
  "hash": "18ba0f62bd991e701460be001c0945ba",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"9. Categorische Data Analyse\"\nauthor: \"Lieven Clement\"\ndate: \"statOmics, Ghent University (https://statomics.github.io)\"\nformat:\n  html:\n    toc: true\n    number-sections: true\n    theme: cosmo\n    highlight-style: tango\n    code-tools: true\n    embed-resources: true\n---\n\n\n# Inleiding\n\n- Vorige hoofdstukken:\n\n  - continue uitkomst  \n  - categorische of continue predictor.\n\n- Nu besluitvorming voor categorische uitkomst.\n- Focus op associatie tussen categorische uitkomst en een categorische predictor.\n- Gebruik van *kruistabellen* om associatie voor te stellen.\n\n***\n\n# Toetsen voor een proportie\n\n## Saksen-studie\n\n- Vrij gesloten populatie (weinig immigratie en emigratie)\n- Wat is de kans dat een ongeboren kind mannelijk is?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboys <- 3175\nn <- 6155\n```\n:::\n\n\n- Op 6155 ongeboren kinderen werden 3175 jongens geobserveerd.\n- Verschil in kans dat ongeboren kind jongen of meisje is?\n\n***\n\n- Gegevens voorstellen als uitkomsten van een numerieke toevalsveranderlijke $X$\n\n  - $X=1$ voor jongens en\n  - $X=0$ voor meisjes.\n\n- Merk op: telprobleem omdat de uitkomst een telling (nl. het aantal jongens)\n\n- Formeel: populatie van ongeboren kinderen\nwaarin elk individu gekenmerkt wordt door een 0 of een 1.\n\n- Uitkomst variabele is binair.\n\n***\n\n## Bernoulli verdeling\n\n- Binaire data $\\longrightarrow$ Bernoulli verdeling:\n  \\begin{eqnarray*}\nX_i &\\sim& B(\\pi) \\text{ met}\\\\\nB(\\pi)&=&\\pi^{X_i}(1-\\pi)^{(1-X_i)},\n\\end{eqnarray*}\n\n- Distributie met 1 model parameter $\\pi$\n\n    - Verwachte waarde van $X_i$: $\\text{E}[X_i]=\\pi,$\n    - Proportie van ongeboren jongens (d.i. kinderen met een 1) in de populatie.\n    - Bijgevolg is $\\pi$ kans dat lukraak getrokken individu een jongen is (een observatie die 1 oplevert).\n\n- Variantie van Bernoulli data bepaald door kans $\\pi$.\n$$\\text{Var}[X_i]=\\pi (1-\\pi).$$\n\n***\n\nGrafische weergave van enkele Bernoulli kansverdelingen\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](09-categoricalDataAnalysis_files/figure-html/unnamed-chunk-2-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n***\n\n- In Saksenstudie worden lukraak 6155 observaties getrokken uit populatie.\n- We schatten $\\pi$ als het steekproefgemiddelde :\n$$\\hat \\pi = \\bar X = \\frac{\\sum\\limits_{i=1}^n X_i}{n},$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\npi <- boys/n\npi\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5158408\n```\n\n\n:::\n:::\n\n\nIn ons voorbeeld is $\\bar x =$ 3175 / 6155 = 51.6%.\n\n***\n\n## Asymptotisch Betrouwbaarheidsinterval\n\n- Saksenstudie heel grote steekproef: 6155 onafhankelijke observaties.\n- CLT kan worden toegepast op gemiddelde: data volgt Bernoulli verdeling, maar gemiddelde o.b.v. onafhankelijke en identiek verdeelde observaties in heel grote steekproef volgt approximatief een normaal verdeling.  \n- $\\text{E}[\\bar X] = \\pi$\n- $\\text{Var}[\\bar X] = \\frac{\\text{Var}[X]}{n} = \\frac{\\pi(1-\\pi)}{n}$\n\n- $\\bar x$ = 0.516\n\n\n::: {.cell}\n\n```{.r .cell-code}\nse <- sqrt((pi*(1-pi))/n)\n```\n:::\n\n\n- SE = 0.0064\\[\n\\text{SE} = \\hat\\sigma_{\\bar x} = \\sqrt{\\frac{\\bar x(1-\\bar x)}{n}} \\]\n- BI: [0.503, 0.528]\n\\[ [\\bar x - z_{\\alpha/2} \\text{SE}_{\\bar x}, \\bar x + z_{\\alpha/2} \\text{SE}_{\\bar x}]\\]\n\n- 0.5 valt niet binnen het 95% BI.\n\n- De kans op een jongen is significant hoger dan 50% op het 5% significantie-niveau.\n\n## Asymptotische Test\n\n- H$_0$: $\\pi = 0.5$ vs H$_1$: $\\pi \\neq 0.5$\n\n- Merk op dat voor een Bernoulli verdeling de variantie onder H$_0$ ook gekend is: $\\pi_0 (1-\\pi_0)$.\n\n- Dus onder $H_0$ is standaard error op \\bar x:\n\n\\[\n\\text{SE}_{0, \\bar x}=\\sqrt{\\frac{\\pi_0 (1-\\pi_0)}{n}}\n\\]\n\n- Statistiek\n\\[ z = \\frac{\\bar x - \\pi_0}{\\text{SE}_{0, \\bar x}}\\]\n\n- Volgt onder de nulhypothese dat er evenveel kans is op een jongen of een meisje ($\\pi_0=0.5$) asymptotisch een normaal verdeling: CLT\n\n\n- p-waarde? Merk op dat het een tweezijdige test is!\n\n\n::: {.cell}\n\n```{.r .cell-code}\npi0 <- 0.5\nse0 <- sqrt(pi0*(1-pi0)/n)\nz <- (pi-pi0)/se0\nz\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.485539\n```\n\n\n:::\n\n```{.r .cell-code}\npval <- pnorm(abs(z),lower=FALSE) *2\npval\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.01293554\n```\n\n\n:::\n:::\n\n\nEr is significant meer kans dat een ongeboren kind mannelijk dan vrouwelijk is (p=0.013). De kans dat een ongeboren kind mannelijk is bedraagt 0.516 (95% BI [0.503, 0.528]).\n\n## Exacte test: Binomiale test\n\n- Statistische toets voor\n  $$H_0: \\pi=1/2 \\text{ versus } H_1: \\pi\\neq 1/2,$$\n\n- Daarvoor moeten we verdeling van de\n   - $X$ en $\\bar X$\n   - of van de som $S=n\\bar X$ kennen.\n- Als alle observaties onafhankelijk zijn en eenzelfde verdeling $B(\\pi)$ volgen dan volgt $S$ een binomiaal verdeling.\n\n***\n\n- Stel  $H_0:\\pi=1/2$ is waar (voorkomen van jongens en meisjes in populatie even waarschijnlijk)\n- Lukrake trekking van één individu uit de populatie, kans op een jongen $$P(X=1)=\\pi=1/2.$$\n- Twee kinderen onafhankelijk van elkaar (en de populatie $\\approx \\infty$):\n  - Kans $\\pi=1/2$ op jongen voor zowel eerste als tweede kind (onafhankelijk van elkaar)\n  - Uitkomsten $(x_1, x_2)$ voor beide kinderen hebben dan 4 mogelijke waarden:\n    $(0,0),(0,1),(1,0)\\text{ en }(1,1).$\n  - Deze komen elk voor met kans $1/4 = 1/2 \\times 1/2$.\n\n- Toevalsveranderlijke $S$ die som van uitkomsten weergeeft kan volgende waarden aannemen:\n\n$(x_1,x_2)$|$s$|$P(S = s)$|\n|:---:|:---:|:---:|\n(0,0)|0|1/4|\n(0,1), (1,0)|1|1/2|\n(1,1)|2|1/4|\n\n***\n\n### Algemeen: $n$ onafhankelijke observaties\n\n- Kans $\\pi$ op \"succes\" (uitkomst 1) voor elke observatie\n- Totaal aantal successen $S$ (som van alle 1-en) kan $n+1$ mogelijke waarden hebben\n  $$S=k\\text{, met }k=0,\\ldots,n$$\n- Verdeling van $S$?\n\\begin{equation}\nP(S=k) = \\left (\n\\begin{array}{c}\nn \\\\\nk \\\\\n\\end{array}\n\\right ) \\pi^k (1-\\pi)^{n-k}  \n\\end{equation}\n- $1-\\pi$: kans op mislukking in 1 enkele trekking (uitkomst met 0 genoteerd) en\n-  binomiaalcoëfficient\n\\begin{equation*}\n\\left (\n\\begin{array}{c}\nn \\\\\nk \\\\\n\\end{array}\n\\right ) = \\frac{n \\times (n-1) \\times ...\\times (n-k+1) }{ k!} = \\frac{ n!}{ k!(n-k)! }\n\\end{equation*}\n\n- In R kan je de kansen van binomiale verdeling voor elke $S=k$ opvragen met `dbinom(k,n,p)`\n\n\n***\n\n### Binomiale Verdeling\n\nDe toevalsveranderlijke $S$ volgt:\n\n-  *Binomiaal verdeelde toevalsveranderlijke* met bijhorende *Binomiale kansverdeling*\n- parameters\n\n    - $n$ (d.i. het aantal trekkingen of, equivalent, de maximale\nuitkomstwaarde)  \n    - $\\pi$ (de kans op een `succes' bij elke trekking).\n\n- Kans berekenen dat $k$ gebeurtenissen zich voordoen op $n$ onafhankelijke experimenten waarbij kans op 1 zo'n gebeurtenis per experiment, $\\pi$ bedraagt.\n- Voor analyse van gegevens die slechts 2 mogelijke waarden kunnen aannemen.\n- Bijvoorbeeld: al dan niet besmet met HIV, wild type van een gen vs een mutant,...\n- Gebruik: Proporties of risico's op een gebeurtenis van een bepaald type vergelijken tussen verschillende groepen.\n\n***\n\n### Een grafische weergave van enkele Binomiale kansverdelingen.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Binomiale verdelingen.](09-categoricalDataAnalysis_files/figure-html/binoms-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n***\n\nToetsstatistieken voor $$H_0:\\pi=1/2\\text{ versus }H_1:\\pi\\neq 1/2$$\n\n\n- $\\bar X-1/2$ of, equivalent,\n- $\\Delta=n(\\bar X-\\pi_0)=S-s_0$.\n- Verdeling van deze laatste toetsstatistiek volgt rechtstreeks uit de Binomiale verdeling:\n  - We observeren $s=$ 3175 en dus $\\delta=s-s_0=$ 3175 $-$ 6155 $\\times 0.5=$ 97.5.\n  - In veronderstelling dat jongens en meisjes even waarschijnlijk zijn (d.i. onder de nulhypothese $H_0:\\pi=1/2$), bekomen we de bijhorende tweezijdige p-waarde:\n    $$p=\\text{P}_0\\left[S-s_0\\geq \\vert \\delta\\vert \\right] + \\text{P}_0\\left[S-s_0\\leq - \\vert \\delta\\vert \\right].$$\n\n- Merk op dat we dit kunnen herschrijven in termen van S.\n$$p=\\text{P}_0\\left[S\\geq s_0+ \\vert \\delta\\vert \\right] + \\text{P}_0\\left[S \\leq s_0 - \\vert \\delta\\vert \\right].$$\n\n***\n\n- Voor ons voorbeeld kunnen we deze kansen als volgt berekenen:\n\n\\begin{eqnarray*}\n\\text{P}_0\\left[S\\geq s_0+ \\vert \\delta\\vert \\right] &=& P(S \\geq 6155 \\times 0.5 + \\vert 3175 - 6155 \\times 0.5\\vert ) \\\\&=& P(S \\geq 3175)\\\\\n&= &P(S= 3175) + P(S=3176) + ... + P(S=6155)\\\\\n& =& 0.0067\\\\\\\\\n\\text{P}_0\\left[S \\leq s_0 - \\vert \\delta\\vert \\right] &=& P(S \\leq  6155 \\times 0.5 - \\vert 3175- 6155 \\times 0.5\\vert) \\\\&=& P(S \\leq 2980)\\\\ &= &P(S=0) + ... + P(S=2980) \\\\\n&=&0.0067\n\\end{eqnarray*}\n\n- Binomiale distributie is symmetrisch als $\\pi=1/2$:\n$$\\text{P}_0\\left[S\\geq s_0+ \\vert \\delta\\vert \\right] = \\text{P}_0\\left[S \\leq s_0 - \\vert \\delta\\vert \\right]$$\n- Dat is niet langer het geval wanneer $\\pi$ afwijkt van 0.5.  \n\n***\n\n\n::: {.cell}\n\n```{.r .cell-code}\npi0 <- 0.5; s0 <- pi0 *n\ndelta <- abs(boys- s0)\ndelta\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 97.5\n```\n\n\n:::\n\n```{.r .cell-code}\nsUp <- s0 + delta\nsDown <- s0 -delta\nc(sDown,sUp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2980 3175\n```\n\n\n:::\n\n```{.r .cell-code}\npUp <- 1-pbinom(sUp-1,n,pi0)\npDown <- pbinom(sDown,n,pi0)\np <- pUp+pDown\nc(pUp,pDown, p)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.006699883 0.006699883 0.013399766\n```\n\n\n:::\n:::\n\n\n- Als $\\pi= 1/2$, kans om door toeval minstens $\\delta=$ 97.5 jongens meer of minder te observeren dan het gemiddelde onder $H_0: s_0=$ 3077.5 , slechts 1.34% is: **de $p$-waarde van de binomiale test.**  \n- Kleine kans om een dergelijk groot aantal jongens te observeren als in realiteit jongens en meisjes even veel voorkomen in de populatie.\n- Drukt uit dat de onderstelling dat jongens en meisjes even veel voorkomen, weinig gesteund wordt door de data.\n\n***\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](09-categoricalDataAnalysis_files/figure-html/unnamed-chunk-7-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n***\n\nDe test kan worden uitgevoerd a.d.h.v. de `binom.test` functie in R.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbinom.test(x=boys,n=n,p=pi0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tExact binomial test\n\ndata:  boys and n\nnumber of successes = 3175, number of trials = 6155, p-value = 0.0134\nalternative hypothesis: true probability of success is not equal to 0.5\n95 percent confidence interval:\n 0.5032696 0.5283969\nsample estimates:\nprobability of success \n             0.5158408 \n```\n\n\n:::\n:::\n\n\nOp het 5% significantie-niveau besluiten we dat er gemiddeld meer kans is dat een ongeboren kind mannelijk dan vrouwelijk is.\n\n- De Binomiale test heeft ook een exact BI weer op een proportie.\n\n- Het exacte BI is te verkiezen boven het BI dat gebaseerd is op de CLT.\n\n- Voor Saksen-studie ligt BI o.b.v. CLT heel dicht bij exacte BI: grote steekproef ($n=$ 6155).\n\n- Merk op dat het testen voor een proportie kan gezien worden als het equivalent van een one-sample t-test voor binaire data.\n\n***\n\n## Conclusie\n\n- Voor de Saksen populatie besluiten we op het 5% significantieniveau dat er meer kans is dat een ongeboren kind mannelijk dan vrouwelijk is ($p=$ 0.013).\nDe kans dat een ongeboren kind mannelijk is, bedraagt 51.6% (95% BI [50.3, 52.8]%).\n\n***\n\n# Toets voor associatie tussen 2 kwalitatieve variabelen\n## Gepaarde gegevens\n\n- 2 keer zelfde individu meten\n- bijvoorbeeld, vóór en na blootstelling aan de experimentele stof\n- telkens de categorische uitkomst te observeren.\n- Hier enkel: *gepaarde binaire uitkomsten*\n- Statistische analyse moet rekening houden met de paring.\n\n***\n\n### Voorbeeld:  partnerkeuze van seksueel mature vrouwelijke *Campbelli* dwerghamster (Rogovin et al. 2017)\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](09-categoricalDataAnalysis_files/figure-html/unnamed-chunk-9-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n***\n\n- Na 3 minuten, scheidingswand weg\n- aggressief vs niet-agressief mannentje\n- Elk vrouwtje onderging tweemaal de test: na verblijf in\n\n    - vijandige omgeving (hoge populatie, weinig voedsel, veel concurrentie)\n    - vriendelijkere omgeving\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Kruistabel van partnerkeuze bij dwerghamster.\n\n|                        |vriendelijk-agressief |vriendelijk-niet-agressief |totaal |\n|:-----------------------|:---------------------|:--------------------------|:------|\n|vijandig-agressief      |3 (e)                 |17 (f)                     |20     |\n|vijandig-niet-agressief |1 (g)                 |13 (h)                     |14     |\n|totaal                  |4                     |30                         |34     |\n\n\n:::\n:::\n\n\n***\n\n- $\\pi_2=P[\\text{agressief mannetje } \\vert \\text{ verblijf vijandige omgeving}]$\n- $\\hat \\pi_2=(e+f)/n$, waarbij $n=e+f+g+h$.\n\n- $\\pi_1=P[\\text{agressief mannetje } \\vert \\text{ verblijf vriendelijke omgeving}]$\n- $\\hat \\pi_1=(e+g)/n$\n- Absoluut riscoverschil (ARV)\n\\begin{equation*}\n\\widehat{\\text{ARV}}=\\hat\\pi_2-\\hat\\pi_1=\\frac{e+f}{n}-\\frac{e+g}{n}=\\frac{f-g}{n}\n\\end{equation*}\n- Enkel beïnvloed door aantallen discordante paren $f$ en $g$\n\n***\n\n- Standaard error op ARV\n\\begin{equation*}\n\\text{SE}_{\\widehat{\\text{ARV}}}=\\frac{1}{n}\\sqrt{f+g-\\frac{(f-g)^2}{n}}\n\\end{equation*}\n\n- Als er voldoende gegevens zijn, kan men een $(1-\\alpha)100\\%$ BI op ARV\n$$\\left[\\widehat{\\text{ARV}}-z_{\\alpha/2}\\text{SE}_{\\widehat{\\text{ARV}}},\\widehat{\\text{ARV}}-z_{\\alpha/2}\\text{SE}_{\\widehat{\\text{ARV}}}\\right]$$\nof\n$$\\left[\\frac{f-g}{n}-\\frac{z_{\\alpha/2}}{n}\\sqrt{f+g-\\frac{(f-g)^2}{n}},\\frac{f-g}{n}+\\frac{z_{\\alpha/2}}{n}\\sqrt{f+g-\\frac{(f-g)^2}{n}}\\right] $$\n\n***\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhamster <- matrix(c(3,17,1,13),ncol=2,byrow=TRUE)\nrownames(hamster) <- c(\"vijandig-agressief\", \"vijandig-niet-agressief\")\ncolnames(hamster) <- c(\"vriendelijk-agressief\",\"vriendelijk-niet-agressief\")\n\nf <- hamster[1,2]\ng <- hamster[2,1]\nn <- sum(hamster)\nriskdiff <- (f-g)/n\nriskdiff\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.4705882\n```\n\n\n:::\n\n```{.r .cell-code}\nse <- sqrt(f+g-(f-g)^2/n)/n\nse\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.09517144\n```\n\n\n:::\n\n```{.r .cell-code}\nbi <- riskdiff + c(-1,1)*qnorm(0.975)*se\nbi\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2840556 0.6571208\n```\n\n\n:::\n:::\n\n\n***\n\n\\begin{equation*}\n\\widehat{\\text{ARV}}=\\frac{17-1}{34}=0.471\n\\end{equation*}\nof 47.1%.\n\n- De standaard error\n\\begin{equation*}\n\\text{SE}_{\\widehat{\\text{ARV}}}=\\frac{1}{34}\\sqrt{17+1-\\frac{(17-1)^2}{34}}=0.0952\n\\end{equation*}\n\n- Een 95\\% betrouwbaarheidsinterval voor het absolute risicoverschil op de keuze van een agressief mannetje tussen een verblijf in een vijandige en vriendelijke omgeving is bijgevolg\n\\begin{equation*}\n\\left[0.471-1.96\\times 0.0952,0.471+1.96\\times 0.0952\\right]=[0.284,0.658]\n\\end{equation*}\n\n- We hebben besluiten dus dat absolute risico verschil in het interval [28.4,65.8]% ligt en weten dat dergelijke intervallen voor grote steekproeven het werkelijke absolute risco verschil met een kans van 95% bevatten.\n\n- Op basis van het BI besluiten we op het 5% niveau dat het meer waarschijnlijk is dat vrouwelijke hamsters een aggressieve partner kiezen nadat ze in een vijandige omgeving hebben verbleven dan wanneer ze in een vriendelijke omgeving verbleven. De kans op de keuze van een agressief mannetje is 47% hoger nadat ze in een vijandige omgeving heeft verbleven (95% BI 28.4,65.8]%)\n\n***\n\n### McNemar test\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|                        |vriendelijk-agressief |vriendelijk-niet-agressief |totaal |\n|:-----------------------|:---------------------|:--------------------------|:------|\n|vijandig-agressief      |3 (e)                 |17 (f)                     |20     |\n|vijandig-niet-agressief |1 (g)                 |13 (h)                     |14     |\n|totaal                  |4                     |30                         |34     |\n\n\n:::\n:::\n\n\n- Toetsen of de risico's verschillen tussen de vijandige en vriendelijke omgeving.\n- Enkel de discordante paren leveren hier informatie over.\n- $f>g$ indicatie tegen $H_0$: partnerkeuze niet geassocieerd met omgeving\n- Kans evalueren dat in een lukraak discordant paar, vrouwtje na verblijf in een vijandige omgeving kiest voor het agressieve mannetje.\n- Deze kans wordt geschat als\n  $$\\frac{f}{f+g}$$\n\n***\n\n  \\begin{eqnarray*}\n  \\text{E}\\left[f/(f+g)\\right]&\\stackrel{H_0}{=}& 0.5\\\\\n  f & \\stackrel{H_0}{\\sim}& \\text{Binom}(n=f+g,\\pi=0.5)\\\\\n  \\text{SE}_{\\frac{f}{f+g}} & \\stackrel{H_0}{=}& \\sqrt{(f+g)\\times 0.5\\times 0.5}=\\frac{\\sqrt{f+g}}{2}\n\\end{eqnarray*}\n\n***\n\n- Asymptotisch one-sample z-test (o.b.v. normale verdeling)\n\n\\begin{equation*}\nz <- \\frac{f-(f+g)/2}{\\sqrt{f+g}/2}=\\frac{f-g}{\\sqrt{f+g}}\n\\end{equation*}\n\n- De Normale benadering is goed als $$f \\times g/(f+g) \\geq 5$$\n\n- In kleine steekproeven is het meer aangewezen om een continuïteitscorrectie te gebruiken d.m.v. de toetsingsgrootheid\n\\begin{equation*}\n\\frac{|f-g|-1}{\\sqrt{f+g}}\n\\end{equation*}\n\nDe **Mc Nemar test** analogon van de gepaarde t-test voor binaire, kwalitatieve i.p.v. continue variabelen.\n\n***\n\nIn R  `mcnemar.test` functie\n\n::: {.cell}\n\n```{.r .cell-code}\nmcnemar.test(hamster)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMcNemar's Chi-squared test with continuity correction\n\ndata:  hamster\nMcNemar's chi-squared = 12.5, df = 1, p-value = 0.000407\n```\n\n\n:::\n:::\n\n\n\n- We verwerpen bijgevolg de nulhypothese op het 5% significantieniveau en\n- Besluiten dat de parternkeuze extreem significant geassocieerd is met de omgeving.\n\n- We zien dat hier eveneens de continuïteitscorrectie werd uitgevoerd en dat we exact dezelfde p-waarde bekomen.\n\n***\n\n- Normale benadering van deze toetstatistiek niet ideaal\nis omdat $f \\times g/(f+g) < 5$.\n\n- Steeds beter: binomiale test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbinom.test(x = f,\n  n = f + g,\n  p = 0.5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tExact binomial test\n\ndata:  f and f + g\nnumber of successes = 17, number of trials = 18, p-value = 0.000145\nalternative hypothesis: true probability of success is not equal to 0.5\n95 percent confidence interval:\n 0.7270564 0.9985944\nsample estimates:\nprobability of success \n             0.9444444 \n```\n\n\n:::\n:::\n\n\n***\n\n### Conclusie\n\n- Op basis van de exacte test besluiten we eveneens dat de parternkeuze extreem significant geassocieerd is met de omgeving ($p<0.001$).\n- De kans op de keuze van een agressief mannetje ligt 47.1% hoger als een dwerghamster vrouwtje zich in een vijandige omgeving bevindt dan wanneer ze zich in een vriendelijke omgeving bevindt (95% BI [28.4, 65.7]%).\n\n***\n\n## Ongepaarde gegevens\n### Genetische associatie studie\n- Genetische associatiestudie polymorfismen in het BRCA1 gen geassocieerd is met borstkanker?\n- Retrospectieve case-controle studie met 800 borstkankercases en 572 controles\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.2.1     ✔ readr     2.2.0\n✔ forcats   1.0.1     ✔ stringr   1.6.0\n✔ ggplot2   4.0.3     ✔ tibble    3.3.1\n✔ lubridate 1.9.5     ✔ tidyr     1.3.2\n✔ purrr     1.2.2     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nbrca <- read_csv(\"https://raw.githubusercontent.com/statOmics/sbc/master/data/brca.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 1372 Columns: 3\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (3): cancer, variant, variant2\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(brca)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 3\n  cancer  variant variant2\n  <chr>   <chr>   <chr>   \n1 control pro/pro other   \n2 control pro/pro other   \n3 control pro/pro other   \n4 control pro/pro other   \n5 control pro/pro other   \n6 control pro/pro other   \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(brca)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       cancer          variant          variant2   \n Length   :1372   Length   :1372   Length   :1372  \n N.unique :   2   N.unique :   3   N.unique :   2  \n N.blank  :   0   N.blank  :   0   N.blank  :   0  \n Min.nchar:   4   Min.nchar:   7   Min.nchar:   5  \n Max.nchar:   7   Max.nchar:   7   Max.nchar:   7  \n```\n\n\n:::\n:::\n\n\n***\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Genotype |Controles   |Cases       |Totaal    |\n|:--------|:-----------|:-----------|:---------|\n|Pro/Pro  |266 (a)     |342 (d)     |608 (a+d) |\n|Pro/Leu  |250 (b)     |369 (e)     |619 (b+e) |\n|Leu/Leu  |56 (c)      |89 (f)      |145 (c+f) |\n|Totaal   |572 (a+b+c) |800 (d+e+f) |1372 (n)  |\n\n\n:::\n:::\n\n\n- In case-controle studies kiest men een vast aantal cases en controles en spoort men voor hen op welke blootstellingen ze in het verleden ondervonden hebben.\n- Dergelijke studies noemt men ook retrospectief\n- Onmogelijk om het risico's and riscoverschillen op borstkanker te schatten: proportie van cases en controles weerspiegelt populatie niet!\n\n***\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Genotype |Controles   |Cases       |Totaal    |\n|:--------|:-----------|:-----------|:---------|\n|Pro/Pro  |266 (a)     |342 (d)     |608 (a+d) |\n|Pro/Leu  |250 (b)     |369 (e)     |619 (b+e) |\n|Leu/Leu  |56 (c)      |89 (f)      |145 (c+f) |\n|Totaal   |572 (a+b+c) |800 (d+e+f) |1372 (n)  |\n\n\n:::\n:::\n\n\n- Wel mogelijk om kans te schatten om allel Leu/Leu\n    - cases: $\\pi_1=f/(d+e+f)=89/800=11.1\\%$\n    - controles:$\\pi_0=c/(a+b+c)=56/572=9.8\\%$\n- Relatief risico op blootstelling voor cases versus\ncontroles is bijgevolg $(89/800)/(56/572)=1.14$.\n- Vrouwen met borstkanker hebben dus 14% meer kans om de allelcombinatie Leu/Leu te hebben op het BRCA1 gen dan vrouwen zonder borstkanker.\n- Dit suggereert een associatie, maar drukt iet uit hoeveel hoger het risico op borstkanker is voor vrouwen met de allelcombinatie Leu/Leu dan voor andere vrouwen\n- Andere risicomaat?\n\n***\n\n\\begin{equation*}\nOdds=\\frac{p}{1-p}\n\\end{equation*}\nwaarbij $p$ de kans is op die gebeurtenis.\n\nTransformatie van het risico, met volgende eigenschappen:\n\n  - de odds neemt waarden aan tussen nul en oneindig.\n\n  - de odds is gelijk aan 1 als en slechts als de kans zelf gelijk is aan\n1/2.\n\n  - de odds neemt toe als de kans toeneemt.\n\n- populair bij gokkers: hoeveel waarschijnlijker het is om te winnen dan om te verliezen\n\n***\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Genotype |Controles   |Cases       |Totaal    |\n|:--------|:-----------|:-----------|:---------|\n|Pro/Pro  |266 (a)     |342 (d)     |608 (a+d) |\n|Pro/Leu  |250 (b)     |369 (e)     |619 (b+e) |\n|Leu/Leu  |56 (c)      |89 (f)      |145 (c+f) |\n|Totaal   |572 (a+b+c) |800 (d+e+f) |1372 (n)  |\n\n\n:::\n:::\n\n\nOdds op allel Leu/Leu\n\n- Cases: $\\mbox{odds}_1=\\frac{ f/(d+e+f)}{(d+e)/(d+e+f)}=f/(d+e)=89/711=0.125$. Vrouwen met borstkanker hebben ongeveer 8 keer meer kans om de allelcombinatie Leu/Leu niet te hebben op het BRCA1 gen dan om het wel te hebben.\n- Controles: $\\mbox{odds}_2=c/(a+b)=56/516=0.109$.\n\n- Associatie tussen blootstelling en uitkomst:\n$$\nOR_{Leu/Leu}=\\frac{\\mbox{odds}_T}{\\mbox{odds}_C}= \\frac{f/(d+e)}{c/(a+b)}=\\frac{f/(d+e)}{c/(a+b)}=1.15\n$$\n\n***\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Genotype |Controles   |Cases       |Totaal    |\n|:--------|:-----------|:-----------|:---------|\n|Pro/Pro  |266 (a)     |342 (d)     |608 (a+d) |\n|Pro/Leu  |250 (b)     |369 (e)     |619 (b+e) |\n|Leu/Leu  |56 (c)      |89 (f)      |145 (c+f) |\n|Totaal   |572 (a+b+c) |800 (d+e+f) |1372 (n)  |\n\n\n:::\n:::\n\n\n- Was de bovenstaande studie echter een volledig lukrake steekproef geweest\n(waarbij het aantal cases en controles niet per design werden vastgelegd),\n- dan konden we daar ook de odds ratio op borstkanker berekenen voor mensen\nmet versus zonder het allel Leu/leu.\n\\begin{equation*}\nOR_{case}=\\frac{ \\frac{ f}{c}}{ \\frac{(d+e)}{(a+b)}} = \\frac{f(a+b)}{c(d+e)}=OR_{Leu/Leu}=1.15,\n\\end{equation*}\n- OR is een symmetrische maat! OR op borstkanker kan wel worden geschat!\n- De odds op borstkanker is bijgevolg 15% hoger bij vrouwen met die specifieke allelcombinatie.\n\n***\n\n- Is verschil groot genoeg zodat we het effect die we in de steekproef zien kunnen veralgemenen naar de populatie toe.\n\n- Hiertoe zullen we de kruistabel eerst herschrijven tot een 2x2 tabel\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Genotype |Controles |Cases     |Totaal     |\n|:--------|:---------|:---------|:----------|\n|andere   |516 (a)   |711 (c)   |1227 (a+c) |\n|Leu/Leu  |56 (b)    |89 (d)    |145 (b+d)  |\n|Totaal   |572 (a+b) |800 (c+d) |1372 (n)   |\n\n\n:::\n:::\n\n\n***\n\n## De Pearson Chi-kwadraat test voor ongepaarde gegevens\n\n- Testen voor associatie tussen de categorische blootstelling (bvb. variant, X) en de categorische uitkomst (bvb. ziekte, Y).\n$$H_0: \\text{Er is geen associatie tussen } X \\text{ en } Y \\text{ vs } H_1: X \\text{ en } Y \\text{ zijn geassocieerd}$$\n\n- Beschouw de rijtotalen $n_\\text{andere}=a+c$, $n_\\text{leu,leu}=b+d$ enerzijds en\n- de kolomtotalen $n_\\text{contr}=a+b$ en $n_\\text{case}=c+d$ anderzijds.\n- Zij verstrekken informatie over de *marginale verdeling* van de blootstelling (bvb. variant, X) en de uitkomst (bvb. ziekte, Y),\nmaar niet over de associatie tussen die veranderlijken.\n- Onder $H_0$ zijn $X$ en $Y$ onafhankelijk zijn en verwacht men een proportie $(b+d)/n$\nvan $a+b$ controles met een Leu/Leu variant, of dat $(a+b)(b+d)/n$ een Leu/Leu variant hebben\n- Analoog kan men verwachte aantal $E_{ij}$ berekenen dat onder de nulhypothese in *elke cel* van de $2\\times 2$ tabel zou liggen.\n\n***\n\n- $E_{11}$ = het verwachte aantal onder $H_0$ in de (1,1)-cel = 145 $\\times$ 800/1372 = 84.55 ;\n\n- $E_{12}$ = het verwachte aantal onder $H_0$ in de (1,2)-cel = 145 $\\times$ 572/1372 = 60.45 ;\n\n- $E_{21}$ = het verwachte aantal onder $H_0$ in de (2,1)-cel = 1227 $\\times$ 800/1372 = 715.5 ;\n\n- $E_{22}$ = het verwachte aantal onder $H_0$ in de (2,2)-cel = 1227 $\\times$ 572/1372 = 511.5 ;\n\nToetsstatistiek:\n\\begin{eqnarray*}\nX^2 &=& \\frac{\\left (|O_{11} - E_{11}| - .5 \\right)^2 }{ E_{11}} + \\frac{\n\\left ( |O_{12} - E_{12}| - .5 \\right)^2 }{E_{12} }+ \\\\\n&&\\quad\\quad\n\\frac{ \\left ( |O_{21}\n- E_{21}| - .5 \\right)^2 }{E_{21}}+ \\frac{ \\left ( |O_{22} - E_{22}| - .5\n\\right)^2 }{E_{22} }\\\\\n X^2 &\\stackrel{H_0}{\\longrightarrow}& \\chi^2(df=1)\n\\end{eqnarray*}\n\n***\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](09-categoricalDataAnalysis_files/figure-html/unnamed-chunk-19-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n***\n\n- Toetsingsgrootheid  groot $\\longrightarrow$ indicatie voor\nafwijking van $H_0$.\n- De p-waarde voor een 2-zijdige toets is\nkans om grotere waarde voor toetsingsgrootheid te observeren dan\ngeobserveerde waarde $x^2$ als nulhypothese waar is $\\longrightarrow$ kans dat $\\chi^2_1$-verdeelde toevalsveranderlijke waarden groter dan $x^2$\naanneemt.\n\n***\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexpected <- matrix(0,nrow=2,ncol=2)\nfor (i in 1:2)\n\tfor (j in 1:2)\n\t\texpected[i,j] <-\n\t\t\tsum(brcaTab2[i,])*sum(brcaTab2[,j])/sum(brcaTab2)\nexpected\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         [,1]     [,2]\n[1,]  84.5481  60.4519\n[2,] 715.4519 511.5481\n```\n\n\n:::\n\n```{.r .cell-code}\nx2 <- sum((abs(brcaTab2-expected) - .5)^2/expected)\n1-pchisq(x2,1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.481519\n```\n\n\n:::\n:::\n\n\n***\n\n- Omdat observaties $O_{ij}$ discrete getallen zijn, kan\ntoetsingsgrootheid $X^2$ slechts discrete waarden aannemen en kan\ncontinue verdeling zoals $\\chi^2_1$-verdeling slechts een benadering zijn.\n- *continuïteitscorrectie*: 0.5 aftrekken van verwachte aantallen in elke cel $\\longrightarrow$ om beter aan te laten sluiten bij $\\chi^2_1$-verdeling\n- *Pearson\nChi-kwadraat toets met Yates correctie*.\n- Wanneer de correctie niet gebruikt\nwordt (d.w.z. wanneer de getallen `0.5' in de uitdrukking voor $X^2$ door 0\nvervangen worden), dan spreekt men van de *Pearson Chi-kwadraat toets*.\n\n***\n\nIn R kan je deze toetsen uitvoeren door de optie \\texttt{correct} op TRUE of FALSE te zetten:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchisq.test(brcaTab2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test with Yates' continuity correction\n\ndata:  brcaTab2\nX-squared = 0.49542, df = 1, p-value = 0.4815\n```\n\n\n:::\n\n```{.r .cell-code}\nchisq.test(brcaTab2, correct=FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  brcaTab2\nX-squared = 0.62871, df = 1, p-value = 0.4278\n```\n\n\n:::\n:::\n\n\n***\n\n- Zelfs met continuïteitscorrectie is $\\chi^2_1$ benadering slechts\nverantwoord als in geen enkele van de cellen het verwachte aantal onder\n$H_0$ kleiner is dan 5.\n- Wanneer de $\\chi^2$-benadering niet verantwoord is, kan men een  *Fisher's exact test* uitvoeren.\n-  De nulhypothese van deze test is eveneens dat $X$ en $Y$ onafhankelijk zijn, en de alternatieve hypothese dat $X$ en $Y$\nafhankelijk zijn.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfisher.test(brcaTab2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tFisher's Exact Test for Count Data\n\ndata:  brcaTab2\np-value = 0.4764\nalternative hypothesis: true odds ratio is not equal to 1\n95 percent confidence interval:\n 0.7998798 1.6738449\nsample estimates:\nodds ratio \n  1.153279 \n```\n\n\n:::\n:::\n\n\n***\n\n\n### Uitbreiding naar categorische variabelen met meerdere niveaus\n\n- $\\chi^2$-toets kan ook als minstens 1 van de discrete variabelen $X$ en $Y$ meer dan 2 mogelijke waarden aanneemt\n\n- Opnieuw: nulhypothese $H_0: X$ en $Y$ zijn onafhankelijk (niet-geassocieerd), ten opzichte van het tweezijdig alternatief $H_A: X$ en $Y$\nzijn niet onafhankelijk (geassocieerd).\n\n- Als de variabele voorgesteld op de rijen $r$ mogelijke uitkomsten heeft en die op de kolommen $c$ mogelijke uitkomsten,\ndan noemt men de kruistabel die $X$ tegenover $Y$ uitzet, een $r \\times c$ tabel.\n\n- Zoals voorheen vergelijkt men het aantal geobserveerde waarden in cel $(i,j)$, $O_{ij}$ genoteerd, met het aantal verwachte waarden onder de nulhypothese, $E_{ij}$\n -Opnieuw is $E_{ij}$ product van het $i$-de rijtotaal met het $j$-de\nkolomtotaal gedeeld door het algemene totaal.\n\n\\begin{equation*}\nX^2 = \\sum_{ij} \\frac{\\left (O_{ij} - E_{ij}\\right)^2 }{ E_{ij}}\n\\end{equation*}\n\n***\n\n- Men kan aantonen dat ze een Chi-kwadraat verdeling volgt met $(r-1) \\times\n(c-1)$ vrijheidsgraden als de nulhypothese waar is.\n- De continuïteitscorrectie wordt meestal niet gebruikt bij meer dan 2 rijen of\nkolommen.\n- **Pearson $\\chi^2$ test** is analogon van de one-way variantie-analyse voor kwalitatieve i.p.v. continue variabelen.\n\n***\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbrcaTab <- table(brca$variant,brca$cancer)\nchisq.test(brcaTab)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  brcaTab\nX-squared = 2.0551, df = 2, p-value = 0.3579\n```\n\n\n:::\n:::\n\n\n- Om te onderzoeken of het BRCA1 gen geassocieerd is met borstkanker, berekenen we de Pearson chi-kwadraat toets voor de case-controle studie.\n- De toetsingsgrootheid bedraagt nu 2.055 en volgt een Chi-kwadraat verdeling met 2 vrijheidsgraden. De kans dat zo’n $\\chi^2$- verdeelde toevalsveranderlijke extremer is dan 2.055, bedraagt 36%.\n- Op het 5% significantieniveau kunnen we dus niet besluiten dat het BRCA1 gen geassocieerd is met borstkanker.\n\n***\n\n# Logistische regressie\n\n- Raamwerk voor het modelleren van binaire data (vb. kanker vs geen kanker): *logistische regressie-modellen*.\n- Binaire gegevens modelleren a.d.h.v. continue en/of dummy variabelen.\n\n- De modellen veronderstellen dat observaties voor subject $i=1,\\ldots,n$ onafhankelijk zijn en een Bernoulli verdeling volgen.\n- Het logaritme van de odds wordt dan gemodelleerd d.m.v. een lineair model, ook wel lineaire predictor genoemd:\n\\begin{equation}\n\\left\\{\n\\begin{array}{ccl}\nY_i&\\sim&B(\\pi_i)\\\\\\\\\nE[Y_i] &=& \\pi_i\\\\\\\\\n\\log \\frac{\\pi_i}{1-\\pi_i}&=&\\beta_0 + \\beta_1X_{i1} + \\ldots + \\beta_p X_{ip}\n\\end{array}\\right.\n\\end{equation}\n\n***\n\n## Categorische predictor\n\n- Borstkanker voorbeeld: is BRCA 1 variant geassocieerd is met het krijgen van borstkanker.\n\n- Net zoals in de anova context, factor in het regressieraamwerk d.m.v. dummy variabelen.\n- 1 dummy variable minder nodig hebben dan er groepen zijn.\n\n- Voor het BRCA 1 voorbeeld zijn dus twee dummy variabelen nodig en kunnen we de data dus modelleren met onderstaande lineaire predictor:\n\n\\begin{eqnarray*}\n  \\log \\frac{\\pi_i}{1-\\pi_i} &=& \\beta_0+\\beta_1 x_{i1} +\\beta_2 x_{i2}\n\\end{eqnarray*}\n\n***\n\n- Waarbij de predictoren dummy-variabelen zijn:\n$$x_{i1} = \\left\\{ \\begin{array}{ll}\n1 & \\text{ als subject $i$ heterozygoot is, Pro/Leu variant} \\\\\n0 & \\text{ als subject $i$ homozygoot is, (Pro/Pro of Leu/Leu variant)} \\end{array}\\right. .$$\n$$x_{i2} = \\left\\{ \\begin{array}{ll}\n1 & \\text{ als subject $i$ homozygoot is in de Leucine mutatie: Leu/Leu } \\\\\n0 & \\text{ als subject $i$ niet homozygoot is in de Leu/Leu variant} \\end{array}\\right. .$$\n\n- Homozygositeit in het wild type allel Pro/Pro wordt voor  dit model de **referentiegroep**.\n\n***\n\n\nWe fitten het model in R.\n\n- Merk op dat we functie `as.factor` gebruiken om de cancer variabele om te zetten naar een factor.\n- en dat we de functie `relevel` gebruiken om de controles als referentie groep de definiëren: eerste niveau van de factor.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbrca <- brca |>\n  mutate(\n    cancer = cancer |>\n      as.factor() |>\n      relevel(\"control\"),\n    variant = variant |>\n      as.factor() |>\n      relevel(\"pro/pro\")\n  )\n\nbrcaLogit <- glm(\n  cancer ~ variant,\n  data = brca,\n  family = binomial)\n\nsummary(brcaLogit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = cancer ~ variant, family = binomial, data = brca)\n\nCoefficients:\n               Estimate Std. Error z value Pr(>|z|)   \n(Intercept)     0.25131    0.08175   3.074  0.00211 **\nvariantleu/leu  0.21197    0.18915   1.121  0.26243   \nvariantpro/leu  0.13802    0.11573   1.193  0.23302   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1863.9  on 1371  degrees of freedom\nResidual deviance: 1861.9  on 1369  degrees of freedom\nAIC: 1867.9\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n:::\n\n\n\nHet intercept is de log-odds op kanker in de referentieklasse (Pro/Pro) en de hellingstermen zijn log odds ratio's tussen de behandeling en de referentieklasse:\n\\begin{eqnarray*}\n\\log \\text{ODDS}_\\text{Pro/Pro}&=&\\beta_0\\\\\\\\\n\\log \\text{ODDS}_\\text{Pro/Leu}&=&\\beta_0+\\beta_1\\\\\\\\\n\\log \\text{ODDS}_\\text{Leu/Leu}&=&\\beta_0+\\beta_2\\\\\\\\\n\\log  \\frac{\\text{ODDS}_\\text{Pro/Leu}}{\\text{ODDS}_\\text{Pro/Pro}}&=&\\log \\text{ODDS}_\\text{Pro/Leu}-\\log ODDS_{Pro/Pro}\\\\\n&=&\\beta_0+\\beta_1-\\beta_0=\\beta_1\\\\\\\\\n\\log  \\frac{\\text{ODDS}_\\text{Leu/Leu}}{\\text{ODDS}_\\text{Pro/Pro}}&=&\\beta_2\n\\end{eqnarray*}\n\n- De analyse laat dus toe om de resultaten onmiddellijk te interpreteren in termen van Odds'es en Odds-ratio's!\n\n***\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(brcaLogit, test = \"Chisq\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Deviance Table\n\nModel: binomial, link: logit\n\nResponse: cancer\n\nTerms added sequentially (first to last)\n\n        Df Deviance Resid. Df Resid. Dev Pr(>Chi)\nNULL                     1371     1863.9         \nvariant  2   2.0562      1369     1861.9   0.3577\n```\n\n\n:::\n:::\n\n\nDe $\\chi^2$-test op het logistische regressiemodel geeft eveneens aan dat er geen significante associatie is tussen de uitkomst (voorkomen van kanker) en de factor ( de genetische variant van het BRCA gen) ($p=$ 0.358).\nDe p-waarde is bijna equivalent aan de p-waarde van de $\\chi^2$-test uit de vorige sectie.\n\n***\n\n- Significante associatie? Post-hoc tests om te evalueren welke odds ratio's verschillend zijn.\n- Voor het BRCA1 voorbeeld zouden we uiteraard geen post-hoc testen\n- Toch illustratie zodat jullie over de code beschikken\n\n\n***\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsuppressPackageStartupMessages({library(multcomp)})\nposthoc <- glht(brcaLogit, linfct = mcp(variant = \"Tukey\"))\nposthocTests <- summary(posthoc)\nposthocTests\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t Simultaneous Tests for General Linear Hypotheses\n\nMultiple Comparisons of Means: Tukey Contrasts\n\n\nFit: glm(formula = cancer ~ variant, family = binomial, data = brca)\n\nLinear Hypotheses:\n                       Estimate Std. Error z value Pr(>|z|)\nleu/leu - pro/pro == 0  0.21197    0.18915   1.121    0.493\npro/leu - pro/pro == 0  0.13802    0.11573   1.193    0.449\npro/leu - leu/leu == 0 -0.07395    0.18922  -0.391    0.917\n(Adjusted p values reported -- single-step method)\n```\n\n\n:::\n:::\n\n\n***\n\n\n::: {.cell}\n\n```{.r .cell-code}\nposthocBI <- confint(posthoc)\nposthocBI\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t Simultaneous Confidence Intervals\n\nMultiple Comparisons of Means: Tukey Contrasts\n\n\nFit: glm(formula = cancer ~ variant, family = binomial, data = brca)\n\nQuantile = 2.3251\n95% family-wise confidence level\n \n\nLinear Hypotheses:\n                       Estimate lwr      upr     \nleu/leu - pro/pro == 0  0.21197 -0.22782  0.65176\npro/leu - pro/pro == 0  0.13802 -0.13106  0.40711\npro/leu - leu/leu == 0 -0.07395 -0.51390  0.36600\n```\n\n\n:::\n:::\n\n- Door middel van de `confint` functie worden BI's verkregen op de log-odds ratios die gecorrigeerd zijn voor multiple testing.\n\n***\n\n- BI's kunnen als volgt worden teruggetransformeerd naar odds ratios:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nOR <- exp(posthocBI$confint)\nOR\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   Estimate       lwr      upr\nleu/leu - pro/pro 1.2361111 0.7962688 1.918913\npro/leu - pro/pro 1.1480000 0.8771612 1.502465\npro/leu - leu/leu 0.9287191 0.5981573 1.441960\nattr(,\"conf.level\")\n[1] 0.95\nattr(,\"calpha\")\n[1] 2.32512\n```\n\n\n:::\n:::\n\n\n- De odds ratios die worden bekomen met het logistisch regressiemodel zijn exact gelijk aan de odds ratios die we zouden bekomen op basis van Tabel:\n- vb.  $\\text{OR}_\\text{Leu/Leu-Pro/Pro}=89\\times 266/(56\\times 342)=$ 1.236.\n\n- Merk op dat de statistische besluitvorming bij logistische modellen beroep doet op asymptotische theorie.\n\n***\n\n## Continue predictor\n\n- Toxicologisch effect van koolstofdisulfide (CS$_2$) op kevers.\n\n- De centrale onderzoeksvraag is of de concentratie van CS$_2$ een effect heeft op de mortaliteit (i.e. kans op sterven) van de kevers?\n\n**Design**\n\n- 32 onafhankelijk experimenten\n- Telkens 1 kever blootgesteld aan één van 8 concentraties (mg/l) van CS$_2$ voor een gegeven periode.\n- De uitkomst van het experiment is: de kever sterft ($y=1$) of de kever overleeft ($y=0$).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbeetles <- read_csv(\"https://raw.githubusercontent.com/statomics/sbc/master/data/beetles.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 32 Columns: 2\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\ndbl (2): dose, status\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(beetles)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 2\n   dose status\n  <dbl>  <dbl>\n1  169.      1\n2  169.      0\n3  169.      0\n4  169.      0\n5  172.      1\n6  172.      0\n```\n\n\n:::\n\n```{.r .cell-code}\ntable(beetles$dose, beetles$status)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        \n         0 1\n  169.07 3 1\n  172.42 3 1\n  175.52 3 1\n  178.42 2 2\n  181.13 1 3\n  183.69 0 4\n  186.1  0 4\n  188.39 0 4\n```\n\n\n:::\n:::\n\n\n***\n\nLogistisch regressiemodel dat log odds modelleert in functie van dosis $x_i$:\n$$\\log \\frac{\\pi_i}{1-\\pi_i}=\\beta_0+\\beta_1 \\times x_i.$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbeetleModel<-glm(\n  status~dose,\n  data = beetles,\n  family = binomial)\n\nsummary(beetleModel)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = status ~ dose, family = binomial, data = beetles)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)   \n(Intercept) -53.1928    18.0046  -2.954  0.00313 **\ndose          0.3013     0.1014   2.972  0.00296 **\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 42.340  on 31  degrees of freedom\nResidual deviance: 26.796  on 30  degrees of freedom\nAIC: 30.796\n\nNumber of Fisher Scoring iterations: 5\n```\n\n\n:::\n:::\n\n\n----\n\n- Intercept: log odds op mortaliteit wanneer er geen $\\text{CS}_2$ gas wordt toegediend.\n- Erg lage odds op sterfte ($\\pi/(1-\\pi)=\\exp(-53.2)$) en dus op een kans die nagenoeg nul is.\n- Merk op: heel sterke extrapolatie: minimum dosis in de dataset 169.07 mg/l.\n\n\n- Geschatte odds ratio voor dosis effect op de mortaliteitskans is $\\exp(0.3013)=1.35$.\n- Dus bij een toename van de dosis CS$_2$ met 1 mg/l, is de odds ratio voor de mortaliteit $1.35$.\n\n***\n\n- We besluiten dat dit effect heel significant is ($p=$ 0.003).\n- Een toename in de CS$_2$  dosis doet de kans op sterven toenemen.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbeetlesTab<-table(beetles) |> data.frame()\n\ndata.frame(\n    grid = seq(\n      min(beetles$dose),\n      max(beetles$dose),.1)\n  ) |>\n  mutate(piHat = predict(beetleModel,\n\t      newdata = data.frame(dose=grid),\n\t      type = \"response\")\n  ) |>\n  ggplot(aes(grid, piHat))+\n  geom_line() +\n  xlab(\"dose\") +\n  ylab(\"probability (dead)\") +\n  geom_text(\n    aes(x = dose |>\n          as.character() |>\n          as.double(),\n        y = status |>\n          as.character() |>\n          as.double(),\n        label = Freq),\n    beetlesTab |>\n      filter(status==0)\n  ) +\n  geom_text(\n    aes(x = dose |>\n          as.character() |>\n          as.double(),\n        y = status |>\n          as.character() |>\n          as.double(),\n       label=Freq),\n   beetlesTab |>\n    filter(status==1)\n  )\n```\n\n::: {.cell-output-display}\n![](09-categoricalDataAnalysis_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n\n\n***\n",
    "supporting": [
      "09-categoricalDataAnalysis_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}