{
  "hash": "419a786ee2b3e4afdbdac7d2c98afbc2",
  "result": {
    "engine": "knitr",
    "markdown": "# Algemeen lineair model {#sec-chap-glm}\n\n\nAlle kennisclips die in dit hoofdstuk zijn verwerkt kan je in deze youtube playlist vinden:\n\n- [Kennisclips Hoofdstuk 10 Algemeen Lineair Model](https://www.youtube.com/playlist?list=PLZH1hP8_LbJLuEaRpvAkW7oQLCCjHqUS4)\n\nLink naar webpage/script die wordt gebruik in de kennisclips:\n\n- [script Hoofdstuk 10](https://statomics.github.io/sbc/rmd/10-MultipleRegression.html)\n\n## Inleiding\n\n<iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/3ltCTl4stEI\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n\nTot nog toe hebben we ons geconcentreerd op het beschrijven van een\nassociatie tussen een uitkomst $Y$ en één enkele predictor $X$.\nVaak is het echter nuttig om de gemiddelde uitkomst niet in termen van\néén, maar in termen van meerdere predictoren simultaan te beschrijven.\nDe volgende voorbeelden illustreren waarom:\n\n1. Vaak is de associatie tussen een verklarende variabele X en een uitkomst Y verstoord als gevolg van een confounder C. Bijvoorbeeld, bij het bepalen van het effect van de duur van blootstelling aan asbest (X) op de longfunctie (Y), is leeftijd (C) een confounder omdat het zowel de duur van blootstelling als de longfunctie beïnvloedt. Om hiervoor te corrigeren, is het noodzakelijk om de associatie tussen X en Y afzonderlijk te beschrijven voor mensen van dezelfde leeftijd (m.a.w. individuen met dezelfde waarde voor de confounder). Voor elke geobserveerde leeftijd (C=c) een aparte lineaire regressie uitvoeren onder mensen van die leeftijd (C=c), is weinig zinvol omdat er vaak weinig mensen met exact dezelfde leeftijd in de studie opgenomen zijn. Dit is in het bijzonder zo wanneer er meerdere confounders zijn. In deze sectie zullen we dit probleem oplossen door de confounder C als extra variabele in het lineaire model op te nemen.\n\n2. In heel wat studies is men geïnteresseerd in welke van een groep variabelen een gegeven uitkomst het meest beïnvloedt. Bijvoorbeeld, het begrijpen van welke aspecten van habitat en menselijke activiteit een voorname impact hebben op de biodiversiteit in het regenwoud is een belangrijk streefdoel van de conservatie-biologie. Daartoe wil men niet alleen de grootte van het woud in rekening brengen, maar ook andere factoren, zoals de ouderdom en hoogteligging van het woud, de nabijheid van andere wouden, ... Een studie van het simultane effect van die verschillende variabelen laat toe om beter inzicht te krijgen in de variatie in biodiversiteit tussen verschillende wouden. Door in het bijzonder wouden met hoge of lage biodiversiteit nader te bekijken, kan men nieuwe predictieve factoren voor biodiversiteit ontdekken.\n\n3. Wanneer men een uitkomst wil voorspellen voor individuen, is het belangrijk om veel predictieve informatie voor hen beschikbaar te hebben en die informatie simultaan in een regressiemodel te kunnen gebruiken. Bijvoorbeeld, na behandeling van patiënten met gevorderde borstkanker is de prognose zeer onzeker. Op basis van gemeten predictoren voor en na de operatie kan men echter regressiemodellen opbouwen die toelaten om in de toekomst voor elke patiënt, op basis van zijn/haar karakteristieken, de prognose te voorspellen. Verwante predicties (maar dan voor het risico op sterfte) worden dagdagelijks gebruikt in eenheden intensieve zorgen om de ernst van de gezondheidstoestand van een patiënt uit te drukken. Het spreekt voor zich dat betere predicties kunnen gemaakt worden wanneer een groot aantal predictoren simultaan worden in rekening gebracht.\n\nIn dit hoofdstuk breiden we daarom enkelvoudige lineaire regressie (Hoofdstuk -@sec-chap-linReg) uit door meerdere predictoren toe te laten. We zullen dus de gemiddelde uitkomsten modelleren als een functie van meerdere predictoren.\nWe illustreren meervoudige lineaire regressie aan de hand van de prostaatkanker dataset.\n\n<!---break-->\n\n### Prostaatkanker dataset {#sec-prostate}\n\n<iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/ZdZ5XLaDZi0\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n\nStamey et al., 1989, bestudeerden het niveau van het prostaat specific antigen (PSA) en een aantal klinische metingen bij 97 mannen waarvan de prostaat werd verwijderd.\nHet doel van de studie is om de associatie van de PSA te bestuderen in functie van het tumorvolume (lcavol), het gewicht van de prostaat (lweight), leeftijd (age), de goedaardige prostaathypertrofie hoeveelheid (lbph), een indicator voor de aantasting van de zaadblaasjes (svi), capsulaire penetratie (lcp), Gleason score (gleason) die de graad van kwaadaardigheid van de kanker weergeeft (hoe hoger de score hoe minder de kankercellen op normaal prostaatweefsel lijken), en, het precentage gleason score 4/5 (pgg45), die de proportie aangeeft van de tumor die ingenomen wordt door kankerweefsel van een hoge graad. De onderzoekers die de dataset verspreidden hebben het tumorvolume, het gewicht, de goedaardige prostraat hypertrofie hoeveelheid en de capsulaire penetratie reeds log-getransformeerd.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprostate <- read_csv(\"https://raw.githubusercontent.com/statomics/sbc/master/data/prostate.csv\")\nprostate\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 97 × 9\n   lcavol lweight   age   lbph svi       lcp gleason pgg45     lpsa\n    <dbl>   <dbl> <dbl>  <dbl> <chr>   <dbl>   <dbl> <chr>    <dbl>\n 1 -0.580    2.77    50 -1.39  healthy -1.39       6 healthy -0.431\n 2 -0.994    3.32    58 -1.39  healthy -1.39       6 healthy -0.163\n 3 -0.511    2.69    74 -1.39  healthy -1.39       7 20      -0.163\n 4 -1.20     3.28    58 -1.39  healthy -1.39       6 healthy -0.163\n 5  0.751    3.43    62 -1.39  healthy -1.39       6 healthy  0.372\n 6 -1.05     3.23    50 -1.39  healthy -1.39       6 healthy  0.765\n 7  0.737    3.47    64  0.615 healthy -1.39       6 healthy  0.765\n 8  0.693    3.54    58  1.54  healthy -1.39       6 healthy  0.854\n 9 -0.777    3.54    47 -1.39  healthy -1.39       6 healthy  1.05 \n10  0.223    3.24    63 -1.39  healthy -1.39       6 healthy  1.05 \n# ℹ 87 more rows\n```\n\n\n:::\n\n```{.r .cell-code}\nprostate$svi <- as.factor(prostate$svi)\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(GGally)\nprostate |>\n  dplyr::select(-pgg45)  |>\n  ggpairs()\n```\n\n::: {.cell-output-display}\n![Scatterplot matrix voor de observaties in de prostaat kanker dataset.](10-GeneralLinearModel_files/figure-epub/fig-lpsaAll-1.png){#fig-lpsaAll fig-align='center' width=100%}\n:::\n:::\n\n\nFiguur -@fig-lpsaAll toont de scatter matrix van de data en suggereert dat de lpsa sterk positief gecorreleerd is met het volume en svi.\nWe zien verder dat lcp en lbph links-gecensureerd lijken te zijn. Er lijkt een ondergrens/detectielimiet te zijn voor deze metingen. Verder blijkt het merendeel van de gleason scores gelijk te zijn aan 6 of 7. We zullen de analyse in dit hoofdstuk beperken tot de associatie van lpsa met het log tumorvolume (lcavol), het log gewicht (lweight) en de aantasting van de zaadblaasjes (svi).\n\n\n\n## Het additieve meervoudig lineaire regressie model\n\n<iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/vATACtD6kpU\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n\nAfzonderlijke lineaire regressiemodellen, zoals\n\n$$E(Y|X_v)=\\alpha+\\beta_v X_v$$\n\nlaten enkel toe om de associatie tussen de prostaat specifieke antigeen concentratie te evalueren op basis van 1 variabele, bijvoorbeeld het log-tumorvolume. Het spreekt voor zich dat meer accurate predicties kunnen bekomen worden door meerdere predictoren simultaan in rekening te brengen.\nBovendien geeft de parameter $\\beta_v$ in dit model mogelijks geen zuiver effect van het tumorvolume weer. Inderdaad, $\\beta_v$ is het gemiddeld verschil in log-psa voor patiënten die 1 eenheid in het log tumorvolume (lcavol) verschillen. Zelfs als lcavol niet is geassocieerd met het lpsa,  dan nog kunnen patiënten met een groter tumorvolume een hoger lpsa hebben omdat ze bijvoorbeeld een aantasting van de zaadblaasjes hebben (svi status 1). Dit is een probleem van confounding (nl. het effect van lcavol wordt verward met het effect van svi) dat kan verholpen worden door patiënten te vergelijken met verschillend log-tumorvolume, maar met dezelfde status voor svi. We zullen in dit hoofdstuk aantonen dat meervoudige lineaire regressiemodellen dit op een natuurlijke wijze mogelijk maken.\n\n### Statistisch model\n\nDe techniek die we hiertoe gaan gebruiken heet *meervoudige lineaire regressie*, in tegenstelling tot *enkelvoudige lineaire regressie* die we eerder gebruikt hebben.\nStel dat we $p-1$ verklarende variabelen $X_1,...,X_{p-1}$ en een uitkomst $Y$ beschikbaar hebben voor $n$\nsubjecten.\nStel bovendien dat de gemiddelde uitkomst lineair kan beschreven worden in functie van deze verklarende variabelen; d.w.z.\n\n$$\nY_i =\\beta_0 + \\beta_1 X_{i1} + ... +\\beta_{p-1} X_{ip-1} + \\epsilon_i\n$$\n\nwaarbij $\\beta_0,\\beta_1,...,\\beta_{p-1}$ onbekende parameters zijn en $\\epsilon_i$ de residuen die niet kunnen worden verklaard a.d.h.v. de predictoren.\nHet principe van de *kleinste kwadratenmethode* kan ook voor dit model worden gebruikt om schatters te bekomen voor de onbekende parameters\n $\\beta_0, \\ldots, \\beta_{p-1}$.\nDe formules voor deze schattingen zijn nu een stuk complexer dan voorheen, maar worden door de software automatisch uitgerekend.\nVoor gegeven\nschattingen $\\hat{\\beta}_0,\\hat{\\beta}_1,...,\\hat{\\beta}_{p-1}$ laat het lineaire\nregressiemodel dan toe om:\n\n1. de verwachte uitkomst te voorspellen voor subjecten met gegeven\nwaarden $x_1,...,x_{p-1}$ voor de verklarende variabelen.\nDit kan geschat worden als\n\n$$\nE[Y\\vert X_1=x_1, \\ldots X_{p-1}=x_{p-1}]=\\hat{\\beta}_0+\\hat{\\beta}_1x_1+...+\\hat{\\beta}_{p-1}x_{p-1}\n$$\n\n2. na te gaan in welke mate de gemiddelde uitkomst verschilt tussen 2 groepen subjecten met $\\delta$ eenheden verschil in een verklarende variabele $X_j$ met $j=1,\\ldots,p$, maar met dezelfde waarden voor alle andere variabelen $\\{X_k,k=1,...,p,k\\ne j\\}$.\nNamelijk:\n\n$$\n\\begin{array}{l}\nE(Y|X_1=x_1,...,X_j=x_j+\\delta,...,X_{p-1}=x_{p-1}) - E(Y|X_1=x_1,...,X_j=x_j,...,X_{p-1}=x_{p-1}) \\\\\n\\quad =\\beta_0 + \\beta_1 x_1 + ... + \\beta_j(x_j+\\delta)+...+\\beta_{p-1} x_{p-1} - \\beta_0 - \\beta_1 x_1 - ... - \\beta_jx_j-...-\\beta_{p-1} x_{p-1} \\\\\n\\quad= \\beta_j\\delta\n\\end{array}\n$$\n\nIn het bijzonder kan $\\beta_j$ geïnterpreteerd worden als het verschil in gemiddelde uitkomst tussen subjecten die 1 eenheid verschillen in de\nwaarde van $X_j$, maar dezelfde waarde hebben van de overige verklarende variabelen in het model. Dit kan geschat worden als $\\hat{\\beta}_j$.\n\n<!---break-->\n\n<iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/5Im-lIB4jGs\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n\n\nVoor het prostaatkanker voorbeeld levert een analyse van het enkelvoudige lineaire regressiemodel $E(Y|X_v)=\\beta_0+\\beta_v X_v$ in R de volgende output.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlmV <- lm(lpsa ~ lcavol, prostate)\nsummary(lmV)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = lpsa ~ lcavol, data = prostate)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.67624 -0.41648  0.09859  0.50709  1.89672 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  1.50730    0.12194   12.36   <2e-16 ***\nlcavol       0.71932    0.06819   10.55   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.7875 on 95 degrees of freedom\nMultiple R-squared:  0.5394,\tAdjusted R-squared:  0.5346 \nF-statistic: 111.3 on 1 and 95 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nWe besluiten op basis van deze gegevens dat patiënten met een tumorvolume dat  1\\% hoger ligt, gemiddeld gezien een prostaat antigeen concentratie zullen hebben die ongeveer 0.72% hoger zal liggen. Merk op dat we voor deze interpretatie beroep hebben gedaan op het feit dat beide variabelen log getransformeerd zijn.\n\nEen analyse van het meervoudige lineaire regressiemodel met de predictoren lcavol (index v), lweight (index w) en svi (index  s)\n\n$$\nE(Y|X_v,X_w,X_s)=\\beta_0 +\\beta_v X_v+\\beta_w X_w+\\beta_s X_s,\n$$\n\nwijzigt dit resultaat vrij behoorlijk, zoals onderstaande output aangeeft.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlmVWS <- lm(lpsa~lcavol + lweight + svi, prostate)\nsummary(lmVWS)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = lpsa ~ lcavol + lweight + svi, data = prostate)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.72966 -0.45767  0.02814  0.46404  1.57012 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -0.26807    0.54350  -0.493  0.62301    \nlcavol       0.55164    0.07467   7.388  6.3e-11 ***\nlweight      0.50854    0.15017   3.386  0.00104 ** \nsviinvasion  0.66616    0.20978   3.176  0.00203 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.7168 on 93 degrees of freedom\nMultiple R-squared:  0.6264,\tAdjusted R-squared:  0.6144 \nF-statistic: 51.99 on 3 and 93 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nDe parameter bij lcavol geeft nu aan dat patiënten met een tumorvolume dat  1% hoger ligt, maar eenzelfde prostaat gewicht en svi status hebben, een prostaat antigeen concentratie zullen hebben dat gemiddeld slechts 0.55% hoger ligt.\nDe reden dat we eerder een verschil van meer dan 0.7% vonden, kan worden verklaard doordat patiënten met een verschil in tumorvolume vaak ook verschillen in prostaat gewicht en svi status.\n\nDe parameter voor svi kunnen we als volgt interpreteren: de prostaat antigeen concentratie ligt gemiddeld een factor exp(0.666)=1.95 hoger voor patiënten met invasie van de zaadblaasjes dan voor patiënten zonder invasie van de zaadblaasjes na correctie voor het prostaat gewicht en het tumorvolume. De introductie van de factor svi in het additieve model zorgt ervoor dat we twee regressievlakken bekomen die evenwijdig zijn maar een verschillend intercept hebben (zie Figuur -@fig-prosAdditiveFit).\n\nDe $R^2$-waarde in bovenstaande analyse bedraagt 62.6%  en geeft aan  62.6% in de variabiliteit van het log-PSA verklaard kan worden d.m.v. het tumorvolume, het prostaat gewicht en de status van de zaadblaasjes.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Fit van het additieve model met termen lcavol, lweight en svi. De figuur geeft duidelijk weer dat de gemiddelde lpsa toeneemt i.f.v. het log-tumorvolume, het log-prostaatgewicht en de invasie van de zaadblaasjes. Merk op dat de fit resulteert in twee parallele vlakken, een regressievlak voor patiënten zonder (blauw) en met invasie van de zaadblaasjes (oranje).](10-GeneralLinearModel_files/figure-epub/fig-prosAdditiveFit-1.png){#fig-prosAdditiveFit fig-align='center' width=100%}\n:::\n:::\n\n\n## Besluitvorming in regressiemodellen\n\n<iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/6AbrMvfGXVw\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n\nAls de gegevens representatief zijn voor de populatie kan men in de meervoudige lineaire regressiecontext eveneens aantonen dat de kleinste kwadraten schatters voor het intercept en de hellingen onvertekend zijn, m.a.w\n\n$$E[\\hat \\beta_j]=\\beta_j,\\quad j=0,\\ldots,p-1.$$\n\nHet feit dat de schatters gemiddeld (over een groot aantal vergelijkbare studies) niet afwijken van de waarden in de populatie, impliceert niet dat ze niet rond die waarde variëren.\nOm inzicht te krijgen hoe dicht we de parameterschatters bij het werkelijke intercept $\\beta_0$ en de werkelijke hellingen $\\beta_j$  mogen verwachten, wensen we bijgevolg ook haar variabiliteit te kennen.\n\nNet zoals in Hoofdstuk -@sec-chap-linReg is het op basis van de puntschatters voor de hellingen niet duidelijk of de verbanden werkelijk voorkomen in de populatie of indien we de verbanden door toeval hebben geobserveerd in de dataset.\nDe schatting van de hellingen is immers onnauwkeurig en zal variëren van steekproef tot steekproef.\nZoals steeds is het resultaat van een data-analyse dus niet interpreteerbaar zonder die variabiliteit in kaart te brengen.\n\nOm de resultaten uit de steekproef te kunnen veralgemenen naar de populatie zullen we in deze context eveneens inzicht nodig hebben op de verdeling van de parameterschatters.\nOm op basis van slechts één steekproef te kunnen voorspellen hoe de parameterschatters variëren van steekproef tot steekproef zullen we naast de onderstelling van\n\n1. *Lineariteit*\n\n    bijkomende aannames moeten maken over de verdeling van de gegevens, met name\n\n2. *Onafhankelijkheid*: de metingen $(X_{11},\\dots, X_{1p-1}, Y_1), ...,  (X_{n1},\\ldots,X_{np-1},Y_n)$ werden gemaakt bij n onafhankelijke subjecten/observationele eenheden\n3. *Homoscedasticiteit* of *gelijkheid van variantie*: de observaties variëren met een gelijke variantie rond het regressievlak. De residuen $\\epsilon_i$ hebben dus een gelijke variantie $\\sigma^2$ voor elk covariaat patroon $(X_1=x_1, ..., X_{p-1}=x_{p-1})$. Dat impliceert ook dat de conditionele variantie van $Y$ gegeven $X_1,\\ldots,X_{p-1}$, $\\text{var}(Y\\vert X_1,\\ldots,X_{p-1})$ dus gelijk is, met name $\\text{var}(Y\\vert  X_1,\\ldots,X_{p-1}) = \\sigma^2$ voor elk covariaat patroon  $(X_1=x_1, ..., X_{p-1}=x_{p-1})$.  De constante $\\sigma$ wordt opnieuw de *residuele standaarddeviatie* genoemd.\n4. *Normaliteit*: de residuen $\\epsilon_i$ zijn normaal verdeeld.\n\nUit aannames 2, 3 en 4 volgt dus dat de residuen $\\epsilon_i$ onafhankelijk zijn en dat ze allen eenzelfde Normale verdeling volgen\n\n$$\\epsilon_i \\sim N(0,\\sigma^2).$$\n\nAls we ook steunen op de veronderstelling van lineariteit weten we dat de originele observaties conditioneel op $X_1,\\ldots,X_{p-1}$ eveneens Normaal verdeeld zijn\n\n$$Y_i\\sim N(\\beta_0+\\beta_1 X_{i1}+\\ldots+\\beta_{p-1} X_{ip-1},\\sigma^2),$$\n\nmet een gemiddelde dat varieert in functie van de waarde van de onafhankelijke variabelen $X_{i1},\\ldots,X_{ip-1}$.\n\nMerk op dat de onzekerheid op de hellingen af zal nemen wanneer er meer observaties zijn en/of wanneer de observaties meer gespreid zijn. Voor het opzetten van een experiment kan dit belangrijke informatie zijn. Uiteraard wordt de precisie ook beïnvloed door de grootte van de variabiliteit van de observaties rond het regressievlak, $\\sigma^2$, maar dat heeft een onderzoeker typisch niet in de hand.\n\nDe conditionele variantie ($\\sigma^2$) is echter niet gekend en is noodzakelijk voor de berekening van de variantie op de parameterschatters. We kunnen $\\sigma^2$ echter opnieuw schatten op basis van  de *mean squared error* (MSE):\n\n$$\\hat\\sigma^2=MSE=\\frac{\\sum\\limits_{i=1}^n \\left(y_i-\\hat\\beta_0-\\hat\\beta_1 X_{i1}-\\ldots-\\hat\\beta_{p-1} X_{ip-1}\\right)^2}{n-p}=\\frac{\\sum\\limits_{i=1}^n e^2_i}{n-p}.$$\n\nAnaloog als in Hoofdstuk -@sec-chap-linReg kunnen we opnieuw toetsen en betrouwbaarheidsintervallen construeren op basis van de teststatistieken  \n\n$$T_k=\\frac{\\hat{\\beta}_k-\\beta_k}{SE(\\hat{\\beta}_k)} \\text{ met } k=0, \\ldots, p-1.$$\n\nAls aan alle aannames is voldaan dan volgen deze statistieken $T_k$ een t-verdeling met $n-p$ vrijheidsgraden.\nWanneer niet is voldaan aan de veronderstelling van normaliteit maar wel aan lineariteit, onafhankelijkheid en homoscedasticiteit dan kunnen we voor inferentie opnieuw beroep doen op de centrale limietstelling die zegt dat de statistiek $T_k$ bij benadering een standaard Normale verdeling zal volgen wanneer het aantal observaties voldoende groot is.\n\nVoor het prostaatkanker voorbeeld kunnen we de effecten in de steekproef opnieuw veralgemenen naar de populatie toe door betrouwbaarheidsintervallen te bouwen voor de hellingen:\n\n$$\n[\\hat\\beta_j - t_{n-p,\\alpha/2} \\text{SE}_{\\hat\\beta_j},\\hat\\beta_j + t_{n-p,\\alpha/2} \\text{SE}_{\\hat\\beta_j}]\n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconfint(lmVWS)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 2.5 %    97.5 %\n(Intercept) -1.3473509 0.8112061\nlcavol       0.4033628 0.6999144\nlweight      0.2103288 0.8067430\nsviinvasion  0.2495824 1.0827342\n```\n\n\n:::\n:::\n\n\nGezien nul niet in de intervallen ligt weten we eveneens dat de associaties tussen lpsa $\\leftrightarrow$ lcavol, lpsa $\\leftrightarrow$ lweight, lpsa $\\leftrightarrow$ svi, statistisch significant zijn op het 5% significantieniveau.\n\nAnderzijds kunnen we ook formele hypothesetoetsen uitvoeren. Onder de nulhypothese veronderstellen we dat er geen associatie is tussen lpsa en de predictor $X_j$:\n\n$$H_0: \\beta_j=0$$\n\nen onder de alternatieve hypothese is er een associatie tussen response en predictor $X_j$:\n\n$$H_1: \\beta_j\\neq0$$\n\nMet de test statistiek\n\n$$T=\\frac{\\hat{\\beta}_j-0}{SE(\\hat{\\beta}_j)}$$\n\nkunnen we de nulhypothese falsifiëren. Onder $H_0$ volgt de statistiek een t-verdeling met $n-p$ vrijheidsgraden, waarbij p het aantal model parameters is van het regressiemodel inclusief het intercept.\n\nDeze tweezijdige testen zijn standaard geïmplementeerd in de standaard output van R.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lmVWS)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = lpsa ~ lcavol + lweight + svi, data = prostate)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.72966 -0.45767  0.02814  0.46404  1.57012 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -0.26807    0.54350  -0.493  0.62301    \nlcavol       0.55164    0.07467   7.388  6.3e-11 ***\nlweight      0.50854    0.15017   3.386  0.00104 ** \nsviinvasion  0.66616    0.20978   3.176  0.00203 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.7168 on 93 degrees of freedom\nMultiple R-squared:  0.6264,\tAdjusted R-squared:  0.6144 \nF-statistic: 51.99 on 3 and 93 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nDe testen geven weer dat de associaties tussen lpsa$\\leftrightarrow$lcavol, lpsa$\\leftrightarrow$lweight en lpsa$\\leftrightarrow$svi, respectievelijk  extreem significant ($p << 0.001$) en sterk significant ($p=0.001$ en $p=0.002$) zijn.\n\n## Nagaan van modelveronderstellingen\n\nVoor de statistische besluitvorming hebben we volgende aannames gedaan\n\n  1. Lineariteit\n  2. Onafhankelijkheid  \n  3. Homoscedasticiteit\n  4. Normaliteit\n\nOnafhankelijkheid is moeilijk te verifiëren op basis van de data, dat zou gegarandeerd moeten zijn door het design van de studie.\nAls we afwijkingen zien van lineariteit dan heeft besluitvorming geen zin gezien het de primaire veronderstelling is.\nIn dat geval moeten we het conditioneel gemiddelde eerst beter modelleren.\nIn geval van lineariteit maar schendingen van homoscedasticiteit of normaliteit dan weten we dat de besluitvorming mogelijks incorrect is omdat de teststatistieken dan niet langer een t-verdeling volgen.\n\n### Lineariteit\nDe primaire veronderstelling in meervoudige lineaire regressie-analyse is de aanname dat de uitkomst (afhankelijke variabele) lineair varieert in functie van de verklarende variabelen.\n\nAfwijkingen van lineariteit kunnen opnieuw worden opgespoord d.m.v. een *residuplot*. Deze wordt weergegeven in Figuur -@fig-prosLinDiag1 links boven. Als de veronderstelling van lineariteit opgaat, krijgt men in een residuplot geen patroon te zien.\nDe residuen zijn immers gemiddeld nul voor elke waarde van de predictoren en zouden dus mooi rond nul moeten variëren.\nDat is inderdaad het geval voor het meervoudig lineaire regressiemodel dat we hebben gefit o.b.v. de prostaat dataset.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npar(mfrow=c(2,2))\nplot(lmVWS)\n```\n\n::: {.cell-output-display}\n![Diagnostische plots voor het nagaan van de veronderstellingen van het lineair regressiemodel waarbij lpsa gemodelleerd wordt a.d.h.v. de predictoren lcavol, lweight en svi.](10-GeneralLinearModel_files/figure-epub/fig-prosLinDiag1-1.png){#fig-prosLinDiag1 fig-align='center' width=100%}\n:::\n:::\n\n\n### Homoscedasticiteit\n\nDe residu-plot kan opnieuw worden gebruikt om de veronderstelling na te gaan van homoscedasticiteit of gelijkheid van variantie.\nDe residu-plot voor het prostaatkanker voorbeeld Figuur -@fig-prosLinDiag1 links boven geeft geen afwijkingen weer van homoscedasiticiteit.\nAlle residuen zijn mooi gespreid binnen dezelfde grenzen voor elke gefitte waarde $\\hat y_i$.\nDe plot van de vierkantswortel van de absolute waarde van de gestandardiseerde error $\\sqrt{|e_i|/\\sqrt{MSE}}$ in functie van de predicties (Figuur -@fig-prosLinDiag1 links onder) geeft ook geen afwijkingen van homoscedasticiteit weer.\n\n\n### Normaliteit\n\nOpnieuw kunnen we de veronderstelling van normaliteit nagaan door gebruik te maken van QQ-plots.  Figuur -@fig-prosLinDiag1 rechts boven geeft de QQ-plot weer van de residuen voor het prostaatkanker voorbeeld. We zien in de plot geen aanwijzing voor afwijkingen van normaliteit.\n\n## Het niet-additieve meervoudig lineair regressiemodel\n\n### Interactie tussen continue variabele en factor variabele\n\n<iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/gdm0_Hh7Abc\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n\nWe breiden het meervoudig lineaire regressie model nu uit door toevoeging van interactie-termen.\n\nHet model in de vorige secties werd een additief model genoemd omdat de bijdrage van het kanker volume in lpsa niet afhangt van de hoogte van het prostaat gewicht en de status van de zaadblaasjes. De helling voor lcavol hangt m.a.w. niet af van de hoogte van het log prostaat gewicht en de status van de zaadblaasjes.\n\n$$\n\\beta_0 + \\beta_v (x_{v}+\\delta_v) + \\beta_w x_{w} +\\beta_s x_{s} - \\beta_0 - \\beta_v x_{v} - \\beta_w x_{w} -\\beta_s x_s = \\beta_v \\delta_v\n$$\n\nDe svi status en de hoogte van het log-prostaatgewicht ($x_w$) heeft geen invloed op de bijdrage van het log-tumorvolume ($x_v$) in de gemiddelde log-prostaat antigeen concentratie en vice versa.\n\nHet zou nu echter kunnen zijn dat de associatie tussen lpsa en lcavol, en tussen lpsa en log-prostaatgewicht wel afhangt van de status van de zaadblaasjes. De gemiddelde toename in lpsa tussen patiënten die één eenheid in het log-tumorvolume verschillen zou bijvoorbeeld lager kunnen zijn voor patiënten met een aangetaste zaadblaasjes dan bij patiënten waarvan de zaadblaasjes niet zijn aangetast. De associatie van het tumorvolume en de prostaat antigeen concentratie hangt in dit geval af van de status van de zaadblaasjes.\n\nOm een dergelijke \\textit{interactie} of \\textit{effectmodificatie} tussen 2 variabelen $X_v$ en $X_s$ enerzijds en tussen $X_w$ en $X_s$ anderzijds statistisch te modelleren kan men producten van de variabelen in kwestie aan het model toevoegen:\n\n$$\nY_i = \\beta_0 + \\beta_v x_{iv} + \\beta_w x_{iw} +\\beta_s x_{is} + \\beta_{vs} x_{iv}x_{is} + \\beta_{ws} x_{iw}x_{is} +\\epsilon_i\n$$\n\nDeze termen kwantificeren de *interactie-effecten* van respectievelijk de predictoren $x_v$ en $x_s$; en van $x_w$ en $x_s$ op de gemiddelde uitkomst.\nIn dit model worden de termen $\\beta_vx_{iv}$, $\\beta_wx_{iw}$ en $\\beta_sx_{is}$ dikwijls de *hoofdeffecten* van de predictoren $x_v$, $x_w$ en $x_s$ genoemd.\n\nWe schatten dit model nu in R. De interacties worden toegevoegd door een term toe te voegen in de formule met de naam van twee variabelen die wordt gescheiden door een `:`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlmVWS_IntVS_WS <- lm(lpsa ~ lcavol + lweight + svi + svi:lcavol + svi:lweight,data=prostate)\nsummary(lmVWS_IntVS_WS)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = lpsa ~ lcavol + lweight + svi + svi:lcavol + svi:lweight, \n    data = prostate)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.50902 -0.44807  0.06455  0.45657  1.54354 \n\nCoefficients:\n                    Estimate Std. Error t value Pr(>|t|)    \n(Intercept)         -0.52642    0.56793  -0.927 0.356422    \nlcavol               0.54060    0.07821   6.912 6.38e-10 ***\nlweight              0.58292    0.15699   3.713 0.000353 ***\nsviinvasion          3.43653    1.93954   1.772 0.079771 .  \nlcavol:sviinvasion   0.13467    0.25550   0.527 0.599410    \nlweight:sviinvasion -0.82740    0.52224  -1.584 0.116592    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.7147 on 91 degrees of freedom\nMultiple R-squared:  0.6367,\tAdjusted R-squared:  0.6167 \nF-statistic: 31.89 on 5 and 91 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nHet effect van lcavol op lpsa en het effect van lweight op lpsa zal nu afhangen van de waarde voor svi.\n$X_s$ is echter een dummy variabele die twee waarden aan kan nemen, $X_s=0$ als de zaadblaasjes niet aangetast zijn en $X_s=1$ als er invasie is van de zaadblaasjes.\nGezien $X_S$ een dummy variabele is bekomen we nu twee verschillende regressievlakken:\n\n1. Een regressievlak voor $X_s=0$:\n\n  $$Y=\\beta_0+\\beta_vX_v+\\beta_wX_w + \\epsilon$$ \n  \n  waar de hellingen voor lcavol en lweight de hoofdeffecten zijn.\n\n2. En een regressievlak voor $X_s=1$:\n\n  $$\n  \\begin{array}{lcl}\n  Y&=&\\beta_0+\\beta_vX_v+\\beta_s+\\beta_wX_w+\\beta_{vs}X_v + \\beta_{ws}X_w +\\epsilon\\\\\\\\\n  &=&(\\beta_0+\\beta_s)+(\\beta_v+\\beta_{vs})X_v+(\\beta_w+\\beta_{ws})X_w+\\epsilon\n  \\end{array}\n  $$\n\n  waar het intercept $\\beta_0 + \\beta_s$ is, de som van het intercept en het hoofdeffect voor $X_s$, en  de hellingen voor lcavol en lweight respectievelijk $\\beta_v+\\beta_{vs}$ en $\\beta_w+\\beta_{ws}$ zijn, m.a.w. de som van het hoofdeffect en de overeenkomstige interactieterm.\n\nGrafisch wordt het model weergegeven in  Figuur -@fig-prosIntFit2.\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Fit van het additieve model met de termen lcavol, lweight, svi (links) en het model met interacties lcavol, lweight, svi . lcavol:svi, lweight:svi (rechts). De rechtse figuur toont duidelijk dat de interactie er nu voor zorgt dat de associaties tussen de response <-> het log-tumorvolume en de response <-> het log-gewicht afhankelijk is van de status van de zaadblaasjes. De interacties zorgen voor andere hellingen bij patiënten met (rood) en zonder invasie (blauw) van de zaadblaasjes. Voor het additieve model (links) zien we enkel een verschuiving van het regressievlak, maar parallelle hellingen. Het hoofdeffect voor een factor variabele zorgt m.a.w. voor een ander intercept.](10-GeneralLinearModel_files/figure-epub/fig-prosIntFit2-1.png){#fig-prosIntFit2 fig-align='center' width=100%}\n:::\n:::\n\n\nMerk op dat de helling voor lcavol groter is bij patiënten met invasie van de zaadblaasjes dan bij patiënten zonder invasie van de zaadblaasjes en dat de helling voor lweight van teken veranderd. We merken verder op dat beide interactie-termen opnieuw niet significant.\n\n<!---break-->\n\n### Interactie tussen twee continue variabelen {#sec-intCont}\n\n<iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/LWBXS4mYbMI\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n\nHet zou ook kunnen dat de associatie tussen lpsa en lcavol afhangt van het prostaatgewicht. De gemiddelde toename in lpsa tussen patiënten die één eenheid van log-tumorvolume verschillen zou bijvoorbeeld lager kunnen zijn voor patiënten met een hoog prostaatgewicht dan bij patiënten met een laag prostaatgewicht. Het effect van het tumorvolume op de prostaat antigeen concentratie hangt in dit geval af van het prostaatgewicht.\n\nOm een dergelijke \\textit{interactie} of \\textit{effectmodificatie} tussen 2 variabelen $X_v$ en $X_w$ statistisch te modelleren, kan men het product van beide variabelen in kwestie aan het model toevoegen:\n\n$$\nY_i = \\beta_0 + \\beta_v x_{iv} + \\beta_w x_{iw} +\\beta_s x_{is} + \\beta_{vw} x_{iv}x_{iw} +\\epsilon_i\n$$\n\n\nHet ‘effect’ van een verschil in 1 eenheid in $X_v$ op de gemiddelde uitkomst bedraagt nu:\n\n$$\n\\begin{array}{l}\nE(Y|X_v=x_v+1,X_w=x_w,X_s=x_s) − E(Y|X_v=x_v,X_w=x_w,X_s=x_s) \\\\\n\\quad = \\beta_0 + \\beta_v (x_{v}+1) + \\beta_w x_w +\\beta_s x_{s} + \\beta_{vw} (x_{v}+1) x_w - \\beta_0 - \\beta_v x_{v} - \\beta_w x_w -\\beta_s x_{s} - \\beta_{vw} (x_{v}) x_w \\\\\n\\quad = \\beta_v +  \\beta_{vw} x_w\n \\end{array}\n$$\n\nwanneer het log-prostaatgewicht $X_w=c$ en de $X_s=x_s$ status ongewijzigd blijven. Merk op dat het ‘effect’ van een wijzing in het tumorvolume bij\nconstant log-prostaat gewicht nu inderdaad afhankelijk is van de hoogte van het log-prostaatgewicht $x_w$.\n\nWe schatten nu opnieuw de parameters van het model in R.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlmVWS_IntVW <- lm(lpsa~lcavol + lweight + svi + lcavol:lweight ,prostate)\nsummary(lmVWS_IntVW)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = lpsa ~ lcavol + lweight + svi + lcavol:lweight, \n    data = prostate)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.65886 -0.44673  0.02082  0.50244  1.57457 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)   \n(Intercept)     -0.6430     0.7030  -0.915  0.36278   \nlcavol           1.0046     0.5427   1.851  0.06734 . \nlweight          0.6146     0.1961   3.134  0.00232 **\nsviinvasion      0.6859     0.2114   3.244  0.00164 **\nlcavol:lweight  -0.1246     0.1478  -0.843  0.40156   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.7179 on 92 degrees of freedom\nMultiple R-squared:  0.6293,\tAdjusted R-squared:  0.6132 \nF-statistic: 39.05 on 4 and 92 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nDe output van het model geeft een schatting van -0.125 voor de interactie $\\beta_{vw}$ tussen het log-tumorvolume en het log-prostaatgewicht. Dat betekent dat de gemiddelde toename in lpsa tussen patiënten met een verschil in het log-tumorvolume maar met eenzelfde prostaatgewicht afhankelijk zal zijn van het prostaatgewicht.\nIn het bijzonder suggereert de output dat patiënten die 1% verschillen in het tumorvolume maar hetzelfde log prostaat gewicht hebben gemiddeld ($1.005-0.125 \\times x_w$)% verschillen in prostaat antigeen concentratie (interpretatie volgt uit log transformatie van de response en tumorvolume).\nPatiënten die 1% verschillen in tumorvolume en die een log-prostaatgewicht hebben van 3 zullen gemiddeld 0.631% in prostaat antigeen concentratie verschillen.  Terwijl patiënten die 1% verschillen in tumorvolume en die een log-prostaatgewicht hebben van 4 gemiddeld een verschil van 0.506% in prostaat antigeen concentratie hebben. De associatie van het log-tumorvolume en de log prostaat antigeen concentratie neemt dus af met toenemend prostaatgewicht.\n\nGrafische interpretatie wordt weergegeven in Figuur -@fig-prosIntFit1. Hier worden het additieve model en het model met de  lcavol:lweight interactie vergeleken. De fit toont duidelijk aan dat de associate tussen lpsa en lcavol gelijk is ongeacht de grootte van het prostaatgewicht voor het additieve model (parallele lijnen in het regressieoppervlak). Voor het model met interactie is dat niet het geval, de associate (helling) neemt af met toenemend prostaatgewicht. We zien een analoog effect wanneer we focussen op de associatie tussen lpsa en lweight. De lpsa $\\leftrightarrow$ lweight associatie neemt af met toenemend log-tumorvolume.\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Fit van het additieve model met de termen lcavol, lweight, svi (links) en het model met interactie lcavol, lweight, svi en lcavol:lweight (rechts). Merk op dat we enkel het regressieoppervlak weergeven voor patiënten zouder invasie van de zaadblaasjes. Dat voor patiënten met invasie van de zaadblaasjes is parallel met het getoonde oppervlak, maar ligt iets hoger. De rechtse figuur toont duidelijk dat de interactie ervoor zorgt dat de associatie tussen de response en het tumorvolume afhankelijk is van de hoogte van het prostaatgewicht en vice versa, dat zorgt voor een torsie in het regressievlak.](10-GeneralLinearModel_files/figure-epub/fig-prosIntFit1-1.png){#fig-prosIntFit1 fig-align='center' width=100%}\n:::\n:::\n\n\n\nMerk op, dat het interactie effect dat geobserveerd wordt in de steekproef echter statistisch niet significant is (p=0.4).\nGezien de hoofdeffecten die betrokken zijn in een interactie term niet los van elkaar kunnen worden geïnterpreteerd is de conventie om een interactieterm uit het model te verwijderen wanneer die niet significant is. Na verwijdering van de niet-significante interactieterm kunnen de hoofdeffecten worden geïnterpreteerd.\n\n\n\n## ANOVA Tabel\n\n<iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/Y4klT3eXJwI\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n\n### SSTot, SSR en SSE\n\nVoor de enkelvoudige lineaire regressie hebben we in detail de decompositie van SSTot=SSR+SSE besproken. In deze sectie breiden we die resultaten uit naar meervoudige lineaire regressie.\n\nDe totale kwadratensom SSTot is gedefinieerd zoals voorheen,\n\n$$\n  \\text{SSTot} = \\sum_{i=1}^n (Y_i - \\bar{Y})^2.\n$$\n\nHet is nog steeds een maat voor de totale variabiliteit in de geobserveerde uitkomsten.\nOok de residuele kwadratensom is zoals voorheen.\n\n$$\n  \\text{SSE} = \\sum_{i=1}^n (Y_i-\\hat{Y}_i)^2.\n$$\n\nBeschouw nu een meervoudig lineair regressiemodel met $p-1$ regressoren. Dan geldt de volgende decompositie van de totale kwadratensom,\n\n$$\n  \\text{SSTot} = \\text{SSR} + \\text{SSE} ,\n$$\n\nmet\n\n$$\n  \\text{SSR} = \\sum_{i=1}^n (\\hat{Y}_i-\\bar{Y})^2.\n$$\n\nDe kwadratensom van de regressie (SSR) kan nog steeds geïnterpreteerd worden als de variabiliteit in de uitkomsten die verklaard kan worden door het regressiemodel.\n\nVoor de vrijheidsgraden en de gemiddelde kwadratensommen geldt:\n\n- SSTot heeft $n-1$ vrijheidsgraden en $\\text{SSTot}/(n-1)$ is een schatter voor de variantie van $Y$ (van de marginale distributie van $Y$).\n- SSE heeft $n-p$ vrijheidsgraden en $\\text{MSE}=\\text{SSE}/(n-p)$ is een schatter voor de residuele variantie van $Y$ gegeven de regressoren (i.e. een schatter voor de residuele variantie $\\sigma^2$ van de foutterm $\\epsilon$).\n- SSR heeft $p-1$ vrijheidsgraden en $\\text{MSR}=\\text{SSR}/(p-1)$ is de gemiddelde kwadratensom van de regressie.\n\nEen gevolg van de decompositie van SSTot is dat de determinatiecoëfficiënt blijft zoals voorheen, i.e.\n\n$$\n  R^2 = 1-\\frac{\\text{SSE}}{\\text{SSTot}} = \\frac{\\text{SSR}}{\\text{SSTot}}\n$$\n\nis de fractie van de totale variabiliteit in de uitkomsten die verklaard wordt door het regressiemodel.\n\nDe teststatistiek\n\n$$\nF=\\text{MSR}/\\text{MSE}\n$$\n\nis onder\n\n$$H_0:\\beta_1=\\ldots=\\beta_{p-1}=0$$\n\nverdeeld volgens een F-verdeling met $p-1$ vrijheidsgraden in de teller en $n-p$ vrijheidsgraden in de noemer $F_{p-1;n-p}$.\n\nDe F-test test m.a.w. het effect van alle predictoren simultaan. Onder de nulhypothese is er geen associatie tussen de respons en elk van de predictoren. De output van deze F-test wordt standaard gegeven onderaan in de summary output.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lmVWS)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = lpsa ~ lcavol + lweight + svi, data = prostate)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.72966 -0.45767  0.02814  0.46404  1.57012 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -0.26807    0.54350  -0.493  0.62301    \nlcavol       0.55164    0.07467   7.388  6.3e-11 ***\nlweight      0.50854    0.15017   3.386  0.00104 ** \nsviinvasion  0.66616    0.20978   3.176  0.00203 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.7168 on 93 degrees of freedom\nMultiple R-squared:  0.6264,\tAdjusted R-squared:  0.6144 \nF-statistic: 51.99 on 3 and 93 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nWe zien dat de algemene nulhypothese heel significant kan worden verworpen. Minstens 1 predictor is extreem significant geassocieerd met de respons. In de individuele t-testen zien we dat elk van de predictoren een sterk significante associatie vertonen.\n\n<!---break-->\n\n### Extra Kwadratensommen\n\n<iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/LXgh32U9Dq4\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n\nWe kunnen een stap verder gaan en voor iedere individuele regressor een kwadratensom definiëren. Er zijn echter verschillende mogelijkheden.\n\nBeschouw de volgende twee regressiemodellen voor regressoren $x_1$ en $x_2$:\n\n$$\n  Y_i = \\beta_0+\\beta_1 x_{i1} + \\epsilon_i,\n$$\n\nmet $\\epsilon_i\\text{ iid } N(0,\\sigma_1^{2})$, en\n\n$$\nY_i = \\beta_0+\\beta_1 x_{i1}+\\beta_2 x_{i2} + \\epsilon_i,\n$$\n\nmet $\\epsilon_i\\text{ iid } N(0,\\sigma_2^{2})$.\n\nMerk op dat we subscript 1 en 2 toegevoegd hebben aan de residuele varianties, maar dat we dezelfde $\\beta$-parameternotatie gebruiken voor beide modellen; dit is om de notatie niet nodeloos complex te maken, maar je moet je ervan bewust zijn dat de $\\beta$-parameters uit beide modellen niet noodzakelijk gelijk zijn.\n\nVoor het eerste (gereduceerde) model geldt de decompositie\n\n$$\n  \\text{SSTot} = \\text{SSR}_1 + \\text{SSE}_1\n$$\n\nen voor het tweede (niet-gereduceerde) model\n\n$$\n  \\text{SSTot} = \\text{SSR}_2 + \\text{SSE}_2\n$$\n\n(SSTot is uiteraard dezelfde in beide modellen omdat dit niet afhangt van het regressiemodel).\n\n\n**Definitie extra kwadratensom**\nDe *extra kwadratensom* (Engels: *extra sum of squares*) van predictor $x_2$ t.o.v. het model met enkel $x_1$ als predictor wordt gegeven door\n\n$$\n  \\text{SSR}_{2\\mid 1} = \\text{SSE}_1-\\text{SSE}_2=\\text{SSR}_2-\\text{SSR}_1.\n$$  \n\n**Einde definitie**\n\nMerk eerst op dat $\\text{SSE}_1-\\text{SSE}_2=\\text{SSR}_2-\\text{SSR}_1$ triviaal is gezien de decomposities van de totale kwadratensommen.\n\nDe extra kwadratensom $\\text{SSR}_{2\\mid 1}$ kan eenvoudig geïnterpreteerd worden als de extra variantie van de uitkomst die verklaard kan worden door regressor $x_2$ toe te voegen aan een model waarin regressor $x_1$ reeds aanwezig is.\n\nMet dit nieuw soort kwadratensom kunnen we voor het model met twee predictoren schrijven\n\n$$\n  \\text{SSTot} = \\text{SSR}_1+ \\text{SSR}_{2\\mid 1} + \\text{SSE}.\n$$\n\nDit volgt rechtstreeks uit de definitie van de extra kwadratensom $\\text{SSR}_{2\\mid 1}$.\n\nDe definitie voor de extra kwadratensom kan uitgebreid worden naar een situatie waar twee geneste lineaire regressiemodellen beschouwd worden.\n\nZonder in te boeten in algemeenheid starten we met de regressiemodellen ($s<p-1$)\n\n$$\nY_i = \\beta_0 + \\beta_1 x_{i1} + \\cdots + \\beta_{s} x_{is} + \\epsilon_i\n$$\n\nmet $\\epsilon_i\\text{ iid }N(0,\\sigma_1^{2})$, en ($s< q\\leq p-1$)\n\n$$\nY_i = \\beta_0 + \\beta_1 x_{i1} + \\cdots + \\beta_{s} x_{is} + \\beta_{s+1} x_{is+1} + \\cdots \\beta_{q}x_{iq}+ \\epsilon_i\n$$\n\nmet $\\epsilon_i\\text{ iid } N(0,\\sigma_2^{2})$.\n\n\nDe **extra kwadratensom** van predictoren $x_{s+1}, \\ldots, x_q$ t.o.v. het model met enkel de predictoren  $x_1,\\ldots, x_{s}$ wordt gegeven door\n\n$$\n  \\text{SSR}_{s+1, \\ldots, q\\mid 1,\\ldots, s} = \\text{SSE}_1-\\text{SSE}_2=\\text{SSR}_2-\\text{SSR}_1.\n$$  \n\nDe extra kwadratensom $\\text{SSR}_{s+1, \\ldots, q\\mid 1,\\ldots, s}$ meet de extra variabiliteit in uitkomst die verklaard wordt door de predictoren $x_{s+1}, \\ldots, x_q$ toe te voegen aan een model met predictoren $x_1,\\ldots, x_{s}$.\nAnders gezegd: het meet de variatie van de uitkomsten verklaard door predictoren $x_{s+1}, \\ldots, x_q$ die niet verklaard wordt door de predictoren  $x_1,\\ldots, x_{s}$.\n\nWe hebben hier SSR notatie gebruikt met lange indexen (bv. $\\text{SSR}_{s, \\ldots, q\\mid 1,\\ldots, s-1}$). Soms wordt de voorkeur gegeven aan de notatie\n\n$$\n  \\text{SSR}(s+1, \\ldots, q\\mid 1,\\ldots, s).\n$$\n\n### Type I Kwadratensommen\n\nStel dat $p-1$ regressoren beschouwd worden, en beschouw een sequentie van modellen ($s=2,\\ldots, p-1$)\n\n$$\nY_i = \\beta_0 + \\sum_{j=1}^{s} \\beta_j x_{ij} + \\epsilon_i\n$$\n\nmet $\\epsilon_i\\text{ iid } N(0,\\sigma^{2})$.\nDe overeenkomstige kwadratensommen worden genoteerd als $\\text{SSR}_{s}$ en $\\text{SSE}_{s}$. De modelsequentie geeft ook aanleiding tot extra kwadratensommen $\\text{SSR}_{s\\mid 1,\\ldots, s-1}$. Deze laatste kwadratensom wordt een type I kwadratensom genoemd. Merk op dat deze afhangt van de volgorde (nummering) van regressoren.\n\nEr kan aangetoond worden dat voor Model met $s=p-1$ geldt\n\n$$\n \\text{SSTot} = \\text{SSR}_1 + \\text{SSR}_{2\\mid 1} + \\text{SSR}_{3\\mid 1,2} + \\cdots + \\text{SSR}_{p-1\\mid 1,\\ldots, p-2} + \\text{SSE},\n$$\n\nmet $\\text{SSE}$ de residuele kwadratensom van het model met alle $p-1$ regressoren en\n\n$$\n  \\text{SSR}_1 + \\text{SSR}_{2\\mid 1} + \\text{SSR}_{3\\mid 1,2} + \\cdots + \\text{SSR}_{p-1\\mid 1,\\ldots, p-2} = \\text{SSR}\n$$\n\nmet $\\text{SSR}$ de kwadratensom van de regressie van het model met alle $p-1$ regressoren.\n\nDe interpretatie van iedere individuele SSR term werd eerder gegeven, maar het is belangrijk om op te merken dat de interpretatie van iedere term afhangt van de volgorde van de regressoren in de sequentie van regressiemodellen.\n\nDus de type I kwadratensommen laten een decompositie van SSTot toe, maar de SSR-termen hangen af van de volgorde waarin de regressoren in het regressiemodel voorkomen.\n\nIedere type I SSR heeft betrekking op het effect van 1 regressor en heeft dus 1 vrijheidsgraad.\nVoor iedere type I SSR term kan een gemiddelde kwadratensom gedefinieerd worden als $\\text{MSR}_{j\\mid 1,\\ldots, j-1}=\\text{SSR}_{j\\mid 1,\\ldots, j-1}/1$.\nDe teststatistiek $F=\\text{MSR}_{j\\mid 1,\\ldots, j-1}/\\text{MSE}$ is onder $H_0:\\beta_j=0$ met $s=j$ verdeeld als $F_{1;n-p}$.\n\nDeze kwadratensommen worden standaard weergegeven door de anova functie in R.\n\n### Type III Kwadratensommen\n\nBeschouw opnieuw het regressiemodel met $p-1$ regressoren.\nDe type III kwadratensom van regressor $x_j$ wordt gegeven door de extra kwadratensom\n\n$$\n  \\text{SSR}_{j \\mid 1,\\ldots, j-1,j+1,\\ldots, p-1} = \\text{SSE}_1-\\text{SSE}_2\n$$\n\n- $\\text{SSE}_2$ de residuele kwadratensom van regressiemodel met alle $p-1$ regressoren.\n- $\\text{SSE}_1$ de residuele kwadratensom van regressiemodel met alle $p-1$ regressoren, uitgezonderd regressor $x_j$.\n\nDe type III kwadratensom $\\text{SSR}_{j \\mid 1,\\ldots, j-1,j+1,\\ldots, p-1}$ kwantificeert dus het aandeel van de totale variantie van de uitkomst dat door regressor $x_j$ verklaard wordt en dat niet door de andere $p-2$ regressoren verklaard wordt.\n\nDe type III kwadratensom heeft ook 1 vrijheidsgraad omdat het om 1 $\\beta$-parameter gaat.\n\nVoor iedere type III SSR term kan een gemiddelde kwadratensom gedefinieerd worden als $\\text{MSR}_{j \\mid 1,\\ldots, j-1,j+1,\\ldots, p-1}=\\text{SSR}_{j \\mid 1,\\ldots, j-1,j+1,\\ldots, p-1}/1$.\n\nDe teststatistiek\n\n$$\nF=\\text{MSR}_{j \\mid 1,\\ldots, j-1,j+1,\\ldots, p-1}/\\text{MSE}\n$$\n\nis onder $H_0:\\beta_j=0$ verdeeld as $F_{1;n-p}$.\n\nDeze kwadratensommen kunnen worden verkregen d.m.v. de Anova functie van het car package. In de Anova functie wordt hiervoor het argument 'type=3' gebruikt.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(car)\nAnova(lmVWS, type = 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnova Table (Type III tests)\n\nResponse: lpsa\n            Sum Sq Df F value    Pr(>F)    \n(Intercept)  0.125  1  0.2433  0.623009    \nlcavol      28.045  1 54.5809 6.304e-11 ***\nlweight      5.892  1 11.4678  0.001039 ** \nsvi          5.181  1 10.0841  0.002029 ** \nResiduals   47.785 93                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nMerk op dat de p-waarden die we verkrijgen voor het testen van elk van de effecten identiek zijn als de p-waarden van de tweezijdige t-testen.\nDe F-test o.b.v. een type III kwadratensom voor 1 parameter is equivalent met de tweezijdige t-test voor deze parameter.  \n\n## Regressiediagnostieken\n\n<iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/6t84tO2zOcs\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n\n### Multicollineariteit\n\nHet is interessant om in de R output voor het model met lcavol:lweight interactie ook naar schattingen van de hoofdeffecten te kijken (Sectie -@sec-intCont).\nDe waarden van de schattingen zijn niet alleen verschillend van wat we in het additieve model vonden, maar de standaardfouten zijn nu veel groter!\nDe oorzaak moet gezocht worden in het probleem van multicollineariteit.\nWanneer 2 predictoren sterk gecorreleerd zijn, dan delen ze voor een groot stuk dezelfde informatie en is het moeilijk om de afzonderlijke effecten van beiden op de uitkomst te schatten. Dit uit zich in het feit dat de computationele berekening van de kleinste kwadratenschatters onstabiel wordt, in die zin dat kleine wijzigingen aan de gegevens of het toevoegen of weglaten van een predictorvariabele een belangrijke impact kunnen hebben op de grootte, en zelfs het teken, van de geschatte regressieparameters.\nEen tweede effect van multicollineariteit is dat standaard errors bij de geschatte regressieparameters fel kunnen worden opgeblazen en de bijhorende betrouwbaarheidsintervallen bijgevolg zeer breed kunnen worden. Zolang men enkel predicties tracht te bekomen op basis van het regressiemodel zonder daarbij te extrapoleren buiten het bereik van de predictoren is multicollineariteit geen probleem.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(cbind(prostate$lcavol,prostate$lweight,prostate$lcavol*prostate$lweight))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          [,1]      [,2]      [,3]\n[1,] 1.0000000 0.1941283 0.9893127\n[2,] 0.1941283 1.0000000 0.2835608\n[3,] 0.9893127 0.2835608 1.0000000\n```\n\n\n:::\n:::\n\n\nWe zien dat de correlatie inderdaad erg hoog is tussen het log-tumorvolume en de interactieterm.\nHet is gekend dat hogere orde termen (interacties en kwadratische termen) vaak een sterke correlatie vertonen.\n\nProblemen als gevolg van multicollineariteit kunnen herkend worden aan het feit dat de resultaten onstabiel worden. Zo kunnen grote wijzigingen optreden in de parameters na toevoeging van een predictor, kunnen zeer brede betrouwbaarheidsintervallen bekomen worden voor sommige parameters of kunnen gewoonweg onverwachte resultaten worden gevonden. Meer formeel kan men zich een idee vormen van de mate waarin er van multicollineariteit sprake is door de correlaties te inspecteren tussen elk paar predictoren in het regressiemodel of via een scatterplot matrix die elk paar predictoren uitzet op een scatterplot.\nDergelijke diagnostieken voor multicollineariteit zijn echter niet ideaal.\nVooreerst geven ze geen idee in welke mate de geobserveerde multicollineariteit de resultaten onstabiel maakt.\nTen tweede kan het in modellen met 3 of meerdere predictoren, zeg X1, X2, X3, voorkomen dat er zware multicollineariteit is ondanks het feit dat alle paarsgewijze correlaties tussen de predictoren laag zijn.\nDit kan bijvoorbeeld optreden wanneer de correlatie hoog is tussen X1 en een lineaire combinatie van X2 en X3.\n\nBovenstaande nadelen kunnen vermeden worden door de \\textit{variance inflation factor (VIF)} te onderzoeken, die voor de $j$-de parameter in het regressiemodel gedefinieerd wordt als\n\n$$\n\\textrm{VIF}_j=\\left(1-R_j^2\\right)^{-1}\n$$\n\nIn deze uitdrukking stelt $R_j^2$ de meervoudige determinatiecoëfficiënt voor van een lineaire regressie van de $j$-de predictor op alle andere predictoren in het model. De VIF heeft de eigenschap dat ze gelijk is aan 1 indien de $j$-de predictor niet lineair geassocieerd is met de andere predictoren in het model, en bijgevolg wanneer de $j$-de parameter in het model niet onderhevig is aan het probleem van multicollineariteit. De VIF is groter dan 1 in alle andere gevallen. In het bijzonder drukt ze uit met welke factor de geobserveerde variantie op de schatting voor de $j$-de parameter groter is dan wanneer alle predictoren onafhankelijk zouden zijn. Hoe groter de VIF, hoe minder stabiel de schattingen bijgevolg zijn. Hoe kleiner de VIF, hoe dichter de schattingen dus bij de gezochte populatiewaarden verwacht worden. In de praktijk spreekt men van ernstige multicollineariteit voor een regressieparameter wanneer haar VIF de waarde 10 overschrijdt.\n\nWe illustreren dat a.d.h.v. onderstaande voorbeeld.\n\n**Voorbeeld vetpercentage**\n\nHet percentage lichaamsvet van een persoon bepalen is een moeilijke en dure meting.\nOm die reden werden in het verleden verschillende studies opgezet met als doel het patroon te ontrafelen tussen werkelijk percentage lichaamsvet en verschillende, makkelijker te meten surrogaten.\nIn een studie heeft men voor\n20 gezonde vrouwen tussen 25 en 34 jaar het percentage lichaamsvet $Y$, de dikte van de huidplooi rond de triceps $X_1$, de dij-omtrek $X_2$ en de middenarmomtrek $X_3$ gemeten.\nIndien we een nauwkeurig regressiemodel kunnen opstellen op basis van de gegevens, dan zal ons dat toelaten om in de toekomst met behulp van dat model voorspellingen te maken voor het percentage lichaamsvet in gezonde vrouwen tussen 25 en 34 jaar, op basis van de huidplooi rond de triceps, de dij-omtrek en de middenarmomtrek.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Scatterplot matrix van de dataset bodyfat.](10-GeneralLinearModel_files/figure-epub/fig-vetScatter-1.png){#fig-vetScatter fig-align='center' width=100%}\n:::\n:::\n\n\nWanneer we de 3 predictoren simultaan aan een regressiemodel toevoegen, bekomen we de volgende output.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlmFat <- lm(Body_fat ~ Triceps + Thigh + Midarm, data = bodyfat)\nsummary(lmFat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Body_fat ~ Triceps + Thigh + Midarm, data = bodyfat)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.7263 -1.6111  0.3923  1.4656  4.1277 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)\n(Intercept)  117.085     99.782   1.173    0.258\nTriceps        4.334      3.016   1.437    0.170\nThigh         -2.857      2.582  -1.106    0.285\nMidarm        -2.186      1.595  -1.370    0.190\n\nResidual standard error: 2.48 on 16 degrees of freedom\nMultiple R-squared:  0.8014,\tAdjusted R-squared:  0.7641 \nF-statistic: 21.52 on 3 and 16 DF,  p-value: 7.343e-06\n```\n\n\n:::\n\n```{.r .cell-code}\nvif(lmFat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Triceps    Thigh   Midarm \n708.8429 564.3434 104.6060 \n```\n\n\n:::\n:::\n\n\nHoewel het model meer dan 80% van de variabiliteit in het vetpercentage kan verklaren en dat de F-test die test voor alle predictoren simultaan extreem significant is, is de associatie echter voor geen enkele predictor significant volgens de individuele t-testen.\nDe scatterplot matrix in Figuur -@fig-vetScatter geeft aan dat er multicollineariteit aanwezig is wat betreft de predictoren $X_1$ en $X_2$, maar niet meteen wat betreft de middenarmomtrek $X_3$. Niettemin bekomen we erg hoge VIFs voor alle model parameters.\n Dit suggereert dat ook de middenarmomtrek gevoelig is aan ernstige multicollineariteit en bijgevolg dat scatterplot matrices inderdaad slechts een beperkt licht werpen op het probleem van multicollineariteit.\n De VIF varieert van 105-709, hetgeen aantoont dat de (kwadratische) afstand tussen de schattingen voor de regressieparameters en hun werkelijke waarden 105 tot 709 keer hoger kan worden verwacht dan wanneer er geen multicollineariteit zou zijn.\nHoewel de paarsgewijze correlatie tussen Midarm en Triceps en Midarm en Thigh laag is, toont de regressie van Midarm op Triceps en Thigh echter aan dat beide variabelen samen 99% van de variabiliteit in de variabiliteit van Midarm kunnen verklaren, wat er voor zorgt dat er ook voor Midarm een extreem hoge multicollineariteit is.  \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlmMidarm <- lm(Midarm ~ Triceps + Thigh, data = bodyfat)\nsummary(lmMidarm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Midarm ~ Triceps + Thigh, data = bodyfat)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.58200 -0.30625  0.02592  0.29526  0.56102 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 62.33083    1.23934   50.29   <2e-16 ***\nTriceps      1.88089    0.04498   41.82   <2e-16 ***\nThigh       -1.60850    0.04316  -37.26   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.377 on 17 degrees of freedom\nMultiple R-squared:  0.9904,\tAdjusted R-squared:  0.9893 \nF-statistic: 880.7 on 2 and 17 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n**Einde voorbeeld**\n\n\nWe evalueren nu de VIF in het prostaatkanker voorbeeld voor het additieve model en het model met interactie.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvif(lmVWS)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     lcavol     lweight sviinvasion \n   1.447048    1.039188    1.409189 \n```\n\n\n:::\n\n```{.r .cell-code}\nvif(lmVWS_IntVW)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        lcavol        lweight    sviinvasion lcavol:lweight \n     76.193815       1.767121       1.426646      80.611657 \n```\n\n\n:::\n:::\n\n\nWe zien dat de variance inflation factors voor het additieve model laag zijn, ze liggen allen dicht bij 1.\nDeze voor het model met interactie zijn echter hoog, voor lcavol en de interactie liggen ze respectievelijk op 76.2 en 80.6.\nWat wijst op zeer ernstige multicollineariteit.\n\nMerk op dat dit voor interactietermen vaak wordt veroorzaakt door het feit dat het hoofdeffect een andere interpretatie krijgt. Voor lcavol wordt dit b.v. het effect van het log-tumorvolume bij een log-prostaatgewicht van 0. Dit kan uiteraard niet voorkomen, alle log-prostaatgewichten liggen tussen 2.37 en 6.108 en berust dus op sterke extrapolatie. In de literatuur wordt daarom vaak voorgesteld om de variabelen te centreren rond het gemiddelde wanneer men hogere orde termen in het model opneemt. Dat is echter niet nodig, we weten immers dat het effect van het log-tumorvolume in het model met de lcavol:lweight interactie niet kan worden bestudeerd zonder het log-prostaatgewicht in rekening te brengen.\nWe zullen in de practica zien dat we i.p.v. de data te centreren evengoed een test kunnen uitvoeren voor het effect van lcavol bij het gemiddelde log-prostaatgewicht, wat de interpretatie is voor het effect van lcavol bij het gecentreerde model.   \n\n<!---break-->\n\n### Invloedrijke observaties\n\n<iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/CcZE9mRUSTE\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n\nIn onderstaande code wordt data gesimuleerd om de impact van outliers te illustreren.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(112358)\nnobs<-20\nsdy<-1\nx<-seq(0,1,length=nobs)\ny<-10+5*x+rnorm(nobs,sd=sdy)\nx1<-c(x,0.5)\ny1 <- c(y,10+5*1.5+rnorm(1,sd=sdy))\nx2 <- c(x,1.5)\ny2 <- c(y,y1[21])\nx3 <- c(x,1.5)\ny3 <- c(y,11)\nplot(x,y,xlim=range(c(x1,x2,x3)),ylim=range(c(y1,y2,y3)))\npoints(c(x1[21],x2[21],x3[21]),c(y1[21],y2[21],y3[21]),pch=as.character(1:3),col=2:4)\nabline(lm(y~x),lwd=2)\nabline(lm(y1~x1),col=2,lty=2,lwd=2)\nabline(lm(y2~x2),col=3,lty=3,lwd=2)\nabline(lm(y3~x3),col=4,lty=4,lwd=2)\nlegend(\"topleft\",col=1:4,lty=1:4,legend=paste(\"lm\",c(\"\",as.character(1:3))),text.col=1:4)\n```\n\n::: {.cell-output-display}\n![Impact van outliers op de regressie. Regressie zonder outliers (zwart), regressie met outlier 1 (groen), regressie met outlier 2 (rood), regressie met outlier 3 (blauw).](10-GeneralLinearModel_files/figure-epub/fig-influential-1.png){#fig-influential fig-align='center' width=100%}\n:::\n:::\n\n\nEen dataset bevat vaak extreme observaties voor zowel de uitkomst $Y$ als de predictoren $X$. Deze kunnen de geschatte regressieparameters en regressielijn sterk beïnvloeden. Dat is niet verwonderlijk vermits de regressielijn de gemiddelde uitkomst voorstelt in functie van $X$ en gemiddelden zeer gevoelig zijn aan outliers. Figuur -@fig-influential toont een puntenwolk met 3 afwijkende observaties samen met 4 lineaire regressielijnen één zonder en één met elk van deze observaties. Merk op dat de regressielijn in bijzondere mate afwijkt wanneer observatie 3 wordt opgenomen in de dataset. Dit kan als volgt worden verklaard. De aanwezigheid van observatie 1 impliceert dat de regressielijn (en bijgevolg het intercept) naar boven wordt getrokken, maar heeft verder geen invloed op het patroon van de regressielijn. Observatie 2 is extreem, maar heeft geen impact op de regressielijn omdat ze het patroon van de rechte volgt. Hoewel observatie 3 niet met een zeer extreme uitkomst $y$ overeenstemt, zal deze observatie toch het meest invloedrijk zijn omdat de predictorwaarde $x$ en, in het bijzonder, de $(x,y)$-combinatie zeer afwijkend is.\n\nHet spreekt voor zich dat het niet wenselijk is dat een enkele observatie het resultaat van een lineaire regressie-analyse grotendeels bepaalt. We wensen daarom over diagnostieken te beschikken die ons toelaten om extreme observaties op te sporen. *Residu's* geven weer hoe ver de uitkomst afwijkt van de regressielijn en kunnen bijgevolg gebruikt worden om extreme uitkomsten te identificeren. In het bijzonder hebben we eerder vermeld dat residu's bij benadering Normaal verdeeld zijn wanneer het model correct is en de uitkomst Normaal verdeeld (bij vaste predictorwaarden) met homogene variantie. Of een residu extreem is, kan in dat opzicht geverifieerd worden door haar te vergelijken met de Normale verdeling. Stel bijvoorbeeld dat men over 100 observaties beschikt, dan verwacht men dat ongeveer 5\\% van de residu's in absolute waarde extremer zijn dan 1.96$\\hat{\\sigma}$. Indien men veel meer extreme residu's observeert, dan is er een indicatie op outliers.\n\nIn de literatuur heeft men een aantal modificaties van residu's ingevoerd met als doel deze nuttiger te maken voor de detectie van outliers. *Studentized residu's* zijn een transformatie van de eerder gedefinieerde residu's die $t$-verdeeld zijn met $n-1$ vrijheidsgraden onder de onderstellingen van het model. Outliers kunnen aldus nauwkeuriger worden opgespoord door na te gaan of veel meer dan 5% van de studentized residu's in absolute waarde het 97.5% percentiel van de $t_{n-1}$-verdeling overschrijden.\n\nExtreme predictorwaarden kunnen in principe opgespoord worden via een scatterplot matrix voor de uitkomst en verschillende predictoren. Wanneer er meerdere predictoren zijn, hebben deze echter ernstige tekortkomingen omdat het een combinatie van meerdere predictoren kan zijn die ongewoon is en dit niet kan opgespoord worden via dergelijke grafieken. Om die reden is het veel zinvoller om de zogenaamde *leverage (invloed, hefboom)* van elke observatie te onderzoeken. Dit is een diagnostische maat voor de mogelijkse invloed van predictor-observaties (in tegenstelling tot de residu's die een diagnostische maat vormen voor de invloed van de uitkomsten). In het bijzonder is de leverage van de $i$-de observatie een maat voor de afstand van predictorwaarde voor de $i$-de observatie tot de gemiddelde predictorwaarde in de steekproef. Hieruit volgt bijgevolg dat indien de leverage voor de $i$-de observatie groot is, ze predictorwaarden heeft die sterk afwijken van het gemiddelde. In dat geval heeft die observatie mogelijks ook grote invloed op de regressieparameters en predicties. Leverage waarden variëren normaal tussen $1/n$ en 1 en zijn gemiddeld $p/n$ met $p$ het aantal ongekende parameters (intercept + $p-1$ hellingen). Een extreme leverage wordt typisch aanschouwd als een waarde groter dan $2p/n$.\n\n### Cook's distance\n\nEen meer rechtstreekse maat om de invloed van elke observatie op de regressie-analyse uit te drukken is de *Cook's distance*. De Cook's distance voor de $i$-de observatie is een diagnostische maat voor de invloed van die observatie op alle predicties of, equivalent, voor haar invloed  op *alle* geschatte parameters. Men bekomt deze door elke predictie $\\hat{Y}_j$ die men op basis van het regressiemodel heeft bekomen voor de $j$-de uitkomst, $j=1,...,n$, te vergelijken met de overeenkomstige predictie $\\hat{Y}_{j(i)}$ die men zou bekomen indien de $i$-de observatie niet gebruikt werd om het regressiemodel te fitten\n\n$$\nD_i=\\frac{\\sum_{j=1}^n(\\hat{Y}_j-\\hat{Y}_{j(i)})^2}{p\\textrm{MSE}}\n$$\n\nIndien de Cook's distance $D_i$ groot is, dan heeft de $i$-de observatie een grote invloed op de predicties en geschatte parameters. In het bijzonder stelt men dat een extreme Cook's distance het 50% percentiel van de $F_{p,n-p}$-verdeling overschrijdt.\n\n\nDeze plots komen standaard bij diagnose van het lineair model.\nWe evalueren dit voor het additieve model en het model met de lcavol:lweight interactie voor de prostaatkanker studie.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npar(mfrow=c(2,2))\nplot(lmVWS,which=5)\nplot(lmVWS_IntVW,which=5)\nplot(cooks.distance(lmVWS),type=\"h\",ylim=c(0,1),main=\"Additive model\")\nabline(h=qf(0.5,length(lmVWS$coef),nrow(prostate)-length(lmVWS$coef)),lty=2)\nplot(cooks.distance(lmVWS_IntVW),type=\"h\",ylim=c(0,1), main=\"Model with lcavol:lweight interaction\")\nabline(h=qf(0.5,length(lmVWS_IntVW$coef),nrow(prostate)-length(lmVWS_IntVW$coef)),lty=2)\n```\n\n::: {.cell-output-display}\n![Evaluatie van de invloed van individuele observaties op het additieve model (links) en het model met de lcavol:lweight interactie (rechts).](10-GeneralLinearModel_files/figure-epub/fig-prosCooksAdditiveInt-1.png){#fig-prosCooksAdditiveInt fig-align='center' width=100%}\n:::\n:::\n\n\nHet is duidelijk dat observatie 32 een grote leverage heeft. Het heeft in het model met interactie ook de grootste invloed van alle datapunten op de fit van het model.\n\nEenmaal men vastgesteld heeft dat een observatie invloedrijk is, kan men zogenaamde *DFBETAS* gebruiken om te bepalen op welke parameter(s) ze een grote invloed uitoefent. De DFBETAS van de $i$-de observatie vormen een diagnostische maat voor de invloed van die observatie *op elke regressieparameter afzonderlijk*, in tegenstelling tot de Cook's distance die de invloed op alle parameters tegelijk evalueert. In het bijzonder bekomt men de DFBETAS voor de $i$-de observatie en de $j$-de parameter door de $j$-de parameter $\\hat{\\beta}_j$ te vergelijken met de parameter $\\hat{\\beta}_{j(i)}$ die men zou bekomen indien het regressiemodel gefit werd zonder de $i$-de observatie in de analyse te betrekken:\n\n$$\\textrm{DFBETAS}_{j(i)}=\\frac{\\hat{\\beta}_{j}-\\hat{\\beta}_{j(i)}}{\\textrm{SD}(\\hat{\\beta}_{j})}$$\n\nUit bovenstaande uitdrukking volgt dat het teken van de DFBETAS voor de $i$-de observatie aangeeft of het weglaten van die observatie uit de analyse een stijging (DFBETAS$<0$) of daling (DFBETAS$>0$) in de overeenkomstige parameter veroorzaakt. In het bijzonder stelt men dat een DFBETAS extreem is wanneer ze 1 overschrijdt in kleine tot middelgrote datasets en $2/\\sqrt{n}$ overschrijdt in grote datasets.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npar(mfrow=c(2,2))\ndfbetasPlots(lmVWS)\n```\n\n::: {.cell-output-display}\n![DFBETAS voor additieve model in prostaatkanker.](10-GeneralLinearModel_files/figure-epub/fig-prosDfBetasAdditive-1.png){#fig-prosDfBetasAdditive fig-align='center' width=100%}\n:::\n:::\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npar(mfrow=c(2,2))\ndfbetasPlots(lmVWS_IntVW)\n```\n\n::: {.cell-output-display}\n![DFBETAS voor model met lcavol:lweight interactie.](10-GeneralLinearModel_files/figure-epub/fig-prosDfBetasInt-1.png){#fig-prosDfBetasInt fig-align='center' width=100%}\n:::\n:::\n\n\nDe Cooks distances en de DFBETAS plots geven aan dat observatie 32 het grootste effect heeft op de regressieparameters. Daarnaast heeft deze observatie ook een extreme \"influence\".\n\nWe gaan observatie 32 nu wat beter bestuderen.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nexp(prostate[32,\"lweight\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  lweight\n    <dbl>\n1    449.\n```\n\n\n:::\n\n```{.r .cell-code}\nboxplot(exp(prostate$lweight),ylab=\"Prostaatgewicht (g)\")\n```\n\n::: {.cell-output-display}\n![Boxplot met outlier voor prostaatgewicht.](10-GeneralLinearModel_files/figure-epub/fig-prosInfl-1.png){#fig-prosInfl fig-align='center' width=100%}\n:::\n:::\n\n\nWanneer we het gewicht terugtransformeren naar de originele schaal zien we dat het prostaatgewicht voor deze patiënt 449.25 g bedraagt. De prostaat van een man heeft gewoonlijk een gewicht van 20-30 gram en het kan vergroten tot 50-100 gram.\nEen prostaatgewicht van meer dan 400 gram komt dus niet voor.\nDe auteurs die de dataset uit de originele publicatie hebben opgenomen in een handboek, hebben gerapporteerd dat ze een tikfout hebben gemaakt en ze hebben het extreme prostaat gewicht later gecorrigeerd naar 49.25 gram, het gewicht dat in de originele publicatie werd gerapporteerd.\n\nGa zelf na welke invloed het corrigeren van het prostaatgewicht heeft op het geschatte regressiemodel.\n\n\n## Contrasten\n\n<iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/TXuXuve20wM\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n\n- Bij meer complexe algemene lineaire modellen wenst men dikwijls meerdere hypothesen te toetsen.\n- Bovendien vertalen de onderzoekshypotheses zich hierbij niet steeds in één parameter, maar in een lineaire combinatie van modelparameters.\n- Een lineaire combinatie van modelparameters wordt ook een contrast genoemd.\n\n### NHANES voorbeeld\n\n- Stel dat de onderzoekers de associatie tussen de leeftijd en de bloeddruk wensen te bestuderen bij Amerikaanse kinderen. Mogelijks is die associatie anders is bij jongens en meisjes.\n\n- De onderzoekers wensen de volgende onderzoeksvragen te beantwoorden:\n\n    - Is er een associatie tussen leeftijd en de bloeddruk  bij meisjes?\n    - Is er een associatie tussen leeftijd en de bloeddruk bij jongens?\n    - Is de associatie tussen leeftijd en de bloeddruk verschillend bij jongens dan bij meisjes?\n\n### Model\n\nWe fitten een model op basis van de gemiddelde systolische bloeddruk (`BPSysAve`) in functie van de leeftijd, geslacht en een interactie tussen leeftijd en geslacht voor volwassen blanke subjecten uit de NHANES studie.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(NHANES)\nbpData <- NHANES |>\nfilter(\n    Age >=6 & \n    Age <= 18 &\n    !is.na(BPSysAve) & \n    !is.na(AgeMonths))\n\nmBp1 <- lm(BPSysAve ~ AgeMonths*Gender, bpData)\ndim(bpData)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 703  76\n```\n\n\n:::\n\n```{.r .cell-code}\npar(mfrow = c(2,2))\nplot(mBp1)\n```\n\n::: {.cell-output-display}\n![](10-GeneralLinearModel_files/figure-epub/unnamed-chunk-14-1.png)\n:::\n:::\n\n\n- Aannames ?\n\n    - lineariteit lijkt ok\n    - Aanname van gelijkheid van variantie lijkt voldaan\n    - Lichte afwijkeingen van normaliteit: indicatie voor lichtjes scheve verdeling met staart naar rechts.\n    - Grote dataset (n = 703) we kunnen steunen op de CLT\n\n<!---break-->\n\n### Besluitvorming\n\n<iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/GLan10H4kuk\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(mBp1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = BPSysAve ~ AgeMonths * Gender, data = bpData)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-30.487  -5.871  -0.890   5.265  33.882 \n\nCoefficients:\n                      Estimate Std. Error t value Pr(>|t|)    \n(Intercept)           92.90682    2.29792  40.431  < 2e-16 ***\nAgeMonths              0.05943    0.01371   4.336 1.66e-05 ***\nGendermale           -11.35031    3.25237  -3.490 0.000514 ***\nAgeMonths:Gendermale   0.09294    0.01943   4.783 2.11e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 9.65 on 699 degrees of freedom\nMultiple R-squared:  0.1939,\tAdjusted R-squared:  0.1904 \nF-statistic: 56.04 on 3 and 699 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nDe onderzoeksvragen vertalen zich in de volgende nullhypotheses:\n\n1. Associatie tussen bloeddruk en leeftijd bij de meisjes?\n\n$$\nH_0: \\beta_\\text{AgeMonths} = 0 \\text{ vs } H_1: \\beta_\\text{AgeMonths} \\neq 0\n$$\n\n2. Associatie tussen bloeddruk en leeftijd bij de jongens?\n\n$$\nH_0: \\beta_\\text{AgeMonths} + \\beta_\\text{AgeMonths:Gendermale} = 0 \\text{ vs } H_1: \\beta_\\text{AgeMonths} + \\beta_\\text{AgeMonths:Gendermale} \\neq 0\n$$\n\n3. Is de Associatie tussen bloeddruk en leeftijd verschillend bij jongens en meisjes?\n\n$$H_0: \\beta_\\text{AgeMonths:Gendermale} = 0 \\text{ vs } H_1: \\beta_\\text{AgeMonths:Gendermale} \\neq 0\n$$\n\n\n- We kunnen onderzoeksvraag 1 en 3 onmiddelijk toetsen o.b.v. de model output.\n- Onderzoeksvraag 2 is echter een lineaire combinatie van twee parameters.\n- Bovendien is er ook het probleem dat we meerdere toetsen nodig hebben om de associaties te bestuderen.\n\nWe kunnen opnieuw gebruik maken van een Anova approach.\n\n1.  We toetsen eerste de omnibus hypothese dat er geen associatie is tussen leeftijd en de bloeddruk.\n\n$$\nH_0: \\beta_\\text{AgeMonths} = \\beta_\\text{AgeMonths} + \\beta_\\text{Age:Gendermale} = \\beta_\\text{Age:Gendermale} = 0\n$$\n\n  - Dat vereenvoudigt zich tot het toetsen dat\n\n$$\nH_0: \\beta_\\text{AgeMonths} = \\beta_\\text{Age:Gendermale} = 0\n$$\n\n  - Wat we kunnen evalueren door twee modellen te vergelijken. Een model met enkel het gender effect en het volledige model met Gender, Age en de Gender x Age interactie.\n\n2. Als we deze hypothese kunnen verwerpen voeren we posthoc analyses uit voor elk van de 3 contrasten.\n\n\n#### Omnibus test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmBp0 <- lm(BPSysAve ~ Gender, bpData)\nanova(mBp0, mBp1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: BPSysAve ~ Gender\nModel 2: BPSysAve ~ AgeMonths * Gender\n  Res.Df   RSS Df Sum of Sq      F    Pr(>F)    \n1    701 78239                                  \n2    699 65095  2     13145 70.576 < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n#### Posthoc testen\n\nDe posthoc testen kunnen we opnieuw uitvoeren a.d.h.v. het multcomp pakket.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(multcomp)\nbpPosthoc <- glht(mBp1, linfct=c(\n  \"AgeMonths = 0\",\n  \"AgeMonths + AgeMonths:Gendermale = 0\",\n  \"AgeMonths:Gendermale = 0\")\n  )\nbpPosthoc |> summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t Simultaneous Tests for General Linear Hypotheses\n\nFit: lm(formula = BPSysAve ~ AgeMonths * Gender, data = bpData)\n\nLinear Hypotheses:\n                                      Estimate Std. Error t value Pr(>|t|)    \nAgeMonths == 0                         0.05943    0.01371   4.336 3.69e-05 ***\nAgeMonths + AgeMonths:Gendermale == 0  0.15237    0.01377  11.061  < 1e-05 ***\nAgeMonths:Gendermale == 0              0.09294    0.01943   4.783  < 1e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n(Adjusted p values reported -- single-step method)\n```\n\n\n:::\n\n```{.r .cell-code}\nbpPosthocBI <- bpPosthoc |> confint()\nbpPosthocBI\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t Simultaneous Confidence Intervals\n\nFit: lm(formula = BPSysAve ~ AgeMonths * Gender, data = bpData)\n\nQuantile = 2.3215\n95% family-wise confidence level\n \n\nLinear Hypotheses:\n                                      Estimate lwr     upr    \nAgeMonths == 0                        0.05943  0.02761 0.09124\nAgeMonths + AgeMonths:Gendermale == 0 0.15237  0.12039 0.18434\nAgeMonths:Gendermale == 0             0.09294  0.04783 0.13805\n```\n\n\n:::\n:::\n\n\nMerk op dat de glht functie ons toelaat om de contrasten te definiëren door de nulhypotheses expliciet te formuleren in een karaktervector waarbij gebruik wordt gemaakt van de naam van de pararameters in het model.\n\n#### Conclusie\n\nWe kunnen besluiten dat er een extreem significante associatie is tussen leeftijd en de bloeddruk (p << 0.001).\nDe bloeddruk bij twee meisjes die in leeftijd verschillen is gemiddeld 0.06 mm Hg hoger per maand leeftijdsverschil bij het oudere meisje (p << 0.001, 95% BI [0.03, 0.09].\nDe bloeddruk bij jongens die in leeftijd verschillen is gemiddeld 0.15 mm Hg hoger per maand leeftijdsverschil bij de oudere jongen. (p << 0.001, 95% BI [0.12, 0.18].\nHet gemiddelde bloeddrukverschil tussen personen in leeftijd verschillen is gemiddeld 0.09 mm Hg/maand hoger bij jongens dan meisjes (p << 0.001, 95% BI [0.05, 0.14]).  \n\n\n\n\n## Factoriële proeven \n\n### Introductie\n\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/V1QAv2_oYBs\n\" frameborder=\"0\" style=\"display: block; margin: auto;\" allow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n\n\n\nIn deze sectie illustreren we hoe experimenten met een factoriële proefopzet geanalyseerd kunnen worden met het algemeen lineair model. \n\nWe focussen hierbij op een two-way anova design waarbij we een continue response modelleren in functie van twee categorische predictor variabelen (factoren). \n\n\n### Data \n\n\n48 ratten werden at random toegewezen aan\n\n- 3 giffen (I,II,III) en\n- 4 behandelingen (A,B,C,D),\n\nen, \n\n- de overlevingstijd werd opgemeten (eenheid: 10 h)\n\nWe transformeren de data eerst naar uren\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(faraway)\ndata(rats)\n\nrats <- rats |> \n  mutate(time=time * 10)\n\nlibrary(GGally)\nrats |> \n  ggpairs()\n```\n\n::: {.cell-output-display}\n![](10-GeneralLinearModel_files/figure-epub/unnamed-chunk-18-1.png)\n:::\n:::\n\n\nDe data exploratie suggereert een effect van beide factoren. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nrats |>\n  ggplot(aes(x=treat,y=time)) + \n  geom_boxplot(outlier.shape=NA) + \n  geom_jitter() +\n  facet_wrap(~poison) +\n  ylab(\"time (h)\")\n```\n\n::: {.cell-output-display}\n![](10-GeneralLinearModel_files/figure-epub/unnamed-chunk-19-1.png)\n:::\n:::\n\n\n- Er zou een interactie kunnen zijn tussen behandeling en gif, het effect van het gif op de overlevingstijd hangt dan af van de behandeling en vice versa. \n- De boxplots geven ook aan dat de data heteroscedastisch zijn. \n\n<!---break-->\n\n### Model \n\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/UxHKF0fgwkY\n\" frameborder=\"0\" style=\"display: block; margin: auto;\" allow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n\n\nWe modelleren de data met een hoofdeffect voor gif en behandeling en een gif $\\times$ behandeling interactie. \n\n$$\n\\begin{array}{lcl}\ny_i &=& \\beta_0  + \\\\\n&&\\beta_{II} x_{iII} + \\beta_{III} x_{iIII} + \\\\\n&& \\beta_{B} x_{iB}  + \\beta_{C} x_{iC} + \\beta_{D} x_{iD} + \\\\\n&&\\beta_{II:B}x_{iII}x_{iB} + \\beta_{II:C}x_{iII}x_{iC}  + \\beta_{II:D}x_{iII}x_{iD} + \\\\\n&&\\beta_{III:B}x_{iIII}x_{iB} + \\beta_{III:C}x_{iIII}x_{iC}  + \\beta_{III:D}x_{iIII}x_{iD} +\n\\epsilon_i\n\\end{array}\n$$\n\nmet $i = 1, \\ldots, n$, $n=48$, en, $x_{iII}$, $x_{iIII}$, $x_{iB}$, $x_{iC}$ en $x_{iD}$ dummy variabelen voor respectievelijk gif II, III, behandeling B, C, en D.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrats1 <- lm(time~poison*treat, rats)\nsummary(rats1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = time ~ poison * treat, data = rats)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.2500 -0.4875  0.0500  0.4312  4.2500 \n\nCoefficients:\n                 Estimate Std. Error t value Pr(>|t|)    \n(Intercept)        4.1250     0.7457   5.532 2.94e-06 ***\npoisonII          -0.9250     1.0546  -0.877   0.3862    \npoisonIII         -2.0250     1.0546  -1.920   0.0628 .  \ntreatB             4.6750     1.0546   4.433 8.37e-05 ***\ntreatC             1.5500     1.0546   1.470   0.1503    \ntreatD             1.9750     1.0546   1.873   0.0692 .  \npoisonII:treatB    0.2750     1.4914   0.184   0.8547    \npoisonIII:treatB  -3.4250     1.4914  -2.297   0.0276 *  \npoisonII:treatC   -1.0000     1.4914  -0.671   0.5068    \npoisonIII:treatC  -1.3000     1.4914  -0.872   0.3892    \npoisonII:treatD    1.5000     1.4914   1.006   0.3212    \npoisonIII:treatD  -0.8250     1.4914  -0.553   0.5836    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.491 on 36 degrees of freedom\nMultiple R-squared:  0.7335,\tAdjusted R-squared:  0.6521 \nF-statistic:  9.01 on 11 and 36 DF,  p-value: 1.986e-07\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(rats1)\n```\n\n::: {.cell-output-display}\n![](10-GeneralLinearModel_files/figure-epub/unnamed-chunk-20-1.png)\n:::\n\n::: {.cell-output-display}\n![](10-GeneralLinearModel_files/figure-epub/unnamed-chunk-20-2.png)\n:::\n\n::: {.cell-output-display}\n![](10-GeneralLinearModel_files/figure-epub/unnamed-chunk-20-3.png)\n:::\n\n::: {.cell-output-display}\n![](10-GeneralLinearModel_files/figure-epub/unnamed-chunk-20-4.png)\n:::\n:::\n\n\nDe errors zijn heteroscedastisch. De residu plot suggereert een relatie tussen gemiddelde en variantie. De QQ-plot suggereert dat de verdeling mogelijks bredere staarten heeft dan de normale verdeling. \n\n\n#### Transformaties \n\n##### Logaritmische transformatie \n\n\n::: {.cell}\n\n```{.r .cell-code}\nrats |>\n  ggplot(aes(x=treat,y=log2(time))) + \n  geom_boxplot(outlier.shape=NA) + \n  geom_jitter() +\n  facet_wrap(~poison)\n```\n\n::: {.cell-output-display}\n![](10-GeneralLinearModel_files/figure-epub/unnamed-chunk-21-1.png)\n:::\n\n```{.r .cell-code}\nrats2 <- lm(time |> log2()~poison*treat, rats)\nplot(rats2)\n```\n\n::: {.cell-output-display}\n![](10-GeneralLinearModel_files/figure-epub/unnamed-chunk-21-2.png)\n:::\n\n::: {.cell-output-display}\n![](10-GeneralLinearModel_files/figure-epub/unnamed-chunk-21-3.png)\n:::\n\n::: {.cell-output-display}\n![](10-GeneralLinearModel_files/figure-epub/unnamed-chunk-21-4.png)\n:::\n\n::: {.cell-output-display}\n![](10-GeneralLinearModel_files/figure-epub/unnamed-chunk-21-5.png)\n:::\n:::\n\n\nLog transformatie verwijdert heteroscedasticiteit niet volledig. \n\n##### Reciproke transformatie\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrats |>\n  ggplot(aes(x=treat,y=1/time)) + \n  geom_boxplot(outlier.shape=NA) + \n  geom_jitter() +\n  facet_wrap(~poison) + \n  ylab (\"rate of dying (1/h)\")\n```\n\n::: {.cell-output-display}\n![](10-GeneralLinearModel_files/figure-epub/unnamed-chunk-22-1.png)\n:::\n\n```{.r .cell-code}\nrats3 <- lm(1/time~poison*treat, rats)\nplot(rats3) \n```\n\n::: {.cell-output-display}\n![](10-GeneralLinearModel_files/figure-epub/unnamed-chunk-22-2.png)\n:::\n\n::: {.cell-output-display}\n![](10-GeneralLinearModel_files/figure-epub/unnamed-chunk-22-3.png)\n:::\n\n::: {.cell-output-display}\n![](10-GeneralLinearModel_files/figure-epub/unnamed-chunk-22-4.png)\n:::\n\n::: {.cell-output-display}\n![](10-GeneralLinearModel_files/figure-epub/unnamed-chunk-22-5.png)\n:::\n:::\n\n\nDe reciproke transformatie lijkt beter. \nTransformaties bemoeilijken soms de interpretatie. \nHier kan de reciproke transformatie echter worden geïnterpreteerd als de \"snelheid van sterven\" (rate of dying). \n\n<!---break-->\n\n### Inferentie \n\n\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/Dy3SyyamlHg\n\" frameborder=\"0\" style=\"display: block; margin: auto;\" allow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n\n\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/GtGKActzZT0\n\" frameborder=\"0\" style=\"display: block; margin: auto;\" allow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n\nEr zijn meerdere interactie termen in het model. \nWe kunnen deze eerst samen testen a.d.h.v. van de resultaten uit de anova tabel. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(car)\nAnova(rats3, type=\"III\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnova Table (Type III tests)\n\nResponse: 1/time\n               Sum Sq Df  F value    Pr(>F)    \n(Intercept)  0.247383  1 103.0395 4.158e-12 ***\npoison       0.111035  2  23.1241 3.477e-07 ***\ntreat        0.035723  3   4.9598  0.005535 ** \npoison:treat 0.015708  6   1.0904  0.386733    \nResiduals    0.086431 36                       \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n#### Verwijderen van niet-significante interactie. \n\nDe interactie tussen gif en behandeling is niet significant op het 5% niveau. \n\nEen veelgebruikte methode is om de niet-significante interactie te verwijderen uit het model. \n\nWe verkrijgen dan een additief model wat toelaat om de effecten van de twee factoren afzonderlijk te bestuderen. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nrats4 <- lm(1/time~poison + treat, rats)\nplot(rats4)\n```\n\n::: {.cell-output-display}\n![](10-GeneralLinearModel_files/figure-epub/unnamed-chunk-24-1.png)\n:::\n\n::: {.cell-output-display}\n![](10-GeneralLinearModel_files/figure-epub/unnamed-chunk-24-2.png)\n:::\n\n::: {.cell-output-display}\n![](10-GeneralLinearModel_files/figure-epub/unnamed-chunk-24-3.png)\n:::\n\n::: {.cell-output-display}\n![](10-GeneralLinearModel_files/figure-epub/unnamed-chunk-24-4.png)\n:::\n:::\n\n\nWe zien wel iets meer afwijkingen in de residu plot.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nAnova(rats4, type=\"III\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnova Table (Type III tests)\n\nResponse: 1/time\n             Sum Sq Df F value    Pr(>F)    \n(Intercept) 0.58219  1 239.399 < 2.2e-16 ***\npoison      0.34877  2  71.708 2.865e-14 ***\ntreat       0.20414  3  27.982 4.192e-10 ***\nResiduals   0.10214 42                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nDe anova tabel toont dat het effect van gif en behandeling beiden extreem significant zijn (beide $p<< 0.001$).\n\nHet additieve model laat toe om de effecten van het type gif en de behandeling afzonderlijke te bestuderen via een post-hoc analyse. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(multcomp)\ncomparisons <- glht(rats4, linfct = mcp(poison = \"Tukey\", treat=\"Tukey\"))\nsummary(comparisons)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t Simultaneous Tests for General Linear Hypotheses\n\nMultiple Comparisons of Means: Tukey Contrasts\n\n\nFit: lm(formula = 1/time ~ poison + treat, data = rats)\n\nLinear Hypotheses:\n                      Estimate Std. Error t value Pr(>|t|)    \npoison: II - I == 0    0.04686    0.01744   2.688  0.07347 .  \npoison: III - I == 0   0.19964    0.01744  11.451  < 0.001 ***\npoison: III - II == 0  0.15278    0.01744   8.763  < 0.001 ***\ntreat: B - A == 0     -0.16574    0.02013  -8.233  < 0.001 ***\ntreat: C - A == 0     -0.05721    0.02013  -2.842  0.05091 .  \ntreat: D - A == 0     -0.13583    0.02013  -6.747  < 0.001 ***\ntreat: C - B == 0      0.10853    0.02013   5.391  < 0.001 ***\ntreat: D - B == 0      0.02991    0.02013   1.485  0.61547    \ntreat: D - C == 0     -0.07862    0.02013  -3.905  0.00276 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n(Adjusted p values reported -- single-step method)\n```\n\n\n:::\n\n```{.r .cell-code}\nconfint(comparisons)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t Simultaneous Confidence Intervals\n\nMultiple Comparisons of Means: Tukey Contrasts\n\n\nFit: lm(formula = 1/time ~ poison + treat, data = rats)\n\nQuantile = 2.8498\n95% family-wise confidence level\n \n\nLinear Hypotheses:\n                      Estimate   lwr        upr       \npoison: II - I == 0    0.0468641 -0.0028223  0.0965506\npoison: III - I == 0   0.1996425  0.1499561  0.2493289\npoison: III - II == 0  0.1527784  0.1030919  0.2024648\ntreat: B - A == 0     -0.1657402 -0.2231132 -0.1083673\ntreat: C - A == 0     -0.0572135 -0.1145865  0.0001594\ntreat: D - A == 0     -0.1358338 -0.1932068 -0.0784609\ntreat: C - B == 0      0.1085267  0.0511538  0.1658996\ntreat: D - B == 0      0.0299064 -0.0274665  0.0872794\ntreat: D - C == 0     -0.0786203 -0.1359932 -0.0212473\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(comparisons,yaxt=\"none\")\ncontrastNames <- c(\"II-I\",\"III-I\",\"III-II\",\"B-A\",\"C-A\",\"D-A\",\"C-B\",\"D-B\",\"D-C\")\naxis(2,at=c(length(contrastNames):1), labels=contrastNames,las=2)\n```\n\n::: {.cell-output-display}\n![](10-GeneralLinearModel_files/figure-epub/unnamed-chunk-26-1.png)\n:::\n:::\n\n\n#### Niet-significante interactie term in het model weerhouden\n\nHet aanvaarden van de nulhypothese dat er geen interactie is, is een zwakke conclusie.\nHet zou immers kunnen dat de power van het experiment te klein is om de interactie op te pikken.\nWe kunnen er ook voor kiezen om de niet significante interactie term in het model te laten. \n\nAls de interactie significant zou zijn geweest, betekent dit dat het effect van het gif op de snelheid van sterven afhangt van de behandeling en vice versa. \nDan kunnen we het effect van het type gif en de behandeling op de overlevingstijd niet afzonderlijk bestuderen. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nExploreModelMatrix::VisualizeDesign(rats,~poison*treat)$plot\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](10-GeneralLinearModel_files/figure-epub/unnamed-chunk-27-1.png)\n:::\n:::\n\n\nWe zouden dan het effect van het type gif afzonderlijk moeten bestuderen voor elke behandeling: \n\n1. Voor behandeling A moeten we dan volgende nulhypotheses toetsen:\n\n- II-I: $H_0: \\beta_{II}=0$\n- III-I: $H_0: \\beta_{III}=0$\n- III-II: $H_0: \\beta_{III}-\\beta_{II}=0$\n\n2. Voor behandeling B:\n\n- II-I: $H_0: \\beta_{II}+\\beta_{II:B}=0$\n- III-I: $H_0: \\beta_{III}+\\beta_{III:B}=0$\n- III-II: $H_0: \\beta_{III}+\\beta_{III:B}-\\beta_{II}-\\beta_{II:B}=0$\n\n3. Voor behandeling C:\n\n- II-I: $H_0: \\beta_{II}+\\beta_{II:C}=0$\n- III-I: $H_0: \\beta_{III}+\\beta_{III:C}=0$\n- III-II: $H_0: \\beta_{III}+\\beta_{III:C}-\\beta_{II}-\\beta_{II:C}=0$\n\n4. Voor behandeling D:\n\n- II-I: $H_0: \\beta_{II}+\\beta_{II:D}=0$\n- III-I: $H_0: \\beta_{III}+\\beta_{III:D}=0$\n- III-II: $H_0: \\beta_{III}+\\beta_{III:D}-\\beta_{II}-\\beta_{II:D}=0$\n\nHet zelfde geldt wanneer we het effect van de behandeling bestuderen: \n\n1. Voor gif I toetsen we dan nulhypothese\n\n- B-A: $H_0: \\beta_{B}=0$\n- C-A: $H_0: \\beta_{C}=0$\n- D-A: $H_0: \\beta_{D}=0$\n- C-B: $H_0: \\beta_{C}-\\beta_{B}=0$\n- D-B: $H_0: \\beta_{D}-\\beta_{B}=0$\n- D-C: $H_0: \\beta_{D}-\\beta_{C}=0$\n\n2. Gif II\n\n- B-A: $H_0: \\beta_{B}+\\beta_{II:B}=0$\n- C-A: $H_0: \\beta_{C}+\\beta_{II:C}=0$\n- D-A: $H_0: \\beta_{D}+\\beta_{II:D}=0$\n- C-B: $H_0: \\beta_{C}+\\beta_{II:C}-\\beta_{B}-\\beta_{II:B}=0$\n- D-B: $H_0: \\beta_{D}+\\beta_{II:D}-\\beta_{B}-\\beta_{II:B}=0$\n- D-C: $H_0: \\beta_{D}+\\beta_{II:D}-\\beta_{C}-\\beta_{II:C}=0$\n\n3. Gif III\n\n- B-A: $H_0: \\beta_{B}+\\beta_{III:B}=0$\n- C-A: $H_0: \\beta_{C}+\\beta_{III:C}=0$\n- D-A: $H_0: \\beta_{D}+\\beta_{III:D}=0$\n- C-B: $H_0: \\beta_{C}+\\beta_{III:C}-\\beta_{B}-\\beta_{III:B}=0$\n- D-B: $H_0: \\beta_{D}+\\beta_{III:D}-\\beta_{B}-\\beta_{III:B}=0$\n- D-C: $H_0: \\beta_{D}+\\beta_{III:D}-\\beta_{C}-\\beta_{III:C}=0$\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncomparisonsInt <- glht(rats3, linfct = c(\n  \"poisonII = 0\",\n  \"poisonIII = 0\",\n  \"poisonIII - poisonII = 0\",\n  \"poisonII + poisonII:treatB = 0\",\n  \"poisonIII + poisonIII:treatB = 0\",\n  \"poisonIII + poisonIII:treatB - poisonII- poisonII:treatB = 0\",  \n  \"poisonII + poisonII:treatC = 0\",\n  \"poisonIII + poisonIII:treatC = 0\",\n  \"poisonIII + poisonIII:treatC - poisonII- poisonII:treatC = 0\",  \n  \"poisonII + poisonII:treatD = 0\",\n  \"poisonIII + poisonIII:treatD = 0\",\n  \"poisonIII + poisonIII:treatD - poisonII- poisonII:treatD = 0\",  \n  \"treatB = 0\",\n  \"treatC = 0\",\n  \"treatD = 0\",\n  \"treatC - treatB = 0\",\n  \"treatD - treatB = 0\",\n  \"treatD - treatC = 0\",\n  \"treatB + poisonII:treatB = 0\",\n  \"treatC + poisonII:treatC = 0\",\n  \"treatD + poisonII:treatD = 0\",\n  \"treatC + poisonII:treatC - treatB - poisonII:treatB = 0\",\n  \"treatD + poisonII:treatD - treatB - poisonII:treatB = 0\",\n  \"treatD + poisonII:treatD - treatC - poisonII:treatC = 0\",\n  \"treatB + poisonIII:treatB = 0\",\n  \"treatC + poisonIII:treatC = 0\",\n  \"treatD + poisonIII:treatD = 0\",\n  \"treatC + poisonIII:treatC - treatB - poisonIII:treatB = 0\",\n  \"treatD + poisonIII:treatD - treatB - poisonIII:treatB = 0\",\n  \"treatD + poisonIII:treatD - treatC - poisonIII:treatC = 0\")\n)\n\ncontrastNames<-\n  c(paste(rep(LETTERS[1:4],each=3),rep(apply(combn(c(\"I\",\"II\",\"III\"),2)[2:1,],2,paste,collapse=\"-\") ,4),sep=\": \"),\n    paste(rep(c(\"I\",\"II\",\"III\"),each=6),rep(apply(combn(c(LETTERS[1:4]),2)[2:1,],2,paste,collapse=\"-\") ,3),sep=\": \"))\n\nplot(comparisonsInt,yaxt=\"none\")\naxis(2,at=c(length(contrastNames):1), labels=contrastNames,las=2)\n```\n\n::: {.cell-output-display}\n![](10-GeneralLinearModel_files/figure-epub/unnamed-chunk-28-1.png)\n:::\n:::\n\n\nIn onze studie was de interactie echter niet significant. Het effect van het gif (II-I, III-I en III-II) verandert dus niet significant volgens de behandeling (A, B, C, en D) en vice versa. Voor onze dataset lijkt het dus zinvol om \n\n1. de effectgrootte voor de paarsgewijze vergelijkingen tussen de verschillende giffen (II-I, III-I en III-II) te schatten door ze uit te middelen over alle behandelingen (A, B, C, en D), en, \n2.  de effectgrootte voor de paarsgewijze vergelijkingen tussen de verschillende behandelingen (B-A, C-A, D-A, C-B, D-B en D-C) te schatten door ze uit te middelen over alle giffen (I, II, III). \n\nDat zou ons gelijkaardige schattingen van de effectgroottes moeten geven als deze voor het additieve model waarbij we de interactie term uit het model hadden geweerd. \n\n\nB.v. voor gif III vs gif II zou dat in volgende contrast resulteren: \n\n- III-II: \n$$H_0: \n\\begin{array}{l}\n\\frac{\\beta_{III}-\\beta_{II}}{4} + \\\\\n\\quad \\frac{\\beta_{III} + \\beta_{III:B}-\\beta_{II} - \\beta_{II:B}}{4} + \\\\\n\\quad \\quad \\frac{\\beta_{III} + \\beta_{III:C}-\\beta_{II} - \\beta_{II:C}}{4} + \\\\\n\\quad \\quad \\quad \\frac{\\beta_{III} + \\beta_{III:D}-\\beta_{II} - \\beta_{II:D}}{4}=0\n\\end{array}\n$$\n$$\nH_0:\\beta_{III} + \\frac{1}{4} \\times \\beta_{III:B} +  \\frac{1}{4} \\times\\beta_{III:C} +  \\frac{1}{4} \\times\\beta_{III:D}\n-\\beta_{II} - \\frac{1}{4} \\times\\beta_{II:B} -  \\frac{1}{4} \\times\\beta_{II:C}  - \\frac{1}{4} \\times\\beta_{II:D}=0\n$$\n\nWe schatten met onderstaande code alle gemiddelde contrasten a.d.h.v. het model met interactie.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontrasts <- c(\n  \"poisonII + 1/4*poisonII:treatB + 1/4*poisonII:treatC + 1/4*poisonII:treatD = 0\",\n  \"poisonIII + 1/4*poisonIII:treatB + 1/4*poisonIII:treatC + 1/4*poisonIII:treatD= 0\",\n  \"poisonIII + 1/4*poisonIII:treatB + 1/4*poisonIII:treatC + 1/4*poisonIII:treatD - poisonII - 1/4*poisonII:treatB - 1/4*poisonII:treatC - 1/4*poisonII:treatD = 0\",\n  \"treatB + 1/3*poisonII:treatB + 1/3*poisonIII:treatB = 0\",\n  \"treatC + 1/3*poisonII:treatC + 1/3*poisonIII:treatC = 0\",\n  \"treatD + 1/3*poisonII:treatD + 1/3*poisonIII:treatD = 0\",\n  \"treatC + 1/3*poisonII:treatC + 1/3*poisonIII:treatC - treatB - 1/3*poisonII:treatB - 1/3*poisonIII:treatB = 0\",\n  \"treatD + 1/3*poisonII:treatD + 1/3*poisonIII:treatD  - treatB - 1/3*poisonII:treatB - 1/3*poisonIII:treatB = 0\",\n  \"treatD + 1/3*poisonII:treatD + 1/3*poisonIII:treatD  - treatC - 1/3*poisonII:treatC - 1/3*poisonIII:treatC = 0\") \n\n\ncomparisonsInt2 <- glht(rats3, linfct = contrasts\n)\nplot(comparisonsInt2,yaxt=\"none\")\ncontrastNames <- c(\"II-I\",\"III-I\",\"III-II\",\"B-A\",\"C-A\",\"D-A\",\"C-B\",\"D-B\",\"D-C\")\naxis(2,at=c(length(contrastNames):1), labels=contrastNames,las=2)\n```\n\n::: {.cell-output-display}\n![](10-GeneralLinearModel_files/figure-epub/unnamed-chunk-29-1.png)\n:::\n:::\n\n\nDe geschatte effectgroottes zijn inderdaad exact gelijk als bij het model zonder interactie omdat het experiment gebalanceerd is. \n\nDe standaard errors verschillen wel lichtjes. \nDat is het gevolg van de errors die verschillen tussen beiden modellen alsook het aantal vrijheidsgraden van de errors (n-p). \n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata.frame(Additive_coef=summary(comparisons)$test$coef,Additive_se=summary(comparisons)$test$sigma,Int_coef=summary(comparisonsInt2)$test$coef,int_se=summary(comparisonsInt2)$test$sigma) |> round(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 Additive_coef Additive_se Int_coef int_se\npoison: II - I           0.047       0.017    0.047  0.017\npoison: III - I          0.200       0.017    0.200  0.017\npoison: III - II         0.153       0.017    0.153  0.017\ntreat: B - A            -0.166       0.020   -0.166  0.020\ntreat: C - A            -0.057       0.020   -0.057  0.020\ntreat: D - A            -0.136       0.020   -0.136  0.020\ntreat: C - B             0.109       0.020    0.109  0.020\ntreat: D - B             0.030       0.020    0.030  0.020\ntreat: D - C            -0.079       0.020   -0.079  0.020\n```\n\n\n:::\n:::\n\n\n<!---break-->\n\n### Conclusie\n\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/95DvzLFe3yk\n\" frameborder=\"0\" style=\"display: block; margin: auto;\" allow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n\nEr is een extreem significant effect van het type gif en de behandeling op de snelheid van sterven bij ratten (p << 0.001).\n\nDe interactie tussen gif en behandeling is niet significant (p = 0.387). \n\nDe snelheid van sterven is gemiddeld 0.2h$^{-1}$  en 0.15h$^{-1}$ hoger voor ratten die blootgesteld worden aan gif III dan aan respectievelijk gif I en II (beide p << 0.001, 95% BI III-I: [0.15, 0.25]h$^{-1}$, 95% BI III-II: [0.1, 0.2]h$^{-1}$)\nDe gemiddelde snelheid van sterven was niet significant verschillend tussen ratten die werden blootgesteld aan gif I en gif II (p=0.074).\n\nDe snelheid van sterven is gemiddeld 0.17h$^{-1}$ en 0.14h$^{-1}$ hoger na behandeling A dan na behandeling B en D (p << 0.001, 95% BI B-A: [-0.22, -0.11]h$^{-1}$, 95% BI D-A: [-0.19, -0.08]h$^{-1}$). \nDe snelheid van sterven is gemiddeld 0.11h$^{-1}$ en 0.08h$^{-1}$ hoger na behandeling C dan respectievelijk na behandeling B en D (C-B: p << 0.001, 95% CI [0.05, 0.17]h$^{-1}$ , D-C: p = 0.003, 95% CI [-0.14, -0.02]h$^{-1}$). \nDe gemiddelde snelheid van sterven is niet significant verschillend tussen ratten behandeld met behandeling C vs A, en D vs B (p- waarden respectievelijk p = 0.051 en p = 0.61).\n\n",
    "supporting": [
      "10-GeneralLinearModel_files/figure-epub"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}