{
  "hash": "dc70fac0fcf08ae78e93730e5a45a065",
  "result": {
    "engine": "knitr",
    "markdown": "# Niet-parametrische statistiek\n\n\n\nAlle kennisclips die in dit hoofdstuk zijn verwerkt kan je in deze youtube playlist vinden:\n\n- [Kennisclips Hoofdstuk 8 Niet-parametrische Statistiek](https://www.youtube.com/playlist?list=PLZH1hP8_LbJJyR4mqLOxDwwOzysbhaFm1)\n\nLink naar webpage/script die wordt gebruik in de kennisclips:\n\n- [script Hoofdstuk 8](https://statomics.github.io/sbc/rmd/08-NonparametericStatistics.html)\n\n## Inleiding\n\n<iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/x0qBWoUpT00\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n\nAlle methoden die in de vorige hoofdstukken behandeld werden, zijn zogenaamde parametrische methoden. Deze term duidt erop dat de geldigheid van de inferentie enkel correct is als er voldaan is aan parametrische veronderstellingen.\n Dit zijn voornamelijk de distributionele veronderstellingen, zoals dat de observaties normaal verdeeld zijn.  Andere\n voorbeelden van een parametrische veronderstelling zijn de gelijkheid van varianties bij de two-sample $t$-test en ANOVA en de lineariteit van een regressiemodel.\n\n Wanneer we over statistische besluitvorming spreken, is bijvoorbeeld de $p$-waarde van een statistische test, of de probabilistische interpretatie van een betrouwbaarheidsinterval enkel correct interpreteerbaar onder bepaalde veronderstellingen:\n\n-  De $p$-waarde is de kans dat de teststatistiek $T$ onder de nulhypothese meer extreem is dan de waargenomen waarde $t$ (gegeven dat $H_0$ waar is). Die kans wordt berekend op basis van de nuldistributie van $T$. Deze distributie wordt bij parametrische testen afgeleid door te steunen op veronderstellingen over de verdeling van de observaties. Indien er niet voldaan is aan deze veronderstellingen, is de berekende $p$-waarde fout. Dit betekent dat de conclusies die op $p$ gebaseerd worden, eveneens mogelijks fout kunnen zijn.\n\n-  De berekening van bv. een $95\\%$ betrouwbaarheidsinterval steunt eveneens op distributionele veronderstellingen. Als er niet voldaan is aan de veronderstellingen, is er geen garantie meer dat de berekende intervallen de (correcte) interpretatie hebben dat dergelijke intervallen de juiste parameterwaarde omvatten met $95\\%$ kans.\n\n Asymptotische theorie is misschien moeilijker te plaatsen onder parametrisch of niet-parametrisch. Je zou kunnen stellen dat bv. een $t$-test asymptotisch niet-parametrisch is, omdat bij erg grote steekproefgroottes de distributionele veronderstelling van normaliteit niet meer belangrijk is.\n\nDe reden waarom we in deze cursus een focus hebben op parametrische methoden is omdat ze efficiënter en meer flexibel zijn wanneer er aan de voorwaarden voldaan is. Efficiëntie betekent dat bij een constante steekproefgrootte de testen een grotere power hebben en dat de betrouwbaarheidsintervallen smaller zijn.  Met meer flexibel bedoelen we dat het eenvoudiger is om de methoden in te zetten voor experimenten met meer complexe designs.\nAls er niet voldaan is aan de veronderstellingen van de parameterische methoden kunnen we voor bepaalde designs overschakelen naar niet-parametrische methoden die in deze situatie nog steeds formeel geldig zijn.\n\n## Vergelijken van twee groepen\n\n<iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/2gkuOjD_Trc\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n\n### Cholestorol voorbeeld\nIn een studie werd de cholesterolconcentratie in het bloed gemeten bij 5 patiënten (groep=1) die twee dagen geleden een hartaanval hadden en bij 5 gezonde personen (groep=2).\nDe onderzoekers wensen na te gaan of de cholesterolconcentratie verschillend is bij hartpatiënten en gezonde personen.\nBoxplots en qqplots van de data worden weergegeven in Figuur -@fig-cholBox en -@fig-cholQQ.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nchol <- read_tsv(\"https://raw.githubusercontent.com/statOmics/sbc/master/data/chol.txt\")\n\nchol <- chol |>\n  mutate(group = as.factor(group))\n\nnGroups <- chol |>\n  pull(group) |>\n  table()\n\nn <- nGroups |>\n  sum()\nchol\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 x 2\n   group cholest\n   <fct>   <dbl>\n 1 1         244\n 2 1         206\n 3 1         242\n 4 1         278\n 5 1         236\n 6 2         188\n 7 2         212\n 8 2         186\n 9 2         198\n10 2         160\n```\n\n\n:::\n\n```{.r .cell-code}\nchol |>  \n  ggplot(aes(x=group,y=cholest)) +\n  geom_boxplot(outlier.shape=NA) +\n  geom_point(position=\"jitter\")\n```\n\n::: {.cell-output-display}\n![Boxplot van de cholesterol concentratie in het bloed bij hartpatiënten (groep 1) en gezonde individuen (groep 2).](08-NietParametrischeStatistiek_files/figure-pdf/fig-cholBox-1.pdf){#fig-cholBox fig-align='center' fig-pos='H' width=100%}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nchol |> ggplot(aes(sample=cholest)) +\n  geom_qq() +\n  geom_qq_line() +\n  facet_wrap(~group)\n```\n\n::: {.cell-output-display}\n![Qqplot van de cholesterol concentratie in het bloed bij hartpatiënten (groep 1) en gezonde individuen (groep 2).](08-NietParametrischeStatistiek_files/figure-pdf/fig-cholQQ-1.pdf){#fig-cholQQ fig-align='center' fig-pos='H' width=100%}\n:::\n:::\n\n\nDe boxplots en qqplots geven aan dat er mogelijks outliers in de data voorkomen.\nHet is moeilijk om inzicht te krijgen in de verdeling van de data gezien we maar 5 observaties hebben per groep.\n\n### Permutatietesten\n\nDe vraagstelling van het cholesterol voorbeeld is geformuleerd in erg ruime bewoordingen en dit laat vrijheid in de vertaling ervan naar een nulhypothese.\n\nLaten we starten met een nulhypothese in termen van gemiddelden. Stel dat $\\mu_1$ en $\\mu_2$ de gemiddelde uitkomsten in behandelingsgroep 1 (hartpatiënten) en 2 (gezonde personen) voorstellen, dan zouden de hypotheses kunnen zijn:\n\n$$H_0: \\mu_1=\\mu_2 \\text{ versus } H_1: \\mu_1\\neq \\mu_2.$$\n\nVoor het testen van deze hypotheses kunnen we bijvoorbeeld gebruik maken van de two-sample $t$-test.\n\nWe gaan de voorwaarden na:\n\n- Normaliteit van de uitkomsten in de twee behandelingsgroepen. Met slechts 5 observaties in iedere groep, kan de veronderstelling niet nagegaan worden.\n- Gelijkheid van varianties. Met slechts 5 observaties in iedere groep, kan de veronderstelling niet nagegaan worden.\n\n\nWe kunnen dus de veronderstellingen van de two-sample $t$-test niet nagaan.\nWe kunnen ook geen beroep doen op de asymptotische benadering omdat 5 observaties per groep te weinig is.\n\nSamengevat: de veronderstellingen van de $t$-test kunnen niet worden nagegaan en er zijn te weinig observaties om gebruik te kunnen maken van de asymptotische benadering. Aangezien het erg gevaarlijk is een statistische methode te gebruiken waarvan de voorwaarden niet nagegaan kunnen worden, is de klassieke $t$-test niet de geschikte methode. De oplossing die in dit hoofdstuk besproken wordt, zijn permutatietesten.\nOm deze te kunnen beschrijven, zullen we eerst de nulhypothese anders formuleren.\n\n\n#### Hypothesen\n\nDe oplossing die in deze sectie besproken wordt, zijn de permutatietesten.\nOm deze te kunnen beschrijven, zullen we eerst de nulhypothese anders formuleren.\n\nDe veronderstelling voor de two-sample $t$-test kunnen we als volgt schrijven, met $Y_{1j}$ en $Y_{2j}$ de notatie voor de uitkomsten uit respectievelijk groep 1 en 2:\n\n$$Y_{1j} \\text{ iid } N(\\mu_1,\\sigma^2) \\;\\;\\;\\text{ en }\\;\\;\\; Y_{2j} \\text{ iid } N(\\mu_2,\\sigma^2).$$\n\nOnder $H_0:\\mu_1=\\mu_2$, wordt dit (stel $\\mu=\\mu_1=\\mu_2$ onder $H_0$)\n\n$$ Y_{ij} \\text{ iid } N(\\mu,\\sigma^2),$$\n\nwat uitdrukt dat alle $n=n_1+n_2$ uitkomsten uit dezelfde normale distributie komen en onafhankelijk verdeeld zijn. Dit laat ons dus toe om de oorspronkelijke nulhypothese van de two-sample $t$-test anders te schrijven:\n\n$$\nH_0: F_1(y) = F_2(y) \\text{ voor alle } y \\;\\;\\;\\text{ of }\\;\\;\\; H_0: f_1(y) = f_2(y) \\text{ voor alle } y\n$$ {#eq-H0F1F2}\n\nmet $F_1$ en $F_2$ de distributiefuncties en $f_1$ en $f_2$ de densiteitfuncties van de verdeling van de uitkomsten in respectievelijk behandelingsgroep 1 en 2, en met de bijkomende veronderstelling dat $f_1$ en $f_2$ de distributiefuncties van Normale verdelingen zijn.\n\nOnder de alternatieve hypothese wordt een locatie-shift verondersteld:\n\n$$H_1: f_1(y)=f_2(y-\\Delta) \\;\\;\\;\\text{ voor alle } y$$\n\nmet $\\Delta=\\mu_1-\\mu_2$, verder hebben de Normale verdelingen dezelfde variantie.\n\nWe illustreren dit in R voor $f_1\\sim N(0,1)$ en $f_2\\sim N(1,1)$ en $\\Delta=-1$.\n\n::: {.cell}\n\n```{.r .cell-code}\nmu1 <- 0\nsigma1 <- 1\nmu2 <- 1\nsigma2 <- 1\ny <- -2:2\ndelta <- mu1 - mu2\ndelta\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -1\n```\n\n\n:::\n\n```{.r .cell-code}\ndnorm(y, mu1, sigma1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.05399097 0.24197072 0.39894228 0.24197072 0.05399097\n```\n\n\n:::\n\n```{.r .cell-code}\ndnorm(y - delta, mu2, sigma2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.05399097 0.24197072 0.39894228 0.24197072 0.05399097\n```\n\n\n:::\n:::\n\n\nDe permutatietesten die in de volgende sectie ontwikkeld worden, kunnen gebruikt worden voor het testen van de hypothese -@eq-H0F1F2, maar dan zonder de Normaliteitsveronderstelling.\n\nWe schrijven hypothese -@eq-H0F1F2 verkort als\n\n$$H_0: F_1=F_2 \\;\\;\\;\\text{ of }\\;\\;\\; H_0:f_1=f_2.$$\n\nAls de nulhypothese waar is, met name dat de verdelingen van de cholesterolconcentraties gelijk zijn voor hartpatiënten en gezonde personen, dan zijn de groep-labels van de 10 personen niet informatief.\nGezien er geen verschil is in de verdeling tussen beide groepen is elke groepering immers irrelevant.\nWe kunnen bijgevolg de verdeling van de test-statistiek onder de nulhypothese bekomen door de groepslabels $G$ te permuteren.\n\n#### Verdeling van de statistiek onder $H_0$\n\nIn praktijk zijn er $m=\\binom{n_1+n_2}{n_1}=\\binom{n}{n_1}=\\binom{n}{n_2}$ mogelijke unieke permutaties $\\cal{G}$ van de groepslabels.\nVoor ons voorbeeld zijn dat er $m=$ 252.\nAls $m$ niet te groot is dan kunnen alle unieke permutaties van de groepslabels berekend worden.\nVoor iedere unique permutatie $g \\in \\cal{G}$ wordt de teststatistiek $t^*_g$ berekend^[in ons geval de t-test statistiek door de originele reponses te gebruiken die nu gekoppeld worden aan de gepermuteerde groepslabels $G_g^*$].\n\nWe kunnen alle m=252 permutaties in R genereren a.d.h.v. de functie `combn(n,n_1)`.\nDit wordt geïllustreerd in de onderstaande R code:\n\n::: {.cell}\n\n```{.r .cell-code}\nG <- combn(n,nGroups[1])\ndim(G)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]   5 252\n```\n\n\n:::\n\n```{.r .cell-code}\nG[,1:10]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]\n[1,]    1    1    1    1    1    1    1    1    1     1\n[2,]    2    2    2    2    2    2    2    2    2     2\n[3,]    3    3    3    3    3    3    3    3    3     3\n[4,]    4    4    4    4    4    4    5    5    5     5\n[5,]    5    6    7    8    9   10    6    7    8     9\n```\n\n\n:::\n:::\n\n\nDe matrix G bevat voor elke permutatie de volgnummers van de observaties die tot de eerste groep zullen behoren.\nWe tonen enkel de eerste 10 permutaties.\nWe kunnen nu de teststatistiek berekenen voor de originele steekproef en voor elke permutatie\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Originele test statistiek\ntOrig=t.test(cholest~group,chol)$statistic\n#bereken alle permutatiecombinaties en voer voor\n#elke combinantie een functie uit die de t-test statistiek\n#berekent voor de gepermuteerde groepslabels\ntOrig <- t.test(cholest ~ group, chol)$statistic\ntOrig\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       t \n3.664425 \n```\n\n\n:::\n\n```{.r .cell-code}\ntStar <- combn(\n  n,\n  nGroups[1],\n\tfunction(g,y) {\n    t.test(y[g],y[-g])$statistic\n    },\n  y = chol |> pull(cholest)\n  )\nhead(tStar)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.6644253 1.6397911 2.3973923 1.5876250 1.9217173 0.9967105\n```\n\n\n:::\n\n```{.r .cell-code}\nlength(tStar)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 252\n```\n\n\n:::\n:::\n\n\nMerk op dat `y[g]` de data selecteert met volgnummers g  uit de vector y en  `y[-g]` de data waarvoor de volgnummers niet tot g behoren.\nDe vector `tStar` bevat de  waarden van de teststatistiek $t^*_g$ voor alle $g \\in {\\cal{G}}$.\n\nWe kunnen nu de verdeling van de teststatistiek onder $H_0$ bestuderen.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nqplot(tStar,bins=50) +\n  xlab(expression(\"permutatiestatistiek t\"^\"*\")) +\n  geom_vline(xintercept=tOrig,col=2)\n```\n\n::: {.cell-output-display}\n![Exacte permutatie nuldistributie van de Welch t-test voor het cholesterol voorbeeld. Bovenaan histogram van elke mogelijke waarde voor de test-statistiek. Onderaan een gewoon histogram met balkbreedtes gelijk aan 1. De geobserveerde waarde voor de test-statistiek is aangeduid met een rode verticale lijn.](08-NietParametrischeStatistiek_files/figure-pdf/fig-tPermDist-1.pdf){#fig-tPermDist fig-align='center' fig-pos='H' width=100%}\n:::\n:::\n\n\nHet histogram (Figuur -@fig-tPermDist) bevat alle informatie voor de permutatienuldistributie van de two-sample $t$-teststatistiek voor de geobserveerde uitkomsten; merk op dat er 252 unieke waarden van de teststatistiek berekend zijn. \t\nHet histogram in Figuur -@fig-tPermDist is de verdeling van de teststatistiek onder de nulhypothese.\nWe zien eveneens dat de geobserveerde teststatistiek vrij extreem is.\n\n#### p-waarde\nNu we in staat zijn de permutatienuldistributie te berekenen, kunnen we hypothesetesten uitvoeren net als in de parametrische statistiek.\n Voor een permutatietest is de $p$-waarde voor de tweezijdige test (immers $H_1: \\mu_1 \\neq \\mu_2$)\n\n$$p=\\text{P}_0\\left[\\vert T\\vert \\geq \\vert t\\vert \\mid \\mathbf{y}\\right].$$\n\nMerk op dat deze p-waarde geconditioneerd is op de geobserveerde cholesterolwaarden die weergegeven worden in de vector $\\mathbf{y}=(y_{11},\\ldots,y_{51},y_{12},\\ldots,y_{52})^T$.\n\n Aangezien de permutatienuldistrubutie van $T$ bepaald wordt door $t^*_g$, $g \\in{\\cal{G}}$, berekenen we\n\n$$p  = \\text{P}_0\\left[\\left\\vert T\\right\\vert \\geq \\left\\vert t\\right\\vert \\mid \\mathbf{y}\\right] = \\frac{\\#\\{g\\in {\\cal{G}}: \\vert t^*_g\\vert \\geq \\vert t \\vert \\}}{m},$$\n\nm.a.w. als de ratio van het aantal permutaties waarvoor de statistiek minstens even extreem is als de geobserveerde statistiek op het totaal aantal permutaties. In R kunnen we dit als volgt berekenen.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npval <- mean(abs(tStar)>=abs(tOrig))\npval\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.01587302\n```\n\n\n:::\n:::\n\n\nWe vinden dus een $p$-waarde van 0.0159. Aangezien $p<5\\%$, besluiten we op het $5\\%$ significantieniveau dat de distributies van de cholesterol concentraties niet gelijk zijn bij hartpatiënten en bij gezonde personen.\n De $p$-waarde die gevonden wordt via de permutatienuldistributie op basis van alle permutaties wordt een **exacte** $p$-waarde genoemd. De permutatienuldistributie wordt een **exacte** nuldistributie genoemd. De term **exact** betekent dat de resultaten correct zijn voor iedere steekproefgrootte $n$.\n\nDe kans op een type I fout wordt dus gecontroleerd door een permutatietest, maar wel conditioneel op de geobserveerde uitkomsten data $\\mathbf{y}$.\n\nWe hebben steeds geconditioneerd op de observaties van de steekproef. **We kunnen ons nu afvragen of we de conclusies kunnen veralgemenen naar de populatie toe? Het antwoord is ja, als de subjecten at random getrokken zijn uit de populatie.**  Het bewijs hiervan valt buiten het bestek van de cursus.\n\nSoms treedt er een praktisch probleem op omdat het aantal permutaties $m=\\#{\\cal{G}}$ erg groot is. Enkele voorbeelden:\n$\\binom{20}{10}=$ 184756, $\\binom{30}{15}=$ 1.55e+08 en $\\binom{40}{20}=$ 1.38e+11.\n\nDus zelfs met slechts 40 observaties en een gebalanceerde proefopzet is het quasi onmogelijk om alle permutaties één voor één door te rekenen.\nDe oplossing bestaat erin om niet alle $g \\in {\\cal{G}}$ te beschouwen, maar slechts een beperkt aantal (bv. 10000 of 100000).\nWe kunnen m.a.w. de nuldistributie benaderen door een groot aantal random permutaties uit te voeren.\n\n\n#### Hoe kunnen we conclusie interpreteren  \n\nWe permuteren immers t statistiek. De effectgrootte in de t-test is de locatie-shift.\n\nAls locatie-shift model niet opgaat is een significant resultaat moeilijk te interpreteren. Het is dan immers niet duidelijk tegenover welk alternatief we dan testen.\n\nLocatie-shift kan niet worden nagegaan in kleine steekproeven...\n\n<!---break-->\n\n### Rank Testen\n\n<iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/6l3-IEfNSN8\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n\nDe ontwikkeling van rank testen startte in de eerste helft van de twintigste eeuw, maar ze vormen vandaag nog steeds de belangrijkste groep van niet-parametrische testen. Aanvankelijk hadden ze hun populariteit te danken aan het feit dat ze niet-parametrisch zijn en dat ze exacte $p$-waarden geven op basis van de permutatienuldistributie. In tegenstelling tot de test besproken in de vorige sectie, hebben rank testen geen nood aan het numeriek opstellen van de permutatienuldistributie voor iedere nieuwe dataset. De permutatienuldistributie van rank testen hangt alleen af van de steekproefgroottes. Bovendien zal blijken dat de testen erg robuust zijn tegen uitschieters (Engels: *outliers*) en dat ze nuttig zijn als het locatie-shift model niet opgaat.\n\nRank testen starten vanuit rank-getransformeerde uitkomsten.\n\n::: {#def-rank}\n## Rank\n\n&nbsp;\n:::\nBeschouw $Y_1, \\ldots, Y_n$. We veronderstellen voorlopig dat\n  er geen twee gelijke observaties voorkomen (i.e. geen *ties*).\n  De rank van observatie $Y_i$ wordt dan\n  gedefinieerd als\n\n\\begin{equation*}\n  R_i=R(Y_i) = \\#\\{Y_j: Y_j\\leq Y_i; j=1,\\ldots, n\\}.\n\\end{equation*}\n\n  De kleinste observatie krijgt dus rank 1, de tweede kleinste rank 2, enzovoort, en de grootste observatie,\n  tenslotte, krijgt rank $n$.\n\n**Einde Definitie**\n\n\n\n De rank transformatie wordt geïllustreerd op basis van het cholesterol voorbeeld.\n\n::: {.cell}\n\n```{.r .cell-code}\nchol |>\n  pull(cholest)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] 244 206 242 278 236 188 212 186 198 160\n```\n\n\n:::\n\n```{.r .cell-code}\nchol |>\n  pull(cholest) |>\n  rank()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1]  9  5  8 10  7  3  6  2  4  1\n```\n\n\n:::\n:::\n\n\nSoms komen *ties* voor in de data, i.e. minstens twee observaties hebben dezelfde numerieke waarde. Een klein voorbeeld:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmetTies <- c(403, 507, 507, 610, 651, 651, 651, 830, 900)\nmetTies |> rank()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.0 2.5 2.5 4.0 6.0 6.0 6.0 8.0 9.0\n```\n\n\n:::\n:::\n\nDe numerieke waarde 507 komt tweemaal voor en de numerieke waarde 651 komt driemaal voor. Dit zijn voorbeelden van *ties*.\nWanneer *ties* voorkomen, wordt dikwijls de definitie van *midranks* toegepast voor de rank-transformatie.\n\n::: {#def-midrank}\n## Midrank\n\n&nbsp;\n:::\nBeschouw $Y_1, \\ldots, Y_n$.\n  De **midrank** van observatie $Y_i$ wordt dan\n  gedefinieerd als\n\n\\begin{eqnarray*}\n  R_i &=& \\frac{ \\#\\{Y_j: Y_j\\leq Y_i\\} + ( \\#\\{Y_j: Y_j < Y_i\\} +1)}{2}.\n\\end{eqnarray*}\n\n**Einde Definitie**\n\n\nIn wat volgt hebben we dikwijls de ranks van de uitkomsten nodig in de gepoolde steekproef. Bijvoorbeeld: beschouw de uitkomsten $Y_{ij}$, $i=1,\\ldots, n_j$ en $j=1,2$.\nDeze uitkomsten kunnen ook gerepresenteerd worden door $Z_1,\\ldots, Z_n$ ($n=n_1+n_2$), de uitkomsten uit de gepoolde steekproef.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt(chol)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        [,1]  [,2]  [,3]  [,4]  [,5]  [,6]  [,7]  [,8]  [,9]  [,10]\ngroup   \"1\"   \"1\"   \"1\"   \"1\"   \"1\"   \"2\"   \"2\"   \"2\"   \"2\"   \"2\"  \ncholest \"244\" \"206\" \"242\" \"278\" \"236\" \"188\" \"212\" \"186\" \"198\" \"160\"\n```\n\n\n:::\n\n```{.r .cell-code}\nz <- chol |>\n  pull(cholest)\nz\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] 244 206 242 278 236 188 212 186 198 160\n```\n\n\n:::\n\n```{.r .cell-code}\nrank(z)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1]  9  5  8 10  7  3  6  2  4  1\n```\n\n\n:::\n:::\n\n\n<!---break-->\n\n### Wilcoxon-Mann-Whitney Test\n\n<iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/qInfzU97YLI\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n\nDe test werd gelijktijdig ontwikkeld door Wilcoxon en door Mann en Whitney. Om deze reden wordt de test dikwijls de **Wilcoxon-Mann-Whitney** (WMW) test genoemd. Soms wordt de test ook de **Wilcoxon rank sum test** of de **Mann-Whitney U test** genoemd.\n\nDe test werd ontwikkeld voor het testen van de nulhypothese -@eq-H0F1F2 tegenover het alternatief $H_1: \\mu_1\\neq \\mu_2$ (of de eenzijdige versies). Eerst wordt er een distributionele veronderstelling gemaakt: het **locatie-shift** model, later relaxeren we deze aanname.\n\n Stel dat $Y_1$ en $Y_2$ uitkomsten zijn uit respectievelijk de eerste en tweede behandelingsgroep, met respectievelijke verdelingen $f_1$ en $f_2$. Het locatie-shift model geldt als er een $\\Delta$ bestaat waarvoor geldt\n\n $$f_1(y)=f_2(y-\\Delta) \\;\\;\\;\\text{ voor alle } y.$$\n\nLocatie-shift betekent dat $f_1$ en $f_2$ dezelfde vorm hebben, maar ze mogen over $\\Delta$ verschoven zijn.\nDe $\\Delta$ uit de definitie heeft als interpretatie: $\\Delta = \\mu_1-\\mu_2$.\nDoor locatie-shift aan te nemen, zal het verwerpen van $H_0: f_1=f_2$ de conclusie $\\mu_1\\neq \\mu_2$ impliceren.\n\nDe klassieke two-sample $t$-teststatistiek is gebouwd rond het verschil in steekproefgemiddelden $\\bar{Y}_1-\\bar{Y}_2$. We beschouwen nu ook het verschil in steekproefgemiddelden, maar niet op basis van de oorspronkelijke uitkomsten, maar op basis van de rank-getransformeerde uitkomsten. De ranks zijn toegekend op basis van de gepoolde observaties (i.e. na samenvoegen van de uitkomsten uit groep 1 en groep 2); dus $R_{ij}=R(Y_{ij})$ is de rank van uitkomst $Y_{ij}$ in de gepoolde steekproef.\nBeschouw de teststatistiek\n\n$$T = \\frac{1}{n_1}\\sum_{i=1}^{n_1} R(Y_{i1}) - \\frac{1}{n_2}\\sum_{i=1}^{n_2} R(Y_{i2}) .$$\n\nDe statistiek vergelijkt dus de gemiddelde rank in groep 1 met de gemiddelde rank in groep 2.\n\nDit is een zinvolle teststatistiek, want\n\n- als $H_0$ waar is, dan verwachten we dat de gemiddelde rank in de eerste groep ongeveer gelijk is aan de gemiddelde rank in de tweede groep en dus verwachten we dat $T$ dicht bij nul ligt.\n\n- als $H_1$ waar is dan verwachten we dat de gemiddelde ranks zullen verschillen en dus dat $T$ niet dicht bij nul zal liggen.\n\nEr kan echter worden aangetoond dat het volstaat het om\n\n$$S_1=\\sum_{i=1}^{n_1} R(Y_{i1})$$\n\nals teststatistiek te beschouwen. $S_1$ is de som van de ranks van de observaties uit de eerste behandelingsgroep; dit verklaart de naam *rank sum test*.\n\n$S_1$ en $S_2$ bevatten immers dezelfde informatie en zijn gerelateerd via\n\n$$S_1+S_2 = \\text{som van alle ranks} = 1+2+\\cdots + n=\\frac{1}{2}n(n+1).$$\n\nNu we weten dat $S_1$ (en $S_2$) een goede teststatistiek is, kan de permutatietestmethode toegepast worden om de exacte permutatienuldistributie op te stellen en de test uit te voeren.\nVoor een gegeven steekproefgrootte $n$, en veronderstellend dat er geen *ties* zijn, nemen de rank-getransformeerde uitkomsten altijd de waarden $1, 2, \\ldots, n$ aan. Voor gegeven groepsgroottes $n_1$ en $n_2$, zal de permutatienuldistributie dan ook steeds dezelfde zijn! In de vorige eeuw (tot ongeveer de jaren 1980) werd dit als een groot voordeel beschouwd omdat de nuldistributies voor gegeven $n_1$ en $n_2$ getabuleerd konden worden (belangrijke kwantielen werden als tabellen in boeken gepubliceerd zodat ze konden gebruikt worden voor het bepalen van kritische waarden en $p$-waarden), waardoor de gebruiker geen nood had aan zware rekencapaciteit. Vandaag de dag speelt dit argument niet meer mee, maar toch blijven de rank testen erg populair, maar dan wel om andere, heel belangrijke redenen.\n\n\n\nNiettegenstaande $S_1$ en $S_2$ perfect als teststatistieken gebruikt kunnen worden, wordt dikwijls gewerkt met de gestandaardiseerde teststatistiek\n\n$$T = \\frac{S_1-\\text{E}_{0}\\left[S_1\\right]}{\\sqrt{\\text{Var}_{0}\\left[S_1\\right]}},$$\n\nmet $\\text{E}_{0}\\left[S_1\\right]$ en $\\text{Var}_{0}\\left[S_1\\right]$ de verwachtingswaarde en variantie van $S_1$ onder $H_0$. Dit zijn dus het gemiddelde en variantie van de permutatienuldistributie van $S_1$.\n\n Onder $H_0$ geldt\n\n $$\\text{E}_{0}\\left[S_1\\right]= \\frac{1}{2}n_1(n+1) \\;\\;\\;\\;\\text{ en }\\;\\;\\;\\; \\text{Var}_{0}\\left[S_1\\right]=\\frac{1}{12}n_1n_2(n+1).$$\n\nVerder kan men onder $H_0$  en als $\\min(n_1,n_2)\\rightarrow \\infty$ opgaat aantonen dat,\n\n $$T = \\frac{S_1-\\text{E}_{0}\\left[S_1\\right]}{\\sqrt{\\text{Var}_{0}\\left[S_1\\right]}} \\rightarrow N(0,1).$$\n\nAsymptotisch volgt de gestandaardiseerde teststatistiek dus een standaardnormaal verdeling.\n\n\nWe illustreren de WMW test aan de hand van de R functie `wilcox.test`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwilcox.test(cholest ~ group, data = chol)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon rank sum exact test\n\ndata:  cholest by group\nW = 24, p-value = 0.01587\nalternative hypothesis: true location shift is not equal to 0\n```\n\n\n:::\n:::\n\n\nWe zien dat we op basis van de test de nulhypothese kunnen verwerpen op het 5% significantie-niveau.\n\nDe output geeft de teststatistiek $W=$ 24.\nIn volgende lijnen berekenen we  $S_1$ en $S_2$ manueel voor de dataset.\n\n::: {.cell}\n\n```{.r .cell-code}\nS1 <- chol |>\n  mutate(cholRank=rank(cholest)) |>\n  filter(group==1) |>\n  pull(cholRank) |>\n  sum()\n\nS2 <- chol |>\n  mutate(cholRank = rank(cholest)) |>\n  filter(group == 2) |>\n  pull(cholRank) |>\n  sum()\n\nS1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 39\n```\n\n\n:::\n\n```{.r .cell-code}\nS2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 16\n```\n\n\n:::\n:::\n\n\nWaar komt $W=$ 24 vandaan? Dit wordt zodadelijk toegelicht.\n\nDe teststatistieken $S_1$ en $S_2$ werden voorgesteld door Wilcoxon, maar tezelfdertijd werd een equivalente test voorgesteld door Mann en Whitney. Hun teststatistiek wordt gegeven door^[in de afwezigheid van *ties*]\n\n$$U_1 = \\sum_{i=1}^{n_1}\\sum_{k=1}^{n_2} \\text{I}\\left\\{Y_{i1}\\geq Y_{k2}\\right\\}.$$\n\nwaarbij $\\text{I}\\left\\{.\\right\\}$ een indicator is die 1 is als de uitdrukking waar is en 0 als dit niet het geval is.\nEr wordt voor elke observatie uit de eerste groep geteld hoeveel keer zij groter of gelijk is aan een observatie uit de tweede groep.\nWe berekenen de Mann-Whitney statistiek nu manueel in R.\n\n::: {.cell}\n\n```{.r .cell-code}\ny1 <- chol |>\n  filter(group==1) |>\n  pull(\"cholest\")\n\ny2 <- chol |>\n  filter(group==2) |>\n  pull(\"cholest\")\n\nu1Hlp <- sapply(\n  y1,\n  function(y1i,y2) {y1i>=y2},\n  y2=y2)\n\ncolnames(u1Hlp) <- y1\nrownames(u1Hlp) <- y2\n\nu1Hlp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     244   206  242  278  236\n188 TRUE  TRUE TRUE TRUE TRUE\n212 TRUE FALSE TRUE TRUE TRUE\n186 TRUE  TRUE TRUE TRUE TRUE\n198 TRUE  TRUE TRUE TRUE TRUE\n160 TRUE  TRUE TRUE TRUE TRUE\n```\n\n\n:::\n\n```{.r .cell-code}\nU1 <- sum(u1Hlp)\nU1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 24\n```\n\n\n:::\n:::\n\n\nEr kan worden aangetoond dat\n\n$$U_1 = S_1 - \\frac{1}{2}n_1(n_1+1).$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nS1-nGroups[1]*(nGroups[1]+1)/2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n 1 \n24 \n```\n\n\n:::\n:::\n\n\nHieruit concluderen we (1) dat $U_1$ en $S_1$ dezelfde informatie bevatten, (2) dat $U_1$ ook een rankstatistiek is en dat exacte testen gebaseerd op $U_1$ en $S_1$ equivalent zijn.\n\nDe statistiek $U_1$ heeft als voordeel dat het een informatieve interpretatie heeft.\nStel $Y_j$ een willekeurige uitkomst uit behandelingsgroep $j$ ($j=1,2$). Dan geldt\n\n\\begin{eqnarray*}\n  \\frac{1}{n_1n_2}\\text{E}\\left[U_1\\right]\n     &=& \\text{P}\\left[Y_1 \\geq Y_2\\right].\n\\end{eqnarray*}\n\nIntuïtief voelen we dit aan: Op basis van de steekproef kunnen we die kans schatten door het gemiddelde te berekenen van alle indicator waarden $\\text{I}\\left\\{Y_{i1}\\geq Y_{k2}\\right\\}$.\nWe voerden inderdaad $n_1 \\times n_2$ vergelijkingen uit.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(u1Hlp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.96\n```\n\n\n:::\n\n```{.r .cell-code}\nU1/(nGroups[1]*nGroups[2])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   1 \n0.96 \n```\n\n\n:::\n:::\n\n\nDe kans $\\text{P}\\left[Y_1 \\geq Y_2\\right]$ wordt een **probabilistische index** (Engels: *probabilistic index*) genoemd.\nHet is de kans dat een uitkomst uit de eerste groep groter of gelijk is dan een uitkomst uit de tweede groep.\nAls $H_0$ waar is, dan is $\\text{P}\\left[Y_1 \\geq Y_2\\right]=\\frac{1}{2}$.\n\nDe gestandaardiseerde Mann-Whitney statistiek is\n\n$$T = \\frac{U_1 - \\frac{n_1n_2}{2}}{\\sqrt{\\frac{1}{12}n_1n_2(n+1)}}.$$\n\nDe R functie `wilcox.test` geeft niet de Wilcoxon rank sum statistiek, maar wel de Mann-Whitney statistiek $U_1$.\nWe weten echter dat exacte permutatietesten gebaseerd op $U_1$, $U_2$, $S_1$ of $S_2$ dezelfde resultaten geven.\nWe bekijken nogmaals de output\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwTest <- wilcox.test(cholest~group, data = chol)\nwTest\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon rank sum exact test\n\ndata:  cholest by group\nW = 24, p-value = 0.01587\nalternative hypothesis: true location shift is not equal to 0\n```\n\n\n:::\n\n```{.r .cell-code}\nU1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 24\n```\n\n\n:::\n\n```{.r .cell-code}\nprobInd <- wTest$statistic/prod(nGroups)\nprobInd\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   W \n0.96 \n```\n\n\n:::\n:::\n\n\nAangezien $p=$ 0.0159 $<0.05$ besluiten we op het $5\\%$ significantieniveau dat de gemiddelde cholesterolconcentratie groter is bij hartpatiënten kort na een hartaanval dan bij gezonde personen.  We nemen aan dat locatie-shift opgaat.\n\nNu we weten hoe $U_1$ berekend wordt, weten we ook meteen dat een cholesterolwaarde van hartpatiënten met een kans van\n$U1/(n_1\\times n_2)=$ 96%\n groter is die van gezonde personen. Aangezien we het locatie-shift model veronderstellen, besluiten we ook dat de gemiddelde uitkomst uit de behandelingsgroep groter is dan de gemiddelde uitkomst uit de placebogroep.\n\nWe zouden de veronderstelling van de locatie-shift moeten nagaan, maar met slechts 5 observaties in elke behandelingsgroep is dit zinloos. Zonder verder theorie hierover te geven, geven we nog mee dat zonder de locatie-shift veronderstelling de conclusie in termen van de probabilistische index correct blijft en de conclusie ook zo zou moeten worden geformuleerd.\n\nDus wanneer we geen locatie-shift veronderstellen en een tweezijdige test uitvoeren testen we eigenlijk\n\n$$H_0: F_1=F_2 \\text{ vs P}(Y_1 \\geq Y_2) \\neq 0.5.$$\n\n### Conclusie Cholestorol Voorbeeld\nEr is een significant verschil in de distributie van de cholesterolconcentraties bij hartpatiënten 2 dagen na hun hartaanval en gezonde individuen ($p=$ 0.0159). Het is meer waarschijnlijk om hogere cholesterolconcentraties te observeren bij hartpatiënten dan bij gezonde individuen. De puntschatting voor deze kans bedraagt 96%.\n\n\n## Vergelijken van $g$ Behandelingen\n\n<iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/tio4b5GUTIk\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n\nIn deze sectie veralgemenen we de methoden uit de vorige sectie.\nDe methoden kunnen ook gezien worden\n als niet-parametrische tegenhangers van de $F$-test uit een one-way ANOVA.\n\n### DMH Voorbeeld\n\nNieuwe (en bestaande) chemische substanties moeten getest worden op genotoxiciteit. De resultaten van genotoxiciteitstesten vormen de basis voor risico-analyses en de classificatie en labeling van chemische substanties in de EU (*Dangerous Substances Directive 67/548/EEC and Regulation (EC) No. 1272/2008*). In dat kader werd een studie met 24 ratten opgezet voor het testen van de genotoxiciteit van 1,2-dimethylhydrazine dihydrochloride (DMH).\nDe ratten werden at random verdeeld over vier groepen die een verschillende dagelijkse DMH dosis kregen toegediend (controle, laag, medium, hoog).\nNa drie weken werden de dieren afgemaakt en werd genotoxiciteit van DMH in de lever bepaald a.d.h.v. een comet assay waarbij DNA strengbreuken worden gevisualiseerd via gel electroforese.\nDe lengte van de comet staart is een proxy voor het aantal strengbreuken.\nDe onderzoekers wensen na te gaan of er verschillen zijn in de DNA schade tengevolge van de DMH dosis.\nBoxplots van de data worden weergegeven in Figuur -@fig-dnaBox.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndna <- read_delim(\"https://raw.githubusercontent.com/statOmics/sbc/master/data/dna.txt\",delim=\" \")\n\ndna <- dna |>\n  mutate(dose = as.factor(dna$dose))\ndna\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 24 x 3\n   id    length dose \n   <chr>  <dbl> <fct>\n 1 Rat1    19.3 0    \n 2 Rat2    18.9 0    \n 3 Rat3    18.6 0    \n 4 Rat4    19.0 0    \n 5 Rat5    17.1 0    \n 6 Rat6    18.8 0    \n 7 Rat7    55.4 1.25 \n 8 Rat8    59.2 1.25 \n 9 Rat9    59.1 1.25 \n10 Rat10   52.1 1.25 \n# i 14 more rows\n```\n\n\n:::\n\n```{.r .cell-code}\ndna |>\n  ggplot(aes(x=dose,y=length,fill=dose))+\n  geom_boxplot() +\n  geom_point(position=\"jitter\")\n```\n\n::: {.cell-output-display}\n![Boxplot van de comet staart lengte in functie van de DMH dosis.](08-NietParametrischeStatistiek_files/figure-pdf/fig-dnaBox-1.pdf){#fig-dnaBox fig-align='center' fig-pos='H' width=100%}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndna |>\n  ggplot(aes(sample=length)) +\n  geom_qq() +\n  geom_qq_line() +\n  facet_wrap(~dose)\n```\n\n::: {.cell-output-display}\n![QQ-plots van de comet staart lengte per DMH dosis.](08-NietParametrischeStatistiek_files/figure-pdf/fig-dnaQQ-1.pdf){#fig-dnaQQ fig-align='center' fig-pos='H' width=100%}\n:::\n:::\n\n\nDe boxplots lijken een indicatie te geven dat de controle groep een andere variabiliteit heeft.\nMerk wel op dat er slechts 6 observaties zijn per groep wat eigenlijk te weinig is om de aannames na te gaan.\n\n<!---break-->\n\n### Kruskal-Wallis Rank Test\n\n<iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/9tZfMB37KFQ\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n\nDe Kruskal-Wallis Rank Test (KW-test) is een niet-parametrisch alternatief voor de ANOVA F-test.\n\n  De klassieke $F$-teststatistiek kan geschreven worden als\n\n  $$F = \\frac{\\text{SST}/(g-1)}{\\text{SSE}/(n-g)} = \\frac{\\text{SST}/(g-1)}{(\\text{SSTot}-\\text{SST})/(n-g)} ,$$\n  \n  met $g$ het aantal groepen.\n\nMerk op dat SSTot enkel afhangt van de uitkomsten $\\mathbf{y}$ en niet zal variëren bij permutaties. Het is dus eigenlijk voldoende om SST als teststatistiek te gebruiken. Ter herinnering: $\\text{SST}=\\sum_{j=1}^g n_j(\\bar{Y}_j-\\bar{Y})^2$.\n\n  De KW teststatistiek maakt gebruik van SST maar dan gebaseerd op de rank-getransformeerde uitkomsten^[we veronderstellen afwezigheid van *ties*],\n\n  $$\\text{SST} = \\sum_{j=1}^g n_j \\left(\\bar{R}_j - \\bar{R}\\right)^2 = \\sum_{j=1}^g n_j \\left(\\bar{R}_j - \\frac{n+1}{2}\\right)^2 ,$$\n\n  met $\\bar{R}_j$ het gemiddelde van de ranks in behandelingsgroep $j$, en $\\bar{R}$ het gemiddelde van alle ranks,\n\n  $$\\bar{R} = \\frac{1}{n}(1+2+\\cdots + n) = \\frac{1}{n}\\frac{1}{2}n(n+1) = \\frac{n+1}{2}.$$\n\n  De KW teststatistiek wordt gegeven door\n\n  $$KW = \\frac{12}{n(n+1)}  \\sum_{j=1}^g n_j \\left(\\bar{R}_j - \\frac{n+1}{2}\\right)^2.$$\n\n  De factor $\\frac{12}{n(n+1)}$ zorgt ervoor dat $KW$ een eenvoudige asymptotische nuldistributie heeft. In het bijzonder, onder $H_0$, als $\\min(n_1,\\ldots, n_g)\\rightarrow \\infty$,\n\n  $$KW  \\rightarrow \\chi^2_{g-1}.$$\n\n  De exacte KW-test kan uitgevoerd worden via de berekening van de permutatienuldistributie (die enkel afhangt van $n_1, \\ldots, n_g$) voor het testen van\n\n  $$H_0: f_1=\\ldots=f_g \\text{ vs } H_1: \\text{ minstens twee gemiddelden verschillend}.$$\n\nOm toe te laten dat $H_1$ geformuleerd is in termen van gemiddelden, moet locatie-shift verondersteld worden. Indien locatie-shift niet opgaat, zou $H_1$ eigenlijk geformuleerd moeten worden in termen van probabilistische indexen:\n\n  $$H_0: f_1=\\ldots=f_g \\text{ vs } H_1: \\exists\\ j,k \\in \\{1,\\ldots,g\\} : \\text{P}\\left[Y_j\\geq Y_k\\right]\\neq 0.5$$\n\n#### DNA Schade Voorbeeld\nEerst analyseren we de data met de R functie `kruskal.test`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkruskal.test(length ~ dose, data = dna)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKruskal-Wallis rank sum test\n\ndata:  length by dose\nKruskal-Wallis chi-squared = 14, df = 3, p-value = 0.002905\n```\n\n\n:::\n:::\n\n\nDe waarde van de KW teststatistiek is 14, met een $p$-waarde van 0.00291. Dus op het $5\\%$ significantieniveau kan de nulhypothese worden verworpen.\n\n  Het is belangrijk om op te merken dat de R-functie `kruskal.test` steeds de asymptotische benadering gebruikt voor de berekening van de $p$-waarden. Met slechts 6 observaties per groep, is dit geen optimale benadering van de exacte $p$-waarde!\n  Met de `coin` R package kunnen we de exacte $p$-waarde wel berekenen via het argument `distribution='exact'`of benaderen a.d.h.v. simulaties `distribution=approximate(B=100000)`, waarbij B het aantal permutaties is.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(coin)\nkwPerm <- kruskal_test(length ~ dose, data = dna,\n\t\t    distribution = approximate(nresample = 100000))\nkwPerm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tApproximative Kruskal-Wallis Test\n\ndata:  length by dose (0, 1.25, 2.5, 5)\nchi-squared = 14, p-value = 0.00033\n```\n\n\n:::\n:::\n\n\nWe kunnen besluiten dat er een extreem significant verschil is in distributie van de DNA schade ten gevolge van de dosis.\n\n<!---break-->\n\n#### Posthoc Analyse\n\n<iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/9kcSwfVo82s\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n\nWe vragen ons nu uiteraard af welke groepen verschillend zijn. Hiervoor dienen we een posthoc analyse uit te voeren met paarsgewijze niet-parametrische testen.\n\nWe kunnen dit bijvoorbeeld doen a.d.h.v Wilcoxon-Mann-Whitney testen.\n\n  - Dat is eigenlijk suboptimaal na KW-test want de data worden opnieuw gerangschikt!\n  - KW gebaseerd over ranks bepaalde over alle groepen\n  - WMW gebaseerd op ranks van twee groepen in vergelijking\n\nBetere alternatieven bestaan maar vallen buiten bestek van de cursus.\n\nWe voeren nu verdere posthoc testen uit voor alle paarsgewijse verschillen a.d.h.v WMW testen.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npairWilcox <- pairwise.wilcox.test(dna$length, dna$dose)\npairWilcox\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPairwise comparisons using Wilcoxon rank sum exact test \n\ndata:  dna$length and dna$dose \n\n     0     1.25  2.5  \n1.25 0.013 -     -    \n2.5  0.013 0.818 -    \n5    0.013 0.721 0.788\n\nP value adjustment method: holm \n```\n\n\n:::\n:::\n\n\nDe output geeft paarsgewijze p-waarden weer voor elke vergelijking. De output wordt in een matrix geordend.\nDe p-waarde voor elk element van de matrix behoort tot de paarsgewijze vergelijking van de groep in de kolom en de groep in de rij.\nStandaard wordt de Holm multiple testing methode gebruikt. Dat is een variant van Bonferroni die minder conservatief is.\n\nWe zien dat alle DMH behandelingen significant verschillen van de controle.\nMaar er is geen significant verschil in de distributie van de DNA schade tussen de verschillende dosisgroepen waarbij DMH werd toegediend.\nOm een puntschatter op de kans op hogere DNA-schade te berekenen voor de vergelijkingen tussen de behandelingen met DMH en de controle zouden we ook de statistieken U1 nodig hebben.\nDit kunnen we niet bekomen uit de `pairwise.wilcox.test` output.\nHiervoor zullen we de individuele wilcoxon testen aan moeten roepen.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnGroep <- table(dna$dose)\n\nprobInd <- combn(\n  levels(dna$dose),\n  2,\n  function(x) {\n\t\t test <- wilcox.test(\n       length~dose,\n       dna |> filter(dose%in%x)\n       )\n\t\t return(test$statistic/prod(nGroep[x]))\n\t})\n\nnames(probInd) <- combn(\n  dna |> pull(dose) |> levels(),\n  2,\n  paste,\n  collapse=\"vs\")\n\nprobInd\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  0vs1.25    0vs2.5      0vs5 1.25vs2.5   1.25vs5    2.5vs5 \n0.0000000 0.0000000 0.0000000 0.4444444 0.2777778 0.3333333 \n```\n\n\n:::\n:::\n\n\nOmdat er twijfels zijn of het locatie-shift model geldig is, doen we enkel uitspraken in termen van de probabilistische index.\n\nWe besluiten dat er extreem significant verschil is in de distributie van de DNA-schade metingen tengevolge van de DMH behandeling ($p<0.001$ KW-test).\nDNA-schade is meer waarschijnlijk na behandeling met DMH dan in de controle behandeling (alle p=0.013, WMW-testen).\nDe kansen op hogere DNA-schade na blootstelling aan DMH bedraagt 100%^[Het berekenen van een BI op deze kansen valt buiten het bestek van de cursus].\nEr zijn geen significante verschillen in de distributies van de comet-lengtes tussen de DMH behandelingen onderling ($p=$ 0.72-0.82). DMH vertoont dus al bij de lage dosis genotoxische effecten. (Alle paarsgewijze testen werden gecorrigeerd voor multiple testing d.m.v. Holm's methode).\n",
    "supporting": [
      "08-NietParametrischeStatistiek_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}