{
  "hash": "b00e538cb047070a13b55fa6a1a9d306",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"6. Enkelvoudige lineaire regressie\"\nauthor: \"Lieven Clement\"\ndate: \"statOmics, Ghent University (https://statomics.github.io)\"\nformat:\n  html:\n    toc: true\n    number-sections: true\n    theme: cosmo\n    highlight-style: tango\n    code-tools: true\n    embed-resources: true\n---\n\n\n\n\n# Breast cancer dataset\n\n\n- subset van studie <https://doi.org/10.1093/jnci/djj052>\n- 32 borstkanker patiënten met een estrogen recepter positieve tumor die tamoxifen chemotherapy behandeling ondergaan. Variabelen:\n\n    - grade: histologische graad van tumor (graad 1 vs 3),\n    - node: status van de lymfe knopen (0: niet aangetast, 1: aantasting en verwijdering van de lymfe knopen),\n    - size: grootte van tumor in cm,\n    - ESR1 en S100A8 gen expressie in tumor biopsy (via microarray technologie)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbrca <- read_csv(\"https://raw.githubusercontent.com/statOmics/sbc/master/data/breastcancer.csv\")\nbrca\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 32 × 10\n   sample_name filename     treatment    er grade  node  size   age  ESR1 S100A8\n   <chr>       <chr>        <chr>     <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>  <dbl>\n 1 OXFT_209    gsm65344.ce… tamoxifen     1     3     1   2.5    66 1939.  207. \n 2 OXFT_1769   gsm65345.ce… tamoxifen     1     1     1   3.5    86 2752.   37.0\n 3 OXFT_2093   gsm65347.ce… tamoxifen     1     1     1   2.2    74  379. 2364. \n 4 OXFT_1770   gsm65348.ce… tamoxifen     1     1     1   1.7    69 2532.   23.6\n 5 OXFT_1342   gsm65350.ce… tamoxifen     1     3     0   2.5    62  141. 3219. \n 6 OXFT_2338   gsm65352.ce… tamoxifen     1     3     1   1.4    63 1495.  108. \n 7 OXFT_2341   gsm65353.ce… tamoxifen     1     1     1   3.3    76 3406.   14.0\n 8 OXFT_1902   gsm65354.ce… tamoxifen     1     3     0   2.4    61 2813.   68.4\n 9 OXFT_1982   gsm65355.ce… tamoxifen     1     1     0   1.7    62  950.   74.2\n10 OXFT_5210   gsm65356.ce… tamoxifen     1     3     0   3.5    65 1053.  182. \n# ℹ 22 more rows\n```\n\n\n:::\n:::\n\n\n- Om didactische redenen verwijderen we eerst 3 outliers in de S100A8 expressie data.\n- In deze studie kan dit echter niet worden verantwoord\n- Later in de lessen laten we zien hoe je goed met alle data omgaat.\n\n\n\n::: {.cell layout-align=\"center\" warnings='false'}\n\n```{.r .cell-code}\nbrca |>\n  ggplot(aes(x=\"\", y=S100A8)) +\n  geom_boxplot() +\n  xlab(\"\") +\n  ylab(\"S100A8 expressie\")\n```\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-2-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n***\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(GGally)\nbrcaSubset <- brca |>\n  filter(S100A8<2000)\nbrcaSubset[,-(1:4)] |> ggpairs()\n```\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n## Associatie tussen ESR1 en S100A8 expressie\n\n- ESR1 in $\\pm$ 75% van borstkankertumoren.\n\n    - Expressie van ER-gen positief voor behandeling: tumor reageert op hormoontherapie\n    - Tamoxifen interageert met ER en moduleert genexpressie.\n\n- Eiwitten van de S100-familie zijn vaak gedisreguleerd bij kanker\n\n- S100A8 expressie onderdrukt immuunsysteem in tumor en creëert inflamatoir milieu die kankergroei promoot.\n\n- Interesse in associatie tussen ESR1 en S100A8 expressie.\n\n1. pipe dataset naar ggplot\n2. selecteer data `ggplot(aes(x=ESR1,y=S100A8))`\n3. voeg punten toe met `geom_point()`\n4. voeg een \"smooth line\" toe `geom_smooth()`\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbrcaSubset |>\n  ggplot(aes(x=ESR1,y=S100A8)) +\n  geom_point() +\n  geom_smooth()\n```\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-4-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n# Lineaire Regressie\n\n- Statistische methode om relatie tussen 2 reeksen observaties $(X_i, Y_i)$, bekomen voor onafhankelijke subjecten $i = 1, ..., n$, te beschrijven.\n\n- Gen expressie voorbeeld\n\n    - Response Y : S100A8 expressie\n    - Predictor X: ESR1 expressie\n\n1. pipe dataset naar ggplot\n2. selecteer data `ggplot(aes(x=ESR1,y=S100A8))`\n3. voeg punten toe met `geom_point()`\n4. voeg een \"smooth line\" toe `geom_smooth()`\n5. voeg een rechte toe `geom_smooth()` met `method = \"lm\"` (linear model). (We zetten `se = FALSE` om geen puntgewijze betrouwbaarheidsintervallen weer te geven)\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbrcaSubset |>\n  ggplot(aes(x = ESR1,y = S100A8)) +\n  geom_point() +\n  geom_smooth(se = FALSE, col = \"grey\") +\n  geom_smooth(method = \"lm\", se = FALSE)\n```\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-5-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n## Model\n\n- Voor vaste $X$, heeft $Y$ niet noodzakelijke dezelfde waarde\n\n$$\\text{observation = signal + noise}$$\n\n$$Y_i=g(X_i)+\\epsilon_i$$\n\n- We definiëren $g(x)$ als het verwachte resultaat voor subjects met $X_i=x$\n\n$$E[Y_i|X_i=x]=g(x)$$\n\nDaarom is $\\epsilon_i$ gemiddeld 0 voor subjects met dezelfde $X_i$:\n$$E[\\epsilon_i|X_i]=0$$\n\n## Lineaire regressie\n\n- Om **accurate** en **interpreteerbare** resultaten te bekomen, kiest men $g(x)$ vaak als een lineaire functie met ongekende parameters.\n\n$$E(Y|X=x)=\\beta_0 + \\beta_1 x$$\n\nonbekend  **intercept** $\\beta_0$ en\n**helling** $\\beta_1$.\n\n- Lineair model legt een *assumptie* op de verdeling van $X$ en $Y$, die incorrect kan zijn.\n\n- *Efficiënte data-analyse*: benut alle observaties om iets te leren over verwachte uitkomst bij $X=x$.\n\n\n## Gebruik\n\n- *Predictie*: wanneer $Y$ ongekend is, maar $X$ wel, kunnen we $Y$ voorspellen op basis van $X$\n\\[E(Y|X=x)=\\beta_0 + \\beta_1 x\\]\n\n- *Associatie*: biologische relatie tussen variabele $X$ en continue meting $Y$ beschrijven.\n- *Intercept:* $E(Y|X=0)=\\beta_0$\n\n- *Slope*:\n\\begin{eqnarray*}\nE(Y|X=x+\\delta)-E(Y|X=x)&=&\\beta_0 + \\beta_1 (x+\\delta) -\\beta_0-\\beta_1 x\\\\\n&=& \\beta_1\\delta\n\\end{eqnarray*}\n\n$\\beta_1:$ verschil in gemiddelde uitkomst voor subjecten die verschillen in één eenheid van de predictor $X$.\n\n# Parameterschatting\n\n- - Kleinste kwadraten techniek\n(Least squares)\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbrcaSubset |>\n  ggplot(aes(x = ESR1, y = S100A8)) +\n  geom_point() +\n  geom_smooth(se = FALSE, col = \"grey\") +\n  geom_smooth(method = \"lm\", se = FALSE)\n```\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-6-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n- Parameters $\\beta_0$ en $\\beta_1$ zijn ongekend\n\n- Parameters schatten op basis van beperkte steekproef\n\n- Best passende lijn\n\n    - Punt op regressielijn voor een gegeven $x_i$: $(x_i, \\beta_0 + \\beta_1 x_i)$  zo dicht mogelijk bij $(x_i, y_i)$\n    - Kies $\\beta_0$ en $\\beta_1$ zodat de som tussen voorspelde en waargenomen punten zo klein mogelijk wordt.\n\n$$SSE=\\sum_{i=1}^n (y_i-\\beta_0-\\beta_1 x_i)^2=\\sum_{i=1}^n e_i^2$$\n\n- Met $e_i$ de residuen: de verticale afstanden van de observaties tot de gefitte regressierechte\n\n## Schatters die SSE minimaliseren\n\n$$\\hat{\\beta_1}= \\frac{\\sum\\limits_{i=1}^n (y_i-\\bar y)(x_i-\\bar x)}{\\sum\\limits_{i=1}^n (x_i-\\bar x)^2}=\\frac{\\mbox{cor}(x,y)s_y}{s_x} $$\n\n$$\\hat{\\beta_0}=\\bar y - \\hat{\\beta}_1 \\bar x $$\n\n- Merk op dat de helling van de kleinste kwadratenlijn evenredig is met de correlatie tussen de uitkomst en de verklarende variabele.\n\nGeschatte lineaire regressiemodel laat toe om:\n\n- verwachte uitkomst te voorspellen voor subjecten met een gegeven waarde $x$ voor de predictor:\n$$\\text{E} [ Y | X = x]=\\hat{\\beta}_0+\\hat{\\beta}_1x$$\n\n- na te gaan hoeveel uitkomst gemiddeld verschilt tussen 2 groepen subjecten met een verschil van $\\delta$ eenheden in de verklarende variabele:\n\n$$\\text{E}\\left[Y|X=x+\\delta\\right]-\\text{E}\\left[Y|X=x\\right]= \\hat{\\beta}_1\\delta$$\n\n### Borstkanker voorbeeld\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm1 <- lm(S100A8 ~ ESR1, brcaSubset)\nsummary(lm1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = S100A8 ~ ESR1, data = brcaSubset)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-95.43 -34.81  -6.79  34.23 145.21 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 208.47145   28.57207   7.296 7.56e-08 ***\nESR1         -0.05926    0.01212  -4.891 4.08e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 59.91 on 27 degrees of freedom\nMultiple R-squared:  0.4698,\tAdjusted R-squared:  0.4502 \nF-statistic: 23.93 on 1 and 27 DF,  p-value: 4.078e-05\n```\n\n\n:::\n:::\n\n\n\\[E(Y|X=x)=208.47-0.059 x\\]\n\n- De verwachte S100A8-expressie is gemiddeld  59 eenheden lager voor patiënten met een ESR1-expressieniveau die 1000 eenheden hoger ligt.\n\n- Verwachte S100A8 expressieniveau voor patiënten met een ESR1 expressieniveau van 2000:  \n\\[208.47-0.059\\times 2000=89.94\\]\n\n- Verwachte S100A8 expressieniveau voor patiënten met een ESR1 expressieniveau van 4000:  \n\\[208.47-0.059\\times 4000=-28.58\\]\n- **Let op voor extrapolatie!** (Veronderstelling van lineariteit kan men enkel nagaan binnen het bereik van de data).\n\n# Statistische besluitvorming (statistische inferentie)\n\nOm besluiten te kunnen trekken over lineaire regressiemodel\n\\[E(Y|X)=\\beta_0+\\beta_1 X\\]\n\nmoeten we weten:\n\n- Hoe de least squares parameter schatters variëren van steekproef tot steekproef, en\n- En hoe is dit onder de nulhypothese dat er geen associatie is tussen predictor en response\n\n- Noodzaak aan statistisch model!\n\n- Modelleer de verdeling van $Y$ gegeven $X$ expliciet: $f_{Y|X}(y)$\n\n## Modelleer verdeling van Y?\n\n1. Naast *lineariteit* hebben we nog aannames nodig!\n2. *Onafhankelijkheid*: waarnemingen $(X_1,Y_1), ...,  (X_n,Y_n)$ zijn gemaakt voor n onafhankelijke subjecten (Is vereist om de variantie te schatten)\n3. *Homoscedasticiteit * of *gelijke varianties*: waarnemingen variëren met gelijk gemiddelde rond de regressielijn.\n    - Residuen $\\epsilon_i$ hebben gelijke variantie voor elke $X_i=x$\n    - $\\text{var}(Y\\vert X=x) = \\sigma^2$ voor elke $X=x$\n    - $\\sigma$ wordt de *residuele standaarddeviatie* genoemd.\n4. *Normaliteit*: de residuen $\\epsilon_i$ zijn normaal verdeeld\n\n![](https://raw.githubusercontent.com/statomics/sbc/master/figures/RegModel3.png){width=100%}\n\n\n- Uit 2, 3 en 4 volgt dat\n$$\\epsilon_i \\text{ i.i.d.} N(0,\\sigma^2).$$\n- Als we ook steunen op eerste veronderstelling van lineariteit:\n$$Y_i\\vert X_i\\sim N(\\beta_0+\\beta_1 X_i,\\sigma^2),$$\n\n- Verder kan men aantonen dat onder deze aannames\n$$\\sigma^2_{\\hat{\\beta}_0}=\\frac{\\sum\\limits_{i=1}^n X^2_i}{\\sum\\limits_{i=1}^n (X_i-\\bar X)^2} \\times\\frac{\\sigma^2}{n} \\text{ en } \\sigma^2_{\\hat{\\beta}_1}=\\frac{\\sigma^2}{\\sum\\limits_{i=1}^n (X_i-\\bar X)^2}$$\n- en dat de parameterschatters eveneens normaal verdeeld zijn\n$$\\hat\\beta_0 \\sim N\\left(\\beta_0,\\sigma^2_{\\hat \\beta_0}\\right) \\text{ en } \\hat\\beta_1 \\sim N\\left(\\beta_1,\\sigma^2_{\\hat \\beta_1}\\right)$$\n\n## Hoge spreiding op $X$ verbetert de precisie\n\n$$\\sigma^2_{\\hat{\\beta}_1}=\\frac{\\sigma^2}{\\sum\\limits_{i=1}^n (X_i-\\bar X)^2}$$\n\n![](https://raw.githubusercontent.com/statomics/sbc/master/figures/spread.png){ width=100% }\n\n- Conditionele variantie ($\\sigma^2$) is niet gekend\n- Schatten d.m.v. gemiddelde van die kwadratische afwijkingen rond de regressierechte\n- *mean squared error* (MSE)\n\n$$\\hat\\sigma^2=MSE=\\frac{\\sum\\limits_{i=1}^n \\left(y_i-\\hat\\beta_0-\\hat\\beta_1\\times x_i\\right)^2}{n-2}=\\frac{\\sum\\limits_{i=1}^n e^2_i}{n-2}.$$\n- Voor het bekomen van deze schatter steunen we op onafhankelijkheid (aanname 2) en homoscedasticiteit (aanname 3).\n- deel door $n-2$\n\nNa schatting van $\\sigma^2$ bekomen we volgende standaard errors:\n\n$$\\text{SE}_{\\hat{\\beta}_0}=\\hat\\sigma_{\\hat{\\beta}_0}=\\sqrt{\\frac{\\sum\\limits_{i=1}^n X^2_i}{\\sum\\limits_{i=1}^n (X_i-\\bar X)^2} \\times\\frac{\\text{MSE}}{n}} \\text{ en } \\text{SE}_{\\hat{\\beta}_1}=\\hat\\sigma_{\\hat{\\beta}_1}=\\sqrt{\\frac{\\text{MSE}}{\\sum\\limits_{i=1}^n (X_i-\\bar X)^2}}$$\n\n- Opnieuw toetsen en betrouwbaarheidsintervallen o.b.v.\n$$T=\\frac{\\hat{\\beta}_k-\\beta_k}{SE(\\hat{\\beta}_k)} \\text{ with } k=1,2.$$\n\n- Als aan alle aannames is voldaan volgt $T$ een t-verdeling met n-2 vrijheidsgraden.\n\n- Als geen normaliteit maar wel onafhankelijk, lineariteit en homoscedasticiteit en grote dataset\n\\[\\rightarrow \\text{Centrale Limietstelling}\\]\n\n\n### Borstkanker voorbeeld\n\n- Negatieve associatie tussen S100A8 en ESR1 gen expressie.\n\n- Veralgemeen effect in steekproef naar populatie met behulp van het betrouwbaarheidsinterval op de helling:\n$$[\\hat\\beta_1 - t_{n-2,\\alpha/2} \\text{SE}_{\\hat\\beta_1},\\hat\\beta_1 + t_{n-2,\\alpha/2} \\text{SE}_{\\hat\\beta_1}]$$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconfint(lm1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   2.5 %       97.5 %\n(Intercept) 149.84639096 267.09649989\nESR1         -0.08412397  -0.03440378\n```\n\n\n:::\n:::\n\n\n- Negatief verband is significant op het 5% significantieniveau.\n\n\n## Hypothese test\n\n- Vertaal de onderzoeksvraag \"Is er een associatie tussen de S100A8- en ESR1-genexpressie?\" naar de parameters in het model.\n- Onder nulhypothese geen associatie tussen expressie van beide genen:\n$$H_0: \\beta_1=0$$\n\n- Onder alternatieve hypothese is er een associatie tussen beide genen:\n$$H_1: \\beta_1\\neq0$$\n\n- Test statistiek\n$$T=\\frac{\\hat{\\beta}_1-0}{SE(\\hat{\\beta}_k)}$$\n\n- Onder $H_0$ volgt de statistiek een t-verdeling met n-2 vrijheidsgraden.\n\n### Brca dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lm1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = S100A8 ~ ESR1, data = brcaSubset)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-95.43 -34.81  -6.79  34.23 145.21 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 208.47145   28.57207   7.296 7.56e-08 ***\nESR1         -0.05926    0.01212  -4.891 4.08e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 59.91 on 27 degrees of freedom\nMultiple R-squared:  0.4698,\tAdjusted R-squared:  0.4502 \nF-statistic: 23.93 on 1 and 27 DF,  p-value: 4.078e-05\n```\n\n\n:::\n:::\n\n\n\n- Associatie tussen de S100A8 en ESR1 genexpressie extreem significant is (p<<0.001).\n- Maar eerst moeten we alle assumpties controleren!\n- Anders kunnen de conclusies o.b.v. de statistische test en het BI onjuist zijn.  \n\n# Nagaan van modelveronderstellingen\n\n- Onafhankelijkheid: design\n- Lineariteit: besluitvorming geen zin als model niet lineair is\n- Homoscedasticiteit: besluitvorming/p-waarde is niet betrouwbaar als de data niet homoscedastisch zijn\n- Normaliteit: besluitvorming/p-waarde is niet betrouwbaar als de data niet normaal verdeeld zijn in kleine steekproeven\n\n\n## Lineariteit\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbrcaSubset |>\n  ggplot(aes(x = ESR1, y = S100A8)) +\n  geom_point() +\n  geom_smooth(se = FALSE, col = \"grey\") +\n  geom_smooth(method = \"lm\", se = FALSE)\n```\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-10-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n\n## Residuplots\n\n- Afwijkingen van lineariteit echter makkelijker opgespoord d.m.v. een *residuplot*. (Zeker als er later meer variabelen zijn in het lineaire model)\n\n- verklarende variabele of predicties $\\hat\\beta_0+\\hat\\beta_1 x$ op de $X$-as\n\n- de *residuen* op de $Y$-as\n$$e_i=y_i-\\hat{g}(x_i)=y_i-\\hat\\beta_0-\\hat\\beta_1\\times x_i,$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(lm1)\n```\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-11-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-11-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-11-4.png){width=672}\n:::\n:::\n\n\n## Homoscedasticiteit (gelijkheid van variantie)\n\n- Residuen en kwadratische residu’s dragen informatie over residuele variabiliteit.\n\n- Associatie met de verklarende variabelen $\\rightarrow$ indicatie van heteroscedasticiteit.\n\n- Scatterplot van of $e_i$ versus $x_i$ of predicties $\\hat \\beta_0+ \\hat \\beta_1 x_i$.\n\n- Scatterplot van gestandaardiseerd residu versus $x_i$ of predicties.\n\n\n## Normaliteit\n\n- Indien voldoende gegevens, schatters normaal verdeeld zelfs wanneer observaties niet Normaal verdeeld zijn: centrale limiet stelling\n\n- Wat ‘voldoende observaties’ zijn, hangt af van hoe goed de verdeling op de Normale lijkt.\n\n- Aanname is dat uitkomsten Normaal verdeeld zijn bij vaste waarden van de verklarende variabelen.\n$$Y_i\\vert X_i\\sim N(\\beta_0+\\beta_1X_i,\\sigma^2)$$\n\n- QQ-plot van response Y is heel misleidend.\n\n- QQ-plot van de residuen $e_i$\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(lm1, which=2)\n```\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n\n# Afwijkingen van Modelveronderstellingen\n\n- Transformatie van onafhankelijke veranderlijke wijzigt de verdeling van Y bij gegeven X niet:\n\n    - helpt niet om normaliteit of homoscedasticiteit te bekomen\n    - helpt wel om lineariteit te bekomen wanneer er normaliteit en homoscedasticiteit is\n    - Vaak ook hogere orde termen: $X^2$, $X^3$, ...\n    $$Y_i=\\beta_0+\\beta_1X_i+\\beta_2X_i^2+ ... + \\epsilon_i$$\n\n\n- Transformatie van response Y kan helpen om normaliteit en homoscedasticiteit te bekomen.\n\n    -  $\\sqrt(Y)$, $\\log(Y)$, 1/Y, ...\n\n\n## Borstkanker voorbeeld\n\nProblemen met\n\n-  heteroscedasticiteit\n- mogelijkse afwijking van normaliteit (scheefheid naar rechts)\n- negatieve concentratievoorspellingen die theoretisch niet mogelijk zijn\n- niet-lineairiteit\n\n- treedt veelal op bij concentratie en intensiteitsmetingen\n- Deze zijn vaak log-normaal verdeeld (normale verdeling na log-transformatie)\n- In Figuur 6.3 eveneens een soort exponentiële trend\n- In de genexpressie literatuur wordt veelal gebruik gemaak van $\\log_2$ transformatie\n- gen-expressie op log-schaal proportionele verschillen op de originele schaal\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbrca |>\n  ggplot(aes(x = ESR1, y = S100A8)) +\n  geom_point() +\n  geom_smooth()\n```\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbrca |>\n  ggplot(aes(\n    x = ESR1 |> log2(),\n    y = S100A8 |> log2())\n    ) +\n  geom_point() +\n  geom_smooth()\n```\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm2<-lm(S100A8 |> log2() ~ ESR1 |> log2(), brca)\nplot(lm2)\n```\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-16-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-16-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-16-4.png){width=672}\n:::\n\n```{.r .cell-code}\nsummary(lm2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = log2(S100A8) ~ log2(ESR1), data = brca)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.94279 -0.66537  0.08124  0.68468  1.92714 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   23.401      1.603   14.60 3.57e-15 ***\nlog2(ESR1)    -1.615      0.150  -10.76 8.07e-12 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.026 on 30 degrees of freedom\nMultiple R-squared:  0.7942,\tAdjusted R-squared:  0.7874 \nF-statistic: 115.8 on 1 and 30 DF,  p-value: 8.07e-12\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconfint(lm2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                2.5 %    97.5 %\n(Intercept) 20.128645 26.674023\nlog2(ESR1)  -1.921047 -1.308185\n```\n\n\n:::\n:::\n\n\n\n### Interpretatie 1\n\nEen patiënt met een ESR1 expressie die 1 eenheid op de $\\log_2$ schaal hoger ligt dan dat van een andere patiënt heeft gemiddeld gezien een expressie-niveau van het S100A8 gen  dat 1.61 eenheden lager ligt (95\\% BI [-1.92,-1.31]).\n\n**Crossectionele studie: enkel uitspraken over verschillen tussen patiënten!**\n\n$$\\log_2 \\hat\\mu_1=23.401  -1.615 \\times \\text{logESR}_1,\\text{ } \\log_2 \\hat\\mu_2=23.401  -1.615 \\times \\text{logESR}_2 $$\n$$\\log_2 \\hat\\mu_2-\\log_2 \\hat\\mu_1=  -1.615 (\\log_2 \\text{ESR}_2-\\log_2 \\text{ESR}_1) = -1.615 \\times 1 = -1.615$$\n\n### Interpretatie 2\n\nModel op log-schaal: bij terugtransformatie verkrijgen we het geometrische gemiddelde\n\n\\begin{eqnarray*}\n\\sum\\limits_{i=1}^n \\frac{\\log x_i}{n}&=&\\frac{\\log x_1 + \\ldots + \\log x_n}{n}\\\\\\\\\n&\\stackrel{(1)}{=}&\\frac{\\log(x_1 \\times \\ldots \\times x_n)}{n}=\\frac{\\log\\left(\\prod\\limits_{i=1}^n x_i\\right)}{n}\\\\\\\\\n&\\stackrel{(2)}{=}&\\log \\left(\\sqrt[\\leftroot{-1}\\uproot{2}\\scriptstyle n]{\\prod\\limits_{i=1}^n x_i}\\right)\n\\end{eqnarray*}\n\n- Populatiegemiddelden $\\mu$ dus geschat a.d.h.v. geometrisch gemiddelden.\n- Logaritmische transformatie is een monotoon: we kunnen betrouwbaarheidsintervallen berekend op log-schaal terugtransformeren!\n\n\n::: {.cell}\n\n```{.r .cell-code}\n2^lm2$coef[2]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlog2(ESR1) \n 0.3265519 \n```\n\n\n:::\n\n```{.r .cell-code}\n2^-lm2$coef[2]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlog2(ESR1) \n    3.0623 \n```\n\n\n:::\n\n```{.r .cell-code}\n2^-confint(lm2)[2,]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   2.5 %   97.5 % \n3.786977 2.476298 \n```\n\n\n:::\n:::\n\n\nEen patiënt met een ESR1 expressie die 2 keer zo hoog is als die van een andere patiënt, zal gemiddeld een S100A8-expressie hebben die 3.06 keer lager is (95\\% BI [2.48,3.79]).\n\n\n$$\\log_2 \\hat\\mu_1=23.401  -1.615 \\times \\text{logESR}_1,\\text{ } \\log_2 \\hat\\mu_2=23.401  -1.615 \\times \\text{logESR}_2 $$\n$$\\log_2 \\hat\\mu_2-\\log_2 \\hat\\mu_1=  -1.615 (\\log_2 \\text{ESR}_2-\\log_2 \\text{ESR}_1) $$\n$$\\log_2 \\left[\\frac{\\hat\\mu_2}{\\hat\\mu_1}\\right]=  -1.615 \\log_2\\left[\\frac{ \\text{ESR}_2}{\\text{ESR}_1}\\right] $$\n$$\\frac{\\hat\\mu_2}{\\hat\\mu_1}=\\left[\\frac{ \\text{ESR}_2}{\\text{ESR}_1}\\right]^{-1.615}=2^ {-1.615} =0.326$$\nor\n$$\\frac{\\hat\\mu_1}{\\hat\\mu_2}=2^{1.615} =3.06$$\n\n\n### Interpratie 3\n\nEen patiënt met een ESR1 expressie die 1\\% hoger is dan die van een andere patiënt zal gemiddeld een expressieniveau voor het S100A8 gen  hebben dat ongeveer -1.61% lager is (95\\% BI [-1.92,-1.31])%.\n\n$$\\log_2 \\hat\\mu_1=23.401  -1.615 \\times \\text{logESR}_1,\\text{ } \\log_2 \\hat\\mu_2=23.401  -1.615 \\times \\text{logESR}_2 $$\n$$\\log_2 \\hat\\mu_2-\\hat\\log_2 \\mu_1=  -1.615 (\\log_2 \\text{ESR}_2-\\log_2 \\text{ESR}_1) $$\n$$\\log_2 \\left[\\frac{\\hat\\mu_2}{\\hat\\mu_1}\\right]=  -1.615 \\log_2\\left[\\frac{ \\text{ESR}_2}{\\text{ESR}_1}\\right] $$\n$$\\frac{\\hat\\mu_2}{\\hat\\mu_1}=\\left[\\frac{ \\text{ESR}_2}{\\text{ESR}_1}\\right]^{-1.615}=1.01^ {-1.615} =0.984 \\approx -1.6\\%$$\n\nDit geldt voor lage tot matige waarden van $\\beta_1$:\n$$-10<\\beta_1<10 \\rightarrow 1.01^{\\beta_1} -1 \\approx \\frac{\\beta_1}{100}.$$\n\n# Besluitvorming over gemiddelde uitkomst\n\n- Regressie model kan ook worden gebruikt voor predictie\n\n- Besluitvorming te doen over de gemiddelde uitkomst bij een gegeven waarde $x$, m.a.w.\n$$\\hat{g}(x)= \\hat{\\beta}_0 + \\hat{\\beta}_1 x$$\n- $\\hat{g}(x)$ een schatter van het conditionele gemiddelde $E[Y\\vert X=x]$\n\n- Parameterschatters Normale verdeeld en onvertekend $\\rightarrow$ schatter $\\hat{g}(x)$ ook Normaal verdeeld en onvertekend.\n\n$$\\text{SE}_{\\hat{g}(x)}=\\sqrt{MSE\\left\\{\\frac{1}{n}+\\frac{(x-\\bar X)^2}{\\sum\\limits_{i=1}^n (X_i-\\bar X)^2}\\right\\}}.$$\n\n$$T=\\frac{\\hat{g}(x)-g(x)}{SE_{\\hat{g}(x)}}\\sim t_{n-2}$$\n\n- Gemiddelde uitkomst en betrouwbaarheidsintervallen op de gemiddelde uitkomst in R via de `predict(.)` functie.\n- `newdata` argument: predictorwaarden (x-waarden) voor het berekenen van gemiddelde uitkomsten\n- `interval=\"confidence\"` argument om betrouwbaarheidsintervallen te bekomen.\n- Zonder `newdata` argument wordt de gemiddelde uitkomsten berekend voor alle predictorwaarden van de dataset.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrid <- 140:4000\ng <- predict(\n  lm2,\n  newdata = data.frame(ESR1 = grid),\n  interval = \"confidence\")\nhead(g)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       fit      lwr      upr\n1 11.89028 10.76082 13.01974\n2 11.87370 10.74721 13.00019\n3 11.85724 10.73370 12.98078\n4 11.84089 10.72028 12.96151\n5 11.82466 10.70696 12.94237\n6 11.80854 10.69372 12.92336\n```\n\n\n:::\n:::\n\n\nMerk op dat we de nieuwe data die we gespecificeerd hebben voor de ESR1 expressie niet moeten transformeren omdat we het model fitten met de `lm`functie en de transformatie hebben gespecificeerd binnen die functie met behulp van het pipe commando!\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbrca |> ggplot(\n  aes(\n    x = ESR1 |> log2(),\n    y = S100A8 |> log2())\n  ) +\n  geom_point() +\n  geom_smooth(method = \"lm\")\n```\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\n## Terugtransformatie\n\n::: {.cell}\n\n```{.r .cell-code}\nnewdata<-data.frame(cbind(grid,2^g))\nbrca |>\n  ggplot(aes(x = ESR1, y = S100A8)) +\n  geom_point() +\n  geom_line(aes(x=grid,y=fit),newdata) +\n  geom_line(aes(x=grid,y=lwr),newdata,color=\"grey\") +\n  geom_line(aes(x=grid,y=upr),newdata,color=\"grey\")\n```\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\n# Predictie-intervallen\n\n-We kunnen ook een voorspelling doen voor de locatie van een nieuwe waarneming die zou worden verzameld in een nieuw experiment voor een patiënt met een bepaalde waarde voor hun ESR1-expressie\n\n- Het is belangrijk op te merken dat dit experiment nog moet worden uitgevoerd. We willen dus de niet-waargenomen individuele expressiewaarde voor een nieuwe patiënt voorspellen.\n\n- Voor een nieuwe onafhankelijke waarneming $Y^*$\n$$\n  Y^* = g(x) + \\epsilon^*\n$$\nmet $\\epsilon^*\\sim N(0,\\sigma^2)$ en $\\epsilon^*$ onafhankelijk van de waarnemingen in de steekproef $Y_1,\\ldots, Y_n$.\n\n- We voorspellen een nieuwe log-S100A8 voor een patiënt met een gekend log2-ESR1-expressieniveau x\n\\[\n  \\hat{y}(x)=\\hat{\\beta}_0+\\hat{\\beta}_1 \\times x\n\\]\n\n-  De geschatte gemiddelde uitkomst en voorspelling voor een nieuwe waarneming zijn gelijk.\n\n-  Maar hun steekproef verdelingen zijn anders!\n\n    - Onzekerheid over de geschatte gemiddelde uitkomst   $\\leftarrow$ onzekerheid over de geschatte modelparameters $\\hat\\beta_0$ en $\\hat\\beta_1$.\n    - Onzekerheid over nieuwe waarneming $\\leftarrow$ *onzekerheid over geschat gemiddelde* en  *extra onzekerheid*  omdat de nieuwe waarneming zal afwijken rond het gemiddelde!\n\n\n$$\\text{SE}_{\\hat{Y}(x)}=\\sqrt{\\hat\\sigma^2+\\hat\\sigma^2_{\\hat{g}(x)}}=\\sqrt{MSE\\left\\{1+\\frac{1}{n}+\\frac{(x-\\bar X)^2}{\\sum\\limits_{i=1}^n (X_i-\\bar X)^2}\\right\\}}.$$\n\n$$\\frac{\\hat{Y}(x)-Y}{\\text{SE}_{\\hat{Y}(x)}}\\sim t_{n-2}$$\n\n- Merk op dat een **predictie-interval** (PI) een verbeterde versie is van een referentie-interval wanneer de modelparameters onbekend zijn: onzekerheid over modelparameters + t-verdeling.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np <- predict(\n  lm2,\n  newdata = data.frame(ESR1 = grid),\n  interval=\"prediction\")\n\nhead(p)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       fit      lwr      upr\n1 11.89028 9.510524 14.27004\n2 11.87370 9.495354 14.25205\n3 11.85724 9.480288 14.23419\n4 11.84089 9.465324 14.21646\n5 11.82466 9.450461 14.19886\n6 11.80854 9.435698 14.18138\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npreddata<-data.frame(\n  grid = grid|>log2(),\n  p)\nbrca |> ggplot(aes(x=ESR1|>log2(),y=S100A8|>log2())) +\n  geom_point() +\n  geom_smooth(method=\"lm\") +\n     geom_line(aes(x=grid,y=lwr),preddata,color=\"blue\") +\n  geom_line(aes(x=grid,y=upr),preddata,color=\"blue\")\n```\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npreddata<-data.frame(cbind(grid,2^p))\nbrca |> ggplot(aes(x = ESR1, y = S100A8)) +\n  geom_point() +\n  geom_line(\n    aes(x = grid,y = fit),\n    newdata) +\n  geom_line(\n    aes(x = grid, y = lwr),\n    newdata,\n    color = \"grey\") +\n  geom_line(\n    aes(x = grid, y = upr),\n    newdata,\n    color = \"grey\") +\n  geom_line(\n    aes(x = grid, y = lwr),\n    preddata,\n    color = \"blue\") +\n  geom_line(\n    aes(x = grid,y = upr),\n    preddata,\n    color = \"blue\")\n```\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\n\n## NHANES voorbeeld\n\n\n- Vergelijk referentie-interval voor cholesterolgehalte met predictie interval.\n\n- Referentie-interval\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(NHANES)\nfem <- NHANES |>\n  filter(Gender==\"female\"&!is.na(DirectChol))\n\n2^(\n  fem |>\n  pull(DirectChol) |>\n  log2() |>\n  mean() +\n    c(-1,1) *\n    qnorm(0.975) *\n    (fem |>\n      pull(DirectChol) |>\n      log2() |>\n      sd())\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8361311 2.4397130\n```\n\n\n:::\n:::\n\n\n- Predictie interval\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlmChol <- lm(DirectChol |> log2() ~ 1, data=fem)\npredInt <- predict(\n  lmChol,\n  interval=\"prediction\",\n  newdata=data.frame(noPred=1)\n  )\nround(2^predInt,2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   fit  lwr  upr\n1 1.43 0.84 2.44\n```\n\n\n:::\n:::\n\n\nMerk op dat het voorspellingsinterval bijna gelijk is aan het referentie-interval voor de grote steekproef. We konden de parameters inderdaad heel precies schatten.\n\nWe zullen hetzelfde doen voor een kleine steekproef van 10 patiënten.\n\n- Referentie interval\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\nfem10 <- NHANES |>\n  filter(Gender==\"female\"&!is.na(DirectChol)) |>\n  sample_n(size=10)\n\n2^(\n  fem10 |>\n    pull(DirectChol) |>\n    log2() |>\n    mean() +\n      c(-1,1) *\n      qnorm(0.975) *\n      (fem10 |>\n        pull(DirectChol) |>\n        log2() |>\n        sd())\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8976012 2.2571645\n```\n\n\n:::\n:::\n\n\nHet referentie-interval is veel smaller dan in de grote steekproef.\n\n- Predictie interval\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlmChol10 <- lm(DirectChol |> log2() ~ 1, data = fem10)\npredInt10 <- predict(\n  lmChol10,\n  interval = \"prediction\",\n  newdata = data.frame(noPred=1)\n  )\nround(2^predInt10, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   fit  lwr  upr\n1 1.42 0.81 2.49\n```\n\n\n:::\n:::\n\n\n- Merk op dat het PI nu onzekerheid meeneemt in parameterschatters (gemiddelde en standaard error).\nEn dat het interval veel breder wordt! Dit is hier vooral belangrijk voor de bovengrens omdat we de gegevens terug hebben getransformeerd!\n\n- Het interval is bijna net zo breed als dat gebaseerd op de grote steekproef.\n\n- Bij kleine steekproeven is het erg belangrijk om met deze extra onzekerheid rekening te houden.\n\n\n# Kwadratensommen en Anova-tabel\n\n## Totale kwadratensom\n\n$$\\text{SSTot} = \\sum_{i=1}^n (Y_i-\\bar{Y})^2.$$\n\n- SStot kan worden gebruikt om de variantie van de **marginale verdeling** van de respons te schatten.\n\n- In dit hoofdstuk hebben we ons gefocused op de **conditionele verdeling** $f(Y\\vert X=x)$.\n\n- We weten dat MSE een goede schatting is van de variantie van de conditionele verdeling van  $Y\\vert X=x$.\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-29-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n## Kwadratensom van de regressie SSR\n\n$$\\text{SSR} = \\sum_{i=1}^n (\\hat{Y}_i - \\bar{Y})^2 = \\sum_{i=1}^n (\\hat{g}(x_i) - \\bar{Y})^2.$$\n\n- Maat voor de afwijking tussen de predicties op de geschatte regressierechte en het steekproefgemiddelde van de uitkomsten.\n\n- Een andere interpretatie: verschil tussen twee modellen\n\n    - Geschatte model $\\hat{g}(x)=\\hat\\beta_0+\\hat\\beta_1x$\n    - Geschatte model zonder predictor (enkel intercept): $g(x)=\\beta_0$ $\\rightarrow$ $\\beta_0$ zal gelijk zijn aan $\\bar{Y}$.\n\n- SSR meet de grootte van het effect van de predictor\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-30-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n## Kwadratensom van de fouten\n\n$$ \\text{SSE} = \\sum_{i=1}^n (Y_i-\\hat{Y}_i )^2 = \\sum_{i=1}^n \\left\\{Y_i-\\hat{g}\\left(x_i\\right)\\right\\}^2.$$\n\n- Hoe kleiner de SSE, hoe beter het model fit.\n\n\n- Kleinste kwadraten techniek!\n\n***\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-31-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nWe kunnen aantonen dat SST kan worden ontbonden in\n\\begin{eqnarray*}\n  \\text{SSTot}\n    &=&  \\sum_{i=1}^n (Y_i-\\bar{Y})^2 \\\\\n    &=&  \\sum_{i=1}^n (Y_i-\\hat{Y}_i+\\hat{Y}_i-\\bar{Y})^2 \\\\\n    &=&  \\sum_{i=1}^n (Y_i-\\hat{Y}_i)^2+\\sum_{i=1}^n(\\hat{Y}_i-\\bar{Y})^2 \\\\\n    &=&  \\text{SSE }+\\text{SSR}  \n  \\end{eqnarray*}\n\n-  De totale variabiliteit in de gegevens (SSTot) wordt gedeeltelijk verklaard door het regressieverband (SSR).\n- Variabiliteit die we niet kunnen verklaren met het regressiemodel is de residuele variabiliteit (SSE).\n\n\n##  Determinatie-coëfficiënt\n\n$$ R^2 = 1-\\frac{\\text{SSE}}{\\text{SSTot}}=\\frac{\\text{SSR}}{\\text{SSTot}}.$$\n\n- *Fractie van de totale variabiliteit in de steekproef-uitkomsten die verklaard wordt door het geschatte regressieverband*.\n\n- Grote $R^2$ indicatie dat model potentieel tot goede predicties kan leiden (kleine SSE)\n\n- Slechts in beperkte mate indicatief voor de p-waarde van de test $H_0:\\beta_1=0$ vs $H_1:\\beta_1\\neq0$.\n\n    - p-waarde sterk beïnvloed door SSE en steekproefgrootte $n$, maar niet door SSTot\n    - De determinatiecoëfficiënt $R^2$ wordt door SSE en SSTot bepaald, maar niet door de steekproefgrootte n.\n\n- Model met lage $R^2$ blijft wel nuttig om associatie te bestuderen, zolang het de associatie correct modelleert!\n\n### Borstkanker voorbeeld\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lm2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = log2(S100A8) ~ log2(ESR1), data = brca)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.94279 -0.66537  0.08124  0.68468  1.92714 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   23.401      1.603   14.60 3.57e-15 ***\nlog2(ESR1)    -1.615      0.150  -10.76 8.07e-12 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.026 on 30 degrees of freedom\nMultiple R-squared:  0.7942,\tAdjusted R-squared:  0.7874 \nF-statistic: 115.8 on 1 and 30 DF,  p-value: 8.07e-12\n```\n\n\n:::\n:::\n\n\n## F-Testen in het enkelvoudig lineair regressiemodel\n\n- Kwadratensommen  zijn basis voor $F$-tests\n$$  F  = \\frac{\\text{MSR}}{\\text{MSE}}$$\n\nmet  $\\text{MSR} = \\frac{\\text{SSR}}{1} \\text{ and } \\text{MSE} = \\frac{\\text{SSE}}{n-2}.$\n\n- MSR wordt de gemiddelde kwadratensom van de regressie genoemd.\n\n- noemers 1 en $n-2$ zijn de vrijheidsgraden van SSR en SSE.\n\n- onder $H_0: \\beta_1=0$ volgt de teststatistiek\n$$H_0:F = \\frac{\\text{MSR}}{\\text{MSE}} \\sim F_{1,n-2},$$\n- F-test is altijd twee-zijdig! $H_1:\\beta_1\\neq 0$\n$$  p = P_0\\left[F\\geq f\\right]=1-F_F(f;1,n-2)$$\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lm2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = log2(S100A8) ~ log2(ESR1), data = brca)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.94279 -0.66537  0.08124  0.68468  1.92714 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   23.401      1.603   14.60 3.57e-15 ***\nlog2(ESR1)    -1.615      0.150  -10.76 8.07e-12 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.026 on 30 degrees of freedom\nMultiple R-squared:  0.7942,\tAdjusted R-squared:  0.7874 \nF-statistic: 115.8 on 1 and 30 DF,  p-value: 8.07e-12\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-34-1.png){width=672}\n:::\n:::\n\n\n\n## Anova Tabel\n\n\n| |Df|Sum Sq|Mean Sq|F value|Pr(>F)|\n|---|---|---|---|---|---|\n|Regressie|vrijheidsgraden SSR|SSR|MSR|f-statistiek|p-waarde|\n|Error|vrijheidsgraden SSE|SSE|MSE| | |\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(lm2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: log2(S100A8)\n           Df  Sum Sq Mean Sq F value   Pr(>F)    \nlog2(ESR1)  1 121.814 121.814   115.8 8.07e-12 ***\nResiduals  30  31.559   1.052                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n# Dummy variabelen\n\n- Lineaire regressiemodel voor het vergelijken van twee gemiddelden.\n- Borstkanker: verschil is in gemiddelde leeftijd van de patiënten met onaangetaste lymfeknopen en patiënten waarvan lymfeknopen werden verwijderd.\n\n- Hiervoor definiëren we eerst een $dummy$ variabele\n$$x_i = \\left\\{ \\begin{array}{ll}\n1 & \\text{aangetaste lymfeknopen} \\\\\n0 & \\text{onaangetaste lymfeknopen} \\end{array}\\right.$$\n\n- groep met $x_i=0$ wordt de **referentiegroep** genoemd.\n\n- Het regressiemodel blijft ongewijzigd,\n$$Y_i = \\beta_0 + \\beta_1 x_i +\\epsilon_i$$\nmet $\\epsilon_i \\text{ iid } N(0,\\sigma^2)$\n\n\nGezien $x_i$ slechts twee waarden kan aannemen, is het eenvoudig om het regressiemodel voor beide waarden van $x_i$ afzonderlijk te bekijken:\n$$ \\begin{array}{lcll}\n   Y_i &=& \\beta_0 +\\epsilon_i &\\text{onaangetaste lymfeknopen} (x_i=0) \\\\\n   Y_i &=& \\beta_0 + \\beta_1 +\\epsilon_i &\\text{ aangetaste lymfeknopen} (x_i=1) .\n \\end{array}$$\n\nDus\n \\begin{eqnarray*}\n   E\\left[Y_i\\mid x_i=0\\right] &=& \\beta_0 \\\\\n   E\\left[Y_i\\mid x_i=1\\right] &=& \\beta_0 + \\beta_1,\n\\end{eqnarray*}\n\n waaruit direct de interpretatie van $\\beta_1$ volgt:\n$$   \\beta_1 = E\\left[Y_i\\mid x_i=1\\right]-E\\left[Y_i\\mid x_i=0\\right]$$\n\n$\\beta_1$ is dus het gemiddelde verschil in leeftijd tussen patiënten met aangetaste lymfeknopen en patiënten met onaangetaste lymfeknopen (referentiegroep).\n\nMet de notatie $\\mu_0= E\\left[Y_i\\mid x_i=0\\right]$ en $\\mu_1= E\\left[Y_i\\mid x_i=1\\right]$ wordt dit\n$$\\beta_1 = \\mu_1-\\mu_0.$$\n\n\nEr kan aangetoond worden dat\n$$\\begin{array}{ccll}\n \\hat\\beta_0\n   &=& \\bar{Y}_1&\\text{ (steekproefgemiddelde in referentiegroep)} \\\\\n \\hat\\beta_1\n   &=& \\bar{Y}_2-\\bar{Y}_1&\\text{(schatter van effectgrootte)} \\\\\n \\text{MSE}\n   &=& S_p^2 .\n\\end{array}$$\n\nDe testen voor $H_0:\\beta_1=0$ vs.  $H_1:\\beta_1\\neq0$ kunnen gebruikt worden voor het testen van de nulhypothese van de two-sample $t$-test, $H_0:\\mu_1=\\mu_2$ t.o.v. $H_1:\\mu_1\\neq\\mu_2$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbrca$node <- as.factor(brca$node)\nt.test(age~node,brca,var.equal=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  age by node\nt = -2.7988, df = 30, p-value = 0.008879\nalternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0\n95 percent confidence interval:\n -15.791307  -2.467802\nsample estimates:\nmean in group 0 mean in group 1 \n       59.94737        69.07692 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm3 <- lm(age~node, brca)\nsummary(lm3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = age ~ node, data = brca)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-19.9474  -5.3269   0.0526   5.3026  18.0526 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   59.947      2.079  28.834  < 2e-16 ***\nnode1          9.130      3.262   2.799  0.00888 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 9.063 on 30 degrees of freedom\nMultiple R-squared:  0.207,\tAdjusted R-squared:  0.1806 \nF-statistic: 7.833 on 1 and 30 DF,  p-value: 0.008879\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(lm3)\n```\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-38-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-38-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-38-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-38-4.png){width=672}\n:::\n:::\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbrca |>\n  ggplot(\n    aes(\n      x = node |>\n        as.factor(),\n      y = age)\n      ) +\n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-39-1.png){width=672}\n:::\n:::\n\n\n\n1. Simulate 9 datasets with the same number of observations as the brca dataset from a normal distribution with the same standard deviation as in the original data. Store the data of all simulations in a data frame\n2. Plot the simulated data using the `ggplot` function\n3. Add a boxplot layer\n4. Use facet_wrap to make a separate plot for simulated dataset\n5. Change label of y-axis\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(354)\nsim_df <- data.frame(\n  node = rep(brca$node, 9),\n  iid = rnorm(9 * nrow(brca), sd = sigma(lm3)),\n  sim = rep(1:9, each = 32)\n  )\nsim_df |>\n  ggplot(aes(x = node, y=iid)) +\n  geom_boxplot() +\n  facet_wrap(.~sim) +\n  ylab(paste0(\"iid N(0,\",round(sigma(lm3)^2,2),\")\"))\n```\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-40-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n## Observationele study\n\n- We kunnen echter niet besluiten dat oudere personen een hoger risico hebben op aantasting van de lymfeknopen ten gevolge van hun leeftijd.\n\n- Mogelijks **confounding**: geen randomisatie $\\rightarrow$ groepen patiënten met aangetaste lymfeknopen en niet-aangetaste lymfeknopen kunnen nog in andere karakteristieken van elkaar verschillen.\n\n- Enkel besluiten dat er een associatie is tussen de lymfeknoop status en de leeftijd.\n\n- Het is dus niet noodzakelijkerwijs een causaal verband!\n\n***\n\n- Is ook zo voor lineair model voor de $\\log_2$-S100A8-expressie.\n\n- Aangezien we de ESR1-expressie niet experimenteel vast hebben kunnen leggen, kunnen we niet besluiten dat een hogere ESR1-expressie de S100A8-expressie doet verlagen.\n\n- Enkel besluiten dat er een negatieve associatie is.\n\n- Om impact van gen te bestuderen op andere genen: knockout mutanten generenen in het labo\n\n\n***\n",
    "supporting": [
      "06-linearRegression_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}