{
  "hash": "e5fb0949bc589e0d7f151b37c11ea374",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"11. Categorical Data Analysis\"\nauthor: \"Lieven Clement\"\ndate: \"statOmics, Ghent University (https://statomics.github.io)\"\nformat:\n  html:\n    toc: true\n    number-sections: true\n    theme: cosmo\n    highlight-style: tango\n    code-tools: true\n    embed-resources: true\n---\n\n\n\n\n# Introduction \n\nUntil now we used models for a continuous response in function of categorical or continuous predictor. Here we will focus on a categorical response.\n\n- we study the association of a categorical outcome and a categorical predictor and \n- touch upon methods to model a categorical outcome with a continuous response. \n\n\n***\n\n# Test for a proportion \n\n## Saksen-study\n\n- Fairly closed population (few migration)\n- Probability that an unborn child is male?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboys <- 3175\nn <- 6155\n```\n:::\n\n\n- On 6155 unborn children 3175 boys are observed.\n- Is there a difference in the probability on the gender of an unborn child? \n\n***\n\n- The data are derived from a binary random variable $X$\n\n  - $X=1$ for a boy and \n  - $X=0$ for a girl.\n\n- Note: count problem: the outcome is a count (number of boys) \n\n- Formally we have considered a population of unborn children where each individual is characterized by a 0 or 1.\n\n***\n\n## Bernoulli Probability Mass Distribution\n\n- Binary data can be modelled using a Bernoulli distribution:\n  \\begin{eqnarray*}\nX_i &\\sim& B(\\pi) \\text{ with}\\\\\nB(\\pi)&=&\\pi^{X_i}(1-\\pi)^{(1-X_i)},\n\\end{eqnarray*}\n\n- It has one model parameter $\\pi$\n\n    - Expected value of $X_i$: $\\text{E}[X_i]=\\pi,$\n    - Proportion of unborn boys (children with $X=1$) in the population.\n    - Hence $\\pi$ is the probability that a random individual from the population is a boy (an observation with $X=1$).\n\n- The variance of Bernoulli data is also related to $\\pi$.\n$$\\text{Var}[X_i]=\\pi (1-\\pi).$$\n\n***\n\nSome Bernoulli probability mass functions\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](10-categoricalDataAnalysis_files/figure-html/unnamed-chunk-2-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n***\n\n- In the Saksen study  6155 observaties were sampled at random from the population.\n- We can estimate $\\pi$  using the sample mean:\n$$\\hat \\pi = \\bar X = \\frac{\\sum\\limits_{i=1}^n X_i}{n},$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\npi=boys/n\npi\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5158408\n```\n\n\n:::\n:::\n\n\nIn our example $\\bar x =$ 3175 / 6155 = 51.6%.\n\n***\n\n## Binomiale test\n\n- Is the observed probability 51.6% that an unborn child is male, sufficient evidence to conclude that there is a higher chance on a boy than on a girl? \n\n- Statistical test for \n  $$H_0: \\pi=1/2 \\text{ versus } H_1: \\pi\\neq 1/2,$$\n\n- We need known the distribution of \n   \n    - $X$ and $\\bar X$\n    - or of the sum $S=n\\bar X$.\n\n***\n\n\n- Suppose that $H_0:\\pi=1/2$ is true (boys and girls have an equal frequency in the population)\n- A random individual from the population has a probability of $$P(X=1)=\\pi=1/2.$$ to be a boy\n\n- Two children that are drawn independently :\n  \n    - Probability of $\\pi=1/2$ on a boy for the first and second child (independent from each other) \n    - Outcomes $(x_1, x_2)$ for both children have 4 possible combinations:\n    $(0,0),(0,1),(1,0)\\text{ en }(1,1).$\n    - Each of them has a probability of $1/4 = 1/2 \\times 1/2$.\n\n- Random variable $S$ is the sum of the outcomes :\n\n$(x_1,x_2)$|$s$|$P(S = s)$|\n|:---:|:---:|:---:|\n(0,0)|0|1/4|\n(0,1), (1,0)|1|1/2|\n(1,1)|2|1/4|\n\n***\n\n### General: $n$ independent samples\n\n- Probability for $\\pi$ on success ($X=1$)\n- Total number of successes $S$ (sum of all values of 1) can take $n+1$ possible values\n  $$S=k\\text{, met }k=0,\\ldots,n$$\n- Distribution of $S$?\n\\begin{equation}\nP(S=k) = \\left (\n\\begin{array}{c}\nn \\\\\nk \\\\\n\\end{array}\n\\right ) \\pi^k (1-\\pi)^{n-k}  \n\\end{equation}\n- $1-\\pi$: probability on 0 for individual observation and\n-  binomial coefficient\n\\begin{equation*}\n\\left (\n\\begin{array}{c}\nn \\\\\nk \\\\\n\\end{array}\n\\right ) = \\frac{n \\times (n-1) \\times ...\\times (n-k+1) }{ k!} = \\frac{ n!}{ k!(n-k)! }\n\\end{equation*}\n\n- In R you can calculate the probabilities on each $S=k$ with the function `dbinom(k,n,p)`\n\n\n***\n\n### Binomial Distribution\n\nS is a:\n\n-  *Binomial distributed random  variable* with *Binomial probability mass function*\n\n- Parameters\n\n    - $n$ (total number of draws from the population, is equivalent to maximal value of the outcome)  \n    - $\\pi$ (probability on `success` for each draw).\n\n- Calculate probability on $k$ successes on $n$ independent draws each with a succes probability of $\\pi$.\n- For binary data X.\n- e.g.: wild type vs mutant of a gene, infected or not infected with HIV, ...\n- Use: Compare proportions or risks on a particular event between groups.\n\n***\n\n### Some Binomial probability mass functions.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Binomiale verdelingen.](10-categoricalDataAnalysis_files/figure-html/binoms-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n***\n\nTest statistic $$H_0:\\pi=1/2\\text{ vs }H_1:\\pi\\neq 1/2$$\n\n\n- $\\bar X-1/2$ or, equivalent,\n- $\\Delta=n(\\bar X-\\pi_0)=S-s_0$.\n- Distribution of the latter test statistic can be derived immediately from the Binomial distribution:\n  - We observe $s=$ 3175 and thus $\\delta=s-s_0=$ 3175 $-$ 6155 $\\times 0.5=$ 97.5.\n  - When boys and girls are equally likely, i.e. under $H_0:\\pi=1/2$, we will get following two-sided p-value:\n    $$p=\\text{P}_0\\left[S-s_0\\geq \\vert \\delta\\vert \\right] + \\text{P}_0\\left[S-s_0\\leq - \\vert \\delta\\vert \\right].$$\n\n- Note, that we can rewrite it in terms of S.\n$$p=\\text{P}_0\\left[S\\geq s_0+ \\vert \\delta\\vert \\right] + \\text{P}_0\\left[S \\leq s_0 - \\vert \\delta\\vert \\right].$$\n\n***\n\n- For the Saksen study we calculate:\n\n\\begin{eqnarray*}\n\\text{P}_0\\left[S\\geq s_0+ \\vert \\delta\\vert \\right] &=& P(S \\geq 6155 \\times 0.5 + \\vert 3175 - 6155 \\times 0.5\\vert ) \\\\&=& P(S \\geq 3175)\\\\\n&= &P(S= 3175) + P(S=3176) + ... + P(S=6155)\\\\\n& =& 0.0067\\\\\\\\\n\\text{P}_0\\left[S \\leq s_0 - \\vert \\delta\\vert \\right] &=& P(S \\leq  6155 \\times 0.5 - \\vert 3175- 6155 \\times 0.5\\vert) \\\\&=& P(S \\leq 2980)\\\\ &= &P(S=0) + ... + P(S=2980) \\\\\n&=&0.0067\n\\end{eqnarray*}\n\n- The Binomial distribution is symmetric for$\\pi=1/2$:\n$$\\text{P}_0\\left[S\\geq s_0+ \\vert \\delta\\vert \\right] = \\text{P}_0\\left[S \\leq s_0 - \\vert \\delta\\vert \\right]$$\n- This is no longer the case when $\\pi$ deviate from 0.5.  \n\n***\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npi0 <- 0.5; s0 <- pi0 *n\ndelta <- abs(boys- s0)\ndelta\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 97.5\n```\n\n\n:::\n\n```{.r .cell-code}\nsUp <- s0 + delta\nsDown <- s0 -delta\nc(sDown,sUp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2980 3175\n```\n\n\n:::\n\n```{.r .cell-code}\npUp <- 1-pbinom(sUp-1,n,pi0)\npDown <- pbinom(sDown,n,pi0)\np <- pUp+pDown\nc(pUp,pDown, p)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.006699883 0.006699883 0.013399766\n```\n\n\n:::\n:::\n\n\n***\n\n\n- If $\\pi= 1/2$, the probability to observe at least  $\\delta=$ 97.5 boys more or less than the mean under $H_0: s_0=$ 3077.5 in a random sample under H_0 is only 1.34% is: **$p$-value of binomial test.**  \n- Very unlikely to observe such a large number of boys in a random sample when boys and girls have the same  frequency in the population (under $H_0$).\n- Hence the hypothesis that the frequency of boys and girls is the same is not supported by the data. \n\n***\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](10-categoricalDataAnalysis_files/figure-html/unnamed-chunk-5-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n***\n\nThe test can immediately be conducted using the `binomial.test` function in R.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbinom.test(x=boys,n=n,p=pi0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tExact binomial test\n\ndata:  boys and n\nnumber of successes = 3175, number of trials = 6155, p-value = 0.0134\nalternative hypothesis: true probability of success is not equal to 0.5\n95 percent confidence interval:\n 0.5032696 0.5283969\nsample estimates:\nprobability of success \n             0.5158408 \n```\n\n\n:::\n:::\n\n\nOn the 5% significance-level we conclude that there is on average a higher probability on a unborn male child than an unborn female child.   \n\n***\n\n### Confidence interval on a proportion\n\n- Estimator of the proportion of boys in the population  is the sample mean $\\hat \\pi=\\bar x=$ 0.516\n- The standard error is\n$$SE_{\\bar x}=\\sqrt{\\frac{\\text{Var}[X]}{n}}=\\sqrt{\\frac{\\pi(1-\\pi)}{n}}$$\n- We can estimate this based on the sample: $SE_{\\bar x}=\\sqrt{\\frac{\\hat\\pi(1-\\hat\\pi)}{n}}=$ 0.0064.\n- 95% CI via CLT: $\\hat\\pi \\pm 1.96 SE_{\\hat\\pi}.$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nse=sqrt(pi*(1-pi)/n)\npi+c(-1,1)*qnorm(0.975)*se\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5033559 0.5283257\n```\n\n\n:::\n:::\n\n\n***\n\n### CI on proportion in small sample? \n\n\n::: {.cell}\n\n```{.r .cell-code}\nCI <- binom.test(x=boys,n=n,p=pi0)$conf.int\nCI\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5032696 0.5283969\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n:::\n\n\n***\n\n\n### Conclusion\n\n- Note that the test for a proportion is equivalent to a one-sample t-test for binary data.\n\n- For the Saksen population we conclude at the 5% significance level that the gender of unborn children is more likely to be male than female ($p=$ 0.013).\nThe probability that an unborn child is male equals 51.6% (95% CI [50.3,52.8]%).\n\n***\n\n# Test for association between two qualitative variables \n## Paired observations\n\n- 2 measurements on same individual\n- e.g. before and after exposure to a chemical substance\n- observe a categorical outcome before and after.\n- *gepaarde binary responses*\n- Statistical analysis has to account for paired design.\n\n***\n\n### Example:  Females choose gentle, but not healthy or macho males in Campbell dwarf hamsters (Rogovin et al. 2017)\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](10-categoricalDataAnalysis_files/figure-html/unnamed-chunk-9-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n***\n\n- The gate is opened upon 3 minutes \n- aggressive vs non-agressive male \n- Each female undergoes the test twice: \n\n    - once upon stay in hostile environment (high population density, shortage of feed, a lot of competition)\n    - and once upon stay in gentle evironment.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|                      |friendly_agressive |friendly_non-agressive |total |\n|:---------------------|:------------------|:----------------------|:-----|\n|hostile_agressive     |3 (e)              |17 (f)                 |20    |\n|hostile_non-agressive |1 (g)              |13 (h)                 |14    |\n|total                 |4                  |30                     |34    |\n\n\n:::\n:::\n\n\n***\n### Absolute risk difference (ARD)\n- $\\pi_1=P[\\text{agressive male } \\vert \\text{hostile}]$\n- $\\hat \\pi_1=(e+f)/n$, with $n=e+f+g+h$.\n\n- $\\pi_0=P[\\text{agressive male } \\vert \\text{ friendly}]$\n- $\\hat \\pi_0=(e+g)/n$\n\\begin{equation*}\n\\widehat{\\text{ARD}}=\\hat\\pi_1-\\hat\\pi_0=\\frac{e+f}{n}-\\frac{e+g}{n}=\\frac{f-g}{n}\n\\end{equation*}\n- Only affected by discordant pairs $f$ en $g$\n\n***\n\n- Standard error on ARD\n\\begin{equation*}\n\\text{SE}_{\\widehat{\\text{ARD}}}=\\frac{1}{n}\\sqrt{f+g-\\frac{(f-g)^2}{n}}\n\\end{equation*}\n\n- If we have large number of observations we can use the CLT to establish an $(1-\\alpha)100\\%$ CI on the ARD\n$$\\left[\\widehat{\\text{ARD}}-z_{\\alpha/2}\\text{SE}_{\\widehat{\\text{ARD}}},\\widehat{\\text{ARD}}-z_{\\alpha/2}\\text{SE}_{\\widehat{\\text{ARD}}}\\right]$$\nor\n$$\\left[\\frac{f-g}{n}-\\frac{z_{\\alpha/2}}{n}\\sqrt{f+g-\\frac{(f-g)^2}{n}},\\frac{f-g}{n}+\\frac{z_{\\alpha/2}}{n}\\sqrt{f+g-\\frac{(f-g)^2}{n}}\\right] $$\n\n***\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhamster <- matrix(c(3,17,1,13),ncol=2,byrow=TRUE)\nrownames(hamster) <- c(\"hostile-agressive\", \"hostile-non-agressive\")\ncolnames(hamster) <- c(\"friendly-agressive\",\"friendly-non-agressive\")\n\nf=hamster[1,2]; g=hamster[2,1] ;n=sum(hamster)\nriskdiff=(f-g)/n\nriskdiff\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.4705882\n```\n\n\n:::\n\n```{.r .cell-code}\nse=sqrt(f+g-(f-g)^2/n)/n\nse\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.09517144\n```\n\n\n:::\n\n```{.r .cell-code}\nci<-riskdiff+c(-1,1)*qnorm(0.975)*se\nci\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2840556 0.6571208\n```\n\n\n:::\n:::\n\n\n***\n\n\\begin{equation*}\n\\widehat{\\text{ARD}}=\\frac{17-1}{34}=0.471\n\\end{equation*}\nThe absolute risk difference on choosing for an agressive male is 47.1% larger upon staying in a hostile environment that when residing in a gentle environment. \n- The standard error\n\\begin{equation*}\n\\text{SE}_{\\widehat{\\text{ARD}}}=\\frac{1}{34}\\sqrt{17+1-\\frac{(17-1)^2}{34}}=0.0952\n\\end{equation*}\n- A 95\\% confidence interval on this absolute risk difference is \n\\begin{equation*}\n\\left[0.471-1.96\\times 0.0952,0.471+1.96\\times 0.0952\\right]=[0.284,0.658]\n\\end{equation*}\n\n***\n\n## McNemar test\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|                      |friendly_agressive |friendly_non-agressive |total |\n|:---------------------|:------------------|:----------------------|:-----|\n|hostile_agressive     |3 (e)              |17 (f)                 |20    |\n|hostile_non-agressive |1 (g)              |13 (h)                 |14    |\n|total                 |4                  |30                     |34    |\n\n\n:::\n:::\n\n\n- Assess if risk on choice for agressive male differs between residing in hostile and friendly environment.\n- Only discordant pairs give information.\n- $f>g$ indication against $H_0$: choice of partner not associated with environment.\n- Evaluate probability that in a random discordant pair, a female chooses an agressive male upon a stay in a hostile environment.\n- We estimate the probability as\n  $$\\frac{f}{f+g}$$\n\n***\n\n  \\begin{eqnarray*}\n  \\text{E}\\left[f/(f+g)\\right]&\\stackrel{H_0}{=}& 0.5\\\\\n  f & \\stackrel{H_0}{\\sim}& \\text{Binom}(n=f+g,\\pi=0.5)\\\\\n  \\text{SE}_{\\frac{f}{f+g}} & \\stackrel{H_0}{=}& \\sqrt{(f+g)\\times 0.5\\times 0.5}=\\frac{\\sqrt{f+g}}{2}\n\\end{eqnarray*}\n\n***\n\n- Asymptotically a one-sample z-test (based on the Normal distribution)\n\n\\begin{equation*}\nz=\\frac{f-(f+g)/2}{\\sqrt{f+g}/2}=\\frac{f-g}{\\sqrt{f+g}}\n\\end{equation*}\n\n- Normal approximation is good if $$f \\times g/(f+g) \\geq 5$$\n\nThe **Mc Nemar test** is the analogon of the paired t-test for binary qualitative variables.\n\n***\n\nIn R we can conduct the analysis using the  `mcnemar.test` function\n\n::: {.cell}\n\n```{.r .cell-code}\nmcnemar.test(hamster)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMcNemar's Chi-squared test with continuity correction\n\ndata:  hamster\nMcNemar's chi-squared = 12.5, df = 1, p-value = 0.000407\n```\n\n\n:::\n:::\n\n\n\n- We reject the null hypothesis at the 5% significance level \n- We conclude that the choice of partner is extremely significantly associated with the environment.\n\n***\n\n- Normale approximation is not optimal and we can perform an exact test using the binomiale test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbinom.test(x=f,n=f+g,p=0.5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tExact binomial test\n\ndata:  f and f + g\nnumber of successes = 17, number of trials = 18, p-value = 0.000145\nalternative hypothesis: true probability of success is not equal to 0.5\n95 percent confidence interval:\n 0.7270564 0.9985944\nsample estimates:\nprobability of success \n             0.9444444 \n```\n\n\n:::\n:::\n\n\n***\n\n### Conclusion\n\n- We conclude that the partner choice is extremely signficantly associated with the environment ($p<0.001$).\n- The probability on choosing an agressive male is on average 47.1% higher when a female hamster resides in a hostile environment than when she resides in a friendly environment (95% CI [28.4,65.7]%).\n\n***\n\n# Unpaired observations\n## Genetic association study\n\n- Are genetic polymorphisms in the BRCA1 gene associated with breast cancer?\n- Retrospective case-control study with 800 breast cancer cases en 572 controls\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbrca<-read_csv(\"https://raw.githubusercontent.com/statOmics/sbc/master/data/brca.csv\")\nhead(brca)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 3\n  cancer  variant variant2\n  <chr>   <chr>   <chr>   \n1 control pro/pro other   \n2 control pro/pro other   \n3 control pro/pro other   \n4 control pro/pro other   \n5 control pro/pro other   \n6 control pro/pro other   \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(brca)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       cancer          variant          variant2   \n Length   :1372   Length   :1372   Length   :1372  \n N.unique :   2   N.unique :   3   N.unique :   2  \n N.blank  :   0   N.blank  :   0   N.blank  :   0  \n Min.nchar:   4   Min.nchar:   7   Min.nchar:   5  \n Max.nchar:   7   Max.nchar:   7   Max.nchar:   7  \n```\n\n\n:::\n:::\n\n\n***\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Genotype |Control     |Cases       |Total     |\n|:--------|:-----------|:-----------|:---------|\n|Pro/Pro  |266 (a)     |342 (d)     |608 (a+d) |\n|Pro/Leu  |250 (b)     |369 (e)     |619 (b+e) |\n|Leu/Leu  |56 (c)      |89 (f)      |145 (c+f) |\n|Totaal   |572 (a+b+c) |800 (d+e+f) |1372 (n)  |\n\n\n:::\n:::\n\n\n- In case-control study one chooses a fixed number of cases and controls and registers which exposures they had in the past.\n- Retrospective study\n- Impossible to assess risks and risk-differences on breast cancer because the proportion of cases and controls does not reflect that in the population!\n\n***\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Genotype |Controls    |Cases       |Total     |\n|:--------|:-----------|:-----------|:---------|\n|Pro/Pro  |266 (a)     |342 (d)     |608 (a+d) |\n|Pro/Leu  |250 (b)     |369 (e)     |619 (b+e) |\n|Leu/Leu  |56 (c)      |89 (f)      |145 (c+f) |\n|Totaal   |572 (a+b+c) |800 (d+e+f) |1372 (n)  |\n\n\n:::\n:::\n\n\n- Is possible to assess probability on allel Leu/Leu\n    - cases: $\\pi_1=f/(d+e+f)=89/800=11.1\\%$\n    - controls:$\\pi_0=c/(a+b+c)=56/572=9.8\\%$\n- Relative risk on exposure for cases versus controls is $11.1/9.8=1.14$.\n- The probability on the Leu/Leu genotype is 14% higher for women with breast cancer than for women without borstkanker.\n- It suggests an association, but it does not let us conclude how much higher the risk is on breast cancer for women with the Leu/Leu genotype as compared to the other women. \n- Other statistic?\n\n***\n\n\\begin{equation*}\nOdds=\\frac{p}{1-p}\n\\end{equation*}\nwith $p$ the probability on the event.\n\nTransformation of risk with following properties:\n\n  - odds has value between 1 and $\\infty$.\n\n  - odds only equals 1 for probability $p=1/2$.\n\n  - de odds increases if probability increases.\n\n- popular in gambling: how much more likely is it to win than to loose\n\n***\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Genotype |Controls    |Cases       |Total     |\n|:--------|:-----------|:-----------|:---------|\n|Pro/Pro  |266 (a)     |342 (d)     |608 (a+d) |\n|Pro/Leu  |250 (b)     |369 (e)     |619 (b+e) |\n|Leu/Leu  |56 (c)      |89 (f)      |145 (c+f) |\n|Totaal   |572 (a+b+c) |800 (d+e+f) |1372 (n)  |\n\n\n:::\n:::\n\n\nOdds on allel Leu/Leu\n\n- Cases: $\\mbox{odds}_1=\\frac{ f/(d+e+f)}{(d+e)/(d+e+f)}=f/(d+e)=89/711=0.125$. The double Leu/Leu variant is 8 times less likely than other allele combinations in the breast cancer cases\n- Controls: $\\mbox{odds}_2=c/(a+b)=56/516=0.109$.\n\n- Association between exposure and outcome:\n$$\nOR_{Leu/Leu}=\\frac{\\mbox{odds}_T}{\\mbox{odds}_C}= \\frac{f/(d+e)}{c/(a+b)}=\\frac{f/(d+e)}{c/(a+b)}=1.15\n$$\n\n***\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Genotype |Controls    |Cases       |Total     |\n|:--------|:-----------|:-----------|:---------|\n|Pro/Pro  |266 (a)     |342 (d)     |608 (a+d) |\n|Pro/Leu  |250 (b)     |369 (e)     |619 (b+e) |\n|Leu/Leu  |56 (c)      |89 (f)      |145 (c+f) |\n|Totaal   |572 (a+b+c) |800 (d+e+f) |1372 (n)  |\n\n\n:::\n:::\n\n\n- If the study would have been a random sample of the population (number of cases and controls not fixed by design) then we would be able to calculate the odds ratio on breast cancer for people with and without the double Leu/leu variant.\n\\begin{equation*}\nOR_{case}=\\frac{ \\frac{ f}{c}}{ \\frac{(d+e)}{(a+b)}} = \\frac{f(a+b)}{c(d+e)}=OR_{Leu/Leu}=1.15,\n\\end{equation*}\n- OR is a symmetric statistic! \n- OR on borstcancer can be estimated!\n- The odds on borstcancer is 15% higher for women with this specific allele combination.\n\n***\n\n- Is the difference large enough to generalize the effect in the sample towards the population? \n\n- We will first rewrite the data in a 2x2 table\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Genotype |Controls  |Cases     |Totaal     |\n|:--------|:---------|:---------|:----------|\n|other    |516 (a)   |711 (c)   |1227 (a+c) |\n|Leu/Leu  |56 (b)    |89 (d)    |145 (b+d)  |\n|Total    |572 (a+b) |800 (c+d) |1372 (n)   |\n\n\n:::\n:::\n\n\n***\n\n## Pearson Chi-square test for independent samples\n\n- Test association between categorical exposure(e.g. variant, X) en categorical response (e.g. disease, Y).\n$$H_0: \\text{There is no association between } X \\text{ and } Y \\text{ vs } H_1: X \\text{ and } Y \\text{ are associated}$$\n\n- Consider row totals $n_\\text{other}=a+c$, $n_\\text{leu,leu}=b+d$ and\n- column totals $n_\\text{contr}=a+b$ en $n_\\text{case}=c+d$.\n- They give information on *marginal distribution* of the exposure (variant, X) and outcome (disease, Y),\nbut not on the association between these variables.\n- Under $H_0$ $X$ and $Y$ are independent and one expects  that $(b+d)/n$\nof the $a+b$ controls have a Leu/Leu variant, or that $(a+b)(b+d)/n$ of them has a Leu/Leu variant \n- We can calculate this expected number $E_{ij}$ under the null hypothesis for *each cell* of the $2 \n\\times 2$ table.\n\n***\n\n- $E_{11}$ = Expected number under $H_0$ in  (1,1)-cell = 1227 $\\times$ 800/1372 = 715.5 ;\n\n- $E_{12}$ = Expected number under $H_0$ in  (1,2)-cell = 1227 $\\times$ 572/1372 = 511.5 ;\n\n- $E_{21}$ = Expected number under $H_0$ in  (2,1)-cell = 145 $\\times$ 800/1372 = 84.55 ;\n\n- $E_{22}$ = Expected number under $H_0$ in  (2,2)-cell = 145 $\\times$ 572/1372 = 60.45 ;\n\nTest-statistic:\n\\begin{eqnarray*}\nX^2 &=& \\frac{\\left (|O_{11} - E_{11}| - .5 \\right)^2 }{ E_{11}} + \\frac{\n\\left ( |O_{12} - E_{12}| - .5 \\right)^2 }{E_{12} }+ \\\\\n&&\\quad\\quad\n\\frac{ \\left ( |O_{21}\n- E_{21}| - .5 \\right)^2 }{E_{21}}+ \\frac{ \\left ( |O_{22} - E_{22}| - .5\n\\right)^2 }{E_{22} }\\\\\n X^2 &\\stackrel{H_0}{\\longrightarrow}& \\chi^2(df=1)\n\\end{eqnarray*}\n\n***\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](10-categoricalDataAnalysis_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n***\n\n- A large value of the test statistic gives an indication that the null hypothesis is false.\n- The test will reject $H_0$ at the $\\alpha 100\\%$\nsignificance level as soon as the observed test-statistic is larger than the $100\\%(1-\\alpha)$-quantile, $\\chi^2_{1,\n\\alpha}$, of the $\\chi^2_1$-distribution.\n- Otherwise we do not reject $H_0$.\n- The p-value of a 2-sided test is the probability to observe a larger test-statistic in a random sample under the null than what we observed in our sample. \n$$p=P_0[\\chi^2_1 \\geq x^2]$$.\n\n***\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexpected <- matrix(0,nrow=2,ncol=2)\nfor (i in 1:2)\n\tfor (j in 1:2)\n\t\texpected[i,j] <-\n\t\t\tsum(brcaTab2[i,])*sum(brcaTab2[,j])/sum(brcaTab2)\nexpected\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         [,1]     [,2]\n[1,] 715.4519 511.5481\n[2,]  84.5481  60.4519\n```\n\n\n:::\n\n```{.r .cell-code}\nx2 <- sum((abs(brcaTab2-expected) - .5)^2/expected)\n1-pchisq(x2,1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.481519\n```\n\n\n:::\n:::\n\n\n***\n\n- Because $O_{ij}$ are discrete values, the $X^2$ can only take discrete values and the continuouss $\\chi^2_1$-distribution is only an approximation of the real distribution. \n- To improve the approximation one substracts 0.5 from the value in each cell: \n*continuity-correction*\n- We refer to this test as *Pearson Chi-squared test with Yates correction*.\n- When the correction is not used (i.e. when the values of `0.5' in the estimator $X^2$ are replaced) we use the *Pearson Chi-squared test*.\n\n***\n\nIn R you can switch the correction on or off by setting the argument `correct` on TRUE or FALSE, respectively:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchisq.test(brcaTab2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test with Yates' continuity correction\n\ndata:  brcaTab2\nX-squared = 0.49542, df = 1, p-value = 0.4815\n```\n\n\n:::\n\n```{.r .cell-code}\nchisq.test(brcaTab2,correct=FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  brcaTab2\nX-squared = 0.62871, df = 1, p-value = 0.4278\n```\n\n\n:::\n:::\n\n\n***\n\n- Even with the $\\chi^2_1$ correction the approximation is only valid if non of the cells has an expected count below 5 under $H_0$.\n- When the $\\chi^2$-approximation is invalid we will use *Fisher's exact test*.\n-  Null hypothesis is also that $X$ and $Y$ are independent, and, the alternative hypothesis that $X$ and $Y$ are dependent.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfisher.test(brcaTab2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tFisher's Exact Test for Count Data\n\ndata:  brcaTab2\np-value = 0.4764\nalternative hypothesis: true odds ratio is not equal to 1\n95 percent confidence interval:\n 0.5974269 1.2501878\nsample estimates:\nodds ratio \n 0.8670925 \n```\n\n\n:::\n:::\n\n\n***\n\n\n## Extension to categorical variables with multiple levels\n\n- The $\\chi^2$-test can also be used if one of the categorical variables $X$ and $Y$ has more than 2 levels\n\n- Again: the null hypothesis $H_0$: $X$ and $Y$ are independent (not associated), against the alternative $H_A: X$ and $Y$\nare associated.\n\n- Let the variable in the rows have $r$ different possible outcomes and the one in the columns $c$ possible outcomes, then we obtain an $r \\times c$ table.\n\n- Again we will compare the observed values in  cell $(i,j)$, referred to as $O_{ij}$, with the expected number under $H_0$, $E_{ij}$\n - Again $E_{ij}$ is the product of the $i^\\text{th}$ row-total and the $j^\\text{th}$ column total devided by the overall total.\n\n\\begin{equation*}\nX^2 = \\sum_{ij} \\frac{\\left (O_{ij} - E_{ij}\\right)^2 }{ E_{ij}}\n\\end{equation*}\n\n***\n\n- We can show that the statistic follows a $\\chi^2$ distribution with $(r-1) \\times\n(c-1)$ degrees of freedom under $H_0$.\n- No continuity correction\n- **Pearson $\\chi^2$ test** is analogon of one-way ANOVA for qualitative variables.\n\n***\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbrcaTab <- table(brca$variant,brca$cancer)\nchisq.test(brcaTab)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  brcaTab\nX-squared = 2.0551, df = 2, p-value = 0.3579\n```\n\n\n:::\n:::\n\n\n- To assess if the variant of the BRCA1 gene is associated with breast cancer we conducted a  Pearson $\\chi^2$test for the $3 \\times 2$ table.\n- The statistic is now 2.055 and follows a $\\chi^2$ distribution with 2 degrees of freedom under $H_0$. The probability to obtain a $\\chi^2$-test statistic in a random sample under $H_0$ that is more extreme than 2.055, is 36%.\n- On the 5% level of significance we conclude that the variant of the BRCA-gene is not associated with breast cancer. \n\n***\n\n# Logistic regression\n\n- Framework to model binary data (e.g cancer vs no cancer): *logistic regression model*.\n- Model binary data with continuous and/or dummy variables.\n\n- The model assumes that observations for subject $i=1,\\ldots,n$ are independent and follow a Bernoulli distribution.\n- The logarithm of the odds is modelled using a linear model, also referred to as linear predictor:\n\\begin{equation}\n\\left\\{\n\\begin{array}{ccl}\nY_i&\\sim&B(\\pi_i)\\\\\\\\\n\\log \\frac{\\pi_i}{1-\\pi_i}&=&\\beta_0 + \\beta_1X_{i1} + \\ldots + \\beta_p X_{ip}\n\\end{array}\\right.\n\\end{equation}\n\n***\n\n## Categorical predictor\n\n- breast cancer example: is BRCA 1  variant associated with breast cancer.\n\n- As in the Anova context, a factor in logistic regression is coded using dummy variables.\n- 1 dummy variable less than the number of groups.\n\n- For BRCA 1 we need two dummy variables and obtain the following linear predictor:\n\n\\begin{eqnarray*}\n  \\log \\frac{\\pi_i}{1-\\pi_i} &=& \\beta_0+\\beta_1 x_{i1} +\\beta_2 x_{i2}\n\\end{eqnarray*}\n\n- with :\n$$x_{i1} = \\left\\{ \\begin{array}{ll}\n1 & \\text{ if subject $i$ is heterozygous, Pro/Leu variant} \\\\\n0 & \\text{if subject $i$ is homozygous, (Pro/Pro or Leu/Leu variant)} \\end{array}\\right. .$$\n$$x_{i2} = \\left\\{ \\begin{array}{ll}\n1 & \\text{ if subject $i$ is homozygous is the Leucine mutation: Leu/Leu } \\\\\n0 & \\text{ of subject $i$ is not homozygous in the Leu/Leu variant} \\end{array}\\right. .$$\n\n- Homozygosity in the  wild type allele Pro/Pro is the  **reference group**.\n\n***\n\nWe fit the model in R.\n\n- Note that we use the function `as.factor` to convert the cancer variable to a factor variable. - We further use the function `relevel` to specify the control treatment as the reference group.  \n\n::: {.cell}\n\n```{.r .cell-code}\nbrca$cancer<-brca$cancer |> as.factor() |> relevel(\"control\")\nbrca$variant<-brca$variant |> as.factor() |> relevel(\"pro/pro\")\nbrcaLogit <- glm(cancer~variant,data=brca,family=binomial)\nsummary(brcaLogit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = cancer ~ variant, family = binomial, data = brca)\n\nCoefficients:\n               Estimate Std. Error z value Pr(>|z|)   \n(Intercept)     0.25131    0.08175   3.074  0.00211 **\nvariantleu/leu  0.21197    0.18915   1.121  0.26243   \nvariantpro/leu  0.13802    0.11573   1.193  0.23302   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1863.9  on 1371  degrees of freedom\nResidual deviance: 1861.9  on 1369  degrees of freedom\nAIC: 1867.9\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n:::\n\n\nThe intercept is the log-odds on cancer in the reference class (Pro/Pro) and the slope terms are  log odds ratios between treatment and reference class:\n\\begin{eqnarray*}\n\\log \\text{ODDS}_\\text{Pro/Pro}&=&\\beta_0\\\\\\\\\n\\log \\text{ODDS}_\\text{Pro/Leu}&=&\\beta_0+\\beta_1\\\\\\\\\n\\log \\text{ODDS}_\\text{Leu/Leu}&=&\\beta_0+\\beta_2\\\\\\\\\n\\log  \\frac{\\text{ODDS}_\\text{Pro/Leu}}{\\text{ODDS}_\\text{Pro/Pro}}&=&\\log \\text{ODDS}_\\text{Pro/Leu}-\\log ODDS_{Pro/Pro}\\\\\n&=&\\beta_0+\\beta_1-\\beta_0=\\beta_1\\\\\\\\\n\\log  \\frac{\\text{ODDS}_\\text{Leu/Leu}}{\\text{ODDS}_\\text{Pro/Pro}}&=&\\beta_2\n\\end{eqnarray*}\n\n- The analysis allows us to interpret the result immediately in oddses and odds ratios!\n\n***\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(brcaLogit,test=\"Chisq\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Deviance Table\n\nModel: binomial, link: logit\n\nResponse: cancer\n\nTerms added sequentially (first to last)\n\n        Df Deviance Resid. Df Resid. Dev Pr(>Chi)\nNULL                     1371     1863.9         \nvariant  2   2.0562      1369     1861.9   0.3577\n```\n\n\n:::\n:::\n\n\nThe $\\chi^2$-test on the logsitic regression model also indicates that there is no significant association between cancer status and the genetic variant of the BRCA gene ($p=$ 0.358).\nDe p-value is almost equivalent to the one of the  $\\chi^2$-test (see previous section).\n\n***\n\n- Significant association? \n\n    - Post-hoc tests to evaluate which of the odds ratios are different from 1.\n    - For BRCA1 example we did not reject the omnibus hypothesis so no post-hoc analysis\n    - For your reference we include the post hoc analysis so that you would have the code. \n\n***\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsuppressPackageStartupMessages({library(multcomp)})\nposthoc <- glht(brcaLogit,linfct=mcp(variant = \"Tukey\"))\nposthocTests <- summary(posthoc)\nposthocTests\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t Simultaneous Tests for General Linear Hypotheses\n\nMultiple Comparisons of Means: Tukey Contrasts\n\n\nFit: glm(formula = cancer ~ variant, family = binomial, data = brca)\n\nLinear Hypotheses:\n                       Estimate Std. Error z value Pr(>|z|)\nleu/leu - pro/pro == 0  0.21197    0.18915   1.121    0.493\npro/leu - pro/pro == 0  0.13802    0.11573   1.193    0.449\npro/leu - leu/leu == 0 -0.07395    0.18922  -0.391    0.917\n(Adjusted p values reported -- single-step method)\n```\n\n\n:::\n:::\n\n\n***\n\n\n::: {.cell}\n\n```{.r .cell-code}\nposthocCI <- confint(posthoc)\nposthocCI\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t Simultaneous Confidence Intervals\n\nMultiple Comparisons of Means: Tukey Contrasts\n\n\nFit: glm(formula = cancer ~ variant, family = binomial, data = brca)\n\nQuantile = 2.3223\n95% family-wise confidence level\n \n\nLinear Hypotheses:\n                       Estimate lwr      upr     \nleu/leu - pro/pro == 0  0.21197 -0.22729  0.65123\npro/leu - pro/pro == 0  0.13802 -0.13074  0.40679\npro/leu - leu/leu == 0 -0.07395 -0.51338  0.36548\n```\n\n\n:::\n:::\n\n- With the `confint` function CI are obtained on the log-odds ratios corrected for multiple testing.\n\n***\n\n- CI's can be backtransformed to odds ratios:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nOR <- exp(posthocCI$confint)\nOR\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   Estimate       lwr      upr\nleu/leu - pro/pro 1.2361111 0.7966861 1.917908\npro/leu - pro/pro 1.1480000 0.8774425 1.501983\npro/leu - leu/leu 0.9287191 0.5984710 1.441205\nattr(,\"conf.level\")\n[1] 0.95\nattr(,\"calpha\")\n[1] 2.32235\n```\n\n\n:::\n:::\n\n\n- De odds ratios that we obtain is exactly equal to the one we calculated based on the contingency table:\n- e.g  $\\text{OR}_\\text{Leu/Leu-Pro/Pro}=89\\times 266/(56\\times 342)=$ 1.236.\n\n- Note, that statistical inference for logistic regression relies on asymptotic theory.\n\n***\n\n## Continuous Predictor\n\n- Toxicolocal effect of carbon disulfite (CS$_2$) on beetles.\n- Research hypothesis is there an effect of the  CS$_2$ concentration on the mortality of beetles?\n\n## Design\n- 32 independent experiments\n- Each time 1 beatle is exposed to one of 8 CS$_2$ concentrations (mg/l).\n- The outcome: mortality ($y=1$) or survival ($y=0$).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbeetles<-read_csv(\"https://raw.githubusercontent.com/statOmics/sbc/master/data/beetles.csv\")\nhead(beetles)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 2\n   dose status\n  <dbl>  <dbl>\n1  169.      1\n2  169.      0\n3  169.      0\n4  169.      0\n5  172.      1\n6  172.      0\n```\n\n\n:::\n\n```{.r .cell-code}\ntable(beetles$dose,beetles$status)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        \n         0 1\n  169.07 3 1\n  172.42 3 1\n  175.52 3 1\n  178.42 2 2\n  181.13 1 3\n  183.69 0 4\n  186.1  0 4\n  188.39 0 4\n```\n\n\n:::\n:::\n\n\n***\n\nWe build a model for the log odds in function of the dose $x_i$:\n$$\\log \\frac{\\pi_i}{1-\\pi_i}=\\beta_0+\\beta_1 \\times x_i.$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbeatleModel<-glm(status~dose,data=beetles,family=binomial)\nsummary(beatleModel)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = status ~ dose, family = binomial, data = beetles)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)   \n(Intercept) -53.1928    18.0046  -2.954  0.00313 **\ndose          0.3013     0.1014   2.972  0.00296 **\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 42.340  on 31  degrees of freedom\nResidual deviance: 26.796  on 30  degrees of freedom\nAIC: 30.796\n\nNumber of Fisher Scoring iterations: 5\n```\n\n\n:::\n:::\n\n\n----\n\n- Intercept has an interpretation of a log odds on mortality when no $\\text{CS}_2$ gas is applied.\n- Very small odds on mortality ($\\pi/(1-\\pi)=\\exp(-53.2)$) so the probability is almost 0.\n- Note that this is a very large extrapolation: minimum dose in dataset is 169.07 mg/l.\n\n\n- Estimated odds ratio for the effect of dose on the mortality probability is $\\exp(0.3013)=1.35$.\n- So a beatle exposed to a CS$_2$ concentration that is 1 mg/l larger than another beatle, will on average have an odds ratio on mortality of $1.35$.\n\n***\n\n- We conclude that this effect is very significant ($p=$ 0.003).\n- Increasing the CS$_2$ dose increases the mortality.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbeetlesTab<-table(beetles) |> data.frame()\n\ndata.frame(grid=seq(min(beetles$dose),max(beetles$dose),.1)) |> \n  mutate(piHat=predict(beatleModel,\n\t      newdata=data.frame(dose=grid),\n\t      type=\"response\")) |> \n  ggplot(aes(grid,piHat))+\n  geom_line() +\n  xlab(\"dose\") +\n  ylab(\"probability (dead)\") +\n  geom_text(aes(x=dose|>as.character()|>as.double(),y=status|>as.character()|>as.double(),label=Freq),beetlesTab|>filter(status==0)) +\ngeom_text(aes(x=dose|>as.character()|>as.double(),y=status|>as.character()|>as.double(),label=Freq),beetlesTab|>filter(status==1))\n```\n\n::: {.cell-output-display}\n![](10-categoricalDataAnalysis_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n\n\n\n***\n",
    "supporting": [
      "10-categoricalDataAnalysis_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}