{
  "hash": "06073518ff1e30afa1a4ca6376fefe87",
  "result": {
    "engine": "knitr",
    "markdown": "# Statistische besluitvorming {#sec-chap-besluit}\n\n\nAlle kennisclips die in dit hoofdstuk zijn verwerkt kan je in deze youtube playlist vinden:\n\n- [Kennisclips Hoofdstuk5 Puntschatters en Intervalschatters](https://www.youtube.com/playlist?list=PLZH1hP8_LbJKyD9Jw5cqd-btYs11f9tkz)\n\n- [Kennisclips Hoofdstuk5 Hypothesetoetsen](https://www.youtube.com/playlist?list=PLZH1hP8_LbJKEtDy2errIWf8hLJODw-jK)\n\nLink naar webpage/script die wordt gebruik in de kennisclips:\n\n\n- [script Hoofdstuk5](https://statomics.github.io/sbc/rmd/05-statisticalInference.html)\n\n- [script Hoofdstuk5: Two-sample t-test](https://statomics.github.io/sbc/rmd/05-statisticalInference-twosampleT.html)\n\n\n\n## Inleiding\n\n<iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/9bqkp6u8gWI\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n\nIn dit hoofdstuk zullen we werken rond de *Captopril dataset*.\nCaptopril is een medicijn dat wordt voorgeschreven bij hypertensie en chronisch hartfalen. Het behoort tot de klasse van ACE remmers die activiteit van het renine-angiotensine-aldosteronsysteem onderdrukken. Dat systeem zet het hormoon angiotensineI om in angiotensine II, die een krachtige vaatvernauwende werking heeft. ACE remmers verminderen de omzetting van angiotensine I naar angiotensine II waardoor de vaatvernauwing wordt onderdrukt. Tijdens de ontwikkeling van het medicijn werd een eerste kleine studie opgezet om na te gaan of captopril een bloeddrukverlagend effect heeft bij patiënten met hypertensie.\n\nObservaties bij een klein aantal subjecten mogen een onderzoeker er dan al van overtuigen iets nieuws te hebben ontdekt, maar om anderen te overtuigen zijn objectieve, wetenschappelijke argumenten nodig.\nVooreerst moeten de\nresultaten voldoende *representatief* zijn, d.w.z. veralgemeenbaar\nnaar een ruime biologische populatie (bvb. naar de volledige populatie van patiënten met hypertensie).\nTen tweede moet er rekening mee gehouden worden dat de resultaten *variabel* zijn, d.w.z. dat men\ndoor toeval doorgaans andere resultaten zou vinden indien men een andere, vergelijkbare\ngroep subjecten zou analyseren.\nOm die reden is het belangrijk om uit te drukken in welke mate de resultaten\n(bvb. de geschatte bloeddrukdaling) zouden variëren van steekproef tot steekproef en of men op basis van de steekproef kan aantonen dat er een effect  is van een behandeling (b.v. dat het middel captopril bloeddrukverlagend werkt in de populatie).\nDit vormt het doel van dit hoofdstuk.\n\nOm een representatieve groep subjecten te waarborgen, vertrekt een goede\nonderzoeksopzet vanuit een belangrijke, precies geformuleerde vraagstelling\nomtrent een duidelijk omschreven populatie.\n\nZoals eerder in de cursus aangegeven, zal men in de praktijk om financiële en logistieke redenen bijna nooit een\nvolledige populatie kunnen bestuderen.\nPopulatieparameters kunnen daarom meestal\nniet exact bepaald worden. Enkel een deel van de populatie kan onderzocht\nworden, wat men een  *steekproef* noemt. Volgens een\ngestructureerd design worden daartoe lukraak subjecten uit de doelpopulatie\ngetrokken en geobserveerd. De onbekende parameters worden vervolgens geschat\no.b.v. die steekproef en noemt men schattingen. In de praktijk hoopt men uiteraard dat de schattingen die men bekomt op basis van de steekproef vergelijkbaar zijn met de overeenkomstige populatieparameters die men voor de volledige populatie zou bekomen.  \nTypisch kan de onderzoeksvraag worden vertaald naar een populatieparameter.\nZe kan bijvoorbeeld worden uitgedrukt in termen van een populatiegemiddelde,  bijvoorbeeld de gemiddelde bloeddrukverandering na de inname van captopril bij patiënten met hypertensie.\n\n## Captopril voorbeeld\n\nOnderzoekers wensen na te gaan of het medicijn Captopril een bloeddruk verlagend effect heeft.\nDe onderzoekers wensen uitspraken te kunnen doen over het effect van captopril op de systolische bloeddruk van huidige en toekomstige patiënten met hypertensie, m.a.w. ze wensen uitspraken te doen over het effect van captopril op het niveau van de *Populatie*.\nZe zullen hiervoor een experiment opzetten om het effect van captopril bestuderen (*Proefopzet*) waarbij een *steekproef* (sample) van de patiënten met hypertensie is getrokken uit de populatie.\nVervolgens zullen ze de data exploreren en het effect van captopril besturen in de steekproef (*Data Exploratie & Beschrijvende Statistiek*). Op basis van de steekproef zullen ze dan het effect van captopril *Schatten* in de populatie en zullen ze a.d.h.v. methoden uit *Statistische besluitvorming*^[Ook wel Statistische Inferentie genoemd] nagaan in hoeverre de geobserveerde effecten in de steekproef veralgemeend kunnen worden naar de algemene populatie toe.\n\nDeze verschillende stappen worden geïllustreerd in Figuur -@fig-captoPop2Samp2Pop.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Verschillende stappen in de captopril studie.](05-StatistischeBesluitvorming_files/figure-html/fig-captoPop2Samp2Pop-1.png){#fig-captoPop2Samp2Pop fig-align='center' width=100%}\n:::\n:::\n\n\n<!---break-->\n\n### Proefopzet\n\n<iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/Wqv86oMZiHQ\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n\nBij proefopzet zullen we een gestructureerd design voorstellen om lukraak subjecten uit de doelpopulatie\nte selecteren, toe te wijzen aan een behandeling en te observeren.\nWe zullen hierbij een response variabele meten, een karakteristiek van interesse. In het captopril voorbeeld is dit de systolische bloeddruk.\n\nIn de captopril studie hebben de onderzoekers gebruik gemaakt van een pre-test/post-test design.\nDe patiënten werden at random gekozen uit de populatie.\nVan elke patiënt in de studie werd de systolische en diasystolische bloeddruk gemeten voor en na het toedienen van captopril.\nHet pre-test/post-test design heeft als voordeel dat we het effect van het toedienen van captopril op de bloeddruk kunnen meten voor elke patiënt. Een nadeel daarentegen is dat er geen controle behandeling is waardoor we een mogelijke bloeddrukverlaging niet noodzakelijkerwijs kunnen toeschrijven aan de werking van captopril. Er zou immers ook een placebo-effect kunnen optreden waardoor de bloeddruk van de patiënt daalt omdat men weet dat men een medicijn kreeg tegen een hoge bloeddruk.\n\n<!---break-->\n\n### Data Exploratie & Beschrijvende Statistiek\n\n\n<iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/F0nfCswaroE\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n\nEens de data zijn geobserveerd, is het belangrijk om deze te exploreren om inzicht te krijgen in hun verdeling en karakteristieken.\nVervolgens zullen we de gegevens samenvatten zodat we het effect van interesse kunnen kwantificeren in de steekproef.\nIn deze studie is de systolische bloeddruk en de diasystolische bloeddruk gemeten voor elke patiënt voor en na het toedienen van captopril.\nDe data is beschikbaar in een tekstbestand met naam `captopril.txt` op de github pagina <https://raw.githubusercontent.com/statOmics/sbc/master/data/captopril.txt>.\nWe zullen eerst exploreren welke figuren nuttig zijn in onze context.\nIn wetenschappelijke artikels worden vaak figuren gemaakt van het gemiddelde en de standaardafwijking (zie Figuur -@fig-captoBar).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n#Eerst lezen we de data in.\n#Deze bevindt zich in de subdirectory dataset\n#Het is een tekstbestand waarbij de kolommen van elkaar gescheiden zijn d.m.v kommas.\n#sep=\",\"\n#De eerste rij bevat de namen van de variabelen\ncaptopril <- read.table(\"https://raw.githubusercontent.com/statOmics/sbc/master/data/captopril.txt\",header=TRUE,sep=\",\")\nhead(captopril)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  id SBPb DBPb SBPa DBPa\n1  1  210  130  201  125\n2  2  169  122  165  121\n3  3  187  124  166  121\n4  4  160  104  157  106\n5  5  167  112  147  101\n6  6  176  101  145   85\n```\n\n\n:::\n\n```{.r .cell-code}\ncaptoprilTidy <- captopril |> gather(type,bp,-id)\ncaptoprilTidy |>\n  group_by(type) |>\n  summarize_at(\"bp\",list(mean=~mean(.,na.rm=TRUE),\n                    sd=~sd(.,na.rm=TRUE),\n                    n=function(x) sum(!is.na(x)))) |>\n  mutate(se=sd/sqrt(n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  type   mean    sd     n    se\n  <chr> <dbl> <dbl> <int> <dbl>\n1 DBPa   103.  12.6    15  3.24\n2 DBPb   112.  10.5    15  2.70\n3 SBPa   158   20.0    15  5.16\n4 SBPb   177.  20.6    15  5.31\n```\n\n\n:::\n\n```{.r .cell-code}\ncaptoprilTidy |>\n  group_by(type) |>\n  summarize_at(\"bp\",list(mean=~mean(.,na.rm=TRUE),\n                    sd=~sd(.,na.rm=TRUE),\n                    n=function(x) sum(!is.na(x)))) |>\n  mutate(se=sd/sqrt(n)) |>\n  ggplot(aes(x=type,y=mean)) +\n  geom_bar(stat=\"identity\") +\n  geom_errorbar(aes(ymin=mean-se, ymax=mean+se),width=.2) +\n  ylim(0,210) +\n  ylab(\"blood pressure (mmHg)\")\n```\n\n::: {.cell-output-display}\n![Barplot van de gemiddelde bloeddruk in de captopril studie. De foutenvlag is 2x de standaard deviatie op de metingen (SBPb: systolic BloodPressure before, DBPb: Diasystolic BloodPressure before, SBPa: systolic BloodPressure after, DBPa: Diasystolic BloodPressure after).](05-StatistischeBesluitvorming_files/figure-html/fig-captoBar-1.png){#fig-captoBar fig-align='center' width=100%}\n:::\n:::\n\n\nDe figuur is echter niet informatief.\nDe hoogte van de balken zegt enkel iets over het gemiddelde.\nWe kunnen onmogelijk weten wat het bereik van de ruwe gegevens is bijvoorbeeld.\nDaarom is het beter om de gegevens zo ruw mogelijk weer te geven in een plot.\nWe kunnen hiervoor bijvoorbeeld gebruik maken van boxplots (Figuur -@fig-captoBox).\nAangezien we maar over 15 patiënten beschikken kunnen we ook de ruwe datapunten toevoegen.\nIn de figuur zien we dat de systolische bloeddruk in de steekproef gemiddeld lager ligt na de behandeling met captopril.\nWe krijgen ook een duidelijk beeld op het bereik van de data.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n#toevoegen van originele datapunten op de plot\n#jitter zal de punten random verspreiden\ncaptoprilTidy |>\n  ggplot(aes(x=type,y=bp)) +\n  geom_boxplot(outlier.shape=NA) +\n  geom_point(position=\"jitter\") +\n  ylim(0,210)\n```\n\n::: {.cell-output-display}\n![Boxplot en ruwe data van de bloeddruk in de captopril studie (SBPb: systolic BloodPressure before, DBPb: Diasystolic BloodPressure before, SBPa: systolic BloodPressure after, DBPa: Diasystolic BloodPressure after).](05-StatistischeBesluitvorming_files/figure-html/fig-captoBox-1.png){#fig-captoBox fig-align='center' width=100%}\n:::\n:::\n\n\nAls alle bloeddrukmetingen onafhankelijk zouden zijn dan is Figuur -@fig-captoBox een goede figuur om de data te exploreren.\nWe weten echter dat de metingen voor en na het toedienen van captopril afkomstig zijn van dezelfde patiënt.\nWe kunnen die informatie toevoegen in een dotplot zoals we illustreren voor de systolische bloeddruk in Figuur -@fig-captoDotBsl.\nIn deze figuur zijn de twee bloeddrukmetingen voor dezelfde persoon verbonden met een lijn.\nDeze figuur geeft duidelijk weer dat de bloeddruk daalt voor elke patiënt wat een sterke aanwijzing is dat er een effect is van het toedienen van captopril op de systolische bloeddruk.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n#De geom_line layer laat ons de bloeddrukmetingen voor dezelfde personen verbinden met een lijn\ncaptoprilTidy |>\n  filter(type%in%c(\"SBPa\",\"SBPb\")) |>\n  mutate(type=factor(type,levels=c(\"SBPb\",\"SBPa\"))) |>\n  ggplot(aes(x=type,y=bp)) +\n  geom_line(aes(group = id)) +\n  geom_point()\n```\n\n::: {.cell-output-display}\n![Dotplot van de systolische bloeddruk in de captopril studie voor en na het toedienen van captopril.](05-StatistischeBesluitvorming_files/figure-html/fig-captoDotBsl-1.png){#fig-captoDotBsl fig-align='center' width=100%}\n:::\n:::\n\n\nAangezien we slechts twee bloeddrukmetingen hebben per patiënt kunnen we het effect van captopril ook berekenen per patiënt door het verschil in de systolische bloeddruk na en voor de toediening van captopril te berekenen. Dat is één van de voordelen van een pre-test/post-test design.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n#we selecteren de bloeddruk na en voor toedienen\n#uit de dataset via naam van variabele d.m.v. $-teken\n#en berekenen het verschil\ndelta <- captopril$SBPa-captopril$SBPb\ncaptopril$deltaSBP <- delta\ncaptopril |>\n  ggplot(aes(x=\"Systolic blood pressure\",y=deltaSBP)) +\n  geom_boxplot(outlier.shape=NA) +\n  geom_point(position=\"jitter\")+\n  ylab(\"Difference (mm mercury)\") +\n  xlab(\"\")\n```\n\n::: {.cell-output-display}\n![Boxplot van het verschil in systolische bloeddruk voor en na het toedienen van captopril.](05-StatistischeBesluitvorming_files/figure-html/fig-captoBoxDelta-1.png){#fig-captoBoxDelta fig-align='center' width=100%}\n:::\n:::\n\n\nWe observeren in Figuur -@fig-captoBoxDelta een bloeddrukdaling voor elke patiënt in de steekproef wat opnieuw een heel sterke indicatie is voor een gunstig effect van het toedienen van captopril op de bloeddruk.\nDe verschillen in systolische bloeddruk zijn een goede maat om het effect van captopril te bepalen.\nWe kunnen de data als volgt samenvatten.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncaptopril |>\n  summarize_at(\"deltaSBP\",list(mean=~mean(.,na.rm=TRUE),\n              sd=~sd(.,na.rm=TRUE),\n              n=function(x) sum(!is.na(x)))) |>\n  mutate(se=sd/sqrt(n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       mean       sd  n       se\n1 -18.93333 9.027471 15 2.330883\n```\n\n\n:::\n:::\n\n\nWe observeren gemiddeld een systolische bloeddrukdaling van  18.93 mmHg en een standaard deviatie van 9.03 mmHg.\n\n\n### Schatten\n\nPre-test/post-test design: Het effect van captopril in de steekproef kan worden bestudeerd door het verschil te bepalen in systolische bloeddruk na en voor de behandeling ($X=\\Delta_\\text{na-voor}$)!\nHoe kunnen we de bloeddrukverschillen modelleren en het effect van het toedienen van captopril schatten?\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![QQ-plot voor het verschil in systolische bloeddruk voor en na het toedienen van captopril.](05-StatistischeBesluitvorming_files/figure-html/fig-captoBoxDiffQQ-1.png){#fig-captoBoxDiffQQ fig-align='center' width=100%}\n:::\n:::\n\n\nWe zien geen grote afwijkingen van Normaliteit in Figuur -@fig-captoBoxDiffQQ.\nWe kunnen de bloeddrukverschillen dus modelleren aan de hand van een Normale verdeling en kunnen het effect van captopril in de populatie beschrijven a.d.h.v. de gemiddelde bloeddrukverschil $\\mu$.\nHet bloeddrukverschil $\\mu$ in de populatie kan worden geschat a.d.h.v. het steekproefgemiddelde $\\bar x$=-18.93 en de standaard afwijking $\\sigma$ a.d.h.v. de steekproefstandaarddeviatie $\\text{SD}$=9.03.\n\nWe vragen ons nu af of het effect dat we observeren in de steekproef groot genoeg is om te kunnen spreken van een effect van captopril in de populatie.\nWe weten immers dat onze statistiek voor de schatting van het effect van captopril in de populatie berekend wordt op basis van de gegevens uit de steekproef en daarom zal variëren van steekproef tot steekproef.\nHet is daarom belangrijk om een inzicht te krijgen in hoe het steekproefgemiddelde zal variëren van steekproef tot steekproef.\n\n\n## Puntschatters: het steekproefgemiddelde\n\n<iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/ISz-KvuEN2c\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n\nZij $X$ een lukrake trekking uit de populatie van de bestudeerde karakteristiek en onderstel dat haar theoretische verdeling (bvb. de Normale verdeling) een gemiddelde $\\mu$ en variatie $\\sigma^2$ heeft.\nOnderstel bovendien dat we geïnteresseerd zijn in het gemiddelde $\\mu$ van die karakteristiek in de studiepopulatie.\nDan kunnen we $\\mu$ schatten op basis van een eenvoudige lukrake steekproef, $X_1,...,X_n$, als het (rekenkundig) gemiddelde\n\n\\begin{equation*}\n\\bar X = \\frac{X_1+ X_2+ ... + X_n}{n} = \\frac{\\sum_{i=1}^{n} X_i}{n}\n\\end{equation*}\n\nvan de toevalsveranderlijken $X_1,X_2, ..., X_n$.\nDit wordt het *steekproefgemiddelde* genoemd.\nHet is belangrijk om te begrijpen dat het\nsteekproefgemiddelde opnieuw een toevalsveranderlijke^[Om die reden duiden we ze aan met een hoofdletter.] is, d.w.z. dat haar\nwaarde zal variëren van steekproef tot steekproef. Hoewel er\nslechts 1 populatie is, zijn er heel wat verschillende steekproeven die men\ndaaruit kan trekken. Dat heeft tot gevolg dat verschillende onderzoekers\n(die verschillende steekproeven uit dezelfde populatie analyseren)\nverschillende waarden zullen vinden voor het steekproefgemiddelde. Om die\nreden heeft het steekproefgemiddelde zelf een verdeling.\nMen zou die theoretisch kunnen bekomen door een oneindig aantal keer een steekproef van $n$ experimentele eenheden uit de populatie te trekken, telkens het steekproefgemiddelde te berekenen en al deze steekproefgemiddelden vervolgens uit te zetten in een histogram.\n\nWe zullen in deze sectie de theoretische verdeling van het steekproefgemiddelde bestuderen.\nDat is belangrijk (a) omdat ze ons inzicht geeft in welke mate het resultaat van de studie zou variëren indien men een nieuwe, gelijkaardige studie zou opzetten; en (b) omdat ze ons leert hoe ver $\\bar X$ van het gezochte populatiegemiddelde $\\mu$ kan afwijken.\nOmdat we slechts over 1 steekproef beschikken (en dus slechts over 1 observatie voor $\\bar X$), is het niet evident^[Zo is het met 1 observatie voor $\\bar X$ niet mogelijk om een histogram voor $\\bar X$ uit te zetten.] hoe we inzicht\nkunnen ontwikkelen in de verdeling van het steekproefgemiddelde.\nIn het vervolg van deze sectie tonen we hoe dit toch mogelijk is op basis van de\nbeschikbare steekproef wanneer we bepaalde aannames doen over de gegevens.\n\n### Overzicht\n\n\n1. Het steekproefgemiddelde is onvertekend\n2. Precisie van steekproefgemiddelde\n3. Distributie van steekproefgemiddelde\n\n\n### Het steekproefgemiddelde is onvertekend\n\nIn de praktijk hoopt men uiteraard dat de schattingen die men bekomt op basis van de steekproef vergelijkbaar zijn met de overeenkomstige populatieparameters die men voor de volledige populatie zou bekomen.  \nOf dat zo is, hangt er in eerste instantie vanaf of de steekproef representatief is voor de studiepopulatie en bijgevolg of men al dan niet lukraak individuen uit de populatie gekozen heeft ter observatie (m.a.w. het hangt af van het design van de studie).\n\nOmwille hiervan is het design van een studie van primair belang om lukrake en representatieve steekproeven te garanderen (zie Sectie -@sec-steekproefdesigns).\nZoals u doorheen deze cursus zult vaststellen, zullen de meeste wetenschappelijke rapporten daarom een gedetailleerde beschrijving geven van de manier waarop de data bekomen werden. Dit moet de lezer toelaten om de validiteit van de studie te beoordelen.\n\nAlgemeen zullen we met $E(X)$, $\\text{Var}(X)$ en $\\text{Cor}(X,Y)$\nrespectievelijk het gemiddelde, de variantie en de correlatie noteren van 2\ntoevalsveranderlijken $X$ en $Y$ in de populatie. Deze worden\nrespectievelijk de *theoretische verwachtingswaarde* van $X$, *theoretische variantie* van $X$ en *theoretische correlatie* van $X$ en $Y$ genoemd.\nMen zou ze bekomen door voor alle individuen in de populatie\nde karakteristieken $X$ en $Y$ op te meten en vervolgens respectievelijk het\nrekenkundig gemiddelde, de variantie en de Pearson correlatie te berekenen. Om die\nreden blijven de rekenregels voor gemiddelden en varianties geldig^[In principe is een meer theoretische, mathematische ontwikkeling nodig omdit aan te tonen, maar voor het bestek van deze cursus volstaat het om het\nmeer intuïtieve argument aan te nemen.] voor populatiegemiddelden en\n-varianties.\n\nIn de onderstelling dat we over een eenvoudige lukrake steekproef beschikken van metingen $X_1,...,X_n$ voor een karakteristiek $X$, volgen $X_1,...,X_n$ allen dezelfde verdeling. In het\nbijzonder hebben ze allen gemiddelde $\\mu$ en variantie $\\sigma^2$; d.i. $E(X_1)=...=E(X_n)=\\mu$ en $\\text{Var}(X_1)=...=\\text{Var}(X_n)=\\sigma^2$. Het feit\ndat we subjecten 1 tot $n$ lukraak uit de populatie getrokken hebben, staat\ner m.a.w. garant voor dat verdeling van de karakteristiek in deze steekproef\nrepresentatief is voor de theoretische verdeling in de doelpopulatie.\nGebruik makend van de rekenregels voor gemiddelden, vinden we bijgevolg dat:\n\n\\begin{eqnarray*}\nE(\\bar X) &=& E \\left(\\frac{X_1+ X_2+ ... + X_n}{n}\\right) \\\\\n&= & \\frac{E(X_1)+ E(X_2)+ ... + E(X_n)}{n} \\\\\n&=& \\frac{\\mu + \\mu + ... +\\mu}{n} \\\\\n&= & \\mu\n\\end{eqnarray*}\n\nDit geeft aan dat het verwachte steekproefgemiddelde in een eenvoudige\nlukrake steekproef gelijk is aan het beoogde populatiegemiddelde $\\mu$. Men\nzegt dan dat $\\bar X$ een *onvertekende schatter* is voor $\\mu$. We kunnen in\ndat geval verwachten dat de waarde $\\bar x$ die we schatten voor $\\mu$ op\nbasis van de steekproef, niet systematisch hoger of lager dan de gezochte waarde $\\mu$ zal zijn. Het spreekt voor zich dat dit een zeer wenselijke eigenschap is.\n\n::: {#def-onvertekende-schatter}\n## Onvertekende schatter\n\n&nbsp;\n:::\nEen statistiek of schatter $S$ voor een\nparameter $\\theta$ wordt **onvertekend** genoemd als haar theoretische\nverwachtingswaarde gelijk is aan die parameter, d.w.z. $E(S)= \\theta$.\n\n**Einde definitie**\n\n<!---break-->\n\n### Imprecisie/standard error\n\n<iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/4Tb8oPjcr3A\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n\nHet feit dat het steekproefgemiddelde (over een groot aantal vergelijkbare studies) *gemiddeld* gezien niet afwijkt van de gezochte waarde $\\mu$, impliceert niet dat ze niet rond die waarde varieert.\nOm inzicht te krijgen hoe dicht we het steekproefgemiddelde bij $\\mu$ mogen verwachten, wensen we bijgevolg ook haar variabiliteit te kennen.\n\nWe illustreren dit met de NHANES studie\n\n  - We zullen 15 vrouwen willekeurig selecteren uit de NHANES studie en zullen hun cholesterolgehalte registreren.\n  - We herhalen dit 50 keer om de variatie van steekproef tot steekproef te beoordelen\n  - We plotten de boxplot voor iedere steekproef en duiden het gemiddelde aan.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2105)\nlibrary(NHANES)\n\nfem <- NHANES |>\n  filter(Gender==\"female\" & !is.na(DirectChol)) |>\n  select(\"DirectChol\")\n\nn <- 15 # number of subjects per sample\nnSim <- 50 # number of simulations\n\nfemSamp <- matrix(nrow=n,ncol=nSim)\nfor (j in 1:nSim)\n{\n  femSamp[,j] <- sample(fem$DirectChol,15)\n  if (j<4) {\n    p <- femSamp |>\n      log2() |>\n      data.frame() |>\n      gather(\"sample\",\"log2cholesterol\") |>\n      ggplot(aes(x=sample,y=log2cholesterol)) +\n      geom_boxplot() +\n      stat_summary(\n        fun.y=mean,\n        geom=\"point\",\n        shape=19,\n        size=3,\n        color=\"red\",\n        fill=\"red\") +\n      geom_hline(yintercept = mean(fem$DirectChol |> log2())) +\n      ylab(\"cholesterol (log2)\")\n    print(p)\n  }\n}\n```\n\n::: {.cell-output-display}\n![](05-StatistischeBesluitvorming_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](05-StatistischeBesluitvorming_files/figure-html/unnamed-chunk-2-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](05-StatistischeBesluitvorming_files/figure-html/unnamed-chunk-2-3.png){width=672}\n:::\n\n```{.r .cell-code}\nfemSamp |>\n  log2() |>\n  data.frame() |>\n  gather(\"sample\",\"log2cholesterol\") |>\n  ggplot(aes(x=sample,y=log2cholesterol)) +\n  geom_boxplot() +\n  stat_summary(fun.y=mean, geom=\"point\", shape=19, size=3, color=\"red\", fill=\"red\") +\n  geom_hline(yintercept = mean(fem$DirectChol |> log2())) +\n  ylab(\"cholesterol (log2)\")\n```\n\n::: {.cell-output-display}\n![](05-StatistischeBesluitvorming_files/figure-html/unnamed-chunk-2-4.png){width=672}\n:::\n:::\n\n\nWe observeren dat het steekproefgemiddelde fluctueert rond het gemiddelde van de populatie.\n\n***\nOpdracht:\n\n1. Kopieer de code\n2. Vergroot de steekproefgrootte tot 100 proefpersonen\n3. Wat observeer je?\n***\n\n**Hoe doen we dit op basis van een enkele steekproef?**\n\nOm inzicht te krijgen in de variabiliteit op $\\bar X$ op basis van een enkele steekproef zullen we assumpties moeten maken:\n\nWe zullen ervan uitgaan dat de metingen $X_1, X_2, ..., X_n$ werden gemaakt bij $n$ *onafhankelijke*\nobservationele eenheden. In woorden betekent onafhankelijkheid dat elk subject een volledig\nnieuw stukje informatie bijdraagt tot het geheel. Een voorbeeld van\nafhankelijkheid tussen studie-objecten komt klassiek uit de studie van\nkankerverwekkende stoffen. Bij testen op zwangere ratten, worden metingen\ngedaan op hun levende foetussen of boorlingen. Foetussen van eenzelfde\nmoeder delen dezelfde genetische achtergrond en zijn daarom waarschijnlijk\nmeer aan elkaar gelijk dan foetussen van verschillende moeders. Zelfs al\nzijn de moeders die opgenomen worden in zo'n studie onafhankelijk van elkaar\ngekozen, de verschillende kleine ratjes leveren niet langer onafhankelijke\nstukjes informatie: via de gedeelde moeders is een afhankelijkheid\ningebouwd.\n\nAfhankelijke gegevens worden ondermeer ook verzameld in\npre-test/post-test designs en cross-over studies.\n\nVoor de Captopril studie bijvoorbeeld hebben we afhankelijke observaties\n\n- Bloeddrukmetingen voor ($Y_{i,before}$) en na ($Y_{i,after}$) toediening van captopril aan dezelfde patiënt $i=1,\\ldots,n$.\n- We hebben ze omgezet in n onafhankelijke metingen door het verschil $Y_{i,na}-Y_{i,voor}$ te nemen.\n\nDe volgende eigenschap illustreert de noodzaak om over onafhankelijke gegevens te beschikken,\nwil men gemakkelijk de variabiliteit van het steekproefgemiddelde kunnen bepalen.\n\n**Eigenschap**\n\nAls $X$ en $Y$ onafhankelijke toevalsveranderlijken zijn,\ndan geldt^[Merk op dat de vierkantswortel van een som niet gelijk is aan de som van de\nvierkantswortels. Bijgevolg is de standaarddeviatie van de som van $X$ en $Y$\nniet de som van de corresponderende standaarddeviaties!]:\n\n\\begin{equation*}\n\\text{Var}(X+Y) = \\text{Var}(X) + \\text{Var}(Y)\n\\end{equation*}\n\nAlgemeen (d.i. voor mogelijks afhankelijke toevalsveranderlijken $X$ en $Y$) geldt voor constanten $a$ en $b$:\n\n\\begin{eqnarray*}\n\\text{Var}(aX+bY) &=& a^2 \\text{Var}(X) + b^2 \\text{Var}(Y) + 2 ab {%\n\\text{Cor}}(X,Y)\\sqrt{\\text{Var}(X)}\\sqrt{\\text{Var}(Y)}\n\\end{eqnarray*}\n\n**Einde Eigenschap**\n\nEen veelgemaakte fout is dat men beweert dat $\\text{Var}(X-Y)=\\text{Var}(X)-\\text{Var}(Y)$. Niets is minder waar! Stel bijvoorbeeld dat de lengte $X$ van moeders en de lengte $Y$ van vaders evenveel variëren zodat $\\text{Var}(X)=\\text{Var}(Y)$. Dan impliceert dat nog niet dat als je het verschil $X-Y$ neemt tussen de lengte van een moeder en haar partner, dat dit verschil variantie nul heeft; d.w.z. dat het niet varieert en bijgevolg voor alle\nmoeder-vader paren exact dezelfde waarde aanneemt! Bovenstaande formules\ngeven inderdaad integendeel aan dat:\n\n\\begin{equation*}\n\\text{Var}(X-Y) = \\text{Var}(X) + \\text{Var}(Y) -2{\\text{Cor}}(X,Y)\\sqrt{\\text{Var}(X)}\\sqrt{\\text{Var}(Y)}.\n\\end{equation*}\n\n#### Variantie schatter voor $\\bar X$\n\nGebruik makend van deze rekenregels en steunend\nop de onafhankelijkheid van de observaties (waarvan we gebruik maken in de\nderde overgang, *) kunnen we nu verder berekenen dat:\n\n\\begin{eqnarray*}\n\\text{Var}(\\bar X)&=&\\text{Var} \\left(\\frac{X_1+ X_2+ ... + X_n}{n}\\right) \\\\\n&= & \\frac{\\text{Var} (X_1+ X_2+ ... + X_n)}{n^2} \\\\\n&\\overset{*}{=} & \\frac{\\text{Var}(X_1)+ \\text{Var}(X_2)+ ... + \\text{Var}(X_n)}{n^2} \\\\\n&=& \\frac{\\sigma^2 + \\sigma^2 + ... \\sigma^2}{n^2} \\\\\n&= & \\frac{\\sigma^2}{n}.\n\\end{eqnarray*}\n\nHet steekproefgemiddelde heeft dus een spreiding (standaarddeviatie) rond\nhaar gemiddelde $\\mu$ die $\\sqrt{n}$ keer kleiner is dan de deviatie op de\noorspronkelijke observaties. Vandaar dat we meer over $\\mu$ kunnen leren\ndoor het steekproefgemiddelde $\\bar X$ te observeren dan door een\nindividuele waarde $X$ te observeren.\n\n::: {#def-standaard-error}\n## Standaard error\n\n&nbsp;\n:::\nDe standaarddeviatie van $\\bar{X}$ is $\\sigma/\\sqrt{n}$ en krijgt in de literatuur de speciale naam {standard error} van\nhet gemiddelde. Algemeen noemt men de standaarddeviatie van een schatter\nvoor een bepaalde parameter $\\theta$, de **standard error** van die\nschatter. Men noteert dit als $SE$.\n\n**Einde definitie**\n\n\n\n::: {#exm-gemiddelde-bloeddrukverandering}\n## Gemiddelde bloeddrukverandering\n\n&nbsp;\n:::\nStel dat we $n = 15$ systolische bloeddrukobservaties zullen meten en dat de standaarddeviatie van de bloeddrukverschillen in de populatie  $\\sigma = 9.0$ mmHg bedraagt, dan is standard error (SE) van de systolische bloeddrukveranderingen $\\bar X$:\n\n$$\nSE= \\frac{9.0}{\\sqrt{15}}=2.32\\text{mmHg.}\n$$\n\nMeestal is $\\sigma$, en bijgevolg de standard error van het\nsteekproefgemiddelde, ongekend. Men moet dan de standard error schatten.\nEen voor de hand liggende schatter met goede eigenschappen is $S/\\sqrt{n},$\nwaarbij $S^2$ de *steekproefvariantie* van de reeks observaties $X_1,...,X_n$ is en $S$ de *steekproef standaarddeviatie* wordt genoemd.\n\nVoor het captopril voorbeeld kunnen we de standard error op het steekproefgemiddelde van de bloeddrukveranderingen schatten in R als\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- length(delta)\nse <- sd(delta)/sqrt(n)\nse\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.330883\n```\n\n\n:::\n:::\n\n\n\n#### Standaarddeviatie vs standard error\n\nWe illustreren dit opnieuw a.d.h.v. herhaalde steekproeven:\n\n- Verschillende steekproef groottes: 10, 50, 100\n- Neem 1000 steekproeven per steekproef grootte van de NHANES studie, voor iedere steekproef berekenen we:\n    - Het gemiddelde\n    - De steekproefstandaarddeviatie\n    - de standaard error\n- We maken een boxplot van de steekproefstandaardevaties en de standaard errors voor de verschillende steekproefgroottes\n\n- In plaats van een for loop te gebruiken zullen we de sapply functie gebruiken die efficiënter is. Het neemt een vector of lijst als invoer en past de functie toe op ieder element van de vector of lijst.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(24)\nfemSamp10 <- sapply(\n  1:1000,\n  function(j,x,size) sample(x,size),\n  size=10,\n  x=fem$DirectChol)\n\nfemSamp50 <- sapply(\n  1:1000,\n  function(j,x,size) sample(x,size),\n  size=50,\n  x=fem$DirectChol)\n\nfemSamp100 <- sapply(\n  1:1000,\n  function(j,x,size) sample(x,size),\n  size=100,\n  x=fem$DirectChol)\n\nres<-rbind(\n  femSamp10 |>\n    log2()|>\n    as.data.frame() |>\n    gather(sample,log2Chol) |>\n    group_by(sample)|>\n    summarize_at(\"log2Chol\",\n               list(median=~median(.,na.rm=TRUE),\n                    mean=~mean(.,na.rm=TRUE),\n                    sd=~sd(.,na.rm=TRUE),\n                    n=function(x) sum(!is.na(x)))) |>\n    mutate(se=sd/sqrt(n)) ,\n  femSamp50 |>\n    log2() |>  \n    as.data.frame() |>\n    gather(sample,log2Chol) |>\n    group_by(sample)|>\n    summarize_at(\"log2Chol\",\n               list(median=~median(.,na.rm=TRUE),\n                    mean=~mean(.,na.rm=TRUE),\n                    sd=~sd(.,na.rm=TRUE),\n                    n=function(x) sum(!is.na(x)))) |>\n    mutate(se=sd/sqrt(n)),\n  femSamp100 |>\n    log2() |>\n    as.data.frame() |>\n    gather(sample,log2Chol) |>\n    group_by(sample)|>\n    summarize_at(\"log2Chol\",\n               list(median=~median(.,na.rm=TRUE),\n                    mean=~mean(.,na.rm=TRUE),\n                    sd=~sd(.,na.rm=TRUE),\n                    n=function(x) sum(!is.na(x)))) |>\n    mutate(se=sd/sqrt(n))\n  )\n```\n:::\n\n**Gemiddelden**\n\nWe illustreren de impact van steekproefgrootte op de distributie van de gemiddeldes van verschillende steekproeven\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres |>\n  ggplot(aes(x= n |> as.factor(),y = mean)) +\n  geom_boxplot() +\n  ylab(\"Direct cholesterol (log2)\") +\n  xlab(\"sample size\")\n```\n\n::: {.cell-output-display}\n![](05-StatistischeBesluitvorming_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n- Merk op dat de variatie van de steekproefgemiddelden inderdaad afneemt naarmate de steekproefgrootte toeneemt. De schatting wordt dus nauwkeuriger naarmate de steekproefgrootte toeneemt.\n\n**Standard deviatie**\n\nWe illustreren nu de impact van de steekproefgrootte op de verdeling van de standaarddeviatie van de verschillende steekproeven\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres |>\n  ggplot(aes(x=n|>as.factor(),y=sd)) +\n  geom_boxplot() +\n  ylab(\"standard deviation\") +\n  xlab(\"sample size\")\n```\n\n::: {.cell-output-display}\n![](05-StatistischeBesluitvorming_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n- De standaarddeviatie blijft vergelijkbaar voor de steekproefgroottes.\nHet is gecentreerd rond dezelfde waarde: de standaarddeviatie in de populatie. Het vergroten van de steekproefgrootte heeft inderdaad geen invloed op de variabiliteit in de populatie!\n\n- Opnieuw zien we dat de variabiliteit van de standaarddeviatie afneemt naarmate de steekproefgrootte toeneemt. De standaarddeviatie kan dus ook nauwkeuriger worden geschat naarmate de steekproefgrootte toeneemt.\n\n**Standaard error van het gemiddelde**\n\nTen slotte illustreren we de impact van de steekproefgrootte op de verdeling van de standaarddeviatie van het gemiddelde van de verschillende steekproeven, de standaard error.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres |>\nggplot(aes(x=n|>as.factor(),y=se)) +\ngeom_boxplot() +\nylab(\"standard error\") +\nxlab(\"sample size\")\n```\n\n::: {.cell-output-display}\n![](05-StatistischeBesluitvorming_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n- De standaard error (de schatter voor de nauwkeurigheid van het steekproefgemiddelde) vermindert aanzienlijk naarmate de steekproefgrootte toeneemt, wat opnieuw bevestigt dat de schatting van het steekproefgemiddelde nauwkeuriger wordt.\n\n#### Normaal verdeelde gegevens\n\nAls de gegevens Normaal verdeeld zijn, dan zijn er meerdere onvertekende\nschatters voor het populatiegemiddelde $\\mu$, bvb. het steekproefgemiddelde en\nde mediaan. Men kan echter aantonen dat in dat geval het\nsteekproefgemiddelde $\\bar{X}$ de onvertekende schatter is voor $\\mu$ met de\nkleinste standard error. Dat betekent dat ze gemiddeld minder afwijkt van\nde echte parameterwaarde dan de mediaan, die veel meer\nvarieert van steekproef tot steekproef. Het steekproefgemiddelde is\nbijgevolg een schatter die accuraat is (want onvertekend) en meest precies\n(kleinste standaarddeviatie).\n\n- We illustreren dit voor herhaalde steekproeven met steekproefgrootte 10\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres |>\n  filter(n == 10) |>\n  select(mean,median) |>\n  gather(type,estimate) |>\n  ggplot(aes(x = type,y = estimate)) +\n  geom_boxplot() +\n  geom_hline(yintercept = fem$DirectChol |>\n    log2() |>\n    mean()) +\n  ggtitle(\"10 personen\")\n```\n\n::: {.cell-output-display}\n![](05-StatistischeBesluitvorming_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nVervolgens vergelijken we de verdeling van het gemiddelde en de mediaan in herhaalde steekproeven van steekproefgrootte 50.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres |>\n  filter(n == 50) |>\n  select(mean, median) |>\n  gather(type, estimate) |>\n  ggplot(aes(x = type,y = estimate)) +\n  geom_boxplot()+\n  geom_hline(yintercept = fem$DirectChol |>\n    log2() |>\n    mean()) +\n  ggtitle(\"50 personen\")\n```\n\n::: {.cell-output-display}\n![](05-StatistischeBesluitvorming_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n<!---break-->\n\n### Verdeling van het steekproefgemiddelde {#sec-verdelingXbar}\n\n<iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/YsaPNknp0Ac\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n\nOm ondermeer goed de betekenis van de standard error te kunnen vatten, moeten we van $\\bar X$ niet alleen het gemiddelde en de standaarddeviatie, maar ook de exacte verdeling kennen. De standard error is immers een standaardeviatie (bvb. van het steekproefgemiddelde), waarvan de betekenis het meest duidelijk is wanneer de metingen (in dit geval, het steekproefgemiddelde) Normaal verdeeld zijn.\nIn het bijzonder geval dat de\nindividuele observaties $X_i$ een Normale verdeling hebben met gemiddelde $\\mu$ en variantie $\\sigma^2$, kan men aantonen dat ook $\\bar X$ Normaal verdeeld is met gemiddelde $\\mu$ en variantie $\\sigma^2/n.$\n\n\n#### NHANES: cholesterol\n\nWe illustreren dit nogmaals met een simulatie gebruik makende van de NHANES-studie.\nDe log2-cholesterolwaarden zijn normaal verdeeld.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n fem |>\n  ggplot(aes(x = DirectChol |> log2()))+\n  geom_histogram(aes(y = ..density.., fill = ..count..)) +\n  xlab(\"Direct cholesterol (log2)\") +\n  stat_function(\n    fun = dnorm,\n    color = \"red\",\n    args = list(\n      mean=mean(fem$DirectChol|>log2()),\n      sd = sd(fem$DirectChol|>log2())\n      )\n    ) +\n  ggtitle(\"Alle vrouwen in NHANES studie\")\n```\n\n::: {.cell-output-display}\n![](05-StatistischeBesluitvorming_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n\n```{.r .cell-code}\nfem |>\n  ggplot(aes(sample = DirectChol |> log2())) +\n  stat_qq() +\n  stat_qq_line() +\n  ggtitle(\"Alle vrouwen in NHANES study\")\n```\n\n::: {.cell-output-display}\n![](05-StatistischeBesluitvorming_files/figure-html/unnamed-chunk-10-2.png){width=672}\n:::\n:::\n\n\n##### Evalueer de verdeling van het gemiddelde voor steekproeven van grootte 10\n\nNu onderzoeken we de resultaten voor de steekproefgrootte van 10.\n\nWe bekijken eerst de plot voor de eerste steekproef.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlog2Chol <- femSamp10[,1] |>\n  log2()\ndata.frame(log2Chol) |>\n  ggplot(aes(x=log2Chol))+\n    geom_histogram(aes(y=..density.., fill=..count..),bins=10) +\n    xlab(\"Direct cholesterol (log2)\") +\n    stat_function(\n      fun=dnorm,\n      color=\"red\",\n      args=list(\n        mean=femSamp10[,1]|>log2()|>mean(), sd=femSamp10[,1]|>log2()|>sd())\n      ) +\n    ggtitle(\"10 random females\") +\n    xlim(fem$DirectChol |> log2() |> range())\n```\n\n::: {.cell-output-display}\n![](05-StatistischeBesluitvorming_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\nVervolgens kijken we naar de verdeling van het steekproefgemiddelde over 1000 steekproeven van steekproefgrootte 10.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmeanLog2Chol <- femSamp10 |>\n  log2() |>\n  colMeans()\ndata.frame(meanLog2Chol) |>\n  ggplot(aes(x=meanLog2Chol)) +\n  geom_histogram(aes(y=..density.., fill=..count..),bins=15) +\n  xlab(\"Mean cholesterol (log2)\") +\n  stat_function(\n    fun=dnorm,\n    color=\"red\",\n    args=list(\n      mean=femSamp10|>log2()|> colMeans() |> mean(),\n      sd=femSamp10|>log2()|> colMeans() |> sd())\n    ) +\n  ggtitle(\"Means on 10 females\")\n```\n\n::: {.cell-output-display}\n![](05-StatistischeBesluitvorming_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n\n```{.r .cell-code}\nmeanLog2Chol <- femSamp10 |>\n  log2()|>\n  colMeans()\ndata.frame(meanLog2Chol) |>\n  ggplot(aes(sample=meanLog2Chol)) +\n  stat_qq() +\n  stat_qq_line() +\n  ggtitle(\"Means on 10 females\")\n```\n\n::: {.cell-output-display}\n![](05-StatistischeBesluitvorming_files/figure-html/unnamed-chunk-12-2.png){width=672}\n:::\n:::\n\n\n**We hebben dus bevestigd dat het gemiddelde ongeveer normaal verdeeld is voor studies met 10 vrouwen, terwijl de originele gegevens ongeveer normaal verdeeld zijn.**\n\n#### Captopril studie\n\nIn het captopril voorbeeld zagen we dat de systolische bloeddrukverandering approximatief normaal verdeeld is.\nDe standard error op de bloeddrukverandering bedroeg 2.33 mm Hg.\nDus op 100 studies met n = 15 subjecten, verwachten we dat de geschatte gemiddelde systolische bloeddrukafwijking ($\\bar X$) op minder dan 2 × 2.33 = 4.66mm Hg van het werkelijke populatiegemiddelde ($\\mu$) ligt in 95 studies.\n\n#### Niet-normaal verdeelde data\n\nAls individuele observaties geen normale verdeling hebben,  is $\\bar X$ nog steeds \\textit{ongeveer} normaal verdeeld\nwanneer het aantal observaties groot genoeg is.\n\nHoe groot moet de steekproef zijn om de normale benadering te laten werken hangt af van de scheefheid van de distributie!\n\n##### NHANES: cholesterol\n\n- We kunnen dit evalueren in de NHanes-studie als we de gegevens niet log2 transformeren.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfem |>\n   ggplot(aes(x=DirectChol))+\n   geom_histogram(aes(y=..density.., fill=..count..)) +\n   xlab(\"Direct cholesterol\") +\n   stat_function(\n     fun=dnorm,\n     color=\"red\",\n     args=list(\n       mean=mean(fem$DirectChol),\n       sd=sd(fem$DirectChol))\n    ) +\n   ggtitle(\"All females in Nhanes study\")\n```\n\n::: {.cell-output-display}\n![](05-StatistischeBesluitvorming_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n\n```{.r .cell-code}\n fem |>\n  ggplot(aes(sample=DirectChol)) +\n  stat_qq() +\n  stat_qq_line() +\n  ggtitle(\"All females in Nhanes study\")\n```\n\n::: {.cell-output-display}\n![](05-StatistischeBesluitvorming_files/figure-html/unnamed-chunk-13-2.png){width=672}\n:::\n:::\n\n\nDe cholesterol data zijn duidelijk niet-normaal verdeeld.\n\n**Verdeling van het steekproefgemiddelde voor verschillende steekproefgroottes**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(121)\nfemSamp5 <- sapply(\n  1:1000,\n  function(j,x,size) sample(x,size),\n  size = 5,\n  x = fem$DirectChol)\n\nmeanChol <- femSamp5 |>\n  colMeans()\ndata.frame(meanChol) |> ggplot(aes(x=meanChol)) +\n  geom_histogram(aes(y=..density.., fill=..count..),bins=15) +\n  xlab(\"Mean cholesterol\") +\n  stat_function(\n    fun=dnorm,\n    color=\"red\",\n    args=list(\n      mean=femSamp5|> colMeans() |> mean(),\n      sd=femSamp5|> colMeans() |> sd())\n    ) +\n  ggtitle(\"Means on 5 females\")\n```\n\n::: {.cell-output-display}\n![](05-StatistischeBesluitvorming_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n\n```{.r .cell-code}\nmeanChol <- femSamp5 |>\n  colMeans()\ndata.frame(meanChol) |>\n  ggplot(aes(sample=meanChol)) +\n  stat_qq() +\n  stat_qq_line() +\n  ggtitle(\"Means on 5 females\")\n```\n\n::: {.cell-output-display}\n![](05-StatistischeBesluitvorming_files/figure-html/unnamed-chunk-14-2.png){width=672}\n:::\n\n```{.r .cell-code}\nmeanChol <- femSamp10 |>\n  colMeans()\ndata.frame(meanChol) |> ggplot(aes(x=meanChol)) +\n  geom_histogram(aes(y=..density.., fill=..count..),bins=15) +\n  xlab(\"Mean cholesterol\") +\n  stat_function(\n    fun=dnorm,\n    color=\"red\",\n    args=list(\n      mean=femSamp10|> colMeans() |> mean(),\n      sd=femSamp10|> colMeans() |> sd())\n    ) +\nggtitle(\"Means on 10 females\")\n```\n\n::: {.cell-output-display}\n![](05-StatistischeBesluitvorming_files/figure-html/unnamed-chunk-14-3.png){width=672}\n:::\n\n```{.r .cell-code}\nmeanChol <- femSamp10 |>\n  colMeans()\ndata.frame(meanChol) |>\n  ggplot(aes(sample=meanChol)) +\n  stat_qq() +\n  stat_qq_line() +\n  ggtitle(\"Means on 10 females\")\n```\n\n::: {.cell-output-display}\n![](05-StatistischeBesluitvorming_files/figure-html/unnamed-chunk-14-4.png){width=672}\n:::\n\n```{.r .cell-code}\nmeanChol <- femSamp50 |>\n  colMeans()\ndata.frame(meanChol) |>\n  ggplot(aes(sample=meanChol)) +\n  stat_qq() +\n  stat_qq_line() +\n  ggtitle(\"Means on 50 females\")\n```\n\n::: {.cell-output-display}\n![](05-StatistischeBesluitvorming_files/figure-html/unnamed-chunk-14-5.png){width=672}\n:::\n\n```{.r .cell-code}\nmeanChol <- femSamp100 |>\n  colMeans()\ndata.frame(meanChol) |>\n  ggplot(aes(sample=meanChol)) +\n  stat_qq() +\n  stat_qq_line() +\n  ggtitle(\"Means on 100 females\")\n```\n\n::: {.cell-output-display}\n![](05-StatistischeBesluitvorming_files/figure-html/unnamed-chunk-14-6.png){width=672}\n:::\n:::\n\n\n**We merken op dat wanneer de data niet normaal verdeeld zijn, de verdeling van het steekproefgemiddelde niet normaal verdeeld is over kleine steekproeven**\n\n**Voor grote steekproeven is het steekproefgemiddelde van niet-normale gegevens echter nog steeds ongeveer normaal verdeeld.**\n\n\n#### Centrale Limietstelling (CLT)\n\nStel dat $X_1, X_2, \\dots, X_n, \\; n$ onafhankelijke lukrake trekkingen van\nde toevalsveranderlijke $X$ voorstellen, met allen dezelfde theoretische\nverdeling. Laat $X$ gemiddelde $\\mu$ en variantie $\\sigma^2$ hebben maar\nverder een ongespecifieerde verdeling, dan wordt de verdeling van het\nsteekproefgemiddelde $\\bar{X}_n = {\\sum_{i=1}^{n} X_i}/{n}$ naarmate $n$\ngroter wordt steeds beter benaderd door de Normale verdeling met gemiddelde $\\mu$ en variantie $\\sigma^2/n.$\n\n**Einde Stelling**\n\nDeze belangrijke eigenschap zal ons toelaten om de meeste technieken die in deze cursus aan bod komen toe te passen op een zeer uitgebreid spectrum van experimenten.\n\n## Intervalschatters\n\n<iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/KIXbdKudFH8\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n\nIn de vorige sectie hebben we vastgesteld dat het steekproefgemiddelde  van\nsteekproef tot steekproef varieert rond het populatiegemiddelde dat we\nwillen schatten.\nOm die reden wensen we in deze sectie een interval rond het\nsteekproefgemiddelde te bepalen waarbinnen we het populatiegemiddelde met\ngegeven kans (bvb. 95\\% kans) kunnen verwachten.\nIn Sectie -@sec-bigek zullen we dit  uitwerken voor het geval waar de populatievariantie $\\sigma^2$\nop de metingen gekend is.\nDeze onderstelling is meestal onredelijk^[Denk zelf maar eens na of je gevallen kunt bedenken waar je al op voorhand,\nzonder ook maar observaties te zien, de variantie op een bepaalde\nkarakteristiek kent...], maar wordt hier gemaakt om redenen van eenvoud.\nIn Sectie -@sec-tBI zullen we van deze onderstelling afstappen.\n\n### Gekende variantie op de metingen {#sec-bigek}\nWanneer de individuele observaties $X$ Normaal verdeeld zijn met gemiddelde $\\mu$ en gekende variantie $\\sigma^2$, noteren we dat als volgt: $X\\sim N(\\mu,\\sigma^2)$.\nUit vorige sectie volgt dan dat het steekproefgemiddelde $\\bar{X}$ eveneens Normaal verdeeld is volgens $N(\\mu,\\sigma^2/n)$. Een 95% referentie-interval voor het steekproefgemiddelde ziet er bijgevolg uit als\n\n\\begin{equation*}\n\\left[\\mu - 1.96 \\frac{\\sigma}{\\sqrt{n}},\\mu + 1.96 \\frac{\\sigma}{\\sqrt{n}}%\n\\right]\n\\end{equation*}\n\nHet bevat met 95% kans het steekproefgemiddelde van een lukrake\nsteekproef. Dit interval kunnen we niet expliciet berekenen op basis van de\ngeobserveerde gegevens, omdat $\\mu$ ongekend is (we gaan er hier voorlopig\nvan uit dat $\\sigma$ wel gekend is). Het kan wel geschat worden als\n\n\\begin{equation*}\n\\left[\\bar X - 1.96 \\frac{\\sigma}{\\sqrt{n}},\\bar X + 1.96 \\frac{\\sigma}{\\sqrt{n}}\\right]\n\\end{equation*}\n\nHoewel dit laatste interval nog steeds kan geïnterpreteerd worden als\neen referentie-interval voor het steekproefgemiddelde, kunnen we er een veel\nnuttigere interpretatie aan geven. Immers, de ongelijkheid $\\mu - 1.96 \\\n\\sigma/\\sqrt{n} < \\bar{X}$ kan equivalent worden herschreven als $\\mu < \\bar{X} + 1.96 \\ \\sigma/\\sqrt{n}$. Hieruit volgt:\n\n\\begin{eqnarray*}\n95\\% &=& P( \\mu - 1.96 \\ \\sigma/\\sqrt{n} < \\bar{X} < \\mu + 1.96 \\ \\sigma/\\sqrt{n} ) \\\\\n&=&P( \\bar{X} - 1.96 \\ \\sigma/\\sqrt{n} < \\mu < \\bar{X} + 1.96 \\ \\sigma/\\sqrt{n} )\n\\end{eqnarray*}\n\nDit leidt tot volgende definitie.\n\n::: {#def-95-procent-betrouwbaarheidsinterval-voor-populatiegemiddelde}\n## 95 procent betrouwbaarheidsinterval voor populatiegemiddelde\n\n&nbsp;\n:::\nHet interval\n\n$$\n\\left[\\bar X - 1.96 \\frac{\\sigma}{\\sqrt{n}},\\bar X + 1.96 \\frac{\\sigma}{\\sqrt{n}}\\right]\n$$ {#eq-bi}\n\nbevat met 95% kans het populatiegemiddelde $\\mu$. Het wordt een **95% betrouwbaarheidsinterval** (in het Engels: *95% confidence interval*) voor het populatiegemiddelde $\\mu$ genoemd. De kans dat het de populatieparameter $\\mu$\nbevat, d.i. 95%, wordt het *betrouwbaarheidsniveau* genoemd.\n\n**Einde definitie**\n\nEen 95% betrouwbaarheidsinterval bepaalt met andere woorden een reeks\nwaarden waarbinnen de gezochte populatieparameter *waarschijnlijk*\n(namelijk met 95% kans) valt.\n\nStel dat we in een steekproef een bloeddrukdaling van -18.93mmHg observeren en dat we weten dat de standaarddeviatie van de bloeddrukmetingen 9mmHg bedraagt. Dan vinden we een betrouwbaarheidsinterval voor de gemiddelde bloeddrukdaling van\n$$\\left[-18.93-1.96\\times 9/\\sqrt{15},-18.93+1.96\\times 9/\\sqrt{15}\\right]=[-23.48,-14.38]mmHg$$\n\n\nDe reden waarom over \"95% kans\" gesproken wordt, is omdat de eindpunten van\nhet 95% betrouwbaarheidsinterval toevalsveranderlijken zijn die variëren\nvan steekproef tot steekproef. Met andere woorden, verschillende\nsteekproeven leveren telkens andere betrouwbaarheidsintervallen op, vermits\ndie intervallen berekend zijn op basis van de gegevens in de steekproef. Men\nnoemt het om die reden *stochastische intervallen*.\nVoor 95% van alle steekproeven zal het berekende 95% betrouwbaarheidsinterval de\ngezochte waarde van de populatieparameter bevatten, en voor de overige 5%\nniet. Dat wordt geïllustreerd a.d.h.v. een simulatiestudie in Sectie -@sec-interpretBI (nadat we de intervallen hebben uitgebreid voor de meer realistische setting waarbij de variantie in de populatie ongekend is).\n\nUiteraard kunnen de onderzoekers o.b.v. een gegeven betrouwbaarheidsinterval\nniet besluiten of het de gezochte parameterwaarde bevat of niet, vermits ze\nprecies op zoek zijn naar die onbekende waarde. Maar ze gebruiken een\nprocedure die in 95% van de gevallen werkt; m.a.w. die in 95% van de\ngevallen de gezochte waarde bevat. Of nog, als men dagelijks gegevens zou\nverzamelen en telkens een 95% betrouwbaarheidsinterval zou berekenen voor\neen nieuwe parameter $\\theta$ (bvb. een odds ratio), dan zou men op lange termijn in 95% van de gevallen de gezochte waarde omvat hebben.\n\nTot nog toe zijn we ervan uitgegaan dat de individuele observaties Normaal verdeeld zijn en dat hun variantie gekend is (want als de variantie $\\sigma^2$ niet gekend is, kan men de grenzen van het interval niet berekenen).\nWegens de Centrale Limietstelling bevat Vergelijking -@eq-bi het gemiddelde $\\mu$\nbij benadering met 95% kans wanneer de steekproef groot is en de variantie\nvan de individuele observaties gekend, maar hun verdeling ongekend is.\n\nWanneer bovendien de variantie ongekend is, kan me ze schatten door gebruik te maken van de\nsteekproefvariantie $S^2$ van de reeks observaties $X_1,...,X_n$. Men kan aantonen dat\nhet interval $[\\bar{X} - 1.96 \\ s/\\sqrt{n} , \\bar{X} + 1.96 \\ s/\\sqrt{n} ]$\ndan het populatiegemiddelde met bij benadering 95% kans bevat, op voorwaarde\ndat de steekproef groot is. In de volgende sectie gaan we na hoe een\nbetrouwbaarheidsinterval voor het populatiegemiddelde geconstrueerd kan\nworden wanneer de variantie ongekend is en de steekproef relatief klein.\n\n\n#### NHANES log2 cholesterol voorbeeld\n\n##### 1 steekproef\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(3146)\nsamp50 <- sample(fem$DirectChol,50)\n\nll <- mean(samp50 |> log2()) - 1.96*sd(samp50 |> log2())/sqrt(50)\nul <- mean(samp50 |> log2()) + 1.96*sd(samp50 |> log2())/sqrt(50)\npopMean <- mean(fem$DirectChol|>log2())\n\nc(ll=ll,ul=ul,popMean=popMean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       ll        ul   popMean \n0.4326245 0.6291622 0.5142563 \n```\n\n\n:::\n:::\n\n\nBij 1 steekproef ligt het populatiegemiddelde binnen het BI of niet.\n\n##### Herhaalde steekproeven\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres$ll <- res$mean-1.96*res$se\nres$ul <- res$mean+1.96*res$se\nmu <- fem$DirectChol|>\n  log2()|>\n  mean()\n\nres$inside<- res$ll <= mu & mu <= res$ul\nres$n <- as.factor(res$n)\nres |>\n  group_by(n) |>\n  summarize(coverage=mean(inside)) |>\n  spread(n,coverage)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n   `10`  `50` `100`\n  <dbl> <dbl> <dbl>\n1  0.92 0.942 0.954\n```\n\n\n:::\n:::\n\n\n- Merk op dat de omvang in de steekproeven met 10 waarnemingen te laag is omdat we geen rekening houden met de onzekerheid in de schatting van de standaarddeviatie.\n\n- Als we kijken naar de eerste 20 intervallen, bevat 1  van de 20 niet het populatiegemiddelde.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres |>\n  filter(n==10) |>\n  slice(1:20) |>\n  ggplot(aes(x = sample,y = mean,color = inside)) +\n  geom_point() +\n  geom_errorbar(aes(ymin = mean-1.96*se,ymax = mean+1.96*se))+\n  geom_hline(yintercept = fem$DirectChol |> log2() |> mean()) +\n  ggtitle(\"20 CI for N = 10\") +\n  ylim(range(fem$DirectChol |> log2()))\n```\n\n::: {.cell-output-display}\n![](05-StatistischeBesluitvorming_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n***\n\n- Voor grote steekproeven (100) is de omvang prima omdat we de standaarddeviatie met een relatief hoge precisie kunnen schatten.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres |>\n  filter(n == 50) |>\n  slice(1:20) |>\n  ggplot(aes(x = sample,y = mean,color = inside)) +\n  geom_point() +\n  geom_errorbar(aes(ymin = mean-1.96*se,ymax = mean+1.96*se))+\n  geom_hline(yintercept = fem$DirectChol |> log2() |> mean()) +\n  ggtitle(\"20 CI for N = 50\") +\n  ylim(range(fem$DirectChol |> log2()))\n```\n\n::: {.cell-output-display}\n![](05-StatistischeBesluitvorming_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n\n```{.r .cell-code}\nres |>\n  filter(n == 100) |>\n  slice(1:20) |>\n  ggplot(aes(x = sample,y = mean,color = inside)) +\n  geom_point() +\n  geom_errorbar(aes(ymin = mean-1.96*se,ymax = mean+1.96*se))+\n  geom_hline(yintercept = fem$DirectChol |> log2() |> mean()) +\n  ggtitle(\"20 CI for N = 100\") +\n  ylim(range(fem$DirectChol |> log2()))\n```\n\n::: {.cell-output-display}\n![](05-StatistischeBesluitvorming_files/figure-html/unnamed-chunk-18-2.png){width=672}\n:::\n:::\n\n\n- Wat heb je geobserveerd voor de intervalbreedte?\n\n#### Andere betrouwbaarheidsniveaus\n\nOm een betrouwbaarheidsinterval met een ander betrouwbaarheidsniveau, $(1-\n\\alpha)100\\%$ te construeren, vervangt men 1.96 door het relevante kwantiel $z_{\\alpha/2}.$\n\nDe breedte van een $100\\%(1-\\alpha)$ betrouwbaarheidsinterval voor een\npopulatiegemiddelde $\\mu$ is $2 z_{\\alpha/2} \\ \\sigma/\\sqrt{n}$. Ze wordt\ndus bepaald door 3 factoren: de standaarddeviatie op de individuele\nobservaties, $\\sigma$, de grootte van de steekproef, $n$, en het\nbetrouwbaarheidsniveau, $1-\\alpha$:\n\n- $n$: naarmate de steekproefgrootte toeneemt, krimpt het\nbetrouwbaarheidsinterval. In grote steekproeven beschikken we immers over veel informatie en kunnen we de gezochte populatieparameter bijgevolg relatief nauwkeurig afschatten.\n\n- $\\sigma$: naarmate de standaarddeviatie van de oorspronkelijke\nobservaties toeneemt, neemt de lengte van het betrouwbaarheidsinterval toe. Indien er immers veel ruis op de gegevens zit, dan is het moeilijker om populatieparameters of -kenmerken te identificeren.\n\n- $1-\\alpha$: naarmate het betrouwbaarheidsniveau toeneemt, wordt het\nbetrouwbaarheidsinterval breder. Indien we immers eisen dat het interval met 99.9\\% kans de populatiewaarde bevat i.p.v. met 80\\% kans, dan zullen we duidelijk een breder interval nodig hebben.\n\nBetrouwbaarheidsintervallen worden niet enkel gebruikt voor het\npopulatiegemiddelde, maar kunnen in principe voor om het even welke\npopulatieparameter worden gedefinieerd. Zo kunnen ze bijvoorbeeld\ngedefinieerd worden voor een verschil tussen 2 gemiddelden, voor een odds ratio, voor een variantie, ... De manier om die\nintervallen te berekenen is vaak complex en sterk afhankelijk van de\ngebruikte schatter voor de populatieparameter. Er wordt daarom niet van u\nverwacht dat u voor alle populatieparameters die we in deze cursus\nontmoeten, een betrouwbaarheidsinterval kunt berekenen, maar wel dat u het\nkunt interpreteren.\n\n::: {#def-betrouwbaarheidsinterval}\n## Betrouwbaarheidsinterval\n\n&nbsp;\n:::\nEen **$(1-\\alpha)100$% betrouwbaarheidsinterval** voor een populatieparameter $\\theta$ is een\ngeschat (en bijgevolg stochastisch) interval dat met $(1-\\alpha)100$% kans\nde echte waarde van die populatieparameter $\\theta$ bevat.\n\n**Einde Definitie**\n\n\n\n<!---break-->\n\n### Ongekende variantie op de metingen {#sec-tBI}\n\n<iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/IPSXJj8jyr8\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n\nTot nog toe werd verondersteld dat de populatievariantie $\\sigma^2$ gekend is bij het berekenen van een betrouwbaarheidsinterval voor $\\mu$.\nBetrouwbaarheidsintervallen voor $\\mu$ werden dan opgebouwd door op te\nmerken dat de gestandaardiseerde waarde $(\\bar{X} - \\mu)/(\\sigma/\\sqrt{n})$\nstandaardnormaal verdeeld is en bijgevolg\n\n\\begin{equation*}\n\\left[\\mu - 1.96 \\frac{\\sigma}{\\sqrt{n}},\\mu + 1.96 \\frac{\\sigma}{\\sqrt{n}}%\n\\right]\n\\end{equation*}\n\neen 95% referentie-interval voor het steekproefgemiddelde voorstelt.\n\nIn de praktijk komt het quasi nooit voor dat men de populatievariantie $\\sigma^2$ exact kent. In de praktijk wordt deze geschat als $S^2$ op basis van de voorhanden zijnde steekproef. Als gevolg hiervan zullen de betrouwbaarheidsintervallen uit voorgaande sectie doorgaans iets te smal zijn (omdat ze er geen rekening mee houden dat ook de variantie werd geschat) en is het\nnoodzakelijk om bij de berekening $(\\bar{X} - \\mu)/(S/\\sqrt{n})$ te\ngebruiken als gestandaardiseerde waarde i.p.v. $(\\bar{X} - \\mu)/(\\sigma/\\sqrt{n})$. Wanneer de steekproef voldoende groot is, ligt de vierkantswortel van variantie $S^2$ voldoende dicht bij $\\sigma$ zodat ${(\\bar{X} - \\mu)}/{(S/\\sqrt{n}) }$ bij benadering een standaardnormale verdeling volgt en, bijgevolg,\n\n$$\n\\left[\\bar{X} - z_{\\alpha/2} \\ \\frac{S}{\\sqrt{n}} , \\bar{X} + z_{\\alpha/2} \\\n\\frac{S}{\\sqrt{n}}\\right]\n$$\n\neen benaderd $(1- \\alpha)100\\%$ betrouwbaarheidsinterval is voor $\\mu$. Voor\nkleine steekproeven is dit niet langer het geval. Daardoor introduceert men\neen extra onnauwkeurigheid in de gestandaardiseerde waarde ${(\\bar{X} - \\mu)}/{(S/\\sqrt{n})}$. Deze is nog wel gecentreerd rond nul en symmetrisch, maar niet langer Normaal verdeeld. De echte verdeling voor eindige\nsteekproefgrootte $n$ heeft zwaardere staarten dan de Normale. Hoeveel\nzwaarder de staarten zijn, hangt van de steekproefgrootte $n$ af. Als $n$\noneindig groot wordt, komt $S$ zodanig dicht bij $\\sigma$ te liggen dat de\nextra onnauwkeurigheid in de gestandaardiseerde waarde verwaarloosbaar is en\nbijgevolg ook het verschil met de Normale verdeling. Maar voor relatief\nkleine steekproeven hangt de verdeling van ${(\\bar{X} - \\mu)}/({S/\\sqrt{n}})$ af van de grootte $n$ van de steekproef. Ze krijgt de naam (Student) $t$-verdeling met $n-1$ vrijheidsgraden (in het Engels: *degrees of freedom*). Deze verdeling wordt voor een aantal verschillende vrijheidsgraden geïllustreerd in Figuur -@fig-tdist.\nDe t-verdelingen in de figuur hebben duidelijk bredere staarten dan de normaalverdeling, waardoor ze ook een grotere percentielwaarden hebben voor een vooropgesteld betrouwbaarheidsniveau.\nDat zal leiden tot bredere intervallen, wat logisch is aangezien we de extra onzekerheid inbouwen die gerelateerd is aan het schatten van de standaarddeviatie.\n\n::: {#def-t-verdeling}\n## t-verdeling\n\n&nbsp;\n:::\nAls $X_1, X_2, ..., X_n$ een steekproef vormen uit de Normale verdeling $N(\\mu, \\sigma^2)$, dan is $(\\bar{X} - \\mu)/(S/\\sqrt{n})$ verdeeld als een $t$-verdeling met $n-1$ vrijheidsgraden.\n\n**Einde Definitie**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ngrid <- seq(-5,5,.1)\ndensDist <- cbind(grid,dnorm(grid), sapply(c(2,5,10),dt,x=grid))\ncolnames(densDist) <- c(\"x\",\"normal\",paste0(\"t\",c(2,5,10)))\n\ndensDist |>\n  as.data.frame() |>\n  gather(dist,dens,-x) |>\n  ggplot(aes(x=x,y=dens,color=dist)) +\n  geom_line() +\n\txlab(\"x\") +\n  ylab(\"Densiteit\")\n```\n\n::: {.cell-output-display}\n![Normale verdeling en t-verdeling met verschillende vrijheidsgraden.](05-StatistischeBesluitvorming_files/figure-html/fig-tdist-1.png){#fig-tdist fig-align='center' width=100%}\n:::\n:::\n\n\nPercentielen van de $t$-verdeling kunnen niet met de hand berekend worden,\nmaar kan men voor de verschillende waarden van $n$ aflezen in Tabellen of berekenen in R.\nIn de onderstaande code wordt het 95%, 97.5%, 99.5% percentiel berekend voor een t-verdeling met 14 vrijheidsgraden, die gebruik kunnen worden voor de berekening van 90%, 95% en 99% betrouwbaarheidsintervallen.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqt(.975,df=14)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.144787\n```\n\n\n:::\n\n```{.r .cell-code}\nqt(c(.95,.975,.995),df=14)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.761310 2.144787 2.976843\n```\n\n\n:::\n:::\n\nWe zien dat het 97.5% percentiel 2.14 voor een t-verdeling met $n-1=14$ vrijheidsgraden inderdaad groter is dan het kwantiel uit de normaal verdeling 1.96.\n\nEen gelijkaardige logica als voor de Normale verdeling met gekende variantie, geeft dan aan dat een $100\\% (1-\\alpha)$ betrouwbaarheidsinterval voor het gemiddelde $\\mu$ van een\nNormaal verdeelde veranderlijke $X$ met onbekende variantie kan berekend\nworden als\n\n\\begin{equation*}\n\\left[\\bar{X} - t_{n-1, \\alpha/2} \\frac{s}{\\sqrt{n}} , \\bar{X} + t_{n-1,\n\\alpha/2} \\frac{s}{\\sqrt{n}}\\right]\n\\end{equation*}\n\nDeze uitdrukking verschilt van deze in de vorige sectie doordat het $(1-\\alpha/2)100\\%$ percentiel van de Normale verdeling wordt vervangen door\nhet $(1-\\alpha/2)100\\%$ percentiel van de t-verdeling met $n-1$\nvrijheidsgraden.\n\n#### Captopril voorbeeld\n\nVoor het captopril voorbeeld kunnen we dus een 95% betrouwbaarheidsinterval bekomen door\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(delta) -  qt(.975,df=14)*sd(delta)/sqrt(n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -23.93258\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(delta) + qt(.975,df=14)*sd(delta)/sqrt(n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -13.93409\n```\n\n\n:::\n:::\n\n\nEen 99% betrouwbaarheidsinterval voor gemiddelde bloeddrukverandering wordt als volgt bekomen:\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(delta) -  qt(.995,df=14)*sd(delta)/sqrt(n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -25.87201\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(delta) + qt(.995,df=14)*sd(delta)/sqrt(n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -11.99466\n```\n\n\n:::\n:::\n\n\n\n\n### Interpretatie van betrouwbaarheidsintervallen {#sec-interpretBI}\n\nWe zullen opnieuw steekproeven trekken van de grote NHANES studie en deze keer BI's bestuderen voor log2-cholesterol steekproefwaarden. We voeren eerst herhaalde experimenten uit met steekproefgrootte 10.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres$n <- as.character(res$n) |>\n  as.double(res$n)\n\nres$ll <- res$mean-qt(0.975,df=res$n-1)*res$se\nres$ul <- res$mean+qt(0.975,df=res$n-1)*res$se\n\nmu <- fem$DirectChol|>log2()|>mean()\n\nres$inside <- res$ll<=mu & mu<=res$ul\nres$n <- as.factor(res$n)\n\nres |>\n  group_by(n) |>\n  summarize(coverage=mean(inside)) |>\n  spread(n,coverage)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n   `10`  `50` `100`\n  <dbl> <dbl> <dbl>\n1 0.949 0.947 0.959\n```\n\n\n:::\n:::\n\n\nWe zien dat de omvang van de intervallen nu worden gecontroleerd op hun nominale betrouwbaarheidsniveau van 95%.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres |>\n  filter(n==10) |>\n  slice(1:20) |>\n  ggplot(aes(x=sample,y=mean,color=inside)) +\n  geom_point() +\n  geom_errorbar(\n    aes(ymin=mean-qt(0.975,df=9)*se,\n    ymax=mean+qt(0.975,df=9)*se))+\n  geom_hline(yintercept = fem$DirectChol |> log2() |> mean()) +\n  ggtitle(\"20 CI for N=10\") +\n  ylim(range(fem$DirectChol |> log2()))\n```\n\n::: {.cell-output-display}\n![Interpretatie van 95$\\%$ betrouwbaarheidintervallen. Resultaten op basis van 20 gesimuleerde steekproeven. We zien in de figuur duidelijk dat het populatiegemiddelde vast is maar ongekend (volle zwarte lijn) en dat de bovengrens en ondergrens van betrouwbaarheidsintervallen voor het populatiegemiddelde varieert van steekproef tot steekproef.](05-StatistischeBesluitvorming_files/figure-html/fig-biInterpret-1.png){#fig-biInterpret width=672}\n:::\n:::\n\n\nDe simulatiestudie toont dus op een empirische wijze aan dat de constructie correct is.\nHet demonstreert bovendien de interpretatie van probabiliteit via herhaalde steekproefname.\nIn Figuur -@fig-biInterpret wordt de interpretatie ook grafisch weergegeven voor de eerste 20 gesimuleerde steekproeven. De figuur toont duidelijk aan dat het werkelijke populatiegemiddelde vast is maar ongekend. Het wordt geschat aan de hand van het steekproefgemiddelde dat at random varieert van steekproef tot steekproef rond het werkelijk gemiddelde.\nWe zien ook dat de grenzen van de betrouwbaarheidsintervallen variëren van steekproef tot steekproef.\nDaarnaast varieert de breedte van de betrouwbaarheidsintervallen eveneens omdat de steekproefstandaarddeviatie eveneens varieert van steekproef tot steekproef^[De steekproefstandaarddeviatie is eveneens een toevallig veranderlijke die van steekproef tot steekproef varieert rond werkelijke standaarddeviatie. Hierdoor zal de breedte van de intervallen eveneens variëren].\n\nIn de praktijk zullen  we op basis van 1 steekproef besluiten dat het betrouwbaarheidsinterval het populatiegemiddelde bevat en we weten dat dergelijke uitspraken met een kans van $1-\\alpha$ (hier 95%) correct zijn.\n\n***\n\n**Opdracht**\n\nVoer de bovenstaande simulatie studie opnieuw uit maar verdubbel de steekproefgrootte. Welke impact heeft dit op de BIs?\n\n***\n\n<!---break-->\n\n\n### Wat rapporteren?\n\nRapporteer dus zeker steeds de onzekerheid op de resultaten! Conclusies trekken op basis van 1 schatting kan zeer misleidend zijn! In statistische analyses rapporteert men daarom systematisch betrouwbaarheidsintervallen.\nBetrouwbaarheidsintervallen vormen een goed compromis: ze zijn smal genoeg om informatief te zijn, maar haast nooit zeer misleidend. We besluiten dat de parameter die ons interesseert in het 95% betrouwbaarheidsinterval zit,\nen weten dat die uitspraak met 95% kans correct is.\nIn de statistiek trekt men dus nooit absolute conclusies.\n\nOp basis van de data-analyse voor het captopril voorbeeld kunnen we dus besluiten dat de gemiddelde bloeddrukdaling\n18.9mmHg bedraagt na het toedienen van captopril. Met een 95% betrouwbaarheidsinterval op het gemiddelde van [-23.9,-13.9]mmHg.\nOp basis van het betrouwbaarheidsinterval is het duidelijk dat het toedienen van captopril resulteert in een sterke bloeddrukdaling bij patiënten met hypertensie.\n\n\n## Principe van Hypothesetoetsen (via one sample t-test)\n\n<iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/Zn3cNZJKKhM\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n\nWe wensen een uitspraak te kunnen doen of er al dan niet een effect is van het toedienen van Captopril op de systolische bloeddruk? Beslissen op basis van gegevens is niet evident. Er is immers onzekerheid of de bevindingen uit de steekproef\ngeneraliseerbaar zijn naar de populatie. We stellen ons dus de vraag of het schijnbaar gunstig effect systematisch of toevallig is?\nEen natuurlijke beslissingsbasis is het gemiddeld verschil $X$ in de systolische bloeddruk:\n\n$$\\bar x=-18.93mmHg (s = 9.03, SE = 2.33)$$\n\nDat $\\bar{x}< 0$ volstaat niet om te beslissen dat de gemiddelde systolische bloeddruk lager is na het toedienen van captopril *op het niveau van de volledige populatie*. Om het effect die we in de steekproef observeren te kunnen *veralgemenen* naar de populatie moet de bloeddrukverlaging voldoende groot zijn. Maar hoe groot moet dit effect nu zijn?\n\n\nHiervoor hebben statistici zogenaamde *toetsen* ontwikkeld om met dit soort vragen om te gaan. Deze leveren een ja/nee antwoord op de vraag of een geobserveerde associatie systematisch is (d.w.z. opgaat voor de studiepopulatie) of als er integendeel onvoldoende informatie in de steekproef voorhanden is om te besluiten dat de geobserveerde associatie ook aanwezig is in de volledige studiepopulatie. Tegenwoordig is het\nhaast onmogelijk om een wetenschappelijk onderzoeksartikel te lezen zonder\nde resultaten van dergelijke toetsen te ontmoeten. Om die reden wensen we in\ndit hoofdstuk in te gaan op de betekenis van statistische toetsen en hun\nnomenclatuur.\n\nWe weten dat we volgens het *falcificatieprincipe* van Popper nooit een hypothese kunnen bewijzen op basis van data (zie Sectie -@sec-wetMeth).\nDaarom zullen we twee hypotheses introduceren: een nulhypothese en een alternatieve hypothese.\nWe zullen dan later a.d.h.v. de toets de nulhypothese trachten te ontkrachten.\n\n### Introductie d.m.v. captopril voorbeeld\n\n- We introduceren hypothese testen eerst intuïtief a.d.h.v. het captopril voorbeeld.\n\n- Op basis van de steekproef kunnen we niet bewijzen dat er een effect is van het toedienen van captopril ($H_1$, alternatieve hypothese).\n\n- We veronderstellen daarom dat er geen effect is van captopril\n\n    - We noemen dit de nulhypothese $H_0$.\n\n    - Falsify (\"probeer te ontkrachten\") de $H_0$.\n\n    - Hoe waarschijnlijk is het om een effect waar te nemen dat minstens zo groot is als wat we in de steekproef in een willekeurige steekproef hebben gezien als $H_0$ waar is?  \n\n<!---break-->\n\n#### Permutatie test\n\n\n- Onder $H_0$ zijn de bloeddrukmetingen voor en na toediening van captopril twee \"base line\" bloeddrukmetingen voor een patiënt\n\n- Onder $H_0$ kunnen we de bloeddrukmetingen voor iedere patiënt in willekeurige volgorde plaatsen (permuteren).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(35)\ncaptoprilSamp <- captopril\nperm <- sample(c(FALSE, TRUE), 15, replace = TRUE)\ncaptoprilSamp$SBPa[perm] <- captopril$SBPb[perm]\ncaptoprilSamp$SBPb[perm] <- captopril$SBPa[perm]\ncaptoprilSamp$deltaSBP <- captoprilSamp$SBPa-captoprilSamp$SBPb\ncaptoprilSamp |>\n  gather(type, bp, -id) |>\n  filter(type %in% c(\"SBPa\",\"SBPb\")) |>\n  mutate(type = factor(type, levels = c(\"SBPb\", \"SBPa\")))|>\n  ggplot(aes(x = type,y = bp)) +\n  geom_line(aes(group = id)) +\n  geom_point()\n```\n\n::: {.cell-output-display}\n![](05-StatistischeBesluitvorming_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata.frame(\n  deltaSBP = c(captopril$deltaSBP,captoprilSamp$deltaSBP),\n  shuffled=rep(c(FALSE,TRUE),each=15)\n  ) |>\n  ggplot(aes(x = shuffled, y = deltaSBP)) +\n  geom_boxplot(outlier.shape = NA) +\n  geom_point(position = \"jitter\")+\n  stat_summary(\n    fun.y = mean,\n    geom = \"point\",\n    shape = 19,\n    size = 3,\n    color = \"red\",\n    fill = \"red\") +\n  ylab(\"Difference (mm mercury)\")\n```\n\n::: {.cell-output-display}\n![](05-StatistischeBesluitvorming_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\nWe permuteren opnieuw\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncaptoprilSamp <- captopril\nperm <- sample(c(FALSE,TRUE), 15, replace = TRUE)\ncaptoprilSamp$SBPa[perm] <- captopril$SBPb[perm]\ncaptoprilSamp$SBPb[perm] <- captopril$SBPa[perm]\ncaptoprilSamp$deltaSBP <- captoprilSamp$SBPa-captoprilSamp$SBPb\ncaptoprilSamp |>\n  gather(type, bp, -id) |>\n  filter(type %in% c(\"SBPa\",\"SBPb\")) |>\n  mutate(type = factor(type, levels = c(\"SBPb\", \"SBPa\")))|>\n  ggplot(aes(x = type,y = bp)) +\n  geom_line(aes(group = id)) +\n  geom_point()\n```\n\n::: {.cell-output-display}\n![](05-StatistischeBesluitvorming_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n\n```{.r .cell-code}\ndata.frame(\n  deltaSBP = c(captopril$deltaSBP,captoprilSamp$deltaSBP),\n  shuffled=rep(c(FALSE,TRUE),each=15)\n  ) |>\n  ggplot(aes(x = shuffled, y = deltaSBP)) +\n  geom_boxplot(outlier.shape = NA) +\n  geom_point(position = \"jitter\")+\n  stat_summary(\n    fun.y = mean,\n    geom = \"point\",\n    shape = 19,\n    size = 3,\n    color = \"red\",\n    fill = \"red\") +\n  ylab(\"Difference (mm mercury)\")\n```\n\n::: {.cell-output-display}\n![](05-StatistischeBesluitvorming_files/figure-html/unnamed-chunk-25-2.png){width=672}\n:::\n:::\n\n\n\n\n- Er zijn $2^{15}$ = 32768 mogelijke permutaties!\n- We hoeven in principe alleen de tekens van de waargenomen bloeddrukverschillen $x$ te wisselen als we permuteren.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npermH <- expand.grid(\n  replicate(\n    15,\n    c(-1,1),\n    simplify=FALSE)\n  ) |>\n  t()\n\npermH[,1:5]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      [,1] [,2] [,3] [,4] [,5]\nVar1    -1    1   -1    1   -1\nVar2    -1   -1    1    1   -1\nVar3    -1   -1   -1   -1    1\nVar4    -1   -1   -1   -1   -1\nVar5    -1   -1   -1   -1   -1\nVar6    -1   -1   -1   -1   -1\nVar7    -1   -1   -1   -1   -1\nVar8    -1   -1   -1   -1   -1\nVar9    -1   -1   -1   -1   -1\nVar10   -1   -1   -1   -1   -1\nVar11   -1   -1   -1   -1   -1\nVar12   -1   -1   -1   -1   -1\nVar13   -1   -1   -1   -1   -1\nVar14   -1   -1   -1   -1   -1\nVar15   -1   -1   -1   -1   -1\n```\n\n\n:::\n:::\n\n\n- We zullen dit voor alle mogelijke permutaties doen en we zullen het gemiddelde bijhouden.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#calculate the means for the permuted data\nmuPerm <- colMeans(permH*captopril$deltaSBP)\ndata.frame(permMean = muPerm) |>\n  ggplot(aes(x=permMean)) +\n  geom_histogram() +\n  geom_vline(\n    xintercept = mean(captopril$deltaSBP),\n    col = \"blue\")\n```\n\n::: {.cell-output-display}\n![](05-StatistischeBesluitvorming_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n\n```{.r .cell-code}\nsum(muPerm <= mean(captopril$deltaSBP))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(muPerm <= mean(captopril$deltaSBP))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.051758e-05\n```\n\n\n:::\n:::\n\n\n-  We zien dat maar 1 van de gemiddelden die werden verkregen onder $H_0$ (door permutatie) zo extreem was als het steekproefgemiddelde dat we in de captopril-studie hebben waargenomen.\n\n- Dus de kans om een bloeddrukdaling waar te nemen die groter of gelijk is dan die in de captopril-studie in een willekeurige steekproef onder de nulhypothese, is 1 op de 32768.\n\nWe hebben dus sterk bewijs dat $H_0$ onjuist is en daarom verwerpen we $H_0$ en concluderen $H_1$: het toedienen van captopril heeft een effect op de bloeddruk van patiënten met hypertensie.\n\n\n#### Pivot\n\n- In de praktijk gebruiken we altijd statistieken die de effectgrootte (gemiddeld verschil) afwegen tegen ruis (standaard error)\n\n- Als we de nulhypothese ontkrachten, standaardiseren we het gemiddelde rond $\\mu_0 = 0$ het gemiddelde onder $H_0$\n\n$$t=\\frac{\\bar X-\\mu_0}{se_{\\bar X}}$$\n\n- Voor het Captopril voorbeeld wordt dit:\n$$\\frac{-18.93-0}{2.33}=-8.12$$\n\n\nWe bepalen nu de nulverdeling van teststatistiek t met permutatie.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndeltaPerms <- permH*captopril$deltaSBP\ntPerm <- colMeans(deltaPerms)/(apply(deltaPerms,2,sd)/sqrt(15))\ntOrig <- mean(captopril$deltaSBP)/sd(captopril$deltaSBP)*sqrt(15)\n\ntPermPlot <- data.frame(permT = tPerm) |>\n  ggplot(aes(x=permT)) +\n  geom_histogram(aes(y = ..density.., fill = ..count..)) +\n  geom_vline(xintercept = tOrig,col = \"blue\")\ntPermPlot\n```\n\n::: {.cell-output-display}\n![](05-StatistischeBesluitvorming_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n\n- Opnieuw heeft slechts 1 van de permutaties een t-statistiek die zo extreem is als de statistiek die wordt waargenomen in de captopril-studie.\n\nWanneer er geen effect is van captopril, is het bijna onmogelijk om een teststatistiek te verkrijgen die zo extreem is als degene die werd waargenomen in de steekproef (t=-8.12).\n\n- De kans om een grotere bloeddrukdaling waar te nemen dan degene die we in onze steekproef hebben waargenomen in een willekeurige steekproef onder $H_0$ is 1/32768.\n\n- We noemen deze kans de *p-waarde*.\n\n- Het meet de sterkte van het bewijs tegen de nulwaarde: hoe kleiner de p-waarde, hoe meer bewijs we hebben dat de nulwaarde niet waar is.\n\n- De verdeling heeft een mooie klokvorm.\n\n***\n\n#### Hoe beslissen we?\n\nWanneer is de p-waarde klein genoeg om te concluderen dat er sterk bewijs is tegen de nulhypothese?\n\n- We werken doorgaans met een significantieniveau van $\\alpha = 0,05$\n\n- We stellen dat we de test hebben uitgevoerd op het significantieniveau van 5%\n\n***\n\n\n#### Permutatietests zijn computationeel veeleisend\n\n- Kunnen we beoordelen hoe extreem de bloeddrukdaling was zonder permutatie?\n\n- We weten dat de bloeddrukverschillen ongeveer normaal verdeeld zijn, dus\n\n$$t=\\frac{\\bar X - \\mu}{se_{\\bar X}}$$\n\nvolgt een t-verdeling (met 14 vrijheidsgraden voor het Captopril voorbeeld).\n\n\n- Onder $H_0$ $\\mu=0$ en \n\n  $$t=\\frac{\\bar X-0}{se_{\\bar X}}\\sim f_{T,14}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntPermPlot +\n  stat_function(\n    fun = dt,\n    color = \"red\",\n    args = list(df=14))\n```\n\n::: {.cell-output-display}\n![](05-StatistischeBesluitvorming_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\n\n- Merk op dat de permutatie-nulverdeling inderdaad overeenkomt met een t-verdeling met 14 vrijheidsgraden.\n\n- Zodat we de statistische test kunnen uitvoeren met behulp van statistische modellen van de gegevens.\n\n- Hiervoor moeten we assumpties maken, die we verifiëren in de data exploratie.\n\nWe overlopen nu alle componenten van een hypothese test waarbij we gebruik maken van veronderstellingen over de distributie van de gegevens.\n\n<!---break-->\n\n\n### Hypotheses\n\n<iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/9YNTVE5xTKg\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n\nAlgemeen starten we met het vertalen van de wetenschappelijke vraagstelling naar een nulhypothese ($H_0$) en een alternatieve hypothese ($H_1$).\nDit kan pas nadat de probleemstelling vertaald is naar een geparametriseerd statistisch model.\nUit de beschrijving van de proefopzet volgt dat $X_1,...,X_n$ i.i.d.^[independent and identically distributed, onafhankelijk en gelijk verdeeld] $f(X)$\nmet $f(X)$ de dichtheidsfunctie van de bloeddrukverschillen.\n\n**Vereenvoudiging**: veronderstel dat $f(X)$ gekend is op een eindig-dimensionale set van parameters $\\mathbf{\\theta}$ na (parametrisch statistisch model).\nVoor het captopril voorbeeld veronderstellen we dat $f(X)$ een normale distributie $N(\\mu,\\sigma^2)$ volgt met parameters $\\mathbf{\\theta}=(\\mu,\\sigma^2)$, het gemiddelde $\\mu$ en variantie  $\\sigma^2$.\n\nDe vraagstelling is geformuleerd in termen van de gemiddelde bloeddrukdaling: $\\mu=E_f[X]$.\n\nDe **alternatieve hypothese** wordt geformuleerd in termen van een parameter van $f(X)$ en dient uit te drukken wat de onderzoekers wensen te bewijzen aan de hand van de studie.\nHier:\n\n$$H_1: \\mu<0.$$\n\nGemiddeld gezien daalt de bloeddruk bij patiënten met hypertensie na toediening van captopril.\n\nDe **nulhypothese** is meestal een uitdrukking van de nultoestand, i.e. de omstandigheden waarin niets bijzonders aan de hand is.\nDe onderzoekers wensen meestal te bewijzen via empirisch onderzoek dat de nulhypothese niet waar is:\n**Falsificatie principe**.\nDe **nulhypothese wordt veelal uitgedrukt door gebruik te maken van dezelfde parameter als deze die in $H_1$** gebruikt is. Hier:\n\n$$H_0 : \\mu=0$$\n\nm.a.w. gemiddeld gezien blijft de systolische bloeddruk na toediening van captopril onveranderd.\n\n<!---break-->\n\n### Test-statistiek\n\n\n<iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/RAG5DI7zwRM\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n\nEens de populatie, de parameters en de nulhypothese en alternatieve hypothese bepaald zijn, kan de basisgedachte van een hypothesetest als volgt bondig beschreven worden.\n\nConstrueer een teststatistiek zodanig dat deze\n\n1. de evidentie meet die aanwezig is in de steekproef,\n2. tegen de gestelde nulhypothese,\n3. ten voordele van de alternatieve hypothese.\n\nEen teststatistiek is dus noodzakelijk een functie van de steekproefobservaties.\n\nVoor het captopril voorbeeld drukt de statistiek\n\n$$T=\\bar X - \\mu_0$$\n\nuit hoever het steekproefgemiddelde van de bloeddrukdaling ligt van het gemiddelde $\\mu_0=0$ in de populatie onder de nulhypothese^[vandaar de index 0 bij $\\mu_0$].\n\n- Als $H_0$ waar is en er dus geen effect is van captopril in de populatie, dan verwachten we dat de teststatistiek T dicht ligt bij $T=0$\n- Als $H_1$ waar is, dan verwachten we dat $T<0$.\n\nIn de praktijk gebruiken we echter meestal teststatistieken die niet alleen de grootte van het effect in rekening brengen maar ook de onzekerheid op het effect.\nWe doen dit door de effectgrootte te balanceren t.o.v. de standard error.\n\n$$T=\\frac{\\bar{X}-0}{\\text{SE}_{\\bar X}}$$\n\nWaarbij $\\mu_0=0$ voor het captopril voorbeeld.\n\nOpnieuw geldt dat\n\n- Als $H_0$ waar is en er dus geen effect is van captopril in de populatie, dan verwachten we dat de teststatistiek T dicht ligt bij $T=0$\n- Als $H_1$ waar is, dan verwachten we dat $T<0$.\n- Voor het captopril voorbeeld vinden we $t=(-18.93-0)/2.33=-8.12$.\n- Is $t = -8.12$ groot genoeg in absolute waarde om te kunnen besluiten dat $\\mu < 0$ en met welke zekerheid kunnen we dit besluiten?\n\nOm daar een uitspraak over te doen zullen we de teststatistiek T verder bestuderen.\nT is een toevalsveranderlijke en de verdeling van T hangt af van de verdeling van de steekproefobservaties, maar die verdeling is ongekend!\nWe hebben normaliteit verondersteld, maar dit laat nog steeds het gemiddelde en de variantie onbepaald.\nBovendien wordt de hypothesetest net geconstrueerd om een uitspraak te kunnen doen over het gemiddelde $\\mu$!\nDe oplossing zit in de nulhypothese die we kunnen veronderstellen als er geen effect is van captopril.\nDe $H_0$ stelt dat $\\mu=0$.\nAls we aannemen dat $H_0$ waar is, dan is het gemiddelde van de normale distributie gekend!\n Als de bloeddrukverschillen $X_1, \\ldots X_{15}$ onafhankelijk en identiek normaal verdeeld (i.i.d.) zijn, dan weten we dat\n\n$$\\bar X  \\stackrel{H_0}{\\sim} N(0, \\sigma^2/n)$$\n\nGezien we $\\sigma^2$ niet kennen kunnen we deze vervangen door de steekproef variantie. Dan weten we dat\n\n$$T=\\frac{\\bar{X}-0}{\\text{SE}_{\\bar X}}\\stackrel{H_0}{\\sim} t(n-1) $$\n\neen t-verdeling volgt met n-1 vrijheidsgraden onder de **nulhypothese**.\nWe weten dat indien de alternatieve hypothese waar zou zijn, we mogen verwachten dat er meer kans is op het observeren van een kleine waarde voor de teststatistiek dan wat verwacht wordt onder de nulhypothese.\nWe zullen de verdeling van de teststatistiek onder de nulhypothese gebruiken om na te gaan of de geobserveerde test-statistiek $t = -8.12$ klein genoeg is om te kunnen besluiten dat $\\mu < 0$.\n\n- **Is de geobserveerde teststatistiekwaarde ($t=-8.12$) een waarde die we verwachten als $H_0$ waar is**, of is het een waarde die onwaarschijnlijk klein is als $H_0$ waar is?\n- In het laatste geval deduceren we dat we niet langer kunnen aannemen dat $H_0$ waar is, en dienen we dus $H_1$ te concluderen.\n-  De vraag blijft: (a) hoe groot moet de geobserveerde teststatistiek $t$ zijn opdat we $H_0$ verwerpen zodat (b) we bereid zijn om $H_1$ te besluiten en (c) hoe zeker zijn we van deze beslissing?\n- Het antwoord hangt samen met de interpretatie van de kansen die berekend kunnen worden op basis van de nuldistributie^[distributie van de teststatistiek onder de nulhypothese] en de geobserveerde teststatistiek $t$.\n\n\n<!---break-->\n\n\n### De p-waarde\n\n<iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/jw5x7x6RX24\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n\nDe kans waarop de keuze tussen $H_0$ en $H_1$ gebaseerd wordt, wordt de **$p$-waarde** genoemd.  De berekeningswijze is context-afhankelijk, maar voor het huidige voorbeeld wordt de $p$-waarde gegeven door\n  \n  $$\n    p = P\\left[T \\leq t \\mid H_0\\right] = \\text{P}_0\\left[T\\leq t\\right],\n  $$\n\n  waar de index \"0\" in $\\text{P}_0\\left[.\\right]$ aangeeft dat de kans onder de nulhypothese berekend wordt. Het is met andere woorden de kans om in een willekeurige steekproef onder de nulhypothese een waarde voor de teststatistiek T te bekomen die lager of gelijk is aan^[meer extreem in de richting van $H_1$] de waarde die in de huidige steekproef werd geobserveerd.\n\nDe $p$-waarde voor het captopril voorbeeld wordt berekend als\n\n  $$p= \\text{P}_0\\left[T\\leq -8.12\\right]=F_t(-8.12;14) = 0.6\\ 10^{-6}.$$\n\nwaarbij $F_t(;14)$ de cumulatieve distributie functie is van een t-verdeling met 14 vrijheidsgraden,\n\n$$F_t(x;14)=\\int\\limits_{-\\infty}^{x} f_t(x;14).$$\n\nWaarbij $f_t(.;14)$ de densiteitsfunctie is van de t-verdeling.\nDe oppervlakte onder de densiteitsfunctie is opnieuw een kans.\nDeze kans kan  berekend worden in R m.b.v. de functie `pt(x,df)` die twee argumenten heeft, de waarde van de test-statistiek `x` en het aantal vrijheidsgraden van de t-verdeling `df`.\n`pt(x,df)` berekent de kans om een waarde te observeren die kleiner of gelijk is aan x wanneer men een willekeurige observatie trekt uit een t-verdeling met df vrijheidsgraden.  \n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- length(delta)\nstat<-(mean(delta)-0)/(sd(delta)/sqrt(n))\nstat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -8.122816\n```\n\n\n:::\n\n```{.r .cell-code}\npt(stat,n-1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.731936e-07\n```\n\n\n:::\n:::\n\n\n::: {#def-p-waarde}\n## $p$-waarde\n\n&nbsp;\n:::\nDe **p-waarde** (ook wel **geobserveerd significantieniveau** genoemd) is de\nkans om onder de nulhypothese een even of meer \"extreme\" toetsinggrootheid\nwaar te nemen (in de richting van het alternatief) dan de waarde $t$ die\ngeobserveerd werd o.b.v. de steekproef. Hoe kleiner die kans is, hoe sterker het bewijs tegen de\nnulhypothese.\n\nMerk op dat de p-waarde de kans **niet** uitdrukt dat de nulhypothese waar is!^[In de frequentistische theorie die we hier volgen, is de nulhypothese immers ofwel altijd waar, ofwel altijd vals, en is het dus zelfs niet mogelijk om de kans te definiëren dat de nulhypothese waar is. Teminste, die kans is ofwel 1 ofwel 0.!].\n\n**Einde Definitie**\n\n\n\nHet woord \"extreem\" duidt op de richting waarvoor de teststatistiek onder de alternatieve hypothese meer waarschijnlijk is. In het voorbeeld is $H_1: \\mu < 0$ en verwachten we dus kleinere waarden van $t$ onder $H_1$. Vandaar de kans op $T\\leq t$.\nUit de definitie van de $p$-waarde volgt dat een kleine $p$-waarde betekent dat de geobserveerde teststatistiek eerder onwaarschijnlijk is als aangenomen wordt dat $H_0$ correct is.\nDus een voldoende kleine $p$-waarde noopt ons tot het **verwerpen van $H_0$** ten voordele van $H_1$.\nDe drempelwaarde waarmee de $p$-waarde vergeleken wordt, wordt het **significantieniveau** genoemd en wordt voorgesteld door $\\alpha$.\n\n::: {#def-significantieniveau}\n## significantieniveau\n\n&nbsp;\n:::\nDe drempelwaarde $\\alpha$ staat gekend als het **significantieniveau** van de statistische test. Een statistische test uitgevoerd op het $\\alpha$ significantieniveau wordt een **niveau-$\\alpha$ test** genoemd (Engels: *level-$\\alpha$ test*).\n\n**Einde definitie**\n\n\nEen toetsingsresultaat wordt *statistisch significant* genoemd\nwanneer de bijhorende p-waarde kleiner is dan $\\alpha$, waarbij $\\alpha$\nmeestal gelijk aan 5\\% wordt genomen. Hoe kleiner de p-waarde hoe meer\n`significant' het testresultaat afwijkt van de verwachting onder de\nnulhypothese. Het aangeven van een p-waarde voor een toets geeft bijgevolg\nmeer informatie over het resultaat dan een eenvoudig ja/nee antwoord of de\nnulhypothese wordt verworpen op een vast gekozen $\\alpha$-niveau. Het geeft immers niet alleen aan of de nulhypothese verworpen wordt op een gegeven significantieniveau, maar ook op welke significantieniveaus de nulhypothese verworpen wordt.\n\nZe vat dus de bewijskracht tegen de nulhypothese samen\n\n$$\\begin{array}{cl}>0.10 & \\text{ niet significant (zwak bewijs)}\\\\0.05-0.10 & \\text{ marginaal significant, suggestief}\\\\0.01-0.05 & \\text{ significant}\\\\0.001-0.01 & \\text{ sterk significant}\\\\<0.001 & \\text{ extreem significant}\\end{array}$$\n\n<!---break-->\n\n### Kritieke waarde\n\n<iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/L9tDrqrfL1k\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n\nEen **alternatieve wijze voor de formulering van de beslissingsregel** kan worden bekomen door gebruik te maken van een kritieke waarde.\nIn plaats van $p$-waarden, kan de beslissingsregel geschreven worden in termen van de teststatistiek.\n Bij gebruik van $p$-waarden bepaalt $p=\\alpha$ de grens.\n Een $p$-waarde van $\\alpha$ schrijven we als\n\n $$p=\\text{P}_0 \\left[ T \\leq t \\right]=\\alpha.$$\n\n Dat is exact de definitie van het het $\\alpha$-percentiel van de distributie van $T$.\n In het voorbeeld is de nuldistributie $t_{n-1}$.\n Dus,\n \n $$\\text{P}_0\\left[T\\leq -t_{n-1;\\alpha}\\right]=\\alpha.$$\n\nDe beslissingsregel mag dus ook geschreven worden als\n\n\\begin{eqnarray*}\n\\text{als } & t< -t_{n-1;\\alpha} & \\text{ dan verwerp }H_0\\text{ en besluit }H_1 \\\\\n  \\text{als } & t\\geq -t_{n-1;\\alpha} & \\text{ dan aanvaard }H_0.\n\\end{eqnarray*}\n\nHet percentiel $t_{n-1;\\alpha}$ dat de drempelwaarde vormt in de beslissingsregel wordt in deze context de **kritieke waarde** op het $5\\%$ significantieniveau genoemd.\nDe beslissingsregel waarbij de geobserveerde $t$ vergeleken wordt met een kritieke waarde is minder algemeen geformuleerd dan deze gebruik makend van de $p$-waarde omdat het expliciet gebruik maakt van de nuldistributie die van teststatistiek tot teststatistiek, of zelfs van dataset tot dataset kan variëren.\n\nDe begrippen p-waarde, kritieke waarde, significantie-niveau, verwerpings- en aanvaardingsregio worden weergegeven in Figuur -@fig-captoTest.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Interpretatie van p-waarde, kritieke waarde, verwerpingsgebied, aanvaardingsgebied voor het captopril voorbeeld.](05-StatistischeBesluitvorming_files/figure-html/fig-captoTest-1.png){#fig-captoTest fig-align='center' width=100%}\n:::\n:::\n\n\n<!---break-->\n\n\n### Beslissingsfouten\n\n<iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/2zIkaD3gWyM\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n\nAangezien de beslissing over het al dan niet verwerpen van de nulhypothese bepaald wordt door slechts een steekproef te observeren, kunnen volgende beslissing genomen worden:\n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table\" style=\"margin-left: auto; margin-right: auto;\">\n <thead>\n<tr>\n<th style=\"empty-cells: hide;border-bottom:hidden;\" colspan=\"1\"></th>\n<th style=\"border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; \" colspan=\"2\"><div style=\"border-bottom: 1px solid #ddd; padding-bottom: 5px; \">Werkelijkheid</div></th>\n</tr>\n  <tr>\n   <th style=\"text-align:center;\"> Besluit </th>\n   <th style=\"text-align:center;\"> H0 </th>\n   <th style=\"text-align:center;\"> H1 </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:center;\"> Aanvaard H0 </td>\n   <td style=\"text-align:center;\"> OK </td>\n   <td style=\"text-align:center;\"> Type II (β) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Verwerp H0 </td>\n   <td style=\"text-align:center;\"> Type I (α) </td>\n   <td style=\"text-align:center;\"> OK </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\nHet schema geeft de vier mogelijke situaties:\n\n- $H_0$ is in werkelijkheid waar, en dit wordt ook besloten aan de hand van de statistische test (dus geen beslissingsfout)\n\n- $H_1$ is in werkelijkheid waar, en dit wordt ook besloten aan de hand van de statistische test (dus geen beslissingsfout)\n\n- $H_0$ is in werkelijkheid waar, maar aan de hand van de statistische test wordt besloten om $H_0$ te verwerpen en $H_1$ te concluderen. Dus $H_1$ wordt foutief besloten. Dit is een zogenaamde **type I** fout.\n\n- $H_1$ is in werkelijkheid waar, maar aan de hand van de statistische test wordt besloten om $H_0$ te aanvaarden.\n Dit is een zogenaamde **type II** fout. Dus $H_0$ wordt foutief aanvaard.\n\n De beslissing is gebaseerd op een teststatistiek $T$ die een toevalsveranderlijke is. De beslissing is dus ook stochastisch en aan de vier mogelijke situaties uit bovenstaand schema kunnen dus probabiliteiten toegekend worden. Net zoals voor het afleiden van de steekproefdistributie van de teststatistiek, moeten we de distributie van de steekproefobservaties kennen alvorens het stochastisch gedrag van de beslissingen te kunnen beschrijven. Indien we aannemen dat $H_0$ waar is, dan is de distributie van $T$ gekend en kunnen ook de kansen op de beslissingen bepaald worden voor de eerste kolom van de tabel.\n\n#### Type I fout\n\nWe starten met de kans op een type I fout (hier uitgewerkt voor het captopril voor beeld):\n\n$$\\text{P}\\left[\\text{type I fout}\\right]=\\text{P}\\left[\\text{verwerp }H_0 \\mid H_0\\right] = \\text{P}_0\\left[T<t_{n-1;1-\\alpha}\\right]=\\alpha.$$\n\n Dit geeft ons meteen een interpretatie van het significantieniveau $\\alpha$: het is de kans op het maken van een type I fout. De constructie van de statistische test garandeert dus dat de kans op het maken van een type I fout gecontroleerd wordt op het significantieniveau $\\alpha$. De kans op het correct aanvaarden van $H_0$ is dus $1-\\alpha$.\nVerder kan aangetoond worden dat de p-waarde onder $H_0$ uniform verdeeld is. Het leidt dus tot een uniforme beslissingsstrategie.\n\nWe illustreren dit in een simulatiestudie\n\n- n=15\n- $\\mu=0$ mmHg, er is dus geen effect van de behandeling\n- $\\sigma =9$ mmHg\n- 1000 gesimuleerde steekproeven\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnsim <- 10000\nn <- 15\nsigma <- 9\nmu <- 0\nmu0 <- 0\nalpha <- 0.05\n\n#simulate nsim samples of size n\ndeltaSim <- matrix(\n  rnorm(n*nsim,mu,sigma),\n  nrow=n,\n  ncol=nsim)\n\npSim <- apply(\n  deltaSim,\n  2,\n  function(x, mu, alternative)    \n    t.test(x,\n      mu = mu,\n      alternative = alternative)$p.value,\n      mu = mu0,\n      alternative=\"less\"\n  )\n\nmean(pSim<alpha)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0513\n```\n\n\n:::\n\n```{.r .cell-code}\ndata.frame(pValue = pSim) |>\n  ggplot(aes(x=pValue)) +\n  geom_histogram() +\n  xlim(0,1)\n```\n\n::: {.cell-output-display}\n![](05-StatistischeBesluitvorming_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n:::\n\n\n- De type I-fout is inderdaad ongeveer 0,05\n- De p-waarden zijn uniform\n\n***\n\n**Opdracht:**\n\nVoer de simulatiestudie opnieuw uit verdubbel hierbij het aantal observaties in de steekproef. Wat observeer je?\n\n***\n\n#### Type II fout\n\nHet bepalen van de kans op een type II fout is minder evident omdat de alternatieve hypothese minder éénduidig is als de nulhypothese. In het captopril voorbeeld is $H_1: \\mu<0$; met deze informatie wordt de distributie van de steekproefobservaties niet volledig gespecifieerd en dus ook niet de distributie van de teststatistiek. Dit impliceert dat we eigenlijk de kans op een type II fout niet kunnen berekenen. De klassieke *work-around* bestaat erin om één specifieke distributie te kiezen die voldoet aan $H_1$.\n\n $$H_1(\\delta): \\mu=0-\\delta \\text{ voor een }\\delta>0.$$\n\n De parameter $\\delta$ kwantificeert de afwijking van de nulhypothese.\n\nDe **kracht** van een test (Engels: *power*) is een kans die meer frequent gebruikt wordt dan de kans op een type II fout $\\beta$. De kracht wordt gedefinieerd als\n\n$$\\pi(\\delta) = 1-\\beta(\\delta) = \\text{P}_\\delta\\left[T>t_{n-1;1-\\alpha}\\right]=\\text{P}_\\delta\\left[P<\\alpha\\right].$$\n\nDe kracht van een niveau-$\\alpha$ test voor het detecteren van een afwijking $\\delta$ van het gemiddelde onder de nulhypothese $\\mu_0=0$ is dus de kans dat de niveau-$\\alpha$ test dit detecteert wanneer de afwijking in werkelijkheid $\\delta$ is.\n\nMerk op dat $\\pi(0)=\\alpha$ en de kracht van een test toeneemt als de afwijking van de nulhypothese toeneemt.\n\nDe **kracht** van de test (d.i. de kans om Type II fouten te vermijden) wordt typisch niet gecontroleerd, tenzij d.m.v. studiedesign en steekproefgrootte.\n\n**Interpretatie**\n\nStel dat we voor een gegeven dataset bekomen dat $p<\\alpha$, m.a.w. $H_0$ wordt verworpen. Volgens het schema van de beslissingsfouten zijn er dan slechts twee mogelijkheden (zie onderste rij van schema): ofwel is de beslissing correct, ofwel hebben we een type I fout gemaakt. Over de type I fout weten we echter dat ze slechts voorkomt met een kleine kans.\nAnderzijds, indien $p\\geq \\alpha$ en we $H_0$ niet verwerpen, dan zijn er ook twee mogelijkheden: ofwel is de beslissing correct, ofwel hebben we een type II fout gemaakt. De kans op een type II fout ($\\beta$) is echter niet gecontroleerd op een gespecifieerde waarde. De statistische test is zodanig geconstrueerd dat ze enkel de kans op een type I fout controleert (op $\\alpha$). Om wetenschappelijk eerlijk te zijn, moeten we een pessimistische houding aannemen en er rekening mee houden dat $\\beta$ groot zou kunnen zijn (i.e. een kleine kracht).\n\nBij $p < \\alpha$ wordt de nulhypothese verworpen en  we mogen hieruit concluderen dat $H_1$ waarschijnlijk juist is. Dit noemen we een sterke conclusie.\nBij $p\\geq \\alpha$ wordt de nulhypothese aanvaard, maar dat impliceert niet  dat we concluderen dat $H_0$ juist is. We kunnen enkel besluiten dat de data onvoldoende bewijskracht tegen $H_0$ ten gunste van $H_1$ bevatten. Dit noemen we een daarom zwakke conclusie.\n\nWe illustreren dit opnieuw in een simulatiestudie:\n\n- n=15\n- $\\mu=-2$ mmHg, er is dus een bloeddrukdaling van 2 mmHg door de behandeling.\n- $\\sigma =9$ mmHg\n- 1000 gesimuleerde steekproeven\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnsim <- 10000\nn <- 15\nsigma <- 9\nmu <- -2\nmu0 <- 0\nalpha <- 0.05\n\n#simulate nsim samples of size n\ndeltaSim <- matrix(\n  rnorm(n*nsim, mu, sigma),\n  nrow=n,\n  ncol=nsim)\n\npSim <- apply(\n  deltaSim,\n  2,\n  function(x,mu,alternative)          \n    t.test(x,\n      mu = mu,\n      alternative = alternative)$p.value,\n      mu = mu0,\n      alternative = \"less\"\n  )\n\nmean(pSim<alpha)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2055\n```\n\n\n:::\n\n```{.r .cell-code}\ndata.frame(pValue = pSim) |>\n  ggplot(aes(x=pValue)) +\n  geom_histogram() +\n  xlim(0,1)\n```\n\n::: {.cell-output-display}\n![](05-StatistischeBesluitvorming_files/figure-html/unnamed-chunk-33-1.png){width=672}\n:::\n:::\n\n- We observeren dat een power van 0.2055 of een type II error van 0.7945.\n\n***\n\n**Opdracht:**\n\nVoer de simulatiestudie opnieuw uit verdubbel hierbij het aantal observaties in de steekproef. Wat observeer je?\n\n***\n\n<!---break-->\n\n### Conclusies Captopril voorbeeld.\n\n<iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/yKZy5-sYWRA\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n\nDe test die we hebben uitgevoerd is in de literatuur ook bekend als de **one sample t-test** op het verschil of als een **gepaarde t-test**, we beschikken immers over gepaarde gegevens per patiënt.\nDe test is eenzijdig uitgevoerd. We testen tegen het alternatief dat er een bloeddrukdaling is.\n\nBeide testen (one sample t-test op het verschil en de gepaarde t-test) geven ons inderdaad dezelfde resultaten:\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(delta,alternative=\"less\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  delta\nt = -8.1228, df = 14, p-value = 5.732e-07\nalternative hypothesis: true mean is less than 0\n95 percent confidence interval:\n      -Inf -14.82793\nsample estimates:\nmean of x \n-18.93333 \n```\n\n\n:::\n\n```{.r .cell-code}\nwith(captopril,\n\t   t.test(\n\t\t\t SBPa,\n\t\t\t SBPb,\n\t\t\t paired=TRUE,\n\t\t\t alternative=\"less\")\n\t\t )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPaired t-test\n\ndata:  SBPa and SBPb\nt = -8.1228, df = 14, p-value = 5.732e-07\nalternative hypothesis: true mean difference is less than 0\n95 percent confidence interval:\n      -Inf -14.82793\nsample estimates:\nmean difference \n      -18.93333 \n```\n\n\n:::\n:::\n\n\nWe kunnen op basis van de test het volgende concluderen:\nNa toediening van captopril is er een extreem significante verlaging van de systolische bloeddruk bij patiënten met hypertensie\n($p << 0.001$). De systolische bloeddruk neemt gemiddeld met 18.9 mm kwik af na de behandeling met captopril (95% BI [$-\\infty,-14.82$] mm Hg).\n\nMerk op dat we\n\n1. Een eenzijdig interval rapporteren gezien we enkel geïnteresseerd zijn om aan te tonen dat er een bloeddrukdaling is.\n2. Door het pre-test/post-test design geen uitsluitsel kunnen geven of dit te wijten is aan de werking van het middel of aan een placebo effect. Er was geen goeie controle! Het gebrek aan een goeie controle is veelal een probleem bij pre-test/post-test designs.\n\n<!---break-->\n\n### Eenzijdig of tweezijdig toetsen?\n\n<iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/L4NynZ_hPw8\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n\nDe test in het captopril voorbeeld was een eenzijdige test. We wensen immers enkel te detecteren of de captopril behandeling de bloeddruk gemiddeld gezien doet dalen.\n\nIn andere gevallen of een andere context wenst men enkel een stijging te detecteren.  \nStel dat men het bloeddrukverschil had gedefinieerd als $X_{i}^\\prime=Y_{i}^\\text{voor}-Y_{i}^\\text{na}$ dan zouden positieve waarden aangeven dat er een bloeddrukdaling was na de behandeling van captopril: de bloeddruk bij aanvang is dan immers groter dan na de behandeling.\nDe gemiddelde bloeddrukverandering in de populatie noteren we nu als $\\mu^\\prime=\\text{E}[X^*]$.\nIn dat geval hadden we een eenzijdige test uit moeten voeren om $H_0: \\mu^\\prime=0$ te testen tegen $H_1: \\mu^\\prime>0$.\nVoor deze test kunnen we de p-waarde als volgt berekenen:\n\n$$p=\\text{P}_0\\left[T\\geq t\\right].$$\n\nWe voeren nu de analyse uit in R op basis van de toevallige veranderlijke $X^\\prime$. We zullen nu het argument `alternative=\"greater\"` gebruiken in de `t.test` functie zodat we de nulhypothese toetsen tegen het alternatief $H_1: \\mu^\\prime>0$:\n\n::: {.cell}\n\n```{.r .cell-code}\ndelta2 <- captopril$SBPb-captopril$SBPa\nt.test(delta2,alternative=\"greater\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  delta2\nt = 8.1228, df = 14, p-value = 5.732e-07\nalternative hypothesis: true mean is greater than 0\n95 percent confidence interval:\n 14.82793      Inf\nsample estimates:\nmean of x \n 18.93333 \n```\n\n\n:::\n:::\n\n\nUiteraard bekomen we met deze analyse exact dezelfde p-waarde en hetzelfde betrouwbaarheidsinterval. Enkel het teken is omgewisseld.\n\nNaast eenzijdige testen kunnen eveneens tweezijdige testen worden uitgevoerd.\nHet had gekund dat de onderzoekers de werking van het nieuwe medicijn captopril wensten te testen, maar het werkingsmechanisme nog niet kenden in de ontwerpfase. In dat geval zou het eveneens interessant geweest zijn om zowel een stijging als een daling van de bloeddruk te kunnen detecteren.\nHiervoor zou men een tweezijdige toetsstrategie moeten gebruiken waarbij men de nulhypothese\n\n$$H_0: \\mu=0$$\n\ngaat testen versus het alternatieve hypothese\n\n$$H_1: \\mu\\neq0,$$\n\nzodat het gemiddelde onder de alternatieve hypothese verschillend is van $0$. Het kan zowel een positieve of negatieve afwijking zijn en men weet niet bij aanvang van de studie in welke richting het werkelijk gemiddelde zal afwijken onder de alternatieve hypothese.\n\nWe kunnen tweezijdig testen op het $\\alpha=5\\%$ significantieniveau door\n\n1. een kritieke waarde af te leiden:\n\t- Bij een tweezijdige test kan het effect onder de alternatieve hypothese zowel positief of negatief zijn. Hierdoor zullen we onder de nulhypothese de kans berekenen om onder de nulhypothese een effect te observeren dat meer extreem is dan het resultaat dat werd geobserveerd in de steekproef.  In deze context betekent \"meer extreem\" dat de statistiek groter is in absolute waarde dan het geobserveerde resultaat, want zowel grote (sterk positieve) als kleine (sterk negatieve) waarden zijn een indicatie van een afwijking  van de nulhypothese.\n\t  - Om een kritieke waarde af te leiden,zullen we het significatie-niveau $\\alpha$ daarom verdelen over de linker en rechter staart van de verdeling onder $H_0$. Gezien de t-verdeling symmetrisch is, volgt dat we een kritieke waarde $c$ kiezen zodat er een kans is van $\\alpha/2=2.5\\%$ dat $T\\geq c$ en er $\\alpha/2=2.5\\%$ kans is dat $T\\leq -c$. We kunnen dit ook nog als volgt formuleren: Er is onder $H_0$ $\\alpha=5\\%$ kans dat $\\vert T\\vert\\geq c$ (zie Figuur -@fig-captoTest2).\n\n2. We kunnen ook gebruik maken van een tweezijdige p-waarde:\n\n\\begin{eqnarray*}\n  p&=&\\text{P}_0\\left[T\\leq -|t|\\right] + \\text{P}_0\\left[T\\geq |t|\\right]\\\\\n  &=&\\text{P}_0\\left[\\vert T\\vert \\geq \\vert t \\vert\\right]\\\\\n  &=&\\text{P}_0\\left[T \\geq \\vert t \\vert\\right]\\times 2.\n\\end{eqnarray*}\n\nWe berekenen dus de kans dat de t-statistiek onder $H_0$ meer extreem is dan de geobserveerde teststatistiek $t$ in de steekproef.\nWaarbij meer extreem tweezijdig moet geïnterpreteerd worden.\nDe teststatistiek onder $H_0$ is meer extreem als hij groter is in absolute waarde dan $\\vert t  \\vert$, de geobserveerde test statistiek.\nGezien de verdeling symmetrisch is, kunnen we ook eerst de kans in de rechter staart van de verdeling berekenen en deze kans vervolgens vermenigvuldigen met 2 zodoende een tweezijdige p-waarde te bekomen.\n\nAls de onderzoekers niet vooraf gedefinieerd hadden dat ze enkel een bloeddrukdaling wensten te detecteren, dan hadden ze dus een twee-zijdige test uitgevoerd.\nMerk op dat het argument `alternative` van de `t.test` functie een default waarde heeft `alternative=\"two.sided\"` zodat er standaard tweezijdig wordt getoetst.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(delta)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  delta\nt = -8.1228, df = 14, p-value = 1.146e-06\nalternative hypothesis: true mean is not equal to 0\n95 percent confidence interval:\n -23.93258 -13.93409\nsample estimates:\nmean of x \n-18.93333 \n```\n\n\n:::\n:::\n\nWe bekomen nog steeds een exteem significant resultaat. De p-waarde is echter dubbel zo groot omdat we tweezijdig testen.\nWe verkrijgen eveneens een tweezijdig betrouwbaarheidsinterval.\nDe tweezijdige toetsstrategie wordt weergegeven in Figuur -@fig-captoTest2.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Interpretatie van p-waarde, kritieke waarde, verwerpingsgebied, aanvaardingsgebied voor het captopril voorbeeld wanneer we een tweezijdige toets uitvoeren.](05-StatistischeBesluitvorming_files/figure-html/fig-captoTest2-1.png){#fig-captoTest2 fig-align='center' width=100%}\n:::\n:::\n\n\nWe kunnen ons nu de vraag stellen wanneer we eenzijdig of tweezijdig toetsen.\nMet een eenzijdige toets kan men gemakkelijker een alternatieve hypothese\naantonen (op voorwaarde dat ze waar is) dan met een tweezijdige toets. Dit\nkomt essentieel omdat bij zo'n toets alle informatie kan worden aangewend om\nin 1 enkele richting te zoeken. Precies daarom vergt de eenzijdige toets een\nextra beschouwing vóór de aanvang van de studie. Ook al hebben we sterke\na priori vermoedens, vaak kunnen we niet zeker zijn dat dat zo is.\nAnders was er immers geen reden om\ndit te willen toetsen.\n\nAls men een eenzijdige test voorstelt, maar men\nvindt een resultaat in de andere richting\ndat formeel statistisch significant is, dan is het niet geschikt om dit te\nzien als bewijs voor een werkelijk effect in die richting. Dat is omdat de\nonderzoekers die mogelijkheid uitgesloten hebben bij de planning van de\nstudie en het resultaat daarom zó onverwacht is dat het als een vals\npositief resultaat kan gezien worden. Een eenzijdige test is om die reden\nniet aanbevolen. Een tweezijdige toets is altijd verdedigbaar omdat ze in principe toelaat om elke afwijking van de nulhypothese te detecteren. Ze worden daarom het meest gebruikt en ten zeerste aangeraden.\nHet is **nooit toegelaten** om een tweezijdige toets in een eenzijdige\ntoets om te zetten **op basis van wat men observeert in de gegevens**!\nAnders wordt de type I fout van de toetsingsstrategie niet correct gecontroleerd.\n\nDat wordt geïllustreerd in de onderstaande simulatie.\nWe evalueren twee strategieën, de correcte tweezijdige test en een test waar we eenzijdig toetsen op basis van het teken van het geobserveerde effect.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(115)\nmu <- 0\nsigma <- 9.0\nnSim <- 1000\nalpha <- 0.05\nn <- 15\npvalsCor <-\n\tpvalsInCor <-\n\tarray(0,nSim)\n\nfor (i in 1:nSim)\n{\n\tx <- rnorm(n, mean = mu, sd = sigma)\n\tpvalsCor[i] <- t.test(x)$p.value\n\n\tif (mean(x)<0)\n\t\tpvalsInCor[i] <- t.test(\n\t\t\tx,\n\t\t\talternative=\"less\")$p.value else\n\t\tpvalsInCor[i] <- t.test(\n\t\t\tx,\n\t\t\talternative=\"greater\")$p.value\n}\nmean(pvalsCor < 0.05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.049\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(pvalsInCor < 0.05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.106\n```\n\n\n:::\n:::\n\n\nWe zien inderdaad dat de type I fout correct gecontroleerd wordt op het nominaal significantie-niveau $\\alpha$ wanneer we tweezijdig testen en dat dit helemaal niet het geval is wanneer we eenzijdige toetsen op basis van het teken van het geobserveerde effect.\n\n## Geclusterde metingen\n\n<iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/3sA_YZpkSXg\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n\nDe data in studies zijn niet altijd onafhankelijk. Dat heeft zijn consequenties voor het schatten van de standaard errors.\nBeschouw een studiedesign waarbij voor $n$ planten, tijdens een bepaalde fase in de groei, de expressie van een bepaald gen 2 maal wordt gemeten om meetfouten te drukken. Men is geïnteresseerd in de gemiddelde genexpressie.\nAls we met $Y_{i1}$ en $Y_{i2}$ de eerste en tweede meting, respectievelijk, voorstellen\nvoor plant $i=1,...,n$, dan kunnen we dit schatten als\n\n\\begin{equation*}\n\\bar Y = \\sum_{i=1}^n \\frac{Y_{i1}+Y_{i2}}{2n}\n\\end{equation*}\n\nIn de onderstelling dat de $n$ planten onafhankelijk van elkaar gekozen\nwerden en de eerste en tweede metingen even variabel zijn (d.w.z. $\\text{Var}(Y_{i1})=\\text{Var}(Y_{i2})=\\sigma^2$), bedraagt de variantie op dit\nsteekproefgemiddelde\n\n\\begin{eqnarray*}\n\\text{Var}(\\bar Y)&=&\\sum_{i=1}^n \\frac{\\text{Var}(Y_{i1}+Y_{i2})}{4n^2} \\\\\n&=&\\sum_{i=1}^n \\frac{\\sigma^2+\\sigma^2+2\\text{Cor}(Y_{i1},Y_{i2})\\sigma^2}{%\n4n^2} \\\\\n&=&\\frac{\\sigma^2}{2n}\\{1+\\text{Cor}(Y_{1},Y_{2})\\}\n\\end{eqnarray*}\n\nVermits verschillende metingen afkomstig van eenzelfde plant doorgaans\npositief met elkaar gecorreleerd zijn, is de standard error op $\\bar Y$ dus\ngroter dan wanneer de $2n$ metingen van $2n$ verschillende, onafhankelijke\nplanten afkomstig zouden zijn. Dat is omdat, gegeven de eerste meting $Y_{i1}$, de tweede meting $Y_{i2}$ geen volledig nieuwe informatie toevoegt en er bijgevolg minder informatie beschikbaar is om het gemiddelde te\nschatten dan wanneer alle gegevens van verschillende planten afkomstig\nwaren. In het bijzonder, wanneer $\\text{Cor}(Y_{1},Y_{2})=1$, dan levert de tweede meting geen nieuwe informatie en bekomt men eenzelfde nauwkeurigheid als wanneer men slechts 1 meting per plant had bekomen. Wanneer $\\text{Cor}(Y_{1},Y_{2})=0$, dan levert de tweede meting volledig nieuwe informatie en bekomt men eenzelfde nauwkeurigheid als wanneer men 1 meting had bekomen voor $2n$ i.p.v. $n$ verschillende planten. Vermits\n\n$$\\frac{\\sigma^2}{2n}\\{1+\\text{Cor}(Y_{1},Y_{2})\\}\\geq \\frac{\\sigma^2}{2n}$$\n\n*Wanneer de correlatie tussen herhaalde genexpressie metingen positief is (hetgeen we verwachten), zal men in de praktijk meer preciese resultaten bekomen door 1 meting te bepalen voor $2n$ verschillende planten dan door 2 metingen te bepalen voor $n$ verschillende planten.*\n\n<!---break-->\n\n### Captopril\n\n<iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/dRygy_BePIU\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n\nDe metingen in de captopril voorbeeld zijn eveneens geclusterd. We hebben immers twee systolische bloeddrukmetingen per patiënt.\n1 meting voor en 1 meting na het toedienen van captopril.\nWe beogen om de gemiddelde bloeddrukverandering $\\mu$ te schatten a.d.h.v. de gegevens\n\n$$(Y_{i1} , Y_{i2}),$$\n\nvoor subjecten $i = 1, ..., n$.\nEn we bekomen de volgende schatting:\n\n$$\\bar X = \\sum_{i=1}^n \\frac{Y_{i2}-Y_{i1}}{n}$$\n\nUit de rekenregels voor de variantie weten we dat\n\n\\begin{eqnarray*}\n\\text{Var}\\left[\\bar X\\right]&=&\\sum_{i=1}^n \\frac{\\text{Var}\\left[Y_{i1}-Y_{i2}\\right]}{n^2}\\\\\n&=&\\sum_{i=1}^n \\frac{\\sigma^2_1+\\sigma^2_2-2\\text{Cor}\\left[Y_{i1},Y_{i2}\\right]\\sigma_1\\sigma_2}{n^2}\\\\\n&=&\\frac{\\sigma^2_1+\\sigma^2_2-2\\text{Cor}\\left[Y_{i1},Y_{i2}\\right]\\sigma_1\\sigma_2}{n},\\\\\n\\end{eqnarray*}\n\nIn R kunnen we dit als volgt berekenen:\n\n::: {.cell}\n\n```{.r .cell-code}\n#functie var op een matrix berekent varianties sigma_1^2, sigma_2^2\n#covariantie sigma_{12}\nvars <- var(captopril[,c(\"SBPb\",\"SBPa\")])\nvars\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         SBPb     SBPa\nSBPb 422.9238 370.7857\nSBPa 370.7857 400.1429\n```\n\n\n:::\n\n```{.r .cell-code}\ncor(captopril$SBPa,captopril$SBPb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9013312\n```\n\n\n:::\n\n```{.r .cell-code}\nvarXbarDelta <- (vars[1,1]+vars[2,2]-2*vars[1,2])/15\nsqrt(varXbarDelta)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.330883\n```\n\n\n:::\n:::\n\n\nWe zien dat de metingen heel sterk gecorreleerd zijn, waardoor de variantie op het verschil veel lager zal liggen dan op de originele metingen.\n\nGezien we voor elke patiënt twee metingen hebben bestaat een alternatieve methode om de standard error te bepalen erin om alle gecorreleerde metingen tot 1 meting te reduceren. Merk op dat we dit enkel kunnen doen voor gepaarde metingen. Alle resulterende metingen zijn dan onafhankelijk.\nConcreet kunnen we voor elke patiënt $i$ in de steekproef het bloeddrukverschil berekenen:\n\n$$X_{i}=Y_{ai}-Y_{bi}$$\n\nen vervolgens standard error op $\\bar X$.\nIn het captopril voorbeeld wordt de schatting\n\n::: {.cell}\n\n```{.r .cell-code}\nsd(delta)/sqrt(15)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.330883\n```\n\n\n:::\n:::\n\n\nWe zien dat we exact dezelfde schatting voor de standard error bekomen.\n\nVerder zien we ook dat het design een groot voordeel heeft:\nAangezien de bloeddrukmetingen voor en na het toedienen van captopril sterk positief gecorreleerd zijn is de variantie van het verschil veel lager dan deze op de originele bloeddrukmetingen.\nIedere patiënt in de studie dient immers als zijn eigen controle en op die manier kunnen we de variabiliteit in de bloeddrukmetingen tussen patiënten uit de analyse verwijderen!\n\nEen gepaard experiment is eigenlijk een speciale vorm van een randomized complete block design:\n\n- Elke persoon is een blok en\n- Elke behandeling is getest binnen blok: een controle bloeddrukmeting en een bloeddrukmeting na toedienen van captopril\n- Tussen de blokken is er inderdaad een grote bron van variabiliteit: e.g.   er is een grote variabiliteit tussen blokken! Personen met een hoge bloeddruk voor het toedienen van captopril hebben meestal ook nog steeds een hoge bloeddruk na de captopril behandeling. De standaarddeviatie in de bloeddruk tussen patiënten voor toedienen van captopril bedraagt  20.6 mmHg.\n\n- We kunnen het effect van captopril in het gepaard design schatten binnen patient. Door het blokdesign kunnen we dus de variabiliteit tussen patiënten uit de analyse weren. Voor een gepaard design kunnen we dat door b.v. doen a.d.h.v. een analyse op de bloeddrukverschillen te doen. De standaard deviatie op de bloeddruk verschillen tussen patiënten is inderdaad veel lager 9.03.\n\n<!---break-->\n\nHoe kunnen we het captopril experiment verder verbeteren?\n\n<iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/3sy1XHUBJFI\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n\n## Two-sample t-test\n\n<iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/wwMk1lYvZ5o\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n\nEen two-sample t-test is een statistische toets die werd ontwikkeld om verschillen in gemiddelde te detecteren tussen twee onafhankelijke groepen. We introduceren eerst een motiverende dataset.\nMen vermoedt dat hinderlijke geur onder de oksels (bromhidrosis) wordt veroorzaakt door specifieke microorganismen die behoren tot de groep van de *Corynebacterium spp.*. Het is immers niet het zweet dat de geur veroorzaakt, maar de geur is het resultaat van specifieke bacteriën die het zweet metaboliseren. Een andere sterk abundante groep wordt gevormd door de *Staphylococcus spp.*. In de CMET onderzoeksgroep van de Universiteit Gent wordt onderzoek verricht naar de mogelijkheid van microbiële transplanties in de oksels om mensen van de hinderlijke okselgeur te verlossen. Deze therapie bestaat erin om eerst het oksel-microbioom te verwijderen door een lokale antibiotica behandeling, en vervolgens via een microbiële transplantie de populatie te beïnvloeden. (zie: <https://youtu.be/9RIFyqLXdVw> )\n\n  De primaire onderzoeksvraag: leidt de microbiële transplantatie na zes weken tot een verandering in de relatieve abundantie van *Staphylococcus spp.* in het oksel microbioom in vergelijking met een placebo behandeling die enkel bestaat uit een antibiotica behandeling?\n  Twintig personen met een hinderlijke okselgeur worden willekeurig toegekend aan twee behandelingsgroepen: placebo (enkel antibiotica) en transplantie (antibiotica, gevolgd door microbiële transplantatie).\n  Zes weken na de start van de behandeling wordt een staal van de huid uit de okselholte genomen en worden de relatieve abundanties van *Staphylococcus spp.* en *Corynebacterium spp.* in het microbioom gemeten via DGGE (*Denaturing Gradient Gel Electrophoresis*).\n\n  De dataset bevat de variabelen Staph en Cor die de relatieve abundanties (%) weergeven van *Staphylococcus spp.* en *Corynebacterium spp.* De variabele Rel werd berekend als\n  \n  $$\\text{Rel}=\\frac{\\text{Staph}}{\\text{Staph}+\\text{Cor}}.$$\n\nDeze variabele is het relatief aandeel van *Staphylococcus spp.* op het totaal aantal *Staphylococcus spp.* en *Corynebacterium spp.*.\n\nWe gaan hiervoor opnieuw de microbioom data inlezen.\nDe resultaten worden weergegeven in Figuur -@fig-okselBox.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nap <- read_csv(\"https://raw.githubusercontent.com/GTPB/PSLS20/master/data/armpit.csv\")\nhead(ap)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 2\n  trt       rel\n  <chr>   <dbl>\n1 placebo  55.0\n2 placebo  31.8\n3 placebo  41.1\n4 placebo  59.5\n5 placebo  63.6\n6 placebo  41.5\n```\n\n\n:::\n\n```{.r .cell-code}\nap |>\n  ggplot(aes(x = trt, y = rel)) +\n  geom_boxplot() +\n  geom_jitter() +\n  xlab(\"Relatieve abundantie\") +\n  ylab(\"Behandeling\")\n```\n\n::: {.cell-output-display}\n![Boxplot van de relatieve Staphylococcus spp. abundantie t.o.v. het totaal van Staphylococcus spp. en Corynebacterium spp., voor beide behandelingsgroepen.](05-StatistischeBesluitvorming_files/figure-html/fig-okselBox-1.png){#fig-okselBox fig-align='center' width=100%}\n:::\n:::\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nap$trt <- as.factor(ap$trt) #zet charactervector om in factor\nap |>\n  ggplot(aes(sample = rel)) +\n  geom_qq() +\n  geom_qq_line() +\n  facet_grid(.~trt) +\n  ylab(\"Relatieve abundantie\")\n```\n\n::: {.cell-output-display}\n![QQ-plots van relatieve Staphylococcus spp. abundantie t.o.v. het totaal van Staphylococcus spp. en Corynebacterium spp.](05-StatistischeBesluitvorming_files/figure-html/fig-okselQQ-1.png){#fig-okselQQ fig-align='center' width=100%}\n:::\n:::\n\n\nNormaliteit van de data in beide groepen wordt ook nagegaan d.m.v. QQ-plots (zie Figuur -@fig-okselQQ). De QQ-plots geven geen te grote afwijkingen weer van normaliteit.\n\nWe introduceren eerst de notatie.\n\n<!---break-->\n\n### Notatie\n\n<iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/dSn4JYHNA6U\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n\nStel $Y_{ij}$ de uitkomst van observatie $i=1,\\ldots, n_j$ uit populatie $j=1,2$. We zullen dikwijls de term **behandeling** of **groep** gebruiken in plaats van populatie, zelfs wanneer de twee populaties niet geïnterpreteerd kunnen worden als behandelingen. Beschouw het als een (misgroeide) conventie. In de context van het voorbeeld is behandeling $j=1$ de microbiële transplantatie en behandeling $j=2$ de placebo behandeling.\n\nWe veronderstellen\n\n$$Y_{ij}\\text{ i.i.d. } N(\\mu_j,\\sigma^2)\\;\\;\\;i=1,\\ldots,n_i\\;j=1,2.$$\n\nMerk op dat dit inhoudt dat gelijke varianties verondersteld worden. De eigenschap van gelijke varianties wordt ook aangeduid met de term **homoskedasticiteit**, en ongelijke varianties met **heteroskedasticiteit**.\n\nWe zijn geïnteresseerd in het testen van de nulhypothese\n\n$$ H_0: \\mu_1 = \\mu_2 $$\n\ntegenover de alternatieve hypothese\n\n$$  H_1: \\mu_1 \\neq \\mu_2 .$$\n\nDe alternatieve hypothese drukt dus de onderzoeksvraag uit: een verschil in relatieve abundantie van *Staphylococcus spp.* na microbiële transplantatie t.o.v. de placebo behandeling.  \nDe nul en alternatieve hypothese kunnen ook worden uitgedrukt in termen van de effectgrootte tussen behandeling en placebo groep $\\mu_1-\\mu_2$:\n\n$$H_0: \\mu_1-\\mu_2 = 0,$$\n\n$$H_1: \\mu_1-\\mu_2 \\neq 0.$$\n\nWe kunnen de effectgrootte in het experiment schatten a.d.h.v. de steekproefgemiddeldes:\n\n$$\\hat \\mu_1-\\hat \\mu_2=\\bar Y_1 -\\bar Y_2.$$\n\nGezien de experimentele eenheden onafhankelijk zijn, zijn de steekproefgemiddeldes dat ook en is de variantie op het verschil:\n\n$$\\text{Var}_{\\bar Y_1 -\\bar Y_2}=\\frac{\\sigma^2}{n_1}+\\frac{\\sigma^2}{n_2}=\\sigma^2 \\left(\\frac{1}{n_1}+\\frac{1}{n_2}\\right).$$\n\nDe standard error is bijgevolg:\n\n$$\\sigma_{\\bar Y_1 -\\bar Y_2}=\\sigma\\sqrt{\\frac{1}{n_1}+\\frac{1}{n_2}}.$$\n\n\nWe zouden de variantie apart kunnen schatten in elke groep aan de hand van de steekproefvariatie, maar als we gelijkheid van variantie kunnen veronderstellen kan de variantie meer precies worden geschat door gebruik te maken van alle gegevens in beide groepen.\nDeze variatieschatter wordt ook de gepoolde variantieschatter genoemd: $S^2_p$.\n\nOp basis van de observaties uit de eerste groep kan $\\sigma^2_1$ geschat worden als\n\n$$S_1^2 = \\frac{1}{n_1-1}\\sum_{i=1}^{n_1} (Y_{i1}-\\bar{Y}_1)^2.$$\n\nAnaloog: op basis van de observaties uit de tweede groep kan $\\sigma^2_2$ geschat worden als\n\n$$S_2^2 = \\frac{1}{n_2-1}\\sum_{i=1}^{n_2} (Y_{i2}-\\bar{Y}_2)^2.$$\n\nMerk op dat we homoscedasticiteit veronderstellen, $\\sigma_1^2=\\sigma_2^2=\\sigma^2$. Dus $S_1^2$ en $S_2^2$ zijn schatters zijn voor dezelfde parameter $\\sigma^2$. Daarom kunnen ze gezamenlijk gebruikt worden om tot één schatter te komen die alle $n_1+n_2$ observaties gebruikt:\n\n$$  S_p^2 = \\frac{n_1-1}{n_1+n_2-2} S_1^2 + \\frac{n_2-1}{n_1+n_2-2} S_2^2 = \\frac{1}{n_1+n_2-2}\\sum_{j=1}^2\\sum_{i=1}^{n_j} (Y_{ij} - \\bar{Y}_j)^2.$$\n\nDe gepoolde variantieschatter wordt dus geschat door gebruik te maken van de kwadratische afwijkingen tussen de observaties en hun groepsgemiddelde en dat te delen door het aantal vrijheidsgraden $n_1+n_2-2$^[We hebben $n_1+n_2$ observaties (vrijheidsgraden) in het experiment, om de gepoolde variantie te schatten hebben we echter 2 vrijheidsgraden verloren aangezien we eerst het gemiddelde in elke groep dienden te bepalen om de variantie te kunnen schatten.].\n\nNu we de effectgrootte en de standard error op de effectgrootte hebben kunnen schatten, kunnen we opnieuw een t-statistiek definiëren (two-sample $t$-teststatistiek):\n\n$$T = \\frac{\\bar{Y}_1-\\bar{Y}_2}{\\sqrt{\\frac{S_p^2}{n_1}+\\frac{S_p^2}{n_2}}} =\n  \\frac{\\bar{Y}_1 - \\bar{Y}_2}{S_p\\sqrt{\\frac{1}{n_1}+\\frac{1}{n_2}}}.$$\n\nAls de data onafhankelijk zijn, de steekproefgemiddelden normaal verdeeld zijn en de variantie in beide groepen gelijk zijn, dan kan men aantonen de teststatistiek T opnieuw een t-verdeling volgt met $n_1+n_2-2$ vrijheidsgraden onder de nulhypothese.\n\nAangezien de alternatieve hypothese $H_1: \\mu_1 \\neq \\mu_2$ impliceert dat de probabiliteitsmassa van de distributie van $T$ onder $H_1$ verschuift naar hogere of lagere waarden, zullen we $H_0$ wensen te verwerpen ten gunste van $H_1$ voor grote absolute waarde van de teststatistiek. De $p$-waarde wordt dus\n\n\\begin{eqnarray*}\n  p&=&\\text{P}_0\\left[T\\leq -|t|\\right] + \\text{P}_0\\left[T\\geq |t|\\right]\\\\\n  &=&\\text{P}_0\\left[\\vert T\\vert \\geq \\vert t \\vert\\right]\\\\\n  &=&\\text{P}_0\\left[T \\geq \\vert t \\vert\\right]\\times 2\\\\\n  &=& 2\\times(1-F_T(\\vert t\\vert;n_1+n_2-2)),\n\\end{eqnarray*}\n\nmet $F_T(\\cdot;n_1+n_2-2)$ de cumulatieve distributiefunctie van $t_{n_1+n_2-2}$.\n\n<!---break-->\n\n### Oksel-voorbeeld\n\n<iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/KBn8uD59p_Q\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n\n De onderzoeksvraag van het oksels-voorbeeld kan vertaald worden in een nulhypothese en een alternatieve hypothese.\n\n De nulhypothese verwoordt de stelling dat de behandeling geen effect heeft op de gemiddelde relatieve abundantie van *Staphylococcus spp.*.\n\n Indien $\\mu_1$ en $\\mu_2$ de gemiddelde abundanties voorstellen in respectievelijk de transplantatie groep en de placebo groep, dan schrijven we\n\n$$H_0: \\mu_1=\\mu_2.$$\n\n De alternatieve hypothese correspondeert met wat we wensen te bewijzen aan de hand van de experimentele data: een verschil in gemiddelde abundantie van   *Staphylococcus spp.* in de transplantatie groep i.v.m. de placebo groep. Dus\n\n$$H_1: \\mu_1\\neq \\mu_2.$$\n\n\nDe R software heeft een specifieke functie voor het uitvoeren van deze $t$-test.\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(\n\trel ~ trt,\n\tdata = ap,\n\tvar.equal=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  rel by trt\nt = -5.0334, df = 18, p-value = 8.638e-05\nalternative hypothesis: true difference in means between group placebo and group transplant is not equal to 0\n95 percent confidence interval:\n -31.53191 -12.96072\nsample estimates:\n   mean in group placebo mean in group transplant \n                44.15496                 66.40127 \n```\n\n\n:::\n:::\n\n\nUit deze analyse lezen we $p\\approx 8.6e-05<<0.05$.\n\nDus op het $5\\%$ significantieniveau verwerpen we de nulhypothese ten voordele van de alternatieve en besluiten we dat de gemiddelde abundantie van  *Staphylococcus spp.* extreem significant hoger is in de transplantatie groep dan in de placebo groep^[Merk op dat we de richting \"significant hoger is in de transplantatie groep\" afleiden uit de groepsgemiddelden in de output en/of het BI].   \n\nIndien de transplantatie geen effect heeft op de gemiddelde  abundantie van *Staphylococcus spp.*, dan is er de kans om een teststatistiek te bekomen in een willekeurige steekproef die minstens zo extreem is als deze die wij geobserveerd hebben minder dan 9 op  $100000$!\n\nDit is uiterst zeldzaam onder de hypothese dat $H_0$ waar is, en het is kleiner dan $5\\%$ (het significantieniveau). Indien $H_1$ waar zou zijn, dan verwachten we grotere absolute waarden van de teststatistiek en verwachten we dus ook kleine $p$-waarden. Om deze reden wensen we niet verder te geloven dat $H_0$ waar is, en besluiten we dat er veel evidentie in de steekproefdata zit om te besluiten dat $H_1$ waar is op het $5\\%$ significantieniveau.\n\n**Good statistical practice** houdt ook in dat niet enkel de $p$-waarde van de hypothesetest wordt gerapporteerd, maar dat ook de gemiddelden en een maat voor de betrouwbaarheid van de schattingen (bv. BI) worden gerapporteerd.\n\n**Conclusie**\nGemiddeld is de relatieve abundantie van *Staphylococcus spp.* in het microbioom van de oksel in de transplantatie groep extreem significant verschillend van dat in de controle groep ($p<<0.001$). De relatieve  abundantie van *Staphylococcus spp.* is gemiddeld -22.2% hoger in de transplantie groep dan in de controle groep (95\\% BI [-31.5,-13.0]%).\n\n## Aannames\n\n<iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/JvIi_TO6OIA\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n\nIn de voorgaande secties hebben we t-testen geïntroduceerd en de geldigheid ervan hangt af van enkele distributionele veronderstellingen:\n\n- Onafhankelijke gegevens (design)\n- One-sample t-test: normaliteit van de steekproefobservaties\n- Paired t-test: normaliteit van de verschillen tussen de gepaarde observaties\n- Two-sample t-test: normaliteit van de steekproefobservaties in beide groepen, en gelijkheid van varianties.\n\nIndien niet voldaan is aan de veronderstellingen, is de t-distributie niet noodzakelijk de correcte nuldistributie, en bijgevolg is er geen garantie dat de p-waarde en kritieke waarden correct zijn.\n\nOok voor de constructie van het betrouwbaarheidsinterval van het gemiddelde hebben we beroep gedaan op de veronderstelling van normaliteit. De normaliteitsveronderstelling was nodig om kwantielen uit de t-verdeling te kunnen gebruiken bij het opstellen van de boven- en ondergrens, en de correcte probabiliteitsinterpretatie van het betrouwbaarheidsinterval hangt hiervan af.\n\n\n### Nagaan van de veronderstelling van Normaliteit\n\nNormaliteit kan via de volgende methoden nagegaan worden.\n\n**Boxplots en histogrammen**\n\nBeide figuren laten toe om een idee te vormen over de vorm van de distributie: symmetrie, outliers. \\ldots\n\n**QQ-plots**\n\n Deze plots laten toe om op een grafische wijze na te gaan in welke mate steekproefobservaties zich gedragen als een vooropgestelde distributie.\n\n**Hypothesetesten (goodness-of-fit test)**\n\nGoodness-of-fit testen zijn statistische hypothesetesten die ontwikkeld zijn voor het testen van de nulhypothese dat de steekproefobservaties uit een vooropgestelde distributie getrokken zijn (hier: normale distributie). De alternatieve hypothese is meestal de negatie van de nulhypothese (hier: geen normaliteit). Bekende testen zijn: Kolmogorov-Smirnov, Shapiro-Wilk en Anderson-Darling.\n\nOp het eerste zicht lijkt een goodness-of-fit test een gemakkelijke en zinvolle oplossing. De methode geeft een $p$-waarde en deze laat onmiddellijk toe om te besluiten of de data normaal verdeeld zijn.\n\n Er is echter kritiek te leveren op deze aanpak:\n\n-  indien $p\\geq \\alpha$, dan is normaliteit niet bewezen! Het zegt enkel dat er onvoldoende evidentie is tegen de veronderstelling van normaliteit. In een kleine steekproef is de kracht van een test meestal klein.\n- indien $p<\\alpha$, dan mag wel besloten worden om de nulhypothese te verwerpen en mag dus besloten worden dat de data niet normaal verdeeld zijn, maar soms is een afwijking van normaliteit niet zo erg.  \n\n**Algemeen advies**:\n Start met een grafische exploratie van de data (boxplots, histogrammen en QQ-plots) en houdt hierbij steeds de steekproefgrootte in het achterhoofd om te vermijden dat je de figuren zou overinterpreteren. Als je twijfelt kan je gebruik maken van simulaties waarbij je nieuwe steekproeven simuleert met eenzelfde steekproefgrootte en data die uit de Normaal verdeling komt met eenzelfde gemiddelde en variantie als wat in de steekproef werd geobserveerd.\n\n Indien een afwijking van normaliteit wordt vastgesteld, tracht dan na te gaan (bv. via literatuur) of de statistische methode die je wenst toe te passen, gevoelig is voor dergelijke afwijkingen (een t-test is bijvoorbeeld vrij ongevoelig voor afwijkingen van Normaliteit als de afwijkingen symmetrisch zijn). Eventueel kan je ook beroep doen op de centrale limietstelling.\n\n### Nagaan van homoscedasticiteit\n\nDat kan opnieuw via boxplots.\nDe grootte van de box is de interkwartiel range (IQR), een robuuste schatter voor de variantie (zie Sectie -@sec-spreiding).\nAls de verschillen tussen de IQR range van beide groepen niet te groot is, kan men besluiten dat de data homoscedastisch zijn.\nOpnieuw kan inzicht gekregen worden in dergelijke plots door gebruik te maken van simulaties (zie Oefeningen).\nMen kan eveneens een formele F-test gebruiken om de varianties te vergelijken (zie oefeningen), maar hiervoor geldt dezelfde kritiek als voor het testen van normaliteit (zie vorige sectie).\n\nAls er bij het vergelijken van gemiddelden tussen twee groepen niet aan homoscedasticiteit is voldaan, kan je gebruik maken van de Welch two-sample T-test.\nHierbij wordt de gepoolde variantieschatter niet langer gebruikt.\n\n$$T =  \\frac{\\bar{Y}_1 - \\bar{Y}_2}{\\sqrt{\\frac{S^2_1}{n_1}+\\frac{S^2_2}{n_2}}}$$\n\nwaarbij $S^2_1$ en $S^2_2$ de steekproefvarianties zijn in beide groepen.\n\nDeze statistiek volgt bij benadering een t-verdeling met een aantal vrijheidsgraden dat ligt tussen het kleinste aantal observaties $\\text{min}(n_1-1,n_2-1)$ en $n_1+n_2-2$.\nDe vrijheidsgraden worden in R berekend via de Welch–Satterthwaite benadering.\nDat kan door in de `t.test` functie het argument `var.equal=FALSE` te zetten.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(\n\trel ~ trt,\n\tdata = ap,\n\tvar.equal=FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  rel by trt\nt = -5.0334, df = 15.892, p-value = 0.0001249\nalternative hypothesis: true difference in means between group placebo and group transplant is not equal to 0\n95 percent confidence interval:\n -31.62100 -12.87163\nsample estimates:\n   mean in group placebo mean in group transplant \n                44.15496                 66.40127 \n```\n\n\n:::\n:::\n\n\nMerk op dat we in de output zien dat een Welch T-test is uitgevoerd aan de titel boven de analyse.\nVerder zien we dat voor dit voorbeeld de aangepaste vrijheidsgraden $df = 17.876$ bijna gelijk zijn aan de vrijheidsgraden van de klassieke T-test, omdat de varianties ongeveer gelijk zijn.\n\n## Wat rapporteren?\n\n<iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/F1Qum-uBrq0\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n\n- In de wetenschappelijke literatuur is er een overdreven aandacht voor p-waarden.\n- Nochtans is het interessanter om een schatting te rapporteren samen met een betrouwbaarheidsinterval (dan met een p-waarde).\n\n**Vuistregel**:\nRapporteer een schatting steeds samen met een betrouwbaarheidsinterval (en een p-waarde), want\n\n1. Het resultaat van een toets kan veelal uit een betrouwbaarheidsinterval worden afgeleid;\n2. Dit laat toe om te oordelen of het resultaat ook **wetenschappelijk van belang** is.\n\n### Reden 1: Relatie toetsen en betrouwbaarheidsintervallen\nStel dat we voor een zekere parameter $\\theta$ (bvb. een\npopulatiegemiddelde, verschil in populatiegemiddelden, odds ratio,\nregressieparameter) de nulhypothese wensen te toetsen dat $H_0 : \\theta=\n\\theta_0$ versus het alternatief $H_A : \\theta \\neq \\theta_0$ voor een zeker\ngetal $\\theta_0$. Dan kan men aantonen dat men deze tweezijdige\ntoetsingsprocedure kan uitvoeren op het $\\alpha 100\\%$ significantieniveau\ndoor de nulhypothese te verwerpen als en slechts als het $(1-\\alpha)100\\%$\nbetrouwbaarheidsinterval voor $\\theta$ het getal $\\theta_0$ niet omvat. Met\nandere woorden, het $(1-\\alpha)100\\%$ betrouwbaarheidsinterval voor $\\theta$\nbevat alle getallen $\\theta_0$ zodat de tweezijdige toets van $H_0 : \\theta=\n\\theta_0$ versus $H_1 : \\theta \\neq \\theta_0$ de nulhypothese niet verwerpt.\n\n### Reden 2: Statistische significantie versus wetenschappelijke relevantie\n\nEen betrouwbaarheidsinterval laat toe om zowel statistische significantie als wetenschappelijk belang van een resultaat te interpreteren.\n\nStel dat experimentele behandeling *significant betere* respons oplevert dan standaard/placebo.\nEen associatie is *statistisch significant* als P $< \\alpha$,\nde data dragen m.a.w. voldoende bewijskracht  om te besluiten dat er een associatie is. Dan blijft het mogelijk dat het effect *wetenschappelijk irrelevant* is.\nMet betrouwbaarheidsintervallen kunnen we dit wel evalueren.\n\nMaar, dat laat echter nog veel subjectiviteit en manipulatie toe. Onderzoekers hopen in de praktijk immers wetenschappelijk belangrijke vondsten te maken en kunnen daarom geneigd zijn om hun oordeel over wat wetenschappelijk belangrijk is, wijzigen in functie van het bekomen betrouwbaarheidsinterval. Om dit te vermijden is het wenselijk dat wetenschappers a priori, d.i. vooraleer de gegevens verzameld werden, hun oordeel over wetenschappelijke relevantie uitdrukken.\n\n\n## Equivalentie-intervallen\n\nBetrouwbaarheidsintervallen kunnen ook worden gebruikt om na te gaan of twee interventies **wetenschappelijk equivalent** zijn.\nTwee interventies worden **wetenschappelijk equivalent** genoemd als het verschil tussen de populatiegemiddelden\n$\\mu_1$ en $\\mu_2$ van hun uitkomsten $X_1$ en $X_2$ in een\nequivalentie-interval ligt (dat 0 zal omvatten), bijvoorbeeld:\n\n\\begin{equation*}\n(\\mu_1 - \\mu_2) \\in [E_1, E_2]\n\\end{equation*}\n\nIn de meeste gevallen worden $E_1$ en $E_2$ symmetrisch rond nul gekozen, in\nwelk geval $E_1=-\\Delta$ en $E_2=\\Delta$ voor gegeven $\\Delta$. Het\n(wetenschappelijk) equivalentie-interval wordt dan gegeven door alle koppels $(\\mu_1,\\mu_2)$ waarvoor\n\n\\begin{equation*}\n|\\mu_1 - \\mu_2| < \\Delta\n\\end{equation*}\n\nTwee interventies zijn met andere woorden klinisch equivalent\nwanneer hun verschil in effect verwaarloosbaar klein is vanuit wetenschappelijk\noogpunt.\n\nIn het vervolg van deze sectie zullen we nagaan of de gemiddelden van 2 onafhankelijke\npopulaties wetenschappelijk equivalent zijn (of wetenschappelijk niet significant van elkaar\nverschillen). Een eerste stap in dit proces is om op basis van louter\nwetenschappelijk overwegingen een interval op te stellen waarbinnen het verschil $\\mu_1-\\mu_2$ verwaarloosbaar klein kan worden genoemd. Dit gebeurt met hulp van een deskundige die kan oordelen over het belang van een gegeven\neffectgrootte. Vervolgens wordt het gemiddeld verschil in uitkomst onder\nbeide interventies geschat op basis van de gegevens. Nagaan of dit verschil\nin het equivalentie-interval gelegen is, volstaat op zich niet om wetenschappelijke\nequivalentie te kunnen besluiten vermits een klein/groot verschil louter\nhet gevolg kan zijn van biologische variatie. Een logische stap is daarom\neen bijhorend 95\\% betrouwbaarheidsinterval voor $\\mu_1 - \\mu_2$ te berekenen op basis van de beschikbare gegevens (gepaard, ongepaard, ...). De wetenschappelijke equivalentie zal nu bepaald worden door de ligging van het\nbetrouwbaarheidsinterval te vergelijken met het interval van wetenschappelijke\nequivalentie.\n\nHet zou verkeerd zijn om wetenschappelijke equivalentie te besluiten zodra het\nequivalentie-interval volledig omsloten is door het 95%\nbetrouwbaarheidsinterval. Inderdaad, kleine steekproeven produceren brede\nbetrouwbaarheidsintervallen zodat men op die manier in kleine steekproeven\ngemakkelijk equivalentie zou besluiten louter wegens gebrek aan\ninformatie. We volgen daarom de volgende strategie. Noem $O$ de ondergrens\nen $B$ de bovengrens van het 95% betrouwbaarheidsinterval voor $\\mu_1-\\mu_2$.\n\n1. Als $E_1 < O < B < E_2$, dan is het verschil tussen de populatiegemiddelden met minstens 95\\% kans binnen de grenzen van wetenschappelijke equivalentie gelegen. Men kan dan met minstens 95\\% zekerheid besluiten dat de 2 interventies inderdaad wetenschappelijk equivalent zijn.\n\n2.  Als $E_2 < O$ dan kan men met minstens 95\\% zekerheid besluiten dat $\\mu_1$ wetenschappelijk significant groter is dan $\\mu_2$. (In dit geval is  $\\mu_1$ automatisch ook statistisch significant groter dan $\\mu_2$ op het 2-zijdig significantieniveau 5\\%).\n\n3. Als $B < E_1$ dan kan men met minstens 95\\% zekerheid besluiten dat $\\mu_1$ wetenschappelijk significant kleiner is dan $\\mu_2.$\n\nHet resultaat kan ook minder duidelijk zijn.\n\n1. Als $O < E_1 < E_2 < B$ dan is er te weinig informatie om ook maar iets betekenisvol te kunnen besluiten: meer gegevens zijn nodig.\n2. Als $O < E_1 < B < E_2$ dan kan men op het 5% significantieniveau besluiten dat $\\mu_1$ *niet* wetenschappelijk groter is dan $\\mu_2$. In dat geval zijn zowel de opties wetenschappelijk equivalent met $\\mu_2$ als wetenschappelijk significant kleiner dan $\\mu_2$ niet uit te sluiten met 95% zekerheid.\n3. Analoog voor de symmetrische situatie waarbij $E_1 < O < E_2 < B.$\n\nIn asthmastudies legt men bijvoorbeeld **op voorhand vast** dat een verschil in Peak Expiratory Flow (PEF) van 15 l/min klinisch onbelangrijk is. Men bepaald m.a.w. een equivalentie-interval: [-15,15] l/min. Een 95\\% BI van [-10,-5] l/min voor gemiddeld verschil in PEF tussen twee geneesmiddelen Formoterol en Salbutamol wijst op een onbelangrijk effect, equivalentie. Het betrouwbaarheidsinterval geeft weer hoe groot het verschil kan zijn.\nAls men een BI van [-25,-16] l/min had bekomen dan kon men besluiten dat het geneesmiddel Formoterol minder efficiënt is gezien het gemiddeld gezien PEF waarden oplevert die wetenschappelijk significant lager zijn dan wanneer Salbutamol wordt toegediend. Als het [-20,-5] l/min zou zijn, dan is er ambiguïteit.\n",
    "supporting": [
      "05-StatistischeBesluitvorming_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}