{
  "hash": "f75cce2c2cdea5f6b89856187bd2bffc",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"2. Concepten\"\nauthor: \"Lieven Clement\"\ndate: \"statOmics, Ghent University (https://statomics.github.io)\"\nformat:\n  html:\n    toc: true\n    number-sections: true\n    theme: cosmo\n    highlight-style: tango\n    code-tools: true\n    embed-resources: true\n---\n\n# Introductie\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](02-concepts_files/figure-html/pop2Samp2Pop-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n## Proefopzet (1)\n   - Scope: De onderzoeker bepaalt de **populatie** naar waar ze de resultaten van de studie wensen te veralgemenen.\n   - Financiële and logistieke beperkingen $\\rightarrow$ **representatieve steekproef** van de populatie: Randomisatie!\n\n## Data analysis (2 & 3)\n   - **Data-Exploratie en Beschrijvende Statistiek (2)**:\n\n      - exploreren,\n      - visualiseren,\n      - samenvatten,\n      - inzicht verwerven in de data,\n      - aannames nagaan\n\n   - **Statistische Besluitvorming (3)** (statistical inference):\n   - Veralgemeen wat we observeren in de steekproef naar de populatie zodat we algemene conclusies kunnen trekken over het proces die we bestuderen.  \n   - Gebruik van statistische modellen voor data analyse en om onzekerheid te kwantificeren en te rapporteren.\n\n\n***\n\n## Voorbeeld\n\n- National Health and Nutrition Examination Survey (NHANES)\n- Americaanse demografische studie\n- Groot aantal van fysieke, demografische, nutritionele, gezondheids karakteristieken  \n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|    ID|Gender | Height|BMI_WHO      | DirectChol| SexNumPartnLife|\n|-----:|:------|------:|:------------|----------:|---------------:|\n| 51624|male   |  164.7|30.0_plus    |       1.29|               8|\n| 51625|male   |  105.4|12.0_18.5    |         NA|              NA|\n| 51630|female |  168.4|30.0_plus    |       1.16|              10|\n| 51638|male   |  133.1|12.0_18.5    |       1.34|              NA|\n| 51646|male   |  130.6|18.5_to_24.9 |       1.55|              NA|\n| 51647|female |  166.7|25.0_to_29.9 |       2.12|              20|\n\n\n:::\n:::\n\n\n***\n\n# Variabelen\n\n- We meten *variabelen* op subjecten in een steekproef\n- Een Variabele is een karateristiek b.v. Lengte, Direct cholesterol, Age, Gender, ...\n- Het varieert van subject tot subject in de populatie en is dus ook in de steekproef en tussen steekproeven.\n\n\n## *Types* van variabelen\n\n1. *Kwalitatieve variabelen*: een beperkt aantal categorieën, niet numeriek.\n\t-  *nominale variabelen*: geen natuurlijke ordening, v.b.  Gender, blood group, ...\n\t-  *ordinale variabelen*: ordening, v.b. BMI class, smoking status (1: never smoked, 2: stopped smoking, 3: smoker)\n\n2. *Numerieke variabelen*:\n   \t- *discrete variabelen*: tellingen v.b. number of partners in life span, ...\n\t- *continue variabelen*: kunnen (in theorie) elke mogelijke waarde aannemen binnen bepaalde grenzen v.b. Age, Height, Weight, BMI, Direct Cholestorol...\n\n\t- Soms dichotomiseren naar een nominale kwalitatieve variabele $\\rightarrow$ informatieverlies: BMI $\\rightarrow$ BMI class\n\n***\n\n# Populatie\n\n- Doel van wetenschappelijke studie: uitspraken doen over de algemene populatie.\n\n- V.b. nagaan of de lengte tussen mannen en vrouwen gemiddeld verschillend is.\n\n\n- Populatie is een theoretisch concept\n\t- Is meestal continu in verandering\n\t- Vaak ook interesse in toekomstige subjecten $\\rightarrow$ dus op bepaald ogenblik niet volledig observeerbaar\n  \t- kan als oneindig groot worden beschouwd\n\n- Populatie duidelijk omschrijven!  \n\n## Populatie duidelijk omschrijven\n\n*Inclusiecriteria* zijn karakteristieken die een subject/experimentele eenheid moet hebben om tot de populatie te behoren, b.v.\n\n- leeftijdscategorie 45-65\n- normaal BMI\n- ...\n\n*Exclusiecriteria* zijn karakteristieken die een subject/experimentele eenheid niet mag hebben om tot de populatie te behoren, b.v.\n\n- diabetes\n- historiek van hard drugs\n- lage gezondheidsstatus\n- slaapproblemen\n- ...\n\n***\n\n# Toevalsveranderlijken (toevallige veranderlijken)\n\n- Variabelen (vb Systolische bloeddruk) variëren in de populatie van subject tot subject!\n\\vspace{15pt}\n- Variabelen zijn dus *random of veranderlijk* aangezien hun waarde veranderlijk is in de populatie\n\\vspace{15pt}\n- **Cruciale vraag**: Hoe nauwkeurig zijn uitspraken over de populatie o.b.v. een groep gemeten subjecten in een steekproef!\n\\vspace{15pt}\n- We zullen dus steeds verschillen zien van steekproef tot steekproef\n\\vspace{15pt}\n- Spreiding op gegevens speelt cruciale rol\n\n***\n\n## Conventie\n\n- Gebruik hoofdletters om aan te geven dat bestudeerde karakteristiek (vb. systolische bloeddruk) variabel is in de populatie zonder daarbij concreet over de gerealiseerde waarde voor een bepaald subject na te denken.\n\\vspace{15pt}\n- Variabele $X$ wordt algemeen een *toevalsveranderlijke* genoemd: is formeel\nresultaat van een *toevallige trekking* van een bepaalde\nkarakteristiek uit de studiepopulatie.\n\\vspace{15pt}\n-  Een toevalsveranderlijke $X$ kan men dus opvatten als onbekende veranderlijke die een meting voorstelt die we plannen te verzamelen bij een random subject, maar nog niet hebben verzameld.\n\\vspace{15pt}\n- Noodzakelijk om te kunnen redeneren hoe resultaten van steekproef tot steekproef kunnen wijzigen\n\\vspace{15pt}\n- Toevallig veranderlijken kunnen kwalitatief, kwantitatief, discreet, continu, .... zijn\n\n***\n\n\n# Beschrijven van de populatie\n\n- Voor we een random variabele meten is het onmogelijk exact te voorspellen hoe hoog ze zal zijn.\n\n- Gerealiseerde waarde van $X$ is onderhevig aan random variabiliteit\n\n- Als we weten hoe de variabele verdeeld is dan kunnen we probabiliteitstheorie gebruiken om de kans te berekenen dat een bepaald voorval (event) zich voordoet: vb wat is de kans dat het IQ van een random subject uit de populatie kleiner of gelijk is aan 80.\n\n- Notatie:\n\n    - Event: $X \\leq 80$\n    - Probabiliteit op event: $Pr(X \\leq 80)$\n\n***\n\n## Intermezzo probabiliteitstheorie\n\n### Discrete toevallig veranderlijken\n\n- Stel dat we een discrete random variabele meten $X$\n\n- Alle mogelijke waarden voor $X$ worden de steekproefruimte  $\\Omega$ genoemd.\n\n    - Voor Gender is de steekproefruimte $\\Omega=(0,1)$  met 0 (vrouw) of 1 (man).\n    - Voor het werpen van een dobbelsteen is de steekproefruimte $\\Omega=(1,2,3,4,5,6)$.\n\n\n- Een event $A$  is een subset van de steekproefruimte\n\n      - Een even getal werpen met een dobbelsteen: $A=(2,4,6)$.\n      - Kan ook een specifieke waarde zijn $A=(1)$.\n\n\n- Event ruimte $\\mathcal{A}$ is de klasse van alle mogelijke events die kunnen optreden bij een bepaald experiment.\n\n- Twee events ($A_1$ en $A_2$) zijn mutueel exclusief als ze niet samen op kunnen treden.\n\n    - v.b. event van de oneven getallen $A_1=(1,3,5)$ en het event om $A_2=(6)$ te gooien.\n    - Dus $A_1 \\bigcap A_2=\\emptyset$.\n\n\n- Probabiliteit $Pr(A)$  is een function $Pr: A \\rightarrow [0,1]$ die voldoet aan\n\n    1. $Pr(A) \\geq 0$ en $Pr(A) \\leq 1$ voor elke $A \\in \\mathcal{A}$\n    2. $Pr(\\Omega)=1$\n    3. Voor mutueel exclusieve events $A_1, A_2, \\ldots A_k$ geldt dat $Pr(A_1 \\cup A_2 \\ldots \\cup A_k)= Pr(A_1) + \\ldots + Pr(A_k)$\n\n\n- Dobbelsteen voorbeeld\n\n    - oneven number $A=(1,3,5)$: is de unie van 3 mutueel exclusieve events $A_1=1$, $A_2=3$ en $A_3=5$ zodat\n    $Pr(A)=Pr(1)+Pr(3)+Pr(5)=1/6+1/6+1/6=0.5$\n    - $\\Omega=(1,2,3,4,5,6)$: $Pr(\\Omega)=1$\n\n\n- Als we twee subjecten (j en k) onafhankelijk trekken van de populatie dan is de gezamelijke probabiliteit\n$P(X_j,X_k)= P(X_j)P(X_k)$\n\n***\n\n#### Verdeling\n\n- De verdeling van een discrete toevallig veranderlijke $X$ beschrijft de kans op elke mogelijke waarde van de steekproefruimte.\n\n- Voorbeeld: Gender is een binaire variabele (0: vrouw, 1: man) en binaire variabelen volgen een Bernoulli verdeling. 50.8% van de subjecten in de Amerikaanse populatie zijn vrouw en 49.2% is man.\n\n- Laat $\\pi$ de probabiliteit zijn op een man $\\pi=0.492$.\n    $$ X\\sim \\left \\{\n    \\begin{array}{lcl}\n    P(X=0) &=& 1-\\pi\\\\\n    P(X=1) &=& \\pi\n    \\end{array} \\right . $$\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(X=c(0,1),prob=c(0.508,0.492)) |>\n  ggplot(aes(x=X,xend=X,y=0,yend=prob)) +\n  geom_segment() +\n  ylab(\"Probability\")\n```\n\n::: {.cell-output-display}\n![](02-concepts_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\nToevallig veranderlijke $X$ volgt een Bernoulli verdeling $B(\\pi)$ met parameter $\\pi=0.492$,\n    $$B(\\pi)= \\pi^x(1-\\pi)^{(1-x)}$$\n\n***\n\n#### Cumulatieve distributie functie\n\n- De cumulatieve distributie functie F(x) geeft de probabiliteit weer om een toevallige veranderlijke X te observeren waarvoor geldt dat $X\\leq x$:\n$$ F(x) = \\sum\\limits_{\\forall X\\leq x} P(x)$$\n\n- Gender voorbeeld $F(0)=1-\\pi$ and F(1)= P(X=0) + P(X=1)=1\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(X=c(-0.5,0,1,1.5),cumprob=c(0,0.508,1,1)) |>\n  ggplot(aes(x=X,y=cumprob)) +\n  geom_step(direction=\"hv\") +\n  ylab(\"F(x)\")\n```\n\n::: {.cell-output-display}\n![](02-concepts_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n- Dobbelsteen:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(X=c(0.5,1:6,6.5),cumprob=c(0,cumsum(rep(1/6,6)),1)) |>\n  ggplot(aes(x=X,y=cumprob)) +\n  geom_step(direction=\"hv\") +\n  ylab(\"F(x)\")\n```\n\n::: {.cell-output-display}\n![](02-concepts_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n***\n\n#### Gemiddelde\n\nHet gemiddelde of de verwachte waarde $E[X]$ van een discrete toevallig veranderlijke $X$ is gegeven door:\n\n$$E[X]=\\sum\\limits_{x\\in\\Omega} x P(X=x)$$\n\n- Gender voorbeeld\n\n    - $E[X]= 0 \\times (1-\\pi) + 1 \\times (\\pi) = \\pi$\n    - The mean equals $E[X]=0.492$.\n\n- Dobbelsteen:\n\n$E[X]= 1 \\times \\frac{1}{6} + 2 \\times \\frac{1}{6} + \\ldots + 6 \\times \\frac{1}{6} =$ 3.5\n\n***\n\n#### Variantie\n\nDe variantie is een maat voor de variabiliteit van een toevallig veranderlijke en wordt gegeven door:\n\n$$E[(X-E[X])^2]=\\sum\\limits_{x\\in\\Omega} (x-E[X])^2 P(X=x)$$\n\n- Gender voorbeeld\n    \\begin{eqnarray}\n    E[(X-E[X])^2]&=&(0-\\pi)^2\\times (1-\\pi)+(1-\\pi)^2 \\times \\pi\\\\\n    &=& \\pi^2 (1-\\pi) + (1-\\pi)^2 \\pi\\\\\n    &=&\\pi (1-\\pi)(\\pi+1-\\pi)\\\\\n    &=&\\pi(1-\\pi)\n    \\end{eqnarray}\n\n***\n\n### Continue toevallig veranderlijke\n\n\n- Een continue toevallig veranderlijke kan binnen bepaalde grenzen alle mogelijke waarden aannemen.\n\n- De kans om exact één bepaalde waarde aanneemt is daarom gelijk aan 0.\n\n- De verdeling wordt daarom weergegeven a.d.h.v. de densiteitsfunctie of de dichtheidsfunctie $f(x)$\n\n- Veel biologische karakteristieken zijn approximatief normaal verdeeld (lengte, bloeddruk, IQ, concentratie metingen na logaritmische transformatie)\n    $$f(x) = \\frac{1}{\\sqrt{2\\pi\\sigma^2}} e^{-\\frac{(x-\\mu)^2}{2\\sigma^2}}$$\n\n- Dat wordt kort genoteerd als $f(x) = N(\\mu,\\sigma^2)$\n\n- Van het IQ is geweten dat het normale verdeling volgt met gemiddelde $\\mu=100$ en standaardafwijking $\\sigma=15$.  \n$$IQ \\sim N(100,15^2)$$\n\n\n- In R kunnen we de dnorm functie gebruiken om de densiteit te berekenen voor een bepaalde waarde X=x.\n\n- De argumenten van `dnorm` zijn `mean` ($\\mu$) en `sd` (standaardafwijking $\\sigma$).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\niq <- tibble(\n  IQ = seq(40,150,.1),\n  Densiteit = dnorm(seq(40,150,.1),mean=100,sd=15)\n  )\niq |>\n  ggplot(aes(x=IQ,y=Densiteit)) +\n  geom_line()\n```\n\n::: {.cell-output-display}\n![](02-concepts_files/figure-html/IQ-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n- Binnen bepaalde grenzen kunnen continue toevallig veranderlijken alle mogelijke waarden aannemen dus is $\\Omega$ oneindig groot.\n\n***\n\n#### Cumulatieve distributie\n\n- Opnieuw is de cumulatieve distributie $F(X)=Pr(X\\leq x)$.\n\n- Omdat X continu is berekenen we deze probabiliteit a.d.h.v. een integraal\n$$F(x)=\\int \\limits_{-\\infty}^x f(x) dx$$\n\n- Merk op dat $f(x)=0$ als x niet tot de steekproefruimte behoort.\n\n- We kunnen $F(x)$ berekenen voor een normaal verdeelde toevallig veranderlijke met de functie `pnorm` die opnieuw argumenten `mean` en `sd` heeft.\n\n\n::: {.cell}\n\n```{.r .cell-code}\niq |>\n  mutate(Probability=pnorm(IQ,mean=100,sd=15)) |>\n  ggplot(aes(x=IQ,y=Probability)) +\n  geom_line()\n```\n\n::: {.cell-output-display}\n![](02-concepts_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nDe probabiliteit dat het IQ van een random subject lager is dan 80 wordt in R berekend door\n\n\n::: {.cell}\n\n```{.r .cell-code}\npnorm(80,mean=100,sd=15)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.09121122\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](02-concepts_files/figure-html/unnamed-chunk-7-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](02-concepts_files/figure-html/unnamed-chunk-8-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n- Voor de grootst mogelijke waarde voor $X$ integreren we over de volledige steekproefruimte $\\Omega$ dus\n$$\\int \\limits_{x \\in \\Omega} f(x) dx=1$$\n\n- De oppervlakte onder de dichtheidsfunctie is dus 1!\n\n***\n\n#### Gemiddelde en variantie\n\n- Het gemiddelde of de verwachte waarde is\n\n$$\\int \\limits_{x \\in \\Omega} x f(x) dx$$\n\n- Voor de normale verdeling\n$$\\int \\limits_{-\\infty}^{+\\infty} x f(x) dx = \\mu$$\n\n- De variantie $E[(X-E[X])^2]$   \n\n$$\\int \\limits_{x \\in \\Omega} (x-E[X])^2 f(x) dx$$\n\n- Voor de normale verdeling bekomen we\n\n$$\\int \\limits_{-\\infty}^{+\\infty} (x-\\mu)^2 f(x) dx = \\sigma^2$$\n\n- Het is vaak moeilijk om de variantie te interpreteren gezien ze niet in de zelfde eenheden staat als het gemiddelde. Daarom werken we vaak met de standaardafwijking:\n\n$$SD=\\sqrt{E[(X-E[X])^2]}$$\n\n\nDE SD voor de normale verdeling, $\\sigma$ heeft de mooie interpretatie dat ongeveer 68% van de populatie een waarde heeft voor de karakteristiek X binnen het interval van 1 standaardafwijking($\\sigma$) rond het gemiddelde:\n\n$$P(\\mu-\\sigma < X < \\mu + \\sigma) \\approx 0.68$$\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](02-concepts_files/figure-html/unnamed-chunk-9-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n- Voor normaal verdeelde toevallig veranderlijken heeft ongeveer 95% van de subjecten in de populatie een waarde die binnen twee standaardafwijkingen ($2 \\sigma$) ligt van het gemiddelde.\n\n$$P[\\mu - 2 \\sigma < X < \\mu + 2 \\sigma]\\approx 0.95$$\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](02-concepts_files/figure-html/unnamed-chunk-10-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n***\n\n## Standardisatie\n\n- Normale data worden vaak gestandaardiseerd.\n\n$$z=\\frac{x-\\mu}{\\sigma}$$\n\n- Na standaardisatie volgen de data een standaard normaal verdeling  met gemiddelde $\\mu=0$ en variantie $\\sigma^2=1$:\n$$z \\sim N(0,1)$$\n\nWe kunnen de `qnorm` functie gebruiken om kwantielen $z_{2.5\\%}$ en $z_{97.5\\%}$ te berekenen die respectievelijk corresponderen met $F(z_{2.5\\%})=0.025$ en $F(z_{97.5\\%})=0.975$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqnorm(0.025)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -1.959964\n```\n\n\n:::\n\n```{.r .cell-code}\nqnorm(0.975)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.959964\n```\n\n\n:::\n:::\n\n\nVoor een standaard normaal verdeelde toevallig veranderlijke valt inderdaad ongeveer $0.975 - 0.025=0.95$ van de waarden binnen het interval [-2,2], of binnen 2 standaardafwijkingen ($\\sigma=1$) van het gemiddelde  ($\\mu=0$).\n\n***\n\n# Steekproef\n\n- In echte studies kennen we de verdeling van een random veranderlijke in de populatie niet!\n\n- Omwille van financiële en logsitieke beperkingen kunen we bijna nooit de volledige populatie bestuderen.\n\n- De populatie parameters (v.b. gemiddeld IQ, variantie van IQ) kunnen daardoor niet zonder onzekerheid worden bepaald.  \n\n- We kunnen enkel een kleine subset van de populatie bestuderen: de *steekproef*  (engels: sample)\n- Trek observaties volgens een gestructureerd design: trek de  **subjecten volledig at random uit de populatie** zodat elk subject een gelijke kans heeft om in de steekproef te worden opgenomen $\\rightarrow$ **Representatieve steekproef**.\n\n- Steekproef $x_1, x_2, . . . , x_{n}$ kan als $n$ realisatie van dezelfde toevallig veranderlijke $X$ worden beschouwd voor subjecten $i = 1,2,...,n$.\n\n- De verdeling in de populatie is ongekend en moet worden geschat op basis van de steekproef.\n\n- Als we aannemen dat de gegevens een bepaalde verdeling volgen (b.v. de normale verdeling $N(\\mu,\\sigma^2)$) dan moeten we enkel de populatie parameters ($\\mu$ en $\\sigma^2$) schatten op basis van de steekproef.\n\n- We noemen dit schattingen (engels: estimates) en noteren ze als volgt:  $\\hat \\mu$ en $\\hat \\sigma^2$.\n\n***\n\n## NHANES voorbeeld\n\n- Gender in the population\n\n- Selecteer $n=10000$ subjecten at random van de Amerikaanse populatie.\n\n- Eens de steekproef is getrokken hebben we $n$ realisaties geobserveerd voor de toevallig veranderlijke $X$.\n\n- *Conventie*: Geobserveerde waarden  worden met een kleine letter aangeduid $x$.\n\n- $x$ is een welbepaalde waarde die werd gemeten/geobserveerd in een uitgevoerd experiment en is niet langer een ongekende variabele.\n\n## Samenvatting  \n\n  - Voor we het experiment uitvoeren is de populatie karakteristiek voor de proefpersonen $1,\\ldots,n$ die we uit de populatie zullen trekken ongekend en zijn dat toevallig veranderlijken: $X_1, \\ldots, X_n$\n  - Dit is noodzakelijk om te kunnen redeneren over hoe de resultaten van steekproef tot steekproef kunnen wijzigen\n  - In een steekproef observeren we gerealiseerde uitkomsten $x_1, x_2, \\dots, x_n$: v.b. gender of lengte van subjecten in de steekproef.\n\n***\n\n# Gender Example\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(NHANES)\nNHANES |> ggplot(aes(x=Gender)) + geom_bar()\n```\n\n::: {.cell-output-display}\n![](02-concepts_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n- Gender is een binaire variabele.\n- Het volgt een Bernoulli verdeling.\n- De Bernoulli verdeling heeft een parameter: het gemiddelde $\\pi$.\n- We kunnen $\\pi$ schatten op basis van de steekproef door het steekproefgemiddelde te berekenen $\\bar x = \\sum\\limits_{i=1}^n x_i$\n- Merk op dat het steekproefgemiddelde zelf een toevallig veranderlijke is! Het wijzigt ook van steekproef tot steekproef!\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNHANES |>\n  count(Gender) |>\n  mutate(probability = n/sum(n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  Gender     n probability\n  <fct>  <int>       <dbl>\n1 female  5020       0.502\n2 male    4980       0.498\n```\n\n\n:::\n:::\n\n\n***\n\n# Lengte\n\n## Empirische verdeling\n\n- We kunnen de verdeling van de lengte voor volwassen vrouwen schatten aan de hand van het histogram.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNHANES |>\n  filter(Gender==\"female\"&!is.na(Height)&Age>18) |>\n  ggplot(aes(x=Height)) +\n  geom_histogram()\n```\n\n::: {.cell-output-display}\n![](02-concepts_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n\n- We kunnen de cumulatieve distributie functie schatten door gebruik te maken van de empirische cumulatieve distributie functie.\n    - Elke observatie werd één keer geobserveerd in het staal.\n    - Dus empirische cumulatieve distributie functie van het staal is een discrete verdeling met probabiliteit 1/n op elke observatie.\n    - De empirische cumulatieve distributie functie (ECDF) is gegeven door\n    $$ECDF(x) = \\sum\\limits_{x_i \\leq x} \\frac{1}{n} = \\frac{\\# (x_i \\leq x)}{n}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNHANES |>\n  filter(Gender==\"female\"&!is.na(Height)&Age>18) |>\n  ggplot(aes(x=Height)) +\n  stat_ecdf()\n```\n\n::: {.cell-output-display}\n![](02-concepts_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\nWe kunnen de empirische cumulatieve distributie functie gebruiken om kansen te berekenen.\nWat is de kans dat een vrouw kleiner is dan 150 cm.\n\n\n::: {.cell}\n\n```{.r .cell-code}\necdfFem <- NHANES |>\n  filter(Gender==\"female\"&!is.na(Height)&Age>18) |>\n  pull(\"Height\") |>\n  ecdf()\necdfFem(150)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.05222073\n```\n\n\n:::\n:::\n\n\n    - We illustreren dit ook voor een steekproef van grootte 10\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(502)\nfem10<- NHANES |>\n  filter(Gender==\"female\"&!is.na(Height)&Age>18) |>\n  sample_n(size=10)\n\nfem10 |>\n  ggplot(aes(x=Height)) +\n  stat_ecdf()\n```\n\n::: {.cell-output-display}\n![](02-concepts_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\necdfFem10 <- fem10 |>\n  pull(Height) |>\n  ecdf()\necdfFem10(150)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\n- Merk op dat die kans niet goed wordt geschat o.b.v. de steekproef.\n\n- Merk ook op dat we die kans ook hadden kunnen schatten door te berekenen hoeveel lengtemetingen er lager zijn dan 150.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNHANES |>\n  filter(Gender==\"female\"&!is.na(Height)&Age>18) |> count(Height <=150) |>\n  mutate(prob=n/sum(n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  `Height <= 150`     n   prob\n  <lgl>           <int>  <dbl>\n1 FALSE            3521 0.948 \n2 TRUE              194 0.0522\n```\n\n\n:::\n\n```{.r .cell-code}\necdfFem(150)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.05222073\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfem10 |>\n  count(Height <=150) |>\n  mutate(prob=n/sum(n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  `Height <= 150`     n  prob\n  <lgl>           <int> <dbl>\n1 FALSE              10     1\n```\n\n\n:::\n\n```{.r .cell-code}\necdfFem10(150)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\n***\n\n## Normale benadering\n\n- In de introductie zagen we dat de lengte metingen een mooie klokvorm hadden.\n\n- We kunnen dus aannemen dat de metingen approximatief normaal verdeeld zijn.\n\n\n- We kunnen de verdeling van de lengte metingen ook benaderen d.m.v. een normale verdeling.\n\n- We moeten hiervoor enkel twee parameters schatten:\n    - gemiddelde via steekproefgemiddelde ($\\hat\\mu=\\bar x$)\n    - variantie via steekproefvariantie ($\\hat{\\sigma}^2= s^2$) of de standaardafwijking d.m.v. steekproef standaarddeviatie ($\\hat\\sigma=s$).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHeightSum <- NHANES |>\n  filter(Gender==\"female\"&!is.na(Height)&Age>18) |>\n  summarize(mean=mean(Height),sd=sd(Height))\nHeightSum\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n   mean    sd\n  <dbl> <dbl>\n1  162.  7.27\n```\n\n\n:::\n:::\n\n\nWe zien dat de benadering goed werkt:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNHANES |>\n  filter(Gender==\"female\"&!is.na(Height)&Age>18) |>\n  ggplot(aes(x=Height)) +\n  geom_histogram(aes(y=..density.., fill=..count..)) +\n  xlab(\"Lengte (cm)\") +\n  stat_function(\n    fun=dnorm,\n    color=\"red\",\n    args=list(\n      mean=HeightSum$mean[1],\n      sd=HeightSum$sd[1]\n      )\n    )\n```\n\n::: {.cell-output-display}\n![](02-concepts_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\n\n- We doen nu hetzelfde op basis van de steekproef met de 10 vrouwen.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHeightSum10 <- fem10 |>\n  summarize(mean=mean(Height),sd=sd(Height))\n\nHeightSum10\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n   mean    sd\n  <dbl> <dbl>\n1  163.  8.19\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfem10 |>\n  ggplot(aes(x=Height)) +\n  geom_histogram(aes(y=..density.., fill=..count..),bins=10) +\n  xlab(\"Lengte (cm)\") +\n  stat_function(\n    fun=dnorm,\n    color=\"red\",\n    args=list(\n      mean=HeightSum10$mean[1],\n      sd=HeightSum10$sd[1]\n      )\n    ) +\n  xlim(130,190)\n```\n\n::: {.cell-output-display}\n![](02-concepts_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\n- We kunnen de normale benadering nu ook gebruiken om de kans te berekenen dat een vrouw kleiner is dan 150 cm: Pr(X <= 150).\n\n- We doen dit op basis van de volledige steekproef en vergelijken dit uit wat we bekomen met de ECDF.  \n\n\n::: {.cell}\n\n```{.r .cell-code}\npnorm(150,HeightSum$mean[1],HeightSum$sd[1])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0484516\n```\n\n\n:::\n\n```{.r .cell-code}\necdfFem(150)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.05222073\n```\n\n\n:::\n:::\n\n\n- Op basis van de kleine steekproef:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npnorm(150,HeightSum10$mean[1],HeightSum10$sd[1])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.05346615\n```\n\n\n:::\n\n```{.r .cell-code}\necdfFem10(150)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\n- Voor kleine steekproef is geschatte kans o.b.v. empirische verdeling veel minder nauwkeurig.\n\n- Kwantielen geschat o.b.v. kleine steekproef zijn immers vrij onzeker. Ze gebruiken immers maar een fractie van de data.   \n\n- De schatting o.b.v. de normale verdeling laat toe om alle data te gebruiken voor het schatten van de model parameters.\n\n***\n\n## Referentie intervallen\n\n- Normale waarden voor de lengte kunnen worden bekomen door gebruik te maken van een referentie interval.\n\n- Typisch wordt een 95% referentie interval gebruikt zodat we voor 95% van de subjecten in de populatie verwachten dat ze een karakteristiek hebben die in het referentie interval ligt.\n\n- We kunnen dat opnieuw op basis van de empirische verdeling.\n\n- We moeten hiervoor $\\hat{F}(x_{2.5\\%})=0.025$ en $\\hat{F}(x_{97.5\\%})=0.975$ berekenen zodat 95% van de observaties in de steekproef vallen in het interval [x_{2.5%},x_{97.5%}].\n\n- Dat kan met de `quantile` functie.\n\n- Grote steekproef\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNHANES |>\n  filter(Gender==\"female\"&!is.na(Height)&Age>18) |>\n  pull(Height) |>\n  quantile(prob=c(0.025,0.975))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n 2.5% 97.5% \n147.6 176.7 \n```\n\n\n:::\n:::\n\n\n- Op basis van de grote steekproef schatten we dat 95% van de vrouwen in de populatie een lengte heeft die ligt in het interval [147.6, 176.7].\n\n- Kleine steekproef\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfem10 |>\n  pull(Height) |>\n  quantile(prob=c(0.025,0.975))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    2.5%    97.5% \n154.7250 178.3275 \n```\n\n\n:::\n:::\n\n\n- Dit interval o.b.v. de kleine steekproef is een ruwe benadering.\n- We hebben immers niet voldoende observaties om een goede benadering te hebben voor extreme quantielen.\n\n### Normale benadering\n\n- We kunnen de functie qnorm gebruiken om quantielen te berekenen van de normale verdeling.\n\n- We weten dat een 95% referentie interval ongeveer binnen twee standaard deviaties rond het gemiddelde ligt.\n\n\n- Grote steekproef\n\n::: {.cell}\n\n```{.r .cell-code}\nqnorm(0.025,mean=HeightSum$mean,sd=HeightSum$sd)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 147.8192\n```\n\n\n:::\n\n```{.r .cell-code}\nHeightSum$mean - 2 * HeightSum$sd\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 147.528\n```\n\n\n:::\n\n```{.r .cell-code}\nqnorm(0.975,mean=HeightSum$mean,sd=HeightSum$sd)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 176.3237\n```\n\n\n:::\n\n```{.r .cell-code}\nHeightSum$mean + 2 * HeightSum$sd\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 176.6149\n```\n\n\n:::\n:::\n\n\n- Kleine steekproef\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqnorm(0.025,mean=HeightSum10$mean,sd=HeightSum10$sd)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 147.1499\n```\n\n\n:::\n\n```{.r .cell-code}\nqnorm(0.975,mean=HeightSum10$mean,sd=HeightSum10$sd)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 179.2701\n```\n\n\n:::\n:::\n\n\n***\n\n## Conclusions\n\n- Voor de grote steekproef geven de empirische verdeling en de normale benadering vergelijkbare resultaten.\n\n- Voor de kleine steekproef werkt de normale benadering beter dan de empirische verdeling.\n\n    - We kijken immers naar extreme quantielen 2.5% en 97.5%.\n    - Er zijn inderdaad weinig gegevens in de steekproef die toelaten om deze quantielen direct te schatten.\n    - Met de normale benadering kunnen we alle data gebruiken om het gemiddelde en de standaarddeviatie te schatten.\n    - Als de aanname van normaliteit geldt dan krijgen we betere schattingen voor deze kwantielen.  \n\n***\n\n# Statistieken\n\n- Formule die we gebruiken om parameters van de verdeling in de populatie te schatten op basis van een steekproef. We refereren hiernaar als statistieken of schatters.\n\n- Het numerieke resultaat die wordt bekomen door deze formules te evalueren worden ook statistieken of schattingen genoemd.\n\n- Onderzoekers wensen ongekende parameters van de verdeling in de populatie te kennen en schatten deze o.b.v. de steekproef.\n\n- Omdat we statistieken berekenen o.b.v. de observaties in een steekproef, variëren statistieken ook van steekproef tot steekproef. Het zijn dus ook random variabelen en we noteren ze dus ook met hoofdletters (b.v. $\\bar X$ voor het steekproefgemiddelde en $S^2$ voor de steekproefvariantie).\n\n- Als we data analyseren moeten we dus nadenken over hoe de statistieken variëren van steekproef tot steekproef.\n\n- Als een statistiek verwijst naar een numerieke waarde die werd gerealiseerd in een bepaalde steekproef dan noteren we deze met een kleine letter: $\\bar x$ en $s^2$.\n\n***\n\n# Conventie\n\n- **Populatieparameters** nemen vaste waarden aan maar zijn meestal ongekend $\\rightarrow$ **Griekse symbolen**.\n\\vspace{15pt}\n\n- **Statistieken** waarmee we deze ongekende parameters schatten o.b.v. een steekproef  $\\rightarrow$  **letters**.\n\\vspace{15pt}\n\n- Vb Normale verdeling\n\n| Populatie | Steekproef|\n| :---: | :---: |\n| $\\mu$ | $\\bar X$ |\n| $\\sigma^2$ | $S^2$ |\n\n\n\n***\n",
    "supporting": [
      "02-concepts_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}