{
  "hash": "cb9b46b46e8c37ce492bd449141db2a2",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"5. Statistische besluitvorming\"\nauthor: \"Lieven Clement\"\ndate: \"statOmics, Ghent University (https://statomics.github.io)\"\nformat:\n  html:\n    toc: true\n    number-sections: true\n    theme: cosmo\n    highlight-style: tango\n    code-tools: true\n    embed-resources: true\n---\n\n\n\n\n\n\n# Introduction\n## Population\n- Het doel van een wetenschappelijk onderzoek is om conclusies te trekken over de algemene populatie\n\n- Hier bestuderen we de invloed van Captopril op de bloeddruk van patiënten met hyptertensie.\n\n- We zullen data verzamelen en deze dan modelleren\n\n- We moeten de onderzoeksvraag altijd vertalen naar de modelparameters of een combinatie van modelparameters.\n\n- bv. het populatie gemiddelde\n  $$E(X)=\\mu$$\n- Vermindert de gemiddelde bloeddruk bij patiënten met hypertensie na toedienen van Captopril?\n\n***\n\n## Overzicht\n\n- Experimenteel Design & Data Exploratie\n- Puntschatters (Schatting)\n- Interval schatters (Statistische inferentie)\n- Hypothese testen (Statistische inferentie)\n\n***\n\n# Captopril voorbeeld\n## Experimental design\n\n- 15 patiënten werden at random getrokken uit de populatie van patiënten met hypertensie\n- pre-test/post-test design: de systolische en diastolysche bloeddruk worden gemeten voor en na toedienen van Captopril.\n- Voordeel: We kunnen het effect van de Captopril toediening op de bloeddruk van de individuele patiënten beoordelen.\n- Nadeel?\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-html/pop2Samp2Pop-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n***\n\n## Data Exploratie en Beschrijvende Statistiek\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncaptopril <- read_csv(\"https://raw.githubusercontent.com/statOmics/sbc/master/data/captopril.txt\")\nhead(captopril)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n     id  SBPb  DBPb  SBPa  DBPa\n  <dbl> <dbl> <dbl> <dbl> <dbl>\n1     1   210   130   201   125\n2     2   169   122   165   121\n3     3   187   124   166   121\n4     4   160   104   157   106\n5     5   167   112   147   101\n6     6   176   101   145    85\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(captopril)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       id            SBPb            DBPb            SBPa          DBPa      \n Min.   : 1.0   Min.   :146.0   Min.   : 98.0   Min.   :129   Min.   : 82.0  \n 1st Qu.: 4.5   1st Qu.:163.5   1st Qu.:103.0   1st Qu.:146   1st Qu.: 98.0  \n Median : 8.0   Median :174.0   Median :112.0   Median :157   Median :103.0  \n Mean   : 8.0   Mean   :176.9   Mean   :112.3   Mean   :158   Mean   :103.1  \n 3rd Qu.:11.5   3rd Qu.:192.5   3rd Qu.:121.5   3rd Qu.:168   3rd Qu.:108.0  \n Max.   :15.0   Max.   :210.0   Max.   :130.0   Max.   :201   Max.   :125.0  \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncaptoprilTidy <-\n  captopril |>\n  gather(type,bp,-id)\n\ncaptoSum <- captoprilTidy |>\n  group_by(type) |>\n  summarize(\n    mean = mean(bp,na.rm=TRUE),\n    sd = sd(bp,na.rm=TRUE),\n    n = sum(!is.na(bp))) |>\n  mutate(se = sd/sqrt(n))\n\ncaptoSum\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  type   mean    sd     n    se\n  <chr> <dbl> <dbl> <int> <dbl>\n1 DBPa   103.  12.6    15  3.24\n2 DBPb   112.  10.5    15  2.70\n3 SBPa   158   20.0    15  5.16\n4 SBPb   177.  20.6    15  5.31\n```\n\n\n:::\n\n```{.r .cell-code}\ncaptoSum |>\n  ggplot(aes(x=type,y=mean)) +\n  geom_bar(stat=\"identity\") +\n  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd),width=.2) +\n  ylim(0,210) +\n  ylab(\"blood pressure (mmHg)\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n- Deze figuur is niet informatief! Het toont de ruwe data niet enkel gemiddelden en de standaard deviatie voor een bloeddruk karakteristiek.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncaptoprilTidy |>\n  ggplot(aes(x=type,y=bp)) +\n  geom_boxplot(outlier.shape=NA) +\n  geom_point(position=\"jitter\") +\n  ylim(0,210)\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nWe zien dat veel van de ruimte die werd ingenomen door de barplot geen gegevens bevat!\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncaptoprilTidy |>\n  ggplot(aes(x=type,y=bp)) +\n  geom_boxplot(outlier.shape=NA) +\n  geom_point(position=\"jitter\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n- Deze plot zou informatief zijn geweest als de gegevens over verschillende individuen waren verzameld.\n\n- De bloeddruk wordt echter bij dezelfde patiënt gemeten!\n\n- We zullen een plot maken waar we de systolische bloeddruk filteren\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncaptoprilTidy |>\n  filter(type%in%c(\"SBPa\",\"SBPb\")) |>\n  mutate(type=factor(type,levels=c(\"SBPb\",\"SBPa\"))) |>\n  ggplot(aes(x=type,y=bp)) +\n  geom_line(aes(group = id)) +\n  geom_point()\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n- We hebben gepaarde data. We kunnen het effect van de behandeling dus onmiddellijk inschatten door de bloeddruk na behandeling te vergelijken met de bloeddruk vóór de behandeling.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncaptopril <-\n  captopril |>\n  mutate(deltaSBP = SBPa - SBPb)\n\ncaptopril |>\n  ggplot(aes(x=\"Systolic blood pressure\",y=deltaSBP)) +\n  geom_boxplot(outlier.shape=NA) +\n  geom_point(position=\"jitter\")+\n  ylab(\"Difference (mm mercury)\") +\n  xlab(\"\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncaptopril |>\n  summarize(\n    mean = mean(deltaSBP,na.rm=TRUE),\n    sd = sd(deltaSBP,na.rm=TRUE),\n    n = sum(!is.na(deltaSBP))) |>\n  mutate(se = sd/sqrt(n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n   mean    sd     n    se\n  <dbl> <dbl> <int> <dbl>\n1 -18.9  9.03    15  2.33\n```\n\n\n:::\n:::\n\n\n\n- Pre-test/post-test design: Effect van Captopril in de steekproef met  $X=\\Delta_\\text{na-voor}$!\n\n- Hoe modelleren we $X=\\Delta_\\text{na-voor}$ en schatten we het effect van Captopril?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncaptopril |>\n  ggplot(aes(sample=deltaSBP)) +\n  stat_qq() +\n  stat_qq_line()\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nDe systolische bloeddruk verschillen zijn ongeveer normaal verdeeld.\n***\n\n## Schatten\n\n\n- Geen susbtantiële afwijkingen van normaliteit.\n\n- We kunnen aannemen dat de verschillen  $X \\sim N(\\mu, \\sigma^2)$.\n\n- Het effect van Captopril in de populatie wordt weergegeven door het gemiddelde bloeddruk verschil $\\mu$.\n\n- De gemiddelde bloeddruk $\\mu$ in de populatie kan worden geschat met behulp van het steekproefgemiddelde $\\bar x$ = -18.93\n\n- De standaarddeviatie $\\sigma$ met de steekproefstandaarddeviatie  $\\text{S}$ = 9.03.\n\n- Is het effect dat we in de steekproef observeren groot genoeg om te concluderen dat er een effect is van de captoprilbehandeling op de bloeddruk op populatieniveau?\n\n- Onze schattingen zullen van steekproef tot steekproef veranderen!\n\n- Hoe zijn de schatters $\\bar X$ en $S$ verdeeld?\n\n\n# Punt schatters: het steekproefgemiddelde\n\n- Stel dat $X$ een willekeurige steekproef is uit de populatie en neem aan dat $X \\sim N(\\mu,\\sigma^2)$\n\n- Schat $\\mu$ op basis van de steekproef $X_1,...,X_n$, gebruik makende van het steekproefgemiddelde\n  $$\\bar X = \\frac{X_1+ X_2+ ... + X_n}{n} = \\frac{\\sum_{i=1}^{n} X_i}{n}$$ van willekeurige variabelen $X_1,X_2, ..., X_n$.\n\n- Steekproef gemiddelde $\\bar X$ is een willekeurige variable dat varieert van steekproef tot steekproef.\n\n- Bestudeer de theoretische verdeling van het steekproefgemiddelde om inzicht te krijgen\n\n    1. in hoe het steekproefgemiddelde kan variëren in een nieuw gelijkaardig onderzoek\n    2. hoe ver $\\bar X$ kan verschillen van het populatiegemiddelde $\\mu$\n\n***\n\n## Overzicht\n\n\n1. Het steekproefgemiddelde is onvertekend\n2. Precisie van steekproefgemiddelde\n3. Distributie van steekproefgemiddelde\n\n***\n\n## Het steekproefgemiddelde is onvertekend\n\n- We kunnen het effect in de steekproef veralgemenen naar de populatie als de schatting in de steekproef een goede benadering is van de populatiewaarde.\n\n- De steekproef moet representatief zijn om de resultaten van de steekproef naar de populatie te generaliseren\n\n- Vermijd bias (zodat het populatiegemiddelde niet systematisch onder of overschat wordt)\n\n- Rapporteer hoe de steekproef is genomen!\n\n- Randomisatie!\n\n- Neem de proefpersonen willekeurig uit de populatie, zodat elke proefpersoon dezelfde kans heeft om in de steekproef terecht te komen\n\n- Proefpersonen met hyptertensie worden willekeurig uit de populatie genomen.\n\n\n- Eenvoudige willekeurige steekproef:  $X_1,...,X_n$ voor kenmerk $X$\n\n- $X_1,...,X_n$ hebben dezelfde distributie\n- Ze hebben hetzelfde gemiddelde $\\mu$ en variantie $\\sigma^2$\n\n- $E(X_1)=...=E(X_n)=\\mu$ en $\\text{Var}(X_1)=...=\\text{Var}(X_n)=\\sigma^2$\n\n- $\\bar X$ is een *overtekende schatter* voor $\\mu$\n\n<details><summary>Click to see proof</summary><p>\n\\begin{eqnarray*}\nE(\\bar X) &=& E \\left(\\frac{X_1+ X_2+ ... + X_n}{n}\\right) \\\\\n&= & \\frac{E(X_1)+ E(X_2)+ ... + E(X_n)}{n} \\\\\n&=& \\frac{\\mu + \\mu + ... +\\mu}{n} \\\\\n&= & \\mu\n\\end{eqnarray*}\n</p></details>\n\n***\n\n## Imprecisie/standard error\n\n- Ook voor representatieve steekproeven zijn de resultaten onnauwkeurig\n\\vspace{10pt}\n- Verschillende steekproeven uit dezelfde populatie geven verschillende resultaten.\n\n- We illustreren dit met de NHANES studie\n\n    - We zullen 15 vrouwen willekeurig selecteren uit de NHANES studie en zullen hun cholesterolgehalte registreren.\n    - We herhalen dit 50 keer om de variatie van steekproef tot steekproef te beoordelen\n    - We plotten de boxplot voor iedere steekproef en duiden het gemiddelde aan.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(NHANES)\n\nfem <- NHANES |>\n  filter(Gender==\"female\" & !is.na(DirectChol)) |>\n  select(\"DirectChol\")\n\nn <- 15 # number of subjects per sample\nnSim <- 50 # number of simulations\n\nfemSamp <- matrix(nrow=n,ncol=nSim)\nfor (j in 1:nSim)\n{\n  set.seed(2105)\n  femSamp[,j] <- sample(fem$DirectChol,15)\n  if (j<4) {\n    p <- femSamp |>\n      log2() |>\n      data.frame() |>\n      gather(\"sample\",\"log2cholesterol\") |>\n      ggplot(aes(x=sample,y=log2cholesterol)) +\n      geom_boxplot() +\n      stat_summary(\n        fun.y=mean,\n        geom=\"point\",\n        shape=19,\n        size=3,\n        color=\"red\",\n        fill=\"red\") +\n      geom_hline(yintercept = mean(fem$DirectChol |> log2())) +\n      ylab(\"cholesterol (log2)\")\n    print(p)\n  }\n}\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-html/unnamed-chunk-10-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-html/unnamed-chunk-10-3.png){width=672}\n:::\n\n```{.r .cell-code}\nfemSamp |>\n  log2() |>\n  data.frame() |>\n  gather(\"sample\",\"log2cholesterol\") |>\n  ggplot(aes(x=sample,y=log2cholesterol)) +\n  geom_boxplot() +\n  stat_summary(fun.y=mean, geom=\"point\", shape=19, size=3, color=\"red\", fill=\"red\") +\n  geom_hline(yintercept = mean(fem$DirectChol |> log2())) +\n  ylab(\"cholesterol (log2)\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-html/unnamed-chunk-10-4.png){width=672}\n:::\n:::\n\n\nWe observeren dat het steekproefgemiddelde fluctueert rond het gemiddelde van de populatie.\n\nOpdracht:\n\n1. Kopieer de code\n2. Vergroot de steekproefgrootte tot 100 proefpersonen\n3. Wat observeer je?\n\n***\n\n**Hoe doen we dit op basis van een enkele steekproef?**\n\n- Inzicht in hoe dicht we $\\bar X$ tot$\\mu$ kunnen verwachten?\n\n- Hoe varieert $\\bar X$ van steekproef tot steekproef?\n\n- Variabiliteit op $\\bar X$\n\n- Dit moeten we bepalen op basis van een enkele steekproef!\n\n- We moeten assumpties maken\n\n- We nemen aan dat de willekeurige variabelen $X_1, X_2, ..., X_n$ afkomstig zijn van $n$ *onafhankelijke* personen.\n\n- Voor de Captopril studie hebben we afhankelijke observaties\n\n    - Bloeddrukmetingen voor ($Y_{i,before}$) en na ($Y_{i,after}$) toediening van captopril aan dezelfde patiënt $i=1,\\ldots,n$.\n    - We hebben ze omgezet in n onafhankelijke metingen door het verschil $Y_{i,na}-Y_{i,voor}$ te nemen.\n\n***\n\n### Variantie schatter voor $\\bar X$\n\n$$\\sigma^2_{\\bar X}=\\frac{\\sigma^2}{n}$$\n\n- De standaarddeviatie van $\\bar X$ rond $\\mu$ is $\\sqrt{n}$ keer kleiner dan de deviatie rond de originele observaties $X$.\n\n- Hoe meer observaties we hebben, des te nauwkeuriger $\\bar X$.\n\n\n<details><summary>Click to see proof</summary><p>\n\\begin{eqnarray*}\n\\text{Var}(\\bar X)&=&\\text{Var} \\left(\\frac{X_1+ X_2+ ... + X_n}{n}\\right) \\\\\n&\\overset{*}{=} & \\frac{\\text{Var}(X_1)+ \\text{Var}(X_2)+ ... + \\text{Var}(X_n)}{n^2} \\\\\n&=& \\frac{\\sigma^2 + \\sigma^2 + ... \\sigma^2}{n^2} \\\\\n&= & \\frac{\\sigma^2}{n}.\n\\end{eqnarray*}\n\n- (*) Dit is gebaseerd op de assumptie van onafhankelijkheid\n$$\\text{Var}[a X_1 + b X_2] = a^2\\text{Var}[X_1] + b^2 \\text{Var}[X_2] + 2 ab\\text{Covar}[X_1,X_2]$$\n\n    - Met $Covar[X_1,X_2]=0$ wanneer $X_1$ en $X_2$ onafhankelijk zijn.\n</p></details>s\n\n**Definitie: standaard error**\n\nDe standaard deviatie van $\\bar{X}$ is $\\sigma/\\sqrt{n}$ en wordt ook wel de **standaard error** van het gemiddelde genoemd.\nOver het algemeen verwijst men naar de standaarddeviatie van een schatter voor een bepaalde parameter $\\theta$ met de term **standaard error** van de schatter die wordt aangeduid als $SE$\n\n***\n\n### Captopril voorbeeld\n\n\n- $n = 15$ verschillen in systolische bloeddruk\n\n- Stel dat de standaarddeviatie van de bloeddrukverschillen in de populatie $\\sigma = 9.0$ mmHg is\n\n- Dan wordt de standaard error (SE) op de gemiddelde systolische bloeddruk verschillen $\\bar X$:\n\n$$\nSE = \\frac{9.0}{\\sqrt{15}}=2.32\\text{mmHg.}\n$$\n\n- Over het algemeen zijn $\\sigma$, en dus de SE op het steekproefgemiddelde onbekend.\n- We moeten dus ook de standaarddeviatie van de steekproef schatten om de standaard error te verkrijgen.\n- Schatter: $SE=S/\\sqrt{n},$\n- Met $S^2$ de steekproefvariantie van $X_1,...,X_n$  en $S$ de steekproefstandaarddeviatie\n\n- Voor het Captopril voorbeeld krijgen we:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- length(captopril$deltaSBP)\nse <- sd(captopril$deltaSBP)/sqrt(n)\nse\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.330883\n```\n\n\n:::\n:::\n\n\n***\n\n### standaarddeviatie vs standaard error\n\n#### Illustratie via herhaalde steekproeven\n\n- Verschillende steekproef groottes: 10, 50, 100\n- Neem 1000 steekproeven per steekproef grootte van de NHANES studie, voor iedere steekproef berekenen we:\n    - Het gemiddelde\n    - De steekproefstandaarddeviatie\n    - de standaard error\n- We maken een boxplot van de steekproefstandaardevaties en de standaard errors voor de verschillende steekproefgroottes\n\n- In plaats van een for loop te gebruiken zullen we de sapply functie gebruiken die efficiënter is. Het neemt een vector of lijst als invoer en past de functie toe op ieder element van de vector of lijst.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(24)\nfemSamp10 <- sapply(\n  1:1000,\n  function(j,x,size) sample(x,size),\n  size=10,\n  x=fem$DirectChol)\n\nfemSamp50 <- sapply(\n  1:1000,\n  function(j,x,size) sample(x,size),\n  size=50,\n  x=fem$DirectChol)\n\nfemSamp100 <- sapply(\n  1:1000,\n  function(j,x,size) sample(x,size),\n  size=100,\n  x=fem$DirectChol)\n\nres<-rbind(\n  femSamp10 |>\n    log2()|>\n    as.data.frame() |>\n    gather(sample,log2Chol) |>\n    group_by(sample)|>\n    summarize_at(\"log2Chol\",\n               list(median=~median(.,na.rm=TRUE),\n                    mean=~mean(.,na.rm=TRUE),\n                    sd=~sd(.,na.rm=TRUE),\n                    n=function(x) sum(!is.na(x)))) |>\n    mutate(se=sd/sqrt(n)) ,\n  femSamp50 |>\n    log2() |>  \n    as.data.frame() |>\n    gather(sample,log2Chol) |>\n    group_by(sample)|>\n    summarize_at(\"log2Chol\",\n               list(median=~median(.,na.rm=TRUE),\n                    mean=~mean(.,na.rm=TRUE),\n                    sd=~sd(.,na.rm=TRUE),\n                    n=function(x) sum(!is.na(x)))) |>\n    mutate(se=sd/sqrt(n)),\n  femSamp100 |>\n    log2() |>\n    as.data.frame() |>\n    gather(sample,log2Chol) |>\n    group_by(sample)|>\n    summarize_at(\"log2Chol\",\n               list(median=~median(.,na.rm=TRUE),\n                    mean=~mean(.,na.rm=TRUE),\n                    sd=~sd(.,na.rm=TRUE),\n                    n=function(x) sum(!is.na(x)))) |>\n    mutate(se=sd/sqrt(n))\n  )\n```\n:::\n\n\n**Gemiddelden**\n\nWe illustreren de impact van steekproefgrootte op de distributie van de gemiddeldes van verschillende steekproeven\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres |>\n  ggplot(aes(x= n |> as.factor(),y = mean)) +\n  geom_boxplot() +\n  ylab(\"Direct cholesterol (log2)\") +\n  xlab(\"sample size\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n- Merk op dat de variatie van de steekproefgemiddelden inderdaad afneemt naarmate de steekproefgrootte toeneemt. De schatting wordt dus nauwkeuriger naarmate de steekproefgrootte toeneemt.\n\n***\n\n**Standard deviatie**\n\nWe illustreren nu de impact van de steekproefgrootte op de verdeling van de standaarddeviatie van de verschillende steekproeven\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres |>\n  ggplot(aes(x=n|>as.factor(),y=sd)) +\n  geom_boxplot() +\n  ylab(\"standard deviation\") +\n  xlab(\"sample size\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n- De standaarddeviatie blijft vergelijkbaar voor de steekproefgroottes.\nHet is gecentreerd rond dezelfde waarde: de standaarddeviatie in de populatie. Het vergroten van de steekproefgrootte heeft inderdaad geen invloed op de variabiliteit in de populatie!\n\n- Opnieuw zien we dat de variabiliteit van de standaarddeviatie afneemt naarmate de steekproefgrootte toeneemt. De standaarddeviatie kan dus ook nauwkeuriger worden geschat naarmate de steekproefgrootte toeneemt.\n\n***\n\n**Standaard error van het gemiddelde**\n\nTen slotte illustreren we de impact van de steekproefgrootte op de verdeling van de standaarddeviatie van het gemiddelde van de verschillende steekproeven, de standaard error.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres |>\nggplot(aes(x=n|>as.factor(),y=se)) +\ngeom_boxplot() +\nylab(\"standard error\") +\nxlab(\"sample size\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n- De standaard error (de schatter voor de nauwkeurigheid van het steekproefgemiddelde) vermindert aanzienlijk naarmate de steekproefgrootte toeneemt, wat opnieuw bevestigt dat de schatting van het steekproefgemiddelde nauwkeuriger wordt.\n\n***\n\n### Normaal verdeelde data\n\n- Voor normaal verdeelde data hebben we meerdere schatters voor het populatiegemiddelde $\\mu$ bv. gemiddelde en mediaan.\n\n- Maar $\\bar{X}$ is de overtekende schatter van $\\mu$ met de kleinste standaard error\n\n-  $\\bar{X}$ wijkt minder af van het gemiddelde $\\mu$ dan de mediaan\n\n- We illustreren dit voor herhaalde steekproeven met steekproefgrootte 10\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres |>\n  filter(n == 10) |>\n  select(mean,median) |>\n  gather(type,estimate) |>\n  ggplot(aes(x = type,y = estimate)) +\n  geom_boxplot() +\n  geom_hline(yintercept = fem$DirectChol |>\n    log2() |>\n    mean()) +\n  ggtitle(\"10 personen\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\nVervolgens vergelijken we de verdeling van het gemiddelde en de mediaan in herhaalde steekproeven van steekproefgrootte 50.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres |>\n  filter(n == 50) |>\n  select(mean, median) |>\n  gather(type, estimate) |>\n  ggplot(aes(x = type,y = estimate)) +\n  geom_boxplot()+\n  geom_hline(yintercept = fem$DirectChol |>\n    log2() |>\n    mean()) +\n  ggtitle(\"50 personen\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n## Verdeling van het steekproefgemiddelde\n\n\n- Hoe varieert $\\bar X$ van steekproef tot steekproef?\n- Verdeling van $\\bar X$?\n- Als $\\bar X$ normaal verdeeld is, heeft de standaard error een goede interpretatie: de SE is de standaard deviatie van het steekproefgemiddelde.\n- Als de data $X_i$ normaal verdeeld zijn, is het steekproefgemiddelde ook normaal verdeeld.\n\n$$X_i \\sim N(\\mu,\\sigma^2) \\rightarrow  \\bar X \\sim N(\\mu,  \\sigma^2/n)$$\n\n***\n\n### NHANES: cholesterol\n\nWe illustreren dit nogmaals met een simulatie gebruik makende van de NHANES-studie.\nDe log2-cholesterolwaarden zijn normaal verdeeld.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n fem |>\n  ggplot(aes(x = DirectChol |> log2()))+\n  geom_histogram(aes(y = ..density.., fill = ..count..)) +\n  xlab(\"Direct cholesterol (log2)\") +\n  stat_function(\n    fun = dnorm,\n    color = \"red\",\n    args = list(\n      mean=mean(fem$DirectChol|>log2()),\n      sd = sd(fem$DirectChol|>log2())\n      )\n    ) +\n  ggtitle(\"Alle vrouwen in NHANES studie\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n\n```{.r .cell-code}\nfem |>\n  ggplot(aes(sample = DirectChol |> log2())) +\n  stat_qq() +\n  stat_qq_line() +\n  ggtitle(\"Alle vrouwen in NHANES study\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-html/unnamed-chunk-18-2.png){width=672}\n:::\n:::\n\n\n***\n\n##### Evalueer de verdeling van het gemiddelde voor steekproeven van grootte 10\n\nWe onderzoeken de resultaten voor de steekproefgrootte van 10.\n\nWe bekijken eerst de plot voor de eerste steekproef.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlog2Chol <- femSamp10[,1] |>\n  log2()\ndata.frame(log2Chol) |>\n  ggplot(aes(x=log2Chol))+\n    geom_histogram(aes(y=..density.., fill=..count..),bins=10) +\n    xlab(\"Direct cholesterol (log2)\") +\n    stat_function(\n      fun=dnorm,\n      color=\"red\",\n      args=list(\n        mean=femSamp10[,1]|>log2()|>mean(), sd=femSamp10[,1]|>log2()|>sd())\n      ) +\n    ggtitle(\"10 random females\") +\n    xlim(fem$DirectChol |> log2() |> range())\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\nVervolgens kijken we naar de verdeling van het steekproefgemiddelde over 1000 steekproeven van steekproefgrootte 10.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmeanLog2Chol <- femSamp10 |>\n  log2() |>\n  colMeans()\ndata.frame(meanLog2Chol) |>\n  ggplot(aes(x=meanLog2Chol)) +\n  geom_histogram(aes(y=..density.., fill=..count..),bins=15) +\n  xlab(\"Mean cholesterol (log2)\") +\n  stat_function(\n    fun=dnorm,\n    color=\"red\",\n    args=list(\n      mean=femSamp10|>log2()|> colMeans() |> mean(),\n      sd=femSamp10|>log2()|> colMeans() |> sd())\n    ) +\n  ggtitle(\"Means on 10 females\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n\n```{.r .cell-code}\nmeanLog2Chol <- femSamp10 |>\n  log2()|>\n  colMeans()\ndata.frame(meanLog2Chol) |>\n  ggplot(aes(sample=meanLog2Chol)) +\n  stat_qq() +\n  stat_qq_line() +\n  ggtitle(\"Means on 10 females\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-html/unnamed-chunk-20-2.png){width=672}\n:::\n:::\n\n\n**We hebben dus bevestigd dat het gemiddelde ongeveer normaal verdeeld is voor studies met 5 en 10 vrouwen, terwijl de originele gegevens ongeveer normaal verdeeld zijn.**\n\n***\n\n#### Captopril studie\n\n- De systolische bloeddrukverschillen in de Captopril studie zijn bij benadering normaal verdeeld.\n\n- s.e.= 2.32 mm Hg\n\n- In 95 van de 100 studies met n = 15 proefpersonen verwachten we dat het steekproefgemiddelde van de systolische bloeddrukverschillen ($\\bar X$) op minder dan $2 \\times 2.32 = 4.64$mm Hg van het werkelijk populatiegemiddelde van de bloeddrukverschillen geschat wordt.\n\n***\n\n### Niet-normaal verdeelde data\n\n- Als individuele observaties geen normale verdeling hebben,  is $\\bar X$ nog steeds \\textit{ongeveer} normaal verdeeld\nwanneer het aantal observaties groot genoeg is.\n\n- Hoe groot moet de steekproef zijn om de normale benadering te laten werken?\n\n- Dit hangt af van de scheefheid van de distributie!\n\n***\n\n#### NHANES: cholesterol\n\n- We kunnen dit evalueren in de NHanes-studie als we de gegevens niet log2 transformeren.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfem |>\n   ggplot(aes(x=DirectChol))+\n   geom_histogram(aes(y=..density.., fill=..count..)) +\n   xlab(\"Direct cholesterol\") +\n   stat_function(\n     fun=dnorm,\n     color=\"red\",\n     args=list(\n       mean=mean(fem$DirectChol),\n       sd=sd(fem$DirectChol))\n    ) +\n   ggtitle(\"All females in Nhanes study\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n\n```{.r .cell-code}\n fem |>\n  ggplot(aes(sample=DirectChol)) +\n  stat_qq() +\n  stat_qq_line() +\n  ggtitle(\"All females in Nhanes study\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-html/unnamed-chunk-21-2.png){width=672}\n:::\n:::\n\n\nDe cholesterol data zijn duidelijk niet-normaal verdeeld.\n\n##### Verdeling van het steekproefgemiddelde voor verschillende steekproefgroottes\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(121)\nfemSamp5 <- sapply(\n  1:1000,\n  function(j,x,size) sample(x,size),\n  size = 5,\n  x = fem$DirectChol)\n\nmeanChol <- femSamp5 |>\n  colMeans()\ndata.frame(meanChol) |> ggplot(aes(x=meanChol)) +\n  geom_histogram(aes(y=..density.., fill=..count..),bins=15) +\n  xlab(\"Mean cholesterol\") +\n  stat_function(\n    fun=dnorm,\n    color=\"red\",\n    args=list(\n      mean=femSamp5|> colMeans() |> mean(),\n      sd=femSamp5|> colMeans() |> sd())\n    ) +\n  ggtitle(\"Means on 5 females\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n\n```{.r .cell-code}\nmeanChol <- femSamp5 |>\n  colMeans()\ndata.frame(meanChol) |>\n  ggplot(aes(sample=meanChol)) +\n  stat_qq() +\n  stat_qq_line() +\n  ggtitle(\"Means on 5 females\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-html/unnamed-chunk-22-2.png){width=672}\n:::\n\n```{.r .cell-code}\nmeanChol <- femSamp10 |>\n  colMeans()\ndata.frame(meanChol) |> ggplot(aes(x=meanChol)) +\n  geom_histogram(aes(y=..density.., fill=..count..),bins=15) +\n  xlab(\"Mean cholesterol\") +\n  stat_function(\n    fun=dnorm,\n    color=\"red\",\n    args=list(\n      mean=femSamp10|> colMeans() |> mean(),\n      sd=femSamp10|> colMeans() |> sd())\n    ) +\nggtitle(\"Means on 10 females\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-html/unnamed-chunk-22-3.png){width=672}\n:::\n\n```{.r .cell-code}\nmeanChol <- femSamp10 |>\n  colMeans()\ndata.frame(meanChol) |>\n  ggplot(aes(sample=meanChol)) +\n  stat_qq() +\n  stat_qq_line() +\n  ggtitle(\"Means on 10 females\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-html/unnamed-chunk-22-4.png){width=672}\n:::\n\n```{.r .cell-code}\nmeanChol <- femSamp50 |>\n  colMeans()\ndata.frame(meanChol) |>\n  ggplot(aes(sample=meanChol)) +\n  stat_qq() +\n  stat_qq_line() +\n  ggtitle(\"Means on 50 females\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-html/unnamed-chunk-22-5.png){width=672}\n:::\n\n```{.r .cell-code}\nmeanChol <- femSamp100 |>\n  colMeans()\ndata.frame(meanChol) |>\n  ggplot(aes(sample=meanChol)) +\n  stat_qq() +\n  stat_qq_line() +\n  ggtitle(\"Means on 100 females\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-html/unnamed-chunk-22-6.png){width=672}\n:::\n:::\n\n\n- **We merken op dat wanneer de data niet normaal verdeeld zijn, de verdeling van het steekproefgemiddelde niet normaal verdeeld is over kleine steekproeven**\n\n- **Voor grote steekproeven is het steekproefgemiddelde van niet-normale gegevens echter nog steeds ongeveer normaal verdeeld.**\n\n***\n\n### Centrale limietstelling\n\nLaat $X_1, \\ldots, X_n$ een reeks willekeurige variabelen zijn die onafhankelijk van dezelfde verdeling (populatie) worden getrokken. Zolang de steekproefgrootte n voldoende groot is, is het steekproefgemiddelde $\\bar X$ ongeveer normaal verdeeld, ongeacht de verdeling van de waarnemingen $X_i$.\n\n### Overzicht van de verdeling van het gemiddelde\n\n![](https://www.nature.com/articles/nmeth.2613.pdf){width=100%}\n\n***\n\n# Interval schatters\n\n- $\\bar X$ varieert rond $\\mu$\n\n- hier zullen we een interval ontwikkelen rond $\\bar X$ dat de waarde $\\mu$ bevat met een waarschijnlijkheid van 95% voor een willekeurige steekproef.\n\n- We nemen eerst aan dat $\\sigma^2$ bekend is en we zullen deze aanname later versoepelen.\n\n***\n\n## Normaal verdeelde data met gekende variantie\n\n- $X\\sim N(\\mu,\\sigma^2) \\rightarrow \\bar X\\sim N\\left(\\mu,\\frac{\\sigma^2}{n}\\right)$\n\n- 95% referentie-interval voor het steekproefgemiddelde\n\n\\begin{equation*}\n\\left[\\mu - 1.96 \\frac{\\sigma}{\\sqrt{n}},\\mu + 1.96 \\frac{\\sigma}{\\sqrt{n}}%\n\\right]\n\\end{equation*}\n\n- Het interval bevat het steekproefgemiddelde van een willekeurige steekproef met een kans van 95%.\n\n- We kunnen dit niet berekenen aangezien $\\mu$ niet gekend is.\n\n- Schat $\\mu$ met $\\bar X$.  \n\\begin{equation*}\n\\left[\\bar X - 1.96 \\frac{\\sigma}{\\sqrt{n}},\\bar X + 1.96 \\frac{\\sigma}{\\sqrt{n}}\\right]\n\\end{equation*}\n\n\n- Meer bruikbare interpretatie:\n\\vspace{15pt}\n- herschrijf $\\mu - 1.96 \\ \\sigma/\\sqrt{n} < \\bar{X}$ as $\\mu < \\bar{X} + 1.96 \\ \\sigma/\\sqrt{n}$.\n\nZodat we kunnen schrijven\n\\begin{eqnarray*}\n95\\% &=& P( \\mu - 1.96 \\ \\sigma/\\sqrt{n} < \\bar{X} < \\mu + 1.96 \\ \\sigma/\\sqrt{n} ) \\\\\n&=&P( \\bar{X} - 1.96 \\ \\sigma/\\sqrt{n} < \\mu < \\bar{X} + 1.96 \\ \\sigma/\\sqrt{n} )\n\\end{eqnarray*}\n\n***\n\n**Definitie van 95% betrouwbaarheids interval op het gemiddelde**\nVoor een willekeurige steekproef bevat het interval\n\\begin{equation}  \n[\\bar{X} - 1.96 \\ \\sigma/\\sqrt{n} , \\bar{X} + 1.96 \\ \\sigma/\\sqrt{n} ],\n\\end{equation}\nhet populatiegemiddelde $\\mu$ met een kans van 95%.\n\n***\n\n- De kans dat het BI voor een willekeurige steekproef de populatieparameter\n $\\mu$ bevat, dus 95%, wordt ook wel het **betrouwbaarheidsniveau** genoemd.\n\n- Merk op dat de onder- en bovengrens van het interval ook willekeurige variabelen zijn die van steekproef tot steekproef variëren. Verschillende steekproeven resulteren inderdaad in verschillende betrouwbaarheidsintervallen omdat ze gebaseerd zijn op verschillende waarnemingen.\n\n- Het zijn dus *stochastische intervallen*\n\n- 95% van de steekproeven zullen een 95% betrouwbaarheidsinterval produceren dat het populatiegemiddelde $\\mu$ zal bevatten. De overige 5% zullen intervallen produceren die het populatiegemiddelde niet bevatten.\n\n- Op basis van één interval kun je niet concluderen dat het de werkelijke populatieparameter bevat, omdat de waarde ervan onbekend is.\n\nOver het algemeen is de standaarddeviatie ongekend en moet het geschat worden.\n\n- Voor grote $n$, zal $[\\bar{X} - 1.96 \\ s/\\sqrt{n} , \\bar{X} + 1.96 \\ s/\\sqrt{n} ]$ het populatiegemiddelde bevatten met een probabiliteit van 95%.\n\n***\n\n### NHANES log2 cholesterol voorbeeld\n\n#### 1 steekproef\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(3146)\nsamp50 <- sample(fem$DirectChol,50)\n\nll <- mean(samp50 |> log2()) - 1.96*sd(samp50 |> log2())/sqrt(50)\nul <- mean(samp50 |> log2()) + 1.96*sd(samp50 |> log2())/sqrt(50)\npopMean <- mean(fem$DirectChol|>log2())\n\nc(ll=ll,ul=ul,popMean=popMean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       ll        ul   popMean \n0.4326245 0.6291622 0.5142563 \n```\n\n\n:::\n:::\n\n\n#### Herhaalde steekproeven\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres$ll <- res$mean-1.96*res$se\nres$ul <- res$mean+1.96*res$se\nmu <- fem$DirectChol|>\n  log2()|>\n  mean()\n\nres$inside<- res$ll <= mu & mu <= res$ul\nres$n <- as.factor(res$n)\nres |>\n  group_by(n) |>\n  summarize(coverage=mean(inside)) |>\n  spread(n,coverage)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n   `10`  `50` `100`\n  <dbl> <dbl> <dbl>\n1  0.92 0.942 0.954\n```\n\n\n:::\n:::\n\n\n- Merk op dat de omvang in de steekproeven met 10 waarnemingen te laag is omdat we geen rekening houden met de onzekerheid in de schatting van de standaarddeviatie.\n\n- Als we kijken naar de eerste 20 intervallen, bevat 1  van de 20 niet het populatiegemiddelde.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres |>\n  filter(n==10) |>\n  slice(1:20) |>\n  ggplot(aes(x = sample,y = mean,color = inside)) +\n  geom_point() +\n  geom_errorbar(aes(ymin = mean-1.96*se,ymax = mean+1.96*se))+\n  geom_hline(yintercept = fem$DirectChol |> log2() |> mean()) +\n  ggtitle(\"20 CI for N = 10\") +\n  ylim(range(fem$DirectChol |> log2()))\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\n***\n\n- Voor grote steekproeven (100) is de omvang prima omdat we de standaarddeviatie met een relatief hoge precisie kunnen schatten.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres |>\n  filter(n == 50) |>\n  slice(1:20) |>\n  ggplot(aes(x = sample,y = mean,color = inside)) +\n  geom_point() +\n  geom_errorbar(aes(ymin = mean-1.96*se,ymax = mean+1.96*se))+\n  geom_hline(yintercept = fem$DirectChol |> log2() |> mean()) +\n  ggtitle(\"20 CI for N = 50\") +\n  ylim(range(fem$DirectChol |> log2()))\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n\n```{.r .cell-code}\nres |>\n  filter(n == 100) |>\n  slice(1:20) |>\n  ggplot(aes(x = sample,y = mean,color = inside)) +\n  geom_point() +\n  geom_errorbar(aes(ymin = mean-1.96*se,ymax = mean+1.96*se))+\n  geom_hline(yintercept = fem$DirectChol |> log2() |> mean()) +\n  ggtitle(\"20 CI for N = 100\") +\n  ylim(range(fem$DirectChol |> log2()))\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-html/unnamed-chunk-26-2.png){width=672}\n:::\n:::\n\n\n- Wat heb je geobserveerd voor de intervalbreedte?\n\n***\n\n### Andere betrouwbaarheidsniveaus\n\n- We kunnen $z_{2.5\\%}=1.96$ vervangen door een ander kwantiel van de normale verdeling $z_{\\alpha/2} om een interval te krijgen met een ander betrouwbaarheidsniveau $1-\\alpha$.\n\n- Betrouwbaarheidsintervallen worden niet alleen gebruikt voor het gemiddelde, maar ook voor andere populatieparameters.\n\n***\n\n## Ongekende variantie\n\nIn echte voorbeelden is $\\sigma$ ongekend en wordt het geschat op basis van de steekproef met behulp van de standaarddeviatie $S$.\n\n- De vorige intervallen waren iets te klein omdat ze geen rekening hielden met de onzekerheid over de schatting van $S$.\n\n- Als $n$ groot is, ligt $S$ in de buurt van $\\sigma$.\n\n- Vandaar dat ${(\\bar{X} - \\mu)}/{(S/\\sqrt{n}) }$ ongeveer standaard normaal verdeeld is en\n\\begin{equation*}\n\\left[\\bar{X} - z_{\\alpha/2} \\ \\frac{S}{\\sqrt{n}} , \\bar{X} + z_{\\alpha/2} \\\n\\frac{S}{\\sqrt{n}}\\right]\n\\end{equation*}\nis een geschatte $(1- \\alpha)100\\%$ CI voor $\\mu$.\n\n- Voor kleine steekproeven geldt dit niet meer (e.g. n=10)\n\nDe schatting van $S$ introduceert extra onzekerheid in de gestandaardiseerde waarde ${(\\bar{X} - \\mu)}/{(S/\\sqrt{n})}$. Zijn distributie\n\n- is nog steeds symmetrisch maar heeft zwaardere staarten dan de normale verdeling.\n\n- Het hangt van $n$ af hoeveel zwaarder de staarten zijn\n\n- is een (Student) $t$-verdeling met $n-1$ *vrijheidsgraden*.\n\n***\n\n### T-verdeling\n\nFormeel: Let $X_1, X_2, ..., X_n$ een onafhankelijke willekeurige steekproef zijn uit een normale verdeling $N(\\mu, \\sigma^2)$, dan volgt $(\\bar{X} - \\mu)/(S/\\sqrt{n})$ een $t$-verdeling met $n-1$ vrijheidsgraden.\n\nDe densiteit van een t-verdeling kan worden berekend in R met de functie `dt`. Het heeft argumenten 'x' voor het kwantiel en 'df' voor de vrijheidsgraden.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrid <- seq(-5,5,.1)\ndensDist <- cbind(grid,dnorm(grid), sapply(c(2,5,10),dt,x=grid))\ncolnames(densDist) <- c(\"x\",\"normal\",paste0(\"t\",c(2,5,10)))\n\ndensDist |>\n  as.data.frame() |>\n  gather(dist,dens,-x) |>\n  ggplot(aes(x=x,y=dens,color=dist)) +\n  geom_line() +\n  xlab(\"x\") +\n  ylab(\"Densiteit\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\n\nt-verdelingen hebben zwaardere staarten dan de normale verdeling $\\rightarrow$ grotere kantielen, dus bredere intervallen voor hetzelfde betrouwbaarheidsniveau.\n\n- Dit geeft de extra onzekerheid weer voor het schatten van $S$.\n\n- Als $n \\rightarrow \\infty$ dan $t(df) \\rightarrow N(0,1)$\n\n\n- kwantielen van de $t$-verdeling kunnen worden berekend in R met behulp van `qt`. bv. 95%, 97.5%, 99.5% kwantiel voor een t-verdeling met 14 vrijheidsgraden.\n\n::: {.cell}\n\n```{.r .cell-code}\nqt(.975,df=14)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.144787\n```\n\n\n:::\n\n```{.r .cell-code}\nqt(c(.95,.975,.995),df=14)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.761310 2.144787 2.976843\n```\n\n\n:::\n:::\n\n\n- Deze kwantielen kunnen gebruikt worden om de 90%, 95% and 99% CI te berekenen.\n\n- 97.5% kwantiel2.14 van een t-verdeling met $n-1=14$ vrijheidsgraden is inderdaad groter dan die van een standaard normale verdeling 1.96.\n\n***\n### Betrouwbaarheidsinterval gebaseerd op de t-verdeling\n\nDe $100\\% (1-\\alpha)$ CI voor het gemiddelde $\\mu$ van een normaal verdeelde willekeurige variabele $X$ met ongekende variantie is\n\n\\begin{equation*}\n\\left[\\bar{X} - t_{n-1, \\alpha/2} \\frac{s}{\\sqrt{n}} , \\bar{X} + t_{n-1,\n\\alpha/2} \\frac{s}{\\sqrt{n}}\\right]\n\\end{equation*}\n\n- We vervangen eenvoudig het $(1-\\alpha/2)100\\%$ kwantiel van de normale verdeling door die van de t-verdeling met $n-1$ vrijheidsgraden.\n\n### Captopril voorbeeld\n\n\n95% CI voor de gemiddelde bloeddrukverandering wordt\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(captopril$deltaSBP) -  qt(.975,df=14)*sd(captopril$deltaSBP)/sqrt(15)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -23.93258\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(captopril$deltaSBP) + qt(.975,df=14)*sd(captopril$deltaSBP)/sqrt(15)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -13.93409\n```\n\n\n:::\n:::\n\n\nHet 99% CI is gegeven door\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(captopril$deltaSBP) -  qt(.995,df=14)*sd(captopril$deltaSBP)/sqrt(15)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -25.87201\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(captopril$deltaSBP) + qt(.995,df=14)*sd(captopril$deltaSBP)/sqrt(15)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -11.99466\n```\n\n\n:::\n:::\n\n\nMerk op dat nul buiten het interval ligt en dat het gehele interval negatief is, wat aangeeft dat er gemiddeld een groot effect is van het toedienen van captopril op de bloeddruk van patiënten met hypertensie.\n\n***\n\n### Interpretatie van het betrouwbaarheidsinterval\n\n- We zullen opnieuw steekproeven trekken van de grote NHANES studie en deze keer BI's bestuderen voor log2-cholesterol steekproefwaarden. We voeren eerst herhaalde experimenten uit met steekproefgrootte 10.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres$n <- as.character(res$n) |>\n  as.double(res$n)\n\nres$ll <- res$mean-qt(0.975,df=res$n-1)*res$se\nres$ul <- res$mean+qt(0.975,df=res$n-1)*res$se\n\nmu <- fem$DirectChol|>log2()|>mean()\n\nres$inside <- res$ll<=mu & mu<=res$ul\nres$n <- as.factor(res$n)\n\nres |>\n  group_by(n) |>\n  summarize(coverage=mean(inside)) |>\n  spread(n,coverage)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n   `10`  `50` `100`\n  <dbl> <dbl> <dbl>\n1 0.949 0.947 0.959\n```\n\n\n:::\n:::\n\n\nWe zien dat de omvang van de intervallen nu worden gecontroleerd op hun nominale betrouwbaarheidsniveau van 95%.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres |>\n  filter(n==10) |>\n  slice(1:20) |>\n  ggplot(aes(x=sample,y=mean,color=inside)) +\n  geom_point() +\n  geom_errorbar(\n    aes(ymin=mean-qt(0.975,df=9)*se,\n    ymax=mean+qt(0.975,df=9)*se))+\n  geom_hline(yintercept = fem$DirectChol |> log2() |> mean()) +\n  ggtitle(\"20 CI for N=10\") +\n  ylim(range(fem$DirectChol |> log2()))\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n:::\n\n\n***\nOpdracht\n\nVoer de bovenstaande simulatie studie opnieuw uit maar verdubbel de steekproefgrootte. Welke impact heeft dit op de BIs?\n***\n\n![](https://www.nature.com/articles/nmeth.2659.pdf){width=100%}\n\n***\n\n## Rapporteren?\n\n\n- Rapporteer altijd de onzekerheid over de resultaten!\n\n- Conclusies op basis van een puntschatting kunnen erg misleidend zijn.\n\n- Bij een statistische analyse rapporteren we daarom altijd betrouwbaarheidsintervallen\n\n- Ze zijn klein genoeg om informatief te zijn, maar bijna nooit misleidend\n\n- Ze vormen een goede afweging tussen statistische significantie en biologische relevantie.\n\n\n- Rapporteer altijd de onzekerheid op de resultaten!\n\n- Bij een statistische analyse rapporteren we daarom altijd betrouwbaarheidsintervallen\n\n- De intervallen zijn klein genoeg om informatief te zijn, maar bijna nooit misleidend\n\n- Ze vormen een goede afweging tussen statistische significantie en biologische relevantie.\n\n- We concluderen dat de populatieparameter in het interval ligt en weten dat deze stelling geldt met een probabiliteit van 95% voor willekeurige steekproeven.\n\n### Captopril voorbeeld\n\nWe concluderen dat de bloeddruk gemiddeld met\n18.9mmHg vermindert na toediening van captopril (95% CI [-23.9,-13.9]mmHg).\n\nOp basis van deze resultaten is het duidelijk dat de behandeling een sterke bloeddrukdaling veroorzaakt bij patiënten met hypertensie.\n\n# Hypothese testen\n\n## Captopril voorbeeld:\nOnderzoekers willen beoordelen of het medicijn captopril de bloeddruk verlaagt bij patiënten met hypertensie.\n\n- Heeft het toedienen van captopril wel of geen effect op de systolische bloeddruk?\n\n- Het ligt niet voor de hand om dergelijke conclusies te trekken op basis van een kleine steekproef\n\n- Het is onzeker of we de observaties in de steekproef naar de populatie kunnen veralgemenen!\n\n-  Is het schijnbaar gunstige effect systematisch of willekeurig?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncaptoprilTidy |>\n  filter(type%in%c(\"SBPa\",\"SBPb\")) |>\n  mutate(type=factor(type,levels=c(\"SBPb\",\"SBPa\"))) |>\n  ggplot(aes(x=type,y=bp)) +\n  geom_line(aes(group = id)) +\n  geom_point()\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-html/unnamed-chunk-33-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncaptopril$deltaSBP <- captopril$SBPa-captopril$SBPb\ncaptopril|>\n  ggplot(aes(x=\"Systolic blood pressure\",y=deltaSBP)) +\n  geom_boxplot(outlier.shape=NA) +\n  geom_point(position=\"jitter\")+\n  ylab(\"Difference (mm mercury)\") +\n  xlab(\"\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-html/unnamed-chunk-34-1.png){width=672}\n:::\n:::\n\n\n\n- Het gemiddelde bloeddrukverschil $\\bar X$ is een natuurlijke basis om onze beslissingen op te baseren.\n\n$$\\bar x\\text{=-18.93 (s=9.03, SE=2.33)}$$\n\n- Het is niet voldoende dat $\\bar{x}< 0$ om te concluderen dat de systolische bloeddruk gemiddeld lager is bij toediening van Captopril *op het niveau van de gehele populatie*.\n\n- Om het effect dat we in de steekproef waarnemen te veralgemenen naar de populatie, moet het voldoende groot zijn.\n\n- Maar hoe groot?\n\n***\n\n### Hypothese testen\n\n- Voor dit doel zijn statistische hypothesetests ontwikkeld\n- Deze geven een zwart/wit antwoord\n- Het is bijna onmogelijk om een wetenschappelijke publicate te lezen zonder resultaten van statistische testen\n- Volgens het *falsificatie principe* van Popper kunnen we nooit een hypothese bewijzen op basis van gegevens.\n\n    - Daarom introduceren we twee hypothesen: een nulhypothese $H_0$ en een alternatieve hypothese $H_1$.\n\n    - We zullen proberen de nulhypothese te ontkrachten op basis van de statistische test.\n\n#### Captopril\n\n- Op basis van de steekproef kunnen we niet bewijzen dat er een effect is van het toedienen van captopril ($H_1$, alternatieve hypothese).\n\n- We veronderstellen daarom dat er geen effect is van captopril\n\n    - We noemen dit de nulhypothese $H_0$.\n\n    - Falsify (\"probeer te ontkrachten\") de $H_0$.\n\n    - Hoe waarschijnlijk is het om een effect waar te nemen dat minstens zo groot is als wat we in de steekproef in een willekeurige steekproef hebben gezien als $H_0$ waar is?  \n\n***\n\n\n#### Permutatie test\n\n\n- Onder $H_0$ zijn de bloeddrukmetingen voor en na toediening van captopril twee \"base line\" bloeddrukmetingen voor een patiënt\n\n- Onder H$_0$ kunnen we de bloeddrukmetingen voor iedere patiënt in willekeurige volgorde plaatsen (permuteren).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(35)\ncaptoprilSamp <- captopril\nperm <- sample(c(FALSE, TRUE), 15, replace = TRUE)\ncaptoprilSamp$SBPa[perm] <- captopril$SBPb[perm]\ncaptoprilSamp$SBPb[perm] <- captopril$SBPa[perm]\ncaptoprilSamp$deltaSBP <- captoprilSamp$SBPa-captoprilSamp$SBPb\ncaptoprilSamp |>\n  gather(type, bp, -id) |>\n  filter(type %in% c(\"SBPa\",\"SBPb\")) |>\n  mutate(type = factor(type, levels = c(\"SBPb\", \"SBPa\")))|>\n  ggplot(aes(x = type,y = bp)) +\n  geom_line(aes(group = id)) +\n  geom_point()\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-html/unnamed-chunk-35-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata.frame(\n  deltaSBP = c(captopril$deltaSBP,captoprilSamp$deltaSBP),\n  shuffled=rep(c(FALSE,TRUE),each=15)\n  ) |>\n  ggplot(aes(x = shuffled, y = deltaSBP)) +\n  geom_boxplot(outlier.shape = NA) +\n  geom_point(position = \"jitter\")+\n  stat_summary(\n    fun.y = mean,\n    geom = \"point\",\n    shape = 19,\n    size = 3,\n    color = \"red\",\n    fill = \"red\") +\n  ylab(\"Difference (mm mercury)\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-html/unnamed-chunk-36-1.png){width=672}\n:::\n:::\n\n\nWe permuteren opnieuw\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncaptoprilSamp <- captopril\nperm <- sample(c(FALSE,TRUE), 15, replace = TRUE)\ncaptoprilSamp$SBPa[perm] <- captopril$SBPb[perm]\ncaptoprilSamp$SBPb[perm] <- captopril$SBPa[perm]\ncaptoprilSamp$deltaSBP <- captoprilSamp$SBPa-captoprilSamp$SBPb\ncaptoprilSamp |>\n  gather(type, bp, -id) |>\n  filter(type %in% c(\"SBPa\",\"SBPb\")) |>\n  mutate(type = factor(type, levels = c(\"SBPb\", \"SBPa\")))|>\n  ggplot(aes(x = type,y = bp)) +\n  geom_line(aes(group = id)) +\n  geom_point()\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-html/unnamed-chunk-37-1.png){width=672}\n:::\n\n```{.r .cell-code}\ndata.frame(\n  deltaSBP = c(captopril$deltaSBP,captoprilSamp$deltaSBP),\n  shuffled=rep(c(FALSE,TRUE),each=15)\n  ) |>\n  ggplot(aes(x = shuffled, y = deltaSBP)) +\n  geom_boxplot(outlier.shape = NA) +\n  geom_point(position = \"jitter\")+\n  stat_summary(\n    fun.y = mean,\n    geom = \"point\",\n    shape = 19,\n    size = 3,\n    color = \"red\",\n    fill = \"red\") +\n  ylab(\"Difference (mm mercury)\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-html/unnamed-chunk-37-2.png){width=672}\n:::\n:::\n\n\n\n- Er zijn $2^{15}$ = 32768 mogelijke permutaties!\n- We hoeven in principe alleen de tekens van de waargenomen bloeddrukverschillen $x$ te wisselen als we permuteren.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npermH <- expand.grid(\n  replicate(\n    15,\n    c(-1,1),\n    simplify=FALSE)\n  ) |>\n  t()\n\npermH[,1:5]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      [,1] [,2] [,3] [,4] [,5]\nVar1    -1    1   -1    1   -1\nVar2    -1   -1    1    1   -1\nVar3    -1   -1   -1   -1    1\nVar4    -1   -1   -1   -1   -1\nVar5    -1   -1   -1   -1   -1\nVar6    -1   -1   -1   -1   -1\nVar7    -1   -1   -1   -1   -1\nVar8    -1   -1   -1   -1   -1\nVar9    -1   -1   -1   -1   -1\nVar10   -1   -1   -1   -1   -1\nVar11   -1   -1   -1   -1   -1\nVar12   -1   -1   -1   -1   -1\nVar13   -1   -1   -1   -1   -1\nVar14   -1   -1   -1   -1   -1\nVar15   -1   -1   -1   -1   -1\n```\n\n\n:::\n:::\n\n\n- We zullen dit voor alle mogelijke permutaties doen en we zullen het gemiddelde bijhouden.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#calculate the means for the permuted data\nmuPerm <- colMeans(permH*captopril$deltaSBP)\ndata.frame(permMean = muPerm) |>\n  ggplot(aes(x=permMean)) +\n  geom_histogram() +\n  geom_vline(\n    xintercept = mean(captopril$deltaSBP),\n    col = \"blue\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-html/unnamed-chunk-39-1.png){width=672}\n:::\n\n```{.r .cell-code}\nsum(muPerm <= mean(captopril$deltaSBP))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(muPerm <= mean(captopril$deltaSBP))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.051758e-05\n```\n\n\n:::\n:::\n\n\n-  We zien dat maar 1 van de gemiddelden die werden verkregen onder $H_0$ (door permutatie) zo extreem was als het steekproefgemiddelde dat we in de captopril-studie hebben waargenomen.\n\n- Dus de kans om een bloeddrukdaling waar te nemen die groter of gelijk is dan die in de captopril-studie in een willekeurige steekproef onder de nulhypothese, is 1 op de 32768.\n\nWe hebben dus sterk bewijs dat $H_0$ onjuist is en daarom verwerpen we $H_0$ en concluderen $H_1$: het toedienen van captopril heeft een effect op de bloeddruk van patiënten met hypertensie.\n\n***\n\n### Pivot\n\n- In de praktijk gebruiken we altijd statistieken die de effectgrootte (gemiddeld verschil) afwegen tegen ruis (standaard error)\n\n- Als we de nulhypothese ontkrachten, standaardiseren we het gemiddelde rond $\\mu_0 = 0$ het gemiddelde onder $H_0$\n\n$$t=\\frac{\\bar X-\\mu_0}{se_{\\bar X}}$$\n\n- Voor het Captopril voorbeeld wordt dit:\n$$\\frac{-18.93-0}{2.33}=-8.12$$\n\n\nWe bepalen nu de nulverdeling van teststatistiek t met permutatie.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndeltaPerms <- permH*captopril$deltaSBP\ntPerm <- colMeans(deltaPerms)/(apply(deltaPerms,2,sd)/sqrt(15))\ntOrig <- mean(captopril$deltaSBP)/sd(captopril$deltaSBP)*sqrt(15)\n\ntPermPlot <- data.frame(permT = tPerm) |>\n  ggplot(aes(x=permT)) +\n  geom_histogram(aes(y = ..density.., fill = ..count..)) +\n  geom_vline(xintercept = tOrig,col = \"blue\")\ntPermPlot\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-html/unnamed-chunk-40-1.png){width=672}\n:::\n:::\n\n\n- Opnieuw heeft slechts 1 van de permutaties een t-statistiek die zo extreem is als de statistiek die wordt waargenomen in de captopril-studie.\n\nWanneer er geen effect van captopril is, is het bijna onmogelijk om een \u000b\u000bteststatistiek te verkrijgen die zo extreem is als degene die werd waargenomen (  t=-8.12).\n\n-De kans om een grotere bloeddrukdaling waar te nemen dan degene die we in onze steekproef hebben waargenomen in een willekeurige steekproef onder $H_0$ is 1/32768.\n\n- We noemen deze kans de *p-waarde*.\n\n- Het meet de sterkte van het bewijs tegen de nulwaarde: hoe kleiner de p-waarde, hoe meer bewijs we hebben dat de nulwaarde niet waar is.\n\n- De verdeling heeft een mooie klokvorm.\n\n***\n\n### Hoe beslissen we?\n\nWanneer is de p-waarde klein genoeg om te concluderen dat er sterk bewijs is tegen de nulhypothese?\n\n- We werken doorgaans met een significantieniveau van $\\alpha = 0,05$\n\n- We stellen dat we de test hebben uitgevoerd op het significantieniveau van 5%\n\n***\n\n\n### Permutatietests zijn computationeel veeleisend\n\n- Kunnen we beoordelen hoe extreem de bloeddrukdaling was zonder permutatie?\n\n- We weten dat de bloeddrukverschillen ongeveer normaal verdeeld zijn, dus\n\n$$t=\\frac{\\bar X - \\mu}{se_{\\bar X}}$$\n\nvolgt een t-verdeling (met 14 vrijheidsgraden voor het Captopril voorbeeld).\n\n\n- Onder H$_0$ $\\mu=0$ en $$t=\\frac{\\bar X-0}{se_{\\bar X}}\\sim f_{T,14}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntPermPlot +\n  stat_function(\n    fun = dt,\n    color = \"red\",\n    args = list(df=14))\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-html/unnamed-chunk-41-1.png){width=672}\n:::\n:::\n\n\n\n- Merk op dat de permutatie-nulverdeling inderdaad overeenkomt met een t-verdeling met 14 vrijheidsgraden.\n\n- Zodat we de statistische test kunnen uitvoeren met behulp van statistische modellen van de gegevens.\n\n- Hiervoor moeten we assumpties maken, die we verifiëren in de data exploratie.\n\n\n***\n\n\n## Hypotheses\n\nVertaal de onderzoeksvraag naar een nulhypothese ($H_0$) en een alternatieve hypothese ($H_1$)\n\nEerst moeten we de onderzoeksvraag vertalen naar een geparametriseerd statistisch model.  \n\n- Uit het experimentele ontwerp volgt dat  $$X_1,...,X_n \\text{ i.i.d } f(X),$$ met $f(X)$ de dichtheidsfunctie van bloeddrukverschillen.\n\n- **vereenvoudig**: neem aan dat $f(X)$ gekend is met uitzondering van een eindig dimensionale set parameters $\\mathbf{\\theta}$ die nog moet worden geschat (parametrisch statistisch model).\n\n### Captopril voorbeeld\n\n$X \\sim N(\\mu,\\sigma^2)$ with $\\mathbf{\\theta}=(\\mu,\\sigma^2)$, the mean $\\mu$ and variance $\\sigma^2$.\n\nDe onderzoeksvraag is nu vertaald in termen van de gemiddelde bloeddrukdaling:: $\\mu = E_f[X]$.\n\nDe **alternatieve hypothese**  is geformuleerd in termen van een parameter van $f(X)$  moet uitdrukken wat de onderzoekers met het onderzoek willen bewijzen.\n\n- hier:\n$$H_1: \\mu<0.$$ Gemiddeld daalt de bloeddruk van patiënten met hypertensie na toediening van captopril.\n\n\nDe **nul hypothese** drukt over het algemeen een nulvoorwaarde uit, d.w.z wanneer er niets uitzonderlijks gebeurt.\n\n- Onderzoekers proberen doorgaans via empirisch onderzoek aan te tonen dat het observeren van de gegevens onder de nul hoogst onwaarschijnlijk is, zodat ze de nulhypothese kunnen verwerpen:\n**Falsificatie principe**.\n\n- De **nul hypothese wordt doorgaans uitgedrukt met dezelfde modelparameter als die wordt gebruikt voor $H_1$.**\n\n- Hier:\n$$H_0 : \\mu=0$$ d.w.z. gemiddeld blijft de systolische bloeddruk ongewijzigd na toediening van captopril.\n\n\n***\n\n## Test-statistiek\n\n\n\nZodra de populatie, de parameters en $H_0$ en $H_1$ zijn bepaald, volgt men bij hypothesetesten de volgende rationale:\n\nConstrueer een teststatistiek zodat deze\n\n1. het bewijs meet in de steekproef,\n\\vspace{10pt}\n2. tegen de nulhypothese, en\n\\vspace{10pt}\n3. in het voordeel van de alternatieve hypothese.\n\nEen teststatistiek moet dus een functie zijn van de waarnemingen in de steekproef.\n\n\n### Captopril voorbeeld\n\n\n$$T=\\frac{\\bar{X}-\\mu_0}{\\text{SE}_{\\bar X}}$$\nMet $\\mu_0=0$ onder $H_0$\n\nOpnieuw\n\n- Als $H_0$ geldt, is er geen effect van captopril op de bloeddruk in de populatie en dan verwachten we teststatistiek $T$ dicht bij 0.\n\n- Als $H_1$ waar is, verwachten we $T <0$.\n\n- In het captopril voorbeeld observeren we $t=(-18.93-0)/2.33=-8.12$.\n\n- Is $t = -8.12$ in absolute waarde groot genoeg om te concluderen dat  $\\mu < 0$ en met welk vertrouwen kunnen we deze conclusie trekken?\n\n- We weten dat t een t-verdeling volgt met 14 vrijheidsgraden onder $H_0$  \n\n\n***\n\n## p-waarde\n\nDe p-waarde is de probabiliteit die $H_0$ en $H_1$ afweegt.\n\nDe manier waarop we het berekenen is contextafhankelijk\n\n- Voor het Captopril voorbeeld hebben we\n  $$\n    p = P\\left[T \\leq t \\mid H_0\\right] = \\text{P}_0\\left[T\\leq t\\right],\n  $$\nDe index \"0\" in $\\text{P}_0\\left[.\\right]$ geeft aan dat de kans wordt berekend onder $H_0$.\n\nHet geeft de kans weer om een teststatistiek $T$ te bekomen die lager of gelijk is aan de waarde die wordt waargenomen in de huidige steekproef in een willekeurige steekproef onder $H_0$ waar te nemen.\n    - d.w.z. de kans om een teststatistiek $T$ te vinden in een willekeurige steekproef onder $H_0$ met een waarde die extremer is (meer in de richting van $H_1$) dan die waargenomen in de huidige steekproef.\n\n### Captopril Voorbeeld\n\n\n- De $p$-waarde voor het captopril voorbeeld wordt als volgt berekend.\n  $$p= \\text{P}_0\\left[T\\leq -8.12\\right]=F_t(-8.12;14) = 0.6\\ 10^{-6}.$$\n\n  met $F_t(;14)$  de cumulatieve verdelingsfunctie van een t-verdeling met 14 vrijheidsgraden:\n\n$$F_t(x;14)=\\int\\limits_{-\\infty}^{x} f_t(x;14).$$\n\nen $f_t(.;14)$ de dichtheidsfunctie van de t-verdeling.\n\n- We berekenen deze kans in R met `pt(x,df)`\n\n    - De waarde van de waargenomen teststatistiek `x` en\n    - het aantal vrijheidsgraden van de t-verdeling \"df\".\n\n- `pt(x,df)` berekent de kans om een waarde kleiner of gelijk aan x waar te nemen als we een willekeurige steekproef zouden trekken uit een t-verdeling met df vrijheidsgraden.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- length(captopril$deltaSBP)\nstat <- (mean(captopril$deltaSBP)-0)/(sd(captopril$deltaSBP)/sqrt(n))\nstat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -8.122816\n```\n\n\n:::\n\n```{.r .cell-code}\npt(stat,n-1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.731936e-07\n```\n\n\n:::\n:::\n\n\n\nIn de praktijk gaan we de test niet zelf berekenen, maar gebruiken we de functie t.test:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(captopril$deltaSBP, alternative = \"less\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  captopril$deltaSBP\nt = -8.1228, df = 14, p-value = 5.732e-07\nalternative hypothesis: true mean is less than 0\n95 percent confidence interval:\n      -Inf -14.82793\nsample estimates:\nmean of x \n-18.93333 \n```\n\n\n:::\n:::\n\n\nMerk op dat we het argument `alternative=\"less\"` moeten specificeren, zodat de p-waarde in de linker staart wordt berekend.\n\n\nDe functie geeft ook een eenzijdig interval omdat we in één richting testen.\n\n***\n\n### Definitie van de p-waarde\n\nDe **p-waarde** (ook wel het ** waargenomen significantieniveau ** genoemd) is de kans om een teststatistiek in een willekeurige steekproef waar te nemen onder de nulhypothese die even extreem of extremer is dan de teststatistiek die in de huidige steekproef is waargenomen\n\n\n- Hoe kleiner de kans, hoe meer bewijs tegen $H_0$.\n\n- Merk op dat de p-waarde ** niet ** de kans is dat de nulhypothese waar is!\n\n- Het woord \"extreem\" geeft aan in welke richting de teststatistiek waarschijnlijker is onder de alternatieve hypothese.\n\n- In het voorbeeld $H_1: \\mu < 0$ n we verwachten dus zeer negatieve waarden voor $t$ onder $H_1$.\n\n- Vanuit de definitie geven kleine p-waarden aan dat de geobserveerde teststatistiek onwaarschijniljk is in de veronderstelling dat $H_0$ correct is.\n\n- Dus een kleine waarde van $p$-waarde betekent dat we ** $H_0$ ** moeten afwijzen ten gunste van $H_1$.\n\n- De drempel die we gebruiken om de $p$-waarde te vergelijken, wordt het **significantie nievau** genoemd en wordt aangegeven met $\\alpha$.\n\n- Een statistische test uitgevoerd op het $\\alpha$ significantie niveau wordt ook wel een **niveau-$\\alpha$ test**.\n\nEen test resultaat is *statistisch significant* als $p<\\alpha$\n\n- $\\alpha$ wordt gewoonlijk gezet op 5\\%.\n\n- Hoe kleiner de p-waarde hoe `significanter' het testresultaat afwijkt van wat onder $H_0$ verwacht kan worden.\n\n- Het vat het bewijs tegen de nul samen.\n\n$$\\begin{array}{cl}>0.10 & \\text{ non significant (no evidence)}\\\\0.05-0.10 & \\text{ marginal significant, weak evidence (do not use this yourself)}\\\\0.01-0.05 & \\text{ significant}\\\\0.001-0.01 & \\text{strongly significant}\\\\<0.001 & \\text{ extremely significant}\\end{array}$$\n\n***\n\n## Kritieke waarde\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-html/unnamed-chunk-44-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n***\n\n## Beslissingsfouten\n\nDe beslissing om $H_0$ te accepteren of te verwerpen wordt genomen op basis van een enkele steekproef.\nEr kan een verkeerde beslissing zijn genomen.\n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table\" style=\"margin-left: auto; margin-right: auto;\">\n <thead>\n<tr>\n<th style=\"empty-cells: hide;border-bottom:hidden;\" colspan=\"1\"></th>\n<th style=\"border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; \" colspan=\"2\"><div style=\"border-bottom: 1px solid #ddd; padding-bottom: 5px; \">Reality</div></th>\n</tr>\n  <tr>\n   <th style=\"text-align:center;\"> Conclusion </th>\n   <th style=\"text-align:center;\"> H0 </th>\n   <th style=\"text-align:center;\"> H1 </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:center;\"> Accept H0 </td>\n   <td style=\"text-align:center;\"> OK </td>\n   <td style=\"text-align:center;\"> Type II ($\\beta$) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Reject H0 </td>\n   <td style=\"text-align:center;\"> Type I ($\\alpha$) </td>\n   <td style=\"text-align:center;\"> OK </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n - Type I error, $\\alpha$: de nul hypothese wordt ten onrechte verworpen (vals positief)\n \\vspace{10pt}\n - Type II error, $\\beta$: de nulhypothese wordt ten onrechte aanvaard\n\n - Beslissing is ook stochastisch! Zie eerste hoofdstuk van de cursus\n\n### Captopril Voorbeeld\n\n- $H_0$: Het toedienen van captopril heeft geen effect op de systolische bloeddruk\n\n- $H_1$: Het toedienen van captopril leidt gemiddeld tot een verlaging van de bloeddruk\n\n- **Type I error**: er is gemiddeld geen bloeddrukdaling bij toediening van captopril, maar we concluderen dat er een effect is van captopril.\n\n- **Type II error**: er is gemiddeld een bloeddrukdaling bij toediening van captopril, maar deze wordt niet opgemerkt door de statistische test.\n\n***\n\n### Type I fout wordt gecontroleerd\n\n\nDe type I-fout wordt gecontroleerd door de constructie van de statistische test.\n\n$$\\text{P}\\left[\\text{type I error}\\right]=\\text{P}\\left[\\text{reject }H_0 \\mid H_0\\right] = \\text{P}_0\\left[T<t_{n-1;1-\\alpha}\\right]=\\alpha $$\n\n\n- Het significantieniveau $\\alpha$ is de kans om een type I-fout te maken.\n\n- De statistische test zorgt ervoor dat de kans op een type I-fout wordt gecontroleerd op het significantieniveau $\\alpha$.\n\n- De kans om $H_0$ correct te accepteren is $1-\\alpha$.\n\n- We kunnen aantonen dat de p-waarde onder $H_0$ uniform verdeeld is.\n\n- Het testen van statistische hypothesen leidt dus tot een uniforme beslissingsstrategie.\n\nWe illustreren dit in een simulatiestudie\n\n- n=15\n- $\\mu=0$ mmHg, er is dus geen effect van de behandeling\n- $\\sigma =9$ mmHg\n- 1000 gesimuleerde steekproeven\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnsim <- 10000\nn <- 15\nsigma <- 9\nmu <- 0\nmu0 <- 0\nalpha <- 0.05\n\n#simulate nsim samples of size n\ndeltaSim <- matrix(\n  rnorm(n*nsim,mu,sigma),\n  nrow=n,\n  ncol=nsim)\n\npSim <- apply(\n  deltaSim,\n  2,\n  function(x, mu, alternative)    \n    t.test(x,\n      mu = mu,\n      alternative = alternative)$p.value,\n      mu = mu0,\n      alternative=\"less\"\n  )\n\nmean(pSim<alpha)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0513\n```\n\n\n:::\n\n```{.r .cell-code}\ndata.frame(pValue = pSim) |>\n  ggplot(aes(x=pValue)) +\n  geom_histogram() +\n  xlim(0,1)\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-html/unnamed-chunk-46-1.png){width=672}\n:::\n:::\n\n\n- De type I-fout is inderdaad ongeveer 0,05\n- De p-waarden zijn uniform\n***\n\n### Type II fout\n\n- Type II-fout bepalen is minder duidelijk.\n- We moeten redeneren onder $H_1$\n- In the captopril voorbeeld is $H_1: \\mu<0$\n- Er zijn veel mogelijke alternatieven\n- De verdeling onder $H_1$ is niet volledig gespecificeerd\n\n- *oplossing:* kies een specifieke distributie onder $H_1$.\n\n $$H_1(\\delta): \\mu=0-\\delta \\text{ for }\\delta>0.$$\n\n- bijv. een bloeddrukverschil van 2 mmHg\n\n- type II wordt ook wel de **kracht** of \"power\" genoemd. Het is de kans om de alternatieve hypothese te aanvaarden.\n\n- Het wordt niet gegarandeerd door het design van de test\n\n- Het hangt af van de experimentele opzet van de studie\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnsim <- 10000\nn <- 15\nsigma <- 9\nmu <- -2\nmu0 <- 0\nalpha <- 0.05\n\n#simulate nsim samples of size n\ndeltaSim <- matrix(\n  rnorm(n*nsim, mu, sigma),\n  nrow=n,\n  ncol=nsim)\n\npSim <- apply(\n  deltaSim,\n  2,\n  function(x,mu,alternative)          \n    t.test(x,\n      mu = mu,\n      alternative = alternative)$p.value,\n      mu = mu0,\n      alternative = \"less\"\n  )\n\nmean(pSim<alpha)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2055\n```\n\n\n:::\n\n```{.r .cell-code}\ndata.frame(pValue = pSim) |>\n  ggplot(aes(x=pValue)) +\n  geom_histogram() +\n  xlim(0,1)\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-html/unnamed-chunk-47-1.png){width=672}\n:::\n:::\n\n- We observeren dat een power van 0.2055 of een type II error van 0.7945.\n\n***\n\n- Wanneer we de steekproefgrootte vergroten\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnsim <- 10000\nn <- 30\nsigma <- 9\nmu <- -2\nmu0 <- 0\nalpha <- 0.05\n\n#simulate nsim samples of size n\ndeltaSim <- matrix(\n  rnorm(n*nsim, mu, sigma),\n  nrow=n,\n  ncol=nsim)\n\npSim <- apply(\n  deltaSim,\n  2,\n  function(x,mu,alternative)          \n    t.test(x,\n      mu = mu,\n      alternative = alternative)$p.value,\n      mu = mu0,\n      alternative = \"less\"\n  )\n\nmean(pSim < alpha)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3189\n```\n\n\n:::\n\n```{.r .cell-code}\ndata.frame(pValue = pSim) |>\n  ggplot(aes(x=pValue)) +\n  geom_histogram() +\n  xlim(0,1)\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-html/unnamed-chunk-48-1.png){width=672}\n:::\n:::\n\n\n- Het vergroten van de steekproefgrootte leidt tot een hogere power.\n- Toch blijft de power om zo'n kleine bloeddrukdaling op te vangen erg laag.\n- Een daling van 2 mmHg is ook niet relevant voor farmaceutische bedrijven.\n\n![](https://www.nature.com/articles/nmeth.2738.pdf){width=100%}\n\n***\n\n### Interpretatie\n\nStel dat een bepaalde steekproef $p < \\alpha$, d.w.z. $H_0$  afwijzen\n\n- Twee mogelijkheden\n\n    - Correcte beslissing,\n\t  - of type I fout.\n\n- We weten dat de kans op een type-I fout klein is, d.w.z. $\\alpha=0.05$.\n\n\nAan de andere kant als $p\\geq\\alpha$ en we $H_0$ niet afwijzen hebben we ook twee opties:\n\n  - Correcte beslissing,\n  - of we hebben een type II fout gemaakt.\n\nDe kans op een type II fout ($\\beta$) wordt niet gecontroleerd op een specifieke waarde.\n\nStatistische test is geconstrueerd om alleen de kans op een type I-fout op  $\\alpha$ te controleren.\n\nOm wetenschappelijk correct te zijn, moeten we een pessimistische houding aannemen en moeten we toegeven dat $\\beta$ groot kan zijn (d.w.z. een kleine power om het alternatief te detecteren).\n\nDus,\n\n- $p < \\alpha$ we verwerpen $H_0$\n\n    - We concluderen dat $H_1$ waarschijnlijk correct is\n\t  - We noemen dit een sterke conclusie\n\n- $p \\geq \\alpha$ accepteer $H_0$  \n\n\t  - Betekent niet dat we $H_0$ correct accepteren.\n  \t- We kunnen enkel concluderen dat de gegevens onvoldoende bewzijs hebben tegen de $H_0$ in voordeel van $H_1$.\n    - Dit noemen we een zwakke conclusie\n    - We concluderen doorgaans dat het effect van de behandeling niet significant is.\n\n***\n\n## Conclusies captopril voorbeeld\n\n\nDe test die we hebben uitgevoerd, wordt aangeduid als\n\n\n- De **enkele steekproef t-test** op het verschil of\n\n- een **gepaarde t-test**. We beschikken inderdaad over gepaarde observaties voor elke patiënt.\n\n- De test is eenzijdig gedaan omdat we testen tegen het alternatief van een bloeddrukdaling.\n\n- Beide tests (één voorbeeld van een t-test op het verschil en een gepaarde t-test) geven dezelfde resultaten:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(captopril$deltaSBP,alternative=\"less\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  captopril$deltaSBP\nt = -8.1228, df = 14, p-value = 5.732e-07\nalternative hypothesis: true mean is less than 0\n95 percent confidence interval:\n      -Inf -14.82793\nsample estimates:\nmean of x \n-18.93333 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(captopril$SBPa,captopril$SBPb,paired=TRUE,alternative=\"less\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPaired t-test\n\ndata:  captopril$SBPa and captopril$SBPb\nt = -8.1228, df = 14, p-value = 5.732e-07\nalternative hypothesis: true mean difference is less than 0\n95 percent confidence interval:\n      -Inf -14.82793\nsample estimates:\nmean difference \n      -18.93333 \n```\n\n\n:::\n:::\n\n\n***\n\n### Conclusie\n\nEr is gemiddeld een extreem significante bloeddrukdaling bij toediening van captopril aan patiënten met hypertensie. De systolische bloeddruk daalt gemiddeld met 18,9 mmHg bij de behandeling met captopril  (95% CI [$-\\infty,-14.82$] mmHg).\n\nLet op dat\n\n1. Er wordt een eenzijdig interval gerapporteerd omdat we alleen geïnteresseerd zijn in een bloeddrukdaling.\n\n2. Vanwege de pretest / posttest opzet kunnen we geen onderscheid maken tussen het effect van de behandeling en een placebo-effect. Er was geen goede controle! Het ontbreken van een goede controle komt meestal voor bij pre-test / post-test designs. Hoe hadden we het design kunnen verbeteren?\n\n***\n\n## eenzijdig or tweezijdige testen?\n\nDe test in het captopril-voorbeeld was een eenzijdige test. We proberen alleen te detecteren of de captoprilbehandeling gemiddeld de bloeddruk verlaagt.\n\n\nStel dat we het bloeddrukverschil hebben gedefinieerd als  $X_{i}^\\prime=Y_{i}^\\text{before}-Y_{i}^\\text{after}$\n\n- Nu duidt een positieve waarde op een bloeddrukdaling\n\n- De gemiddelde verandering in bloeddruk wordt nu aangeduid als $\\mu^\\prime=\\text{E}[X^\\prime]$.\n\n- Dus nu moeten we een eenzijdige test gebruiken om $H_0: \\mu^\\prime=0$ te beoordelen tegen $H_1: \\mu^\\prime>0$.\n\n- p-waarde wordt nu:\n$$p=\\text{P}_0\\left[T\\geq t\\right].$$\n\n***\n\nAnalyse gebaseerd op $X^\\prime$: Argument `alternative=\"greater\"` Zo dat we $H_1: \\mu^\\prime>0$ gebruiken:\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(captopril$SBPb-captopril$SBPa, alternative=\"greater\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  captopril$SBPb - captopril$SBPa\nt = 8.1228, df = 14, p-value = 5.732e-07\nalternative hypothesis: true mean is greater than 0\n95 percent confidence interval:\n 14.82793      Inf\nsample estimates:\nmean of x \n 18.93333 \n```\n\n\n:::\n:::\n\n\n\nNatuurlijk behalen we dezelfde resultaten. Alleen het teken is verwisseld.\n\n\n### Tweezijdige test\n\n\nStel dat onderzoekers het werkingsmechanisme van het nieuwe medicijn captopril in de ontwerpfase wilden beoordelen en veronderstel dat gezonde proefpersonen in een vroege fase van de medicijnontwikkeling werden gebruikt.\n\nIn dit geval zou het interessant zijn geweest om zowel bloeddrukdalingen als stijgingen waar te nemen.\n\nDan hebben we een tweezijdige teststrategie nodig\n\n$$H_0: \\mu=0$$\ntegen de alternatieve hypothese\n\n$$H_1: \\mu\\neq0,$$\n\nzodat het gemiddelde onder het alternatief verschilt van nul.\n\nHet kunnen zowel positieve als negatieve veranderingen zijn en we wisten van tevoren niet in welke richting het werkelijke gemiddelde zal afwijken van $H_1$.\n\n\nWe kunnen een tweezijdige test uitvoeren op het $\\alpha=5\\%$ significantieniveau door\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-html/unnamed-chunk-52-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n***\n\nHet argument `alternative` van  de `t.test` functie is heeft default waarde `alternative=\"two.sided\"`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(captopril$deltaSBP)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  captopril$deltaSBP\nt = -8.1228, df = 14, p-value = 1.146e-06\nalternative hypothesis: true mean is not equal to 0\n95 percent confidence interval:\n -23.93258 -13.93409\nsample estimates:\nmean of x \n-18.93333 \n```\n\n\n:::\n:::\n\n\n- We behalen nog steeds een buitengewoon significant resultaat.\n- De p-waarde is dubbel zo groot omdat we tweezijdig testen.\n\nInderdaad\n\n$$p=P_0[T \\leq -\\vert t \\vert] + P_0[T \\geq \\vert t \\vert] = P_0[\\vert T \\vert \\geq \\vert t \\vert] = 2 \\times P_0[T \\geq \\vert t \\vert]$$\n\n\n- We verkrijgen ook een tweezijdig betrouwbaarheidsinterval\n\n***\n\n### Eénzijdige of tweezijdige test?\n\nMet een eenzijdige test kunnen we $H_0$ gemakkelijker afwijzen op voorwaarde dat $H_1$ waar is dan met een tweezijdige test.\n\n\n- Alle informatie wordt gebruikt om in één richting te testen\n\n- De beslissing om eenzijdig te testen moet in de ontwerpfase worden genomen voordat het experiment wordt uitgevoerd\n\n- Zelfs als we sterke a priori aannames hebben, zijn we er niet helemaal zeker van, anders zouden we geen reden hebben om het onderzoek te doen.\n\n- Als we in de ontwerpfase een eenzijdige test voorstellen en we zien een resultaat in tegengestelde richting dat statistisch significant zou zijn, kunnen we geen conclusies trekken uit het experiment.\n\n- In de ontwerpfase hebben we dit resultaat uitgesloten omdat het zo onverwacht is dat het een vals positief moet zijn.\n\n- Daarom worden eenzijdige tests niet aanbevolen.\n\nEen tweezijdige test kan altijd worden verdedigd en stelt u in staat elke afwijking van $H_0$ te detecteren en wordt ten zeerste aanbevolen.\n\n\nHet is **nooit toegestaan** om een tweezijdige test te veranderen in een eenzijdige test op basis van wat er in de steekproef is waargenomen! Anders wordt de type I-fout van de teststrategie niet correct gecontroleerd.\n\n***\n\nWe illustreren dit in onderstaande simulatiestudie:\n\n1. correcte tweezijdige test en\n2. eenzijdige test met zijn teken gebaseerd op wat werd waargenomen in de steekproef.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(115)\nmu <- 0\nsigma <- 9.0\nnSim <- 1000\nalpha <- 0.05\nn <- 15\n\npvalsCor <-\n  pvalsInCor <-\n  array(0,nSim)\n\nfor (i in 1:nSim)\n{\n\tx <- rnorm(n, mean = mu, sd = sigma)\n\tpvalsCor[i] <- t.test(x)$p.value\n\tif (mean(x) < 0)\n\t\tpvalsInCor[i] <- t.test(x, alternative = \"less\")$p.value else\n\t\tpvalsInCor[i] <- t.test(x, alternative = \"greater\")$p.value\n}\n\nmean(pvalsCor < 0.05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.049\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(pvalsInCor < 0.05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.106\n```\n\n\n:::\n:::\n\n\n- Type I-fout correct gecontroleerd op  $\\alpha$ voor tweezijdige test.\n- Type I-fout niet correct gecontroleerd wanneer we eenzijdig testen op basis van wat we in de steekproef hebben waargenomen.\n\n# Nature column over testen\n\n![](https://www.nature.com/articles/nmeth.2698.pdf){width=100%}\n\n# Geclusterde metingen\n\n- Data niet altijd onafhankelijk.\n- Consequenties voor schatten van standaard errors\n\n## Voorbeeld\n\n- Studiedesign met $n$ planten\n- Expressie van bepaald gen wordt 2 maal gemeten\n- Men is geïnteresseerd in gemiddelde genexpressie.\n- $Y_{i1}$ en $Y_{i2}$ de eerste en tweede meting\nvoor plant $i=1,...,n$:\n\\begin{equation*}\n\\bar Y = \\sum_{i=1}^n \\frac{Y_{i1}+Y_{i2}}{2n}\n\\end{equation*}\n\n- Stel planten onafhankelijk\n- Eerste en tweede metingen even variabel ()$\\text{Var}(Y_{i1})=\\text{Var}(Y_{i2})=\\sigma^2$)\n- Variantie op steekproefgemiddelde:\n\\begin{eqnarray*}\n\\text{Var}(\\bar Y)&=&\\sum_{i=1}^n \\frac{\\text{Var}(Y_{i1}+Y_{i2})}{4n^2} \\\\\n&=&\\sum_{i=1}^n \\frac{\\sigma^2+\\sigma^2+2\\text{Cor}(Y_{i1},Y_{i2})\\sigma^2}{%\n4n^2} \\\\\n&=&\\frac{\\sigma^2}{2n}\\{1+\\text{Cor}(Y_{1},Y_{2})\\}\n\\end{eqnarray*}\n\n- Metingen afkomstig van zelfde plant doorgaans\npositief met elkaar gecorreleerd zijn\n- $SE_{\\bar Y}$ dus\ngroter dan bij $2n$ metingen van $2n$ verschillende\nplanten\n- Gegeven eerste meting $Y_{i1}$ brengt de tweede meting $Y_{i2}$ geen volledig nieuwe informatie bij\n- Er is bijgevolg minder informatie beschikbaar om het gemiddelde te\nschatten dan wanneer alle gegevens van verschillende planten afkomstig\nwaren.\n\nWat bij twee extremen:\n\n- Stel dat $\\text{Cor}(Y_{1},Y_{2})=1$ tweede meting geen nieuwe informatie en zelfde nauwkeurigheid als wanneer we alleen de n eerste metingen beschouwen\n- Wanneer $\\text{Cor}(Y_{1},Y_{2})=0$, tweede meting volledig nieuwe informatie en dus eenzelfde nauwkeurigheid als bij 1 meting voor $2n$ i.p.v. $n$ verschillende planten. Vermits\n\\[\\frac{\\sigma^2}{2n}\\{1+\\text{Cor}(Y_{1},Y_{2})\\}\\geq \\frac{\\sigma^2}{2n}\\]\n\n*Wanneer de correlatie tussen herhaalde genexpressie metingen positief is (hetgeen we verwachten), zal men in de praktijk meer preciese resultaten bekomen door 1 meting te bepalen voor $2n$ verschillende planten dan door 2 metingen te bepalen voor $n$ verschillende planten.*\n\n- Als er evenveel herhaalde metingen zijn voor elk subject/experimentele unit (vb plant) dan kan men metingen ook reduceren naar $n$ onafhankelijke metingen door het gemiddelde te berekenen per experimentele unit.\n- Omdat de gemiddeldes per experimentele unit zijn gebaseerd op evenveel herhaalde metingen zal de precisie van die gemiddeldes hetzelfde zijn.\n- Bij verschillend aantal herhaalde metingen per experimentele unit kan men NIET met gemiddeldes per Exp. unit werken want die hebben anders een verschillende precisie\n$longrightarrow$ dan zijn meer geavanceerde methoden nodig!\n\n## Captopril\n\n- Metingen geclusterd: twee systolische bloeddrukmetingen per patiënt\n\n    - 1 meting voor en\n    - 1 meting na het toedienen van captopril.\n\n- Gemiddelde bloeddrukverandering $\\mu$  schatten a.d.h.v. gegevens\n$$(Y_{i1} , Y_{i2}),$$\nvoor subjecten $i = 1, ..., n$.\n\n$$\\bar X = \\sum_{i=1}^n \\frac{Y_{i2}-Y_{i1}}{n}$$\n\nUit rekenregels voor variantie:\n\\begin{eqnarray*}\n\\text{Var}\\left[\\bar X\\right]&=&\\sum_{i=1}^n \\frac{\\text{Var}\\left[Y_{i1}-Y_{i2}\\right]}{n^2}\\\\\n&=&\\sum_{i=1}^n \\frac{\\sigma^2_1+\\sigma^2_2-2\\text{Cor}\\left[Y_{i1},Y_{i2}\\right]\\sigma_1\\sigma_2}{n^2}\\\\\n&=&\\frac{\\sigma^2_1+\\sigma^2_2-2\\text{Cor}\\left[Y_{i1},Y_{i2}\\right]\\sigma_1\\sigma_2}{n},\\\\\n\\end{eqnarray*}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#functie var op een matrix berekent varianties sigma_1^2, sigma_2^2\n#covariantie sigma_{12}\nvars <- var(captopril[,c(\"SBPb\",\"SBPa\")])\nvars\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         SBPb     SBPa\nSBPb 422.9238 370.7857\nSBPa 370.7857 400.1429\n```\n\n\n:::\n\n```{.r .cell-code}\ncor(captopril$SBPa,captopril$SBPb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9013312\n```\n\n\n:::\n\n```{.r .cell-code}\nvarXbarDelta <- (vars[1,1]+vars[2,2]-2*vars[1,2])/15\nsqrt(varXbarDelta)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.330883\n```\n\n\n:::\n:::\n\n\n- Metingen heel sterk gecorreleerd.  Variantie op het verschil veel lager dan op de originele metingen!\n\n- alternatieve methode om de standard error te bepalen:\n\n  - gecorreleerde metingen tot 1 meting te reduceren\n  - kan enkel voor design met gepaarde metingen (2 metingen per patient)\n  - Alle verschillen zijn onafhankelijk.\n\n$$X_{i}=Y_{ai}-Y_{bi}$$\n   - vervolgens standard error op $\\bar X$.\n\nIn het captopril voorbeeld wordt de schatting\n\n::: {.cell}\n\n```{.r .cell-code}\nsd(captopril$deltaSBP)/sqrt(15)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.330883\n```\n\n\n:::\n:::\n\n\n- Exact dezelfde schatting voor standard error\n\n- Groot voordeel van design:\n\n    - bloeddrukmetingen voor en na sterk positief gecorreleerd $\\longrightarrow$ variantie van verschil veel lager dan dat op originele bloeddrukmetingen\n\n    - Iedere patiënt dient immers als zijn eigen controle\n    - We kunnen variabiliteit in bloeddrukmetingen tussen patiënten uit de analyse verwijderen!\n\n- Een gepaard experiment is speciale vorm van randomized complete block design:\n\n    - Elke persoon is een blok en\n    - Elke behandeling getest blok: een controle bloeddrukmeting en een bloeddrukmeting na toedienen van captopril\n    - Er is een grote variabiliteit tussen blokken! $\\longrightarrow$ Bloeddruk hoog voor meestal ook bloeddruk hoog na captopril behandeling.\n    - standaarddeviatie in bloeddruk tussen patienten voor toedienen van captopril bedraagt  20.6 mmHg.\n\n    - Effect van captopril schatten binnen patient.\n    - Door het blokdesign variabiliteit tussen patiënten uit de analyse weren.\n    - Voor een gepaard design kan dat door b.v. analyse op bloeddrukverschillen.\n    - Standaard error op bloeddruk verschillen tussen patiënten is inderdaad veel lager 9.03.\n    - Voor blok design met meer metingen per blok analyse met meervoudig regressie model (Hoofdstuk 10).\n\nHoe kunnen we het captopril experiment verder verbeteren?\n\n***\n",
    "supporting": [
      "05-statisticalInference_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"05-statisticalInference_files/libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"05-statisticalInference_files/libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}