<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="nl" xml:lang="nl"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Basiscursus Statistiek voor de 2de Bachelor of Science in de Biologie, - in de Biochemie &amp; de Biotechnologie, - in de Biomedische Wetenschappen, en - in de Chemie">

<title>7&nbsp; Enkelvoudige lineaire regressie – Cursus Statistiek 2026-2027</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./07-VariantieAnalyse.html" rel="next">
<link href="./05-StatistischeBesluitvorming.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-5ccb035bea26c1e21f80f44cf7c27909.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Geen resultaten",
    "search-matching-documents-text": "Gevonden documenten",
    "search-copy-link-title": "Kopieer link om te zoeken",
    "search-hide-matches-text": "Extra overeenkomsten verbergen",
    "search-more-match-text": "meer overeenkomst in dit document",
    "search-more-matches-text": "meer overeenkomsten in dit document",
    "search-clear-button-title": "Wissen",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Annuleren",
    "search-submit-button-title": "Verzenden",
    "search-label": "Zoeken"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Schakel zijbalknavigatie" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./06-LineareRegressie.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Enkelvoudige lineaire regressie</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Schakel zijbalknavigatie" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Zoeken" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Cursus Statistiek 2026-2027</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/statOmics/statistiek2deBach" title="Broncode" class="quarto-navigation-tool px-1" aria-label="Broncode"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Download" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Download"><i class="bi bi-download"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="./Statistiek_2026_2027.pdf">
              <i class="bi bi-file-pdf pe-1"></i>
            Download PDF
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="./Statistiek_2026_2027.epub">
              <i class="bi bi-journal pe-1"></i>
            Download ePub
            </a>
          </li>
      </ul>
    </div>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Zoeken"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Cursus Statistiek 2026-2027</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-Inleiding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Inleiding</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-Concepten.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Belangrijke concepten &amp; conventies</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-Proefopzet.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Studiedesign</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-DataExploratie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Data exploratie en beschrijvende statistiek</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-StatistischeBesluitvorming.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Statistische besluitvorming</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-LineareRegressie.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Enkelvoudige lineaire regressie</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-VariantieAnalyse.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Variantie analyse</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-NietParametrischeStatistiek.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Niet-parametrische statistiek</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-CategorischeDataAnalyse.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Categorische data analyse</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-GeneralLinearModel.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Algemeen lineair model</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-ModelSelectie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Modelselectie</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">References</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Inhoudsopgave</h2>
   
  <ul>
  <li><a href="#inleiding" id="toc-inleiding" class="nav-link active" data-scroll-target="#inleiding"><span class="header-section-number">7.1</span> Inleiding</a>
  <ul class="collapse">
  <li><a href="#borstkanker-dataset" id="toc-borstkanker-dataset" class="nav-link" data-scroll-target="#borstkanker-dataset"><span class="header-section-number">7.1.1</span> Borstkanker dataset</a></li>
  <li><a href="#data-exploratie" id="toc-data-exploratie" class="nav-link" data-scroll-target="#data-exploratie"><span class="header-section-number">7.1.2</span> Data exploratie</a></li>
  <li><a href="#model" id="toc-model" class="nav-link" data-scroll-target="#model"><span class="header-section-number">7.1.3</span> Model</a></li>
  </ul></li>
  <li><a href="#lineaire-regressie" id="toc-lineaire-regressie" class="nav-link" data-scroll-target="#lineaire-regressie"><span class="header-section-number">7.2</span> Lineaire regressie</a></li>
  <li><a href="#parameterschatting" id="toc-parameterschatting" class="nav-link" data-scroll-target="#parameterschatting"><span class="header-section-number">7.3</span> Parameterschatting</a></li>
  <li><a href="#sec-linBesluit" id="toc-sec-linBesluit" class="nav-link" data-scroll-target="#sec-linBesluit"><span class="header-section-number">7.4</span> Statistische besluitvorming</a></li>
  <li><a href="#nagaan-van-modelveronderstellingen" id="toc-nagaan-van-modelveronderstellingen" class="nav-link" data-scroll-target="#nagaan-van-modelveronderstellingen"><span class="header-section-number">7.5</span> Nagaan van modelveronderstellingen</a>
  <ul class="collapse">
  <li><a href="#lineariteit" id="toc-lineariteit" class="nav-link" data-scroll-target="#lineariteit"><span class="header-section-number">7.5.1</span> Lineariteit</a></li>
  <li><a href="#veronderstelling-van-homoscedasticiteit-gelijkheid-van-variantie" id="toc-veronderstelling-van-homoscedasticiteit-gelijkheid-van-variantie" class="nav-link" data-scroll-target="#veronderstelling-van-homoscedasticiteit-gelijkheid-van-variantie"><span class="header-section-number">7.5.2</span> Veronderstelling van homoscedasticiteit (gelijkheid van variantie)</a></li>
  <li><a href="#veronderstelling-van-normaliteit" id="toc-veronderstelling-van-normaliteit" class="nav-link" data-scroll-target="#veronderstelling-van-normaliteit"><span class="header-section-number">7.5.3</span> Veronderstelling van normaliteit</a></li>
  </ul></li>
  <li><a href="#afwijkingen-van-modelveronderstellingen" id="toc-afwijkingen-van-modelveronderstellingen" class="nav-link" data-scroll-target="#afwijkingen-van-modelveronderstellingen"><span class="header-section-number">7.6</span> Afwijkingen van Modelveronderstellingen</a></li>
  <li><a href="#besluitvorming-over-gemiddelde-uitkomst" id="toc-besluitvorming-over-gemiddelde-uitkomst" class="nav-link" data-scroll-target="#besluitvorming-over-gemiddelde-uitkomst"><span class="header-section-number">7.7</span> Besluitvorming over gemiddelde uitkomst</a></li>
  <li><a href="#predictie-intervallen" id="toc-predictie-intervallen" class="nav-link" data-scroll-target="#predictie-intervallen"><span class="header-section-number">7.8</span> Predictie-intervallen</a>
  <ul class="collapse">
  <li><a href="#nhanes-voorbeeld" id="toc-nhanes-voorbeeld" class="nav-link" data-scroll-target="#nhanes-voorbeeld"><span class="header-section-number">7.8.1</span> NHANES voorbeeld</a></li>
  </ul></li>
  <li><a href="#sec-linAnova" id="toc-sec-linAnova" class="nav-link" data-scroll-target="#sec-linAnova"><span class="header-section-number">7.9</span> Kwadratensommen en Anova-tabel</a>
  <ul class="collapse">
  <li><a href="#determinatie-coëfficiënt" id="toc-determinatie-coëfficiënt" class="nav-link" data-scroll-target="#determinatie-coëfficiënt"><span class="header-section-number">7.9.1</span> Determinatie-coëfficiënt</a></li>
  <li><a href="#f-testen-in-het-enkelvoudig-lineair-regressiemodel" id="toc-f-testen-in-het-enkelvoudig-lineair-regressiemodel" class="nav-link" data-scroll-target="#f-testen-in-het-enkelvoudig-lineair-regressiemodel"><span class="header-section-number">7.9.2</span> F-Testen in het enkelvoudig lineair regressiemodel</a></li>
  <li><a href="#anova-tabel" id="toc-anova-tabel" class="nav-link" data-scroll-target="#anova-tabel"><span class="header-section-number">7.9.3</span> Anova Tabel</a></li>
  </ul></li>
  <li><a href="#sec-linDummy" id="toc-sec-linDummy" class="nav-link" data-scroll-target="#sec-linDummy"><span class="header-section-number">7.10</span> Dummy variabelen</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/statOmics/statistiek2deBach/edit/main/06-LineareRegressie.qmd" class="toc-action"><i class="bi bi-github"></i>Pagina bewerken</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-chap-linReg" class="quarto-section-identifier"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Enkelvoudige lineaire regressie</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Alle kennisclips die in dit hoofdstuk zijn verwerkt kan je in deze youtube playlist vinden:</p>
<ul>
<li><a href="https://www.youtube.com/playlist?list=PLZH1hP8_LbJJyNBiMlv24sSI0oKB8EtI0">Kennisclips Hoofdstuk6 Lineaire Regressie</a></li>
</ul>
<p>Link naar webpage/script die wordt gebruik in de kennisclips:</p>
<ul>
<li><a href="https://statomics.github.io/sbc/rmd/06-linearRegression.html">script Hoofdstuk6</a></li>
</ul>
<section id="inleiding" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="inleiding"><span class="header-section-number">7.1</span> Inleiding</h2>
<iframe width="560" height="315" src="https://www.youtube.com/embed/w6xczw8JNpI" frameborder="0" style="display: block; margin: auto;" allow="autoplay; encrypted-media" allowfullscreen="">
</iframe>
<!---break-->
<section id="borstkanker-dataset" class="level3" data-number="7.1.1">
<h3 data-number="7.1.1" class="anchored" data-anchor-id="borstkanker-dataset"><span class="header-section-number">7.1.1</span> Borstkanker dataset</h3>
<iframe width="560" height="315" src="https://www.youtube.com/embed/aH0kNKVaLTA" frameborder="0" style="display: block; margin: auto;" allow="autoplay; encrypted-media" allowfullscreen="">
</iframe>
<p><span class="citation" data-cites="sotiriou2006">Sotiriou e.a. (<a href="#ref-sotiriou2006" role="doc-biblioref">2006</a>)</span> publiceerden onderzoek naar de moleculaire basis van borstkanker. In de studie hebben de onderzoekers voor een groot aantal borstkanker patiënten klinische variabelen geregistreerd alsook de genexpressie in tumor weefsel gemeten voor duizenden genen m.b.v. microarray technologie. De genexpressie werd gemeten op de tumor biopsie die werd genomen voordat de behandeling werd gestart. De studie is een retrospectieve studie in de zin dat niet werd geëxperimenteerd en dat de genexpressie werd geëvalueerd als gevolg van de blootstelling die de individuen hebben ondergaan in het verleden.</p>
<p>In dit hoofdstuk zullen we een subset van de data gebruiken om de associatie te bestuderen tussen de genexpressie van twee sleutelgenen bij borstkanker: de estrogeen receptor 1 (ESR1) gen, een belangrijke biomerker voor de prognose van de patiënt, en het S100A8 gen dat een prominente rol speelt in de regulatie van inflammatie en immuun respons.</p>
<p>De data is opgeslagen in een tekst bestand met naam <code>brca.csv</code> op de github repository van de cursus.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>brca <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://raw.githubusercontent.com/statOmics/sbc/master/data/breastcancer.csv"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">head</span>(brca),<span class="at">caption=</span><span class="st">"Overzicht van de variabelen in de borstkanker dataset."</span>,<span class="at">booktabs =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div id="tbl-brcaMicroLin" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-brcaMicroLin-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabel&nbsp;7.1: Overzicht van de variabelen in de borstkanker dataset.
</figcaption>
<div aria-describedby="tbl-brcaMicroLin-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 14%">
<col style="width: 19%">
<col style="width: 12%">
<col style="width: 3%">
<col style="width: 7%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 4%">
<col style="width: 12%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">sample_name</th>
<th style="text-align: left;">filename</th>
<th style="text-align: left;">treatment</th>
<th style="text-align: right;">er</th>
<th style="text-align: right;">grade</th>
<th style="text-align: right;">node</th>
<th style="text-align: right;">size</th>
<th style="text-align: right;">age</th>
<th style="text-align: right;">ESR1</th>
<th style="text-align: right;">S100A8</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">OXFT_209</td>
<td style="text-align: left;">gsm65344.cel.gz</td>
<td style="text-align: left;">tamoxifen</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.5</td>
<td style="text-align: right;">66</td>
<td style="text-align: right;">1939.1990</td>
<td style="text-align: right;">207.19682</td>
</tr>
<tr class="even">
<td style="text-align: left;">OXFT_1769</td>
<td style="text-align: left;">gsm65345.cel.gz</td>
<td style="text-align: left;">tamoxifen</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3.5</td>
<td style="text-align: right;">86</td>
<td style="text-align: right;">2751.9521</td>
<td style="text-align: right;">36.98611</td>
</tr>
<tr class="odd">
<td style="text-align: left;">OXFT_2093</td>
<td style="text-align: left;">gsm65347.cel.gz</td>
<td style="text-align: left;">tamoxifen</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.2</td>
<td style="text-align: right;">74</td>
<td style="text-align: right;">379.1951</td>
<td style="text-align: right;">2364.18306</td>
</tr>
<tr class="even">
<td style="text-align: left;">OXFT_1770</td>
<td style="text-align: left;">gsm65348.cel.gz</td>
<td style="text-align: left;">tamoxifen</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.7</td>
<td style="text-align: right;">69</td>
<td style="text-align: right;">2531.7473</td>
<td style="text-align: right;">23.61504</td>
</tr>
<tr class="odd">
<td style="text-align: left;">OXFT_1342</td>
<td style="text-align: left;">gsm65350.cel.gz</td>
<td style="text-align: left;">tamoxifen</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2.5</td>
<td style="text-align: right;">62</td>
<td style="text-align: right;">141.0508</td>
<td style="text-align: right;">3218.74109</td>
</tr>
<tr class="even">
<td style="text-align: left;">OXFT_2338</td>
<td style="text-align: left;">gsm65352.cel.gz</td>
<td style="text-align: left;">tamoxifen</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.4</td>
<td style="text-align: right;">63</td>
<td style="text-align: right;">1495.4213</td>
<td style="text-align: right;">107.56868</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="data-exploratie" class="level3" data-number="7.1.2">
<h3 data-number="7.1.2" class="anchored" data-anchor-id="data-exploratie"><span class="header-section-number">7.1.2</span> Data exploratie</h3>
<p>In Sectie <a href="04-DataExploratie.html#sec-correlatie" class="quarto-xref"><span>5.7</span></a> werd de associatie tussen beide genen uitgebreid verkend. Daarin hebben we de genexpressie data eerst log-getransformeerd.</p>
<p>In dit hoofdstuk zullen we om didactische redenen eerst werken met de expressiemetingen op de originele schaal. De expressie van het S100A8 gen wordt weergegeven in Figuur <a href="#fig-s100a8Boxplot" class="quarto-xref"><span>7.1</span></a>. Op de originele schaal zien we drie heel grote outliers. Omwille van didactische redenen worden deze eerst verwijderd uit de dataset. In principe mogen outliers enkel worden verwijderd uit een studie als daar een goede reden voor is. We kunnen op basis van de informatie over de studie echter niet argumenteren waarom de outliers niet representatief zijn, zoals bijvoorbeeld wel het geval zou zijn wanneer zich meetfouten of problemen voordeden m.b.t. deze observaties in de studie. Later in het hoofdstuk zullen we zien hoe we op een correcte wijze alle data kunnen modelleren.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>brca <span class="sc">|&gt;</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span><span class="st">""</span>, <span class="at">y=</span>S100A8)) <span class="sc">+</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"S100A8 expressie"</span>)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-s100a8Boxplot" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-s100a8Boxplot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-LineareRegressie_files/figure-html/fig-s100a8Boxplot-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-s100a8Boxplot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figuur&nbsp;7.1: Expressie van het S100A8 gen.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Om meerdere variabelen in de borstkanker dataset te bestuderen, kunnen we gebruik maken van de grafische scatterplot matrix voorstelling (zie Figuur <a href="#fig-brcaGenAl" class="quarto-xref"><span>7.2</span></a>). Hierbij wordt een matrix met paarsgewijze dotplots voor alle variabelen geproduceerd.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GGally)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>brcaSubset <span class="ot">&lt;-</span> brca <span class="sc">|&gt;</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(S100A8<span class="sc">&lt;</span><span class="dv">2000</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co">#progress = FALSE zo dat ggpairs niet de vooruitgang print van het plotten</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>brcaSubset[,<span class="sc">-</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>)] <span class="sc">|&gt;</span> <span class="fu">ggpairs</span>(<span class="at">progress =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-brcaGenAl" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-brcaGenAl-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-LineareRegressie_files/figure-html/fig-brcaGenAl-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-brcaGenAl-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figuur&nbsp;7.2: Scatterplot matrix voor de observaties in de borstkanker dataset na verwijdering van outliers in de S100A8 expressie (merk op dat we deze outliers in principe niet mochten verwijderen uit de dataset).
</figcaption>
</figure>
</div>
</div>
</div>
<p>In de scatterplot matrix zien we bijvoorbeeld dat er een positieve associatie lijkt te zijn tussen de leeftijd (age) en de lymfeknoop status (node; geeft aan of de lymfeknopen al dan niet aangetast zijn en chirurgisch werden verwijderd, node 0: niet aangetast, 1: aangetast). Daarnaast observeren we ook een indicatie voor een negatieve associatie (dalende trend) tussen de ESR1 en S100A8 gen expressie.</p>
<p>In dit hoofdstuk zullen we ons in het bijzonder focussen op de relatie tussen de ESR1 en de S100A8 gen expressie. Een individuele scatterplot met smoother (zie Figuur <a href="#fig-brcaSmooth" class="quarto-xref"><span>7.3</span></a>) geeft de associatie tussen beide genen nog beter weer. Smoothers kunnen trends visualiseren tussen variabelen zonder vooraf veronderstellingen te doen over de vorm van het verband en zijn daarom heel erg nuttig bij data exploratie. We zien dat de genexpressie van S100A8 gemiddeld gezien daalt voor patiënten met een hogere expressie van ESR1.</p>
<ol type="1">
<li>pipe dataset naar ggplot</li>
<li>selecteer data <code>ggplot(aes(x=ESR1,y=S100A8))</code></li>
<li>voeg punten toe met <code>geom_point()</code></li>
<li>voeg een “smooth line” toe <code>geom_smooth()</code></li>
</ol>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>brcaSubset <span class="sc">|&gt;</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>ESR1, <span class="at">y=</span>S100A8)) <span class="sc">+</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>()</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-brcaSmooth" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-brcaSmooth-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-LineareRegressie_files/figure-html/fig-brcaSmooth-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-brcaSmooth-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figuur&nbsp;7.3: Scatterplot voor S100A8 expressie in functie van de ESR1 expressie met smoother die het verband tussen beide genen samenvat (na verwijdering van outliers in de S100A8 expressie, merk op dat we deze outliers in principe niet mochten verwijderen uit de dataset).
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="model" class="level3" data-number="7.1.3">
<h3 data-number="7.1.3" class="anchored" data-anchor-id="model"><span class="header-section-number">7.1.3</span> Model</h3>
<p>Op basis van Figuur <a href="#fig-brcaSmooth" class="quarto-xref"><span>7.3</span></a> zien we dat er een relatie is tussen de S100A8 (Y) en ESR1 (X) expressie. De expressiemetingen voor het S100A8 gen zijn echter onderhevig aan ruis onder andere door biologische variabiliteit en technische variabiliteit. Voor een gegeven waarde <span class="math inline">\(X=x\)</span> neemt de genexpressie <span class="math inline">\(Y\)</span> dus niet steeds dezelfde waarde aan. Generiek kunnen we de S100A8 gen expressie dus beschrijven als</p>
<p><span class="math display">\[\text{observatie = signaal + ruis.}\]</span></p>
<p>Wiskundig kunnen we dat modelleren als</p>
<p><span class="math display">\[Y_i=g(X_i)+\epsilon_i\]</span></p>
<p>waarbij we de toevallige veranderlijke S100A8 genexpressie voor subject <span class="math inline">\(i\)</span> (<span class="math inline">\(Y_i\)</span>) modelleren in functie van de genexpressie van het ESR1 gen (<span class="math inline">\(X_i\)</span>). Uiteraard is dit verband niet perfect. Dat wordt aangegeven door de foutterm <span class="math inline">\(\epsilon_i\)</span> die uitdrukt dat observaties <span class="math inline">\(Y_i\)</span> variëren rond dit verband, m.a.w. het verband modelleert een conditioneel gemiddelde:</p>
<p><span class="math display">\[E[Y_i|X_i=x]=g(x),\]</span></p>
<p>het is de verwachte uitkomst<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> (<span class="math inline">\(E[Y]\)</span>) bij subjecten met een expressieniveau <span class="math inline">\(X_i=x\)</span> voor het ESR1 gen.</p>
<p>Zo geeft <span class="math inline">\(E(Y|X=2400)\)</span> de gemiddelde genexpressie aan van het S100A8 gen voor subjecten die een expressie hebben van 2400 voor het ESR1 gen. Men zou dit gemiddelde bekomen door van alle patiënten in de studiepopulatie, die een ESR1 expressie hebben van 2400, de S100A8 expressie te meten en hier vervolgens het gemiddelde van te nemen. Het gemiddelde <span class="math inline">\(E(Y|X=x)\)</span> wordt een <em>conditioneel gemiddelde</em> genoemd omdat het een gemiddelde uitkomst beschrijft, conditioneel op het feit dat <span class="math inline">\(X=x\)</span>.</p>
<p>Gezien</p>
<p><span class="math display">\[E[Y_i|X_i=x]=g(x)\]</span></p>
<p>het gemiddelde beschrijft voor subjecten met een ESR1 expressieniveau van <span class="math inline">\(x\)</span> is de foutterm <span class="math inline">\(\epsilon_i\)</span> gemiddeld 0 voor deze subjecten:</p>
<p><span class="math display">\[E[\epsilon_i\vert X_i=x]=0.\]</span></p>
</section>
</section>
<section id="lineaire-regressie" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="lineaire-regressie"><span class="header-section-number">7.2</span> Lineaire regressie</h2>
<iframe width="560" height="315" src="https://www.youtube.com/embed/d0QptODQABY" frameborder="0" style="display: block; margin: auto;" allow="autoplay; encrypted-media" allowfullscreen="">
</iframe>
<p>Om accurate en interpreteerbare resultaten te bekomen gaat men vaak bepaalde veronderstellingen doen over de structuur van <span class="math inline">\(g(x)\)</span>. Zo modelleert men <span class="math inline">\(g(x)\)</span> vaak als een lineaire functie van ongekende parameters. Dat wordt geïllustreerd in Figuur <a href="#fig-brcaLin1" class="quarto-xref"><span>7.4</span></a>.</p>
<ol type="1">
<li>pipe dataset naar ggplot</li>
<li>selecteer data <code>ggplot(aes(x=ESR1,y=S100A8))</code></li>
<li>voeg punten toe met <code>geom_point()</code></li>
<li>voeg een “smooth line” toe <code>geom_smooth()</code></li>
<li>voeg een rechte toe <code>geom_smooth()</code> met <code>method = "lm"</code> (linear model). (We zetten <code>se = FALSE</code> om geen puntgewijze betrouwbaarheidsintervallen weer te geven)</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>brcaSubset <span class="sc">|&gt;</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> ESR1, <span class="at">y =</span> S100A8)) <span class="sc">+</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">col =</span> <span class="st">"grey"</span>) <span class="sc">+</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-brcaLin1" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-brcaLin1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-LineareRegressie_files/figure-html/fig-brcaLin1-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-brcaLin1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figuur&nbsp;7.4: Scatterplot voor S100A8 expressie in functie van de ESR1 expressie met lineair model dat het verband tussen beide genen samenvat (na verwijdering van outliers in de S100A8 expressie, merk op dat we deze outliers in principe niet mochten verwijderen uit de dataset zoals we verder in dit hoofdstuk zullen zien).
</figcaption>
</figure>
</div>
</div>
</div>
<p>Men veronderstelt dan het onderstaande lineaire regressiemodel</p>
<p><span id="eq-linreg"><span class="math display">\[
E(Y|X =x)=\beta_0 + \beta_1 x
\tag{7.1}\]</span></span></p>
<p>waarbij <span class="math inline">\(\beta_0\)</span> en <span class="math inline">\(\beta_1\)</span> ongekende modelparameters zijn. In deze uitdrukking stelt <span class="math inline">\(E(Y|X=x)\)</span> de waarde op de <span class="math inline">\(Y\)</span>-as voor, <span class="math inline">\(x\)</span> de waarde op de <span class="math inline">\(X\)</span>-as, het <em>intercept</em> <span class="math inline">\(\beta_0\)</span> stelt het snijpunt met de <span class="math inline">\(Y\)</span>-as voor en de <em>helling</em> <span class="math inline">\(\beta_1\)</span> geeft de richtingscoëfficiënt van de rechte weer. Uitdrukking <a href="#eq-linreg" class="quarto-xref"><span>7.1</span></a> wordt een <em>statistisch model</em> genoemd. Merk op dat dit model enkel een onderstelling maakt over het gemiddelde van de S100A8 expressie.</p>
<p>Deze naamgeving suggereert dat het bepaalde onderstellingen legt op de verdeling van de geobserveerde gegevens. In het bijzonder onderstelt het dat de gemiddelde uitkomst lineair varieert in functie van één verklarende variabele <span class="math inline">\(X\)</span>. Om die reden wordt Model <a href="#eq-linreg" class="quarto-xref"><span>7.1</span></a> ook een <em>enkelvoudig lineair regressiemodel</em> genoemd. Onder dit model kan elke meting <span class="math inline">\(Y\)</span> op een foutterm <span class="math inline">\(\epsilon\)</span> na beschreven worden als een lineaire functie van de verklarende variabele <span class="math inline">\(X\)</span>, verder in deze cursus ook de predictor genoemd:</p>
<p><span class="math display">\[Y=E(Y|X=x)+\epsilon=\beta_0+\beta_1 x+\epsilon\]</span></p>
<p>waarbij <span class="math inline">\(\epsilon\)</span> de afwijking tussen de uitkomst en haar (conditioneel) gemiddelde waarde voorstelt, dit is de onzekerheid in de responsvariabele.</p>
<p>Gezien het lineair regressiemodel onderstellingen doet over de verdeling van X en Y , kunnen deze onderstellingen ook vals zijn. Later in dit hoofdstuk zullen we zien hoe deze onderstellingen geëvalueerd kunnen worden. Als echter voldaan is aan de onderstellingen, laat dit een efficiënte data-analyse toe: alle observaties worden benut om te leren over verwachte uitkomst bij X = x.</p>
<p>Het lineair regressiemodel kan worden gebruikt voor<br>
- <em>predictie</em> (voorspellingen): als <span class="math inline">\(Y\)</span> ongekend is, maar <span class="math inline">\(X\)</span> wel gekend is, kunnen we <span class="math inline">\(Y\)</span> voorspellen op basis van <span class="math inline">\(X\)</span></p>
<p><span class="math display">\[\text{E}\left[Y|X =x\right]=\beta_0 + \beta_1 x.\]</span></p>
<ul>
<li><em>associatie</em>: beschrijven van de biologische relatie tussen variabele <span class="math inline">\(X\)</span> en continue meting <span class="math inline">\(Y\)</span>:</li>
</ul>
<p><span class="math display">\[\text{E}\left[Y|X=x+\delta\right]-\text{E}\left[Y|X=x\right]= \left[\beta_0+\beta_1(x+\delta)\right]-(\beta_0+\beta_1x)=\beta_1\delta\]</span></p>
<p>waarbij <span class="math inline">\(\beta_1\)</span> het verschil is in gemiddelde uitkomst tussen subjecten die 1 eenheid verschillen in de genexpressie van het ESR1 gen.</p>
</section>
<section id="parameterschatting" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="parameterschatting"><span class="header-section-number">7.3</span> Parameterschatting</h2>
<iframe width="560" height="315" src="https://www.youtube.com/embed/_Z3wseKXxjk" frameborder="0" style="display: block; margin: auto;" allow="autoplay; encrypted-media" allowfullscreen="">
</iframe>
<p>De parameters <span class="math inline">\(\beta_0\)</span> en <span class="math inline">\(\beta_1\)</span> zijn ongekenden. Indien de volledige studiepopulatie geobserveerd werd, dan zouden beide parameters exact bepaald kunnen worden (door bijvoorbeeld in 2 x-waarden de gemiddelde uitkomst te berekenen en vervolgens het resulterende stelsel van 2 vergelijkingen, bepaald door Model <a href="#eq-linreg" class="quarto-xref"><span>7.1</span></a>, op te lossen).</p>
<p>In de praktijk observeert men slechts een beperkte steekproef uit de studiepopulatie en is de taak om die parameters te schatten op basis van de beschikbare observaties. Deze schatting gebeurt door naar de lijn te zoeken die “het best past” bij de gegevens. Daarbij wil men dat bij een gegeven waarde <span class="math inline">\(x_i\)</span> voor het <span class="math inline">\(i\)</span>-de subject het punt op de regressielijn, <span class="math inline">\((x_i, \beta_0 + \beta_1 x_i)\)</span>, zo weinig mogelijk afwijkt van de overeenkomstige observatie <span class="math inline">\((x_i, y_i)\)</span>. Dit realiseert men door deze waarden voor <span class="math inline">\(\beta_0\)</span> en <span class="math inline">\(\beta_1\)</span> te kiezen die de som van die kwadratische afstanden tussen de voorspelde en geobserveerde punten,</p>
<p><span class="math display">\[\sum_{i=1}^n (y_i-\beta_0-\beta_1 x_i)^2=\sum_{i=1}^n e_i^2\]</span></p>
<p>zo klein mogelijk maakt. Waarbij <span class="math inline">\(e_i\)</span> de verticale afstanden van de observaties tot de gefitte regressierechte, ook wel residuen genoemd (zie Figuur <a href="#fig-brcaLinRes" class="quarto-xref"><span>7.5</span></a>).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-brcaLinRes" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-brcaLinRes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-LineareRegressie_files/figure-html/fig-brcaLinRes-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-brcaLinRes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figuur&nbsp;7.5: Scatterplot voor S100A8 expressie in functie van de ESR1 expressie met lineair model (rode lijn) en residuen (zwarte gestreepte lijnen).
</figcaption>
</figure>
</div>
</div>
</div>
<p>De rechte die men aldus bekomt, noemt men de <em>kleinste kwadratenlijn</em> en is de best passende rechte door de puntenwolk.</p>
<p>De overeenkomstige waarden of schattingen <span class="math inline">\(\hat{\beta}_0\)</span> voor <span class="math inline">\(\beta_0\)</span> en <span class="math inline">\(\hat{\beta}_1\)</span> voor <span class="math inline">\(\beta_1\)</span>, noemt men <em>kleinste kwadratenschattingen</em>.</p>
<p>Men kan eenvoudig aantonen dat</p>
<p><span class="math display">\[\hat{\beta_1}= \frac{\sum\limits_{i=1}^n (y_i-\bar y)(x_i-\bar x)}{\sum\limits_{i=1}^n (x_i-\bar x)^2}=\frac{\mbox{cor}(x,y)s_y}{s_x} \]</span></p>
<p>en dat</p>
<p><span class="math display">\[\hat{\beta_0}=\bar y - \hat{\beta}_1 \bar x \]</span></p>
<p>Merk op dat de helling van de kleinste kwadratenlijn evenredig is met de correlatie tussen de uitkomst en de verklarende variabele.</p>
<p>Voor gegeven schattingen <span class="math inline">\(\hat{\beta}_0\)</span> voor <span class="math inline">\(\beta_0\)</span> en <span class="math inline">\(\hat{\beta}_1\)</span> voor <span class="math inline">\(\beta_1\)</span> laat het lineaire regressiemodel <a href="#eq-linreg" class="quarto-xref"><span>7.1</span></a> toe om:</p>
<ul>
<li>de verwachte uitkomst te voorspellen voor subjecten met een gegeven waarde <span class="math inline">\(x\)</span> voor de verklarende variabele. Deze kan geschat worden als <span class="math inline">\(\hat{\beta}_0+\hat{\beta}_1x\)</span>.</li>
<li>na te gaan hoeveel de uitkomst gemiddeld verschilt tussen 2 groepen subjecten met een verschil van <span class="math inline">\(\delta\)</span> eenheden in de verklarende variabele. Namelijk:</li>
</ul>
<p><span class="math display">\[\text{E}\left[Y|X=x+\delta\right]-\text{E}\left[Y|X=x\right]= \hat{\beta}_1\delta\]</span></p>
<p>Voor de borstkanker dataset levert een analyse van de gegevens in R de volgende resultaten op.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>lm1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(S100A8 <span class="sc">~</span> ESR1, brcaSubset)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm1)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = S100A8 ~ ESR1, data = brcaSubset)

Residuals:
   Min     1Q Median     3Q    Max 
-95.43 -34.81  -6.79  34.23 145.21 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 208.47145   28.57207   7.296 7.56e-08 ***
ESR1         -0.05926    0.01212  -4.891 4.08e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 59.91 on 27 degrees of freedom
Multiple R-squared:  0.4698,    Adjusted R-squared:  0.4502 
F-statistic: 23.93 on 1 and 27 DF,  p-value: 4.078e-05</code></pre>
</div>
</div>
<p>De software rapporteert <span class="math inline">\(\hat{\beta}_0=\)</span> 208.47 en <span class="math inline">\(\hat{\beta}_1=\)</span>-0.059. We besluiten dat, de verwachte S100A8 expressie gemiddeld 59 eenheden lager ligt bij patiënten met een ESR1 expressieniveau die 1000 eenheden hoger ligt. Bovendien kunnen we de S100A8 expressie voorspellen die men mag verwachten bij een gegeven ESR1 expressieniveau. Bijvoorbeeld, bij een ESR1 expressieniveau van 1300 verwachten we een S100A8 expressieniveau van 208.47 <span class="math inline">\(-\)</span> 0.059 <span class="math inline">\(\times\)</span> 1300= 131.43.</p>
<p>Merk op in Figuur <a href="#fig-brcaLin1" class="quarto-xref"><span>7.4</span></a> dat er in de dataset geen patiënt is geobserveerd die een ESR1 expressieniveau had van 1300. Op basis van de dataset zou het bijgevolg niet mogelijk zijn om, zonder gebruik te maken van een statistisch model, een schatting te bekomen voor de S100A8 expressie bij deze ESR1 expressiewaarde. Onder de veronderstelling dat de gemiddelde S100A8 expressie lineair varieert in functie van de ESR1 expressie, kunnen we alle observaties gebruiken om dit gemiddelde te schatten. Bijgevolg bekomen we een zinvol en precies resultaat, op voorwaarde dat aan de veronderstelling van lineariteit is voldaan. Het zal bijgevolg belangrijk zijn om de veronderstelling van lineariteit na te gaan (zie verder).</p>
<p>Gezien de lineariteit van het model enkel kan worden nagegaan over het geobserveerde bereik van de verklarende variabele (bijvoorbeeld, over het interval 396.1,3967.2), is het belangrijk om te begrijpen dat de resultaten van een lineair regressiemodel niet zomaar kunnen geëxtrapoleerd worden voorbij de kleinste of grootste geobserveerde <span class="math inline">\(X\)</span>-waarde. Met het model kunnen we de verwachte S100A8 intensiteit voor patiënten met een ESR1 expressie-niveau van 4500 schatten, maar de geobserveerde data laten niet toe om na te gaan of dit een betrouwbare schatting is. Het zou immers kunnen dat de regressielijn bij hoge waarden van de predictorvariabele afbuigt of opklimt waardoor een lineaire extrapolatie misleidend zou zijn. Merk zo bijvoorbeeld op dat predictie bij een ESR1 intensiteit van 4500 bijzonder misleidend is vermits ze een negatief resultaat oplevert wat onmogelijk is voor een intensiteitsmeting (208.47 <span class="math inline">\(+\)</span> -0.059 <span class="math inline">\(\times\)</span> 4500= -58.22).</p>
</section>
<section id="sec-linBesluit" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="sec-linBesluit"><span class="header-section-number">7.4</span> Statistische besluitvorming</h2>
<iframe width="560" height="315" src="https://www.youtube.com/embed/GIg108WaOcQ" frameborder="0" style="display: block; margin: auto;" allow="autoplay; encrypted-media" allowfullscreen="">
</iframe>
<p>Als de gegevens representatief zijn voor de populatie kan men in de regressiecontext eveneens aantonen dat de kleinste kwadraten schatters voor het intercept en de helling onvertekend zijn, m.a.w</p>
<p><span class="math display">\[E[\hat \beta_0]=\beta_0 \text{ en } E[\hat \beta_1]=\beta_1\]</span></p>
<p>Het feit dat de schatters gemiddeld (over een groot aantal vergelijkbare studies) niet afwijken van de waarden in de populatie, impliceert niet dat ze niet rond die waarde variëren. Om inzicht te krijgen hoe dicht we de parameterschatters bij het werkelijke intercept <span class="math inline">\(\beta_0\)</span> en de werkelijke helling <span class="math inline">\(\beta_1\)</span> mogen verwachten, wensen we bijgevolg ook haar variabiliteit te kennen.</p>
<p>In de borstkanker dataset hebben we een negatieve associatie geobserveerd tussen de S100A8 en ESR1 gen expressie. Net zoals in Hoofdstuk <a href="05-StatistischeBesluitvorming.html" class="quarto-xref"><span>6</span></a> is het op basis van de puntschatters voor de helling niet duidelijk of dat verband werkelijk voorkomt in de populatie of indien we het verband door toeval hebben geobserveerd in de dataset. De schatting van de helling is immers onnauwkeurig en zal variëren van steekproef tot steekproef. Het resultaat van een data-analyse is dus niet interpreteerbaar zonder die variabiliteit in kaart te brengen.</p>
<p>Om de resultaten uit de steekproef te kunnen veralgemenen naar de populatie zullen we in deze context eveneens inzicht nodig hebben op de verdeling van de parameterschatters. Om te kunnen voorspellen hoe de parameterschatters variëren van steekproef tot steekproef enkel en alleen op basis van slechts één steekproef zullen we naast de onderstelling van</p>
<ol type="1">
<li><em>Lineariteit</em></li>
</ol>
<p>bijkomende aannames moeten maken over de verdeling van de gegevens, met name</p>
<ol start="2" type="1">
<li><em>Onafhankelijkheid</em>: de metingen <span class="math inline">\((X_1,Y_1), ...,  (X_n,Y_n)\)</span> werden gemaakt bij n onafhankelijke subjecten/observationele eenheden</li>
<li><em>Homoscedasticiteit</em> of <em>gelijkheid van variantie</em>: de observaties variëren met een gelijke variantie rond de regressierechte. De residuen <span class="math inline">\(\epsilon_i\)</span> hebben dus een gelijke variantie <span class="math inline">\(\sigma^2\)</span> voor elke <span class="math inline">\(X_i=x\)</span>. Dat impliceert ook dat de conditionele variantie van Y gegeven X<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>, <span class="math inline">\(\text{var}(Y\vert X=x)\)</span> dus gelijk is, met name <span class="math inline">\(\text{var}(Y\vert X=x) = \sigma^2\)</span> voor elke waarde <span class="math inline">\(X=x\)</span>. De constante <span class="math inline">\(\sigma\)</span> wordt ook de <em>residuele standaarddeviatie</em> genoemd.</li>
<li><em>Normaliteit</em>: de residuen <span class="math inline">\(\epsilon_i\)</span> zijn normaal verdeeld.</li>
</ol>
<p>Uit 2, 3 en 4 volgt dus dat de residuen <span class="math inline">\(\epsilon_i\)</span> onafhankelijk zijn en dat ze allen eenzelfde Normale verdeling volgen</p>
<p><span class="math display">\[\epsilon_i \sim N(0,\sigma^2).\]</span></p>
<p>Als we ook steunen op de veronderstelling van lineariteit weten we dat de originele observaties conditioneel op <span class="math inline">\(X\)</span> eveneens Normaal verdeeld zijn</p>
<p><span class="math display">\[Y_i\sim N(\beta_0+\beta_1 X_i,\sigma^2),\]</span></p>
<p>met een gemiddelde dat varieert in functie van de waarde van de onafhankelijke variabele <span class="math inline">\(X_i\)</span>.</p>
<p>Verder kan men aantonen dat onder deze aannames</p>
<p><span class="math display">\[\sigma^2_{\hat{\beta}_0}=\frac{\sum\limits_{i=1}^n X^2_i}{\sum\limits_{i=1}^n (X_i-\bar X)^2} \times\frac{\sigma^2}{n} \text{ en } \sigma^2_{\hat{\beta}_1}=\frac{\sigma^2}{\sum\limits_{i=1}^n (X_i-\bar X)^2}\]</span></p>
<p>en dat de parameterschatters eveneens normaal verdeeld zijn</p>
<p><span class="math display">\[\hat\beta_0 \sim N\left(\beta_0,\sigma^2_{\hat \beta_0}\right) \text{ en } \hat\beta_1 \sim N\left(\beta_1,\sigma^2_{\hat \beta_1}\right)\]</span></p>
<p>Merk op dat de onzekerheid op de helling af zal nemen wanneer er meer observaties zijn en/of wanneer de observaties meer gespreid zijn. Voor het opzetten van een experiment kan dit belangrijke informatie zijn. Uiteraard wordt de precisie ook beïnvloed door de grootte van de variabiliteit van de observaties rond de rechte, <span class="math inline">\(\sigma^2\)</span>, maar dat heeft een onderzoeker meestal niet in de hand.</p>
<p>De conditionele variantie (<span class="math inline">\(\sigma^2\)</span>) is echter niet gekend en is noodzakelijk voor de berekening van de variantie op de parameterschatters. We kunnen <span class="math inline">\(\sigma^2\)</span> echter ook schatten op basis van de observaties. Zoals beschreven in Hoofdstuk <a href="04-DataExploratie.html" class="quarto-xref"><span>5</span></a> kunnen we de variatie van de uitkomsten rond hun conditionele gemiddelde beschrijven d.m.v. de afwijkingen tussen de observaties <span class="math inline">\(y_i\)</span> en hun (geschatte) gemiddelde <span class="math inline">\(\hat{g}(x)=\hat{\beta}_0+\hat{\beta}_1x_i\)</span>, de residu’s. Het gemiddelde van die residu’s is echter altijd 0 omdat positieve en negatieve residu’s mekaar opheffen. Bijgevolg levert het gemiddelde residu geen goede maat op voor de variatie en is het beter om naar kwadratische afwijkingen <span class="math inline">\(e_i^2\)</span> te kijken. Net zoals de steekproefvariantie een goede schatter was voor de variantie (Sectie <a href="04-DataExploratie.html#sec-spreiding" class="quarto-xref"><span>5.3.2</span></a>), zal in de regressiecontext het gemiddelde van die kwadratische afwijkingen rond de regressierechte opnieuw een goede schatter zijn voor <span class="math inline">\(\sigma^2\)</span>. Deze schatter wordt in de literatuur ook wel de <em>mean squared error</em> (MSE) genoemd.</p>
<p><span class="math display">\[\hat\sigma^2=MSE=\frac{\sum\limits_{i=1}^n \left(y_i-\hat\beta_0-\hat\beta_1\times x_i\right)^2}{n-2}=\frac{\sum\limits_{i=1}^n e^2_i}{n-2}.\]</span></p>
<p>Voor het bekomen van deze schatter steunen we op onafhankelijkheid (aanname 2) en homoscedasticiteit (aanname 3). Merk op dat we bij deze schatter niet delen door het aantal observaties <span class="math inline">\(n\)</span>, maar door <span class="math inline">\(n-2\)</span>. Hierbij corrigeren we voor het feit dat voor de berekening van MSE 2 vrijheidsgraden worden gespendeerd aan het schatten van het intercept en de helling.</p>
<p>Na het schatten van MSE kunnen we <span class="math inline">\(\sigma^2\)</span> door MSE vervangen zodat schatters worden bekomen voor de variantie en standard error op de schatters van model parameters,</p>
<p><span class="math display">\[\text{SE}_{\hat{\beta}_0}=\hat\sigma_{\hat{\beta}_0}=\sqrt{\frac{\sum\limits_{i=1}^n X^2_i}{\sum\limits_{i=1}^n (X_i-\bar X)^2} \times\frac{\text{MSE}}{n}} \text{ en } \text{SE}_{\hat{\beta}_1}=\hat\sigma_{\hat{\beta}_1}=\sqrt{\frac{\text{MSE}}{\sum\limits_{i=1}^n (X_i-\bar X)^2}}\]</span></p>
<p>Analoog als in Hoofdstuk <a href="05-StatistischeBesluitvorming.html" class="quarto-xref"><span>6</span></a> kunnen we opnieuw toetsen en betrouwbaarheidsintervallen construeren op basis van de teststatistieken</p>
<p><span class="math display">\[T=\frac{\hat{\beta}_k-\beta_k}{SE(\hat{\beta}_k)} \text{ met } k=0,1.\]</span></p>
<p>Als aan alle aannames is voldaan dan volgen deze statistieken <span class="math inline">\(T\)</span> een t-verdeling met n-2 vrijheidsgraden. Wanneer niet is voldaan aan de veronderstelling van normaliteit maar wel aan lineariteit, onafhankelijkheid en homoscedasticiteit dan kunnen we voor inferentie opnieuw beroep doen op de centrale limietstelling die zegt dat de statistiek T bij benadering een standaard Normaal verdeling zal volgen wanneer het aantal observaties voldoende groot is.</p>
<p>In de borstkanker dataset hebben we een negatieve associatie geobserveerd tussen de S100A8 en ESR1 gen expressie. We kunnen het effect in de steekproef nu veralgemenen naar de populatie toe door een betrouwbaarheidsinterval te bouwen voor de helling:</p>
<p><span class="math display">\[[\hat\beta_1 - t_{n-2,\alpha/2} \text{SE}_{\hat\beta_1},\hat\beta_1 + t_{n-2,\alpha/2} \text{SE}_{\hat\beta_1}]\]</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(lm1)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   2.5 %       97.5 %
(Intercept) 149.84639096 267.09649989
ESR1         -0.08412397  -0.03440378</code></pre>
</div>
</div>
<p>Op basis van de R-output bekomen we een 95% betrouwbaarheidsinterval voor de helling [-0.084,-0.034]. Gezien nul niet in het interval ligt weten we eveneens dat de negatieve associatie statistisch significant is op het 5% significantieniveau.</p>
<p>Anderzijds kunnen we ook een formele hypothesetoets uitvoeren. Onder de nulhypothese veronderstellen we dat er geen associatie is tussen de expressie van beide genen:</p>
<p><span class="math display">\[H_0: \beta_1=0\]</span></p>
<p>en onder de alternatieve hypothese is er een associatie tussen beide genen:</p>
<p><span class="math display">\[H_1: \beta_1\neq0\]</span></p>
<p>Met de test statistiek</p>
<p><span class="math display">\[T=\frac{\hat{\beta}_1-0}{SE(\hat{\beta}_k)}\]</span></p>
<p>kunnen we de nulhypothese falsifiëren. Onder <span class="math inline">\(H_0\)</span> volgt de statistiek een t-verdeling met n-2 vrijheidsgraden.</p>
<p>Deze tweezijdige test is geïmplementeerd in de standaard output van R.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm1)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = S100A8 ~ ESR1, data = brcaSubset)

Residuals:
   Min     1Q Median     3Q    Max 
-95.43 -34.81  -6.79  34.23 145.21 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 208.47145   28.57207   7.296 7.56e-08 ***
ESR1         -0.05926    0.01212  -4.891 4.08e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 59.91 on 27 degrees of freedom
Multiple R-squared:  0.4698,    Adjusted R-squared:  0.4502 
F-statistic: 23.93 on 1 and 27 DF,  p-value: 4.078e-05</code></pre>
</div>
</div>
<p>De test geeft weer dat de associatie tussen de S100A8 en ESR1 genexpressie extreem significant is (p&lt;&lt;0.001). Als de nulhypothese waar is en als aan alle voorwaarden is voldaan dan is er een kans van 4 op 100000 om een helling te vinden die minstens even extreem is door toeval. Het is bijgevolg heel onwaarschijnlijk om dergelijke associatie te observeren in een steekproef wanneer de nulhypothese waar is.</p>
<p>Vooraleer we een conclusie trekken is het echter belangrijk dat we alle aannames verifiëren omdat de statistische test en de betrouwbaarheidsintervallen anders incorrect zijn.</p>
</section>
<section id="nagaan-van-modelveronderstellingen" class="level2" data-number="7.5">
<h2 data-number="7.5" class="anchored" data-anchor-id="nagaan-van-modelveronderstellingen"><span class="header-section-number">7.5</span> Nagaan van modelveronderstellingen</h2>
<iframe width="560" height="315" src="https://www.youtube.com/embed/cs_IzOFFEwg" frameborder="0" style="display: block; margin: auto;" allow="autoplay; encrypted-media" allowfullscreen="">
</iframe>
<p>Voor de statistische besluitvorming hebben we volgende aannames gedaan</p>
<ol type="1">
<li>Lineariteit</li>
<li>Onafhankelijkheid<br>
</li>
<li>Homoscedasticiteit</li>
<li>Normaliteit</li>
</ol>
<p>Onafhankelijkheid is moeilijk te verifiëren op basis van de data, dat zou gegarandeerd moeten zijn door het design van de studie. Als we afwijkingen zien van lineariteit dan heeft besluitvorming geen zin gezien het de primaire veronderstelling is. In dat geval moeten we het conditioneel gemiddeld eerst beter modelleren. In geval van lineariteit maar schendingen van homoscedasticiteit of normaliteit dan weten we dat de besluitvorming mogelijks incorrect is omdat de teststatistiek dan niet langer een t-verdeling volgt.</p>
<section id="lineariteit" class="level3" data-number="7.5.1">
<h3 data-number="7.5.1" class="anchored" data-anchor-id="lineariteit"><span class="header-section-number">7.5.1</span> Lineariteit</h3>
<p>De primaire veronderstelling in lineaire regressie-analyse is de aanname dat de uitkomst (afhankelijke variabele) lineair varieert ten opzichte van de verklarende variabele. Deze veronderstelling kan men gemakkelijk grafisch verifiëren op basis van een scatterplot waarbij men de uitkomst uitzet in functie van de verklarende variabele. Vervolgens gaat men na of het verband een lineair patroon volgt.<br>
In Figuur <a href="#fig-brcaLin1" class="quarto-xref"><span>7.4</span></a> zien we systematische afwijkingen bij kleine en grote waarden voor de ESR1 expressie. De observaties liggen dan steeds systematisch boven de regressierechte wat aangeeft dat het gemiddelde in deze regio’s systematisch wordt onderschat. Afwijkingen van lineariteit worden vaak echter makkelijker opgespoord d.m.v. een <em>residuplot</em>. Dit is een scatterplot met de verklarende variabele op de <span class="math inline">\(X\)</span>-as en de <em>residuen</em> op de <span class="math inline">\(Y\)</span>-as</p>
<p><span class="math display">\[e_i=y_i-\hat{g}(x_i)=y_i-\hat\beta_0-\hat\beta_1\times x_i,\]</span></p>
<p>deze werden weergegeven in Figuur <a href="#fig-brcaLinRes" class="quarto-xref"><span>7.5</span></a>.</p>
<p>Als de veronderstelling van lineariteit opgaat, krijgt men in een residuplot geen patroon te zien. De residuen zijn immers gemiddeld nul voor elke waarde van de predictor en zouden dus mooi rond nul moeten variëren.</p>
<p>Wanneer de residu’s echter een niet-lineair patroon onthullen, dan geeft dit aan dat extra termen in het model moeten worden opgenomen om de gemiddelde uitkomst correct te voorspellen. Bijvoorbeeld, wanneer de residu’s een kwadratisch patroon onthullen, dan kunnen we schrijven dat bij benadering <span class="math inline">\(e_i\approx \delta_0+\delta_1 x_i+\delta_2 x_i^2\)</span> voor zekere getallen <span class="math inline">\(\delta_0,\delta_1,\delta_2\)</span>, en bijgevolg dat de uitkomst <span class="math inline">\(y_i=\hat{\alpha}+\hat{\beta}x_i+e_i\approx (\hat{\alpha}+\delta_0)+(\hat{\beta}+\delta_1)x_i+\delta_2 x_i^2\)</span> (op een foutterm na) een kwadratische functie is van <span class="math inline">\(x_i\)</span>. In dat geval is het aangewezen om op een kwadratisch regressiemodel over te stappen (zie Hoofdstuk <a href="10-GeneralLinearModel.html" class="quarto-xref"><span>11</span></a>). Residuplots worden standaard gegenereerd door de R-software. Hier worden de residuen echter geplot ten opzichte van de gefitte waarden wat eenvoudiger is wanneer meerdere predictoren in het model worden opgenomen (zie Hoofdstuk <a href="10-GeneralLinearModel.html" class="quarto-xref"><span>11</span></a>).</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(lm1)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-brcaLinDiag1" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-brcaLinDiag1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-LineareRegressie_files/figure-html/fig-brcaLinDiag1-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-brcaLinDiag1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figuur&nbsp;7.6: Diagnostische plots voor het nagaan van de veronderstellingen van het lineair regressiemodel waarbij de S100A8 expressie wordt gemodelleerd i.f.v de ESR1 expressie (na verwijdering van 3 outliers).
</figcaption>
</figure>
</div>
</div>
</div>
<p>De residu plot voor het borstkanker voorbeeld wordt weergegeven in Figuur <a href="#fig-brcaLinDiag1" class="quarto-xref"><span>7.6</span></a> boven links. De residuen zijn niet overal mooi gespreid rond nul. Bij lage en hoge voorspelde waarden voor het model (dus bij hoge en lage waarden voor de predictor, negatieve helling) zijn de residuen overwegend positief wat opnieuw aangeeft dat het model de data in deze regio’s systematisch onderschat. Dat was ergens te verwachten gezien de smoother in Figuur <a href="#fig-brcaSmooth" class="quarto-xref"><span>7.3</span></a> immers eerder een exponentiëel verband suggereerde. Bovendien voorspelde het regressiemodel eveneens negatieve waarden voor de S100A8 expressie wat onmogelijk is voor intensiteitsmetingen die immers steeds positief zijn.</p>
</section>
<section id="veronderstelling-van-homoscedasticiteit-gelijkheid-van-variantie" class="level3" data-number="7.5.2">
<h3 data-number="7.5.2" class="anchored" data-anchor-id="veronderstelling-van-homoscedasticiteit-gelijkheid-van-variantie"><span class="header-section-number">7.5.2</span> Veronderstelling van homoscedasticiteit (gelijkheid van variantie)</h3>
<p>Residuen en kwadratische residu’s dragen informatie in zich over residuele variabiliteit. Als er homoscedasiticiteit is dan verwachten we dat de residuen eenzelfde spreiding hebben voor elke waarde van de predictor en voor elke predictie. Als de spreiding in de residuen geassocieerd zijn met de verklarende variabelen, dan is er indicatie van heteroscedasticiteit. De diagnostische plots van het software pakket R geven een residu-plot weer en een plot van de vierkantswortel van de absolute waarde van de gestandaardiseerde error <span class="math inline">\(\sqrt{|e_i|/\sqrt{MSE}}\)</span> in functie van de predicties. De residu-plot voor het borstkanker voorbeeld Figuur <a href="#fig-brcaLinDiag1" class="quarto-xref"><span>7.6</span></a> boven links geeft afwijkingen weer van homoscedasiticiteit. De spreiding in de residuen lijkt toe te nemen met een toenemende waarde van de predictor. De plot beneden links is specifiek om de voorwaarde van gelijkheid van variantie na te gaan en geeft eveneens aan dat de variantie toeneemt met het conditioneel gemiddelde. Een dergelijke trend komt dikwijls voor bij concentratiemetingen en intensiteitsmetingen, die vaak een multiplicatieve errorstructuur vertonen i.p.v. een additieve error.</p>
<p>Voor bepaalde types uitkomsten bestaan er <em>variantie-stabiliserende transformaties</em> voor de afhankelijke variabele die erop gericht zijn om de onderstelling van homoscedasticiteit te doen opgaan. Voor proporties of percentages, gebruikt men bijvoorbeeld vaak de arcsin-transformatie die de uitkomst <span class="math inline">\(Y\)</span> omzet in <span class="math inline">\(\arcsin\sqrt{Y}\)</span>, omdat men kan aantonen dat percentages (onder bepaalde onderstellingen) een constante variantie hebben na deze transformatie. Voor concentraties en intensiteitsmetingen gebruikt men dan weer vaak een logaritmische transformatie gezien deze (a) positief zijn, (b) vaak gekenmerkt worden door een variantie die toeneemt met het gemiddelde en (c) veelal een scheve verdeling vertonen maar rechts. Indien transformatie van de uitkomst niet helpt of niet wenselijk is (bijvoorbeeld, omdat het de interpretatie van het model niet ten goede komt) en er is een consistent patroon van ongelijke variantie (bijvoorbeeld, toenemende variantie in uitkomst bij toenemende predictorwaarden), dan kan men ook <em>gewogen kleinste kwadratenschatters</em> (in het Engels: <em>weighted least squares</em>) bepalen. Een verder alternatief is om <em>veralgemeende lineaire modellen</em> (in het Engels: <em>generalized linear models</em>) te schatten die tevens andere verdelingen voor de uitkomst dan de Normale verdeling toelaten. Beide klassen van oplossingen (d.i. gewogen kleinste kwadratenschatters en veralgemeende lineaire modellen) vallen echter buiten het bestek van deze cursus.</p>
</section>
<section id="veronderstelling-van-normaliteit" class="level3" data-number="7.5.3">
<h3 data-number="7.5.3" class="anchored" data-anchor-id="veronderstelling-van-normaliteit"><span class="header-section-number">7.5.3</span> Veronderstelling van normaliteit</h3>
<p>Opnieuw kunnen we de veronderstelling van normaliteit nagaan door gebruik te maken van QQ-plots. Een QQ-plot van de afhankelijke variabele is misleidend omdat deze nagaat of de metingen voor alle subjecten samen Normaal verdeeld zijn. Dat is echter niet het geval gezien de normale verdeling per subject varieert. Elk subject kan immers andere waarde hebben voor de predictor <span class="math inline">\(X\)</span> (ESR1 expressie) en bijgevolg hebben ze een verschillend conditioneel gemiddelde. Normaal verdeelde uitkomsten bij gegeven <span class="math inline">\(x\)</span>-waarde impliceert echter dat de residu’s bij benadering Normaal verdeeld zijn. Afwijkingen van Normaliteit in een QQ-plot van de residu’s levert dus een indicatie dat de uitkomsten niet Normaal verdeeld zijn bij vaste <span class="math inline">\(x\)</span>.</p>
<p>Figuur <a href="#fig-brcaLinDiag1" class="quarto-xref"><span>7.6</span></a> rechts boven geeft de QQ-plot weer van de residuen voor het borstkanker voorbeeld. We zien wat afwijkingen in de rechterstaart die wijzen op meerdere outliers of op observaties die systematisch hoger liggen dan wat verwacht kan worden op basis van de normaalverdeling. Dit is niet verrassend omdat heterogeniteit van de variantie vaak samengaat met niet-Normaliteit, i.h.b. scheefheid, van de gegevens. Dat komt vaak voor bij concentratie- en intensiteitsmetingen.</p>
</section>
</section>
<section id="afwijkingen-van-modelveronderstellingen" class="level2" data-number="7.6">
<h2 data-number="7.6" class="anchored" data-anchor-id="afwijkingen-van-modelveronderstellingen"><span class="header-section-number">7.6</span> Afwijkingen van Modelveronderstellingen</h2>
<iframe width="560" height="315" src="https://www.youtube.com/embed/CEgIqaqVj4M" frameborder="0" style="display: block; margin: auto;" allow="autoplay; encrypted-media" allowfullscreen="">
</iframe>
<p>De primaire onderstelling in lineaire regressie-analyse is de aanname dat de uitkomst lineair varieert in de predictor. Wanneer residuplots suggereren dat aan deze onderstelling niet is voldaan, dan kan men overwegen om de verklarende variabele te transformeren. In genexpressie studies waarbij expressie als een covariaat wordt gebruikt om een andere variabele te verklaren, is het bijvoorbeeld vaak zo dat de (gemiddelde) uitkomst niet lineair varieert in functie van de predictor, maar wel in functie van het logaritme van de genexpressie. In dat geval kan men ervoor kiezen om de log-transformatie van de verklarende variabele als predictor in het model op te nemen. Vaak wordt in expressie studies een <span class="math inline">\(\log_2\)</span> transformatie gebruikt. In andere voorbeelden kan een andere transformatie dan de log-transformatie beter geschikt zijn, zoals de vierkantswortel (<span class="math inline">\(\sqrt{x}\)</span>) of inverse (<span class="math inline">\(1/x\)</span>) transformatie.</p>
<p>Een transformatie van de verklarende variabele is vaak makkelijk uit te voeren, maar bemoeilijkt wel vaak de interpretatie van de parameters in het model. Dit laatste is echter niet het geval wanneer de log-transformatie wordt gebruikt, een stijging in <span class="math inline">\(log_2\)</span>-expressie met bijvoorbeeld 1 eenheid is immers equivalent met een wijziging in genexpressie met een factor <span class="math inline">\(2^1=2\)</span>. Kenmerkend aan transformatie van de verklarende variabele is dat ze geen rechtstreekse invloed heeft op de homogeniteit van de variantie en de Normaliteit van de uitkomst (bij vaste waarden van de predictorvariabele), tenzij door het verbeteren van de lineariteit van het model. Om die reden is deze optie vaak minder geschikt wanneer er sterke afwijkingen van Normaliteit zijn.</p>
<p>Een alternatieve mogelijkheid om de lineariteit van het model te verbeteren, is hogere orde regressie (in het Engels: <em>higher order regression</em>). Hierbij modelleert men rechtstreeks niet-lineaire relaties door hogere orde termen in het model op te nemen. Zo kan men bijvoorbeeld een tweede orde model beschouwen:</p>
<p><span class="math display">\[E(Y|X)=\beta_0+\beta_1X+\beta_2X^2\]</span></p>
<p>zodat de regressiekromme eruit ziet als een parabool, of een derde orde model:</p>
<p><span class="math display">\[E(Y|X)=\beta_0+\beta_1X+\beta_2X^2+\beta_3X^3\]</span></p>
<p>zodat de regressiekromme een derdegraadspolynoom is. Deze methode kan gezien worden als een vorm van transformatie van de verklarende variabele en bezit wezenlijk dezelfde eigenschappen en voor- en nadelen. Een bijkomend voordeel is echter dat het hier niet nodig is om zelf een transformatie te zoeken, maar dat de methode zelf impliciet een goede polynoom als transformatie schat.</p>
<p>Tenslotte kan men ook overwegen om, in plaats van de verklarende variabele, de uitkomst te transformeren. Bijvoorbeeld, wanneer de uitkomsten scheef verdeeld zijn naar rechts is het vaak aangewezen om een log-transformatie van de uitkomst uit te voeren en deze nieuwe variabele als uitkomst in het model op te nemen. Doorgaans verbetert dit niet alleen de lineariteit van het model, maar maakt het ook de residu’s beter Normaal verdeeld met een meer constante variabiliteit. Deze methode heeft dezelfde voor- en nadelen als transformatie van de verklarende variabele. Een groot verschil dat de keuze tussen beide methoden beïnvloedt is dat transformaties van de onafhankelijke variabele weinig of geen invloed hebben op de verdeling van de residu’s (tenzij via wijzigingen in hun gemiddelde) in tegenstelling tot transformaties van de afhankelijke variabele. In het bijzonder blijven Normaal verdeelde residu’s vrij Normaal verdeeld na transformatie van de verklarende variabele, terwijl ze mogelijks niet langer Normaal verdeeld zijn na transformatie van de uitkomst, en vice versa.</p>
<p>In het borstkanker voorbeeld wordt de S100A8 genexpressie gemodelleerd in functie van de ESR1 genexpressie. Er waren problemen m.b.t. heteroscedasticiteit, mogelijkse afwijking van normaliteit (scheefheid naar rechts), negatieve concentratievoorspellingen die theoretisch niet mogelijk zijn en niet-lineairiteit. Dergelijke problemen treden veelal op bij concentratie en intensiteitsmetingen. Deze zijn vaak log-normaal verdeeld (normale verdeling na log-transformatie) en worden daarom vaak log-getransformeerd. Bovendien zagen we in Figuur <a href="#fig-brcaSmooth" class="quarto-xref"><span>7.3</span></a> eveneens een soort exponentiële trend. In de genexpressie literatuur wordt veelal gebruik gemaak van <span class="math inline">\(\log_2\)</span> transformatie gezien een verschil van 1 op log-schaal een verdubbeling impliceert in de expressie op de originele schaal. Wanneer men gen-expressie op log-schaal modelleert, modellert men dus in feite proportionele verschillen op de originele schaal wat ook meer relevant is vanuit een biologisch standpunt.</p>
<p>In deze sectie zullen we beide genexpressies <span class="math inline">\(\log_2\)</span> transformeren en een log-lineaire regressie uitvoeren. Zoals we zullen zien vormen de outliers in de S100A8 expressie na log-transformatie ook geen problemen meer.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>brca <span class="ot">&lt;-</span> brca <span class="sc">|&gt;</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">log2S100A8 =</span> <span class="fu">log2</span>(S100A8),</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">log2ESR1 =</span> <span class="fu">log2</span>(ESR1)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>lm2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(log2S100A8 <span class="sc">~</span> log2ESR1, brca)</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>brca <span class="sc">|&gt;</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> log2ESR1, <span class="at">y =</span> log2S100A8)) <span class="sc">+</span></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">col =</span> <span class="st">"grey"</span>) <span class="sc">+</span></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-brcaLogLin" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-brcaLogLin-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-LineareRegressie_files/figure-html/fig-brcaLogLin-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-brcaLogLin-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figuur&nbsp;7.7: Scatterplot voor log2-S100A8 expressie in functie van de log2-ESR1 expressie met smoother en lineair model die het verband tussen beide genen samenvatten (outliers worden niet langer verwijderd uit de dataset).
</figcaption>
</figure>
</div>
</div>
</div>
<p>In Figuur <a href="#fig-brcaLogLin" class="quarto-xref"><span>7.7</span></a> zien we duidelijk een dalende lineaire trend van de S100A8 expressie i.f.v. de ESR1 expressie na log-transformatie. De smoother toont ook niet langer een afwijking aan van lineariteit. Daarnaast kunnen we alle data meenemen in de analyse en kan het model geen negatieve expressiewaarden meer voorspellen na terugtransformatie. In Figuur <a href="#fig-brcaLogLin2" class="quarto-xref"><span>7.8</span></a> zien we tevens dat er niet langer afwijkingen zijn van lineariteit, normaliteit en gelijkheid van variantie. De residuen in de residu-plot liggen mooi rond nul en hebben een constante spreiding. De QQ-plot toont geen systematische afwijkingen van normaliteit en de plot links beneden toont ook geen trend in de variantie van de residuen.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(lm2)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-brcaLogLin2" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-brcaLogLin2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-LineareRegressie_files/figure-html/fig-brcaLogLin2-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-brcaLogLin2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figuur&nbsp;7.8: Diagnostische plots voor het lineair model voor log2-S100A8 expressie in functie van de log2-ESR1.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Na log-transformatie zijn alle voorwaarden voldaan en kunnen we overgaan tot statistische besluitvorming en interpretatie van de modelparameters.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm2)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log2S100A8 ~ log2ESR1, data = brca)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.94279 -0.66537  0.08124  0.68468  1.92714 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   23.401      1.603   14.60 3.57e-15 ***
log2ESR1      -1.615      0.150  -10.76 8.07e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.026 on 30 degrees of freedom
Multiple R-squared:  0.7942,    Adjusted R-squared:  0.7874 
F-statistic: 115.8 on 1 and 30 DF,  p-value: 8.07e-12</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(lm2)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                2.5 %    97.5 %
(Intercept) 20.128645 26.674023
log2ESR1    -1.921047 -1.308185</code></pre>
</div>
</div>
<p>Er is een extreem significante negatieve associatie tussen de S100A8 en ESR1 genexpressie (<span class="math inline">\(p&lt;&lt;0.001\)</span>).</p>
<!---break-->
<iframe width="560" height="315" src="https://www.youtube.com/embed/1RSt_majpH0" frameborder="0" style="display: block; margin: auto;" allow="autoplay; encrypted-media" allowfullscreen="">
</iframe>
<p><strong>Interpretatie 1</strong></p>
<p>Een patiënt met een ESR1 expressie die 1 eenheid op de <span class="math inline">\(\log_2\)</span> schaal hoger ligt dan dat van een andere patiënt heeft gemiddeld gezien een expressie-niveau van het S100A8 gen dat 1.61 eenheden lager ligt (95% BI [-1.92,-1.31]).</p>
<p>Merk op dat dit een crossectionele studie is, we kunnen met het model alleen maar uitspraken doen over verschillen tussen patiënten!</p>
<p><span class="math display">\[\log_2 \hat\mu_1=23.401  -1.615 \times \text{logESR}_1,\text{ } \log_2 \hat\mu_2=23.401  -1.615 \times \text{logESR}_2 \]</span></p>
<p><span class="math display">\[\log_2 \hat\mu_2-\log_2 \hat\mu_1=  -1.615 (\log_2 \text{ESR}_2-\log_2 \text{ESR}_1) = -1.615 \times 1 = -1.615\]</span></p>
<p><strong>Interpretatie 2</strong> Wanneer de data op log-schaal wordt gemodelleerd, worden na terugtransformatie geometrische gemiddelden bekomen. Ter illustratie herschrijven we bijvoorbeeld het rekenkundig gemiddelde op de log schaal:</p>
<p><span class="math display">\[\begin{eqnarray*}
\sum\limits_{i=1}^n \frac{\log x_i}{n}&amp;=&amp;\frac{\log x_1 + \ldots + \log x_n}{n}\\\\
&amp;\stackrel{(1)}{=}&amp;\frac{\log(x_1 \times \ldots \times x_n)}{n}=\frac{\log\left(\prod\limits_{i=1}^n x_i\right)}{n}\\\\
&amp;\stackrel{(2)}{=}&amp;\log \left(\sqrt[\leftroot{-1}\uproot{2}\scriptstyle n]{\prod\limits_{i=1}^n x_i}\right)
\end{eqnarray*}\]</span></p>
<p>waarbij in overgang (1) en (2) wordt gesteund op de eigenschappen van logaritmen en <span class="math inline">\(\prod\)</span> de product operator is. Na terug transformatie wordt dus een geometrisch gemiddelde <span class="math inline">\(\sqrt[\leftroot{-1}\uproot{2}\scriptstyle n]{\prod\limits_{i=1}^n x_i}\)</span> bekomen.</p>
<p>In de onderstaande notatie worden de populatiegemiddelden <span class="math inline">\(\mu\)</span> dus geschat a.d.h.v. geometrisch gemiddelden. Omdat de logaritmische transformatie een monotone transformatie is, kunnen we ook betrouwbaarheidsintervallen berekend op log-schaal terugtransformeren!</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span><span class="sc">^</span>lm2<span class="sc">$</span>coef[<span class="dv">2</span>]</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> log2ESR1 
0.3265519 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span><span class="sc">^-</span>lm2<span class="sc">$</span>coef[<span class="dv">2</span>]</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>log2ESR1 
  3.0623 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span><span class="sc">^-</span><span class="fu">confint</span>(lm2)[<span class="dv">2</span>,]</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   2.5 %   97.5 % 
3.786977 2.476298 </code></pre>
</div>
</div>
<p>Een patiënt met een ESR1 expressie die 2 keer zo hoog is als die van een andere patiënt, zal gemiddeld een S100A8-expressie hebben die 3.06 keer lager is (95% BI [2.48,3.79]).</p>
<p><span class="math display">\[\log_2 \hat\mu_1=23.401  -1.615 \times \text{logESR}_1,\text{ } \log_2 \hat\mu_2=23.401  -1.615 \times \text{logESR}_2 \]</span></p>
<p><span class="math display">\[\log_2 \hat\mu_2-\log_2 \hat\mu_1=  -1.615 (\log_2 \text{ESR}_2-\log_2 \text{ESR}_1) \]</span></p>
<p><span class="math display">\[\log_2 \left[\frac{\hat\mu_2}{\hat\mu_1}\right]=  -1.615 \log_2\left[\frac{ \text{ESR}_2}{\text{ESR}_1}\right] \]</span></p>
<p><span class="math display">\[\frac{\hat\mu_2}{\hat\mu_1}=\left[\frac{ \text{ESR}_2}{\text{ESR}_1}\right]^{-1.615}=2^ {-1.615} =0.326\]</span></p>
<p>of</p>
<p><span class="math display">\[\frac{\hat\mu_1}{\hat\mu_2}=2^{1.615} =3.06\]</span></p>
<p><strong>Interpretatie 3</strong> Een patiënt met een ESR1 expressie die 1% hoger is dan die van een andere patiënt zal gemiddeld een expressieniveau voor het S100A8 gen hebben dat ongeveer 1.61% lager is (95% BI [-1.92,-1.31]%).</p>
<p><span class="math display">\[\log_2 \hat\mu_1=23.401  -1.615 \times \text{logESR}_1,\text{ } \log_2 \hat\mu_2=23.401  -1.615 \times \text{logESR}_2 \]</span></p>
<p><span class="math display">\[\log_2 \hat\mu_2-\log_2 \hat \mu_1=  -1.615 (\log_2 \text{ESR}_2-\log_2 \text{ESR}_1) \]</span></p>
<p><span class="math display">\[\log_2 \left[\frac{\hat\mu_2}{\hat\mu_1}\right]=  -1.615 \log_2\left[\frac{ \text{ESR}_2}{\text{ESR}_1}\right] \]</span></p>
<p><span class="math display">\[\frac{\hat\mu_2}{\hat\mu_1}=\left[\frac{ \text{ESR}_2}{\text{ESR}_1}\right]^{-1.615}=1.01^ {-1.615} =0.984 \approx -1.6\%\]</span></p>
<p>Merk op dat voor waarden van</p>
<p><span class="math display">\[−10&lt; \beta_1&lt;10 \rightarrow 1.01 ^{\beta_1}−1 \approx \frac{\beta_1}{100}.\]</span></p>
<p>Dus voor log-getransformeerde predictoren met kleine tot gematigde waarden voor <span class="math inline">\(\beta_1\)</span> kan de helling <span class="math inline">\(\beta_1\)</span> als volgt geïnterpreteerd worden: een 1% toename in de predictor resulteert gemiddeld in een <span class="math inline">\(\beta_1\)</span>% verschil in de uitkomst.</p>
</section>
<section id="besluitvorming-over-gemiddelde-uitkomst" class="level2" data-number="7.7">
<h2 data-number="7.7" class="anchored" data-anchor-id="besluitvorming-over-gemiddelde-uitkomst"><span class="header-section-number">7.7</span> Besluitvorming over gemiddelde uitkomst</h2>
<iframe width="560" height="315" src="https://www.youtube.com/embed/Ix_ih2SxtKA" frameborder="0" style="display: block; margin: auto;" allow="autoplay; encrypted-media" allowfullscreen="">
</iframe>
<p>In de sectie <a href="#sec-linBesluit" class="quarto-xref"><span>7.4</span></a> toonden we dat de parameterschatters van het linear regressie model normaal verdeeld zijn onder de voorwaarden van onafhankelijkheid, lineariteit, homoscedasticiteit en (conditionele) normaliteit van de gegevens. Het regressie model wordt niet enkel gebruikt om de associatie tussen twee variabelen te bestuderen, maar ook om voorspellingen te doen van de response gegeven een gekende waarde voor de predictor. In dat geval wenst men vaak besluitvorming te doen over de gemiddelde uitkomst geschat met het model bij een gegeven waarde <span class="math inline">\(x\)</span>, m.a.w.</p>
<p><span class="math display">\[\hat{g}(x)= \hat{\beta}_0 + \hat{\beta}_1 x\]</span></p>
<p>Hierbij is de gemiddelde uitkomst <span class="math inline">\(\hat{g}(x)\)</span> een schatter van het conditionele gemiddelde <span class="math inline">\(E[Y\vert X=x]\)</span>. Wanneer de parameterschatters een Normale verdeling volgen zal de schatter voor de gemiddelde uitkomst ook Normaal verdeeld zijn gezien het een lineaire combinatie is van de parameterschatters. Gezien de parameterschatters onvertekend zijn, is de schatter van de gemiddelde uitkomst dat ook.</p>
<p>Men kan aantonen dat de standard error op de schatter voor de gemiddelde uitkomst</p>
<p><span class="math display">\[\text{SE}_{\hat{g}(x)}=\sqrt{MSE\left\{\frac{1}{n}+\frac{(x-\bar X)^2}{\sum\limits_{i=1}^n (X_i-\bar X)^2}\right\}}.\]</span></p>
<p>Dit geeft aan dat de schatter voor de gemiddelde uitkomst het meest precies is voor <span class="math inline">\(x=\bar x\)</span> en in dit punt zelfs even precies zijn dan wanneer alle observaties <span class="math inline">\(x_1,\ldots, x_n\)</span> in de steekproef gelijk zouden zijn aan <span class="math inline">\(x\)</span>.</p>
<p>Opnieuw kan men aantonen dat de statistiek</p>
<p><span class="math display">\[T=\frac{\hat{g}(x)-g(x)}{SE_{\hat{g}(x)}}\sim t_{n-2}\]</span></p>
<p>een t-verdeling volgt met <span class="math inline">\(n-2\)</span> vrijheidsgraden.</p>
<p>Deze statistiek kan opnieuw gebruikt worden voor besluitvorming d.m.v. hypothese testen of door de constructie van betrouwbaarheidsintervallen.</p>
<p>De gemiddelde uitkomst en betrouwbaarheidsintervallen op de gemiddelde uitkomst kunnen eenvoudig worden verkregen in R via de <code>predict(.)</code> functie. De predictorwaarden (x-waarden) voor het berekenen van gemiddelde uitkomsten kunnen worden meegegeven via het <code>newdata</code> argument. Betrouwbaarheidsintervallen op de geschatte gemiddelde uitkomsten kunnen worden verkregen d.m.v. het argument <code>interval="confidence"</code>. Zonder het newdata argument wordt de gemiddelde uitkomsten berekend voor alle predictorwaarden van de dataset.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>grid <span class="ot">&lt;-</span> <span class="fu">log2</span>(<span class="dv">140</span><span class="sc">:</span><span class="dv">4000</span>)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>g <span class="ot">&lt;-</span> <span class="fu">predict</span>(</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  lm2,</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">log2ESR1=</span>grid),</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">interval =</span> <span class="st">"confidence"</span>)</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(g)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr
1 11.89028 10.76082 13.01974
2 11.87370 10.74721 13.00019
3 11.85724 10.73370 12.98078
4 11.84089 10.72028 12.96151
5 11.82466 10.70696 12.94237
6 11.80854 10.69372 12.92336</code></pre>
</div>
</div>
<p>De gemiddelde uitkomst en hun 95% puntgewijze betrouwbaarheidsintervallen kunnen eveneens grafisch worden weergegeven (Figuur <a href="#fig-brcaLogLinPred1" class="quarto-xref"><span>7.9</span></a>)</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>brca <span class="sc">|&gt;</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> log2ESR1, <span class="at">y =</span> log2S100A8)) <span class="sc">+</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>) <span class="sc">+</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"ESR1 (log2)"</span>) <span class="sc">+</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"S100A8 (log2)"</span>)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-brcaLogLinPred1" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-brcaLogLinPred1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-LineareRegressie_files/figure-html/fig-brcaLogLinPred1-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-brcaLogLinPred1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figuur&nbsp;7.9: Scatterplot voor log2-S100A8 expressie in functie van de log2-ESR1 expressie met model schattingen en 95<span class="math inline">\(\%\)</span> betrouwbaarheidsintervallen.
</figcaption>
</figure>
</div>
</div>
</div>
<p>De gemiddelde uitkomst en hun 95% betrouwbaarheidsintervallen kunnen makkelijk worden teruggetransformeerd naar de originele schaal, zodat een geometrisch gemiddelde wordt bekomen met 95% betrouwbaarheidsintervallen op het geometrische gemiddelde. Deze kunnen dan grafisch worden weergegeven op de originele schaal in een gewone scatterplot (Figuur <a href="#fig-brcaLogLinPred2" class="quarto-xref"><span>7.10</span></a> links) of in een scatterplot met logaritmische assen (Figuur <a href="#fig-brcaLogLinPred2" class="quarto-xref"><span>7.10</span></a> rechts). In Figuur <a href="#fig-brcaLogLinPred2" class="quarto-xref"><span>7.10</span></a> (links) is het duidelijk dat we met het model na log-transformatie een exponentieel verband kunnen modelleren op de originele schaal.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>newdata <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="fu">cbind</span>(<span class="at">grid=</span> <span class="dv">2</span><span class="sc">^</span>grid, <span class="dv">2</span><span class="sc">^</span>g))</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> brca <span class="sc">|&gt;</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span> ESR1, <span class="at">y =</span> S100A8)) <span class="sc">+</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> grid, <span class="at">y =</span> fit), newdata) <span class="sc">+</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> grid, <span class="at">y =</span> lwr), newdata, <span class="at">color=</span><span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> grid, <span class="at">y =</span> upr), newdata, <span class="at">color=</span><span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"ESR1"</span>) <span class="sc">+</span></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"S100A8"</span>)</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> brca <span class="sc">|&gt;</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span> ESR1, <span class="at">y =</span> S100A8)) <span class="sc">+</span></span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> grid, <span class="at">y =</span> fit), newdata) <span class="sc">+</span></span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> grid, <span class="at">y =</span> lwr), newdata, <span class="at">color=</span><span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> grid,<span class="at">y =</span> upr), newdata, <span class="at">color=</span><span class="st">"red"</span>)  <span class="sc">+</span></span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">trans =</span> <span class="st">'log2'</span>) <span class="sc">+</span></span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">trans =</span> <span class="st">'log2'</span>) <span class="sc">+</span></span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"log2 ESR1"</span>) <span class="sc">+</span></span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"log2 S100A8"</span>)</span>
<span id="cb28-20"><a href="#cb28-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-21"><a href="#cb28-21" aria-hidden="true" tabindex="-1"></a>gridExtra<span class="sc">::</span><span class="fu">grid.arrange</span>(p1, p2, <span class="at">ncol =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-brcaLogLinPred2" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-brcaLogLinPred2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-LineareRegressie_files/figure-html/fig-brcaLogLinPred2-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-brcaLogLinPred2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figuur&nbsp;7.10: Scatterplot voor S100A8 expressie in functie van de ESR1 expressie met model schattingen (geometrische gemiddeldes) een 95<span class="math inline">\(\%\)</span> betrouwbaarheidsintervallen (links: originele schaal, rechts: originele schaal met logaritmische assen).
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="predictie-intervallen" class="level2" data-number="7.8">
<h2 data-number="7.8" class="anchored" data-anchor-id="predictie-intervallen"><span class="header-section-number">7.8</span> Predictie-intervallen</h2>
<iframe width="560" height="315" src="https://www.youtube.com/embed/U7p08lYVnPI" frameborder="0" style="display: block; margin: auto;" allow="autoplay; encrypted-media" allowfullscreen="">
</iframe>
<p>Het geschatte regressiemodel kan ook worden gebruikt om een <strong>predictie</strong> te maken voor één uitkomst van één experiment waarbij een nieuwe uitkomst <span class="math inline">\(Y^*\)</span> bij een gegeven <span class="math inline">\(x\)</span> zal geobserveerd worden. Het is belangrijk in te zien dat dit experiment nog moet worden uitgevoerd. We wensen dus een nog niet-geobserveerde individuele uitkomst te voorspellen.</p>
<p>Aangezien <span class="math inline">\(Y^*\)</span> een nieuwe, onafhankelijke observatie voorstelt, weten we dat</p>
<p><span class="math display">\[
  Y^* = g(x) + \epsilon^*
\]</span></p>
<p>met <span class="math inline">\(\epsilon^*\sim N(0,\sigma^2)\)</span> en <span class="math inline">\(\epsilon^*\)</span> onafhankelijk van de steekproefobservaties <span class="math inline">\(Y_1,\ldots, Y_n\)</span>.</p>
<p>We weten dat <span class="math inline">\(\hat{g}(x)\)</span> een schatting is van de gemiddelde log-S100A8 expressie bij de log-ESR1 expressie <span class="math inline">\(x\)</span>, met name een schatting van het conditioneel gemiddelde <span class="math inline">\(\text{E}[Y\vert x]\)</span>. We argumenteren nu dat <span class="math inline">\(\hat{g}(x)\)</span> ook een goede predictie is van een nieuwe log-S100A8 expressiewaarde <span class="math inline">\(Y^*\)</span> bij een gegeven log-ESR1 expressieniveau <span class="math inline">\(x\)</span>.</p>
<p>We weten reeds dat <span class="math inline">\(\hat{g}(x)\)</span> een schatting is van <span class="math inline">\(\text{E}[Y\vert x]\)</span>, wat het punt op de regressierechte bij <span class="math inline">\(x\)</span> voorstelt. Het regressiemodel stelt dat bij een gegeven <span class="math inline">\(x\)</span>, de individuele uitkomsten <span class="math inline">\(Y\)</span> Normaal verdeeld zijn rond dit punt op de regressierechte. Aangezien een Normale verdeling symmetrisch is, is het even waarschijnlijk om een uitkomst groter dan <span class="math inline">\(\text{E}[Y\vert x]\)</span> te observeren, als een uitkomst kleiner dan <span class="math inline">\(\text{E}[Y\vert x]\)</span> te observeren. We beschikken echter niet over meer informatie dat ons zou toelaten om te vermoeden dat een uitkomst eerder groter, dan wel kleiner dan <span class="math inline">\(\text{E}[Y\vert x]\)</span> zou zijn. Om die reden is het punt op de (geschatte) regressierechte de beste predictie van een individuele uitkomst bij een gegeven <span class="math inline">\(x\)</span>.</p>
<p>We voorspellen dus een nieuwe log-S100A8 meting bij een gekend log2-ESR1 expressieniveau x door</p>
<p><span class="math display">\[\hat{y}(x)=\hat{\beta}_0+\hat{\beta}_1 \times x\]</span></p>
<p>Merk op dat <span class="math inline">\(\hat{y}(x)\)</span> eigenlijk numeriek gelijk is aan <span class="math inline">\(\hat{g}(x)\)</span>. Gezien het verschil in interpretatie tussen een predictie en een schatting van een conditioneel gemiddelde, gebruiken we een andere notatie.</p>
<p>Hoewel de geschatte gemiddelde uitkomst en de predictie voor een nieuwe uitkomst gelijk zijn, zullen hun steekproefdistributies echter verschillend zijn: de onzekerheid op de geschatte gemiddelde uitkomst wordt gedreven door de onzekerheid op de parameterschatters <span class="math inline">\(\hat\beta_0\)</span> en <span class="math inline">\(\hat\beta_1\)</span>. De onzekerheid op de ligging van een nieuwe observatie, daarentegen, wordt gedreven door de <em>onzekerheid op het geschatte gemiddelde</em> en de <em>bijkomende onzekerheid</em> ten gevolge van het feit dat <em>nieuwe observaties at random variëren rond de het conditionele gemiddelde</em> (de regressie rechte) met een variantie <span class="math inline">\(\sigma^2\)</span>. De nieuwe observatie is eveneens onafhankelijk van de observaties in de steekproef zodat de error <span class="math inline">\(\epsilon\)</span> onafhankelijk zal zijn van de schatter van de gemiddelde uitkomst <span class="math inline">\(\hat{g}(x)\)</span>. De standard error op een predictie voor een nieuwe observatie wordt dus</p>
<p><span class="math display">\[\text{SE}_{\hat{Y}(x)}=\sqrt{\hat\sigma^2+\hat\sigma^2_{\hat{g}(x)}}=\sqrt{MSE\left\{1+\frac{1}{n}+\frac{(x-\bar X)^2}{\sum\limits_{i=1}^n (X_i-\bar X)^2}\right\}}.\]</span></p>
<p>Opnieuw kan worden aangetoond dat de statistiek</p>
<p><span class="math display">\[\frac{\hat{Y}(x)-Y}{\text{SE}_{\hat{Y}(x)}}\sim t_{n-2}\]</span></p>
<p>een t-verdeling volgt met n-2 vrijheidsgraden. Deze statistiek kan gebruikt worden om een betrouwbaarheidsinterval op de predictie te construeren, ook wel een <strong>predictie-interval</strong> (PI) genoemd. Merk op dat dit predictie-interval een verbeterde versie is van een referentie-interval wanneer de modelparameters niet gekend zijn. Het PI houdt immers rekening met de onzekerheid op het geschatte gemiddelde (gebruik van standard error op predictie i.p.v. standaard deviatie) en deze op de geschatte standaard deviatie (gebruik van t-verdeling i.p.v Normale verdeling).</p>
<p>Predicties en predictie-intervallen (PIs) kunnen opnieuw eenvoudig worden verkregen in R via de <code>predict(.)</code> functie. De predictorwaarden (x-waarden) voor het berekenen van de predicties<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> worden opnieuw meegegeven via het <code>newdata</code> argument. PIs op de predicties kunnen worden verkregen d.m.v. het argument <code>interval="prediction"</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>grid <span class="ot">&lt;-</span> <span class="fu">log2</span>(<span class="dv">140</span><span class="sc">:</span><span class="dv">4000</span>)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">predict</span>(</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  lm2,</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">log2ESR1=</span>grid),</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">interval=</span><span class="st">"prediction"</span>)</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(p)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr
1 11.89028 9.510524 14.27004
2 11.87370 9.495354 14.25205
3 11.85724 9.480288 14.23419
4 11.84089 9.465324 14.21646
5 11.82466 9.450461 14.19886
6 11.80854 9.435698 14.18138</code></pre>
</div>
</div>
<p>De predicties en hun 95% puntgewijze predictie-intervallen kunnen eveneens grafisch worden weergegeven (Figuur <a href="#fig-brcaLogLinPred3" class="quarto-xref"><span>7.11</span></a>). Merk op dat de intervallen veel breder zijn dan de betrouwbaarheidsintervallen. Merk ook op dat de meeste observaties binnen de predictie-intervallen liggen. We verwachten inderdaad gemiddeld 95% van de observaties binnen de predictie-intervallen. Dat is niet zo voor de betrouwbaarheidsintervallen, die immers geen informatie geven over de verwachte locatie van een nieuwe observatie, maar wel over waar men het conditioneel gemiddelde verwacht op basis van de steekproef!</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>preddata <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="fu">cbind</span>(<span class="at">grid =</span> grid,p))</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>brca <span class="sc">|&gt;</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>log2ESR1,<span class="at">y=</span>log2S100A8)) <span class="sc">+</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">"lm"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> grid,<span class="at">y =</span> lwr),</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>    preddata,</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">color=</span><span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> grid,<span class="at">y =</span> upr),</span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>    preddata,</span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">color=</span><span class="st">"red"</span>)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-brcaLogLinPred3" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-brcaLogLinPred3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-LineareRegressie_files/figure-html/fig-brcaLogLinPred3-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-brcaLogLinPred3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figuur&nbsp;7.11: Scatterplot voor log2-S100A8 expressie in functie van de log2-ESR1 expressie met model voorspellingen en 95<span class="math inline">\(\%\)</span> betrouwbaarheidsintervallen en 95<span class="math inline">\(\%\)</span> predictie-intervallen. Rode lijn: predictie interval, grijze band: betrouwbaarheidsinterval, zwarte lijn: lineair model
</figcaption>
</figure>
</div>
</div>
</div>
<!---break-->
<section id="nhanes-voorbeeld" class="level3" data-number="7.8.1">
<h3 data-number="7.8.1" class="anchored" data-anchor-id="nhanes-voorbeeld"><span class="header-section-number">7.8.1</span> NHANES voorbeeld</h3>
<iframe width="560" height="315" src="https://www.youtube.com/embed/JCkCskNuYn8" frameborder="0" style="display: block; margin: auto;" allow="autoplay; encrypted-media" allowfullscreen="">
</iframe>
<p>Aangezien een predictie-interval een verbeterde versie is van een referentie-interval bij ongekend populatie gemiddelde en de standaardafwijking, kunnen we a.d.h.v. de <code>lm(.)</code> functie referentie-intervallen beter vervangen door predictie-intervallen. Het PI zal eveneens de onzekerheid meenemen op de parameterschattingen (gemiddelde en standard error).</p>
<ul>
<li><p>Vergelijk referentie-interval voor cholesterolgehalte met predictie interval.</p></li>
<li><p>Referentie-interval</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(NHANES)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>fem <span class="ot">&lt;-</span> NHANES <span class="sc">|&gt;</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Gender<span class="sc">==</span><span class="st">"female"</span><span class="sc">&amp;!</span><span class="fu">is.na</span>(DirectChol))</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span><span class="sc">^</span>(</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>  fem <span class="sc">|&gt;</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(DirectChol) <span class="sc">|&gt;</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">log2</span>() <span class="sc">|&gt;</span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mean</span>() <span class="sc">+</span></span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>) <span class="sc">*</span></span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">qnorm</span>(<span class="fl">0.975</span>) <span class="sc">*</span></span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>    (fem <span class="sc">|&gt;</span></span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>      <span class="fu">pull</span>(DirectChol) <span class="sc">|&gt;</span></span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a>      <span class="fu">log2</span>() <span class="sc">|&gt;</span></span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a>      <span class="fu">sd</span>())</span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8361311 2.4397130</code></pre>
</div>
</div>
<ul>
<li>Predictie interval</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>lmChol <span class="ot">&lt;-</span> <span class="fu">lm</span>(DirectChol <span class="sc">|&gt;</span> <span class="fu">log2</span>() <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data=</span>fem)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>predInt <span class="ot">&lt;-</span> <span class="fu">predict</span>(</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  lmChol,</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">interval=</span><span class="st">"prediction"</span>,</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">newdata=</span><span class="fu">data.frame</span>(<span class="at">noPred=</span><span class="dv">1</span>)</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="dv">2</span><span class="sc">^</span>predInt,<span class="dv">2</span>)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   fit  lwr  upr
1 1.43 0.84 2.44</code></pre>
</div>
</div>
<p>Merk op dat het voorspellingsinterval bijna gelijk is aan het referentie-interval voor de grote steekproef. We konden de parameters inderdaad heel precies schatten.</p>
<p>We zullen hetzelfde doen voor een kleine steekproef van 10 patiënten.</p>
<ul>
<li>Referentie interval</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>fem10 <span class="ot">&lt;-</span> NHANES <span class="sc">|&gt;</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Gender<span class="sc">==</span><span class="st">"female"</span><span class="sc">&amp;!</span><span class="fu">is.na</span>(DirectChol)) <span class="sc">|&gt;</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sample_n</span>(<span class="at">size=</span><span class="dv">10</span>)</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span><span class="sc">^</span>(</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>  fem10 <span class="sc">|&gt;</span></span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pull</span>(DirectChol) <span class="sc">|&gt;</span></span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">log2</span>() <span class="sc">|&gt;</span></span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mean</span>() <span class="sc">+</span></span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>      <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>) <span class="sc">*</span></span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a>      <span class="fu">qnorm</span>(<span class="fl">0.975</span>) <span class="sc">*</span></span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a>      (fem10 <span class="sc">|&gt;</span></span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a>        <span class="fu">pull</span>(DirectChol) <span class="sc">|&gt;</span></span>
<span id="cb36-15"><a href="#cb36-15" aria-hidden="true" tabindex="-1"></a>        <span class="fu">log2</span>() <span class="sc">|&gt;</span></span>
<span id="cb36-16"><a href="#cb36-16" aria-hidden="true" tabindex="-1"></a>        <span class="fu">sd</span>())</span>
<span id="cb36-17"><a href="#cb36-17" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8976012 2.2571645</code></pre>
</div>
</div>
<p>Het referentie-interval is veel smaller dan in de grote steekproef.</p>
<ul>
<li>Predictie interval</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>lmChol10 <span class="ot">&lt;-</span> <span class="fu">lm</span>(DirectChol <span class="sc">|&gt;</span> <span class="fu">log2</span>() <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> fem10)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>predInt10 <span class="ot">&lt;-</span> <span class="fu">predict</span>(</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  lmChol10,</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">interval =</span> <span class="st">"prediction"</span>,</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">noPred=</span><span class="dv">1</span>)</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="dv">2</span><span class="sc">^</span>predInt10, <span class="dv">2</span>)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   fit  lwr  upr
1 1.42 0.81 2.49</code></pre>
</div>
</div>
<ul>
<li><p>Merk op dat het PI nu onzekerheid meeneemt in parameterschatters (gemiddelde en standaard error). En dat het interval veel breder wordt! Dit is hier vooral belangrijk voor de bovengrens omdat we de gegevens terug hebben getransformeerd!</p></li>
<li><p>Het interval is bijna net zo breed als dat gebaseerd op de grote steekproef.</p></li>
<li><p>Bij kleine steekproeven is het erg belangrijk om met deze extra onzekerheid rekening te houden.</p></li>
</ul>
</section>
</section>
<section id="sec-linAnova" class="level2" data-number="7.9">
<h2 data-number="7.9" class="anchored" data-anchor-id="sec-linAnova"><span class="header-section-number">7.9</span> Kwadratensommen en Anova-tabel</h2>
<iframe width="560" height="315" src="https://www.youtube.com/embed/kVWfeCOnhJM" frameborder="0" style="display: block; margin: auto;" allow="autoplay; encrypted-media" allowfullscreen="">
</iframe>
<p>In deze sectie bespreken we de constructie van kwadratensommen die typisch in een tabel worden gegeven en die behoren tot de klassieke presentatiewijze van een regressie-analyse. De tabel wordt de variantie-analyse tabel of anova tabel genoemd.</p>
<p>De <strong>totale kwadratensom</strong> is gelijk aan</p>
<p><span class="math display">\[\text{SSTot} = \sum_{i=1}^n (Y_i-\bar{Y})^2.\]</span></p>
<p>Het is de som van de kwadratische afwijkingen van de observaties rond het steekproefgemiddelde <span class="math inline">\(\bar Y\)</span>. Deze kwadratensom kan worden gebruikt om de variantie te schatten van de <strong>marginale distributie</strong> van de uitkomsten.</p>
<ul>
<li>In dit hoofdstuk wordt de focus hoofdzakelijk gelegd op de <strong>conditionele distributie</strong> van <span class="math inline">\(Y\vert X=x\)</span>.</li>
<li>We weten reeds dat MSE een schatter is van de variantie van de conditionele distributie van <span class="math inline">\(Y\vert X=x\)</span>.</li>
<li>De <strong>marginale distributie</strong> van <span class="math inline">\(Y\)</span> is de verdeling van <span class="math inline">\(Y\)</span> wanneer we geen rekening houden met de waarde voor de predictor <span class="math inline">\(X\)</span>. Het heeft als gemiddelde <span class="math inline">\(E[Y]\)</span> wat geschat wordt door het steekproefgemiddelde <span class="math inline">\(\bar{Y}\)</span> en een variantie <span class="math inline">\(\text{var}[Y]\)</span> die geschat kan worden aan de hand van <span class="math inline">\(\frac{\text{SSTot}}{n-1}\)</span>, de steekproefvariantie van <span class="math inline">\(Y\)</span> (zie Sectie <a href="04-DataExploratie.html#sec-spreiding" class="quarto-xref"><span>5.3.2</span></a>).</li>
</ul>
<p>Een grafische interpretatie van SSTot wordt weergegeven in Figuur <a href="#fig-brcaLogSSR" class="quarto-xref"><span>7.13</span></a>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>brca <span class="sc">|&gt;</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">y =</span> log2S100A8, <span class="at">x =</span> log2ESR1)) <span class="sc">+</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="fu">aes</span>(<span class="at">yintercept =</span> <span class="fu">mean</span>(log2S100A8))) <span class="sc">+</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="fu">aes</span>(<span class="at">x =</span> log2ESR1, <span class="at">xend =</span> log2ESR1, <span class="at">y=</span>log2S100A8,</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>                   <span class="at">yend =</span><span class="fu">mean</span>(log2S100A8)), <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"ESR1 expressie (log2)"</span>) <span class="sc">+</span></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"S100A8 expressie (log2)"</span>)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-brcaLogSSTot" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-brcaLogSSTot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-LineareRegressie_files/figure-html/fig-brcaLogSSTot-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-brcaLogSSTot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figuur&nbsp;7.12: Interpretatie van de totale kwadratensom (SSTot): de som van de kwadratische afwijkingen rond het steekproefgemiddelde.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Daarnaast kunnen we eveneens een tweede kwadratensom definiëren: de <strong>kwadratensom van de regressie, SSR,</strong> die een maat is voor de variabiliteit die verklaard kan worden door de regressie. Het is de som van de kwadratische afwijkingen van de voorspelde response <span class="math inline">\(\hat{Y}_i\)</span><a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> rond het steekproefgemiddelde <span class="math inline">\(\bar Y\)</span>.</p>
<p>De kwadratensom van de regressie is gelijk aan</p>
<p><span class="math display">\[\text{SSR} = \sum_{i=1}^n (\hat{Y}_i - \bar{Y})^2 = \sum_{i=1}^n (\hat{g}(x_i) - \bar{Y})^2.\]</span></p>
<p>SSR is een maat voor de afwijking tussen de predicties op de geschatte regressierechte en het steekproefgemiddelde van de uitkomsten. Het kan ook geïnterpreteerd worden als een maat voor de afwijking tussen de geschatte regressierechte <span class="math inline">\(\hat{g}(x)=\hat\beta_0+\hat\beta_1x\)</span> en een “geschatte regressierechte” waarbij de regressor geen effect heeft op de gemiddelde uitkomst. Deze laatste is dus eigenlijk een schatting van de regressierechte <span class="math inline">\(g(x)=\beta_0\)</span>, waarin <span class="math inline">\(\beta_0\)</span> geschat wordt door <span class="math inline">\(\bar{Y}\)</span>. Anders geformuleerd: SSR meet de grootte van het regressie-effect zodat <span class="math inline">\(\text{SSR} \approx 0\)</span> duidt op geen effect van de regressor en <span class="math inline">\(\text{SSR}&gt;0\)</span> duidt op een effect van de regressor. We voelen reeds aan dat <span class="math inline">\(\text{SSR}\)</span> zal kunnen worden gebruikt voor het ontwikkelen van een statistische test die de associatie tussen <span class="math inline">\(X\)</span> en <span class="math inline">\(Y\)</span> evalueert.</p>
<p>Een grafische interpretatie van SSR wordt weergegeven in Figuur <a href="#fig-brcaLogSSR" class="quarto-xref"><span>7.13</span></a>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>lm2_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">log2S100A8 =</span> brca<span class="sc">$</span>log2S100A8, <span class="at">fitted =</span> lm2<span class="sc">$</span>fitted.values, <span class="at">log2ESR1 =</span> brca<span class="sc">$</span>log2ESR1)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>brca <span class="sc">|&gt;</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span> log2ESR1, <span class="at">y =</span> log2S100A8)) <span class="sc">+</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x=</span>log2ESR1, <span class="at">y =</span>lm2<span class="sc">$</span>fitted), <span class="at">pch =</span> <span class="dv">2</span>, <span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>,<span class="at">size=</span><span class="fl">0.6</span>, <span class="at">color =</span> <span class="st">"red"</span>)  <span class="sc">+</span></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="fu">aes</span>(<span class="at">yintercept =</span> <span class="fu">mean</span>(log2S100A8))) <span class="sc">+</span></span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="at">data =</span> lm2_df, <span class="fu">aes</span>(<span class="at">x =</span> log2ESR1, <span class="at">xend =</span> log2ESR1,</span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">y =</span> fitted, <span class="at">yend =</span>  <span class="fu">mean</span>(log2S100A8)), <span class="at">lty =</span><span class="dv">2</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"S100A8 expressie (log2)"</span>) <span class="sc">+</span></span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"ESR1 expressie (log2)"</span>)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-brcaLogSSR" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-brcaLogSSR-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-LineareRegressie_files/figure-html/fig-brcaLogSSR-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-brcaLogSSR-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figuur&nbsp;7.13: Interpretatie van de kwadratensom van de regressie (SSR): de som van de kwadratische afwijkingen tussen de geschatte regressierechte en het steekproefgemiddelde van de uitkomsten.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Tenslotte herhalen we de <strong>kwadratensom van de fout</strong>:</p>
<p><span class="math display">\[ \text{SSE} = \sum_{i=1}^n (Y_i-\hat{Y}_i )^2 = \sum_{i=1}^n \left\{Y_i-\hat{g}\left(x_i\right)\right\}^2.\]</span></p>
<p>Van SSE weten we reeds dat het een maat is voor de afwijking tussen de observaties en de predicties bij de geobserveerde <span class="math inline">\(x_i\)</span> uit de steekproef. Hoe kleiner SSE, hoe beter de fit (schatting) van de regressierechte voor predictiedoeleinden. We hebben deze immers geminimaliseerd om tot de kleinste kwadratenschatters te komen.</p>
<p>Een interpretatie van SSE voor het log-log model wordt weergegeven in Figuur <a href="#fig-brcaLogSSE" class="quarto-xref"><span>7.14</span></a>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>brca <span class="sc">|&gt;</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span> log2ESR1, <span class="at">y =</span> log2S100A8)) <span class="sc">+</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x=</span>log2ESR1, <span class="at">y =</span>lm2<span class="sc">$</span>fitted), <span class="at">pch =</span> <span class="dv">2</span>, <span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>,<span class="at">size=</span><span class="fl">0.6</span>, <span class="at">color =</span> <span class="st">"red"</span>)  <span class="sc">+</span></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="at">data =</span> lm2_df, <span class="fu">aes</span>(<span class="at">x =</span> log2ESR1, <span class="at">xend =</span> log2ESR1,</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">y =</span> fitted, <span class="at">yend =</span>  log2S100A8), <span class="at">lty =</span><span class="dv">2</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"S100A8 expressie (log2)"</span>) <span class="sc">+</span></span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"ESR1 expressie (log2)"</span>)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-brcaLogSSE" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-brcaLogSSE-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-LineareRegressie_files/figure-html/fig-brcaLogSSE-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-brcaLogSSE-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figuur&nbsp;7.14: Interpretatie van de kwadratensom van de error (SSE): de som van de kwadratische afwijkingen tussen uitkomsten en de predicties op de geschatte regressierechte.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Verder kan worden aangetoond dat de totale kwadratensom als volgt kan ontbonden worden</p>
<p><span class="math display">\[\begin{eqnarray*}
  \text{SSTot}
    &amp;=&amp;  \sum_{i=1}^n (Y_i-\bar{Y})^2 \\
    &amp;=&amp;  \sum_{i=1}^n (Y_i-\hat{Y}_i+\hat{Y}_i-\bar{Y})^2 \\
    &amp;=&amp;  \sum_{i=1}^n (Y_i-\hat{Y}_i)^2+\sum_{i=1}^n(\hat{Y}_i-\bar{Y})^2 \\
    &amp;=&amp;  \text{SSE }+\text{SSR}  
\end{eqnarray*}\]</span></p>
<p>Merk op dat de dubbel product term wegvalt. Er kan aangetoond worden dat deze gelijk is aan nul. Dat valt buiten het bestek van deze cursus. De ontbinding van de totale kwadratensom kan als volgt worden geïnterpreteerd: De totale variabiliteit in de data (SSTot) wordt gedeeltelijk verklaard door het regressieverband (SSR). De variabiliteit die niet door het regressieverband verklaard wordt, is de residuele variabiliteit (SSE).</p>
<!---break-->
<section id="determinatie-coëfficiënt" class="level3" data-number="7.9.1">
<h3 data-number="7.9.1" class="anchored" data-anchor-id="determinatie-coëfficiënt"><span class="header-section-number">7.9.1</span> Determinatie-coëfficiënt</h3>
<iframe width="560" height="315" src="https://www.youtube.com/embed/JGT-pwIjgaY" frameborder="0" style="display: block; margin: auto;" allow="autoplay; encrypted-media" allowfullscreen="">
</iframe>
<p>De <strong>determinatiecoëfficiënt</strong> wordt gedefinieerd door</p>
<p><span class="math display">\[ R^2 = 1-\frac{\text{SSE}}{\text{SSTot}}=\frac{\text{SSR}}{\text{SSTot}}.\]</span></p>
<p>Het is dus <em>de fractie van de totale variabiliteit in de steekproef-uitkomsten die verklaard wordt door het geschatte regressieverband</em>.</p>
<p>Een grote <span class="math inline">\(R^2\)</span> is meestal een indicatie dat het model potentieel tot goede predicties kan leiden (kleine SSE), maar de waarde van <span class="math inline">\(R^2\)</span> is slechts in beperkte mate indicatief voor de p-waarde van de test <span class="math inline">\(H_0:\beta_1=0\)</span> vs <span class="math inline">\(H_1:\beta_1\neq0\)</span>.</p>
<ul>
<li>De p-waarde wordt immers sterk beïnvloed door SSE, maar niet door SSTot. Ook de steekproefgrootte n heeft een grote invloed op de p-waarde.</li>
<li>De determinatiecoëfficiënt <span class="math inline">\(R^2\)</span> wordt door SSE en SSTot bepaald, maar niet door de steekproefgrootte n.</li>
</ul>
<p><span class="math inline">\(R^2\)</span> vormt een maat voor de <em>predictieve waarde</em> van de verklarende variabele. Dat wil zeggen dat ze uitdrukt hoe goed de verklarende variabele de uitkomst voorspelt. <span class="math inline">\(R^2\)</span> is steeds gelegen tussen <span class="math inline">\(0\)</span> en <span class="math inline">\(1\)</span>. Een waarde gelijk aan 1 geeft aan dat er geen residuele variatie is rond de regressielijn en dat de uitkomst dus een perfect lineaire relatie met de predictor vertoont. Analoog impliceert een <span class="math inline">\(R^2\)</span> waarde van 0 dat er geen associatie is tussen de uitkomst en de predictor.</p>
<p>Vaak wordt er verkeerdelijk beweerd dat een lineair regressiemodel slecht is wanneer de determinatiecoëfficiënt klein is (bvb. <span class="math inline">\(R^2=0.2\)</span>). Wanneer het doel van de studie erin bestaat om de uitkomst te voorspellen o.b.v. verklarende variabele, dan is een hoge <span class="math inline">\(R^2\)</span> inderdaad vereist omdat er bij een lage waarde veel variabiliteit op de uitkomsten overblijft, die niet wordt opgevangen door de verklarende variabele. Wanneer het doel van de studie er echter in bestaat om het effect van een blootstelling op de uitkomst te bepalen, dan is een lineair regressiemodel goed zodra het correct de associatie beschrijft tussen de uitkomst enerzijds en de blootstelling anderzijds. Wanneer blootstelling zwak geassocieerd zijn met de uitkomst, dan wordt een kleine <span class="math inline">\(R^2\)</span>-waarde verwacht, zelfs wanneer een correct regressiemodel wordt gebruikt.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm2)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log2S100A8 ~ log2ESR1, data = brca)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.94279 -0.66537  0.08124  0.68468  1.92714 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   23.401      1.603   14.60 3.57e-15 ***
log2ESR1      -1.615      0.150  -10.76 8.07e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.026 on 30 degrees of freedom
Multiple R-squared:  0.7942,    Adjusted R-squared:  0.7874 
F-statistic: 115.8 on 1 and 30 DF,  p-value: 8.07e-12</code></pre>
</div>
</div>
<p>In de output voor het borstkankervoorbeeld zien we een <span class="math inline">\(R^2\)</span>=0.79 en kunnen we besluiten dat 79% van de variabiliteit in de <span class="math inline">\(\log_2\)</span>-S100A8 expressie kan worden verklaard door de <span class="math inline">\(\log_2\)</span>-ESR1 expressie-waarden.</p>
</section>
<section id="f-testen-in-het-enkelvoudig-lineair-regressiemodel" class="level3" data-number="7.9.2">
<h3 data-number="7.9.2" class="anchored" data-anchor-id="f-testen-in-het-enkelvoudig-lineair-regressiemodel"><span class="header-section-number">7.9.2</span> F-Testen in het enkelvoudig lineair regressiemodel</h3>
<p>De kwadratensommen vormen de basis van een belangrijke klasse van hypothesetesten. De <span class="math inline">\(F\)</span>-teststatistiek wordt gedefinieerd als</p>
<p><span class="math display">\[  F  = \frac{\text{MSR}}{\text{MSE}}\]</span></p>
<p>met</p>
<p><span class="math display">\[\text{MSR} = \frac{\text{SSR}}{1} \text{ en } \text{MSE} = \frac{\text{SSE}}{n-2}.\]</span></p>
<p>MSR wordt de gemiddelde kwadratensom van de regressie genoemd. De noemers 1 en <span class="math inline">\(n-2\)</span> zijn de vrijheidsgraden van SSR en SSE. Ze kan worden gebruikt om de nulhypothese <span class="math inline">\(H_0: \beta_1=0\)</span>, dat er geen associatie is tussen de uitkomst (response) en de blootstelling (predictor) te evalueren t.o.v de alternatieve hypothese <span class="math inline">\(H_1: \beta_1\neq0\)</span>.</p>
<p>Onder <span class="math inline">\(H_0: \beta_1=0\)</span> volgt de teststatistiek</p>
<p><span class="math display">\[H_0:F = \frac{\text{MSR}}{\text{MSE}} \sim F_{1,n-2},\]</span></p>
<p>een F-verdeling met 1 vrijheidsgraad in de teller en n-2 vrijheidsgraden in de noemer.</p>
<p>De teststatistiek kan enkel gebruikt worden voor het testen tegenover <span class="math inline">\(H_1:\beta_1\neq 0\)</span> (tweezijdig alternatief), waarvoor de <span class="math inline">\(p\)</span>-waarde gegeven wordt door</p>
<p><span class="math display">\[  p = P_0\left[F\geq f\right]=1-F_F(f;1,n-2),\]</span></p>
<p>de kans onder de nulhypothese<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a> om een test statistiek F te bekomen die ten minste zo extreem is<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a> als de waarde f die werd geobserveerd in de steekproef, <span class="math inline">\(F_F(.;1,n-2)\)</span> de cumulatieve distributie is van een F-verdeling met 1 vrijheidsgraad in de teller en n-2 vrijheidsgraden in de noemer. De kritieke waarde op het <span class="math inline">\(\alpha\)</span> significantieniveau is <span class="math inline">\(F_{1,n-2;1-\alpha}\)</span>.</p>
</section>
<section id="anova-tabel" class="level3" data-number="7.9.3">
<h3 data-number="7.9.3" class="anchored" data-anchor-id="anova-tabel"><span class="header-section-number">7.9.3</span> Anova Tabel</h3>
<p>De kwadratensommen en de F-test worden meestal in een zogenaamde variantie-analyse tabel of een anova tabel gerapporteerd.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 14%">
<col style="width: 29%">
<col style="width: 10%">
<col style="width: 11%">
<col style="width: 19%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Df</th>
<th style="text-align: left;">Sum Sq</th>
<th style="text-align: left;">Mean Sq</th>
<th style="text-align: left;">F value</th>
<th style="text-align: left;">Pr(&gt;F)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Regressie</td>
<td style="text-align: left;">vrijheidsgraden SSR</td>
<td style="text-align: left;">SSR</td>
<td style="text-align: left;">MSR</td>
<td style="text-align: left;">f-statistiek</td>
<td style="text-align: left;">p-waarde</td>
</tr>
<tr class="even">
<td style="text-align: left;">Error</td>
<td style="text-align: left;">vrijheidsgraden SSE</td>
<td style="text-align: left;">SSE</td>
<td style="text-align: left;">MSE</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
</div>
</div>
<p>De anovatabel voor het borstkanker voorbeeld kan als volgt in de R-software worden bekomen</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(lm2)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: log2S100A8
          Df  Sum Sq Mean Sq F value   Pr(&gt;F)    
log2ESR1   1 121.814 121.814   115.8 8.07e-12 ***
Residuals 30  31.559   1.052                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>We besluiten dus dat er een extreem significant lineair verband is tussen de <span class="math inline">\(\log_2\)</span> ESR1 expressie en de <span class="math inline">\(\log_2\)</span> S100A8 expressie. De <span class="math inline">\(F\)</span>-test is tweezijdig. Door te kijken naar het teken van <span class="math inline">\(\hat\beta_1\)</span> (<span class="math inline">\(\hat\beta_1=-1.615\)</span>) kunnen we tevens besluiten dat er een negatieve associatie is tussen beiden. Merk op dat de <span class="math inline">\(p\)</span>-waarde van de <span class="math inline">\(F\)</span>-test en de <span class="math inline">\(p\)</span>-waarde van de tweezijdige <span class="math inline">\(t\)</span>-test exact gelijk zijn. Voor het enkelvoudig lineair regressie-model zijn beide testen equivalent!</p>
</section>
</section>
<section id="sec-linDummy" class="level2" data-number="7.10">
<h2 data-number="7.10" class="anchored" data-anchor-id="sec-linDummy"><span class="header-section-number">7.10</span> Dummy variabelen</h2>
<iframe width="560" height="315" src="https://www.youtube.com/embed/HTSlZimXkdw" frameborder="0" style="display: block; margin: auto;" allow="autoplay; encrypted-media" allowfullscreen="">
</iframe>
<p>Het lineaire regressiemodel kan ook gebruikt worden voor het vergelijken van twee gemiddelden. In het Borstkanker voorbeeld kunnen we bijvoorbeeld nagaan of er een verschil is in de gemiddelde leeftijd van de patiënten met onaangetaste lymfeknopen en patiënten waarvan de lymfeknopen werden verwijderd.</p>
<p>Hiervoor definiëren we eerst een <em>dummy</em> variabele</p>
<p><span class="math display">\[x_i = \left\{ \begin{array}{ll}
1 &amp; \text{aangetaste lymfeknopen} \\
0 &amp; \text{onaangetaste lymfeknopen} \end{array}\right.\]</span></p>
<p>De groep met <span class="math inline">\(x_i=0\)</span> wordt de <strong>referentiegroep</strong> genoemd. Het regressiemodel blijft ongewijzigd,</p>
<p><span class="math display">\[Y_i = \beta_0 + \beta_1 x_i +\epsilon_i\]</span></p>
<p>met <span class="math inline">\(\epsilon_i \text{ iid } N(0,\sigma^2)\)</span><a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a>.</p>
<p>Gezien <span class="math inline">\(x_i\)</span> slechts twee waarden kan aannemen, is het eenvoudig om het regressiemodel voor beide waarden van <span class="math inline">\(x_i\)</span> afzonderlijk te bekijken:</p>
<p><span class="math display">\[\begin{array}{lcll}
   Y_i &amp;=&amp; \beta_0 +\epsilon_i &amp;\text{onaangetaste lymfeknopen} (x_i=0) \\
   Y_i &amp;=&amp; \beta_0 + \beta_1 +\epsilon_i &amp;\text{ aangetaste lymfeknopen} (x_i=1) .
\end{array}\]</span></p>
<p>Dus</p>
<p><span class="math display">\[\begin{eqnarray*}
   E\left[Y_i\mid x_i=0\right] &amp;=&amp; \beta_0 \\
   E\left[Y_i\mid x_i=1\right] &amp;=&amp; \beta_0 + \beta_1,
\end{eqnarray*}\]</span></p>
<p>waaruit direct de interpretatie van <span class="math inline">\(\beta_1\)</span> volgt:</p>
<p><span class="math display">\[   \beta_1 = E\left[Y_i\mid x_i=1\right]-E\left[Y_i\mid x_i=0\right]\]</span></p>
<p><span class="math inline">\(\beta_1\)</span> is dus het gemiddelde verschil in leeftijd tussen patiënten met aangetaste lymfeknopen en patiënten met onaangetaste lymfeknopen (referentiegroep).</p>
<p>Met de notatie <span class="math inline">\(\mu_1= E\left[Y_i\mid x_i=0\right]\)</span> en <span class="math inline">\(\mu_2= E\left[Y_i\mid x_i=1\right]\)</span> wordt dit</p>
<p><span class="math display">\[\beta_1 = \mu_2-\mu_1.\]</span><a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a></p>
<p>Er kan aangetoond worden dat</p>
<p><span class="math display">\[\begin{array}{ccll}
\hat\beta_0
   &amp;=&amp; \bar{Y}_1&amp;\text{ (steekproefgemiddelde in referentiegroep)} \\
\hat\beta_1
   &amp;=&amp; \bar{Y}_2-\bar{Y}_1&amp;\text{(schatter van effectgrootte)} \\
\text{MSE}
   &amp;=&amp; S_p^2 .
\end{array}\]</span></p>
<p>De testen voor <span class="math inline">\(H_0:\beta_1=0\)</span> vs.&nbsp;<span class="math inline">\(H_1:\beta_1\neq0\)</span> kunnen gebruikt worden voor het testen van de nulhypothese van de two-sample <span class="math inline">\(t\)</span>-test, <span class="math inline">\(H_0:\mu_1=\mu_2\)</span> t.o.v. <span class="math inline">\(H_1:\mu_1\neq\mu_2\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>brca<span class="sc">$</span>node<span class="ot">=</span><span class="fu">as.factor</span>(brca<span class="sc">$</span>node)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>lm3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(age<span class="sc">~</span>node,brca)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(age <span class="sc">~</span> node, brca, <span class="at">var.equal=</span><span class="cn">TRUE</span>)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  age by node
t = -2.7988, df = 30, p-value = 0.008879
alternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0
95 percent confidence interval:
 -15.791307  -2.467802
sample estimates:
mean in group 0 mean in group 1 
       59.94737        69.07692 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm3)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = age ~ node, data = brca)

Residuals:
     Min       1Q   Median       3Q      Max 
-19.9474  -5.3269   0.0526   5.3026  18.0526 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   59.947      2.079  28.834  &lt; 2e-16 ***
node1          9.130      3.262   2.799  0.00888 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 9.063 on 30 degrees of freedom
Multiple R-squared:  0.207, Adjusted R-squared:  0.1806 
F-statistic: 7.833 on 1 and 30 DF,  p-value: 0.008879</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(lm3)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-brcaLymf" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-brcaLymf-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-LineareRegressie_files/figure-html/fig-brcaLymf-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-brcaLymf-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figuur&nbsp;7.15: Diagnostische plot voor het model waarbij leeftijd wordt gemodelleerd a.d.h.v. een dummy variabele voor factor lymfe knoop status.
</figcaption>
</figure>
</div>
</div>
</div>
<p>We zien in de R output dat de output van de t-test en het lineaire model met 1 dummy variabele identieke resultaten geeft voor de test statistiek en de p-waarde. We zien eveneens een heel significante associatie tussen de leeftijd en de lymfe node status (p=0.009). De leeftijd van personen met aangetaste lymfeknopen is gemiddeld 9.1 jaar hoger dan die van patiënten zonder aantasting van de lymfeknopen.</p>
<p><strong>Let op</strong>: We kunnen echter niet besluiten dat oudere personen een hoger risico hebben op aantasting van de lymfeknopen ten gevolge van hun leeftijd. Aangezien de studie een observationele studie is, kunnen de groepen patiënten met aangetaste lymfeknopen en niet-aangetaste lymfeknopen nog in andere karateristieken van elkaar verschillen. We kunnen dus enkel besluiten dat er een associatie is tussen de lymfeknoop status en de leeftijd. Het is dus niet noodzakelijkerwijs een causaal verband! Het is immers steeds <strong>moeilijk om causale verbanden</strong> te trekken op basis van <strong>observationele studies</strong> gezien <strong>confounding</strong> kan optreden. We hebben de patiënten immers niet kunnen randomiseren over de twee groepen, de lymfeknoopstatus werd niet geïnduceerd door de onderzoekers maar enkel geobserveerd en we kunnen daarom niet garanderen dat de patiënten enkel verschillen in de lymfeknoopstatus!</p>
<p>Hetzelfde geldt voor het lineair model voor de <span class="math inline">\(\log_2\)</span>-S100A8-expressie. Aangezien we de ESR1-expressie niet experimenteel vast hebben kunnen leggen, kunnen we niet besluiten dat een hogere ESR1-expressie de S100A8-expressie doet verlagen. We hebben beide genexpressies enkel geobserveerd dus kunnen we alleen besluiten dat ze negatief geassocieerd zijn met elkaar. Om te evalueren of de expressie van een bepaald gen de expressie van ander genen beïnvloedt, gaat men vaak knockout constructen generenen in het labo, dat zijn mutanten die een bepaald gen niet tot expressie kunnen brengen. Wanneer de wild type (normale genotype) en de knockout dan onder identieke condities worden opgegroeid in het lab, weten onderzoekers dat verschillen in genexpressie worden geïnduceerd door de afwezigheid van de expressie van het knockout gen. Experimentele studies zijn immers essentieel om causale verbanden te kunnen trekken.</p>
<p><strong>Veronderstellingen:</strong> We moeten echter ook nog de veronderstellingen van het model voor de leeftijd nagaan! In Figuur <a href="#fig-brcaLymf" class="quarto-xref"><span>7.15</span></a> zien we geen afwijkingen van normaliteit in de QQ-plot. Er lijkt echter wel een aanwijzing dat de variantie in beide groepen verschillend is. De residuen lijken meer gespreid in de groep met lagere gemiddelde leeftijd (node=0) dan in de groep met een hogere gemiddelde leeftijd (node=1).<br>
Merk echter ook op dat er een verschil is in het aantal observaties in beide groepen. Wanneer we een boxplot maken, zoals we ook deden in het hoofdstuk <a href="05-StatistischeBesluitvorming.html" class="quarto-xref"><span>6</span></a> om gelijkheid van variantie na te gaan bij het uitvoeren van een t-test, zien we dat het verschil in interkwartiel afstand (IQR, boxgrootes) niet zo groot is (Figuur <a href="#fig-boxNode" class="quarto-xref"><span>7.16</span></a>). Als we data simuleren die <span class="math inline">\(iid\)</span> normaal verdeeld zijn en deze at random opsplitsen in twee groepen die gelijk zijn in grootte als die voor de lymfeknoop status (19 vs 13 patiënten) zien we dat een dergelijk verschil in IQR gerust kan voorkomen door toeval (Figuur <a href="#fig-boxSim" class="quarto-xref"><span>7.17</span></a>). We kunnen dus besluiten dat aan alle aannames is voldaan voor de statistische besluitvorming en dat we de R-output van het statistisch model voor de response age i.f.v de dummy variabele voor de node-status mogen gebruiken om conclusies te formuleren over de associatie tussen leeftijd en node status (zie hoger).</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>brca <span class="sc">|&gt;</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> node<span class="sc">|&gt;</span><span class="fu">as.factor</span>(), <span class="at">y =</span> age)) <span class="sc">+</span></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"node"</span>)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-boxNode" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-boxNode-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-LineareRegressie_files/figure-html/fig-boxNode-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-boxNode-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figuur&nbsp;7.16: boxplot van de leeftijd vs lymfeknoop status in de borstkanker dataset.
</figcaption>
</figure>
</div>
</div>
</div>
<ol type="1">
<li>Simulate 9 datasets with the same number of observations as the brca dataset from a normal distribution with the same standard deviation as in the original data. Store the data of all simulations in a data frame</li>
<li>Plot the simulated data using the <code>ggplot</code> function</li>
<li>Add a boxplot layer</li>
<li>Use facet_wrap to make a separate plot for simulated dataset</li>
<li>Change label of y axis</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">354</span>)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>sim_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">node =</span> <span class="fu">rep</span>(brca<span class="sc">$</span>node, <span class="dv">9</span>),</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">iid =</span> <span class="fu">rnorm</span>(<span class="dv">9</span> <span class="sc">*</span> <span class="fu">nrow</span>(brca), <span class="at">sd =</span> <span class="fu">sigma</span>(lm3)),</span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">sim =</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>, <span class="at">each =</span> <span class="dv">32</span>)</span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>sim_df <span class="sc">|&gt;</span></span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> node, <span class="at">y=</span>iid)) <span class="sc">+</span></span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(.<span class="sc">~</span>sim) <span class="sc">+</span></span>
<span id="cb53-11"><a href="#cb53-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="fu">paste0</span>(<span class="st">"iid N(0,"</span>,<span class="fu">round</span>(<span class="fu">sigma</span>(lm3)<span class="sc">^</span><span class="dv">2</span>,<span class="dv">2</span>),<span class="st">")"</span>))</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-boxSim" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-boxSim-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-LineareRegressie_files/figure-html/fig-boxSim-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-boxSim-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figuur&nbsp;7.17: Simulatie van normaal verdeelde gegevens met gelijk gemiddelde en variantie. Zoals in de borstkanker dataset zijn er 19 observaties in ene groep en 13 observaties in de andere groep. We zien dat er door puur toeval een behoorlijk verschil kan optreden in de IQR tussen beide groepen in de steekproef.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Zoals we illustreerden is het steeds nuttig om simulaties te gebruiken om te leren inschatten wanneer de diagnostische plots duiden op een afwijking van de voorwaarden.</p>


<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-sotiriou2006" class="csl-entry" role="listitem">
Sotiriou, Christos, Pratyaksha Wirapati, Sherene Loi, e.a. 2006. <span>‘Gene expression profiling in breast cancer: understanding the molecular basis of histologic grade to improve prognosis.’</span> <em>Journal of the National Cancer Institute</em> (Functional Genomics; Translational Research Unit, Universite Libre de Bruxelles, Brussels, Belgium. christos.sotiriou@bordet.be) 98 (4): 262-72. <a href="https://doi.org/10.1093/jnci/djj052">https://doi.org/10.1093/jnci/djj052</a>.
</div>
</div>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>In de cursus zullen we naar Y refereren met de term afhankelijke variable, response variabele of uitkomst, wat 3 synoniemen zijn<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Analoog aan het conditionele gemiddelde <span class="math inline">\(E(Y|X=x)\)</span>, geeft <span class="math inline">\(\text{var}(Y\vert X=x) = \sigma^2\)</span> de variantie weer op de uitkomsten voor de subgroep van de studiepopulatie bestaande uit subjecten met een ESR1 gen expressie gelijk aan <span class="math inline">\(x\)</span>.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>die zoals reeds geargumenteerd numeriek gelijk zijn aan de gemiddelde uitkomst<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>in de predictorpunten <span class="math inline">\(X_i\)</span> die werden geobserveerd in de steekproef<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>Vandaar <span class="math inline">\(P_0\)</span> waarbij subscript 0 aangeeft dat het een kans is onder <span class="math inline">\(H_0\)</span><a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>Hier groter of gelijk aan<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>Merk op dat iid staat voor independent and identically distributed of onafhankelijk en gelijk verdeeld<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>Noot: de indexen 1 en 2 mogen gerust vervangen worden door 0 en 1 om explicieter naar <span class="math inline">\(x_i=0\)</span> en <span class="math inline">\(x_1=1\)</span> te verwijzen; dan wordt <span class="math inline">\(\beta_1=\mu_1-\mu_0\)</span><a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Gekopieerd!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Gekopieerd!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./05-StatistischeBesluitvorming.html" class="pagination-link" aria-label="Statistische besluitvorming">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Statistische besluitvorming</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./07-VariantieAnalyse.html" class="pagination-link" aria-label="Variantie analyse">
        <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Variantie analyse</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/statOmics/statistiek2deBach/edit/main/06-LineareRegressie.qmd" class="toc-action"><i class="bi bi-github"></i>Pagina bewerken</a></li></ul></div></div></div></footer></body></html>