<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="nl" xml:lang="nl"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Basiscursus Statistiek voor de 2de Bachelor of Science in de Biologie, - in de Biochemie &amp; de Biotechnologie, - in de Biomedische Wetenschappen, en - in de Chemie">

<title>9&nbsp; Niet-parametrische statistiek – Cursus Statistiek 2026-2027</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./09-CategorischeDataAnalyse.html" rel="next">
<link href="./07-VariantieAnalyse.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-5ccb035bea26c1e21f80f44cf7c27909.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Geen resultaten",
    "search-matching-documents-text": "Gevonden documenten",
    "search-copy-link-title": "Kopieer link om te zoeken",
    "search-hide-matches-text": "Extra overeenkomsten verbergen",
    "search-more-match-text": "meer overeenkomst in dit document",
    "search-more-matches-text": "meer overeenkomsten in dit document",
    "search-clear-button-title": "Wissen",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Annuleren",
    "search-submit-button-title": "Verzenden",
    "search-label": "Zoeken"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Schakel zijbalknavigatie" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./08-NietParametrischeStatistiek.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Niet-parametrische statistiek</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Schakel zijbalknavigatie" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Zoeken" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Cursus Statistiek 2026-2027</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/statOmics/statistiek2deBach" title="Broncode" class="quarto-navigation-tool px-1" aria-label="Broncode"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Download" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Download"><i class="bi bi-download"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="./Statistiek_2026_2027.pdf">
              <i class="bi bi-file-pdf pe-1"></i>
            Download PDF
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="./Statistiek_2026_2027.epub">
              <i class="bi bi-journal pe-1"></i>
            Download ePub
            </a>
          </li>
      </ul>
    </div>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Zoeken"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Cursus Statistiek 2026-2027</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-Inleiding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Inleiding</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-Concepten.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Belangrijke concepten &amp; conventies</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-Proefopzet.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Studiedesign</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-DataExploratie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Data exploratie en beschrijvende statistiek</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-StatistischeBesluitvorming.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Statistische besluitvorming</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-LineareRegressie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Enkelvoudige lineaire regressie</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-VariantieAnalyse.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Variantie analyse</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-NietParametrischeStatistiek.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Niet-parametrische statistiek</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-CategorischeDataAnalyse.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Categorische data analyse</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-GeneralLinearModel.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Algemeen lineair model</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-ModelSelectie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Modelselectie</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">References</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Inhoudsopgave</h2>
   
  <ul>
  <li><a href="#inleiding" id="toc-inleiding" class="nav-link active" data-scroll-target="#inleiding"><span class="header-section-number">9.1</span> Inleiding</a></li>
  <li><a href="#vergelijken-van-twee-groepen" id="toc-vergelijken-van-twee-groepen" class="nav-link" data-scroll-target="#vergelijken-van-twee-groepen"><span class="header-section-number">9.2</span> Vergelijken van twee groepen</a>
  <ul class="collapse">
  <li><a href="#cholestorol-voorbeeld" id="toc-cholestorol-voorbeeld" class="nav-link" data-scroll-target="#cholestorol-voorbeeld"><span class="header-section-number">9.2.1</span> Cholestorol voorbeeld</a></li>
  <li><a href="#permutatietesten" id="toc-permutatietesten" class="nav-link" data-scroll-target="#permutatietesten"><span class="header-section-number">9.2.2</span> Permutatietesten</a></li>
  <li><a href="#rank-testen" id="toc-rank-testen" class="nav-link" data-scroll-target="#rank-testen"><span class="header-section-number">9.2.3</span> Rank Testen</a></li>
  <li><a href="#wilcoxon-mann-whitney-test" id="toc-wilcoxon-mann-whitney-test" class="nav-link" data-scroll-target="#wilcoxon-mann-whitney-test"><span class="header-section-number">9.2.4</span> Wilcoxon-Mann-Whitney Test</a></li>
  <li><a href="#conclusie-cholestorol-voorbeeld" id="toc-conclusie-cholestorol-voorbeeld" class="nav-link" data-scroll-target="#conclusie-cholestorol-voorbeeld"><span class="header-section-number">9.2.5</span> Conclusie Cholestorol Voorbeeld</a></li>
  </ul></li>
  <li><a href="#vergelijken-van-g-behandelingen" id="toc-vergelijken-van-g-behandelingen" class="nav-link" data-scroll-target="#vergelijken-van-g-behandelingen"><span class="header-section-number">9.3</span> Vergelijken van <span class="math inline">\(g\)</span> Behandelingen</a>
  <ul class="collapse">
  <li><a href="#dmh-voorbeeld" id="toc-dmh-voorbeeld" class="nav-link" data-scroll-target="#dmh-voorbeeld"><span class="header-section-number">9.3.1</span> DMH Voorbeeld</a></li>
  <li><a href="#kruskal-wallis-rank-test" id="toc-kruskal-wallis-rank-test" class="nav-link" data-scroll-target="#kruskal-wallis-rank-test"><span class="header-section-number">9.3.2</span> Kruskal-Wallis Rank Test</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/statOmics/statistiek2deBach/edit/main/08-NietParametrischeStatistiek.qmd" class="toc-action"><i class="bi bi-github"></i>Pagina bewerken</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Niet-parametrische statistiek</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Alle kennisclips die in dit hoofdstuk zijn verwerkt kan je in deze youtube playlist vinden:</p>
<ul>
<li><a href="https://www.youtube.com/playlist?list=PLZH1hP8_LbJJyR4mqLOxDwwOzysbhaFm1">Kennisclips Hoofdstuk 8 Niet-parametrische Statistiek</a></li>
</ul>
<p>Link naar webpage/script die wordt gebruik in de kennisclips:</p>
<ul>
<li><a href="https://statomics.github.io/sbc/rmd/08-NonparametericStatistics.html">script Hoofdstuk 8</a></li>
</ul>
<section id="inleiding" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="inleiding"><span class="header-section-number">9.1</span> Inleiding</h2>
<iframe width="560" height="315" src="https://www.youtube.com/embed/x0qBWoUpT00" frameborder="0" style="display: block; margin: auto;" allow="autoplay; encrypted-media" allowfullscreen="">
</iframe>
<p>Alle methoden die in de vorige hoofdstukken behandeld werden, zijn zogenaamde parametrische methoden. Deze term duidt erop dat de geldigheid van de inferentie enkel correct is als er voldaan is aan parametrische veronderstellingen. Dit zijn voornamelijk de distributionele veronderstellingen, zoals dat de observaties normaal verdeeld zijn. Andere voorbeelden van een parametrische veronderstelling zijn de gelijkheid van varianties bij de two-sample <span class="math inline">\(t\)</span>-test en ANOVA en de lineariteit van een regressiemodel.</p>
<p>Wanneer we over statistische besluitvorming spreken, is bijvoorbeeld de <span class="math inline">\(p\)</span>-waarde van een statistische test, of de probabilistische interpretatie van een betrouwbaarheidsinterval enkel correct interpreteerbaar onder bepaalde veronderstellingen:</p>
<ul>
<li><p>De <span class="math inline">\(p\)</span>-waarde is de kans dat de teststatistiek <span class="math inline">\(T\)</span> onder de nulhypothese meer extreem is dan de waargenomen waarde <span class="math inline">\(t\)</span> (gegeven dat <span class="math inline">\(H_0\)</span> waar is). Die kans wordt berekend op basis van de nuldistributie van <span class="math inline">\(T\)</span>. Deze distributie wordt bij parametrische testen afgeleid door te steunen op veronderstellingen over de verdeling van de observaties. Indien er niet voldaan is aan deze veronderstellingen, is de berekende <span class="math inline">\(p\)</span>-waarde fout. Dit betekent dat de conclusies die op <span class="math inline">\(p\)</span> gebaseerd worden, eveneens mogelijks fout kunnen zijn.</p></li>
<li><p>De berekening van bv. een <span class="math inline">\(95\%\)</span> betrouwbaarheidsinterval steunt eveneens op distributionele veronderstellingen. Als er niet voldaan is aan de veronderstellingen, is er geen garantie meer dat de berekende intervallen de (correcte) interpretatie hebben dat dergelijke intervallen de juiste parameterwaarde omvatten met <span class="math inline">\(95\%\)</span> kans.</p></li>
</ul>
<p>Asymptotische theorie is misschien moeilijker te plaatsen onder parametrisch of niet-parametrisch. Je zou kunnen stellen dat bv. een <span class="math inline">\(t\)</span>-test asymptotisch niet-parametrisch is, omdat bij erg grote steekproefgroottes de distributionele veronderstelling van normaliteit niet meer belangrijk is.</p>
<p>De reden waarom we in deze cursus een focus hebben op parametrische methoden is omdat ze efficiënter en meer flexibel zijn wanneer er aan de voorwaarden voldaan is. Efficiëntie betekent dat bij een constante steekproefgrootte de testen een grotere power hebben en dat de betrouwbaarheidsintervallen smaller zijn. Met meer flexibel bedoelen we dat het eenvoudiger is om de methoden in te zetten voor experimenten met meer complexe designs. Als er niet voldaan is aan de veronderstellingen van de parameterische methoden kunnen we voor bepaalde designs overschakelen naar niet-parametrische methoden die in deze situatie nog steeds formeel geldig zijn.</p>
</section>
<section id="vergelijken-van-twee-groepen" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="vergelijken-van-twee-groepen"><span class="header-section-number">9.2</span> Vergelijken van twee groepen</h2>
<iframe width="560" height="315" src="https://www.youtube.com/embed/2gkuOjD_Trc" frameborder="0" style="display: block; margin: auto;" allow="autoplay; encrypted-media" allowfullscreen="">
</iframe>
<section id="cholestorol-voorbeeld" class="level3" data-number="9.2.1">
<h3 data-number="9.2.1" class="anchored" data-anchor-id="cholestorol-voorbeeld"><span class="header-section-number">9.2.1</span> Cholestorol voorbeeld</h3>
<p>In een studie werd de cholesterolconcentratie in het bloed gemeten bij 5 patiënten (groep=1) die twee dagen geleden een hartaanval hadden en bij 5 gezonde personen (groep=2). De onderzoekers wensen na te gaan of de cholesterolconcentratie verschillend is bij hartpatiënten en gezonde personen. Boxplots en qqplots van de data worden weergegeven in Figuur <a href="#fig-cholBox" class="quarto-xref"><span>9.1</span></a> en <a href="#fig-cholQQ" class="quarto-xref"><span>9.2</span></a>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>chol <span class="ot">&lt;-</span> <span class="fu">read_tsv</span>(<span class="st">"https://raw.githubusercontent.com/statOmics/sbc/master/data/chol.txt"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>chol <span class="ot">&lt;-</span> chol <span class="sc">|&gt;</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">group =</span> <span class="fu">as.factor</span>(group))</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>nGroups <span class="ot">&lt;-</span> chol <span class="sc">|&gt;</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(group) <span class="sc">|&gt;</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">table</span>()</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> nGroups <span class="sc">|&gt;</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>()</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>chol</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 2
   group cholest
   &lt;fct&gt;   &lt;dbl&gt;
 1 1         244
 2 1         206
 3 1         242
 4 1         278
 5 1         236
 6 2         188
 7 2         212
 8 2         186
 9 2         198
10 2         160</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>chol <span class="sc">|&gt;</span>  </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>group,<span class="at">y=</span>cholest)) <span class="sc">+</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">outlier.shape=</span><span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">position=</span><span class="st">"jitter"</span>)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-cholBox" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cholBox-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="08-NietParametrischeStatistiek_files/figure-html/fig-cholBox-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cholBox-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figuur&nbsp;9.1: Boxplot van de cholesterol concentratie in het bloed bij hartpatiënten (groep 1) en gezonde individuen (groep 2).
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>chol <span class="sc">|&gt;</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">sample=</span>cholest)) <span class="sc">+</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_qq</span>() <span class="sc">+</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_qq_line</span>() <span class="sc">+</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>group)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-cholQQ" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cholQQ-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="08-NietParametrischeStatistiek_files/figure-html/fig-cholQQ-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cholQQ-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figuur&nbsp;9.2: Qqplot van de cholesterol concentratie in het bloed bij hartpatiënten (groep 1) en gezonde individuen (groep 2).
</figcaption>
</figure>
</div>
</div>
</div>
<p>De boxplots en qqplots geven aan dat er mogelijks outliers in de data voorkomen. Het is moeilijk om inzicht te krijgen in de verdeling van de data gezien we maar 5 observaties hebben per groep.</p>
</section>
<section id="permutatietesten" class="level3" data-number="9.2.2">
<h3 data-number="9.2.2" class="anchored" data-anchor-id="permutatietesten"><span class="header-section-number">9.2.2</span> Permutatietesten</h3>
<p>De vraagstelling van het cholesterol voorbeeld is geformuleerd in erg ruime bewoordingen en dit laat vrijheid in de vertaling ervan naar een nulhypothese.</p>
<p>Laten we starten met een nulhypothese in termen van gemiddelden. Stel dat <span class="math inline">\(\mu_1\)</span> en <span class="math inline">\(\mu_2\)</span> de gemiddelde uitkomsten in behandelingsgroep 1 (hartpatiënten) en 2 (gezonde personen) voorstellen, dan zouden de hypotheses kunnen zijn:</p>
<p><span class="math display">\[H_0: \mu_1=\mu_2 \text{ versus } H_1: \mu_1\neq \mu_2.\]</span></p>
<p>Voor het testen van deze hypotheses kunnen we bijvoorbeeld gebruik maken van de two-sample <span class="math inline">\(t\)</span>-test.</p>
<p>We gaan de voorwaarden na:</p>
<ul>
<li>Normaliteit van de uitkomsten in de twee behandelingsgroepen. Met slechts 5 observaties in iedere groep, kan de veronderstelling niet nagegaan worden.</li>
<li>Gelijkheid van varianties. Met slechts 5 observaties in iedere groep, kan de veronderstelling niet nagegaan worden.</li>
</ul>
<p>We kunnen dus de veronderstellingen van de two-sample <span class="math inline">\(t\)</span>-test niet nagaan. We kunnen ook geen beroep doen op de asymptotische benadering omdat 5 observaties per groep te weinig is.</p>
<p>Samengevat: de veronderstellingen van de <span class="math inline">\(t\)</span>-test kunnen niet worden nagegaan en er zijn te weinig observaties om gebruik te kunnen maken van de asymptotische benadering. Aangezien het erg gevaarlijk is een statistische methode te gebruiken waarvan de voorwaarden niet nagegaan kunnen worden, is de klassieke <span class="math inline">\(t\)</span>-test niet de geschikte methode. De oplossing die in dit hoofdstuk besproken wordt, zijn permutatietesten. Om deze te kunnen beschrijven, zullen we eerst de nulhypothese anders formuleren.</p>
<section id="hypothesen" class="level4" data-number="9.2.2.1">
<h4 data-number="9.2.2.1" class="anchored" data-anchor-id="hypothesen"><span class="header-section-number">9.2.2.1</span> Hypothesen</h4>
<p>De oplossing die in deze sectie besproken wordt, zijn de permutatietesten. Om deze te kunnen beschrijven, zullen we eerst de nulhypothese anders formuleren.</p>
<p>De veronderstelling voor de two-sample <span class="math inline">\(t\)</span>-test kunnen we als volgt schrijven, met <span class="math inline">\(Y_{1j}\)</span> en <span class="math inline">\(Y_{2j}\)</span> de notatie voor de uitkomsten uit respectievelijk groep 1 en 2:</p>
<p><span class="math display">\[Y_{1j} \text{ iid } N(\mu_1,\sigma^2) \;\;\;\text{ en }\;\;\; Y_{2j} \text{ iid } N(\mu_2,\sigma^2).\]</span></p>
<p>Onder <span class="math inline">\(H_0:\mu_1=\mu_2\)</span>, wordt dit (stel <span class="math inline">\(\mu=\mu_1=\mu_2\)</span> onder <span class="math inline">\(H_0\)</span>)</p>
<p><span class="math display">\[ Y_{ij} \text{ iid } N(\mu,\sigma^2),\]</span></p>
<p>wat uitdrukt dat alle <span class="math inline">\(n=n_1+n_2\)</span> uitkomsten uit dezelfde normale distributie komen en onafhankelijk verdeeld zijn. Dit laat ons dus toe om de oorspronkelijke nulhypothese van de two-sample <span class="math inline">\(t\)</span>-test anders te schrijven:</p>
<p><span id="eq-H0F1F2"><span class="math display">\[
H_0: F_1(y) = F_2(y) \text{ voor alle } y \;\;\;\text{ of }\;\;\; H_0: f_1(y) = f_2(y) \text{ voor alle } y
\tag{9.1}\]</span></span></p>
<p>met <span class="math inline">\(F_1\)</span> en <span class="math inline">\(F_2\)</span> de distributiefuncties en <span class="math inline">\(f_1\)</span> en <span class="math inline">\(f_2\)</span> de densiteitfuncties van de verdeling van de uitkomsten in respectievelijk behandelingsgroep 1 en 2, en met de bijkomende veronderstelling dat <span class="math inline">\(f_1\)</span> en <span class="math inline">\(f_2\)</span> de distributiefuncties van Normale verdelingen zijn.</p>
<p>Onder de alternatieve hypothese wordt een locatie-shift verondersteld:</p>
<p><span class="math display">\[H_1: f_1(y)=f_2(y-\Delta) \;\;\;\text{ voor alle } y\]</span></p>
<p>met <span class="math inline">\(\Delta=\mu_1-\mu_2\)</span>, verder hebben de Normale verdelingen dezelfde variantie.</p>
<p>We illustreren dit in R voor <span class="math inline">\(f_1\sim N(0,1)\)</span> en <span class="math inline">\(f_2\sim N(1,1)\)</span> en <span class="math inline">\(\Delta=-1\)</span>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>mu1 <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>sigma1 <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>mu2 <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>sigma2 <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">2</span><span class="sc">:</span><span class="dv">2</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>delta <span class="ot">&lt;-</span> mu1 <span class="sc">-</span> mu2</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>delta</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dnorm</span>(y, mu1, sigma1)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.05399097 0.24197072 0.39894228 0.24197072 0.05399097</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dnorm</span>(y <span class="sc">-</span> delta, mu2, sigma2)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.05399097 0.24197072 0.39894228 0.24197072 0.05399097</code></pre>
</div>
</div>
<p>De permutatietesten die in de volgende sectie ontwikkeld worden, kunnen gebruikt worden voor het testen van de hypothese <a href="#eq-H0F1F2" class="quarto-xref"><span>9.1</span></a>, maar dan zonder de Normaliteitsveronderstelling.</p>
<p>We schrijven hypothese <a href="#eq-H0F1F2" class="quarto-xref"><span>9.1</span></a> verkort als</p>
<p><span class="math display">\[H_0: F_1=F_2 \;\;\;\text{ of }\;\;\; H_0:f_1=f_2.\]</span></p>
<p>Als de nulhypothese waar is, met name dat de verdelingen van de cholesterolconcentraties gelijk zijn voor hartpatiënten en gezonde personen, dan zijn de groep-labels van de 10 personen niet informatief. Gezien er geen verschil is in de verdeling tussen beide groepen is elke groepering immers irrelevant. We kunnen bijgevolg de verdeling van de test-statistiek onder de nulhypothese bekomen door de groepslabels <span class="math inline">\(G\)</span> te permuteren.</p>
</section>
<section id="verdeling-van-de-statistiek-onder-h_0" class="level4" data-number="9.2.2.2">
<h4 data-number="9.2.2.2" class="anchored" data-anchor-id="verdeling-van-de-statistiek-onder-h_0"><span class="header-section-number">9.2.2.2</span> Verdeling van de statistiek onder <span class="math inline">\(H_0\)</span></h4>
<p>In praktijk zijn er <span class="math inline">\(m=\binom{n_1+n_2}{n_1}=\binom{n}{n_1}=\binom{n}{n_2}\)</span> mogelijke unieke permutaties <span class="math inline">\(\cal{G}\)</span> van de groepslabels. Voor ons voorbeeld zijn dat er <span class="math inline">\(m=\)</span> 252. Als <span class="math inline">\(m\)</span> niet te groot is dan kunnen alle unieke permutaties van de groepslabels berekend worden. Voor iedere unique permutatie <span class="math inline">\(g \in \cal{G}\)</span> wordt de teststatistiek <span class="math inline">\(t^*_g\)</span> berekend<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>.</p>
<p>We kunnen alle m=252 permutaties in R genereren a.d.h.v. de functie <code>combn(n,n_1)</code>. Dit wordt geïllustreerd in de onderstaande R code:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>G <span class="ot">&lt;-</span> <span class="fu">combn</span>(n,nGroups[<span class="dv">1</span>])</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(G)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]   5 252</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>G[,<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>]</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]    1    1    1    1    1    1    1    1    1     1
[2,]    2    2    2    2    2    2    2    2    2     2
[3,]    3    3    3    3    3    3    3    3    3     3
[4,]    4    4    4    4    4    4    5    5    5     5
[5,]    5    6    7    8    9   10    6    7    8     9</code></pre>
</div>
</div>
<p>De matrix G bevat voor elke permutatie de volgnummers van de observaties die tot de eerste groep zullen behoren. We tonen enkel de eerste 10 permutaties. We kunnen nu de teststatistiek berekenen voor de originele steekproef en voor elke permutatie</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Originele test statistiek</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>tOrig<span class="ot">=</span><span class="fu">t.test</span>(cholest<span class="sc">~</span>group,chol)<span class="sc">$</span>statistic</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="co">#bereken alle permutatiecombinaties en voer voor</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="co">#elke combinantie een functie uit die de t-test statistiek</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="co">#berekent voor de gepermuteerde groepslabels</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>tOrig <span class="ot">&lt;-</span> <span class="fu">t.test</span>(cholest <span class="sc">~</span> group, chol)<span class="sc">$</span>statistic</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>tOrig</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       t 
3.664425 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>tStar <span class="ot">&lt;-</span> <span class="fu">combn</span>(</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  n,</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  nGroups[<span class="dv">1</span>],</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">function</span>(g,y) {</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">t.test</span>(y[g],y[<span class="sc">-</span>g])<span class="sc">$</span>statistic</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>    },</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> chol <span class="sc">|&gt;</span> <span class="fu">pull</span>(cholest)</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(tStar)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.6644253 1.6397911 2.3973923 1.5876250 1.9217173 0.9967105</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(tStar)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 252</code></pre>
</div>
</div>
<p>Merk op dat <code>y[g]</code> de data selecteert met volgnummers g uit de vector y en <code>y[-g]</code> de data waarvoor de volgnummers niet tot g behoren. De vector <code>tStar</code> bevat de waarden van de teststatistiek <span class="math inline">\(t^*_g\)</span> voor alle <span class="math inline">\(g \in {\cal{G}}\)</span>.</p>
<p>We kunnen nu de verdeling van de teststatistiek onder <span class="math inline">\(H_0\)</span> bestuderen.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qplot</span>(tStar,<span class="at">bins=</span><span class="dv">50</span>) <span class="sc">+</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="fu">expression</span>(<span class="st">"permutatiestatistiek t"</span><span class="sc">^</span><span class="st">"*"</span>)) <span class="sc">+</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept=</span>tOrig,<span class="at">col=</span><span class="dv">2</span>)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-tPermDist" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-tPermDist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="08-NietParametrischeStatistiek_files/figure-html/fig-tPermDist-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tPermDist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figuur&nbsp;9.3: Exacte permutatie nuldistributie van de Welch t-test voor het cholesterol voorbeeld. Bovenaan histogram van elke mogelijke waarde voor de test-statistiek. Onderaan een gewoon histogram met balkbreedtes gelijk aan 1. De geobserveerde waarde voor de test-statistiek is aangeduid met een rode verticale lijn.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Het histogram (Figuur <a href="#fig-tPermDist" class="quarto-xref"><span>9.3</span></a>) bevat alle informatie voor de permutatienuldistributie van de two-sample <span class="math inline">\(t\)</span>-teststatistiek voor de geobserveerde uitkomsten; merk op dat er 252 unieke waarden van de teststatistiek berekend zijn.<br>
Het histogram in Figuur <a href="#fig-tPermDist" class="quarto-xref"><span>9.3</span></a> is de verdeling van de teststatistiek onder de nulhypothese. We zien eveneens dat de geobserveerde teststatistiek vrij extreem is.</p>
</section>
<section id="p-waarde" class="level4" data-number="9.2.2.3">
<h4 data-number="9.2.2.3" class="anchored" data-anchor-id="p-waarde"><span class="header-section-number">9.2.2.3</span> p-waarde</h4>
<p>Nu we in staat zijn de permutatienuldistributie te berekenen, kunnen we hypothesetesten uitvoeren net als in de parametrische statistiek. Voor een permutatietest is de <span class="math inline">\(p\)</span>-waarde voor de tweezijdige test (immers <span class="math inline">\(H_1: \mu_1 \neq \mu_2\)</span>)</p>
<p><span class="math display">\[p=\text{P}_0\left[\vert T\vert \geq \vert t\vert \mid \mathbf{y}\right].\]</span></p>
<p>Merk op dat deze p-waarde geconditioneerd is op de geobserveerde cholesterolwaarden die weergegeven worden in de vector <span class="math inline">\(\mathbf{y}=(y_{11},\ldots,y_{51},y_{12},\ldots,y_{52})^T\)</span>.</p>
<p>Aangezien de permutatienuldistrubutie van <span class="math inline">\(T\)</span> bepaald wordt door <span class="math inline">\(t^*_g\)</span>, <span class="math inline">\(g \in{\cal{G}}\)</span>, berekenen we</p>
<p><span class="math display">\[p  = \text{P}_0\left[\left\vert T\right\vert \geq \left\vert t\right\vert \mid \mathbf{y}\right] = \frac{\#\{g\in {\cal{G}}: \vert t^*_g\vert \geq \vert t \vert \}}{m},\]</span></p>
<p>m.a.w. als de ratio van het aantal permutaties waarvoor de statistiek minstens even extreem is als de geobserveerde statistiek op het totaal aantal permutaties. In R kunnen we dit als volgt berekenen.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>pval <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">abs</span>(tStar)<span class="sc">&gt;=</span><span class="fu">abs</span>(tOrig))</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>pval</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.01587302</code></pre>
</div>
</div>
<p>We vinden dus een <span class="math inline">\(p\)</span>-waarde van 0.0159. Aangezien <span class="math inline">\(p&lt;5\%\)</span>, besluiten we op het <span class="math inline">\(5\%\)</span> significantieniveau dat de distributies van de cholesterol concentraties niet gelijk zijn bij hartpatiënten en bij gezonde personen. De <span class="math inline">\(p\)</span>-waarde die gevonden wordt via de permutatienuldistributie op basis van alle permutaties wordt een <strong>exacte</strong> <span class="math inline">\(p\)</span>-waarde genoemd. De permutatienuldistributie wordt een <strong>exacte</strong> nuldistributie genoemd. De term <strong>exact</strong> betekent dat de resultaten correct zijn voor iedere steekproefgrootte <span class="math inline">\(n\)</span>.</p>
<p>De kans op een type I fout wordt dus gecontroleerd door een permutatietest, maar wel conditioneel op de geobserveerde uitkomsten data <span class="math inline">\(\mathbf{y}\)</span>.</p>
<p>We hebben steeds geconditioneerd op de observaties van de steekproef. <strong>We kunnen ons nu afvragen of we de conclusies kunnen veralgemenen naar de populatie toe? Het antwoord is ja, als de subjecten at random getrokken zijn uit de populatie.</strong> Het bewijs hiervan valt buiten het bestek van de cursus.</p>
<p>Soms treedt er een praktisch probleem op omdat het aantal permutaties <span class="math inline">\(m=\#{\cal{G}}\)</span> erg groot is. Enkele voorbeelden: <span class="math inline">\(\binom{20}{10}=\)</span> 184756, <span class="math inline">\(\binom{30}{15}=\)</span> 1.55e+08 en <span class="math inline">\(\binom{40}{20}=\)</span> 1.38e+11.</p>
<p>Dus zelfs met slechts 40 observaties en een gebalanceerde proefopzet is het quasi onmogelijk om alle permutaties één voor één door te rekenen. De oplossing bestaat erin om niet alle <span class="math inline">\(g \in {\cal{G}}\)</span> te beschouwen, maar slechts een beperkt aantal (bv. 10000 of 100000). We kunnen m.a.w. de nuldistributie benaderen door een groot aantal random permutaties uit te voeren.</p>
</section>
<section id="hoe-kunnen-we-conclusie-interpreteren" class="level4" data-number="9.2.2.4">
<h4 data-number="9.2.2.4" class="anchored" data-anchor-id="hoe-kunnen-we-conclusie-interpreteren"><span class="header-section-number">9.2.2.4</span> Hoe kunnen we conclusie interpreteren</h4>
<p>We permuteren immers t statistiek. De effectgrootte in de t-test is de locatie-shift.</p>
<p>Als locatie-shift model niet opgaat is een significant resultaat moeilijk te interpreteren. Het is dan immers niet duidelijk tegenover welk alternatief we dan testen.</p>
<p>Locatie-shift kan niet worden nagegaan in kleine steekproeven…</p>
<!---break-->
</section>
</section>
<section id="rank-testen" class="level3" data-number="9.2.3">
<h3 data-number="9.2.3" class="anchored" data-anchor-id="rank-testen"><span class="header-section-number">9.2.3</span> Rank Testen</h3>
<iframe width="560" height="315" src="https://www.youtube.com/embed/6l3-IEfNSN8" frameborder="0" style="display: block; margin: auto;" allow="autoplay; encrypted-media" allowfullscreen="">
</iframe>
<p>De ontwikkeling van rank testen startte in de eerste helft van de twintigste eeuw, maar ze vormen vandaag nog steeds de belangrijkste groep van niet-parametrische testen. Aanvankelijk hadden ze hun populariteit te danken aan het feit dat ze niet-parametrisch zijn en dat ze exacte <span class="math inline">\(p\)</span>-waarden geven op basis van de permutatienuldistributie. In tegenstelling tot de test besproken in de vorige sectie, hebben rank testen geen nood aan het numeriek opstellen van de permutatienuldistributie voor iedere nieuwe dataset. De permutatienuldistributie van rank testen hangt alleen af van de steekproefgroottes. Bovendien zal blijken dat de testen erg robuust zijn tegen uitschieters (Engels: <em>outliers</em>) en dat ze nuttig zijn als het locatie-shift model niet opgaat.</p>
<p>Rank testen starten vanuit rank-getransformeerde uitkomsten.</p>
<div id="def-rank" class="theorem definition">
<p><span class="theorem-title"><strong>Definitie 9.1 (Rank)</strong></span> &nbsp;</p>
</div>
<p>Beschouw <span class="math inline">\(Y_1, \ldots, Y_n\)</span>. We veronderstellen voorlopig dat er geen twee gelijke observaties voorkomen (i.e.&nbsp;geen <em>ties</em>). De rank van observatie <span class="math inline">\(Y_i\)</span> wordt dan gedefinieerd als</p>
<p><span class="math display">\[\begin{equation*}
  R_i=R(Y_i) = \#\{Y_j: Y_j\leq Y_i; j=1,\ldots, n\}.
\end{equation*}\]</span></p>
<p>De kleinste observatie krijgt dus rank 1, de tweede kleinste rank 2, enzovoort, en de grootste observatie, tenslotte, krijgt rank <span class="math inline">\(n\)</span>.</p>
<p><strong>Einde Definitie</strong></p>
<p>De rank transformatie wordt geïllustreerd op basis van het cholesterol voorbeeld.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>chol <span class="sc">|&gt;</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(cholest)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 244 206 242 278 236 188 212 186 198 160</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>chol <span class="sc">|&gt;</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(cholest) <span class="sc">|&gt;</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rank</span>()</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1]  9  5  8 10  7  3  6  2  4  1</code></pre>
</div>
</div>
<p>Soms komen <em>ties</em> voor in de data, i.e.&nbsp;minstens twee observaties hebben dezelfde numerieke waarde. Een klein voorbeeld:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>metTies <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">403</span>, <span class="dv">507</span>, <span class="dv">507</span>, <span class="dv">610</span>, <span class="dv">651</span>, <span class="dv">651</span>, <span class="dv">651</span>, <span class="dv">830</span>, <span class="dv">900</span>)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>metTies <span class="sc">|&gt;</span> <span class="fu">rank</span>()</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.0 2.5 2.5 4.0 6.0 6.0 6.0 8.0 9.0</code></pre>
</div>
</div>
<p>De numerieke waarde 507 komt tweemaal voor en de numerieke waarde 651 komt driemaal voor. Dit zijn voorbeelden van <em>ties</em>. Wanneer <em>ties</em> voorkomen, wordt dikwijls de definitie van <em>midranks</em> toegepast voor de rank-transformatie.</p>
<div id="def-midrank" class="theorem definition">
<p><span class="theorem-title"><strong>Definitie 9.2 (Midrank)</strong></span> &nbsp;</p>
</div>
<p>Beschouw <span class="math inline">\(Y_1, \ldots, Y_n\)</span>. De <strong>midrank</strong> van observatie <span class="math inline">\(Y_i\)</span> wordt dan gedefinieerd als</p>
<p><span class="math display">\[\begin{eqnarray*}
  R_i &amp;=&amp; \frac{ \#\{Y_j: Y_j\leq Y_i\} + ( \#\{Y_j: Y_j &lt; Y_i\} +1)}{2}.
\end{eqnarray*}\]</span></p>
<p><strong>Einde Definitie</strong></p>
<p>In wat volgt hebben we dikwijls de ranks van de uitkomsten nodig in de gepoolde steekproef. Bijvoorbeeld: beschouw de uitkomsten <span class="math inline">\(Y_{ij}\)</span>, <span class="math inline">\(i=1,\ldots, n_j\)</span> en <span class="math inline">\(j=1,2\)</span>. Deze uitkomsten kunnen ook gerepresenteerd worden door <span class="math inline">\(Z_1,\ldots, Z_n\)</span> (<span class="math inline">\(n=n_1+n_2\)</span>), de uitkomsten uit de gepoolde steekproef.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t</span>(chol)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        [,1]  [,2]  [,3]  [,4]  [,5]  [,6]  [,7]  [,8]  [,9]  [,10]
group   "1"   "1"   "1"   "1"   "1"   "2"   "2"   "2"   "2"   "2"  
cholest "244" "206" "242" "278" "236" "188" "212" "186" "198" "160"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> chol <span class="sc">|&gt;</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(cholest)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>z</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 244 206 242 278 236 188 212 186 198 160</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rank</span>(z)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1]  9  5  8 10  7  3  6  2  4  1</code></pre>
</div>
</div>
<!---break-->
</section>
<section id="wilcoxon-mann-whitney-test" class="level3" data-number="9.2.4">
<h3 data-number="9.2.4" class="anchored" data-anchor-id="wilcoxon-mann-whitney-test"><span class="header-section-number">9.2.4</span> Wilcoxon-Mann-Whitney Test</h3>
<iframe width="560" height="315" src="https://www.youtube.com/embed/qInfzU97YLI" frameborder="0" style="display: block; margin: auto;" allow="autoplay; encrypted-media" allowfullscreen="">
</iframe>
<p>De test werd gelijktijdig ontwikkeld door Wilcoxon en door Mann en Whitney. Om deze reden wordt de test dikwijls de <strong>Wilcoxon-Mann-Whitney</strong> (WMW) test genoemd. Soms wordt de test ook de <strong>Wilcoxon rank sum test</strong> of de <strong>Mann-Whitney U test</strong> genoemd.</p>
<p>De test werd ontwikkeld voor het testen van de nulhypothese <a href="#eq-H0F1F2" class="quarto-xref"><span>9.1</span></a> tegenover het alternatief <span class="math inline">\(H_1: \mu_1\neq \mu_2\)</span> (of de eenzijdige versies). Eerst wordt er een distributionele veronderstelling gemaakt: het <strong>locatie-shift</strong> model, later relaxeren we deze aanname.</p>
<p>Stel dat <span class="math inline">\(Y_1\)</span> en <span class="math inline">\(Y_2\)</span> uitkomsten zijn uit respectievelijk de eerste en tweede behandelingsgroep, met respectievelijke verdelingen <span class="math inline">\(f_1\)</span> en <span class="math inline">\(f_2\)</span>. Het locatie-shift model geldt als er een <span class="math inline">\(\Delta\)</span> bestaat waarvoor geldt</p>
<p><span class="math display">\[f_1(y)=f_2(y-\Delta) \;\;\;\text{ voor alle } y.\]</span></p>
<p>Locatie-shift betekent dat <span class="math inline">\(f_1\)</span> en <span class="math inline">\(f_2\)</span> dezelfde vorm hebben, maar ze mogen over <span class="math inline">\(\Delta\)</span> verschoven zijn. De <span class="math inline">\(\Delta\)</span> uit de definitie heeft als interpretatie: <span class="math inline">\(\Delta = \mu_1-\mu_2\)</span>. Door locatie-shift aan te nemen, zal het verwerpen van <span class="math inline">\(H_0: f_1=f_2\)</span> de conclusie <span class="math inline">\(\mu_1\neq \mu_2\)</span> impliceren.</p>
<p>De klassieke two-sample <span class="math inline">\(t\)</span>-teststatistiek is gebouwd rond het verschil in steekproefgemiddelden <span class="math inline">\(\bar{Y}_1-\bar{Y}_2\)</span>. We beschouwen nu ook het verschil in steekproefgemiddelden, maar niet op basis van de oorspronkelijke uitkomsten, maar op basis van de rank-getransformeerde uitkomsten. De ranks zijn toegekend op basis van de gepoolde observaties (i.e.&nbsp;na samenvoegen van de uitkomsten uit groep 1 en groep 2); dus <span class="math inline">\(R_{ij}=R(Y_{ij})\)</span> is de rank van uitkomst <span class="math inline">\(Y_{ij}\)</span> in de gepoolde steekproef. Beschouw de teststatistiek</p>
<p><span class="math display">\[T = \frac{1}{n_1}\sum_{i=1}^{n_1} R(Y_{i1}) - \frac{1}{n_2}\sum_{i=1}^{n_2} R(Y_{i2}) .\]</span></p>
<p>De statistiek vergelijkt dus de gemiddelde rank in groep 1 met de gemiddelde rank in groep 2.</p>
<p>Dit is een zinvolle teststatistiek, want</p>
<ul>
<li><p>als <span class="math inline">\(H_0\)</span> waar is, dan verwachten we dat de gemiddelde rank in de eerste groep ongeveer gelijk is aan de gemiddelde rank in de tweede groep en dus verwachten we dat <span class="math inline">\(T\)</span> dicht bij nul ligt.</p></li>
<li><p>als <span class="math inline">\(H_1\)</span> waar is dan verwachten we dat de gemiddelde ranks zullen verschillen en dus dat <span class="math inline">\(T\)</span> niet dicht bij nul zal liggen.</p></li>
</ul>
<p>Er kan echter worden aangetoond dat het volstaat het om</p>
<p><span class="math display">\[S_1=\sum_{i=1}^{n_1} R(Y_{i1})\]</span></p>
<p>als teststatistiek te beschouwen. <span class="math inline">\(S_1\)</span> is de som van de ranks van de observaties uit de eerste behandelingsgroep; dit verklaart de naam <em>rank sum test</em>.</p>
<p><span class="math inline">\(S_1\)</span> en <span class="math inline">\(S_2\)</span> bevatten immers dezelfde informatie en zijn gerelateerd via</p>
<p><span class="math display">\[S_1+S_2 = \text{som van alle ranks} = 1+2+\cdots + n=\frac{1}{2}n(n+1).\]</span></p>
<p>Nu we weten dat <span class="math inline">\(S_1\)</span> (en <span class="math inline">\(S_2\)</span>) een goede teststatistiek is, kan de permutatietestmethode toegepast worden om de exacte permutatienuldistributie op te stellen en de test uit te voeren. Voor een gegeven steekproefgrootte <span class="math inline">\(n\)</span>, en veronderstellend dat er geen <em>ties</em> zijn, nemen de rank-getransformeerde uitkomsten altijd de waarden <span class="math inline">\(1, 2, \ldots, n\)</span> aan. Voor gegeven groepsgroottes <span class="math inline">\(n_1\)</span> en <span class="math inline">\(n_2\)</span>, zal de permutatienuldistributie dan ook steeds dezelfde zijn! In de vorige eeuw (tot ongeveer de jaren 1980) werd dit als een groot voordeel beschouwd omdat de nuldistributies voor gegeven <span class="math inline">\(n_1\)</span> en <span class="math inline">\(n_2\)</span> getabuleerd konden worden (belangrijke kwantielen werden als tabellen in boeken gepubliceerd zodat ze konden gebruikt worden voor het bepalen van kritische waarden en <span class="math inline">\(p\)</span>-waarden), waardoor de gebruiker geen nood had aan zware rekencapaciteit. Vandaag de dag speelt dit argument niet meer mee, maar toch blijven de rank testen erg populair, maar dan wel om andere, heel belangrijke redenen.</p>
<p>Niettegenstaande <span class="math inline">\(S_1\)</span> en <span class="math inline">\(S_2\)</span> perfect als teststatistieken gebruikt kunnen worden, wordt dikwijls gewerkt met de gestandaardiseerde teststatistiek</p>
<p><span class="math display">\[T = \frac{S_1-\text{E}_{0}\left[S_1\right]}{\sqrt{\text{Var}_{0}\left[S_1\right]}},\]</span></p>
<p>met <span class="math inline">\(\text{E}_{0}\left[S_1\right]\)</span> en <span class="math inline">\(\text{Var}_{0}\left[S_1\right]\)</span> de verwachtingswaarde en variantie van <span class="math inline">\(S_1\)</span> onder <span class="math inline">\(H_0\)</span>. Dit zijn dus het gemiddelde en variantie van de permutatienuldistributie van <span class="math inline">\(S_1\)</span>.</p>
<p>Onder <span class="math inline">\(H_0\)</span> geldt</p>
<p><span class="math display">\[\text{E}_{0}\left[S_1\right]= \frac{1}{2}n_1(n+1) \;\;\;\;\text{ en }\;\;\;\; \text{Var}_{0}\left[S_1\right]=\frac{1}{12}n_1n_2(n+1).\]</span></p>
<p>Verder kan men onder <span class="math inline">\(H_0\)</span> en als <span class="math inline">\(\min(n_1,n_2)\rightarrow \infty\)</span> opgaat aantonen dat,</p>
<p><span class="math display">\[T = \frac{S_1-\text{E}_{0}\left[S_1\right]}{\sqrt{\text{Var}_{0}\left[S_1\right]}} \rightarrow N(0,1).\]</span></p>
<p>Asymptotisch volgt de gestandaardiseerde teststatistiek dus een standaardnormaal verdeling.</p>
<p>We illustreren de WMW test aan de hand van de R functie <code>wilcox.test</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(cholest <span class="sc">~</span> group, <span class="at">data =</span> chol)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon rank sum exact test

data:  cholest by group
W = 24, p-value = 0.01587
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
</div>
<p>We zien dat we op basis van de test de nulhypothese kunnen verwerpen op het 5% significantie-niveau.</p>
<p>De output geeft de teststatistiek <span class="math inline">\(W=\)</span> 24. In volgende lijnen berekenen we <span class="math inline">\(S_1\)</span> en <span class="math inline">\(S_2\)</span> manueel voor de dataset.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>S1 <span class="ot">&lt;-</span> chol <span class="sc">|&gt;</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">cholRank=</span><span class="fu">rank</span>(cholest)) <span class="sc">|&gt;</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(group<span class="sc">==</span><span class="dv">1</span>) <span class="sc">|&gt;</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(cholRank) <span class="sc">|&gt;</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>()</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>S2 <span class="ot">&lt;-</span> chol <span class="sc">|&gt;</span></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">cholRank =</span> <span class="fu">rank</span>(cholest)) <span class="sc">|&gt;</span></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(group <span class="sc">==</span> <span class="dv">2</span>) <span class="sc">|&gt;</span></span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(cholRank) <span class="sc">|&gt;</span></span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>()</span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a>S1</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 39</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>S2</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 16</code></pre>
</div>
</div>
<p>Waar komt <span class="math inline">\(W=\)</span> 24 vandaan? Dit wordt zodadelijk toegelicht.</p>
<p>De teststatistieken <span class="math inline">\(S_1\)</span> en <span class="math inline">\(S_2\)</span> werden voorgesteld door Wilcoxon, maar tezelfdertijd werd een equivalente test voorgesteld door Mann en Whitney. Hun teststatistiek wordt gegeven door<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<p><span class="math display">\[U_1 = \sum_{i=1}^{n_1}\sum_{k=1}^{n_2} \text{I}\left\{Y_{i1}\geq Y_{k2}\right\}.\]</span></p>
<p>waarbij <span class="math inline">\(\text{I}\left\{.\right\}\)</span> een indicator is die 1 is als de uitdrukking waar is en 0 als dit niet het geval is. Er wordt voor elke observatie uit de eerste groep geteld hoeveel keer zij groter of gelijk is aan een observatie uit de tweede groep. We berekenen de Mann-Whitney statistiek nu manueel in R.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>y1 <span class="ot">&lt;-</span> chol <span class="sc">|&gt;</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(group<span class="sc">==</span><span class="dv">1</span>) <span class="sc">|&gt;</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(<span class="st">"cholest"</span>)</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>y2 <span class="ot">&lt;-</span> chol <span class="sc">|&gt;</span></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(group<span class="sc">==</span><span class="dv">2</span>) <span class="sc">|&gt;</span></span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(<span class="st">"cholest"</span>)</span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>u1Hlp <span class="ot">&lt;-</span> <span class="fu">sapply</span>(</span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a>  y1,</span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a>  <span class="cf">function</span>(y1i,y2) {y1i<span class="sc">&gt;=</span>y2},</span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">y2=</span>y2)</span>
<span id="cb42-13"><a href="#cb42-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-14"><a href="#cb42-14" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(u1Hlp) <span class="ot">&lt;-</span> y1</span>
<span id="cb42-15"><a href="#cb42-15" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(u1Hlp) <span class="ot">&lt;-</span> y2</span>
<span id="cb42-16"><a href="#cb42-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-17"><a href="#cb42-17" aria-hidden="true" tabindex="-1"></a>u1Hlp</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     244   206  242  278  236
188 TRUE  TRUE TRUE TRUE TRUE
212 TRUE FALSE TRUE TRUE TRUE
186 TRUE  TRUE TRUE TRUE TRUE
198 TRUE  TRUE TRUE TRUE TRUE
160 TRUE  TRUE TRUE TRUE TRUE</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>U1 <span class="ot">&lt;-</span> <span class="fu">sum</span>(u1Hlp)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>U1</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 24</code></pre>
</div>
</div>
<p>Er kan worden aangetoond dat</p>
<p><span class="math display">\[U_1 = S_1 - \frac{1}{2}n_1(n_1+1).\]</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>S1<span class="sc">-</span>nGroups[<span class="dv">1</span>]<span class="sc">*</span>(nGroups[<span class="dv">1</span>]<span class="sc">+</span><span class="dv">1</span>)<span class="sc">/</span><span class="dv">2</span></span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> 1 
24 </code></pre>
</div>
</div>
<p>Hieruit concluderen we (1) dat <span class="math inline">\(U_1\)</span> en <span class="math inline">\(S_1\)</span> dezelfde informatie bevatten, (2) dat <span class="math inline">\(U_1\)</span> ook een rankstatistiek is en dat exacte testen gebaseerd op <span class="math inline">\(U_1\)</span> en <span class="math inline">\(S_1\)</span> equivalent zijn.</p>
<p>De statistiek <span class="math inline">\(U_1\)</span> heeft als voordeel dat het een informatieve interpretatie heeft. Stel <span class="math inline">\(Y_j\)</span> een willekeurige uitkomst uit behandelingsgroep <span class="math inline">\(j\)</span> (<span class="math inline">\(j=1,2\)</span>). Dan geldt</p>
<p><span class="math display">\[\begin{eqnarray*}
  \frac{1}{n_1n_2}\text{E}\left[U_1\right]
     &amp;=&amp; \text{P}\left[Y_1 \geq Y_2\right].
\end{eqnarray*}\]</span></p>
<p>Intuïtief voelen we dit aan: Op basis van de steekproef kunnen we die kans schatten door het gemiddelde te berekenen van alle indicator waarden <span class="math inline">\(\text{I}\left\{Y_{i1}\geq Y_{k2}\right\}\)</span>. We voerden inderdaad <span class="math inline">\(n_1 \times n_2\)</span> vergelijkingen uit.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(u1Hlp)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.96</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>U1<span class="sc">/</span>(nGroups[<span class="dv">1</span>]<span class="sc">*</span>nGroups[<span class="dv">2</span>])</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   1 
0.96 </code></pre>
</div>
</div>
<p>De kans <span class="math inline">\(\text{P}\left[Y_1 \geq Y_2\right]\)</span> wordt een <strong>probabilistische index</strong> (Engels: <em>probabilistic index</em>) genoemd. Het is de kans dat een uitkomst uit de eerste groep groter of gelijk is dan een uitkomst uit de tweede groep. Als <span class="math inline">\(H_0\)</span> waar is, dan is <span class="math inline">\(\text{P}\left[Y_1 \geq Y_2\right]=\frac{1}{2}\)</span>.</p>
<p>De gestandaardiseerde Mann-Whitney statistiek is</p>
<p><span class="math display">\[T = \frac{U_1 - \frac{n_1n_2}{2}}{\sqrt{\frac{1}{12}n_1n_2(n+1)}}.\]</span></p>
<p>De R functie <code>wilcox.test</code> geeft niet de Wilcoxon rank sum statistiek, maar wel de Mann-Whitney statistiek <span class="math inline">\(U_1\)</span>. We weten echter dat exacte permutatietesten gebaseerd op <span class="math inline">\(U_1\)</span>, <span class="math inline">\(U_2\)</span>, <span class="math inline">\(S_1\)</span> of <span class="math inline">\(S_2\)</span> dezelfde resultaten geven. We bekijken nogmaals de output</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>wTest <span class="ot">&lt;-</span> <span class="fu">wilcox.test</span>(cholest<span class="sc">~</span>group, <span class="at">data =</span> chol)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>wTest</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon rank sum exact test

data:  cholest by group
W = 24, p-value = 0.01587
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>U1</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 24</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>probInd <span class="ot">&lt;-</span> wTest<span class="sc">$</span>statistic<span class="sc">/</span><span class="fu">prod</span>(nGroups)</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>probInd</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   W 
0.96 </code></pre>
</div>
</div>
<p>Aangezien <span class="math inline">\(p=\)</span> 0.0159 <span class="math inline">\(&lt;0.05\)</span> besluiten we op het <span class="math inline">\(5\%\)</span> significantieniveau dat de gemiddelde cholesterolconcentratie groter is bij hartpatiënten kort na een hartaanval dan bij gezonde personen. We nemen aan dat locatie-shift opgaat.</p>
<p>Nu we weten hoe <span class="math inline">\(U_1\)</span> berekend wordt, weten we ook meteen dat een cholesterolwaarde van hartpatiënten met een kans van <span class="math inline">\(U1/(n_1\times n_2)=\)</span> 96% groter is die van gezonde personen. Aangezien we het locatie-shift model veronderstellen, besluiten we ook dat de gemiddelde uitkomst uit de behandelingsgroep groter is dan de gemiddelde uitkomst uit de placebogroep.</p>
<p>We zouden de veronderstelling van de locatie-shift moeten nagaan, maar met slechts 5 observaties in elke behandelingsgroep is dit zinloos. Zonder verder theorie hierover te geven, geven we nog mee dat zonder de locatie-shift veronderstelling de conclusie in termen van de probabilistische index correct blijft en de conclusie ook zo zou moeten worden geformuleerd.</p>
<p>Dus wanneer we geen locatie-shift veronderstellen en een tweezijdige test uitvoeren testen we eigenlijk</p>
<p><span class="math display">\[H_0: F_1=F_2 \text{ vs P}(Y_1 \geq Y_2) \neq 0.5.\]</span></p>
</section>
<section id="conclusie-cholestorol-voorbeeld" class="level3" data-number="9.2.5">
<h3 data-number="9.2.5" class="anchored" data-anchor-id="conclusie-cholestorol-voorbeeld"><span class="header-section-number">9.2.5</span> Conclusie Cholestorol Voorbeeld</h3>
<p>Er is een significant verschil in de distributie van de cholesterolconcentraties bij hartpatiënten 2 dagen na hun hartaanval en gezonde individuen (<span class="math inline">\(p=\)</span> 0.0159). Het is meer waarschijnlijk om hogere cholesterolconcentraties te observeren bij hartpatiënten dan bij gezonde individuen. De puntschatting voor deze kans bedraagt 96%.</p>
</section>
</section>
<section id="vergelijken-van-g-behandelingen" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="vergelijken-van-g-behandelingen"><span class="header-section-number">9.3</span> Vergelijken van <span class="math inline">\(g\)</span> Behandelingen</h2>
<iframe width="560" height="315" src="https://www.youtube.com/embed/tio4b5GUTIk" frameborder="0" style="display: block; margin: auto;" allow="autoplay; encrypted-media" allowfullscreen="">
</iframe>
<p>In deze sectie veralgemenen we de methoden uit de vorige sectie. De methoden kunnen ook gezien worden als niet-parametrische tegenhangers van de <span class="math inline">\(F\)</span>-test uit een one-way ANOVA.</p>
<section id="dmh-voorbeeld" class="level3" data-number="9.3.1">
<h3 data-number="9.3.1" class="anchored" data-anchor-id="dmh-voorbeeld"><span class="header-section-number">9.3.1</span> DMH Voorbeeld</h3>
<p>Nieuwe (en bestaande) chemische substanties moeten getest worden op genotoxiciteit. De resultaten van genotoxiciteitstesten vormen de basis voor risico-analyses en de classificatie en labeling van chemische substanties in de EU (<em>Dangerous Substances Directive 67/548/EEC and Regulation (EC) No.&nbsp;1272/2008</em>). In dat kader werd een studie met 24 ratten opgezet voor het testen van de genotoxiciteit van 1,2-dimethylhydrazine dihydrochloride (DMH). De ratten werden at random verdeeld over vier groepen die een verschillende dagelijkse DMH dosis kregen toegediend (controle, laag, medium, hoog). Na drie weken werden de dieren afgemaakt en werd genotoxiciteit van DMH in de lever bepaald a.d.h.v. een comet assay waarbij DNA strengbreuken worden gevisualiseerd via gel electroforese. De lengte van de comet staart is een proxy voor het aantal strengbreuken. De onderzoekers wensen na te gaan of er verschillen zijn in de DNA schade tengevolge van de DMH dosis. Boxplots van de data worden weergegeven in Figuur <a href="#fig-dnaBox" class="quarto-xref"><span>9.4</span></a>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>dna <span class="ot">&lt;-</span> <span class="fu">read_delim</span>(<span class="st">"https://raw.githubusercontent.com/statOmics/sbc/master/data/dna.txt"</span>,<span class="at">delim=</span><span class="st">" "</span>)</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>dna <span class="ot">&lt;-</span> dna <span class="sc">|&gt;</span></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">dose =</span> <span class="fu">as.factor</span>(dna<span class="sc">$</span>dose))</span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>dna</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 24 × 3
   id    length dose 
   &lt;chr&gt;  &lt;dbl&gt; &lt;fct&gt;
 1 Rat1    19.3 0    
 2 Rat2    18.9 0    
 3 Rat3    18.6 0    
 4 Rat4    19.0 0    
 5 Rat5    17.1 0    
 6 Rat6    18.8 0    
 7 Rat7    55.4 1.25 
 8 Rat8    59.2 1.25 
 9 Rat9    59.1 1.25 
10 Rat10   52.1 1.25 
# ℹ 14 more rows</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>dna <span class="sc">|&gt;</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>dose,<span class="at">y=</span>length,<span class="at">fill=</span>dose))<span class="sc">+</span></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">position=</span><span class="st">"jitter"</span>)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-dnaBox" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-dnaBox-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="08-NietParametrischeStatistiek_files/figure-html/fig-dnaBox-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-dnaBox-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figuur&nbsp;9.4: Boxplot van de comet staart lengte in functie van de DMH dosis.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>dna <span class="sc">|&gt;</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">sample=</span>length)) <span class="sc">+</span></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_qq</span>() <span class="sc">+</span></span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_qq_line</span>() <span class="sc">+</span></span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>dose)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-dnaQQ" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-dnaQQ-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="08-NietParametrischeStatistiek_files/figure-html/fig-dnaQQ-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-dnaQQ-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figuur&nbsp;9.5: QQ-plots van de comet staart lengte per DMH dosis.
</figcaption>
</figure>
</div>
</div>
</div>
<p>De boxplots lijken een indicatie te geven dat de controle groep een andere variabiliteit heeft. Merk wel op dat er slechts 6 observaties zijn per groep wat eigenlijk te weinig is om de aannames na te gaan.</p>
<!---break-->
</section>
<section id="kruskal-wallis-rank-test" class="level3" data-number="9.3.2">
<h3 data-number="9.3.2" class="anchored" data-anchor-id="kruskal-wallis-rank-test"><span class="header-section-number">9.3.2</span> Kruskal-Wallis Rank Test</h3>
<iframe width="560" height="315" src="https://www.youtube.com/embed/9tZfMB37KFQ" frameborder="0" style="display: block; margin: auto;" allow="autoplay; encrypted-media" allowfullscreen="">
</iframe>
<p>De Kruskal-Wallis Rank Test (KW-test) is een niet-parametrisch alternatief voor de ANOVA F-test.</p>
<p>De klassieke <span class="math inline">\(F\)</span>-teststatistiek kan geschreven worden als</p>
<p><span class="math display">\[F = \frac{\text{SST}/(g-1)}{\text{SSE}/(n-g)} = \frac{\text{SST}/(g-1)}{(\text{SSTot}-\text{SST})/(n-g)} ,\]</span></p>
<p>met <span class="math inline">\(g\)</span> het aantal groepen.</p>
<p>Merk op dat SSTot enkel afhangt van de uitkomsten <span class="math inline">\(\mathbf{y}\)</span> en niet zal variëren bij permutaties. Het is dus eigenlijk voldoende om SST als teststatistiek te gebruiken. Ter herinnering: <span class="math inline">\(\text{SST}=\sum_{j=1}^g n_j(\bar{Y}_j-\bar{Y})^2\)</span>.</p>
<p>De KW teststatistiek maakt gebruik van SST maar dan gebaseerd op de rank-getransformeerde uitkomsten<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>,</p>
<p><span class="math display">\[\text{SST} = \sum_{j=1}^g n_j \left(\bar{R}_j - \bar{R}\right)^2 = \sum_{j=1}^g n_j \left(\bar{R}_j - \frac{n+1}{2}\right)^2 ,\]</span></p>
<p>met <span class="math inline">\(\bar{R}_j\)</span> het gemiddelde van de ranks in behandelingsgroep <span class="math inline">\(j\)</span>, en <span class="math inline">\(\bar{R}\)</span> het gemiddelde van alle ranks,</p>
<p><span class="math display">\[\bar{R} = \frac{1}{n}(1+2+\cdots + n) = \frac{1}{n}\frac{1}{2}n(n+1) = \frac{n+1}{2}.\]</span></p>
<p>De KW teststatistiek wordt gegeven door</p>
<p><span class="math display">\[KW = \frac{12}{n(n+1)}  \sum_{j=1}^g n_j \left(\bar{R}_j - \frac{n+1}{2}\right)^2.\]</span></p>
<p>De factor <span class="math inline">\(\frac{12}{n(n+1)}\)</span> zorgt ervoor dat <span class="math inline">\(KW\)</span> een eenvoudige asymptotische nuldistributie heeft. In het bijzonder, onder <span class="math inline">\(H_0\)</span>, als <span class="math inline">\(\min(n_1,\ldots, n_g)\rightarrow \infty\)</span>,</p>
<p><span class="math display">\[KW  \rightarrow \chi^2_{g-1}.\]</span></p>
<p>De exacte KW-test kan uitgevoerd worden via de berekening van de permutatienuldistributie (die enkel afhangt van <span class="math inline">\(n_1, \ldots, n_g\)</span>) voor het testen van</p>
<p><span class="math display">\[H_0: f_1=\ldots=f_g \text{ vs } H_1: \text{ minstens twee gemiddelden verschillend}.\]</span></p>
<p>Om toe te laten dat <span class="math inline">\(H_1\)</span> geformuleerd is in termen van gemiddelden, moet locatie-shift verondersteld worden. Indien locatie-shift niet opgaat, zou <span class="math inline">\(H_1\)</span> eigenlijk geformuleerd moeten worden in termen van probabilistische indexen:</p>
<p><span class="math display">\[H_0: f_1=\ldots=f_g \text{ vs } H_1: \exists\ j,k \in \{1,\ldots,g\} : \text{P}\left[Y_j\geq Y_k\right]\neq 0.5\]</span></p>
<section id="dna-schade-voorbeeld" class="level4" data-number="9.3.2.1">
<h4 data-number="9.3.2.1" class="anchored" data-anchor-id="dna-schade-voorbeeld"><span class="header-section-number">9.3.2.1</span> DNA Schade Voorbeeld</h4>
<p>Eerst analyseren we de data met de R functie <code>kruskal.test</code></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kruskal.test</span>(length <span class="sc">~</span> dose, <span class="at">data =</span> dna)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  length by dose
Kruskal-Wallis chi-squared = 14, df = 3, p-value = 0.002905</code></pre>
</div>
</div>
<p>De waarde van de KW teststatistiek is 14, met een <span class="math inline">\(p\)</span>-waarde van 0.00291. Dus op het <span class="math inline">\(5\%\)</span> significantieniveau kan de nulhypothese worden verworpen.</p>
<p>Het is belangrijk om op te merken dat de R-functie <code>kruskal.test</code> steeds de asymptotische benadering gebruikt voor de berekening van de <span class="math inline">\(p\)</span>-waarden. Met slechts 6 observaties per groep, is dit geen optimale benadering van de exacte <span class="math inline">\(p\)</span>-waarde! Met de <code>coin</code> R package kunnen we de exacte <span class="math inline">\(p\)</span>-waarde wel berekenen via het argument <code>distribution='exact'</code>of benaderen a.d.h.v. simulaties <code>distribution=approximate(B=100000)</code>, waarbij B het aantal permutaties is.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(coin)</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>kwPerm <span class="ot">&lt;-</span> <span class="fu">kruskal_test</span>(length <span class="sc">~</span> dose, <span class="at">data =</span> dna,</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">distribution =</span> <span class="fu">approximate</span>(<span class="at">nresample =</span> <span class="dv">100000</span>))</span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a>kwPerm</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Approximative Kruskal-Wallis Test

data:  length by dose (0, 1.25, 2.5, 5)
chi-squared = 14, p-value = 0.00047</code></pre>
</div>
</div>
<p>We kunnen besluiten dat er een extreem significant verschil is in distributie van de DNA schade ten gevolge van de dosis.</p>
<!---break-->
</section>
<section id="posthoc-analyse" class="level4" data-number="9.3.2.2">
<h4 data-number="9.3.2.2" class="anchored" data-anchor-id="posthoc-analyse"><span class="header-section-number">9.3.2.2</span> Posthoc Analyse</h4>
<iframe width="560" height="315" src="https://www.youtube.com/embed/9kcSwfVo82s" frameborder="0" style="display: block; margin: auto;" allow="autoplay; encrypted-media" allowfullscreen="">
</iframe>
<p>We vragen ons nu uiteraard af welke groepen verschillend zijn. Hiervoor dienen we een posthoc analyse uit te voeren met paarsgewijze niet-parametrische testen.</p>
<p>We kunnen dit bijvoorbeeld doen a.d.h.v Wilcoxon-Mann-Whitney testen.</p>
<ul>
<li>Dat is eigenlijk suboptimaal na KW-test want de data worden opnieuw gerangschikt!</li>
<li>KW gebaseerd over ranks bepaalde over alle groepen</li>
<li>WMW gebaseerd op ranks van twee groepen in vergelijking</li>
</ul>
<p>Betere alternatieven bestaan maar vallen buiten bestek van de cursus.</p>
<p>We voeren nu verdere posthoc testen uit voor alle paarsgewijse verschillen a.d.h.v WMW testen.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>pairWilcox <span class="ot">&lt;-</span> <span class="fu">pairwise.wilcox.test</span>(dna<span class="sc">$</span>length, dna<span class="sc">$</span>dose)</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>pairWilcox</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pairwise comparisons using Wilcoxon rank sum exact test 

data:  dna$length and dna$dose 

     0     1.25  2.5  
1.25 0.013 -     -    
2.5  0.013 0.818 -    
5    0.013 0.721 0.788

P value adjustment method: holm </code></pre>
</div>
</div>
<p>De output geeft paarsgewijze p-waarden weer voor elke vergelijking. De output wordt in een matrix geordend. De p-waarde voor elk element van de matrix behoort tot de paarsgewijze vergelijking van de groep in de kolom en de groep in de rij. Standaard wordt de Holm multiple testing methode gebruikt. Dat is een variant van Bonferroni die minder conservatief is.</p>
<p>We zien dat alle DMH behandelingen significant verschillen van de controle. Maar er is geen significant verschil in de distributie van de DNA schade tussen de verschillende dosisgroepen waarbij DMH werd toegediend. Om een puntschatter op de kans op hogere DNA-schade te berekenen voor de vergelijkingen tussen de behandelingen met DMH en de controle zouden we ook de statistieken U1 nodig hebben. Dit kunnen we niet bekomen uit de <code>pairwise.wilcox.test</code> output. Hiervoor zullen we de individuele wilcoxon testen aan moeten roepen.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>nGroep <span class="ot">&lt;-</span> <span class="fu">table</span>(dna<span class="sc">$</span>dose)</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>probInd <span class="ot">&lt;-</span> <span class="fu">combn</span>(</span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">levels</span>(dna<span class="sc">$</span>dose),</span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a>  <span class="dv">2</span>,</span>
<span id="cb68-6"><a href="#cb68-6" aria-hidden="true" tabindex="-1"></a>  <span class="cf">function</span>(x) {</span>
<span id="cb68-7"><a href="#cb68-7" aria-hidden="true" tabindex="-1"></a>         test <span class="ot">&lt;-</span> <span class="fu">wilcox.test</span>(</span>
<span id="cb68-8"><a href="#cb68-8" aria-hidden="true" tabindex="-1"></a>       length<span class="sc">~</span>dose,</span>
<span id="cb68-9"><a href="#cb68-9" aria-hidden="true" tabindex="-1"></a>       dna <span class="sc">|&gt;</span> <span class="fu">filter</span>(dose<span class="sc">%in%</span>x)</span>
<span id="cb68-10"><a href="#cb68-10" aria-hidden="true" tabindex="-1"></a>       )</span>
<span id="cb68-11"><a href="#cb68-11" aria-hidden="true" tabindex="-1"></a>         <span class="fu">return</span>(test<span class="sc">$</span>statistic<span class="sc">/</span><span class="fu">prod</span>(nGroep[x]))</span>
<span id="cb68-12"><a href="#cb68-12" aria-hidden="true" tabindex="-1"></a>    })</span>
<span id="cb68-13"><a href="#cb68-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-14"><a href="#cb68-14" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(probInd) <span class="ot">&lt;-</span> <span class="fu">combn</span>(</span>
<span id="cb68-15"><a href="#cb68-15" aria-hidden="true" tabindex="-1"></a>  dna <span class="sc">|&gt;</span> <span class="fu">pull</span>(dose) <span class="sc">|&gt;</span> <span class="fu">levels</span>(),</span>
<span id="cb68-16"><a href="#cb68-16" aria-hidden="true" tabindex="-1"></a>  <span class="dv">2</span>,</span>
<span id="cb68-17"><a href="#cb68-17" aria-hidden="true" tabindex="-1"></a>  paste,</span>
<span id="cb68-18"><a href="#cb68-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">collapse=</span><span class="st">"vs"</span>)</span>
<span id="cb68-19"><a href="#cb68-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-20"><a href="#cb68-20" aria-hidden="true" tabindex="-1"></a>probInd</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  0vs1.25    0vs2.5      0vs5 1.25vs2.5   1.25vs5    2.5vs5 
0.0000000 0.0000000 0.0000000 0.4444444 0.2777778 0.3333333 </code></pre>
</div>
</div>
<p>Omdat er twijfels zijn of het locatie-shift model geldig is, doen we enkel uitspraken in termen van de probabilistische index.</p>
<p>We besluiten dat er extreem significant verschil is in de distributie van de DNA-schade metingen tengevolge van de DMH behandeling (<span class="math inline">\(p&lt;0.001\)</span> KW-test). DNA-schade is meer waarschijnlijk na behandeling met DMH dan in de controle behandeling (alle p=0.013, WMW-testen). De kansen op hogere DNA-schade na blootstelling aan DMH bedraagt 100%<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a>. Er zijn geen significante verschillen in de distributies van de comet-lengtes tussen de DMH behandelingen onderling (<span class="math inline">\(p=\)</span> 0.72-0.82). DMH vertoont dus al bij de lage dosis genotoxische effecten. (Alle paarsgewijze testen werden gecorrigeerd voor multiple testing d.m.v. Holm’s methode).</p>


</section>
</section>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>in ons geval de t-test statistiek door de originele reponses te gebruiken die nu gekoppeld worden aan de gepermuteerde groepslabels <span class="math inline">\(G_g^*\)</span><a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>in de afwezigheid van <em>ties</em><a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>we veronderstellen afwezigheid van <em>ties</em><a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>Het berekenen van een BI op deze kansen valt buiten het bestek van de cursus<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Gekopieerd!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Gekopieerd!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./07-VariantieAnalyse.html" class="pagination-link" aria-label="Variantie analyse">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Variantie analyse</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./09-CategorischeDataAnalyse.html" class="pagination-link" aria-label="Categorische data analyse">
        <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Categorische data analyse</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/statOmics/statistiek2deBach/edit/main/08-NietParametrischeStatistiek.qmd" class="toc-action"><i class="bi bi-github"></i>Pagina bewerken</a></li></ul></div></div></div></footer></body></html>