<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="nl" xml:lang="nl"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Basiscursus Statistiek voor de 2de Bachelor of Science in de Biologie, - in de Biochemie &amp; de Biotechnologie, - in de Biomedische Wetenschappen, en - in de Chemie">

<title>10&nbsp; Categorische data analyse – Cursus Statistiek 2026-2027</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./10-GeneralLinearModel.html" rel="next">
<link href="./08-NietParametrischeStatistiek.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-5ccb035bea26c1e21f80f44cf7c27909.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Geen resultaten",
    "search-matching-documents-text": "Gevonden documenten",
    "search-copy-link-title": "Kopieer link om te zoeken",
    "search-hide-matches-text": "Extra overeenkomsten verbergen",
    "search-more-match-text": "meer overeenkomst in dit document",
    "search-more-matches-text": "meer overeenkomsten in dit document",
    "search-clear-button-title": "Wissen",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Annuleren",
    "search-submit-button-title": "Verzenden",
    "search-label": "Zoeken"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Schakel zijbalknavigatie" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./09-CategorischeDataAnalyse.html"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Categorische data analyse</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Schakel zijbalknavigatie" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Zoeken" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Cursus Statistiek 2026-2027</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/statOmics/statistiek2deBach" title="Broncode" class="quarto-navigation-tool px-1" aria-label="Broncode"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Download" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Download"><i class="bi bi-download"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="./Statistiek_2026_2027.pdf">
              <i class="bi bi-file-pdf pe-1"></i>
            Download PDF
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="./Statistiek_2026_2027.epub">
              <i class="bi bi-journal pe-1"></i>
            Download ePub
            </a>
          </li>
      </ul>
    </div>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Zoeken"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Cursus Statistiek 2026-2027</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-Inleiding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Inleiding</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-Concepten.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Belangrijke concepten &amp; conventies</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-Proefopzet.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Studiedesign</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-DataExploratie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Data exploratie en beschrijvende statistiek</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-StatistischeBesluitvorming.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Statistische besluitvorming</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-LineareRegressie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Enkelvoudige lineaire regressie</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-VariantieAnalyse.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Variantie analyse</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-NietParametrischeStatistiek.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Niet-parametrische statistiek</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-CategorischeDataAnalyse.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Categorische data analyse</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-GeneralLinearModel.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Algemeen lineair model</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-ModelSelectie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Modelselectie</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">References</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Inhoudsopgave</h2>
   
  <ul>
  <li><a href="#inleiding" id="toc-inleiding" class="nav-link active" data-scroll-target="#inleiding"><span class="header-section-number">10.1</span> Inleiding</a></li>
  <li><a href="#toetsen-voor-een-proportie" id="toc-toetsen-voor-een-proportie" class="nav-link" data-scroll-target="#toetsen-voor-een-proportie"><span class="header-section-number">10.2</span> Toetsen voor een proportie</a>
  <ul class="collapse">
  <li><a href="#asymptotisch-betrouwbaarheidsinterval" id="toc-asymptotisch-betrouwbaarheidsinterval" class="nav-link" data-scroll-target="#asymptotisch-betrouwbaarheidsinterval"><span class="header-section-number">10.2.1</span> Asymptotisch Betrouwbaarheidsinterval</a></li>
  <li><a href="#asymptotische-test" id="toc-asymptotische-test" class="nav-link" data-scroll-target="#asymptotische-test"><span class="header-section-number">10.2.2</span> Asymptotische Test</a></li>
  <li><a href="#sec-binom" id="toc-sec-binom" class="nav-link" data-scroll-target="#sec-binom"><span class="header-section-number">10.2.3</span> Binomiale test</a></li>
  <li><a href="#conclusie" id="toc-conclusie" class="nav-link" data-scroll-target="#conclusie"><span class="header-section-number">10.2.4</span> Conclusie</a></li>
  </ul></li>
  <li><a href="#toets-voor-associatie-tussen-2-kwalitatieve-variabelen" id="toc-toets-voor-associatie-tussen-2-kwalitatieve-variabelen" class="nav-link" data-scroll-target="#toets-voor-associatie-tussen-2-kwalitatieve-variabelen"><span class="header-section-number">10.3</span> Toets voor associatie tussen 2 kwalitatieve variabelen</a>
  <ul class="collapse">
  <li><a href="#gepaarde-gegevens" id="toc-gepaarde-gegevens" class="nav-link" data-scroll-target="#gepaarde-gegevens"><span class="header-section-number">10.3.1</span> Gepaarde gegevens</a></li>
  <li><a href="#sec-catOnPaired" id="toc-sec-catOnPaired" class="nav-link" data-scroll-target="#sec-catOnPaired"><span class="header-section-number">10.3.2</span> Ongepaarde gegevens</a></li>
  <li><a href="#de-pearson-chi-kwadraat-test-voor-ongepaarde-gegevens" id="toc-de-pearson-chi-kwadraat-test-voor-ongepaarde-gegevens" class="nav-link" data-scroll-target="#de-pearson-chi-kwadraat-test-voor-ongepaarde-gegevens"><span class="header-section-number">10.3.3</span> De Pearson Chi-kwadraat test voor ongepaarde gegevens</a></li>
  </ul></li>
  <li><a href="#logistische-regressie" id="toc-logistische-regressie" class="nav-link" data-scroll-target="#logistische-regressie"><span class="header-section-number">10.4</span> Logistische regressie</a>
  <ul class="collapse">
  <li><a href="#categorische-predictor" id="toc-categorische-predictor" class="nav-link" data-scroll-target="#categorische-predictor"><span class="header-section-number">10.4.1</span> Categorische predictor</a></li>
  <li><a href="#continue-predictor" id="toc-continue-predictor" class="nav-link" data-scroll-target="#continue-predictor"><span class="header-section-number">10.4.2</span> Continue predictor</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/statOmics/statistiek2deBach/edit/main/09-CategorischeDataAnalyse.qmd" class="toc-action"><i class="bi bi-github"></i>Pagina bewerken</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-chap-categorisch" class="quarto-section-identifier"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Categorische data analyse</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Alle kennisclips die in dit hoofdstuk zijn verwerkt kan je in deze youtube playlist vinden:</p>
<ul>
<li><a href="https://www.youtube.com/playlist?list=PLZH1hP8_LbJJnNyz6IMPqq6fCMZJ63y8x">Kennisclips Hoofdstuk 9 Categorische Data Analyse</a></li>
</ul>
<p>Link naar webpage/script die wordt gebruik in de kennisclips:</p>
<ul>
<li><a href="https://statomics.github.io/sbc/rmd/09-categoricalDataAnalysis.html">script Hoofdstuk 9</a></li>
</ul>
<section id="inleiding" class="level2" data-number="10.1">
<h2 data-number="10.1" class="anchored" data-anchor-id="inleiding"><span class="header-section-number">10.1</span> Inleiding</h2>
<iframe width="560" height="315" src="https://www.youtube.com/embed/09ErJc8pK3w" frameborder="0" style="display: block; margin: auto;" allow="autoplay; encrypted-media" allowfullscreen="">
</iframe>
<p>Tot nog toe zijn we hoofdzakelijk ingegaan op het modelleren van een continue uitkomst a.d.h.v. een categorische of continue predictor. In dit hoofdstuk onderzoeken we hoe we tot besluitvorming kunnen komen voor een categorische uitkomst. We zullen hierbij focussen op de associatie tussen een categorische uitkomst en een categorische predictor. Zoals we in Sectie <a href="04-DataExploratie.html#sec-kruistabel" class="quarto-xref"><span>5.6.1</span></a> hebben gezien zijn <em>kruistabellen</em> aangewezen om hun associatie voor te stellen.</p>
</section>
<section id="toetsen-voor-een-proportie" class="level2" data-number="10.2">
<h2 data-number="10.2" class="anchored" data-anchor-id="toetsen-voor-een-proportie"><span class="header-section-number">10.2</span> Toetsen voor een proportie</h2>
<iframe width="560" height="315" src="https://www.youtube.com/embed/L9xrDypeZWI" frameborder="0" style="display: block; margin: auto;" allow="autoplay; encrypted-media" allowfullscreen="">
</iframe>
<p>In Saksen werd een studie opgezet binnen een vrij gesloten populatie mensen (weinig immigratie en emigratie) om te bepalen hoe waarschijnlijk het was dat een ongeboren kind mannelijk is.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>boys <span class="ot">&lt;-</span> <span class="dv">3175</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">6155</span></span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Op 6155 ongeboren kinderen werden 3175 jongens geobserveerd. We wensen na te gaan of er een verschil is in de kans dat het ongeboren kind een jongen is of een meisje. In het vervolg van deze sectie vatten we deze gegevens op als uitkomsten van een numerieke toevalsveranderlijke <span class="math inline">\(X\)</span> met uitkomst 1 voor jongens en 0 voor meisjes. Merk op dat we hier met een zogenaamd telprobleem te maken hebben omdat de uitkomst een telling (nl. het aantal jongens) voorstelt.</p>
<p>Formeel hebben we nu een populatie van ongeboren kinderen beschouwd waarin elk individu gekenmerkt wordt door een 0 of een 1. De uitkomst variabele is dus binair. Binaire data kan worden gemodelleerd a.d.h.v. een Bernoulli verdeling:</p>
<p><span class="math display">\[X_i \sim B(\pi) \text{ met}\]</span></p>
<p><span class="math display">\[B(\pi)=\pi^{X_i}(1-\pi)^{(1-X_i)},\]</span></p>
<p>een distributie met 1 model parameter <span class="math inline">\(\pi\)</span>. <span class="math inline">\(\pi\)</span> is de verwachte waarde van <span class="math inline">\(X_i\)</span>:</p>
<p><span class="math display">\[\text{E}[X_i]=\pi,\]</span></p>
<p>de proportie van ongeboren jongens (d.i. kinderen met een 1) in de populatie. Bijgevolg is <span class="math inline">\(\pi\)</span> ook de kans dat een lukraak getrokken individu een jongen is (een observatie die 1 oplevert).</p>
<p>De variantie van Bernoulli data is eveneens gerelateerd aan de kans <span class="math inline">\(\pi\)</span>.</p>
<p><span class="math display">\[\text{Var}[X_i]=\pi (1-\pi).\]</span></p>
<p>Een grafische weergave van enkele Bernoulli kansverdelingen wordt weergegeven in Figuur <a href="#fig-bernoulli" class="quarto-xref"><span>10.1</span></a>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-bernoulli" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-bernoulli-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="09-CategorischeDataAnalyse_files/figure-html/fig-bernoulli-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bernoulli-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figuur&nbsp;10.1: Bernoulli verdelingen.
</figcaption>
</figure>
</div>
</div>
</div>
<p>In het voorbeeld werden lukraak 6155 observaties getrokken uit de populatie. We kunnen <span class="math inline">\(\pi\)</span> schatten op basis van de data d.m.v. het steekproefgemiddelde van de binaire data:</p>
<p><span class="math display">\[\hat \pi = \bar X = \frac{\sum\limits_{i=1}^n X_i}{n},\]</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>pi <span class="ot">&lt;-</span> boys<span class="sc">/</span>n</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>pi</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5158408</code></pre>
</div>
</div>
<p>In ons voorbeeld is <span class="math inline">\(\bar x =\)</span> 3175 / 6155 = 51.6%.</p>
<p>De vraag stelt zich nu of het feit dat 51.6% van de kinderen in de studie mannelijk zijn, voldoende overtuigingskracht draagt om te beweren dat er meer kans is dat een ongeboren kind een jongen is dan een meisje. Met andere woorden, we wensen op basis van deze observaties statistisch te toetsen of de kans <span class="math inline">\(\pi\)</span> al dan niet gelijk is aan 50%.</p>
<p>We zullen die vraag eerst beantwoorden met een asymptotisch betrouwbaarheidsinterval, vervolgens ontwikkelen we een asymptotische test en een exacte test die ook geldig is in kleine steekproeven.</p>
<!---break-->
<section id="asymptotisch-betrouwbaarheidsinterval" class="level3" data-number="10.2.1">
<h3 data-number="10.2.1" class="anchored" data-anchor-id="asymptotisch-betrouwbaarheidsinterval"><span class="header-section-number">10.2.1</span> Asymptotisch Betrouwbaarheidsinterval</h3>
<iframe width="560" height="315" src="https://www.youtube.com/embed/QbHmdmPK-uc" frameborder="0" style="display: block; margin: auto;" allow="autoplay; encrypted-media" allowfullscreen="">
</iframe>
<p>In de Saksenstudie werd een heel grote steekproef getrokken: 6155 onafhankelijke observaties uit dezelfde populatie (verdeling).</p>
<p>We kunnen dus de centrale limietstelling (CLT) toegepassen op gemiddelde: de data volgen een Bernoulli verdeling, maar gemiddelde o.b.v. onafhankelijke en identiek verdeelde observaties in heel grote steekproef volgt approximatief een normaal verdeling.</p>
<p>Voor Bernoulli verdeelde gegevens weten we dat:</p>
<ul>
<li><span class="math inline">\(\text{E}[\bar X] = \pi\)</span>.</li>
<li><span class="math inline">\(\text{Var}[\bar X] = \frac{\text{Var}[X]}{n} = \frac{\pi(1-\pi)}{n}\)</span>.</li>
</ul>
<p>Uit de steekproef weten we verder dat <span class="math inline">\(\bar x\)</span> = 0.516 en kunnen we de standard error schatten:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>se <span class="ot">&lt;-</span> <span class="fu">sqrt</span>((pi<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>pi))<span class="sc">/</span>n)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>De standard error is dus SE = 0.0064</p>
<p><span class="math display">\[\text{SE} = \hat\sigma_{\bar x} = \sqrt{\frac{\bar x(1-\bar x)}{n}}\]</span></p>
<p>En we bekomen volgend betrouwbaarheidsinterval (BI) op het gemiddelde: [0.503, 0.528]</p>
<p><span class="math display">\[[\bar x - z_{\alpha/2} \text{SE}_{\bar x}, \bar x + z_{\alpha/2} \text{SE}_{\bar x}]\]</span></p>
<p>0.5 valt niet binnen het 95% BI. Uit de equivalentie tussen betrouwbaarheidsintervallen en statistische testen volgt dus dat de kans op een jongen significant hoger is dan 50% op het 5% significantie-niveau.</p>
</section>
<section id="asymptotische-test" class="level3" data-number="10.2.2">
<h3 data-number="10.2.2" class="anchored" data-anchor-id="asymptotische-test"><span class="header-section-number">10.2.2</span> Asymptotische Test</h3>
<p>Voor een statistische test moeten we de onderzoeksvraag vertalen naar een nul en alternatieve hypothese in termen van een modelparameter. We wensen aan te tonen dat de kans <span class="math inline">\(\pi\)</span> verschillend is van 50% (alternatieve hypothese). Daarom zullen we de nul hupothese falsifiëren dat <span class="math inline">\(\pi = 0.5\)</span>.</p>
<p><span class="math display">\[H_0: \pi = 0.5 \text{ vs } H_1: \pi \neq 0.5\]</span></p>
<p>Merk op dat voor een Bernoulli verdeling de variantie onder H<span class="math inline">\(_0\)</span> ook gekend is: <span class="math inline">\(\pi_0 (1-\pi_0)\)</span>.</p>
<p>Dus onder <span class="math inline">\(H_0\)</span> is standaard error op <span class="math inline">\(\bar x\)</span>:</p>
<p><span class="math display">\[\text{SE}_{0, \bar x}=\sqrt{\frac{\pi_0 (1-\pi_0)}{n}}\]</span></p>
<p>We kunnen onder de nulhypothese dus volgende statistiek gebruiken die een afwijking van de nulhypothese in de richting van het alternatief zal detecteren.</p>
<p><span class="math display">\[z = \frac{\bar x - \pi_0}{\text{SE}_{0, \bar x}}\]</span></p>
<ul>
<li><p>Onder <span class="math inline">\(H_0\)</span> verwachten we z dicht bij 0. Onder <span class="math inline">\(H_1\)</span> zal z verschuiven naar negatieve (<span class="math inline">\(\pi &lt; \pi_0\)</span>)of positieve waarden (<span class="math inline">\(\pi&gt;\pi_0\)</span>).</p></li>
<li><p>z volgt onder de nulhypothese dat er evenveel kans is op een jongen of een meisje (<span class="math inline">\(\pi_0=0.5\)</span>) asymptotisch een standaard normaal verdeling: we kunnen immers de CLT toepassen!</p></li>
</ul>
<p>We kunnen eenvoudig een p-waarde bekomen door gebruik te maken van de cumulatieve distributie van een standaard normale verdeling. Merk op dat het een tweezijdige test is!</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>pi0 <span class="ot">&lt;-</span> <span class="fl">0.5</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>se0 <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(pi0<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>pi0)<span class="sc">/</span>n)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> (pi<span class="sc">-</span>pi0)<span class="sc">/</span>se0</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>z</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.485539</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>pval <span class="ot">&lt;-</span> <span class="fu">pnorm</span>(<span class="fu">abs</span>(z),<span class="at">lower=</span><span class="cn">FALSE</span>) <span class="sc">*</span><span class="dv">2</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>pval</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.01293554</code></pre>
</div>
</div>
<p>We besluiten dus dat er significant meer kans is dat een ongeboren kind mannelijk dan vrouwelijk is (p=0.013). De kans dat een ongeboren kind mannelijk is bedraagt 0.516 (95% BI [0.503, 0.528]).</p>
<!---break-->
</section>
<section id="sec-binom" class="level3" data-number="10.2.3">
<h3 data-number="10.2.3" class="anchored" data-anchor-id="sec-binom"><span class="header-section-number">10.2.3</span> Binomiale test</h3>
<iframe width="560" height="315" src="https://www.youtube.com/embed/QvfZol-vHBw" frameborder="0" style="display: block; margin: auto;" allow="autoplay; encrypted-media" allowfullscreen="">
</iframe>
<p>Om een toets te kunnen construeren van de nulhypothese dat</p>
<p><span class="math display">\[H_0: \pi=1/2 \text{ versus } H_1: \pi\neq 1/2,\]</span></p>
<p>moeten we de verdeling van de gegevens <span class="math inline">\(X\)</span> en van de schatter voor de proportie, <span class="math inline">\(\hat \pi = \bar X\)</span> (of equivalent de som <span class="math inline">\(S=n\bar X\)</span>) kennen.</p>
<p>Stel dat het voorkomen van jongens en meisjes in de populatie even waarschijnlijk zijn; m.a.w. stel dat de nulhypothese waar is. Bij lukrake trekking van één individu uit de populatie is de kans dat men een jongen observeert dan gelijk aan <span class="math inline">\(P(X=1) = \pi = 1/2.\)</span> Als twee kinderen onafhankelijk van elkaar getrokken worden (en de populatie is bij benadering oneindig groot) dan heeft zowel het eerste als het tweede kind kans 1/2 om mannelijk te zijn (onafhankelijk van elkaar). De uitkomsten <span class="math inline">\((x_1, x_2)\)</span> voor beide kinderen hebben dan 4 mogelijke waarden: <span class="math inline">\((0,0), (0,1),(1,0)\)</span> en <span class="math inline">\((1,1).\)</span> Deze komen elk voor met kans <span class="math inline">\(1/4 = 1/2 \times 1/2\)</span>. Bijgevolg kan de toevalsveranderlijke <span class="math inline">\(S\)</span> die de som van de uitkomsten weergeeft, de volgende waarden aannemen:</p>
<!-- $(x_1,x_2)$|$s$|$P(S = s)$|
|:---:|:---:|:---:|
(0,0)|0|1/4|
(0,1), (1,0)|1|1/2|
(1,1)|2|1/4| -->
<table>
<thead>
<tr>
<th class="tg-c3ow">
<span class="math inline">\((x_1,x_2)\)</span>
</th>
<th class="tg-c3ow">
<span class="math inline">\(s\)</span>
</th>
<th class="tg-c3ow">
<span class="math inline">\(P(S=s)\)</span>
</th>
</tr>
</thead>
<tbody>
<tr>
<td class="tg-c3ow">
(0,0)
</td>
<td class="tg-c3ow">
0
</td>
<td class="tg-c3ow">
1/4
</td>
</tr>
<tr>
<td class="tg-c3ow">
(0,1),(1,0)
</td>
<td class="tg-c3ow">
1
</td>
<td class="tg-c3ow">
1/2
</td>
</tr>
<tr>
<td class="tg-c3ow">
(1,1)
</td>
<td class="tg-c3ow">
2
</td>
<td class="tg-c3ow">
1/4
</td>
</tr>
</tbody>
</table>
<p>In het algemeen, als men <span class="math inline">\(n\)</span> onafhankelijke observaties trekt telkens met kans <span class="math inline">\(\pi\)</span> op “succes” (uitkomst 1), dan kan het totaal aantal successen <span class="math inline">\(S\)</span> (of de som van alle 1-en), <span class="math inline">\(n+1\)</span> mogelijke waarden hebben. Men kan aantonen dat elke waarde <span class="math inline">\(k\)</span> tussen 0 en <span class="math inline">\(n\)</span> dan de volgende kans op voorkomen heeft:</p>
<p><span id="eq-binomk"><span class="math display">\[
P(S=k) = \left (
\begin{array}{c}
n \\
k \\
\end{array}
\right ) \pi^k (1-\pi)^{n-k}
\tag{10.1}\]</span></span></p>
<p>waarbij <span class="math inline">\(1-\pi\)</span> de kans is op mislukking in 1 enkele trekking (uitkomst met 0 genoteerd) en <span class="math inline">\(\left(\begin{array}{c}
n \\
k \\
\end{array}\right)\)</span> de binomiaalcoëfficient<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<p><span class="math display">\[\begin{equation*}
\left (
\begin{array}{c}
n \\
k \\
\end{array}
\right ) = \frac{n \times (n-1) \times ...\times (n-k+1) }{ k!} = \frac{ n!}{ k!(n-k)! }
\end{equation*}\]</span></p>
<p>is, waarbij <span class="math inline">\(0!=1!=1\)</span>.</p>
<p>In R kan je die kansen opvragen met behulp van het commando <code>dbinom(k,n,p)</code>.</p>
<p>Een toevalsveranderlijke <span class="math inline">\(S\)</span> met een kansverdeling zoals in Model <a href="#eq-binomk" class="quarto-xref"><span>10.1</span></a> noemt men een <em>Binomiaal verdeelde toevalsveranderlijke</em>. De bijhorende kansverdeling is de <em>Binomiale kansverdeling</em> met parameters <span class="math inline">\(n\)</span> (d.i. het aantal trekkingen of, equivalent, de maximale uitkomstwaarde) en <span class="math inline">\(\pi\)</span> (de kans op een `succes’ bij elke trekking). Ze kan gebruikt worden om te berekenen wat de kans is dat er zich op een vast totaal van <span class="math inline">\(n\)</span> onafhankelijke experimenten <span class="math inline">\(k\)</span> gebeurtenissen van een bepaald type voordoen, als je weet dat de kans dat zich 1 zo’n gebeurtenis voordoet op 1 experiment, <span class="math inline">\(\pi\)</span> bedraagt. De Binomiale kansverdeling wordt vooral gebruikt voor de analyse van gegevens die slechts 2 mogelijke waarden kunnen aannemen. Dergelijke gegevens komen vaak voor in wetenschappelijk onderzoek (bijvoorbeeld: al dan niet besmet met HIV, wild type van een gen vs een mutant,…). Kennis van de Binomiale verdeling kan dan helpen om proporties of risico’s op een gebeurtenis van een bepaald type te vergelijken tussen verschillende groepen. Een grafische weergave van enkele Binomiale kansverdelingen is gegeven in Figuur <a href="#fig-binoms" class="quarto-xref"><span>10.2</span></a>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-binoms" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-binoms-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="09-CategorischeDataAnalyse_files/figure-html/fig-binoms-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-binoms-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figuur&nbsp;10.2: Binomiale verdelingen.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Om nu te toetsen of <span class="math inline">\(\pi=1/2\)</span> versus het alternatief dat <span class="math inline">\(\pi\neq 1/2\)</span>, is een voor de hand liggende toetsstatistiek <span class="math inline">\(\bar X-1/2\)</span> of, equivalent, <span class="math inline">\(\Delta=n(\bar
X-\pi_0)=S-s_0\)</span>. De verdeling van deze laatste toetsstatistiek volgt rechtstreeks uit de Binomiale verdeling.</p>
<p>We observeren <span class="math inline">\(s=\)</span> 3175 en dus <span class="math inline">\(\delta=s-s_0=\)</span> 3175 <span class="math inline">\(-\)</span> 6155 <span class="math inline">\(\times 0.5=\)</span> 97.5. In de onderstelling dat jongens en meisjes even waarschijnlijk zijn (d.i. onder de nulhypothese <span class="math inline">\(H_0:\pi=1/2\)</span>), kunnen we de bijhorende tweezijdige p-waarde berekenen als de kans dat de uitkomst</p>
<p><span class="math display">\[p=\text{P}_0\left[S-s_0\geq \vert \delta\vert \right] + \text{P}_0\left[S-s_0\leq - \vert \delta\vert \right].\]</span></p>
<p>Merk op dat we dit kunnen herschrijven in termen van S.</p>
<p><span class="math display">\[p=\text{P}_0\left[S\geq s_0+ \vert \delta\vert \right] + \text{P}_0\left[S \leq s_0 - \vert \delta\vert \right].\]</span></p>
<p>Voor ons voorbeeld kunnen we deze kansen als volgt berekenen:</p>
<p><span class="math display">\[\begin{eqnarray*}
\text{P}_0\left[S\geq s_0+ \vert \delta\vert \right] &amp;=&amp; P(S \geq 6155 \times 0.5 + \vert 3175 - 6155 \times 0.5\vert ) = P(S \geq 3175)\\
&amp;= &amp;P(S= 3175) + P(S=3176) + ... + P(S=6155)\\
&amp; =&amp; 0.0067\\\\
\text{P}_0\left[S \leq s_0 - \vert \delta\vert \right] &amp;=&amp; P(S \leq  6155 \times 0.5 - \vert 3175- 6155 \times 0.5\vert) = P(S \leq 2980)\\ &amp;= &amp;P(S=0) + ... + P(S=2980) \\
&amp;=&amp;0.0067
\end{eqnarray*}\]</span></p>
<p>Gezien <span class="math inline">\(\pi=0.5\)</span> zijn deze kansen gelijk omdat de binomiale distributie dan symmetrisch is. Dat is niet langer het geval wanneer <span class="math inline">\(\pi\)</span> afwijkt van 0.5.</p>
<p>In R kan men de kansen berekenen via de commando’s:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>pi0 <span class="ot">&lt;-</span> <span class="fl">0.5</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>s0 <span class="ot">&lt;-</span> pi0 <span class="sc">*</span>n</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>delta <span class="ot">&lt;-</span> <span class="fu">abs</span>(boys<span class="sc">-</span> s0)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>delta</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 97.5</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>sUp <span class="ot">&lt;-</span> s0 <span class="sc">+</span> delta</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>sDown <span class="ot">&lt;-</span> s0 <span class="sc">-</span>delta</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(sDown,sUp)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2980 3175</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Merk op dat we voor de berekening naar rechts</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="co">#pbinom(sUp-1,n,pi) gebruiken omdat we met</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="co">#pbinom de kans berekenen in de linkse staart</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co">#anders wordt s=3175 er niet bij geteld!</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>pUp <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">pbinom</span>(sUp<span class="dv">-1</span>, n, pi0)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>pUp</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.006699883</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>pDown <span class="ot">&lt;-</span> <span class="fu">pbinom</span>(sDown, n, pi0)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>pDown</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.006699883</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> pUp<span class="sc">+</span>pDown</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>p</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.01339977</code></pre>
</div>
</div>
<p>waarbij <code>pbinom(sUp-1,n,pi0)</code> de kans op een resultaat kleiner of gelijk aan <span class="math inline">\(s_0+\vert \delta\vert -1 =\)</span> 3174 berekent. Als <span class="math inline">\(\pi= 1/2\)</span>, dan zou de kans om door toeval minstens <span class="math inline">\(\delta=\)</span> 97.5 jongens meer of minder te observeren dan het gemiddelde onder <span class="math inline">\(H_0: s_0=\)</span> 3077.5 , slechts 1.34% is, de <span class="math inline">\(p\)</span>-waarde van de binomiale test.<br>
Dit geeft aan dat het heel onwaarschijnlijk is om een dergelijk groot aantal jongens te observeren als in realiteit jongens en meisjes even waarschijnlijk zijn. Het drukt met andere woorden uit dat de onderstelling dat jongens en meisjes even waarschijnlijk zijn, weinig gesteund wordt door de data. Dit blijkt ook uit Figuur <a href="#fig-pitests" class="quarto-xref"><span>10.3</span></a>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-pitests" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pitests-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="09-CategorischeDataAnalyse_files/figure-html/fig-pitests-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pitests-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figuur&nbsp;10.3: Binomiale verdeling van het aantal jongens S onder <span class="math inline">\(H_0: \pi=0.5 (n=6155)\)</span>.
</figcaption>
</figure>
</div>
</div>
</div>
<p>De test kan eveneens worden uitgevoerd a.d.h.v. de <code>binomial.test</code> functie in R.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">binom.test</span>(<span class="at">x =</span> boys, <span class="at">n =</span> n, <span class="at">p =</span> pi0)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Exact binomial test

data:  boys and n
number of successes = 3175, number of trials = 6155, p-value = 0.0134
alternative hypothesis: true probability of success is not equal to 0.5
95 percent confidence interval:
 0.5032696 0.5283969
sample estimates:
probability of success 
             0.5158408 </code></pre>
</div>
</div>
<p>Op het 5% significantie-niveau besluiten we dat er meer kans is dat een ongeboren kind mannelijk dan vrouwelijk is.</p>
<p>Voor de Saksen-studie ligt het BI op basis van de CLT heel dicht bij het exacte BI omdat de studie is gebaseerd op een grote steekproef (<span class="math inline">\(n=\)</span> 6155).</p>
<ul>
<li><p>De Binomiale test heeft ook een exact BI weer op een proportie.</p></li>
<li><p>Het exacte BI is te verkiezen boven het BI dat gebaseerd is op de CLT.</p></li>
<li><p>Voor Saksen-studie ligt BI o.b.v. CLT heel dicht bij exacte BI: grote steekproef (<span class="math inline">\(n=\)</span> 6155).</p></li>
</ul>
<p>Merk op dat het testen voor een proportie kan gezien worden als het equivalent van een one-sample t-test voor binaire data.</p>
</section>
<section id="conclusie" class="level3" data-number="10.2.4">
<h3 data-number="10.2.4" class="anchored" data-anchor-id="conclusie"><span class="header-section-number">10.2.4</span> Conclusie</h3>
<p>Voor de Saksen populatie besluiten we op het 5% significantieniveau dat er meer kans is dat een ongeboren kind mannelijk dan vrouwelijk is (<span class="math inline">\(p=\)</span> 0.013). De kans dat een ongeboren kind mannelijk is, bedraagt 51.6% (95% BI [50.3,52.8]%).</p>
</section>
</section>
<section id="toets-voor-associatie-tussen-2-kwalitatieve-variabelen" class="level2" data-number="10.3">
<h2 data-number="10.3" class="anchored" data-anchor-id="toets-voor-associatie-tussen-2-kwalitatieve-variabelen"><span class="header-section-number">10.3</span> Toets voor associatie tussen 2 kwalitatieve variabelen</h2>
<section id="gepaarde-gegevens" class="level3" data-number="10.3.1">
<h3 data-number="10.3.1" class="anchored" data-anchor-id="gepaarde-gegevens"><span class="header-section-number">10.3.1</span> Gepaarde gegevens</h3>
<iframe width="560" height="315" src="https://www.youtube.com/embed/C-GVbk29SEY" frameborder="0" style="display: block; margin: auto;" allow="autoplay; encrypted-media" allowfullscreen="">
</iframe>
<p>Net zoals bij het vergelijken van gemiddelden (uitkomsten op 2 continue veranderlijken) is het ook hier in principe mogelijk dezelfde individuen 2 keer te meten (bijvoorbeeld, vóór en na blootstelling aan de experimentele stof) en telkens de uitkomst te observeren. In dat geval hebben we te maken met <em>gepaarde binaire uitkomsten</em> en moeten we in de statistische analyse rekening houden met de paring.</p>
<section id="voorbeeld" class="level4" data-number="10.3.1.1">
<h4 data-number="10.3.1.1" class="anchored" data-anchor-id="voorbeeld"><span class="header-section-number">10.3.1.1</span> Voorbeeld</h4>
<p><span class="citation" data-cites="Rogovin2017">Rogovin e.a. (<a href="#ref-Rogovin2017" role="doc-biblioref">2017</a>)</span> onderzochten de partnerkeuze van seksueel mature vrouwelijke <em>Campbelli</em> dwerghamster. Hiervoor bekeken ze verschillende karakteristieken van de mannetjes, waaronder seksgerelateerde morfologische kenmerken (lichaamsmassa, externe testikel diameter), testosteron niveau, immunocompetentie kenmerken (de concentratie aan T-cel en B-cel immuuncellen in het bloed), maar ook gedragskenmerken zoals agressiviteit en seksuele dominantie van het mannetje.</p>
<p>De experimentele set-up betreft een rechthoekige doos van plexiglas met drie compartimenten, waarin het vrouwtje zich in het middenste gedeelte bevindt (zie Figuur <a href="#fig-hamsterKooi" class="quarto-xref"><span>10.4</span></a>).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-hamsterKooi" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-hamsterKooi-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="09-CategorischeDataAnalyse_files/figure-html/fig-hamsterKooi-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-hamsterKooi-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figuur&nbsp;10.4: Experimentele opstelling voor het bepalen van de partnerkeuze bij dwerghamsters
</figcaption>
</figure>
</div>
</div>
</div>
<p>De mannetjes, die overigens broers zijn, hangen vast aan de doos waardoor ze zich slechts over drie vierden van de ruimte van hun compartiment vrij kunnen bewegen. Na alle dieren enkele minuten te laten acclimatiseren worden niet-doorzichtige wanden die de compartimenten scheidden, opgetrokken waardoor het vrouwtje zich via de aangegeven deurtjes naar de mannetjes kan begeven. Aangezien de mannetjes zich niet buiten hun compartiment kunnen begeven, ligt de keuze volledig in de handen van het vrouwtje. Het wordt aangenomen dat het vrouwtje een partnerkeuze maakt indien ze meer dan twee derden van de tijd met één mannetje doorbrengt, relatief ten opzichte van de totale tijd die ze met mannetjes doorbrengt.</p>
<p>Elk vrouwtje onderging tweemaal de test, waarbij ze telkens kon kiezen tussen één agressief en één niet-agressief mannetje. Om te onderzoeken of de partnerkeuze van het vrouwtje beïnvloed wordt door de omgeving, kwam het vrouwtje in één van de testen uit een vijandige omgeving (hoge populatie, weinig voedsel, veel concurrentie) en in een andere test uit een vriendelijkere omgeving.</p>
<p>De resultaten van de studie zijn samengevat in de onderstaande kruistabel (Tabel <a href="#tbl-catHamster" class="quarto-xref"><span>10.1</span></a>).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>hamster <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">17</span>,<span class="dv">1</span>,<span class="dv">13</span>),<span class="at">ncol=</span><span class="dv">2</span>,<span class="at">byrow=</span><span class="cn">TRUE</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(hamster) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"vijandig-agressief"</span>, <span class="st">"vijandig-niet-agressief"</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(hamster) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"vriendelijk-agressief"</span>,<span class="st">"vriendelijk-niet-agressief"</span>)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div id="tbl-catHamster" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-catHamster-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabel&nbsp;10.1: Kruistabel van partnerkeuze bij dwerghamster.
</figcaption>
<div aria-describedby="tbl-catHamster-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th">vriendelijk-agressief</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">vriendelijk-niet-agressief</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">totaal</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">vijandig-agressief</td>
<td style="text-align: left;">3 (e)</td>
<td style="text-align: left;">17 (f)</td>
<td style="text-align: left;">20</td>
</tr>
<tr class="even">
<td style="text-align: left;">vijandig-niet-agressief</td>
<td style="text-align: left;">1 (g)</td>
<td style="text-align: left;">13 (h)</td>
<td style="text-align: left;">14</td>
</tr>
<tr class="odd">
<td style="text-align: left;">totaal</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">30</td>
<td style="text-align: left;">34</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>De kans op de keuze voor een agressief mannetje na verblijf in een vijandige omgeving noteren we als <span class="math inline">\(\pi_1\)</span> en kunnen we schatten als <span class="math inline">\((e+f)/n\)</span>, waarbij <span class="math inline">\(n=e+f+g+h\)</span>. De kans op de keuze voor een agressief mannetje na een vriendelijke omgeving noteren we met <span class="math inline">\(\pi_0\)</span> en kunnen we schatten als <span class="math inline">\((e+g)/n\)</span>. Het verschil tussen beide kansen, het absoluut riscoverschil (ARV), schatten we als</p>
<p><span class="math display">\[\begin{equation*}
\widehat{\text{ARV}}=\hat\pi_1-\hat\pi_0=\frac{e+f}{n}-\frac{e+g}{n}=\frac{f-g}{n}
\end{equation*}\]</span></p>
<p>en wordt enkel beïnvloed door de aantallen discordante paren <span class="math inline">\(f\)</span> en <span class="math inline">\(g\)</span><a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>. Men kan aantonen dat de standaard error van dit verschil gelijk is aan</p>
<p><span class="math display">\[\begin{equation*}
\text{SE}_{\widehat{\text{ARV}}}=\frac{1}{n}\sqrt{f+g-\frac{(f-g)^2}{n}}
\end{equation*}\]</span></p>
<p>Als er voldoende gegevens zijn, kan men een <span class="math inline">\((1-\alpha)100\%\)</span> betrouwbaarheidsinterval voor het absolute risicoverschil op de keuze voor een agressief mannetje t.g.v. de omgeving schatten als</p>
<p><span class="math display">\[\left[\widehat{\text{ARV}}-z_{\alpha/2}\text{SE}_{\widehat{\text{ARV}}},\widehat{\text{ARV}}+z_{\alpha/2}\text{SE}_{\widehat{\text{ARV}}}\right]\]</span></p>
<p>of</p>
<p><span class="math display">\[\left[\frac{f-g}{n}-\frac{z_{\alpha/2}}{n}\sqrt{f+g-\frac{(f-g)^2}{n}},\frac{f-g}{n}+\frac{z_{\alpha/2}}{n}\sqrt{f+g-\frac{(f-g)^2}{n}}\right] \]</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> hamster[<span class="dv">1</span>,<span class="dv">2</span>]</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>g <span class="ot">&lt;-</span> hamster[<span class="dv">2</span>,<span class="dv">1</span>]</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">sum</span>(hamster)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>riskdiff <span class="ot">&lt;-</span> (f<span class="sc">-</span>g)<span class="sc">/</span>n</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>riskdiff</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4705882</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>se <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(f<span class="sc">+</span>g<span class="sc">-</span>(f<span class="sc">-</span>g)<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>n)<span class="sc">/</span>n</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>se</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.09517144</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>bi <span class="ot">&lt;-</span> riskdiff <span class="sc">+</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>)<span class="sc">*</span><span class="fu">qnorm</span>(<span class="fl">0.975</span>)<span class="sc">*</span>se</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>bi</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2840556 0.6571208</code></pre>
</div>
</div>
<p>Het absolute risicoverschil op de keuze van een agressief mannetje tussen een verblijf in een vijandige en vriendelijke omgeving bedraagt</p>
<p><span class="math display">\[\begin{equation*}
\widehat{\text{ARV}}=\frac{17-1}{34}=0.471
\end{equation*}\]</span></p>
<p>of 47.1%. De standaard error van dit verschil is</p>
<p><span class="math display">\[\begin{equation*}
\text{SE}_{\widehat{\text{ARV}}}=\frac{1}{34}\sqrt{17+1-\frac{(17-1)^2}{34}}=0.0952
\end{equation*}\]</span></p>
<p>Een 95% betrouwbaarheidsinterval absolute risicoverschil op de keuze van een agressief mannetje tussen een verblijf in een vijandige en vriendelijke omgeving is bijgevolg</p>
<p><span class="math display">\[\begin{equation*}
\left[0.471-1.96\times 0.0952,0.471+1.96\times 0.0952\right]=[0.284,0.658]
\end{equation*}\]</span></p>
<p>We hebben dus geschat dat het absolute risico met 95% kans in het interval [28.4,65.8]% ligt.</p>
<!---break-->
</section>
<section id="mcnemar-test" class="level4" data-number="10.3.1.2">
<h4 data-number="10.3.1.2" class="anchored" data-anchor-id="mcnemar-test"><span class="header-section-number">10.3.1.2</span> McNemar test</h4>
<iframe width="560" height="315" src="https://www.youtube.com/embed/ypRozT2YH90" frameborder="0" style="display: block; margin: auto;" allow="autoplay; encrypted-media" allowfullscreen="">
</iframe>
<p>We gaan vervolgens na hoe we kunnen toetsen of de risico’s verschillen tussen de vijandige en vriendelijke omgeving. Indien alle vrouwtjes in zowel de vijandige als vriendelijke omgeving dezelfde partnerkeuze hadden, dan was er geen informatie over de vraag of de omgeving geassocieerd is met de partnerkeuze. Enkel de discordante paren leveren hier informatie over. Als er meer discordante paren zijn waar een vrouwtje een agressief mannetje kiest na verblijf in een vijandige omgeving en een niet-agressief mannetje na een vriendelijke omgeving, dan discordante paren waar het vrouwtje een niet-agressief mannetje kiest na verblijf in een vijandige omgeving en een agressief mannetje kiest na een vriendelijke omgeving, dan is er een indicatie tegen de nulhypothese dat er geen associatie is tussen de partnerkeuze en de omgeving. Men kan daarom toetsen of de partnerkeuze geassocieerd is met de omgeving door de kans te evalueren dat in een lukraak discordant paar, het vrouwtje na verblijf in een vijandige omgeving kiest voor het agressieve mannetje. Deze kans wordt geschat als <span class="math inline">\(f/(f+g)\)</span> en wordt verwacht in de buurt van 0.5 te liggen als de nulhypothese geldt dat er geen associatie is tussen partnerkeuze en omgeving. Meer bepaald volgt het getal <span class="math inline">\(f\)</span> binnen de groep discordante paren onder de nulhypothese een Binomiale verdeling met parameters <span class="math inline">\(f+g\)</span> en 0.5. De standaarddeviatie van <span class="math inline">\(f\)</span> is bijgevolg gelijk aan</p>
<p><span class="math display">\[\begin{equation*}
\sqrt{(f+g)\times 0.5\times 0.5}=\frac{\sqrt{f+g}}{2}
\end{equation*}\]</span></p>
<p>onder de nulhypothese. Op voorwaarde dat er voldoende observaties zijn, kan men nu de one-sample z-test<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> gebruiken om te toetsen of de kans dat een lukraak discordant paar in de cel rechtsboven van de tabel gelegen is, 0.5 bedraagt. M.a.w. bekijken we het gestandaardiseerde verschil tussen <span class="math inline">\(f\)</span> en haar verwachtingswaarde onder de nulhypothese:</p>
<p><span class="math display">\[\begin{equation*}
\frac{f-(f+g)/2}{\sqrt{f+g}/2}=\frac{f-g}{\sqrt{f+g}}
\end{equation*}\]</span></p>
<p>die bij benadering een Normale verdeling volgt onder de nulhypothese. De Normale benadering is goed als</p>
<p><span class="math display">\[f \times g/(f+g) \geq 5\]</span></p>
<p>De toets gebaseerd op bovenstaande toetsingsgrootheid heet de <em>Mc Nemar toets</em>.</p>
<p>In kleine steekproeven is het meer aangewezen om een continuïteitscorrectie te gebruiken d.m.v. de toetsingsgrootheid</p>
<p><span class="math display">\[\begin{equation*}
\frac{|f-g|-1}{\sqrt{f+g}}
\end{equation*}\]</span></p>
<p>De <strong>Mc Nemar test</strong> wordt gebruikt om te toetsen of er een associatie is tussen 2 kwalitatieve, binaire variabelen, i.h.b. om te toetsen of de kans op succes voor de ene variabele verschilt tussen de 2 strata van de andere kwalitatieve variabele. Ze vereist dat alle metingen voor de ene kwalitatieve variabele (uitkomst) in het ene stratum van de andere kwalitatieve variabele, onafhankelijk zijn, en dat elke meting uit het ene stratum gepaard is met een meting uit het andere stratum in die zin dat ze van verwante subjecten afkomstig zijn. Op die manier vormt ze het analogon van de gepaarde t-test voor binaire, kwalitatieve i.p.v. continue variabelen.</p>
<p>We voeren nu de analyse uit voor het hamstervoorbeeld in R:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>correct <span class="ot">&lt;-</span> f<span class="sc">*</span>g<span class="sc">/</span>(f<span class="sc">+</span>g)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>correct</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9444444</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co">#continuiteitscorrectie</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> (<span class="fu">abs</span>(f<span class="sc">-</span>g)<span class="sc">-</span><span class="dv">1</span>)<span class="sc">/</span><span class="fu">sqrt</span>(f<span class="sc">+</span>g)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>z</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.535534</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> (<span class="dv">1</span><span class="sc">-</span><span class="fu">pnorm</span>(z))<span class="sc">*</span><span class="dv">2</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>p</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.000406952</code></pre>
</div>
</div>
<p>Voor het dwerghamster voorbeeld observeren we dat <span class="math inline">\(f\times g/(f+g)=\)</span> 0.944 <span class="math inline">\(&lt;5\)</span>. We zullen dus de continuïteitscorrectie uitvoeren. De McNemar toetsingsgrootheid bedraagt <span class="math inline">\((\vert 17-1 \vert -1)/\sqrt{17+1}=\)</span> 3.54. De kans dat een Normaal verdeelde toevalsveranderlijke groter is dan 3.54 of kleiner is dan -3.54 bedraagt 0.0407% en stelt ook de p-waarde van de toets voor. We verwerpen bijgevolg de nulhypothese op het 5% significantieniveau en besluiten dat de parternkeuze extreem significant geassocieerd is met de omgeving.</p>
<p>In R kan de analyse ook worden uitgevoerd a.d.h.v. de <code>mcnemar.test</code> functie</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mcnemar.test</span>(hamster)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    McNemar's Chi-squared test with continuity correction

data:  hamster
McNemar's chi-squared = 12.5, df = 1, p-value = 0.000407</code></pre>
</div>
</div>
<p>We zien dat hier eveneens de continuïteitscorrectie werd uitgevoerd en dat we exact dezelfde p-waarde bekomen.</p>
<p>Merk echter op dat de Normale benadering van deze toetstatistiek niet ideaal is omdat <span class="math inline">\(f \times g/(f+g)=\)</span> 0.944 <span class="math inline">\(&lt;5\)</span>. Bovenstaande p-waarde is om die reden niet accuraat.</p>
<p>Het is steeds meer aangewezen om een exacte toets te gebruiken op basis van het principe in Sectie <a href="#sec-binom" class="quarto-xref"><span>10.2.3</span></a>. Dergelijke toetsen maken gebruik van de exacte Binomiale verdeling van de gegevens om te toetsen of de kans dat een lukraak discordant paar in de cel rechtsboven van de tabel gelegen is, 0.5 bedraagt.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">binom.test</span>(<span class="at">x =</span> f,</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">n =</span> f <span class="sc">+</span> g,</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">p =</span> <span class="fl">0.5</span>)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Exact binomial test

data:  f and f + g
number of successes = 17, number of trials = 18, p-value = 0.000145
alternative hypothesis: true probability of success is not equal to 0.5
95 percent confidence interval:
 0.7270564 0.9985944
sample estimates:
probability of success 
             0.9444444 </code></pre>
</div>
</div>
</section>
<section id="conclusie-1" class="level4" data-number="10.3.1.3">
<h4 data-number="10.3.1.3" class="anchored" data-anchor-id="conclusie-1"><span class="header-section-number">10.3.1.3</span> Conclusie</h4>
<p>Op basis van de exacte test besluiten we eveneens dat de parternkeuze extreem significant geassocieerd is met de omgeving (<span class="math inline">\(p&lt;0.001\)</span>). De kans op de keuze van een agressief mannetje ligt 47.1% hoger als een dwerghamster vrouwtje zich in een vijandige omgeving bevindt dan wanneer ze zich in een vriendelijke omgeving bevindt (95% BI [28.4,65.7]%).</p>
<!---break-->
</section>
</section>
<section id="sec-catOnPaired" class="level3" data-number="10.3.2">
<h3 data-number="10.3.2" class="anchored" data-anchor-id="sec-catOnPaired"><span class="header-section-number">10.3.2</span> Ongepaarde gegevens</h3>
<iframe width="560" height="315" src="https://www.youtube.com/embed/ncLVxqTw3NY" frameborder="0" style="display: block; margin: auto;" allow="autoplay; encrypted-media" allowfullscreen="">
</iframe>
<p>We beschouwen hier opnieuw Voorbeeld <a href="03-Proefopzet.html#exm-brcaLeu" class="quarto-xref"><span>4.16</span></a>. Het is belangrijk om dit voorbeeld eerst grondig door te nemen alsook de Sectie rond data exploratie van categorische variabelen (Sectie <a href="04-DataExploratie.html#sec-explCatVar" class="quarto-xref"><span>5.5</span></a>).</p>
<p>Deze genetische associatiestudie was erop gericht om na te gaan of polymorfismen in het BRCA1 gen geassocieerd is met borstkanker. Het was een retrospectieve case-controle studie die 800 borstkankercases en 572 controles omvatte. Een R object met de data is opgeslagen in de file <code>brca.rda</code> in de dataset folder.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>brca <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://raw.githubusercontent.com/statOmics/sbc/master/data/brca.csv"</span>)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(brca)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  cancer  variant variant2
  &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;   
1 control pro/pro other   
2 control pro/pro other   
3 control pro/pro other   
4 control pro/pro other   
5 control pro/pro other   
6 control pro/pro other   </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(brca)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       cancer          variant          variant2   
 Length   :1372   Length   :1372   Length   :1372  
 N.unique :   2   N.unique :   3   N.unique :   2  
 N.blank  :   0   N.blank  :   0   N.blank  :   0  
 Min.nchar:   4   Min.nchar:   7   Min.nchar:   5  
 Max.nchar:   7   Max.nchar:   7   Max.nchar:   7  </code></pre>
</div>
</div>
<p>De dataset bevat 3 categorische variabelen: de ziekte status (factor cancer: controle vs case), brca variant (variant: wild type Pro/Pro, enkele mutatie Pro/Leu, dubbele mutatie Leu/Leu) en een factor of men de dubbele Leu/Leu mutatie bevat of niet (variant2).</p>
<p>Een kruistabel kan in R verkregen worden door</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>brcaTab <span class="ot">&lt;-</span> <span class="fu">table</span>(brca<span class="sc">$</span>variant,brca<span class="sc">$</span>cancer)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>brcaTab</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         
          case control
  leu/leu   89      56
  pro/leu  369     250
  pro/pro  342     266</code></pre>
</div>
</div>
<p>Informatie omtrent het BRCA1-polymorfisme werd bekomen via DNA-analyse en staat opnieuw getabuleerd in Tabel <a href="#tbl-leu3" class="quarto-xref"><span>10.2</span></a>.</p>
<div class="cell">
<div id="tbl-leu3" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-leu3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabel&nbsp;10.2: Kruistabel van borstkanker-status versus BRCA1-allel.
</figcaption>
<div aria-describedby="tbl-leu3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Genotype</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Controles</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Cases</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Totaal</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Pro/Pro</td>
<td style="text-align: left;">266 (a)</td>
<td style="text-align: left;">342 (d)</td>
<td style="text-align: left;">608 (a+d)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Pro/Leu</td>
<td style="text-align: left;">250 (b)</td>
<td style="text-align: left;">369 (e)</td>
<td style="text-align: left;">619 (b+e)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Leu/Leu</td>
<td style="text-align: left;">56 (c)</td>
<td style="text-align: left;">89 (f)</td>
<td style="text-align: left;">145 (c+f)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Totaal</td>
<td style="text-align: left;">572 (a+b+c)</td>
<td style="text-align: left;">800 (d+e+f)</td>
<td style="text-align: left;">1372 (n)</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<!---break-->
<iframe width="560" height="315" src="https://www.youtube.com/embed/HOoX8qET4os" frameborder="0" style="display: block; margin: auto;" allow="autoplay; encrypted-media" allowfullscreen="">
</iframe>
<p>In Sectie <a href="04-DataExploratie.html#sec-retrospect" class="quarto-xref"><span>5.5.2</span></a> zagen we reeds dat <em>het relatief risico</em> op de aandoening (d.w.z. op <em>case</em>) in de populatie voor blootgestelden versus niet-blootgestelden niet rechtstreeks kan geschat worden op basis van gegevens uit een <em>case-controle studie</em>. We zagen dat we wel een uitspraak konden doen hierover a.d.h.v. odds ratio’s, gezien het een symmetrische associatie maat is.<br>
In voorbeeld <a href="03-Proefopzet.html#exm-brcaLeu" class="quarto-xref"><span>4.16</span></a> konden we daarom de odds op borstkanker berekenen voor vrouwen met allel Leu/Leu versus vrouwen zonder de dubbele mutatie als <span class="math inline">\(OR=89\times (266+250)/(56\times (342+369))=89\times 512/(56 \times 711)=1.15\)</span>. De odds op borstkanker is bijgevolg 15% hoger bij vrouwen met die specifieke allelcombinatie. We kunnen ons nu afvragen of dat verschil groot genoeg is zodat we het effect die we in de steekproef zien kunnen veralgemenen naar de populatie toe.</p>
<p>Hiertoe zullen we de kruistabel eerst herschrijven tot een 2x2 tabel zodat we de vrouwen met een Leu/Leu variant vergelijken met de vrouwen in de studie die niet homozygoot zijn in de mutatie<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> (Tabel <a href="#tbl-leu4" class="quarto-xref"><span>10.3</span></a>).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>brcaTab2 <span class="ot">&lt;-</span> <span class="fu">table</span>(brca<span class="sc">$</span>variant2, brca<span class="sc">$</span>cancer)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>brcaTab2</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         
          case control
  leu/leu   89      56
  other    711     516</code></pre>
</div>
</div>
<div class="cell">
<div id="tbl-leu4" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-leu4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabel&nbsp;10.3: Kruistabel van borstkanker-status versus Leu/Leu-variant.
</figcaption>
<div aria-describedby="tbl-leu4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Genotype</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Controles</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Cases</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Totaal</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">andere</td>
<td style="text-align: left;">516 (a)</td>
<td style="text-align: left;">711 (c)</td>
<td style="text-align: left;">1227 (a+c)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Leu/Leu</td>
<td style="text-align: left;">56 (b)</td>
<td style="text-align: left;">89 (d)</td>
<td style="text-align: left;">145 (b+d)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Totaal</td>
<td style="text-align: left;">572 (a+b)</td>
<td style="text-align: left;">800 (c+d)</td>
<td style="text-align: left;">1372 (n)</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<!---break-->
</section>
<section id="de-pearson-chi-kwadraat-test-voor-ongepaarde-gegevens" class="level3" data-number="10.3.3">
<h3 data-number="10.3.3" class="anchored" data-anchor-id="de-pearson-chi-kwadraat-test-voor-ongepaarde-gegevens"><span class="header-section-number">10.3.3</span> De Pearson Chi-kwadraat test voor ongepaarde gegevens</h3>
<iframe width="560" height="315" src="https://www.youtube.com/embed/aDNU0ZBtpMs" frameborder="0" style="display: block; margin: auto;" allow="autoplay; encrypted-media" allowfullscreen="">
</iframe>
<p>We zullen een toets ontwikkelen voor het testen van associatie tussen de categorische blootstelling (bvb. variant, X) en de categorische uitkomst (bvb. ziekte, Y). Concreet zullen we</p>
<p><span class="math display">\[H_0: \text{Er is geen associatie tussen } X \text{ en } Y \text{ vs } H_1: X \text{ en } Y \text{ zijn geassocieerd}\]</span></p>
<p>testen.</p>
<p>Beschouw de rijtotalen <span class="math inline">\(n_\text{andere}=a+c\)</span>, <span class="math inline">\(n_\text{leu,leu}=b+d\)</span> enerzijds en de kolomtotalen <span class="math inline">\(n_\text{contr}=a+b\)</span> en <span class="math inline">\(n_\text{case}=c+d\)</span> anderzijds. Zij verstrekken informatie over de <em>marginale verdeling</em> van de blootstelling (bvb. variant, X) en de uitkomst (bvb. ziekte, Y), maar niet over de associatie tussen die veranderlijken. Als de nulhypothese waar is dat <span class="math inline">\(X\)</span> en <span class="math inline">\(Y\)</span> onafhankelijk zijn, dan verwacht men dat een proportie <span class="math inline">\((b+d)/n\)</span> van <span class="math inline">\(a+b\)</span> controles met een Leu/Leu variant, of dat <span class="math inline">\((a+b)(b+d)/n\)</span> een Leu/Leu variant hebben omdat een proportie <span class="math inline">\((b+d)/n\)</span> van alle geobserveerde individuen een Leu/Leu variant heeft. Analoog kan men op basis van de marginale gegevens het verwachte aantal berekenen dat onder de nulhypothese in <em>elke cel</em> van de <span class="math inline">\(2\times 2\)</span> tabel zou liggen. Dit verwachte aantal onder <span class="math inline">\(H_0\)</span> in de <span class="math inline">\((i,j)\)</span>-de cel (conditioneel op de marges van de tabel) wordt aangeduid met <span class="math inline">\(E_{ij}\)</span> en is het product van het <span class="math inline">\(i\)</span>-de rijtotaal met het <span class="math inline">\(j\)</span>-de kolomtotaal gedeeld door het algemene totaal. In bovenstaand voorbeeld vinden we</p>
<ul>
<li><p><span class="math inline">\(E_{11}\)</span> = het verwachte aantal onder <span class="math inline">\(H_0\)</span> in de (1,1)-cel = 145 <span class="math inline">\(\times\)</span> 800/1372 = 84.55 ;</p></li>
<li><p><span class="math inline">\(E_{12}\)</span> = het verwachte aantal onder <span class="math inline">\(H_0\)</span> in de (1,2)-cel = 145 <span class="math inline">\(\times\)</span> 572/1372 = 60.45 ;</p></li>
<li><p><span class="math inline">\(E_{21}\)</span> = het verwachte aantal onder <span class="math inline">\(H_0\)</span> in de (2,1)-cel = 1227 <span class="math inline">\(\times\)</span> 800/1372 = 715.5 ;</p></li>
<li><p><span class="math inline">\(E_{22}\)</span> = het verwachte aantal onder <span class="math inline">\(H_0\)</span> in de (2,2)-cel = 1227 <span class="math inline">\(\times\)</span> 572/1372 = 511.5 ;</p></li>
</ul>
<p>Een toets van de nulhypothese gebeurt nu op basis van een vergelijking tussen de geobserveerde aantallen in cellen <span class="math inline">\((i,j),\)</span> genoteerd met <span class="math inline">\(O_{ij}\)</span> en de verwachte aantallen <span class="math inline">\(E_{ij}\)</span>. In dat opzicht levert de toetsingsgrootheid</p>
<p><span class="math display">\[\begin{equation*}
X^2 = \frac{\left (|O_{11} - E_{11}| - .5 \right)^2 }{ E_{11}} + \frac{
\left ( |O_{12} - E_{12}| - .5 \right)^2 }{E_{12} }+ \frac{ \left ( |O_{21}
- E_{21}| - .5 \right)^2 }{E_{21}}+ \frac{ \left ( |O_{22} - E_{22}| - .5
\right)^2 }{E_{22} }
\end{equation*}\]</span></p>
<p>een goede discriminatie tussen de nulhypothese en de alternatieve hypothese. Men kan aantonen dat ze onder de nulhypothese bij benadering een zogenaamde <span class="math inline">\(\chi^2\)</span>-verdeling volgt met 1 vrijheidsgraad. Deze verdeling neemt uiteraard alleen positieve waarden aan en is scheef naar rechts verdeeld, behalve als het aantal vrijheidsgraden groot is (minstens 100), in welk geval ze meer symmetrisch wordt.</p>
<p>Figuur <a href="#fig-chidist" class="quarto-xref"><span>10.5</span></a> toont haar algemene vorm.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-chidist" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-chidist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="09-CategorischeDataAnalyse_files/figure-html/fig-chidist-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-chidist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figuur&nbsp;10.5: Dichtheidsfuncties voor enkele Chi-kwadraat verdelingen
</figcaption>
</figure>
</div>
</div>
</div>
<p>Een grote waarde van de toetsingsgrootheid geeft een indicatie van een afwijking van de nulhypothese. Concreet zal een toets op het <span class="math inline">\(\alpha 100\%\)</span> significantieniveau de nulhypothese verwerpen zodra de geobserveerde waarde van de toetsingsgrootheid het <span class="math inline">\(100\%(1-\alpha)\)</span>-percentiel, <span class="math inline">\(\chi^2_{1,
\alpha}\)</span>, van de <span class="math inline">\(\chi^2_1\)</span>-verdeling overschrijdt. Ze kan niet verwerpen in het andere geval. De p-waarde voor een 2-zijdige toets is in dit geval de kans om een grotere waarde voor de toetsingsgrootheid te observeren dan de geobserveerde waarde <span class="math inline">\(x^2\)</span> als de nulhypothese waar is. Dit is de kans dat een <span class="math inline">\(\chi^2_1\)</span>-verdeelde toevalsveranderlijke waarden groter dan <span class="math inline">\(x^2\)</span> aanneemt.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>expected <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="dv">0</span>, <span class="at">nrow =</span> <span class="dv">2</span>, <span class="at">ncol =</span> <span class="dv">2</span>)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>)</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> (j <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>)</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>        expected[i,j] <span class="ot">&lt;-</span> <span class="fu">sum</span>(brcaTab2[i,]) <span class="sc">*</span> <span class="fu">sum</span>(brcaTab2[,j]) <span class="sc">/</span> <span class="fu">sum</span>(brcaTab2)</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>expected</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         [,1]     [,2]
[1,]  84.5481  60.4519
[2,] 715.4519 511.5481</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>x2 <span class="ot">&lt;-</span> <span class="fu">sum</span>((<span class="fu">abs</span>(brcaTab2 <span class="sc">-</span> expected) <span class="sc">-</span> .<span class="dv">5</span>)<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> expected)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span><span class="sc">-</span><span class="fu">pchisq</span>(x2, <span class="dv">1</span>)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.481519</code></pre>
</div>
</div>
<p>Omdat de observaties <span class="math inline">\(O_{ij}\)</span> in feite discrete getallen zijn, kan de toetsingsgrootheid <span class="math inline">\(X^2\)</span> slechts discrete waarden aannemen en kan een continue verdeling zoals de <span class="math inline">\(\chi^2_1\)</span>-verdeling slechts een benadering zijn voor haar werkelijke verdeling. Om de discrete verdeling beter bij de continue <span class="math inline">\(\chi^2_1\)</span>-verdeling te doen aansluiten, heeft men in de uitdrukking van de toetsingsgrootheid voor elke cel telkens 0.5 afgetrokken. Dit wordt een <em>continuïteitscorrectie</em> genoemd. In dit geval gaat het om de correctie van Yates en noemt men deze toets dan ook de <em>Pearson Chi-kwadraat toets met Yates correctie</em>. Wanneer de correctie niet gebruikt wordt (d.w.z. wanneer de getallen `0.5’ in de uitdrukking voor <span class="math inline">\(X^2\)</span> door 0 vervangen worden), dan spreekt men van de <em>Pearson Chi-kwadraat toets</em>. In R kan je deze toetsen uitvoeren door de optie op TRUE of FALSE te zetten:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(brcaTab2)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test with Yates' continuity correction

data:  brcaTab2
X-squared = 0.49542, df = 1, p-value = 0.4815</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(brcaTab2, <span class="at">correct =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  brcaTab2
X-squared = 0.62871, df = 1, p-value = 0.4278</code></pre>
</div>
</div>
<p>Zelfs wanneer de continuïteitscorrectie wordt gebruikt, zal de <span class="math inline">\(\chi^2_1\)</span> benadering voor de verdeling van de toetsingsgrootheid slechts verantwoord zijn als in geen enkele van de cellen het verwachte aantal onder <span class="math inline">\(H_0\)</span> kleiner is dan 5. Wanneer de <span class="math inline">\(\chi^2\)</span>-benadering niet verantwoord is, kan men een <em>exacte toets</em> uitvoeren die rekening houdt met de echte mogelijke verdelingen van de marginale tellingen over de individuele cellen in de tabel. Dergelijke test maakt bijgevolg geen <span class="math inline">\(\chi^2\)</span>-benadering voor de verdeling van de toetsingsgrootheid onder de nulhypothese. De test die met de exacte verdeling van de marginale tellingen over de individuele cellen rekening houdt, wordt in de literatuur <em>Fisher’s exact test</em> genoemd. De nulhypothese van deze test is eveneens dat <span class="math inline">\(X\)</span> en <span class="math inline">\(Y\)</span> onafhankelijk zijn, en de alternatieve hypothese dat <span class="math inline">\(X\)</span> en <span class="math inline">\(Y\)</span> afhankelijk zijn. Een nadeel van de exacte test, is dat ze conservatief is (d.w.z. dat ze een kleinere kans hebben op een Type I fout dan vooropgesteld, en bijgevolg een grotere kans op Type II fouten). In R bekomt men deze test als volgt:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fisher.test</span>(brcaTab2)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Fisher's Exact Test for Count Data

data:  brcaTab2
p-value = 0.4764
alternative hypothesis: true odds ratio is not equal to 1
95 percent confidence interval:
 0.7998798 1.6738449
sample estimates:
odds ratio 
  1.153279 </code></pre>
</div>
</div>
<p>Merk op dat deze functie tevens 95% betrouwbaarheidsintervallen rapporteert voor de bijhorende odds ratio.</p>
<!---break-->
<section id="uitbreiding-naar-categorische-variabelen-met-meerdere-niveaus" class="level4" data-number="10.3.3.1">
<h4 data-number="10.3.3.1" class="anchored" data-anchor-id="uitbreiding-naar-categorische-variabelen-met-meerdere-niveaus"><span class="header-section-number">10.3.3.1</span> Uitbreiding naar categorische variabelen met meerdere niveaus</h4>
<iframe width="560" height="315" src="https://www.youtube.com/embed/4RyuL1qqan8" frameborder="0" style="display: block; margin: auto;" allow="autoplay; encrypted-media" allowfullscreen="">
</iframe>
<p>Als minstens 1 van de discrete variabelen <span class="math inline">\(X\)</span> en <span class="math inline">\(Y\)</span> meer dan 2 mogelijke waarden aanneemt, kan men nagaan of de kansverdeling van <span class="math inline">\(Y\)</span> afhangt van de <span class="math inline">\(X\)</span>-waarde in de populatie door een veralgemening van de <span class="math inline">\(\chi^2\)</span>-toets uit vorige sectie. Ook hier toetst men de nulhypothese <span class="math inline">\(H_0: X\)</span> en <span class="math inline">\(Y\)</span> zijn onafhankelijk, ten opzichte van het tweezijdig alternatief <span class="math inline">\(H_A: X\)</span> en <span class="math inline">\(Y\)</span> zijn niet onafhankelijk. Als de variabele voorgesteld op de rijen <span class="math inline">\(r\)</span> mogelijke uitkomsten heeft en die op de kolommen <span class="math inline">\(c\)</span> mogelijke uitkomsten, dan noemt men de kruistabel die <span class="math inline">\(X\)</span> tegenover <span class="math inline">\(Y\)</span> uitzet, een <span class="math inline">\(r \times c\)</span> tabel.</p>
<p>Zoals voorheen vergelijkt men het aantal geobserveerde waarden in cel <span class="math inline">\((i,j)\)</span>, <span class="math inline">\(O_{ij}\)</span> genoteerd, met het aantal verwachte waarden onder de nulhypothese in deze cel, <span class="math inline">\(E_{ij}\)</span> genoemd, op basis van de marginale totalen. Net als voorheen is <span class="math inline">\(E_{ij}\)</span> het product van het <span class="math inline">\(i\)</span>-de rijtotaal met het <span class="math inline">\(j\)</span>-de kolomtotaal gedeeld door het algemene totaal. De toetsingsgrootheid is nu</p>
<p><span class="math display">\[\begin{equation*}
X^2 = \sum_{ij} \frac{\left (O_{ij} - E_{ij}\right)^2 }{ E_{ij}}
\end{equation*}\]</span></p>
<p>Men kan aantonen dat ze een Chi-kwadraat verdeling volgt met <span class="math inline">\((r-1) \times
(c-1)\)</span> vrijheidsgraden als de nulhypothese waar is. De continuïteitscorrectie wordt meestal niet gebruikt bij meer dan 2 rijen of kolommen.</p>
<p>We voeren nu de test uit voor het BRCA voorbeeld waarbij we nu gebruik maken van alle varianten</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(brcaTab)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  brcaTab
X-squared = 2.0551, df = 2, p-value = 0.3579</code></pre>
</div>
</div>
<p>Om te onderzoeken of het BRCA1 gen geassocieerd is met borstkanker, berekenen we de Pearson chi-kwadraat toets voor de case-controle studie uit Tabel <a href="#tbl-leu3" class="quarto-xref"><span>10.2</span></a>. De toetsingsgrootheid bedraagt nu 2.055 en volgt een Chi-kwadraat verdeling met 2 vrijheidsgraden. De kans dat zo’n <span class="math inline">\(\chi^2\)</span>- verdeelde toevalsveranderlijke extremer is dan 2.055, bedraagt 36%. Op het 5% significantieniveau kunnen we dus niet besluiten dat het BRCA1 gen geassocieerd is met borstkanker.</p>
<p>De <strong>Pearson <span class="math inline">\(\chi^2\)</span> test</strong> wordt gebruikt om te toetsen of er een associatie is tussen 2 kwalitatieve (mogelijks niet binaire) variabelen, i.h.b. om te toetsen of de verdeling<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a> van de ene kwalitatieve variabele verschilt alnaargelang de waarde van de andere kwalitatieve variabele. Ze vereist dat de 2 metingen voor de 2 kwalitatieve variabelen telkens bekomen werden van onafhankelijke subjecten, en dat minstens 80% van de cellen in de overeenkomstige kruistabel een verwacht aantal observaties van minstens 5 bezitten. Op die manier vormt ze het analogon van de one-way variantie-analyse voor kwalitatieve i.p.v. continue variabelen.</p>
</section>
</section>
</section>
<section id="logistische-regressie" class="level2" data-number="10.4">
<h2 data-number="10.4" class="anchored" data-anchor-id="logistische-regressie"><span class="header-section-number">10.4</span> Logistische regressie</h2>
<iframe width="560" height="315" src="https://www.youtube.com/embed/LISLJCACdx8" frameborder="0" style="display: block; margin: auto;" allow="autoplay; encrypted-media" allowfullscreen="">
</iframe>
<p>In de statistische literatuur bestaat ook een raamwerk voor het modelleren van binaire data (vb. kanker vs geen kanker): <em>logistische regressie-modellen</em>. Net zoals we bij het regressiemodel voor Normale continue gegevens hebben gezien in Hoofdstuk <a href="06-LineareRegressie.html" class="quarto-xref"><span>7</span></a>, <a href="07-VariantieAnalyse.html" class="quarto-xref"><span>8</span></a> en <a href="10-GeneralLinearModel.html" class="quarto-xref"><span>11</span></a>, laten logistische regressie modellen toe om binaire gegevens te modelleren a.d.h.v. continue en/of dummy variabelen.</p>
<p>De modellen veronderstellen dat de observaties voor subject <span class="math inline">\(i=1,\ldots,n\)</span> onafhankelijk zijn en een Bernoulli verdeling volgen. Het logaritme van de odds wordt dan gemodelleerd d.m.v. een lineair model, ook wel lineaire predictor genoemd:</p>
<p><span class="math display">\[\begin{equation}
\left\{
\begin{array}{ccl}
Y_i&amp;\sim&amp;B(\pi_i)\\\\
\log \frac{\pi_i}{1-\pi_i}&amp;=&amp;\beta_0 + \beta_1X_{i1} + \ldots + \beta_p X_{ip}
\end{array}\right.
\end{equation}\]</span></p>
<section id="categorische-predictor" class="level3" data-number="10.4.1">
<h3 data-number="10.4.1" class="anchored" data-anchor-id="categorische-predictor"><span class="header-section-number">10.4.1</span> Categorische predictor</h3>
<p>We illustreren logistische regressie aan de hand van het borstkanker voorbeeld waar we bestuderen of de BRCA 1 variant geassocieerd is met het krijgen van borstkanker (zie Sectie <a href="#sec-catOnPaired" class="quarto-xref"><span>10.3.2</span></a>).</p>
<p>Net zoals in de anova context, kunnen we een factor in het regressieraamwerk introduceren door gebruik te maken van dummy variabelen. We zullen hierbij 1 dummy variable minder nodig hebben dan er groepen zijn.</p>
<p>Voor het BRCA 1 voorbeeld zijn dus twee dummy variabelen nodig en kunnen we de data dus modelleren met onderstaande lineaire predictor:</p>
<p><span class="math display">\[\begin{eqnarray*}
  \log \frac{\pi_i}{1-\pi_i} &amp;=&amp; \beta_0+\beta_1 x_{i1} +\beta_2 x_{i2}
\end{eqnarray*}\]</span></p>
<p>Waarbij de predictoren dummy-variabelen zijn:</p>
<p><span class="math display">\[x_{i1} = \left\{ \begin{array}{ll}
1 &amp; \text{ als subject $i$ heterozygoot is, Pro/Leu variant} \\
0 &amp; \text{ als subject $i$ homozygoot is, (Pro/Pro of Leu/Leu variant)} \end{array}\right. .\]</span></p>
<p>en</p>
<p><span class="math display">\[x_{i2} = \left\{ \begin{array}{ll}
1 &amp; \text{ als subject $i$ homozygoot is in de Leucine mutatie: Leu/Leu variant} \\
0 &amp; \text{ als subject $i$ niet homozygoot is in de Leu/Leu variant} \end{array}\right. .\]</span></p>
<p>Homozygositeit in het wild type allel Pro/Pro wordt voor dit model de <strong>referentiegroep</strong>.</p>
<p>Het model wordt als volgt in R gefit:</p>
<ul>
<li>Merk op dat we functie <code>as.factor</code> gebruiken om de cancer variabele om te zetten naar een factor.</li>
<li>en dat we de functie <code>relevel</code> gebruiken om de controles als referentie groep de definiëren: eerste niveau van de factor.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>brca <span class="ot">&lt;-</span> brca <span class="sc">|&gt;</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">cancer =</span> cancer <span class="sc">|&gt;</span></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>      <span class="fu">as.factor</span>() <span class="sc">|&gt;</span></span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>      <span class="fu">relevel</span>(<span class="st">"control"</span>),</span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">variant =</span> variant <span class="sc">|&gt;</span></span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a>      <span class="fu">as.factor</span>() <span class="sc">|&gt;</span></span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a>      <span class="fu">relevel</span>(<span class="st">"pro/pro"</span>)</span>
<span id="cb58-9"><a href="#cb58-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb58-10"><a href="#cb58-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-11"><a href="#cb58-11" aria-hidden="true" tabindex="-1"></a>brcaLogit <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb58-12"><a href="#cb58-12" aria-hidden="true" tabindex="-1"></a>  cancer <span class="sc">~</span> variant,</span>
<span id="cb58-13"><a href="#cb58-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> brca,</span>
<span id="cb58-14"><a href="#cb58-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> binomial)</span>
<span id="cb58-15"><a href="#cb58-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-16"><a href="#cb58-16" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(brcaLogit)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = cancer ~ variant, family = binomial, data = brca)

Coefficients:
               Estimate Std. Error z value Pr(&gt;|z|)   
(Intercept)     0.25131    0.08175   3.074  0.00211 **
variantleu/leu  0.21197    0.18915   1.121  0.26243   
variantpro/leu  0.13802    0.11573   1.193  0.23302   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 1863.9  on 1371  degrees of freedom
Residual deviance: 1861.9  on 1369  degrees of freedom
AIC: 1867.9

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>Het intercept is de log-odds op kanker in de referentieklasse (Pro/Pro) en de hellingstermen zijn log odds ratio’s tussen de behandeling en de referentieklasse:</p>
<p><span class="math display">\[\begin{eqnarray*}
\log \text{ODDS}_\text{Pro/Pro}&amp;=&amp;\beta_0\\\\
\log \text{ODDS}_\text{Pro/Leu}&amp;=&amp;\beta_0+\beta_1\\\\
\log \text{ODDS}_\text{Leu/Leu}&amp;=&amp;\beta_0+\beta_2\\\\
\log  \frac{\text{ODDS}_\text{Pro/Leu}}{\text{ODDS}_\text{Pro/Pro}}&amp;=&amp;\log \text{ODDS}_\text{Pro/Leu}-\log ODDS_{Pro/Pro}\\
&amp;=&amp;\beta_0+\beta_1-\beta_0=\beta_1\\\\
\log  \frac{\text{ODDS}_\text{Leu/Leu}}{\text{ODDS}_\text{Pro/Pro}}&amp;=&amp;\beta_2
\end{eqnarray*}\]</span></p>
<p>De analyse laat dus toe om de resultaten onmiddellijk te interpreteren in termen van Odds’es en Odds-ratio’s!</p>
<p>Net zoals bij een ANOVA analyse bij een continue response, kan de anova functie worden gebruikt voor het testen of er een associatie is tussen het voorkomen van kanker en de genetische variant.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(brcaLogit, <span class="at">test =</span> <span class="st">"Chisq"</span>)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model: binomial, link: logit

Response: cancer

Terms added sequentially (first to last)

        Df Deviance Resid. Df Resid. Dev Pr(&gt;Chi)
NULL                     1371     1863.9         
variant  2   2.0562      1369     1861.9   0.3577</code></pre>
</div>
</div>
<p>De <span class="math inline">\(\chi^2\)</span>-test in het logistische regressiemodel geeft eveneens aan dat er geen significante associatie is tussen de uitkomst (voorkomen van kanker) en de factor ( de genetische variant van het BRCA gen) (<span class="math inline">\(p=\)</span> 0.358). De p-waarde is bijna equivalent aan de p-waarde van de <span class="math inline">\(\chi^2\)</span>-test uit de vorige sectie.</p>
<p>Als er een significante associatie was geweest, dan hadden we post-hoc tests kunnen uitvoeren om te evalueren welke odds ratio’s verschillend zijn. Voor het BRCA1 voorbeeld zouden we uiteraard geen post-hoc testen uitvoeren omdat de globale <span class="math inline">\(\chi^2\)</span>-test voor het testen van associatie niet significant is. We illustreren de post-hoc analyse toch zodat jullie over de code beschikken voor het uitvoeren van de analyses.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(multcomp)</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>posthoc <span class="ot">&lt;-</span> <span class="fu">glht</span>(brcaLogit,</span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">linfct =</span> <span class="fu">mcp</span>(<span class="at">variant =</span> <span class="st">"Tukey"</span>))</span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a>posthocTests <span class="ot">&lt;-</span> <span class="fu">summary</span>(posthoc)</span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a>posthocTests</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     Simultaneous Tests for General Linear Hypotheses

Multiple Comparisons of Means: Tukey Contrasts


Fit: glm(formula = cancer ~ variant, family = binomial, data = brca)

Linear Hypotheses:
                       Estimate Std. Error z value Pr(&gt;|z|)
leu/leu - pro/pro == 0  0.21197    0.18915   1.121    0.493
pro/leu - pro/pro == 0  0.13802    0.11573   1.193    0.449
pro/leu - leu/leu == 0 -0.07395    0.18922  -0.391    0.917
(Adjusted p values reported -- single-step method)</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>posthocBI <span class="ot">&lt;-</span> <span class="fu">confint</span>(posthoc)</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>posthocBI</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     Simultaneous Confidence Intervals

Multiple Comparisons of Means: Tukey Contrasts


Fit: glm(formula = cancer ~ variant, family = binomial, data = brca)

Quantile = 2.324
95% family-wise confidence level
 

Linear Hypotheses:
                       Estimate lwr      upr     
leu/leu - pro/pro == 0  0.21197 -0.22760  0.65154
pro/leu - pro/pro == 0  0.13802 -0.13093  0.40697
pro/leu - leu/leu == 0 -0.07395 -0.51368  0.36578</code></pre>
</div>
</div>
<p>Door middel van de <code>confint</code> functie worden BI’s verkregen op de log-odds ratios die gecorrigeerd zijn voor multiple testing. Deze kunnen als volgt worden teruggetransformeerd naar odds ratios:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>OR <span class="ot">&lt;-</span> <span class="fu">exp</span>(posthocBI<span class="sc">$</span>confint)</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>OR</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   Estimate       lwr      upr
leu/leu - pro/pro 1.2361111 0.7964429 1.918494
pro/leu - pro/pro 1.1480000 0.8772785 1.502264
pro/leu - leu/leu 0.9287191 0.5982882 1.441645
attr(,"conf.level")
[1] 0.95
attr(,"calpha")
[1] 2.323964</code></pre>
</div>
</div>
<p>De odds ratios die worden bekomen met het logistisch regressiemodel zijn exact gelijk aan de odds ratios die we zouden bekomen op basis van Tabel <a href="#tbl-leu3" class="quarto-xref"><span>10.2</span></a>: vb. <span class="math inline">\(\text{OR}_\text{Leu/Leu-Pro/Pro}=89\times 266/(56\times 342)=\)</span> 1.236.</p>
<p>Merk op dat de statistische besluitvorming bij logistische modellen beroep doet op asymptotische theorie. Ze is dus enkel correct voor grote steekproeven.</p>
<!---break-->
</section>
<section id="continue-predictor" class="level3" data-number="10.4.2">
<h3 data-number="10.4.2" class="anchored" data-anchor-id="continue-predictor"><span class="header-section-number">10.4.2</span> Continue predictor</h3>
<iframe width="560" height="315" src="https://www.youtube.com/embed/iHYzyzOpJz4" frameborder="0" style="display: block; margin: auto;" allow="autoplay; encrypted-media" allowfullscreen="">
</iframe>
<p>Om het toxicologisch effect van een stof te kwantificeren worden dierproeven uitgevoerd waarbij dieren bij verschillende concentraties van de stof worden blootgesteld voor een bepaalde tijd. In dit voorbeeld wordt koolstofdisulfide (CS<span class="math inline">\(_2\)</span>) bestudeerd in proeven met kevers. De centrale onderzoeksvraag is of de concentratie van CS<span class="math inline">\(_2\)</span> een effect heeft op de mortaliteit (i.e.&nbsp;kans op sterven) van de kevers?</p>
<p><strong>Design</strong> In 32 onafhankelijk experimenten wordt een kever blootgesteld aan één van 8 concentraties (mg/l) van CS<span class="math inline">\(_2\)</span> voor een gegeven periode. De uitkomst van het experiment is: de kever sterft (<span class="math inline">\(y=1\)</span>) of de kever overleeft (<span class="math inline">\(y=0\)</span>). Een R object met de data is opgeslagen in de file <code>kevers.rda</code> in de dataset folder.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>beetles <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://raw.githubusercontent.com/statomics/sbc/master/data/beetles.csv"</span>)</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(beetles)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
   dose status
  &lt;dbl&gt;  &lt;dbl&gt;
1  169.      1
2  169.      0
3  169.      0
4  169.      0
5  172.      1
6  172.      0</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(beetles<span class="sc">$</span>dose, beetles<span class="sc">$</span>status)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        
         0 1
  169.07 3 1
  172.42 3 1
  175.52 3 1
  178.42 2 2
  181.13 1 3
  183.69 0 4
  186.1  0 4
  188.39 0 4</code></pre>
</div>
</div>
<p>We bouwen nu een logistisch regressiemodel waarbij we de log odds modelleren in functie van de dosis <span class="math inline">\(x_i\)</span>:</p>
<p><span class="math display">\[\log \frac{\pi_i}{1-\pi_i}=\beta_0+\beta_1 \times x_i.\]</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>beetleModel<span class="ot">&lt;-</span><span class="fu">glm</span>(</span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>  status<span class="sc">~</span>dose,</span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> beetles,</span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> binomial)</span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(beetleModel)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = status ~ dose, family = binomial, data = beetles)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)   
(Intercept) -53.1928    18.0046  -2.954  0.00313 **
dose          0.3013     0.1014   2.972  0.00296 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 42.340  on 31  degrees of freedom
Residual deviance: 26.796  on 30  degrees of freedom
AIC: 30.796

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
<p>Het intercept heeft als betekenis de log odds op mortaliteit wanneer er geen <span class="math inline">\(\text{CS}_2\)</span> gas wordt toegediend. Het duidt op een heel erg lage odds op sterfte (<span class="math inline">\(\pi/(1-\pi)=\exp(-53.2)\)</span>) en dus op een kans die nagenoeg nul is. We verwachten inderdaad dat de kevers niet zullen sterven als we geen gas gebruiken in het experiment. Merk op dat de interpretatie van het intercept echter wel op een heel sterke extrapolatie berust gezien de minimum dosis in de dataset 169.07 mg/l bedroeg.</p>
<p>De geschatte odds ratio voor het effect van dosis op de mortaliteitskans is <span class="math inline">\(\exp(0.3013)=1.35\)</span>. Dus bij een toename van de dosis CS<span class="math inline">\(_2\)</span> met 1 mg/l, is de odds ratio voor de mortaliteit <span class="math inline">\(1.35\)</span>. We besluiten dat dit effect heel significant is (<span class="math inline">\(p=\)</span> 0.003). Een toename in de CS<span class="math inline">\(_2\)</span> dosis doet de kans op sterven toenemen.</p>
<p>Figuur <a href="#fig-keversFit" class="quarto-xref"><span>10.6</span></a> toont de geschatte probabiliteit in functie van de dosis die werd gefit a.d.h.v. het regressiemodel. De figuur werd bekomen met onderstaande R code. We kunnen predicties voor nieuwe dosissen berekenen d.m.v. de <code>predict</code> functie. Het argument <code>type="response"</code> geeft aan dat we de predicties op de probabiliteitsschaal wensen. Wanneer we dat niet specifiëren genereert het model predictie op de log odds schaal.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>beetlesTab<span class="ot">&lt;-</span><span class="fu">table</span>(beetles) <span class="sc">|&gt;</span> <span class="fu">data.frame</span>()</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(</span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">grid =</span> <span class="fu">seq</span>(</span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a>      <span class="fu">min</span>(beetles<span class="sc">$</span>dose),</span>
<span id="cb74-6"><a href="#cb74-6" aria-hidden="true" tabindex="-1"></a>      <span class="fu">max</span>(beetles<span class="sc">$</span>dose),.<span class="dv">1</span>)</span>
<span id="cb74-7"><a href="#cb74-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb74-8"><a href="#cb74-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">piHat =</span> <span class="fu">predict</span>(beetleModel,</span>
<span id="cb74-9"><a href="#cb74-9" aria-hidden="true" tabindex="-1"></a>          <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">dose=</span>grid),</span>
<span id="cb74-10"><a href="#cb74-10" aria-hidden="true" tabindex="-1"></a>          <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb74-11"><a href="#cb74-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb74-12"><a href="#cb74-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(grid, piHat))<span class="sc">+</span></span>
<span id="cb74-13"><a href="#cb74-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb74-14"><a href="#cb74-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"dose"</span>) <span class="sc">+</span></span>
<span id="cb74-15"><a href="#cb74-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"probability (dead)"</span>) <span class="sc">+</span></span>
<span id="cb74-16"><a href="#cb74-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(</span>
<span id="cb74-17"><a href="#cb74-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> dose <span class="sc">|&gt;</span></span>
<span id="cb74-18"><a href="#cb74-18" aria-hidden="true" tabindex="-1"></a>          <span class="fu">as.character</span>() <span class="sc">|&gt;</span></span>
<span id="cb74-19"><a href="#cb74-19" aria-hidden="true" tabindex="-1"></a>          <span class="fu">as.double</span>(),</span>
<span id="cb74-20"><a href="#cb74-20" aria-hidden="true" tabindex="-1"></a>        <span class="at">y =</span> status <span class="sc">|&gt;</span></span>
<span id="cb74-21"><a href="#cb74-21" aria-hidden="true" tabindex="-1"></a>          <span class="fu">as.character</span>() <span class="sc">|&gt;</span></span>
<span id="cb74-22"><a href="#cb74-22" aria-hidden="true" tabindex="-1"></a>          <span class="fu">as.double</span>(),</span>
<span id="cb74-23"><a href="#cb74-23" aria-hidden="true" tabindex="-1"></a>        <span class="at">label =</span> Freq),</span>
<span id="cb74-24"><a href="#cb74-24" aria-hidden="true" tabindex="-1"></a>    beetlesTab <span class="sc">|&gt;</span></span>
<span id="cb74-25"><a href="#cb74-25" aria-hidden="true" tabindex="-1"></a>      <span class="fu">filter</span>(status<span class="sc">==</span><span class="dv">0</span>)</span>
<span id="cb74-26"><a href="#cb74-26" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb74-27"><a href="#cb74-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(</span>
<span id="cb74-28"><a href="#cb74-28" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> dose <span class="sc">|&gt;</span></span>
<span id="cb74-29"><a href="#cb74-29" aria-hidden="true" tabindex="-1"></a>          <span class="fu">as.character</span>() <span class="sc">|&gt;</span></span>
<span id="cb74-30"><a href="#cb74-30" aria-hidden="true" tabindex="-1"></a>          <span class="fu">as.double</span>(),</span>
<span id="cb74-31"><a href="#cb74-31" aria-hidden="true" tabindex="-1"></a>        <span class="at">y =</span> status <span class="sc">|&gt;</span></span>
<span id="cb74-32"><a href="#cb74-32" aria-hidden="true" tabindex="-1"></a>          <span class="fu">as.character</span>() <span class="sc">|&gt;</span></span>
<span id="cb74-33"><a href="#cb74-33" aria-hidden="true" tabindex="-1"></a>          <span class="fu">as.double</span>(),</span>
<span id="cb74-34"><a href="#cb74-34" aria-hidden="true" tabindex="-1"></a>       <span class="at">label=</span>Freq),</span>
<span id="cb74-35"><a href="#cb74-35" aria-hidden="true" tabindex="-1"></a>   beetlesTab <span class="sc">|&gt;</span></span>
<span id="cb74-36"><a href="#cb74-36" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(status<span class="sc">==</span><span class="dv">1</span>)</span>
<span id="cb74-37"><a href="#cb74-37" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-keversFit" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-keversFit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="09-CategorischeDataAnalyse_files/figure-html/fig-keversFit-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-keversFit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figuur&nbsp;10.6: Fit van het logistische regressiemodel voor de kevers data. Het aantal kevers die dood/levend was per dosis is weergegeven met een cijfer.
</figcaption>
</figure>
</div>
</div>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-Rogovin2017" class="csl-entry" role="listitem">
Rogovin, Konstantin A., Anastasiya M. Khrushchova, Olga N. Shekarova, Nina A. Vasilieva, en Nina Yu Vasilieva. 2017. <span>‘Females choose gentle, but not healthy or macho males in Campbell dwarf hamsters (Phodopus campbelli Thomas 1905)’</span>. <em>Current Zoology</em> 63 (5): 545-54. <a href="https://doi.org/10.1093/cz/zow090">https://doi.org/10.1093/cz/zow090</a>.
</div>
</div>
</section>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>Wees voorzichtig als je een binomiaalcoëfficient met een zakrekenmachine berekent. Teller en noemer kunnen snel zeer groot worden. Om (afrondings)fouten te vermijden moet men de uitdrukking eerst zoveel mogelijk vereenvoudigen.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Indien de partnerkeuze niet geassocieerd zou zijn met de omgeving, verwachten we dat deze kansen (<span class="math inline">\(\pi_1\)</span> en <span class="math inline">\(\pi_0\)</span>) gelijk zijn op populatieniveau. Als we een associatie verwachten, met name partnerkeuze wordt beïnvloed door omgeving, dan zouden we verwachten dat vele hamsters zouden “switchen” van partnervoorkeur als ze uit een andere omgeving komen. De observaties waarbij geswitch wordt van partner worden discordante paren genoemd<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Inderdaad, vermits de variantie onder de nulhypothese exact gekend is, moet er geen correctie worden uitgevoerd voor het schatten van de variantie en kunnen we de z-test gebruiken.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>heterozygoot Pro/Leu of homozygoot Pro/Pro<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>Indien de ene kwalitatieve variabele 2 waarden aanneemt, bvb, succes of faling, dan kan deze toets gebruikt worden om na te gaan of de kans op succes verschilt tussen strata van de andere kwalitatieve variabele.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Gekopieerd!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Gekopieerd!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./08-NietParametrischeStatistiek.html" class="pagination-link" aria-label="Niet-parametrische statistiek">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Niet-parametrische statistiek</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./10-GeneralLinearModel.html" class="pagination-link" aria-label="Algemeen lineair model">
        <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Algemeen lineair model</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/statOmics/statistiek2deBach/edit/main/09-CategorischeDataAnalyse.qmd" class="toc-action"><i class="bi bi-github"></i>Pagina bewerken</a></li></ul></div></div></div></footer></body></html>